// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: If your application isn't properly secured, external users might derive or inherit unauthorized privileges when they run it. Before you can run an application in production, you must carefully harden its configuration.
:seo-title: Application configuration security hardening
:seo-description: If your application isn't properly secured, external users might derive or inherit unauthorized privileges when they run it. Before you can run an application in production, you must carefully harden its configuration.
:page-layout: general-reference
:page-type: general
= Application configuration security hardening

If your application isn't properly secured, external users might derive or inherit unauthorized privileges when they run it.
This unauthorized access can lead to users with access to sensitive information about your application and other users.
Before you can run an application in production, you must carefully harden its configuration.

== User roles and access
Understanding the roles and mappings of users is key to securely configuring your application for production use.
For information about how to map users to roles and groups, see link:/docs/ref/general/#authorization.html[Authorization].

If you don't configure user roles in the `server.xml` file, Open Liberty uses the group names that a user is attached to as the role names for the user by default.
For conflicts in a servlet's role mapping between an application's `web.xml` file and annotations in the application, the config in the `web.xml` file takes precedence.
If there is a conflict between the `ibm-application-bnd.xmi` and `server.xml` files, then the config int he `server.xml` file takes precedence.

When the role mapping binding information for a protected application isn't provided, the group name and role name must be the same.
For example, if the role name is `manager`, then a user who belongs to a `manager` group has access to that resource.
This example applies only when application binding information isn't specified for the application in the `ibm-application-bnd.xmi` or `server.xml` files.

== Web server document root
WAR files contain application code and sensitive information.
Only some of that information is web-servable content, so the web server document root should not be set to the WAR root.
If the web server document root is set to the WAR root, the web server serves up all the contents of the WAR file without interpretation, which means that code, raw JSPs, and more are served to your users.

Avoid placing sensitive information in the WAR root.
The web container serves any files that are found in the root of the WAR file, which is okay if the root contains only servable content.
However, because the web container serves files from the WAR root, it must never contain any content that users shouldn't see, including property or class files.
If you must place such information in the WAR file, place it in the `WEB-INF` directory, as permitted by the servlet specification.
Information in this directory is never served by the web container.

== Secure servlets
Servlets can be served by class name or with a normal URL alias.
By default, Open Liberty does not allow you to serve servlets by class name.
Instead of defining a mapping for each servlet, a single generic URL (such as `/servlet`) serves all servlets.
The component of the path after the base is assumed to be the class name for the servlet.
For example, `/servlet/com.ibm.sample.MyServlet` refers to the `com.ibm.sample.MyServlet` servlet class.

You can serve servlets by class name by setting the `serveServletsByClassnameEnabled` property to `true` in the application's `ibm-web-ext.xmi` file.
For production purposes, don't enable this property.
Enabling the `serveServletsByClassnameEnabled` property makes it possible for anyone that knows the class name of any servlet to directly invoke it.

=== Servlet aliases

Servlets are secured by URL. Each URL that is to be secured must be specified in the web.xml file describing the application. If a servlet has more than one  alias (that is, multiple URLs access the same servlet class) or there are many servlets, it is easy to accidentally forget to secure an alias. Be cautious. Since Open Liberty secures URLs and not the underlying classes, if just one servlet URL is insecure, an intruder  might  be able to bypass security.  To alleviate this, use wildcards to secure servlets wherever possible. If that is not appropriate, carefully double check your web.xml file before deployment.

Make sure that when you  specify authorization constraints for servlets that you either  list no methods, or very carefully list (likely in multiple  constraints)ALL the methods for a servlet (GET, POST, PUT, HEAD, and so on). 

In the following secure example, endpoints in the web application are unreachable by default.
If a new servlet is added, you must add a security constraint for the new URL so that anyone can use it:

[source,xml]
----
<security-constraint>
  <web-resource-collection>
    <web-resource-name>DefaultDeny</web-resource-name>
    <url-pattern>/*</url-pattern>
  </web-resource-collection>
  <auth-constraint>
    <role-name>NoAccess</role-name>
  </auth-constraint>
</security-constraint>
.. or for Servlet 3.1 or higher, use the: <deny-uncovered-http-methods/> or <http-method-omission> elements
----

== Error handler
When errors occur in a web application, an error message is displayed to the user.
By default, Open Liberty displays a raw exception stack dump of the error.
Not only is this output unfriendly to users, but it also reveals information about the application, including names of classes and methods.

It is best to ensure that users never see a raw error message by defining a default error page that displays whenever an unhandled exception occurs.
This page can be a user-friendly error message rather than a stack trace.
The default error page is defined in the `ibm-web-ext.xmi` file by using the `defaultErrorPage` attribute.

== File serving and directory browsing
You can further limit the risk of serving inappropriate content by disabling file serving and directory browsing in your web applications.
Set the following property in the `ibm-web-ext.xmi` file:

[source,xml]
----
<enable-directory-browsing value="false" />
----

== Confidential transport guarantee
In order to ensure that applications will only run over secure HTTP connections (over TLS) specify transport guarantee of CONFIDENTIAL in the `web.xml` or `ibm-web-ext.xmi` files:

[source,xml]
----
<user-data-constraint>
  <transport-guarantee>CONFIDENTIAL</transport-guarantee>
</user-data-constraint>
----
