// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: You can choose among different options for packaging applications with Open Liberty. The simplest workflow for developing your cloud-native applications is to build applications with Maven or Gradle and containerize with Docker, before deploying them to the cloud with Kubernetes or OpenShift.
:seo-title: Application packaging for deployment - OpenLiberty.io
:seo-description: You can choose among different options for packaging applications with Open Liberty. The simplest workflow for developing your cloud-native applications is to build applications with Maven or Gradle and containerize with Docker, before deploying them to the cloud with Kubernetes or OpenShift.
:page-layout: general-reference
:page-type: general
= Application packaging for deployment

You can choose among different options for packaging applications with Open Liberty.
The simplest workflow for developing your cloud-native applications is to build applications with Maven or Gradle and containerize with Docker, before deploying them to the cloud with Kubernetes or OpenShift.

In this context, _packaging_ means bundling together an application with an Open Liberty server into a single compressed file.
You can decide how to package applications based on how you will eventually deploy them.

Open Liberty offers different packaging options, including packaging formats for containerization and server packages that are appropriate for more traditional setups.
If your goal is to deploy an application to link:https://kubernetes.io/[Kubernetes] or link:https://www.openshift.com/[OpenShift], <<package-container,package your application for containerization>>.
If you're working on a more traditional environment, you can create a <<server-package,server package>> that can be used to store, distribute, or deploy an application to a different location or to another machine.

== Maven and Gradle build tools
Maven and Gradle are build automation tools that make managing your builds and dependencies easier.
Both build tools help you download dependencies, build source code, run tests, and package applications.
The Open Liberty project provides Maven and Gradle plug-ins to help you develop and package applications with Open Liberty.

With link:https://maven.apache.org/[Maven], you use a `pom.xml` file to define information about your project.
To learn more about the Open Liberty Maven plug-in, check out the link:https://github.com/OpenLiberty/ci.maven[Open Liberty Maven plug-in documentation] and this guide on link:/guides/maven-intro.html[Building a web application with Maven].

link:https://gradle.org/[Gradle] uses a domain-specific language based on Groovy, and Gradle build scripts are made up of incremental tasks that form a program.
To learn more about the Open Liberty Gradle plug-in, check out the link:https://github.com/OpenLiberty/ci.gradle[Open Liberty Gradle plug-in documentation] and this guide on link:https://openliberty.io/guides/gradle-intro.html[Building a web application with Gradle].

== Building a WAR deployment artifact
Before you can package an application, you must build your application into a WAR deployment artifact.
You create this WAR file by specifying `war` as the packaging type in your `pom.xml` file or `build.gradle` file, as shown in the following example:

include::{common-includes}/maven-gradle-tabs.adoc[]

[.tab_content.maven-section]
--
In your `pom.xml` file:
[source,xml]
----
<packaging>war</packaging>
----
--

[.tab_content.gradle-section]
--
In your `build.gradle` file:
----
apply plugin: 'war'
----
--

After you use Maven or Gradle to generate this initial WAR file, you can package the application with Open Liberty into a server package for containerization or traditional deployment.
You also have the option of deploying the WAR file directly on Open Liberty.

[#server-package]
== Server packages
A server package is a compressed file that contains an Open Liberty runtime environment, the files in the shared resources directory, a specific server, and the applications that are embedded in the server.
You can also choose to exclude the runtime binary files from the compressed file.
Open Liberty supports `zip`, `jar`, `tar`, and `tar.gz` package types.

Different options can be specified with the `include` parameter or attribute to tailor a server package to meet your needs.
The `minify` option can be specified to create a package that only has the server config of the application.
The `runnable` option is used to package an application and Open Liberty into a link:/docs/ref/general/#runnablejarfiles.html[runnable JAR file].
The JAR file is portable and ready to deploy both the application and server together.
The `minify` option can be specified with the `runnable` option to package into a minimum runnable JAR file that contains only what you need to run your application.

For example, the following config packages the `myServer` server into a minimum runnable JAR file:

include::{common-includes}/maven-gradle-tabs.adoc[]

[.tab_content.maven-section]
--
In your `pom.xml` file:
[source,xml]
----
<plugin>
    <groupId>io.openliberty.tools</groupId>
    <artifactId>liberty-maven-plugin</artifactId>
    <executions>
        ...
        <execution>
            <id>package-server</id>
            <phase>package</phase>
            <goals>
                <goal>package</goal>
            </goals>
            <configuration>
                <packageName>test</packageName>
                <packageType>jar</packageType>
                <include>minify,runnable</include>
            </configuration>
        </execution>
        ...
    </executions>
    <configuration>
       <installDirectory>/opt/ibm/wlp</installDirectory>
       <serverName>myServer</serverName>
    </configuration>
</plugin>
----
--

[.tab_content.gradle-section]
--
In your `build.gradle` file:
----
apply plugin: 'liberty'

liberty {

    server {
        name = 'myServer'

        packageLiberty {
            packageName = "test"
            include = "minify,runnable"
        }
    }
}
----
--

After you configure your Maven or Gradle configurations with packaging specifications, you're ready to build the project.
For more information about Open Liberty packaging options with Maven, see the link:https://github.com/OpenLiberty/ci.maven/blob/master/docs/package.md#package[`package` goal in the Maven documentation].
For more information about Open Liberty packaging options with Gradle, see the link:https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyPackage.md#libertypackage-task[`libertyPackage` task in the Gradle documentation].

[#package-container]
== Packaging for containerization
If you're planning to containerize your application for cloud deployment, use Maven or Gradle to package it into a `tar.gz` file.
When you package your application, specify `usr` in the `include` parameter or attribute.
The `usr` option packages only relevant files in the `wlp.user.dir` directory, effectively excluding the runtime binary files from the compressed file.

For example, the following config packages the `myServer` server into a `tar.gz` file with `usr` contents:

include::/docs/ref/general/maven-gradle-tabs.adoc[]

[.tab_content.maven-section]
--
In your `pom.xml` file:
[source,xml]
----
<plugin>
    <groupId>io.openliberty.tools</groupId>
    <artifactId>liberty-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>package-server</id>
            <phase>package</phase>
            <goals>
                <goal>package</goal>
            </goals>
            <configuration>
                <packageName>test</packageName>
                <packageType>tar.gz</packageType>
                <include>usr</include>
            </configuration>
        </execution>
        ...
    </executions>
    <configuration>
       <installDirectory>/opt/ibm/wlp</installDirectory>
       <serverName>myServer</serverName>
    </configuration>
</plugin>
----
--

[.tab_content.gradle-section]
--
In your `build.gradle` file:
----
apply plugin: 'liberty'

liberty {

    server {
        name = 'myServer'

        packageLiberty {
            packageName = "test"
            packageType = "tar.gz"
            include = "usr"
        }
    }
}
----
--

After you package your application into a `tar.gz` file with `usr` contents and build it with Maven or Gradle, you can containerize it for cloud deployment.
Containerizing your server package bundles together the environment that your application needs to run.
With Docker containers, you have the portability to run your application on any machine that is running Docker.

A Docker image is a multi-layered file that serves as a template for a Docker container.
The simplest way to containerize your packaged application is by using the latest link:https://hub.docker.com/r/openliberty/open-liberty/[Open Liberty Docker images], which include the most recent feature versions and link:/docs/ref/general/#security-vulnerabilities.html[security fixes].

If you want to build your own Docker image, you need to create a link:https://docs.docker.com/engine/reference/builder/[Dockerfile].
A Dockerfile is a text file that contains commands about how an image is built.
If you choose to create your own Docker image, make sure to follow link:/docs/ref/general/#server-configuration-hardening.html[server configuration hardening best practices].
To learn more about running applications with Open Liberty Docker images, see this guide on link:/guides/containerize.html[Containerizing microservices].

== See also

* To learn how to update and deploy an application on Open Liberty with Maven and Docker, see this guide about link:https://openliberty.io/guides/getting-started.html[Getting started with Open Liberty].
* Have a Spring Boot application?
To learn how to containerize, package, and run a Spring Boot application on an Open Liberty server without modification, see the guide about link:https://openliberty.io/guides/spring-boot.html[Containerizing, packaging, and running a Spring Boot application].
* To learn the specifics of deploying to different cloud services, including AWS, AKS, and GCP, check out the link:https://openliberty.io/guides/?search=deploy[Open Liberty deployment guides].
