// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Configuring a basic user registry for application development
:seo-description: Open Liberty provides an easy-to-use basic user registry for developers.
:page-layout: general-reference
:page-type: general
= Configuring a basic user registry for application development

A user registry is a database that contains account information, such as usernames and passwords, that can be retrieved by applications to link:/docs/ref/general/#authentication.html[authenticate] and link:/docs/ref/general/#authorization.html[authorize] users and services.

Typically, microservice-based applications in production run on an application server that is configured to use an external registry, such as a Lightweight Directory Access Protocol (LDAP) registry. However, in test environments, a developer might want to set up a basic, file-based user registry within the application server to simplify security operations during the development process. Open Liberty provides an easy-to-use basic user registry for developers.

== The Application Security feature

The `appSecurity` feature provides the core capability for the Java EE Security API. This feature must be enabled in the `server.xml` file in order to configure a basic user registry. For more information, see link:/docs/ref/feature/#appSecurity-3.0.html[the Application Security feature].

== A basic user registry for test environments

Instead of being hosted externally, Open Liberty's basic user registry is configured directly in the `server.xml` file, or in an adjacent XML file on the server. Although this configuration is not secure enough for production environments, it can help simplify authentication and authorization scenarios during development and testing. The basic user registry provides a fast and easy way to test the access to your protected application.

To configure a basic registry, first add the `appSecurity` feature to the `server.xml` file. Then, configure a `basicRegistry` element either directly in the `server.xml` file or in a `userRegistry.xml` file, as shown in the following example. In this example, the user registry is configured to specify two users, Asha and Hiro, and their passwords. The registry also specifies one user group, admin, of which Asha is the only member.

[source, java]
----
<basicRegistry id="basic1" realm="SampleRealm">
     <user name="Asha" password="ashapwd" />
     <user name="Hiro" password="{xor}PD4tMy8oOw==" />
     <group name="admin">
       <member name="Asha" />
     </group>
</basicRegistry>
----

== QuickStart security with Open Liberty

Another option for configuring a basic user registry for development environments is to add the `quickStartSecurity` element to the `server.xml` file, as shown in the following example:

`<quickStartSecurity userName="Asha" userPassword="ashapwd"/>`

Adding this element automatically configures a registry with only one user (in this example, Asha) who is specified to be in the admin group. To use this element, the `appSecurity` feature must be configured in the `server.xml` file. No additional configuration is required.

The registry that is configured by this element is limited to a single user and is not sufficiently secure for production environments. However, it is useful in test scenarios, particularly for secured JMX connections that require an administrator to access.

== Hashing user passwords

To conceal the passwords in your basic user registry, use the hash option of the encode task on the `securityUtility` command, as shown in the following example:

`securityUtility encode --encoding=hash ashapwd`

This command can be used regardless of whether the registry is configured with the `basicRegistry` element or the `quickStartSecurity` element. For more information, see (link pending).


== Configure a basic user registry with Open Liberty

Ready to configure your own basic user registry with Open Liberty? Check out the link:/guides/security-intro.html#configuring-the-user-registry[Configuring the user registry] section of our guide to link:/guides/security-intro.html[Securing a web application].
