// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Configuring a basic user registry for application development
:seo-description: Open Liberty provides an easy-to-use basic user registry for developers.
:page-layout: general-reference
:page-type: general
= Basic user registries for application development

Open Liberty provides an easy-to-use basic user registry for development environments.

A user registry is a data source that contains account information, such as usernames and passwords. An application server can retrieve this information  to link:/docs/ref/general/#authentication.html[authenticate] and link:/docs/ref/general/#authorization.html[authorize] users.

Typically, microservice-based applications in production run on an application server that is configured to use an external user registry, such as a Lightweight Directory Access Protocol (LDAP) registry. However, in test environments, a developer might want to set up a basic, file-based user registry within the application server to simplify security operations during the development process.

== The Application Security feature

The `appSecurity-3.0` feature provides the core capability for the Java EE Security API. This feature must be enabled in the `server.xml` file to configure a basic user registry. For more information, see link:/docs/ref/feature/#appSecurity.html[the Application Security feature].

== A basic user registry for test environments

You can configure a basic user registry directly in the `server.xml` file. Although this registry is not secure enough for production environments, it can help simplify authentication and authorization scenarios during development and testing. The basic user registry provides a fast and easy way to test the access to your protected application.

For example, you can configure a basic user registry for your application that contains two users, their passwords, and one user group for the admin role. If you designate one of your two users as an admin, you can test access to your application resources for that role without having to connect to an external user registry. For configuration examples, see link:/docs/ref/feature/#appSecurity.html[the Application Security feature].

== QuickStart security

The simplest option for configuring a basic user registry is to enable QuickStart security. This option automatically configures a registry with only one user who is specified to be in the admin group. To use this element, the Application Security feature must be configured in the `server.xml` file. No additional configuration is required. The registry that is configured by this option is not sufficiently secure for production environments. However, it is useful in test scenarios, particularly for testing secured JMX connections that require administrator access. For configuration examples, see link:/docs/ref/feature/#appSecurity.html[the Application Security feature].

== User password security

To help keep your user registry secure, do not store user passwords in plain text. You can obfuscate the passwords in your basic user registry with the hash option of the encode action on the `securityUtility` command.
You can use this command regardless of whether the registry is configured with the `basicRegistry` element or the `quickStartSecurity` element. For more information, see link:/docs/ref/general/#securityUtility.html[the securityUtility command].

== Federation of basic registries

You can combine multiple basic user registries with each other, or with custom or LDAP registries, into a single federated registry. Federated registries provide a single logical view of multiple user registries and repositories. If multiple basic user registries are configured in your `server.xml` file, they are federated by default if you enable both the Application Security feature and the Federated User Registry feature. For more information, see link:/docs/ref/feature/#federatedRegistry-1.0.html[the Federated User Registry feature].

== Where to next

Ready to configure your own basic user registry with Open Liberty? Check out the link:/guides/security-intro.html#configuring-the-user-registry[Configuring the user registry] section of the guide to link:/guides/security-intro.html[Securing a web application].
