// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: You can enable sign-on (SSO) for HTTP requests by using Simple and Protected GSS-API Negotiation Mechanism (SPNEGO) web authentication for Open Liberty. With SPNEGO SSO, HTTP users log in only once to a Microsoft domain controller at their desktop.
:seo-title: Configuring SPNEGO authentication - OpenLiberty.io
:page-layout: general-reference
:page-type: general
= Configuring SPNEGO authentication

You can enable sign-on (SSO) for HTTP requests by using Simple and Protected GSS-API Negotiation Mechanism (SPNEGO) web authentication for Open Liberty.
With SPNEGO SSO, HTTP users log in only once to a Microsoft domain controller at their desktop.

link:https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/6.4/html/security_guide/about_spnego[SPNEGO] enables users to log in to applications by using their Microsoft Windows account login instead of using a separate account to log in to their Windows operating system.
SPNEGO can be used to provide SSO in an application if the organization uses Microsoft Active Directory.
SPNEGO can also be configured to work on Linux operating systems.
This task demonstrates how to configure an Open Liberty server to support SSO for HTTP requests by using SPNEGO.

== Prerequisites

To enable SPNEGO, the clocks for the client, Active Directory server, and Open Liberty server must be synchronized to within 5 minutes of each other.
This allowable difference in synchronization is configurable.

Before you begin, ensure that the following software is available:

- A Microsoft Windows Server running an Active Directory Domain Controller and associated Kerberos Key Distribution Center (KDC).
In this example, the hostname for the domain controller is `myAdMachine.example.com`, the domain controller name is `mydomain.example.com`, and the Kerberos realm name is `MYDOMAIN.EXAMPLE.COM`.
- A Microsoft Windows domain member (client).
In this example, the hostname for the client is `myClientMachine.example.com`.
- A server platform with an Open Liberty server that has an application with a protected resource.
Users in the Active Directory must be able to access Open Liberty server-protected resources by using a native Open Liberty server authentication mechanism, such as link:/docs/ref/feature/#socialLogin-1.0.html[Social Media Login].
In this example, the Open Liberty server hostname  is `myLibertyMachine.example.com`.

== Procedure

To configure SPNEGO, you complete the following items:

. Create a Kerberos service principal name and keytab file and copy the keytab file to Open Liberty.
. Create a Kerberos configuration file on Open Liberty, and configure the link:/docs/ref/feature/#spnego-1.0.html[SPENGO feature].
. Configure the browser client so users can access SPNEGO-protected resources from a browser.

=== Create a Kerberos service principal name and keytab file

. Create a user account for the Open Liberty server.
This account is used to map to the Kerberos service principal name (SPN).
On Active Directory machines, create this account by going to **Start > Administrative Tools > Active Directory Users and Computers**.
Then, right-click **Users** in the pane, and click **New > User**.
Ensure that you create the user account with password security.

. Run the Microsoft `setspn` command to map the user account to a Kerberos SPN.
This user account represents the Open Liberty server as a Kerberos service with the KDC.
The following example shows how to run the `setspn` command:
+
----
setspn -S HTTP/myLibertyMachine.example.com myLibertyMachine_http
----
+
The previous example command produces the following output:
+
----
Registering ServicePrincipalNames for CN=myLibertyMachine_http,CN=Users,DC=MYDOMAIN,DC=EXAMPLE,DC=COM
                 HTTP/myLibertyMachine.example.com
Updated object
----

. Create the Kerberos keytab file by running the Microsoft `ktpass` command.
The default name for the keytab file is `krb5.keytab`.
The following example shows how to run the `ktpass` command:
+
----
ktpass -out krb5.keytab -princ HTTP/myLibertyMachine.example.com@MYDOMAIN.EXAMPLE.COM -mapUser myLibertyMachine_http -mapOp set -pass security -crypto RC4-HMAC-NT -ptype KRB5_NT_PRINCIPAL
----
+
To verify that the command worked correctly and there isn't a duplicated SPN in the Microsoft forest, run the Microsoft `ldif` command:
+
----
ldifde -f check_SPN.txt -t 3268 -d "" -l servicePrincipalName -r "
(servicePrincipalName=HTTP/myLibertyMachine.example.com)" -p subtree
----
+
The following example output shows that one entry was returned, which indicates that there isn't a duplicated SPN:
+
----
Connecting to "myAdMachine.MYDOMAIN.EXAMPLE.COM"
Logging in as current user using SSPI
Exporting directory to file check_SPN.txt
Searching for entries...
Writing out entries.
1 entries exported
----

. If you have multiple SPNs, you need to merge your keytab files.
To merge the files, run the `ktpass` command with the `-in` option to include an existing keytab file with the newly created keytab file.
The following example includes the `myOtherKrb5.keytab` file:
+
----
ktpass -in myOtherKrb5.keytab -out krb5.keytab -princ HTTP/myLibertyMachine.example.com@MYDOMAIN.EXAMPLE.COM -mapUser myLibertyMachine_http -mapOp set -pass security -crypto RC4-HMAC-NT -ptype KRB5_NT_PRINCIPAL
----
+
The previous example command produces the following output:
+
----
Targeting domain controller: myAdMachine.MYDOMAIN.EXAMPLE.COM
Using legacy password setting method
Successfully mapped HTTP/myLibertyMachine.example.com to myLibertyMachine_http.
Key created.
Output keytab to krb5.keytab:
Keytab version: 0x502
keysize 93 HTTP/myLibertyMachine.example.com@MYDOMAIN.EXAMPLE.COM ptype 1 (KRB5_NT_PRINCIPAL) vno 3 etype 0x17 (RC4-HMAC) keylength 16 (0x148d643db283327d3f3d44547da8cade)
----

=== Copy the Kerberos keytab and configuration files and enable SPNEGO web authentication
. Copy the Kerberos keytab file from the domain controller to the Open Liberty server.
The default location of the file is the same directory as the Kerberos configuration file, which varies depending on the operating system:
* For Windows operating systems, the default location is `C:\windows\krb5.ini`.
* For Mac and Linux operating systems, the default location is `/etc/krb5.conf`.

. Create a Kerberos configuration file.
The Kerberos configuration file contains client configuration information.
This information includes the locations of KDCs for the realms of interest, defaults for the current Kerberos realm, and mappings of hostnames onto Kerberos realms.
+
Before you choose an encryption type, ensure that you have a common encryption type for the Kerberos configuration file, Kerberos keytab file, Kerberos SPN, and Kerberos client.
For example, if the Kerberos client uses the RC4-HMAC encryption type, the target server must support the RC4-HMAC encryption type.
The Kerberos configuration file must also list RC4-HMAC first in the `default_tgt_enctypes` and `default_tkt_enctypes` parameters.

. Verify the Kerberos configuration and keytab files.
To verify the Kerberos configuration and keytab files, use the `klist` and `kinit` commands.
.. Run the `klist` command to list the SPN in the keytab file:
+
----
klist -k -t /etc/krb5.keytab
----
.. Run the `kinit` command to validate the SPN in the keytab file and the Kerberos configuration file:
+
----
kinit -k -t /etc/krb5.keytab HTTP/myLibertyMachine.example.com
----
.. Run the `klist` command again to list the Kerberos ticket.
If you get the Kerberos ticket, then the Kerberos keytab and configuration files are valid.

. Configure and enable SPNEGO web authentication for Open Liberty.
You can enable SPNEGO web authentication by enabling the Simple and Protected GSSAPI Negotiation Mechanism (SPNEGO) feature.
For information about how to enable this feature and configuration examples, go to the link:/docs/ref/feature/#spnego-1.0.html[Open Liberty feature documentation].
+
The runtime forms the default SPN by using the fully qualified hostname.
If the default SPN doesn't match the SPN that's in the `krb5.keytab` file, then you need to specify the link:/docs/ref/config/#spnego.html[`servicePrincipalNames` attribute], for example:
+
----
<spnego id="mySpnego" servicePrincipalNames="HTTP/myLibertyMachine.example.com"/>
----
+
When values for the `krb5Config` or `krb5Keytab` attributes aren't provided, each file is expected to exist at its default location.
+
If you use the Oracle JDK or Java 11, add the `java.security.krb5.kdc` and `java.security.krb5.realm` JVM system properties to the `jvm.options` file, as shown in the following example:
+
----
-Djava.security.krb5.kdc=myKdcMachine.example.com
-Djava.security.krb5.realm=EXAMPLE.COM
----

=== Configure the client application on the client application machine

The following steps are for users who are accessing SPNEGO-protected resources from a browser and must be completed on the client machine.
Ensure that browser supports SPNEGO authentication and that the user is logged in to the domain controller.

==== Google Chrome on Windows

. Open the Control Panel and click **Internet Options**.
In the window that's displayed, click the **Security** tab.
. Select the **Local** intranet icon and click **Sites**.
. Click **Advanced** in the Local intranet window.
. Complete the **Add this website to the zone** field with the web address of the hostname so that SSO can be enabled for the list of websites that are shown in the websites field.
Close the second Local intranet window.
. Click **OK**, and close the Local intranet window.
. In the Internet Options window, click the **Advanced** tab and scroll to **Security** settings. Ensure that the **Enable Integrated Windows Authentication** box is selected.
. Click **OK**.
Restart Internet Explorer to activate this configuration.

==== Google Chrome on Mac or Linux

. Add the `--auth-server-whitelist` parameter to the `google-chrome` command.
For example, to configure SPNEGO for Chrome on Linux, run the following command:
+
----
google-chrome --auth-server-whitelist = "hostname/domain"
----
+
This command runs Chrome and sets the `--auth-server-whitelist` parameter so that SPNEGO can work in the browser.

==== Microsoft Internet Explorer

. Log in to the Active Directory domain.
. In an Internet Explorer window, click **Tools > Internet Options**.
In the window that's displayed, click the **Security** tab.
. Select the **Local** intranet icon and click **Sites**.
. Click **Advanced** in the Local intranet window.
. Complete the **Add this website to the zone** field with the web address of the hostname so that SSO can be enabled for the websites that are shown in the **websites** field.
Close the second Local intranet window.
. Click **OK**, and close the Local intranet window.
. In the Internet Options window, click the **Advanced** tab and scroll to **Security** settings. Ensure that the **Enable Integrated Windows Authentication** box is selected.
. Click **OK**.
Restart Internet Explorer to activate this configuration.

==== Mozilla Firefox

. Log in to the Active Directory domain.
. In the Firefox address field, type `about:config`.
. In the search box, type `network.n`.
. Double-click **network.negotiate-auth.trusted-uris**.
This preference lists the sites that are permitted to engage in SPNEGO authentication with the browser.
Enter a comma-delimited list of trusted domains or URLs.
. If your SPNEGO solution uses credential delegation, double-click **network.negotiate-auth.delegation-uris**.
This preference lists the sites for which the browser can delegate user authorization to the server.
Enter a comma-delimited list of trusted domains or URLs.
. Click **OK**.
Restart Firefox to activate this configuration.

== Results

After you configure SPNEGO authentication, you can deploy applications in your company that users must log in to only once.
To verify that SPNEGO is working, log in to the domain controller and access a protected resource on Open Liberty.
Because you are logged in to the domain controller, you aren't prompted for credentials.
If you aren't logged in to the domain controller and attempt to access a protected resource, you are prompted for credentials.
