// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Configuring SPNEGO authentication in Open Liberty
:seo-description:
:page-layout: general-reference
:page-type: general
= Configuring SPNEGO authentication in Open Liberty

You can enable sign-on (SSO) for HTTP requests by using Simple and Protected GSS-API Negotiation Mechanism (SPNEGO) web authentication for Open Liberty.
With SPNEGO SSO, HTTP users log in only once to a Microsoft domain controller at their desktop.

SPNEGO SSO is also known as Integrated Windows Authentication (IWA) for Windows platform.
Open Liberty supports SPNEGO for IWA but not for Kerberos and NT LAN Manager (NTLM).
The clocks for the client, Microsoft Active Directory server, and Open Liberty server must be synchronized to within 5 minutes of each other.
The allowable difference in synchronization is configurable.
The software configuration must have a running domain controller, at least one client machine in that domain and a server platform with an Open Liberty server that has a protected resource within an application, for a total of three required machines. Using SPNEGO directly from the domain controller is not supported.

Ensure that the following software is available:

- A Microsoft Windows Server running an Active Directory Domain Controller and associated Kerberos Key Distribution Center (KDC).
In this example, the host name for the domain controller is `myAdMachine.example.com`, the domain controller name is `mydomain.example.com`, and the Kerberos realm name is `MYDOMAIN.EXAMPLE.COM`.
- A Microsoft Windows domain member (client) that supports the SPNEGO authentication mechanism as defined in IETF RFC 2478.
Most modern browsers support SPNEGO authentication.
In this example, the host name for the client is `myClientMachine.example.com`.
- A server platform with an Open Liberty server that has an application with a protected resource.
Users in the Active Directory must be able to access Open Liberty server-protected resources by using a native Open Liberty server authentication mechanism.
In this example, the Open Liberty server host name  is `myLibertyMachine.example.com`.
