// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: You can configure an LDAP user registry to manage authentication and authorization for your applications that run on Open Liberty.
:page-layout: general-reference
:seo-title: Configuring an LDAP user registry for authentication and authorization
:seo-description: You can configure an LDAP user registry to manage authentication and authorization for your applications that run on Open Liberty.
:page-layout: general-reference
:page-type: general
= LDAP user registries for authentication and authorization

You can configure a Lightweight Directory Access Protocol (LDAP) user registry to help manage authentication and authorization for your applications that run on Open Liberty.

LDAP is an open protocol that supports authentication and authorization services. LDAP specifies the language that application servers use to communicate with the user registries that store security information such as usernames, passwords, and user groups. Although a link:/docs/ref/general/#csec-basic-registry.html[basic user registry] might be sufficient during development and testing of an application, an LDAP user registry provides the extra security that is required for applications in production.

You can configure Open Liberty to retrieve security information from an LDAP server if you are building an application that uses a preexisting user registry. LDAP is the industry standard for directory servers, providing a means to create, modify, search, and delete users and groups in your applications. There are many LDAP servers available, such as the link:https://www.ibm.com/support/knowledgecenter/SSVJJU_6.4.0/com.ibm.IBMDS.doc_6.4/c_po_SDS_overview.html[IBM Security Directory Server] and the Microsoft Active Directory. There are also open-source LDAP servers, such as link:http://www.openldap.org/[OpenLDAP] and link:http://directory.apache.org/apacheds/[ApacheDS].




== Federated LDAP registries

You can combine multiple user registries into a single federated registry to manage authentication and authorization. Federated registries provide a single logical view of multiple user registries and repositories.

In cases where user and group information is spread across multiple registries, federation enables Open Liberty to use this distributed user information in a unified manner with continuous store of information. Different types of registries can be federated to combine information from Lightweight Directory Access Protocol (LDAP), basic, and custom user registries and repositories into a common registry to manage application security. However, user registries that are configured with the quickStartSecurity element cannot be federated with other registries.


== LDAP registries and the Social Media Login feature
You can use Open Liberty's Social Media Login feature to help manage authentication with a configured LDAP registry. Depending how you configure the feature, users can either supply their social media credentials to authenticate to the LDAP registry or choose between their LDAP sign in and social media credentials for authentication. For more information, see the example configurations for the link:/docs/ref/feature/#socialLogin-1.0.html[Social Media Login feature].

== LDAP registry configuration

To use an existing LDAP server as a user registry, first add the link:/docs/ref/feature/#appSecurity-3.0.html[Application Security] and link:/docs/ref/feature/#ldapRegistry-3.0.html[LDAP User Registry] features to your `server.xml` file. If you need to communicate with a TSL-enabled LDAP server, you must also add the link:/docs/ref/feature/#transportSecurity-1.0.html[Transport Security] feature.

For a full list of configuration elements and attributes, see the link:/docs/ref/config/#ldapRegistry.html[LDAP User Registry configuration].
