// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Defines default port numbers of Open Liberty features and an example of how you can override the default port in your server configuration.
:seo-description: Defines default port numbers of Open Liberty features and an example of how you can override the default port in your server configuration.
:page-layout: general-reference
:page-type: general
= Default port numbers

Some parts of Open Liberty use default TCP/IP port numbers.
You can override the default port numbers by specifying a different port number in your server configuration.

== Runtime environment port numbers

For the command port, the Open Liberty server acquires an ephemeral port to be used by the command listener.
You can configure this port in the `bootstrap.properties` file. For more information, see link:https://openliberty.io//ref/config/serverConfiguration.html[Server Configuration].


The following table defines default port numbers of Open Liberty features and an example of how you can override the default port in your server configuration.

[cols="a,a",width="100%"]
|===
|Feature|Default port and configuration example

|link:/docs/ref/feature/#ejbRemote-3.2.html[Enterprise JavaBeans Remote]

| . IIOP port: 2809
  . IIOP/SSL port: 9402
----
<iiopEndpoint id="defaultIiopEndpoint" iiopPort="2809">
     <iiopsOptions iiopsPort="9402" sslRef="defaultSSLConfig"/>
</iiopEndpoint>
----

|link:/docs/ref/feature/#servlet-4.0.html[Java Servlets]

| . HTTP port: 9080
  . HTTPS port: 9443

----
<httpEndpoint id="defaultHttpEndpoint"
    httpPort="9082"
    httpsPort="9445" />
----
For more information about HTTP endpoints, see link:/docs/ref/config/#httpEndpoint.html[HTTP Endpoint (httpEndpoint)]

 |link:/docs/ref/feature/#sipServlet-1.1.html[SIP Servlet]

 | . TCP port: 5060
   . TLS port: 5061
   . UDP port: 5060

----
 <sipEndpoint id="defaultSipEndpoint"
    sipTCPPort="5062"
    sipUDPPort="5062"
    sipTLSPort="5063" />
----

  |link:/docs/ref/feature/#wasJmsServer-1.0.html[Message Server]

  | . Incoming unsecure port: 7276
    . Incoming secure port: 7286

----
<wasJmsEndpoint id="InboundJmsEndpoint"
   wasJmsPort="7278"
   wasJmsSSLPort="7288">
</wasJmsEndpoint>
----
For more information about WAS JMS endpoints, see link:/docs/ref/config/#wasJmsEndpoint.html[WAS JMS Endpoint (wasJmsEndpoint)].
