// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: OpenShift is a Kubernetes-based application platform. After you write your applications, you can containerize and deploy them to OpenShift to orchestrate and automate your containers.
:seo-description: OpenShift is a Kubernetes-based application platform. After you write your applications, you can containerize and deploy them to OpenShift to orchestrate and automate your containers.
:page-layout: general-reference
:page-type: general
= Deploying Open Liberty applications on OpenShift

link:https://www.openshift.com/[OpenShift] is a Kubernetes-based application platform.
After you write an application, you can use OpenShift to build, containerize, and deploy your application so that it's highly available and scalable.
You can use the Open Liberty Operator to simplify deploying and managing your applications in the cloud.

== What is OpenShift?
OpenShift is a Kubernetes-based application platform for container orchestration.
After you develop and containerize your applications, your containers need to communicate with each other and scale as each service is needed.
OpenShift provides features that automate and manage containers to meet the needs of developers and ops teams.

OpenShift takes the upstream Kubernetes project and adds fixes and helpful tooling.
It's also thoroughly tested before every release.
These additions support enterprise applications, and you can have peace of mind knowing that your application platform was thoroughly tested and debugged.

== Running applications on OpenShift
One of the benefits of running your applications on OpenShift is that you can deploy them to a cloud-hosted IaaS, or to your current on-premises structure.
You can use the link:https://docs.openshift.com/online/starter/cli_reference/openshift_cli/getting-started-cli.html[OpenShift CLI] or link:https://docs.openshift.com/online/starter/cli_reference/openshift_developer_cli/understanding-odo.html[OpenShift Do CLI] to develop your application.
Then, containerize your application in Open Liberty containers and deploy them to an OpenShift cluster.

For a step-by-step tutorial on deploying to OpenShift, see the link:https://openliberty.io/guides/cloud-openshift.html[Deploying microservices to OpenShift guide]. For more information about different OpenShift deployment options, see the link:https://www.openshift.com/learn/topics/deploy[OpenShift documentation].

== Open Liberty Operator
Operators are extensions to Kubernetes that are customized to automate tasks beyond the initial automation that Kubernetes or OpenShift provide.
The Open Liberty Operator is a Level 5 Operator, which means that it has the highest level of enterprise capabilities.
This Operator offers production-grade capabilities, including simple configuration of persistent or advanced storage and the ability to delegate single-sign on (SSO) to external providers.
It also automates updates of binding information among applications, meaning that it connects applications and maintains information about whether a particular application produces or consumes a service.

Kubernetes Operators use the link:https://github.com/operator-framework[Operator framework] and can be used on Kubernetes or OpenShift.
The Open Liberty Operator is available for installation from link:https://operatorhub.io/operator/open-liberty[OperatorHub].
You can also find it available as a Red Hat certified Operator from link:https://access.redhat.com/containers/#/registry.connect.redhat.com/ibm/open-liberty-operator[OpenShift Container Platform (OCP)].
For more information about Operators, see the link:https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Kubernetes documentation].

== See also
* To learn how to deploy microservices in Open Liberty Docker containers to Kubernetes and manage them with the Kubernetes CLI, see the link:https://openliberty.io/guides/kubernetes-intro.html[Deploying microservices to Kubernetes guide].

// Ready to find out more about the Open Liberty Operator?

// * For more information about installing and configuring the Open Liberty Operator, see ___.
// * For information about troubleshooting the Open Liberty Operator, see ___.
// * For information about integrating different observability and monitoring tools with the Open Liberty Operator, see ___.
