// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: When you run Open Liberty in development mode, you can rapidly code, deploy, test, and debug applications directly in your IDE or text editor.
:seo-title: Development mode
:seo-description: When you run Open Liberty in development mode, you can rapidly code, deploy, test, and debug applications directly in your IDE or text editor.
:page-layout: general-reference
:page-type: general
= Development mode

When you run Open Liberty in development mode (dev mode), you can rapidly code, deploy, test, and debug applications directly from your integrated development environment (IDE) or text editor.

With dev mode, you can quickly iterate on changes to your code and get immediate feedback from on-demand or automatic unit and integration tests. You can also attach a debugger to step through your code at any time.
Dev mode is available as a goal of link:https://github.com/OpenLiberty/ci.maven[the Open Liberty Maven plug-in] or as a task of https://github.com/OpenLiberty/ci.gradle[the Liberty Gradle plug-in].
It integrates a set of capabilities for Open Liberty so that you can edit and monitor your application in real time, without restarting your running server.
Dev mode addresses three primary focus areas: deploying changes, running tests, and debugging.

== Run Open Liberty in dev mode

You can use dev mode through either the Open Liberty Maven plug-in or the Open Liberty Gradle plug-in. To use dev mode, link:https://github.com/OpenLiberty/ci.maven#configuration[enable the Open Liberty Maven plug-in] or link:https://github.com/OpenLiberty/ci.gradle#usage[the Open Liberty Gradle plug-in] and run one of the following commands:

Maven: `mvn liberty:dev`
Gradle: `gradle libertyDev`

=== Detect, recompile, and deploy code changes

Dev mode can automatically detect, recompile, and deploy code changes whenever you save a new change in your IDE or text editor. Dev mode automatically detects the following changes to your application source:

- Java source file and test file changes
- Resource file changes
- Configuration directory and configuration file changes
- New dependency additions to your `pom.xml` file for Maven users or `build.gradle` file for Gradle users
- New feature additions in the Open Liberty server configuration

Resource file, configuration file, and configuration directory changes are copied into your target directory.
New dependencies in your `pom.xml` file or `build.gradle` file are added to your class path.
New features are installed and started.

Some changes, such as adding certain configuration directories or files, do not take effect until you restart dev mode.
To enable these changes, restart dev mode when prompted.
To restart, first exit dev mode by pressing `CTRL+C`, or by typing `q` and pressing `Enter`.
Then, run the `mvn liberty:dev` command or the `gradle libertyDev` command to restart.
After the server restarts, the changes are detected, recompiled, and picked up by the running server.

You can configure how dev mode handles changes to your code by specifying parameters when you start dev mode.
For more information about configuration parameters, see link:https://github.com/OpenLiberty/ci.maven/blob/master/docs/dev.md#dev[the dev goal of the Open Liberty Maven plug-in] or link:https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyDev.md#libertydev-task[the libertyDev task of the Open Liberty Gradle plug-in].

=== Run unit and integration tests on demand

You can run unit and integration tests on demand by pressing `Enter` in the command window where dev mode is running.
Dev mode runs the unit tests and integration tests that are configured for your project.
If you add a test to your project, it is compiled and included the next time that you run tests.

You can get immediate feedback on your changes by configuring dev mode to run hot tests.
Hot tests are unit or integration tests that run automatically whenever you start dev mode or make a code change.
To configure hot testing, specify the hot test parameter when you start dev mode, as shown in the following examples:

Maven: `mvn liberty:dev -DhotTests`

Gradle: `gradle libertyDev --hotTests`

You can also add parameters to specify whether to skip tests.
For Maven, you can add parameters to skip unit tests, skip integration tests, or skip all tests. For Gradle, you can add a parameter to skip all tests.
For more information about configuration parameters, see link:https://github.com/OpenLiberty/ci.maven/blob/master/docs/dev.md#dev[the dev goal of the Open Liberty Maven plug-in] or link:https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyDev.md#libertydev-task[the libertyDev task of the Open Liberty Gradle plug-in].

=== Attach a debugger to the running server

You can attach a debugger to the running server to step through your code at any time.
You can specify breakpoints in your source code to locally debug different parts of your application.
The default port for debugging is `7777`.
If the default port is not available, dev mode selects a random port to use as the debug port.

=== VS Code extension for dev mode

With the link:https://marketplace.visualstudio.com/items?itemName=Open-Liberty.liberty-dev-vscode-ext[Open Liberty Tools VS Code extension], you can start dev mode, make dynamic code changes, run tests, and debug your application, all without leaving the VS Code editor.
After you install the extension and enable either the Maven or Gradle plug-in, you can select your project under the Liberty Dev Dashboard in the VS Code side bar.
You can access dev mode functions by right-clicking your project name and selecting a command from the menu.


== Where to go next

- Try out dev mode for yourself with link:https://github.com/OpenLiberty/demo-devmode[the demo-devmode sample project] and the guide to link:/guides/getting-started.html[Packaging and deploying applications].

== See also

- View command examples, explanations of available dev mode parameters, and more in link:https://github.com/OpenLiberty/ci.maven/blob/master/docs/dev.md#dev[the dev goal of the Open Liberty Maven plug-in] and link:https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyDev.md#libertydev-task[the libertyDev task of the Open Liberty Gradle plug-in].
