//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The `featureUtility viewSettings` command allows you to view repository and proxy settings.
:seo-title: featureUtility viewSettings - OpenLiberty.io
:seo-description: The `featureUtility viewSettings` command allows you to view repository and proxy settings.
:page-layout: general-reference
:page-type: general
= featureUtility viewSettings

The `featureUtility viewSettings` command allows you to view repository and proxy settings.
When you run the command, it displays the parsed properties from the `featureUtility.properties` file.

== Usage example

Display detailed error messages for the validation of your `featureUtility.properties` file:

----
featureUtility viewSettings --viewValidationMessages
----

== Syntax

Run the command from the `path_to_liberty/bin` directory.

----
featureUtility viewSettings [option]
----

option::
One optional parameter.

== Option

[%header,cols=2*]
|===
|Option
|Description

|--viewValidationMessages
|Displays detailed messages from the validation of the configured `featureUtility.properties` file.
Each message contains an error code, the line number where the error was found, and the cause of the error.

|===
