//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The `featureUtility installFeature` command install features. You can install either a single feature or a list of space-separated features.
:seo-title: featureUtility installFeature - OpenLiberty.io
:seo-description: The `featureUtility installFeature` command install features. You can install either a single feature or a list of space-separated features.
:page-layout: general-reference
:page-type: general
= featureUtility installFeature

The `featureUtility installFeature` command install features.
You can install either a single feature or a list of space-separated features.

== Usage examples

Install the link:/docs/ref/feature/#mpHealth-2.2.html[MicroProfile Health 2.2 feature] from Maven Central:

----
featureUtility installFeature mpHealth-2.2
----

Install the MicroProfile Health 2.2 feature without caching the feature to the local Maven repository:

----
featureUtility installFeature mpHealth-2.2 --noCache
----

Install the link:https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.liberty.autogen.base.doc/ae/rwlp_feature_adminCenter-1.0.html[Admin Center feature] from Maven Central:

----
featureUtility installFeature adminCenter-1.0 --acceptLicense
----

== Syntax

Run the command from the `path_to_liberty/bin` directory.

----
featureUtility installFeature [options]
----

options::
One or more optional parameters.

== Options

[%header,cols=2*]
|===
|Option
|Description

|--acceptLicense
|Accepts the license agreement.

|featureName
|One or more features that are separated by a space.
Specify the feature shortname or the Maven coordinate.
If you specify a Maven coordinate, it must contain the group ID and the artifact ID, for example, `io.openliberty.features:mpHealth-2.0`.
{empty} +
{empty} +
If the version and packaging type aren't specified, the version defaults to the current runtime version and the packaging type defaults to ESA.

|--noCache
|Specifies that features installed from a remote repository, such as Maven Central, aren't cached locally.

|--verbose
|Displays additional debug information while the action runs.

|===
