//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: featureUtility command
:seo-description:
:page-layout: general-reference
:page-type: general
= featureUtility command


== Usage examples



== Syntax

Run the command from the `path_to_liberty/bin` directory.

----
featureUtility action [options]
----

action::
The action that the command performs.

options::
One or more optional parameters that you can specify to modify an action.
Options differ based on the value of *action*.

== Actions and options

=== installFeature

This action installs features.
You can install a single feature or a list of space-separated features.

The following options are available for the *installFeature* action:

[%header,cols=2*]
|===
|Option
|Description

|--acceptLicense
|Accepts the license agreement.

a|_name_
|One or more features that are separated by a space.
Specify the feature shortname or the Maven coordinate.
If you specify a Maven coordinate, it must contain the group ID and the artifact ID, for example, `io.openliberty.features:mpHealth-2.0`.
{empty} +
{empty} +
If the version and packaging type aren't specified, the version defaults to the current runtime version and the packaging type defaults to ESA.

|--noCache
|Specifies that features installed from a remote repository, for example, Maven Central, aren't cached locally.

|--verbose
|Displays additional debug information while the action runs.

|===

=== installServerFeature

This action installs the required features for a specified server.

The following options are available for the *installServerFeature* action:

[%header,cols=2*]
|===
|Option
|Description

|--acceptLicense
|Accepts the license agreement.

a|_name_
|The name of an existing server in the same Open Liberty environment.

|--noCache
|Specifies that features installed from a remote repository, for example, Maven Central, aren't cached locally.

|--verbose
|Displays additional debug information while the action runs.

|===

=== find

This action finds features in the repositories that are applicable to your configuration and allows you to view detailed information about features.

The following options are available for the *find* action:

[%header,cols=2*]
|===
|Option
|Description

a|_name_
|One or more features that are separated by a space.
Specify the feature shortname or the Maven coordinate.
If you specify a Maven coordinate, it must contain the group ID and the artifact ID, for example, `io.openliberty.features:mpHealth-2.0`.
{empty} +
{empty} +
If the version and packaging type aren't specified, the version defaults to the current runtime version and the packaging type defaults to ESA.

|===

=== viewSettings

This action allows you to view the repositories and proxy settings.

The following options are available for the *viewSettings* action:

[%header,cols=2*]
|===
|Option
|Description

|--viewvalidationmessages
|Displays detailed messages from the validation of the configured `featureUtility.properties` file.
Each message contains an error code, the line number where the error was found, and the cause of the error.

|===

=== help

This action displays help information for a specified action.

The following options are available for the *help* action:

[%header,cols=2*]
|===
|Option
|Description

a|_name_
a|The name of the `featureUtility` *action* for which you need help information.

|===

== Environment variables

You can specify environment variables to modify the behavior of the `featureUtility` command.
Environment variables can be specified in the shell environment or as properties in the `featureUtility.properties` file that's located in the `{wlp.install.dir}/etc/` directory.
Environment variables that are specified in the `featureUtility.properties` file take precedence over environment variables with the same name that are specified in the shell environment.

You can override Maven Central as your Maven repository by defining an on-premises Maven repository with the `mavenCentralMirror.url` property in the `featureUtility.properties` file.
Then, set the `mavenCentralMirror.user` and `mavenCentralMirror.password` properties if the repository requires a user name and password.

You can also define additional remote repositories by adding the `customRepoName.url` property in the `featureUtility.properties` file.
Each repository name must be unique, and defined repositories are accessed in the order that they're specified.
If a repository requires a user name and password, also set the `customRepoName.user` and `customRepoName.password` properties.
In the following example, two custom repositories, `remoteRepo1` and `remoteRepo2`, are defined.
`remoteRepo2` is secure and also requires a user name and password:

----
remoteRepo1.url=http://my-remote-server1/maven2
remoteRepo2.url=https://my-remote-server2/secure/maven2
remoteRepo2.user=operator
remoteRepo2.password={aes}KM8dhwcv892Ss1sawu9R+
----

The following table lists the environment variables that you can specify to modify the `featureUtility` command:

[%header,cols=2*]
|===
|Environment variable
|Description

|`FEATURE_REPO_URL`
|Overrides Maven Central with an on-premises Maven repository.
{empty} +
{empty} +
The `mavenCentralMirror.url` property overrides this environment variable.

|`FEATURE_REPO_USER`
|The username for `FEATURE_REPO_URL` user credentials.
{empty} +
{empty} +
The `mavenCentralMirror.user` property overrides this environment variable.

|`FEATURE_REPO_PASSWORD`
|The password for `FEATURE_REPO_URL` user credentials.
{empty} +
{empty} +
The `mavenCentralMirror.password` property overrides this environment variable.

|`FEATURE_LOCAL_REPO`
|Overrides the local Maven repository.
{empty} +
{empty} +
The `featureLocalRepo` property overrides this environment variable. For example,
if you specify `featureLocalRepo=/usr/IBM/maven/repository` in the `featureUtility.properties` file, then any value set with the `FEATURE_LOCAL_REPO` environment variable is overriden.

|`http_proxy`
a|Configures the outbound HTTP proxy, for example, `http_proxy=http://server:port`.
{empty} +
{empty} +
The `proxyHost`, `proxyPort`, `proxyUser`, and `proxyPassword` properties override this environment variable.
For example, including the following example properties in the `featureUtility.properties` file overrides any value set with the `http_proxy` environment variable:

* `proxyHost=my.proxy.server.ibm.com`
* `proxyPort=9080`
* `proxyUser=admin`
* `proxyPassword={aes}AH5NLyd7DfGb12pK17Pw+`

|`https_proxy`
a|Configures the outbound HTTPS proxy, for example, `https_proxy=https://server:port`.
{empty} +
{empty} +
The `proxyHost`, `proxyPort`, `proxyUser`, and `proxyPassword` properties override this environment variable.
For example, including the following example properties in the `featureUtility.properties` file overrides any value set with the `https_proxy` environment variable:

* `proxyHost=my.proxy.server.ibm.com`
* `proxyPort=9080`
* `proxyUser=admin`
* `proxyPassword={aes}AH5NLyd7DfGb12pK17Pw+`

|===
