// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Hardening Open Liberty servers in production - openliberty.io
:seo-description:
:page-layout: general-reference
:page-type: general
= Hardening Open Liberty servers in production

//What is hardening? Why do I need to harden my Open Liberty server?
Hardening is a general term that is used to describe the measures that are taken to enhance your system security against potential threats and risks. It is important to harden your Open Liberty server to prevent against different types of intrusions and vulnerabilities that can occur. Security intrusions and vulnerabilities can be broken down into different groups:

* <<#operating-system,Operating system>>
* <<#network,Network>>
* <<#application-configuration,Application configuration>>

[#operating-system]
== Operating system
Operating system intrusions occur when users with local access attempt to cause damage or extract sensitive information. One example of this intrusion is if malware was introduced into your operating system, allowing unauthorized access to the operating system and its contents. It's important to keep your version of Open Liberty up to date. Open Liberty fix packs are upward compatible, and the zero migration policy allows you to move to a newer fix pack without changing anything in your server configuration. Ensuring that you have a recent version of Open Liberty positions you for link:/docs/ref/general/#security-vulnerabilities.html[critical security fixes].

=== Best practices
Basic and Quick Start Security user registries are useful for development environments, but they are not acceptable for readiness testing, QA, or production use. Instead, use an LDAP user registry, federated repositories, or create a custom user registry. If you use an LDAP user registry, maintain your bind password in a separate `include` file, not in the `server.xml` file. If you use federated repositories, ... If you use a custom registry, use the `UserRegistry` class to implement the registry, and make sure that the registry is thoroughly reviewed before it's used in production.

When you configure file permissions,...

To learn more about how to harden your operating system against vulnerabilities, go to <link to OS topic>.

[#network]
== Network
Network intrusions occur when unauthorized users monitor or alter network traffic. <COMMON EXAMPLE - MITM attacks>.

=== Best practices
Use a firewall to shield production Open Liberty servers. Configure applications to run on a virtual host to keep admin traffic separate from application requests.

Disable non-SSL ports by setting them to `-1` in the `server.xml` file. Use mutual TLS when possible. Only use certificates that are signed by a Certificate Authority for public-facing production servers.

To learn more about network vulnerabilities and best practices to prevent network intrusions, go to <link to network topic>.

[#application-configuration]
== Application configuration
Application configuration intrusions occur when external users run applications that derive or inherit privileges that they are not authorized to. <COMMON EXAMPLE - Inheriting the identity of the server>.

=== Best practices
*

To learn more about ways to configure your application to prevent application intrusions, go to <link to application configuration topic>.
