// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: It is important to harden your Open Liberty server for production to reduce vulnerabilities and prevent security intrusions.
:seo-title: Hardening Open Liberty servers in production - openliberty.io
:seo-description: It is important to harden your Open Liberty server for production to reduce vulnerabilities and prevent security intrusions.
:page-layout: general-reference
:page-type: general
= Hardening Open Liberty servers in production

Hardening is a general term that is used to describe the measures that are taken to enhance your system security against potential threats and risks in production.
It is important to harden your Open Liberty server to reduce vulnerabilities and prevent security intrusions.
Different types of security intrusions can threaten different parts of your system, and there are best practices that you can employ to make each part less vulnerable.
Security intrusions and vulnerabilities can be broken down into different groups:

* <<#operating-system,Operating system>>
* <<#network,Network>>
* <<#application-configuration,Application configuration>>


[#operating-system]
== Operating system
Operating system (OS) intrusions occur when users with local access attempt to cause damage or extract sensitive information.
One example of this type of intrusion is malware.
If malware is introduced into a system, unauthorized users might be able to access the OS and its contents.

To learn more about OS vulnerabilities and ways to prevent OS intrusions, see link:/docs/ref/general/#os-hardening.html[Operating system security hardening].

=== Best practices

* *Stay up to date with Open Liberty*: To reduce OS vulnerabilities, it's important to keep your version of Open Liberty up to date.
Open Liberty fix packs are compatible with later versions, and the zero migration policy means that you can move to a newer fix pack without changing anything in your server configuration.
Keeping Open Liberty up to date helps ensure that you have the most recent link:/docs/ref/general/#security-vulnerabilities.html[critical security fixes].
To get the latest version of Open Liberty, go to the link:https://openliberty.io/downloads/[downloads page].
* *Use user registries that are safe for production*: Basic and Quick Start Security user registries are useful for development environments, but they are not acceptable for readiness testing, QA, or production use.
Instead, use an LDAP user registry, federated repositories, or create a custom user registry.
If you use an LDAP user registry, maintain your bind password in a separate `include` file, not in the `server.xml` file.
If you use a custom registry, use the `UserRegistry` class to implement the registry, and make sure that the registry is thoroughly reviewed before you use it in production.
* *Use web single-sign on*: For user authentication, it is common to use single-sign on (SSO) technologies (such as SAML, JWT, or OpenID Connect) instead of directly accessing user registries from Open Liberty.
SSO provides better security and regulatory compliance.
If you use SSO, maintain your SSO configuration in a separate include file, not in the `server.xml` file.
For more information about configuring SSO, see link:/docs/ref/general/#sso-config-json.html[SSO configuration with JSON Web Tokens].
* *Carefully configure file permissions*: When you configure file permissions, ensure that users who require access to the server's configuration have no more than the required capability (ie: a database administrator only has access to the data source configuration that is referenced in the `server.xml` using an `include` statement).
Users that aren't administrators or developers with specialized access (ie: to view application/server logs), should fall into the `other` group for server configuration files, and all files should have the other group configured with no access (indicated with `0`).
* *Encrypt passwords*: Use AES encryption for passwords instead of Base64 encoding.
You can use the `securityUtility` command, which provides plain text encryption for Open Liberty.
// For more information about the `securityUtility` command, see <link pending>.


[#network]
== Network
Network intrusions occur when unauthorized users monitor or alter network traffic. Replay attacks and man-in-the-middle (MITM) attacks are two examples of network intrusions.

To learn more about network vulnerabilities and ways to prevent network intrusions, see link:/docs/ref/general/#network-hardening.html[Network security hardening].

=== Best practices

* *Use a firewall*: Use a firewall to shield production Open Liberty servers so that they don't run in the demilitarized zone (DMZ).
The DMZ is an unsecured network segment that exists between internal and external networks.
Firewalls help prevent security intrusions by monitoring network traffic and blocking specific traffic based on security rules.
* *Enable the Transport Level Security feature*: The link:/docs/ref/feature/#transportSecurity.html[Transport Level Security feature] enables TLS for HTTP connections and adds the ability to configure outbound transports with TLS.
Additionally, disable non-TLS ports by setting them to `-1` in the `server.xml` file, and use only certificates that are signed by a certificate authority for public-facing production servers.
Also, enable TLS in your client and web server.
Using TLS connections throughout your network communication flow helps protect your server from network intrusions.
+
If you use SSO for user authentication, all SSO endpoint URLs must use a secure HTTP scheme (HTTPS), and the client must perform a TLS server certificate check.
* *Run applications on a virtual host*: Configure applications to run on a virtual host.
Open Liberty admin traffic comes in on the default host, so configuring your applications to run on a virtual host keeps Open Liberty admin traffic separate from application requests.


[#application-configuration]
== Application configuration
Application configuration intrusions occur when external users run applications that derive or inherit privileges that they are not authorized to.
One example of this type of intrusion happens when an application inherits the identity of the server, giving the application unauthorized permissions.

To learn more about application configuration vulnerabilities and ways to prevent application intrusions, see link:/docs/ref/general/#application-hardening.html[Application configuration security hardening].

=== Best practices

* *Understand application roles and access control*: Roles and mappings are crucial for securely configuring your application.
Incorrect role mapping can give inadvertent levels of access to users, which can result in users gaining unapproved access to sensitive resources.
For more information about roles and mapping them to the appropriate users or groups, see link:/docs/ref/general/#authorization.html[Authorization].
* *Secure servlet aliases*: Servlets are secured by URLs, and each URL must be specified in the `web.xml` file or with JAX-RS, using annotations in your application.
Because Open Liberty secures URLs and not the underlying classes, if a single servlet URL is insecure, an intruder might be able to bypass security.
