// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Hardening Open Liberty servers in production - openliberty.io
:seo-description:
:page-layout: general-reference
:page-type: general
= Hardening Open Liberty servers in production

Hardening is a general term that is used to describe the measures that are taken to enhance your system security against potential threats and risks in production. It is important to harden your Open Liberty server to reduce vulnerabilities and prevent security intrusions. Different types of security intrusions can threaten different parts of your system, and there are best practices that you can employ to make each part less vulnerable. Security intrusions and vulnerabilities can be broken down into different groups:

* <<#operating-system,Operating system>>
* <<#network,Network>>
* <<#application-configuration,Application configuration>>


[#operating-system]
== Operating system
Operating system (OS) intrusions occur when users with local access attempt to cause damage or extract sensitive information. One example of this type of intrusion is malware. If malware is introduced into a system, unauthorized users might be able to access the OS and its contents.

To learn more about OS vulnerabilities and ways to prevent OS intrusions, go to <link pending>.

==== Best practices

* *Keep Open Liberty up to date*: To reduce OS vulnerabilities, it's important to keep your version of Open Liberty up to date. Open Liberty fix packs are compatible with later versions, and the zero migration policy means that you can move to a newer fix pack without changing anything in your server configuration. Keeping Open Liberty up to date helps ensure that you have the most recent link:/docs/ref/general/#security-vulnerabilities.html[critical security fixes]. To get the latest version of Open Liberty, go to the link:https://openliberty.io/downloads/[downloads page].
* *Use user registries that are safe for production*: Basic and Quick Start Security user registries are useful for development environments, but they are not acceptable for readiness testing, QA, or production use. Instead, use an LDAP user registry, federated repositories, or create a custom user registry. If you use an LDAP user registry, maintain your bind password in a separate `include` file, not in the `server.xml` file. If you use a custom registry, use the `UserRegistry` class to implement the registry, and make sure that the registry is thoroughly reviewed before you use it in production.
* *Use web single-sign on*: For user authentication, it is common to use single-sign on (SSO) technologies (such as SAML, JWT, or OpenID Connect) instead of direct user registry access from Open Liberty. SSO can be used instead of user registries, and it provides better security and regulatory compliance. If you use SSO, maintain your SSO configuration in a separate include file, not in the `server.xml` file. For more information about configuring SSO, go to <link pending>.
* *Carefully configure file permissions*: When you configure file permissions, ensure that the users who want access to the configuration fall into the appropriate permission bit. Users that are not the owner and are not part of the authorized group fall into the `other` permission bit, which is indicated with `0`.
* *Encrypt passwords*: Use encryption for passwords instead of Base64 encoding. You can use the `securityUtility` command, which provides plain text encryption for Open Liberty. For more information about the `securityUtility` command, go to <link pending>.


[#network]
== Network
Network intrusions occur when unauthorized users monitor or alter network traffic. Replay attacks and man-in-the-middle (MITM) attacks are two examples of types of network intrusions.

To learn more about network vulnerabilities and ways to prevent network intrusions, go to <link pending>.

==== Best practices

* *Use a firewall*: Use a firewall to shield production Open Liberty servers so that they don't run in the DMZ. The DMZ is an unsecured network segment that exists between internal and external networks. Firewalls help prevent security intrusions by monitoring network traffic and blocking specific traffic based on security rules.
* *Enable the `transportSecurity` feature*: The link:/docs/ref/feature/#transportSecurity.html[Transport Security feature] enables the link:/docs/ref/feature/#ssl.html[SSL feature] to support SSL connections and adds the ability to configure outbound transports. Additionally, disable non-SSL ports by setting them to `-1` in the `server.xml` file, and use only certificates that are signed by a certificate authority for public-facing production servers. Also, enable SSL in your client and web server. Using SSL connections throughout your network communication flow helps protect your server from network intrusions.
+
If you use SSO for user authentication, all SSO endpoint URLs must use an HTTPS scheme, and the client must perform a TLS server certificate check.
* *Run applications on a virtual host*: Configure applications to run on a virtual host. Open Liberty admin traffic comes in on the default host, so configuring your applications to run on a virtual host keeps Open Liberty admin traffic separate from application requests.


[#application-configuration]
== Application configuration
Application configuration intrusions occur when external users run applications that derive or inherit privileges that they are not authorized to. One example of this type of intrusion happens when an application inherits the identity of the server, giving the application unauthorized permissions.

To learn more about application configuration vulnerabilities and ways to prevent application intrusions, go to <link pending>.

==== Best practices

* *Understand application roles and access control*: Roles and mappings are crucial for securely configuring your application. Incorrect role mapping can give inadvertent levels of access to users, which can result in users gaining unapproved access to sensitive resources. For more information about roles and mapping them to the appropriate users or groups, go to <link pending>.
* *Secure servlet aliases*: Servlets are secured by URLs, and each URL must be specified in the `web.xml` file. Because Open Liberty secures URLs and not the underlying classes, if a single servlet URL is insecure, an intruder might be able to bypass security.
