// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Hardening Open Liberty servers in production - openliberty.io
:seo-description:
:page-layout: general-reference
:page-type: general
= Hardening Open Liberty servers in production

Hardening is a general term that is used to describe the measures that are taken to enhance your system security against potential threats and risks. It is important to harden your Open Liberty server to reduce vulnerabilities and prevent against different types of intrusions that can occur. Security intrusions and vulnerabilities can be broken down into different groups:

* <<#operating-system,Operating system>>
* <<#network,Network>>
* <<#application-configuration,Application configuration>>


[#operating-system]
== Operating system
Operating system intrusions occur when users with local access attempt to cause damage or extract sensitive information. One example of this type of intrusion is malware being introduced into an operating system, allowing unauthorized access to the operating system and its contents.

To learn more about operating system vulnerabilities and ways to prevent operating system intrusions, go to <link to operating system topic>.

=== Best practices

===== Keep Open Liberty up to date
To reduce operating system vulnerabilities, it's important to keep your version of Open Liberty up to date. Open Liberty fix packs are upward compatible, and the zero migration policy allows you to move to a newer fix pack without changing anything in your server configuration. Ensuring that you have a recent version of Open Liberty positions you for link:/docs/ref/general/#security-vulnerabilities.html[critical security fixes].

===== Use user registries that are safe for production
Basic and Quick Start Security user registries are useful for development environments, but they are not acceptable for readiness testing, QA, or production use. Instead, use an LDAP user registry, federated repositories, or create a custom user registry. If you use an LDAP user registry, maintain your bind password in a separate `include` file, not in the `server.xml` file. If you use a custom registry, use the `UserRegistry` class to implement the registry, and make sure that the registry is thoroughly reviewed before it's used in production.

===== Carefully configure file permissions
When you configure file permissions, ensure that those who want access to the configuration fall into the appropriate permission bit. People who shouldn't have access at all fall into the `other` permission bit that's marked as `0`.

===== Encrypt passwords
Use encryption for passwords instead of Base64 encoding. You can use the `securityUtility` command, which provides plain text encryption for Open Liberty.


[#network]
== Network
Network intrusions occur when unauthorized users monitor or alter network traffic. Replay attacks and man-in-the-middle (MITM) attacks are two examples of network intrusions.

To learn more about network vulnerabilities and ways to prevent network intrusions, go to <link to network topic>.

=== Best practices

===== Use a firewall
To prevent network intrusions, use a firewall to shield production Open Liberty servers so that they don't run in the de-militarized zone (DMZ).

===== Use Transport Security
It's important to use the feature:transportSecurity-1.0[] feature to ___. This feature enables the feature:ssl-1.0[] feature In addition to enabling `transportSecurity-1.0`, disable non-SSL ports by setting them to `-1` in the `server.xml` file. Only use certificates that are signed by a Certificate Authority for public-facing production servers.

===== alsdkfj;asdf
Configure applications to run on a virtual host to keep admin traffic separate from application requests.


[#application-configuration]
== Application configuration
Application configuration intrusions occur when external users run applications that derive or inherit privileges that they are not authorized to. One example of this type of intrusion happens when an application inherits the identity of the server, giving the application unauthorized permissions.

To learn more about application configuration vulnerabilities and ways to prevent application intrusions, go to <link to application configuration topic>.

=== Best practices

===== alskdjfa;
