// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
= Java SE support

Open Liberty requires a Java SE runtime. A Java SE runtime (also known as a Java Runtime Environment or a Java Developer Kit), provides the tools to develop, run, and monitor your Java application. Open Liberty can run on any Java SE 8, 11, or 12 compatible runtime. Because of behavior and API differences between Java SE 8 and Java SE 11, an application that runs on Open Liberty with Java SE 8 might not run on Open Liberty with Java SE 11. See the https://docs.oracle.com/en/java/javase/11/migrate/index.html#JSMIG-GUID-C25E2B1D-6C24-4403-8540-CFEA875B994A[Oracle Java SE 11 migration guide] for more details.

Open Liberty always recommends running the most recent release of Java available.

== Java SE 8

Any recent Java SE release from IBM, Oracle, or AdoptOpenJDK works. With Oracle Java, the minimum supported level is Java SE 8u25.

== Java SE 11

Open Liberty currently only recommends the https://adoptopenjdk.net/index.html?variant=openjdk11&jvmVariant=openj9[OpenJDK 11 with OpenJ9 11.0.2] (or newer) release from AdoptOpenJDK. This is due to the following bugs we found in OpenJDK which are fixed in that release, but are not yet fixed in upstream OpenJDK:

// Insert list of bugs 
* https://bugs.openjdk.java.net/browse/JDK-8213202[JDK-8213202] Possible race condition in TLS 1.3 session resumption - this causes breaks in many of our regression tests when running with TLS 1.3.

=== See also

https://openliberty.io/blog/2019/02/06/java-11.html[Open Liberty and Java 11]

== Java SE 12

Any recent Java SE release from AdoptOpenJDK, OpenJDK, or Oracle will work. Java SE 12 is not a long-term supported release, with standard support scheduled to end in September 2019.
