// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Configuring an LDAP user registry for authentication and authorization
:seo-description: You can configure an LDAP user registry to manage authentication and authorization for your applications that run on Open Liberty.
:page-layout: general-reference
:page-type: general
= Configuring an LDAP user registry for authentication and authorization

You can configure a Lightweight Directory Access Protocol (LDAP) user registry to help manage authentication and authorization for your applications that run on Open Liberty.

LDAP is an open protocol that supports authentication and authorization services. LDAP specifies the language that application servers use to communicate with the user registries that store security information such as usernames, passwords, and user groups. Although a link:/docs/ref/general/#basic-registry.html[basic user registry] might be sufficient during development and testing of an application, an LDAP user registry provides the extra security that is required for applications in production.

You can configure Open Liberty to retrieve security information from an LDAP server if you are building an application that uses a preexisting user registry. LDAP is the industry standard for directory servers, providing a means to create, modify, search, and delete users and groups in your applications. There are many LDAP servers available, such as the link:https://www.ibm.com/support/knowledgecenter/SSVJJU_6.4.0/com.ibm.IBMDS.doc_6.4/c_po_SDS_overview.html[IBM Security Directory Server] and Microsoft's Active Directory. There are also open source LDAP servers, such as link:http://www.openldap.org/[OpenLDAP] and link:http://directory.apache.org/apacheds/[ApacheDS].

== Configuring an LDAP registry with Open Liberty

To use an existing LDAP server as a user registry, first add the link:/docs/ref/feature/#appSecurity-3.0.html[Application Security] and link:/docs/ref/config/#ldapRegistry.html[LDAP User Registry] features to your `server.xml` file. If you need to communicate with an SSL-enabled LDAP server, you must also add the link:/docs/ref/feature/#transportSecurity-1.0.html[Transport Security] feature.

Configure the LDAP user registry by adding the `<ldapregistry>` element to your `server.xml` file. Then, specify the port number, the host DNS name or IP address, LDAP type, and other attributes, as required by your security configuration. The following example shows a simple configuration for using IBM's Security Directory server as an LDAP registry:

[source,java]
----

<ldapRegistry id="LDAP" realm="SampleLdapIDSRealm"
      host="myldap.ibm.com" port="389" ignoreCase="true"
      baseDN="o=ibm,c=us"
      ldapType="IBM Security Directory Server" searchTimeout="8m">
</ldapRegistry>
----
For a full list of configuration elements and attributes, see the link:/docs/ref/config/#ldapRegistry.html[LDAP User Registry feature].


== Federated LDAP registries
You can also federate LDAP user registries so that multiple registries can be referenced together from a local view. You can federate LDAP registries with one another or with custom and basic user registries. For more information, see Federating user registries (link pending).

== Using the Social Media Login feature with LDAP registries

You can use Open Liberty's Social Media Login feature to help manage authentication with a configured LDAP registry. Depending how you configure the feature, users can either supply their social media credentials to authenticate to the LDAP registry or choose between their LDAP sign in and social media credentials for authentication. For more information, see the example configurations for the link:/docs/ref/feature/#socialLogin-1.0.html[Social Media Login feature].

== LDAP certificate map mode

You can use Open Liberty's certificate map mode to map X.509 public key certificates into an external LDAP user registry for authentication. You can choose from four different map modes to specify how a certificate is mapped to the LDAP registry.

* `EXACT_DN` +
Use `EXACT_DN` mode to map the certificate by its Distinguished Name (DN). To use this mapping mode, the DN in the certificate must exactly match the user entry in the LDAP server.

* `CERTIFICATE_FILTER` +
Use a specified certificate filter to map the certificate to the registry.

* `CUSTOM` +
Use this mode to provide a custom-mapping implementation. For more information, see link:/blog/2018/06/29/full_java_ee_8_liberty_18002.html#certmapper[Control how custom X.509 certificates map to users in Liberty’s LDAP and basic user registries].

* `NOT_SUPPORTED` +
The `NOT_SUPPORTED` mapping mode throws a `CertificateMapNotSupportedException` error if the registry receives an attempt to authenticate with a certificate. The `CertificateMapNotSupportedException` error is ignored if any other federated repositories can authenticate the certificate.

In the following example, certificate map mode is configured to map with a certificate filter on the Subject's common name (CN). The certificate is mapped to the IBM Security Directory LDAP Server.

[source,java]
----
<ldapRegistry id="LDAP" realm="SampleLdapIDSRealm"
      host="myldap.ibm.com" port="389" ignoreCase="true"
      baseDN="o=ibm,c=us"
      certificateMapMode="CERTIFICATE_FILTER"
      certificateFilter="uid=${SubjectCN}"
      userFilter="(&amp;(uid=%v)(objectclass=ePerson))"
      groupFilter="(&amp;(cn=%v)(|(objectclass=groupOfNames)
          (objectclass=groupOfUniqueNames)(objectclass=groupOfURLs)))"
      userIdMap="*:uid"
      groupIdMap="*:cn"
      groupMemberIdMap="ibm-allGroups:member;ibm-allGroups:uniqueMember;
          groupOfNames:member;groupOfUniqueNames:uniqueMember"
      ldapType="IBM Security Directory Server" searchTimeout="8m" />
----

For more information about certificate map mode and certificate filters, see link:/docs/ref/config/#ldapRegistry.html[LDAP User Registry].
