// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: Log management - OpenLiberty.io
:seo-description:
= Log management

Logs contain a record of events that occur while the application runs.  With effective log management, you can analyze the log events to better understand the behavior of applications.

To properly analyze log events, the events must be gathered into an accessible format that can be processed and stored securely. The log format provides the flexibility to represent any events in configurable log fields that can add more granularity and context for analysis. Logs are text-based immutable records of events that occur while an application runs.

Open Liberty servers and applications produce a variety of logs that can be used for different forms of analysis. For more information, see https://draft-openlibertyio.mybluemix.net/docs/ref/general/#json-log-events-list.html[JSON log events reference list].

To enable more flexible analysis, the logs from all the servers are typically aggregated into a single format. Several log analysis tools are used to facilitate this log aggregation and enhance the ability to manage the log events that are generated by applications. Open Liberty provides methods of using those tools to analyze logs.

With Open Liberty, you can avoid configuring the tools to analyze each of the different log formats and instead use either JSON logging or the Logstash collector to simplify log management.

== Analyzing JSON logs

In Open Liberty, you can configure your applications to generate logs in the JSON log format. When the logs are emitted by applications in the JSON log format, the usability of the log events is improved and the log analysis tools can manage the logs events more easily. The log analysis tools help to create centralized locations for managing logs and parsing log events to gain insight into the behavior of applications.  For more information, see https://draft-openlibertyio.mybluemix.net/docs/ref/general/#log-trace-configuration.html[Log and trace configuration].

== Managing log events with the Logstash collector

Open Liberty provides a Logstash collector feature that helps you to manage the events within logs to further analyze the behavior of applications. The feature is best used in scenarios where the JSON log format is not applicable.

You can use the Logstash collector feature to consolidate all of the log events to enable more flexible analysis. To consolidate the events, the feature captures the events, breaks them into fields, and securely forwards them to a specified configured logstash log collection server within a cloud environment. The Logstash collector feature stores events in environments that lack the management capabilities that help to determine application behavior.

For more information, see https://draft-openlibertyio.mybluemix.net/docs/ref/general/#forwarding-logs-logstash.html[Forwarding logs and events to Logstash with Logstash collector].
