// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: Log management - OpenLiberty.io
:seo-description:
= Log management

Logs are a record of events that occur during the operation of your servers.  As records of events, logs collect important information that is useful for diagnosing problems and helping you understand the behavior of applications.

To properly analyze log events, the events must be gathered into an accessible format that can be processed and stored securely. The log format provides the flexibility to represent any events in configurable log fields that can add more granularity and context for analysis. Logs are text-based immutable records of events that occur while an application runs.

Open Liberty servers and applications produce a variety of logs that can be used for different forms of analysis. These include logs such as the message log, trace log, first failure data captures (FFDC), audit logs and access logs.

Message logs record errors, warnings, and general information as the server runs. These logs are viewed most often to understand the general health of the server. Trace logs provide details about the infrastructure of components or applications that run on the server and can be enabled for specific components when problems occur. FFDC logs record information for specific exception conditions that include the details of the exception stack and dumps of objects from the server that relate to the cause of the exception. Audit logs record events from the server that are important to assessing security issues and are useful for security analysis. Access logs record every HTTP request that is made to the server, which is useful for traffic analysis.

It is common to aggregate logs from all servers with log analysis tools so that the logs can be easily searched and analyzed. Aggregating logs enables simpler log analysis that helps to determine which events occur in proximity to each other, which servers encounter the same problems, and to determine when problems first occurred.

== Analyzing JSON logs

While log aggregation and analysis tools can typically be configured to understand different log file formats, a simpler method is to emit all logs from Open Liberty servers in the JSON format. As JSON is a self-describing format, log analysis tools are typically able to consume JSON logs without the need for format-specific parsing instructions. Open Liberty can format its message log and console output in the JSON format.

With Open Liberty, you can write your logs to the console in the JSON format and rely on the server management system to automatically consume and parse console logs. This flexibility enables servers to run in different environments without modifying the server log configuration.

== Managing log events with the Logstash collector

Open Liberty provides a Logstash collector feature that can send logs directly to a Logstash server. https://www.elastic.co/logstash[Logstash] is a log aggregation tool. The feature can view message, trace, FFDC, audit, and access log events in your Open Liberty server at run time and forward those events securely to the host and port where your Logstash server runs.

The Logstash collector is convenient to use when your target log aggregator is Logstash, and when the environment your server runs in doesn't automatically aggregate and forward log events.

For more information, see https://draft-openlibertyio.mybluemix.net/docs/ref/general/#forwarding-logs-logstash.html[Forwarding logs and events to Logstash with Logstash collector].
