// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: Log management - OpenLiberty.io
:seo-description:
= Log management

Logs are a record of events that occur during the operation of your servers. As records of events, logs collect important information that is useful for diagnosing problems and helping you understand the behavior of applications.

Open Liberty servers and applications produce various logs that can be used for different forms of analysis. These logs include the message log, trace log, first failure data captures (FFDC), audit logs, and access logs. For more information, see link:/docs/ref/general/#json-log-events-list.html[JSON log events reference list].

It is common to aggregate logs from all servers with log analysis tools so that the logs can be easily searched and analyzed. Aggregating logs enables simpler log analysis that helps to determine which events occur in proximity to each other, which servers encounter the same problems, and to determine when problems first occur.

== Simplifying log parsing with JSON logs

While log aggregation and analysis tools can typically be configured to understand different log file formats, a simpler method is to emit all logs from Open Liberty servers in JSON format. As JSON is a self-describing format, log analysis tools are typically able to consume JSON logs without the need for format-specific parsing instructions. Open Liberty can format its message log and console output in JSON format.

With Open Liberty, you can write your logs to the console in JSON format and rely on the server management system to automatically consume and parse console logs. This flexibility enables servers to run in different environments without modifying the server log configuration.

== Forwarding log events with the Logstash collector

Open Liberty provides a Logstash collector feature that can send logs directly to a Logstash server. https://www.elastic.co/logstash[Logstash] is a log aggregation tool. The feature collects message, trace, FFDC, audit, and access log events in your Open Liberty server at run time. Those events are then forwarded securely to the host and port where your Logstash server runs.

The Logstash collector is best used when your target log aggregator is Logstash, and when the environment your server runs in doesn't automatically aggregate and forward log events.

For more information, see link:/docs/ref/general/#forwarding-logs-logstash.html[Forwarding logs and events to Logstash with Logstash collector].
