// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: Log management - OpenLiberty.io
:seo-description:
= Log management

Log management can enable you to understand the behavior of applications. By configuring logs, you can observe and manage the data that is generated by applications.

== Analyzing data with logs
When you access applications, you can analyze the data that is generated by the applications to draw insights from the behavior of the application. The data that is gathered from the application can be used in several different ways. You can use the application data to identify specific areas of potential failure within the application and diagnose the overall health of the application. You can also debug instances of failure within the application and conduct an analysis of the different dependencies of the application to understand the relationship between different components of applications.

To properly analyze application data, the data must be gathered into an accessible format that can be processed and stored securely. The log format provides the flexibility to represent any data in configurable log fields that can add more granularity and context for analysis. Logs are text-based immutable records of events that occur while an application is running. The logs can be emitted by applications in a structured form, such as JSON, that improves the usability of application data.

=== JSON logging format
The JSON log format can enable you to configure the application logs in a way that provides more understanding of the application behavior. To enable the JSON logging format in Open Liberty, you can add the following properties to the `bootstrap.properties` file in the application:

----
com.ibm.ws.logging.console.format=json
com.ibm.ws.logging.console.log.level=info
com.ibm.ws.logging.console.source=message,trace,accessLog,ffdc,audit
----

In the JSON logging format, you can use the `jsonFieldMappings` attribute to replace default field names with new field names to further analyze the logs of the application. For more information, see https://openliberty.io/docs/ref/general/#logging.html[Logging and Tracing].

== Managing log events with the Logstash Collector

Open Liberty provides a https://openliberty.io/docs/ref/feature/#logstashCollector-1.0.html[Logstash Collector] feature that helps you to manage the events within logs to further analyze the behavior of applications. The following example shows how to configure the Logstash Collector feature in a `server.xml` file:
----
<featureManager>
    <feature>logstashCollector-1.0</feature>
</featureManager>

<keyStore id="defaultKeyStore" password="Liberty" />
<keyStore id="defaultTrustStore" location="trust.jks" password="Liberty" />
<ssl id="mySSLConfig" trustStoreRef="defaultTrustStore" keyStoreRef="defaultKeyStore" />

<logstashCollector
	source="message,trace,garbageCollection,ffdc,accessLog,audit"
	hostName="localhost"
	port="5043"
	sslRef="mySSLConfig"
	maxEvents="10"
	maxFieldLength="3000">
	<tag>serverRackA5</tag>
	<tag>billingAppTeam</tag>
</logstashCollector>
----

You can use the Logstash Collector feature to consolidate all of the log events to enable more flexible analysis. To consolidate the events, the feature captures the events, breaks them into fields, and securely forwards them to a configured logstash log collection server within a cloud environment. The Logstash Collector feature is best used to store events in environments that lack the management capabilities such as file storage that help to determine application behavior.
