// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: Log management - OpenLiberty.io
:seo-description:
= Log management

Logs contain the data that is generated by applications. With effective log management, you can analyze the log data to better understand the behavior of applications.

To properly analyze application data, the data must be gathered into an accessible format that can be processed and stored securely. The log format provides the flexibility to represent any data in configurable log fields that can add more granularity and context for analysis. Logs are text-based immutable records of events that occur while an application runs. The logs can be emitted by applications in a structured form, such as JSON, that improves the usability of application data.

Several tools are available that can use logs to enhance your ability to observe and manage the data that is generated by applications. Open Liberty provides methods of utilizing those tools to analyze logs. These methods include the use of tools such as Splunk and the Elastic stack to analyze JSON-formatted logs. With Open Liberty, you can also use the Logstash Collector feature to perform log analysis.

== Managing log events with the Logstash collector

Open Liberty provides a Logstash collector feature that helps you to manage the events within logs to further analyze the behavior of applications.

You can use the Logstash collector feature to consolidate all of the log events to enable more flexible analysis. To consolidate the events, the feature captures the events, breaks them into fields, and securely forwards them to a configured logstash log collection server within a cloud environment. The Logstash collector feature is best used to store events in environments that lack the management capabilities that help to determine application behavior.

For more information, see https://draft-openlibertyio.mybluemix.net/docs/ref/general/#collecting-logs-logstash.html[Collecting logs and events with Logstash collector].

== Analyzing JSON logs

In Open Liberty, you can configure your application to log in the JSON log format. You can then send your logs to a log analysis tool that can consume JSON logs. The structure that is provided by the JSON logs within the tools can help to create centralized locations for managing and analyzing logs. For more information, see https://draft-openlibertyio.mybluemix.net/docs/ref/general/#logging.html[Logging and Tracing].

=== Analyzing JSON logs with the Elastic stack
The https://www.elastic.co/[Elastic stack] is a log management platform, which consists of Elasticsearch, Kibana, Logstash, and Beat, that enables the collection of data into a single place for more thorough analysis. The centralized logging makes it easier to troubleshoot the application, detect problems, secure the application, or complete any other function that is important to understand the behavior of the application.

Each of the tools that compose the Elastic stack provide a distinct function to analyze logs.
Elasticsearch is a search and analytics engine. Logstash is a log aggregator that collects and processes data. Kibana provides a user interface that allows users to visualize and query their data with graphs and charts. Beats consists of data shippers that collect and send data from different services.  The combination of these tools provides an increased level of interaction with the log data to enhance the usability of logs.

=== Analyzing JSON logs with Splunk
While other log management platforms, such as Elastic stack, can also increase the usability of logs, https://www.splunk.com/en_us/central-log-management.html[Splunk] can provide the most flexibility to manage the log data that is generated by applications. Splunk is a centralized log analysis tool that can consolidate log data within any format. The tool also provides a wide variety of functions that are designed to address several possible use cases for enterprise log management such as application compliance reporting and log consolidation.
