:page-layout: general-reference
:page-type: general
:page-description: MicroShed testing helps you to write integration tests using testcontainers for Java microservice applications. With MicroShed testing you can test your Open Liberty application from outside the container so you are testing the exact same image that runs in production.
:page-categories: MicroShed testing
:seo-title: Testing in a container with MicroShed testing
:seo-description:  MicroShed testing helps you to write integration tests using testcontainers for Java microservice applications. With MicroShed testing you can test your Open Liberty application from outside the container so you are testing the exact same image that runs in production.
= Testing in a container

Writing tests in a microservices scenario can be complex, time-consuming, and your test might work differently in a production environment.
Microshed testing helps you write true-to-production integration tests for your containerized Java microservice applications using testcontainers.
While adhering to the standards of the development-production-parity for building modern applications,

Integration testing evaluates the performance of a group of microservices as a whole unit, as compared to unit tests, which tests each microservice as an individual unit.
Thus, integration tests are more comprehensive than unit tests.
However, integration tests can be more complicated and take longer to run.
Microshed testing makes your work easier and faster by streamlining integration tests with testcontainers.


== Why integration testing

You need to be sure that your application works in development as well as production mode.
Developers usually run unit tests as they are easier, faster, and test a few methods at a time.
Integration tests assess multiple test classes and components at once, and are better at analyzing the working of the different parts of your application as a whole.
Therefore, developers find integration testing to be more reliable for their application to work in production environment.
However, integration tests take longer and can be complicated to set up and configure.
With faster development cycles and limited time available to developers, it's not always feasible to run integrated tests for your applications.

== Development-production parity

Development-production parity, or dev-prod parity, is one of the factors in the link:https://12factor.net/[twelve-factor app], a methodology to build modern applications.
The idea behind dev-prod parity is to keep the development, staging, and production environments as similar as possible, and it addresses gaps in development ad production in terms of time, personnel, and tools.
Developers mostly use different tools in development as compared to production for speed and ease of use.
For example you might use a local maven build in development, but the application might be deployed to a docker container in production.
The application might work on your machine but not in production.
So it is important to use the same services in development as in production.

==The containers scenario

The programming paradigms have changed with how we test software.
Currently, many developers run containers in production.
Containers are convenient and combine everything you need to run a service into a single unit.
They are easy to manage with an orchestration software like Kubernetes.
They are lightweight and disposable and fairly easy to configure with environment variables.
They are easy to leverage containers in a test environment using testcontainers, which is a helper library

== What challenges does MicroShed resolve

An application might run differently in production as compared to the development and testing environment.
Differences between the environments can cause a test to fail in production, even though it passed in development.
You can address this issue by testing your application in the same container that you use in production.

Running tests in development mode is convenient for local development, but it can be tedious to test against a running Open Liberty server in production scenarios, such as CI/CD pipelines.
For this reason, MicroShed Testing can start and stop the application runtime before and after the tests are run.

== How it works

You can use MicroShed Testing to develop integration tests for your Open Liberty application.
You test your application from outside its container so that the tests run against the same image that you use in production.




Ready to try using MicroShed Testing to test a MicroProfile or Jakarta EE application? Check out our guide https://openliberty.io/guides/microshed-testing.html[Testing a MicroProfile or Jakarta EE application]
