// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: MicroProfile Config is an API that externalizes configuration from microservices, thus keeping it separate from the source code. MicroProfile Config can be used by applications as a single API that can retrieve configuration information from different sources.
:seo-description: MicroProfile Config is an API that externalizes configuration from microservices, thus keeping it separate from the source code. MicroProfile Config can be used by applications as a single API that can retrieve configuration information from different sources.
:page-layout: general-reference
:page-type: general

= Microservice configuration

MicroProfile Config is an API that externalizes the configuration from microservices, thus keeping it separate from the source code. Microservices consist of multiple services, running on multiple servers, and can make configuration difficult, especially in a production environment. With Microprofile Config, external configuration can be injected into services in the containers without the need for repackaging them. 

Applications can use MicroProfile Config as a single API that can retrieve configuration information from different sources.
When your applications are deployed as microservices, having a single place to update the configuration data of multiple microservices is useful for several reasons:

-	 Building systems as collections of independent microservices increases the number of services that need to be managed.
-	 Different stages in the pipeline often use different configuration sources for a single piece of configuration data and a component needs updating as it moves through the pipeline.
-	 Containerization of services means that while a component is ‘live’ in production, the environment it is running in might be more dynamic. Thus if the component needs configuration updates you don't need to restart it.

The MicroProfile Config API allows for a consistent means to access configuration data from pluggable configuration sources. Configuration properties can be injected by using Java CDI in a form that is easy to use. Data values and sources can vary across the DevOps pipeline without code change or repackaging, and dynamic and fully typed data is catered for.


== Why it is important to configure microservices without having to update the app code?

A microservice can be deployed several times, by using multiple versions and across multiple environments ((e.g. development, test, production). The microservice needs to work in all those environments without the need to modify the code. It is important to avoid embedding configuration in code, particularly if that config contains sensitive information such as passwords.

Configuration data can come from different locations and in different formats – system properties, system environment variables, properties files or resources, XML files or resources, and data sources. MicroProfile Config calls these sources of data ConfigSources. The same configuration property can be defined in multiple ConfigSources. A prioritization can be used to determine which ConfigSource is used for the property value. Each ConfigSource has a specified priority, which is defined by its ordinal value. A higher ordinal means that the values taken from this ConfigSource override ConfigSources with a lower ordinal value.

MicroProfile Config has three default ConfigSources:

-	All META-INF/microprofile-config.properties found on the class path (default ordinal = 100).
-	Environment variables (default ordinal = 300).
-	System properties (default ordinal = 400).

An optional default value can be specified by using Java annotations. The optional default value applies if the application does not find configuration values in any of the ConfigSources.

== What you can do with MP Config?

There are many benefits of using MP Config:

•	Merge multiple configuration sources into a single configuration and access with one API.
•	Override configuration property values with values from configuration sources that are designated as having a higher precedence.
•	Store values in named properties files, system environment variables, or Java System properties.
•	Load `ConfigSource` resources by using a Java `ClassLoader`, either the application’s current context `ClassLoader` or a user supplied `ClassLoader`.
•	Provide values by registering a user implementation of a `ConfigSource` interface.
•	Retrieve values as Strings or as typed objects of a particular Java class by using built in or custom type Converters.
•	Discover `ConfigSource` and `Converter` implementations by using the Java `ServiceLoader` pattern.
•	Directly inject configuration property values, whether for primitives, standard types, or user supplied types, by using Java CDI (Context and Dependency Injection).


