:page-layout: general-reference
:page-type: general
:page-description: MicroShed testing helps you to write integration tests using testcontainers for Java microservice applications. With MicroShed testing you can test your Open Liberty application from outside the container so you are testing the exact same image that runs in production.
:page-categories: MicroShed testing
:seo-title: Testing in a container with MicroShed testing
:seo-description:  MicroShed testing helps you to write integration tests using testcontainers for Java microservice applications. With MicroShed testing you can test your Open Liberty application from outside the container so you are testing the exact same image that runs in production.
= Testing in a container

Writing a test can be a complex, time-consuming, and might work differently in a production environment.
Microshed testing helps you write true-to-production integration tests for your Java microservice applications.

Integration testing looks at microservices as a group and tests their performance as a whole unit, as compared to unit tests, which look at each microservice as an individual unit.
Intergration tests offer advantages over unit tests, for example, detecting bugs earlier in the cycle.
However, integration tests can be more complicated and take longer to run.
Microshed testing makes your work easier and faster by streamlining integration tests with testcontainers.


== Why integration testing

Developers usually run unit tests as they are easier and faster and usually test a few methods.
Integration tests  looks at multiple test classes, and are better at analyzing the working of the different parts of your application as a whole.
However, integration tests take longer and can be complicated to set up and configure.

== What challenges does MicroShed resolve

An application might run differently in production as compared to the development and testing environment.
Differences between the environments can cause a test to fail in production, even though it passed in development.
You can address this issue by testing your application in the same container that you use in production.

Running tests in development mode is convenient for local development, but it can be tedious to test against a running Open Liberty server in production scenarios, such as CI/CD pipelines.
For this reason, MicroShed Testing can start and stop the application runtime before and after the tests are run.

== How it works

You can use MicroShed Testing to develop integration tests for your Open Liberty application.
You test your application from outside its container so that the tests run against the same image that you use in production.




Ready to try using MicroShed Testing to test a MicroProfile or Jakarta EE application? Check out our guide https://openliberty.io/guides/microshed-testing.html[Testing a MicroProfile or Jakarta EE application]
