:page-layout: general-reference
:page-type: general
:page-description: Microservice architecture is a popular approach for building cloud-native applications in which each capability is developed as an independent service. It enables small, autonomous teams to develop, deploy, and scale their respective services independently.
:page-categories: MicroProfile
:seo-title: MicroProfile simplifies developing cloud-native Java microservices
:seo-description: Microservice architecture is a popular approach for building cloud-native applications in which each capability is developed as an independent service. It enables small, autonomous teams to develop, deploy, and scale their respective services independently.
= Testing in a container
MicroShed Testing offers a fast and simple way of writing and running true-to-production integration tests for Java microservice applications. MicroShed Testing exercises your containerized application from outside the container so you are testing the exact same image that runs in production.

MicroShed Testing aims to:

- be easy to get started with
- work with any Java EE, Jakarta EE or MicroProfile runtime
- provide true-to-production tests

You can use MicroShed Testing to develop integration tests for your Open Liberty application. You test your application from outside its container so that the tests run against the same image that you use in production.

== Why integration testing

Integration testing is an approach where modules are developed, and testing of modules always starts at the finest level of the programming hierarchy and continues towards the lower levels. It’s the extension of unit testing. Integration testing takes a smaller unit of unit testing and tests their behavior as the whole.

Most of the industry and organization have adapted only to the Unit testing and Functional testing. It’s some of the organization that has the Integration testing in the testing life cycle.

Testing starts at the very early stages of development and bugs are caught earlier rather than late in the cycle. Creating the right test gives precise feedback loop mechanism between both developers and test engineers.



== What challenges does Microshed resolve



== How it works (with code snippets)

To write a test with MircoShed testing, first add microshed-testing-testcontainers and junit-jupiter artifact IDs as test-scoped dependencies, as shown in the following example:
