// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: MicroProfile Config is an API that externalizes configuration from microservices, keeping it separate from the source code. MicroProfile Config can be used by applications as a single API that can retrieve configuration information from different sources.
:seo-description: MicroProfile Config is an API that externalizes configuration from microservices, keeping it separate from the source code. MicroProfile Config can be used by applications as a single API that can retrieve configuration information from different sources.
:page-layout: general-reference
:page-type: general
= Externalizing configuration in microservices

Microservices move between different environments and resource connection details can change. Externalizing configuration (for example, using MicroProfile Config) means you can change configuration values without altering your application code.

== Separating configuration and code

During their lifecycle, microservices need to be deployed repeatedly across multiple environments (development, test, production). They need different configurations, for example, deployment-specific external URLs or credentials that change regularly. Microservices need to run in these conditions without the need to change code.

Backing services need to be swapped without the need for a change in the apps code (databases, messaging services, SMTP services, API accessible consumer services). Each backing service must be attached to your application as a resource and detached if needed, without the need to change the code or a distinction between a local and external service.

In the cloud, microservices deployed to Kubernetes clusters need to communicate, so port binding (knowing which port to connect to) is important. As Kubernetes creates and destroys instances of microservices to scale the app up and down, port numbers can change. New port numbers need to be assigned to microservices and information needs to be injected into the affected microservices during startup. For more information, see link: https://openliberty.io/guides/kubernetes-microprofile-config.html[Configuring microservices running in Kubernetes].

Hence, it is important to change the configuration of the microservices without having to update the code and recompile it.

== MicroProfile Config

MicroProfile Config externalizes the configuration from microservices, keeping it separate from the source code. With MicroProfile Config, external configuration can be injected into services in the containers without the need to repackage them.

Applications can use MicroProfile Config as a single API to retrieve configuration information from different sources. Configuration data can come from different locations and in different formats – system properties, system environment variables, properties files or resources, XML files or resources, and data sources. MicroProfile Config calls these sources of data ConfigSources. The same configuration property can be defined in multiple ConfigSources. A prioritization can be used to determine which ConfigSource is used for the property value. Each ConfigSource has a specified priority, which is defined by its ordinal value. A higher ordinal means that the values taken from this ConfigSource override ConfigSources with a lower ordinal value.

MicroProfile Config has three default ConfigSources:

-	All META-INF/microprofile-config.properties found on the class path (default ordinal = 100).
-	Environment variables (default ordinal = 300).
-	System properties (default ordinal = 400).

An optional default value can be specified by using Java annotations. The optional default value applies if the application does not find configuration values in any of the ConfigSources. For more information, see link:https://openliberty.io/guides/microprofile-config-intro.html[Separating configuration from code in microservices]

MicroProfile Config is used to configure other MicroProfile capabilities. It can externalize configuration of keystores when microservices are secured (MP JWT). For example, the public key location and verification can be set in properties files so that if the location of the key repository changes, it can easily be updated. MicroProfile Config can also be used in configuration of channel attributes (MP Reactive Messaging). For example, it can set the connection details of messaging channels and connectors, and the topic names that are used by the app to use and produce messages. MicroProfile Config can help in overriding values in fault tolerance (MP FT). For example, it can set the value of an annotation so that you can change the value if the tolerance is found to be too low or too high.
