// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: MicroProfile Config is an API that externalizes configuration from microservices, thus keeping it separate from the source code. MicroProfile Config can be used by applications as a single API that can retrieve configuration information from different sources.
:seo-description: MicroProfile Config is an API that externalizes configuration from microservices, thus keeping it separate from the source code. MicroProfile Config can be used by applications as a single API that can retrieve configuration information from different sources.
:page-layout: general-reference
:page-type: general
= Externalizing configuration in microservices

Microservices move between different environments where resources can change. Updating them individually can be difficult and tedious. Externalizing configuration enables a microservice to run in multiple environments without modification. With MicroProfile Config, you can conveniently change configuration values without modifying your application code.

== Separating configuration and code

Microservices can be deployed several times, by using multiple versions and across multiple environments (development, test, production), and need different configurations. For example, they might need deployment-specific external URLs or credentials that change regularly. If these configuration values are hardcoded within the service, they must be redeployed for every configuration change. Hence, it is important to change the configuration of the microservices without having to update the code and recompile it.

Backing services need to be swapped without the need for a change in the apps code (databases, messaging services, SMTP services, API accessible consumer services). Each backing service is an attached resource, which indicates their loose coupling to the deploy they are attached to. These services might be managed by the same developer or by an external service.

In the cloud, microservices deployed to Kubernetes clusters need to communicate , so port binding (knowing which port to connect to) is important. As Kubernetes creates and destroys instances of microservices to scale the app up an down, port numbers change. It is important that Kubernetes can can assign new port numbers to microservices and that information is injected into all the microservices that need to know it as during start up. For more information, refer to https://openliberty.io/guides/kubernetes-microprofile-config.html

== MicroProfile Config

MicroProfile Config is an API that externalizes the configuration from microservices, thus keeping it separate from the source code. With Microprofile Config, external configuration can be injected into services in the containers without the need for repackaging them.

Applications can use MicroProfile Config as a single API to retrieve configuration information from different sources.
The MicroProfile Config API allows for a consistent means to access configuration data from pluggable configuration sources. Configuration properties can be injected by using Java CDI in a form that is easy to use. Data values and sources can vary across the DevOps pipeline without code change or repackaging, and dynamic and fully typed data is catered for.

Configuration data can come from different locations and in different formats – system properties, system environment variables, properties files or resources, XML files or resources, and data sources. MicroProfile Config calls these sources of data ConfigSources. The same configuration property can be defined in multiple ConfigSources. A prioritization can be used to determine which ConfigSource is used for the property value. Each ConfigSource has a specified priority, which is defined by its ordinal value. A higher ordinal means that the values taken from this ConfigSource override ConfigSources with a lower ordinal value.

MicroProfile Config has three default ConfigSources:

-	All META-INF/microprofile-config.properties found on the class path (default ordinal = 100).
-	Environment variables (default ordinal = 300).
-	System properties (default ordinal = 400).

An optional default value can be specified by using Java annotations. The optional default value applies if the application does not find configuration values in any of the ConfigSources.
MicroProfile Config is used to configure other MicroProfile capabilities. It is used to externalize configuration of keystores when microservices are secured (MP JWT). For example, the public key location and verification can be set in properties files so that if the location of the key repository changes, it can easily be updated. MP Config can also be used in configuration of channel attributes (MP Reactive Messaging). For example, it can set the connection details of messaging channels and connectors, and the topic names that are used by the app to use and produce messages. It can help in overriding values in fault tolerance (MP FT). For example, it can set the value of an annotation so that you can easily change the value if the tolerance is found to be too low or too high.

=== See aslo

- https://openliberty.io/guides/microprofile-config-intro.html
- https://openliberty.io/guides/microprofile-config-intro.html
- https://openliberty.io/guides/kubernetes-microprofile-config.html
- https://t.co/t6p7IY0hUn
- https://12factor.net/
- https://www.openliberty.io/docs/ref/feature/#mpConfig.html
