// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:  A health check is a special REST API implementation that you can use to  validate the status of a microservice and its dependencies. MicroProfile Health enables services in an application to self-check their health and then publishes the overall health status to a defined endpoint.
:seo-title: Monitoring microservices with MicroProfile Health
:seo-description:  A health check is a special REST API implementation that you can use to  validate the status of a microservice and its dependencies. MicroProfile Health enables services in an application to self-check their health and then publishes the overall health status to a defined endpoint.
:page-layout: general-reference
:page-type: general
= Monitoring microservices with MicroProfile Health

Monitoring the health of the microservices that make up your application is crucial to providing your users with reliable functionality. A *health check* is a special REST API implementation that you can use to validate the status of a microservice and its dependencies. MicroProfile Health enables services in an application to self-check their health and then publishes the overall health status to a defined endpoint. A self-check can assess anything that the service needs: a dependency, a system property, a database connection, or the availability of required resources. Services report as either `UP` (available) or `DOWN` (unavailable) by implementing the API provided by MicroProfile Health. A service orchestrator can then use these status reports to decide how to manage and scale the services within an application.

== MicroProfile Health Check provided endpoints

MicroProfile Health Check provides three endpoints:

- `/health`: a one-stop check that can apply to any application, providing status information to load balancer requests
- `/health/ready`: returns the readiness of a service, or whether it boots successfully. This endpoint corresponds to the Kubernetes readiness probe.
- `/health/live`: returns the liveness of a service, or whether it has encountered a bug or deadlock. This endpoint corresponds to the Kubernetes liveness probe.

`supply endpoint examples- particularly @live and @ready which are not addressed in the guides yet`

== Where to next?

Ready to start monitoring your microservices with MicroProilfe Health? Check out the Open Liberty interactive guides for link:[Adding health reports to microservices](/guides/microprofile-health) and link:[Checking the health of microservices on Kubernetes](/guides/kubernetes-microprofile-health).

==== See also:

-link:[Open Liberty features: MicroProfile Health](/docs/ref/feature/#mpHealth)
-link:[MicroProfile Health on Github](https://github.com/eclipse/microprofile-health)
