:page-layout: general-reference
:page-type: general
:page-description: OpenID Connect (OIDC) is an identity protocol based on OAuth 2.0 that is widely used in SSO technologies. OIDC works well with cloud, mobile, and native applications.
:page-categories: OpenID Connect
:seo-title: OpenID Connect (OIDC) is an identity protocol based on OAuth 2.0.
:seo-description: OpenID Connect (OIDC) is an identity protocol based on OAuth 2.0 that is widely used in SSO technologies. OIDC works well with cloud, mobile, and native applications.
= Monitoring and Observability

There is a culture change around monitoring that comes with a shift to cloud native. Although applications in both on-premises and cloud-native environments are expected to be highly available and resilient to failure, the methods that are used to achieve those goals are different. As a result, the purpose of monitoring shifts: instead of monitoring to avoid failure, monitor to manage failure.

In on-premises environments, infrastructure and middleware are provisioned based on planned capacity and high availability patterns, for example, active-active or active-passive. Unexpected failures can be complex in this environment, requiring significant effort for problem determination and recovery. External monitoring is performed by agents that examine resource utilization to avoid known classes of failures. As an example, consider the tuning of heap size, timeouts, and garbage collection policies for Java applications.

A cloud-native application is composed of independent microservices and required backing services. Even though a cloud-native application as a whole must remain available and continue to function, individual service instances will start or stop as to adjust for capacity requirements or to recover from failure.

== Observability

Monitoring this fluid system requires each participant to be observable. Each entity must produce appropriate data to support automated problem detection and alerting, manual debugging when necessary, and analysis of system health (historical trends and analytics).

What kinds of data should a service produce to be observable?

Health checks (often custom HTTP endpoints) help orchestrators, like Kubernetes or Cloud Foundry, perform automated actions to maintain overall system health.
Metrics are a numeric representation of data that is collected at intervals into a time series. Numerical time series data is easy to store and query, which helps when looking for historical trends. Over a longer period, numerical data can be compressed into less granular aggregates, daily or weekly, for example.
Log entries represent discrete events. Log entries are essential for debugging, as they often include stack traces and other contextual information that can help identify the root cause of observed failures.
Distributed, request, or end-to-end tracing captures the end-to-end flow of a request through the system. Tracing essentially captures both relationships between services (the services the request touched), and the structure of work through the system (synchronous or asynchronous processing, child-of or follows-from relationships).


== The OpenID Connect Provider (openidConnectServer-1.0) feature

You can configure an Open Liberty server to act as an OpenID Connect Provider by enabling the https://openliberty.io/docs/ref/feature/#openidConnectServer-1.0.html[openidConnectServer-1.0] feature in Liberty.


== Configuring Open Liberty as an SSO provider

The OpenID Connect Provider (openidConnectServer-1.0) feature can be configured to manage user authentication for OpenID Connect clients and microservices. The OpenID Connect Provider can work directly with a user registry such as LDAP or act as an identity broker and delegate to another security provider.

Add the `openidConnectServer-1.0` Liberty feature and any other needed features to the `server.xml` file. The `transportSecurity-1.0` feature is also required for the `openidConnectServer-1.0` feature.

[source, java]
----
<feature>openidConnectServer-1.0</feature>
<feature>transportSecurity-1.0</feature>
----

Define an `OAuth` service provider. The configuration of an `OAuth` service provider includes the appropriate `oauth-roles`, `oauthProvider`, and user registry elements. Any user that is authorized to use OpenID Connect must also be mapped to the authenticated `oauth-role`.

In the following example, the OP expects the client's SSL port to be set to 443.

[source, java]
----
<openidConnectProvider id="OidcConfigSample" oauthProviderRef="OAuthConfigSample" />

<oauthProvider id="OAuthConfigSample">
<localStore>
<!-- localstore is for test/dev use and not for production -->
<client name="client01" secret="{xor}LDo8LTor"
displayname="client01"
scope="openid profile email">
   <redirect>https://server.example.com:443/oidcclient/redirect/client01</redirect>
   <redirect>https://server2.example.com:443/oidcclient/redirect/client01</redirect>
</client>
</localStore>
</oauthProvider>
----

Add an `openidConnectProvider` element with the `oauthProviderRef` attribute references the configured `oauthProvider`. Each `oauthProvider` can be referenced by only one `openidConnectProvider`. Two or more `openidConnectProvider` elements cannot reference to the same `oauthProvider`. The name attribute and the secret attribute of the client element must match the client ID and the client secret of the corresponding OpenID Connect Client.

Configure the truststore of the server to include the signer certificates of the OpenID Connect Relying Parties, or clients, that are supported.

Modify the SSL configuration of the server to use the configured truststore.

[source, java]
----
<sslDefault sslRef="DefaultSSLSettings" />
<ssl id="DefaultSSLSettings" keyStoreRef="myKeyStore" trustStoreRef="myTrustStore" />
<keyStore id="myKeyStore" password="{xor}Lz4sLCgwLTs=" type="jks" location="${server.config.dir}/resources/security/BasicKeyStore.jks" />
<keyStore id="myTrustStore" password="{xor}Lz4sLCgwLTs=" type="jks" location="${server.config.dir}/resources/security/BasicTrustStore.jks" />
----

OpenID Connect is configured to use the default SSL configuration that is specified by the server. Therefore, the default SSL configuration for the server must use the truststore that is configured for OpenID Connect.
