// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:seo-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:page-layout: general-reference
:page-type: general
= Documenting microservice APIs with OpenAPI

OpenAPI, previously known as Swagger, defines a standard interface for documenting and exposing RESTful APIs.
This standard interface enables both humans and computers to process a web service available through its REST API without directly accessing the source code of the web service.
MicroProfile OpenAPI provides a set of Java interfaces and programming models that enable Java developers to natively produce OpenAPI documents from their JAX-RS applications.

Developers can write a web service to communicate with the REST API of another web service only if they have the relevant information to do so.
A developer needs to understand what information their web service can request from the second web service using its REST API and what information the API needs from the first web service in order to be able to return the relevant information.

There are two main ways to generate a link:https://swagger.io/docs/specification/about/[OpenAPI] document.
The developer can generate documentation of the REST API from the source code of the REST API itself.
The reference document then produced, lists all the API endpoints and descriptions of how to use them.
Alternatively, the developer can start by designing the API in the form of structured documentation that they can then augment with annotations in the code.
The developer can even generate the stubs for the source code, including client libraries for the API, from this manually created documentation.

== Processing annotations to generate REST API documentation

You can easily generate basic API documentation from a JAX-RS application; the JAX-RS framework handles that for you.
You should, however, provide more useful explanations of the parts of the API, where appropriate, by adding annotations to your code.
The annotations are then processed to provide more detailed and useful documentation about how to use the REST API.

The following example shows a JAX-RS request to list host names in the inventory.
The OpenAPI annotations in the example provide more useful and explanatory information about the operation:
[source,java]
----
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @APIResponse(
        responseCode = "200",
        description = "host:properties pairs stored in the inventory.",
        content = @Content(
            mediaType = "application/json",
            schema = @Schema(
                type = SchemaType.OBJECT,
                implementation = InventoryList.class)))
    @Operation(
        summary = "List inventory contents.",
        description = "Returns the currently stored host:properties pairs in the "
        + "inventory.")
    public InventoryList listContents() {
        return manager.list();
    }
----

In the following OpenAPI documentation example code, the JAX-RS framework generates the `path /inventory/systems` path based on the value of the `@Path` annotation, and the value of the `operationId` key (listContents) based on the name of the method (listContents()).
The other parts of the document are generated from the OpenAPI annotations that the developer annotated the code with.
For example, the `@Operation` annotation provides more meaningful information about what the operation does and why; in this case, the operation returns a list of the host names with properties of each host that are currently stored by the inventory web service.

[source,java]
----
/inventory/systems:
  get:
    summary: List inventory contents.
    description: Returns the currently stored host:properties pairs in the inventory.
    operationId: listContents
    responses:
      200:
        description: host:properties pairs stored in the inventory.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryList'
----

The information provided through the OpenAPI annotations augment the basic API documentation that is generated by the JAX-RS framework.

See the link:https://www.openliberty.io/docs/ref/microprofile/3.0/#package=org/eclipse/microprofile/openapi/annotations/package-frame.html&class=org/eclipse/microprofile/openapi/annotations/Operation.html[MicroProfile OpenAPI Javadoc] for the annotations available
== Manually created REST API documentation

An alternative approach is to design the REST API in an editor, such as the Swagger editor, before writing any code.
This approach enables you to spot any problems in the design before, rather than after, implementation.
In large companies, it is important to have consistent, usable APIs that have been reviewed and agreed by the relevant people that it is a good API design.
This API design then forms a contract and must be implemented as agreed.

You can write this API design in YAML or JSON which can then be used to generate the documentation and, optionally, even stubs for the API code itself.
You can then also augment the documentation with annotations in the code as described previously.

For examples of Static OpenAPI files, see link:https://github.com/eclipse/microprofile-open-api/wiki/Static-File-Samples[Static File Samples].

== Filtering components in and out of API documentation

You can use filters to organize your APIs. For example, you can choose to expose some APIs to one audience and other APIs to another audience.

With link:https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/OASFilter.java[OASFilter], you can receive callbacks for various key OpenAPI elements.

To use OASFilter, create an implementation of the interface and register it using the `mp.openapi.filter` configuration key, where the value is the fully qualified name of the filter class.

For examples of OASFilter, see link:https://github.com/eclipse/microprofile-open-api/wiki/OASFilter-Samples[OASFilter Samples].

== Viewing and formatting API documentation

The documentation that is generated for the REST API is available at the /openapi endpoint of your web service.
The documentation is formatted using the standard OpenAPI user interface (UI) and a default style sheet.
You can optionally customise the style sheet for your web service.
You can also link:https://www.ibm.com/support/knowledgecenter/en/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_api_mpopenapi_custom.html[customize] the UI available from the endpoint `/openapi/ui`.
