// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:seo-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:page-layout: general-reference
:page-type: general
= OpenAPI documentation for microservices

OpenAPI is a standardized mechanism for developers to describe REST APIs. With OpenAPI you can describe REST APIs and generate API documentation from the APIs themselves. MicroProfile OpenAPI is a specification outlined as an official set of annotations and interfaces that help developers successfully generate OpenAPI documentation for their Java RESTful APIs.

You can generate the OpenAPI document in multiple ways.

== Annotations

JAX-RS annotations are processed by default with MP OpenAPI. You can augment the existing code with OpenAPI annotations without rewriting portions of the OpenAPI document that are already covered by the JAX-RS framework.

Vendors must process all the relevant JAX-RS annotations, like @Path and @Consumes, and Java objects used as input or output to JAX-RS operations. Developers can deploy their existing JAX-RS application into a MP OpenAPI vendor and check out the output from `/openapi`.

Annotations like @Callback, @Components, @ParameterIn, and more are found in the Eclipse OpenAPI annotations package . For an overview of annotation, see https://download.eclipse.org/microprofile/microprofile-open-api-1.0/microprofile-openapi-spec.html#_quick_overview_of_annotations.

When the same annotation is used on a class and a method, the values from the method instance take precedence for that particular method, for example, @Server and @Tag annotations. The annotation values from the method’s parameters take precedence over corresponding annotation values from the method itself, for example, @Parameter and @RequestBody. The @Schema annotation has a complex set of possible combinations. It can be placed on POJOs and referenced from many other annotations.

For examples of annotations, see link:https://github.com/eclipse/microprofile-open-api/wiki/Annotation-Samples[Annotation Samples]

== Static OpenAPI files

Take the initial output from `/openapi` as a starting point to document your APIs with Static OpenAPI files. The static files can also be written before any code, which is an approach often adopted by enterprises that want to lock-in the contract of the API. The OpenAPI document is referred as the "source of truth" in this case, by which the client and provider must abide.

You can use a static OpenAPI file in YAML format or JSON format.

For examples of Static OpenAPI files, see link:https://github.com/eclipse/microprofile-open-api/wiki/Static-File-Samples[Static File Samples].

== Programming model

You can provide OpenAPI elements via Java POJOs. For a complete set of models see,  link:https://github.com/eclipse/microprofile-open-api/tree/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations[org.eclipse.microprofile.openapi.models] package.

Use link:https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/OASFactory.java[OASFactory] to create all the elements of an OpenAPI tree, and the link:https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/OASModelReader.java[OASModelReader] interface to bootstrap the OpenAPI model tree used by the processing framework.

For examples of OASModelReader, see link:https://github.com/eclipse/microprofile-open-api/wiki/OASModelReader-Samples[OASModelReader Samples].

== Filter

With link:https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/OASFilter.java[OASFilter], you can  receive callbacks for various key OpenAPI elements. To use it, create an implementation of the interface and register it using the `mp.openapi.filter` configuration key, where the value is the fully qualified name of the filter class.

For examples of OASFilter, see link:https://github.com/eclipse/microprofile-open-api/wiki/OASFilter-Samples[OASFilter Samples].

==OpenAPI UI

The native OpenAPI UI is value-add from Open Liberty is that ships out of the box. This UI is built from the link:https://github.com/swagger-api/swagger-ui[Open Source Swagger UI] and renders the generated `/openapi` document into a user friendly page. It has the ability to `Try out` each endpoint, making an invocation to the back-end straight from the UI.

The UI, available from the endpoint `/openapi/ui` can also be link:https://www.ibm.com/support/knowledgecenter/en/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_api_mpopenapi_custom.html[customized].
