// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:seo-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:page-layout: general-reference
:page-type: general
= Documenting microservice APIs with OpenAPI

MicroProfile OpenAPI is a MicroProfile community programming model for OpenAPI.
With MicroProfile OpenAPI, Java developers can generate structured documentation from their JAX-RS applications.

The structured documentation helps other developers and microservices understand and communicate with your microservice.
Developers can write a web service to communicate with the REST API of another web service only if they have the relevant information to do so.
MicroProfile OpenAPI specification facilitates this communication by generating human and machine-readable documentation on an easy to use interface without the need to access the source code.

There are two main approaches to generate an OpenAPI document, code-first and design-first.
In the code-first approach, the developer can generate documentation of the REST API from the source code.
The reference document that is produced, lists all the API endpoints and descriptions of how to use them.
Alternatively, in the design-first approach, you can use a set of predefined models to manually create all elements of the OpenAPI tree.
You can even generate the stubs for the source code, including client libraries for the API, from this manually created documentation.

== Code-first approach

In the code-first approach, you can generate basic API documentation from your JAX-RS application; the annotations are processed by default.
Then, you can augment the JAX-RS annotations with OpenAPI annotations, which are processed to generate the documentation.
Adding annotations takes less work and gives useful explanation of the different ports of the API.

The following example shows a JAX-RS request to list hostnames in the inventory.
The OpenAPI annotations in the example provide more useful and explanatory information about the operation:

[source,java]
----
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @APIResponse(
        responseCode = "200",
        description = "host:properties pairs stored in the inventory.",
        content = @Content(
            mediaType = "application/json",
            schema = @Schema(
                type = SchemaType.OBJECT,
                implementation = InventoryList.class)))
    @Operation(
        summary = "List inventory contents.",
        description = "Returns the currently stored host:properties pairs in the "
        + "inventory.")
    public InventoryList listContents() {
        return manager.list();
    }
----

In the following OpenAPI documentation example code, the JAX-RS framework generates the `path /inventory/systems` path based on the value of the `@Path` annotation, and the value of the `operationId` key (`listContents`) based on the name of the method (`listContents()`).
The other parts of the document are generated from the OpenAPI annotations that the developer annotated the code with.
For example, the `@Operation` annotation provides more meaningful information about what the operation does and why; in this case, the operation returns a list of the hostnames with properties of each host that are currently stored by the inventory web service.

[source,java]
----
/inventory/systems:
  get:
    summary: List inventory contents.
    description: Returns the currently stored host:properties pairs in the inventory.
    operationId: listContents
    responses:
      200:
        description: host:properties pairs stored in the inventory.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryList'
----

The information that is provided through the OpenAPI annotations augments the basic API documentation that is generated by the JAX-RS framework.

See here for the link:https://github.com/eclipse/microprofile-open-api/wiki/Annotation-Samples[annotations available].

You can further use link:http://download.eclipse.org/microprofile/microprofile-open-api-1.1/microprofile-openapi-spec.html#_filter[filters] to organize your APIs, for example, choose to expose some APIs to one audience and other APIs to another audience.

== Design-first approach

An alternative approach is to design the REST API in an editor, such as the Swagger editor, before any code.
With this approach, you can spot any problems in the design before implementation.
In large companies, it is important to have consistent, usable APIs reviewed and agreed by the relevant people that it is a good API design.
This API design then forms a contract and must be implemented as agreed.

You can write this API design in YAML or JSON, which can then be used to generate the documentation and, optionally, even stubs for the API code itself.
You can then also augment the documentation with annotations in the code as described.

For examples of Static OpenAPI files, see link:https://github.com/eclipse/microprofile-open-api/wiki/Static-File-Samples[Static File Samples].

== Filter

With OASFilter, you can receive callbacks for various key OpenAPI elements.
To use OASFilter, create an implementation of the interface and register it using the `mp.openapi.filter` configuration key, where the value is the fully qualified name of the filter class.

For examples of OASFilter, see link:https://github.com/eclipse/microprofile-open-api/wiki/OASFilter-Samples[OASFilter Samples]

== Viewing and formatting API documentation

The documentation that is generated for the REST API is available at the `/openapi` endpoint of your web service.
The documentation is formatted by using the standard OpenAPI user interface (UI) and a default stylesheet.
You can optionally customize the stylesheet for your web service.
You can also link:https://www.ibm.com/support/knowledgecenter/en/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_api_mpopenapi_custom.html[customize] the UI available from the endpoint `/openapi/ui`.
