// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:seo-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:page-layout: general-reference
:page-type: general
= OpenAPI documentation for microservices

OpenAPI is a standardized mechanism for developers to describe REST APIs. With OpenAPI you can describe REST APIs and generate API documentation from the APIs themselves. MicroProfile OpenAPI is a specification outlined as an official set of annotations and interfaces that help developers successfully generate OpenAPI documentation for their Java RESTful APIs.

You can generate the OpenAPI document in multiple ways.

== Annotations

With MP OpenAPI, JAX-RS annotations are processed by default. You can augment the existing code with OpenAPI annotations without rewriting portions of the OpenAPI document that are already covered by the JAX-RS framework.

Vendors must process all the relevant JAX-RS annotations, like @Path and @Consumes, and Java objects used as input or output to JAX-RS operations. Developers can deploy their existing JAX-RS application into a MP OpenAPI vendor and check out the output from `/openapi`.

== Static OpenAPI files

Take the initial output from `/openapi` as a starting point to document your APIs with Static OpenAPI files. The static files can also be written before any code, which is an approach often adopted by enterprises that want to lock-in the contract of the API. The OpenAPI document is referred as the "source of truth" in this case, by which the client and provider must abide.

== Programming model

Use the API interfaces to provide a bootstrap  OpenAPI model tree.

== Filter

Sometimes application developers might need to update or remove certain elements and fields of the OpenAPI document. This is done via a filter, which is called once after all other documentation mechanisms have completed.
