// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:seo-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:page-layout: general-reference
:page-type: general
= Documenting microservice APIs with OpenAPI

MicroProfile OpenAPI is a MicroProfile community programming model for OpenAPI.
With MicroProfile OpenAPI, Java developers can generate structured documentation from their JAX-RS applications.

The structured documentation helps other developers and microservices understand and communicate with your microservice.
Developers can write a web service to communicate with the REST API of another web service only if they have the relevant information to do so.
MicroProfile OpenAPI specification facilitates this communication by generating human and machine-readable documentation on a simple interface without the need to access the source code.

There are two main approaches to generate an OpenAPI document, code-first and design-first.
In the code-first approach, the developer can generate documentation of the REST API from the source code.
The reference document that is produced, lists all the API endpoints and descriptions of how to use them.
Alternatively, in the design-first approach, you can use a set of predefined models to manually create all elements of the OpenAPI tree.
You can even generate the stubs for the source code, including client libraries for the API, from this manually created documentation.

== Code-first approach

In the code-first approach, you can generate basic API documentation from your JAX-RS application; the annotations are processed by default.
Then, you can augment the JAX-RS annotations with OpenAPI annotations, which are processed to generate the documentation.
Adding annotations takes less work and gives useful explanation of the different parts of the API.

The following example shows a JAX-RS request to list hostnames in the inventory.
The OpenAPI annotations in the example provide more useful and explanatory information about the operation:

[source,java]
----
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @APIResponse(
        responseCode = "200",
        description = "host:properties pairs stored in the inventory.",
        content = @Content(
            mediaType = "application/json",
            schema = @Schema(
                type = SchemaType.OBJECT,
                implementation = InventoryList.class)))
    @Operation(
        summary = "List inventory contents.",
        description = "Returns the currently stored host:properties pairs in the "
        + "inventory.")
    public InventoryList listContents() {
        return manager.list();
    }
----

In the following OpenAPI documentation example that is generated from the example code, the JAX-RS framework generates the `inventory/systems` path based on the value of the `@Path` annotation.
The JAX-RS framework also generates the value of the `operationId` key (`listContents`) based on the name of the method (`listContents()`).
The other parts of the document are generated from the OpenAPI annotations in the code.
For example, the `@Operation` annotation provides more meaningful information about what the operation does and why.
In this case, the operation returns a list of the hostnames with properties of each host that are currently stored by the inventory web service.

[source,java]
----
/inventory/systems:
  get:
    summary: List inventory contents.
    description: Returns the currently stored host:properties pairs in the inventory.
    operationId: listContents
    responses:
      200:
        description: host:properties pairs stored in the inventory.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryList'
----

The information that is provided through the OpenAPI annotations augments the basic API documentation that is generated by the JAX-RS framework.

See the link:https://www.openliberty.io/docs/ref/microprofile/3.0/#package=org/eclipse/microprofile/openapi/annotations/package-frame.html&class=org/eclipse/microprofile/openapi/annotations/Operation.html[MicroProfile OpenAPI Javadoc] for the annotations available.
You can further use link:https://github.com/eclipse/microprofile-open-api/wiki/OASFilter-Samples[filters] to organize your APIs. For example, choose to expose some APIs to one audience and other APIs to another audience.

== Design-first approach

An alternative approach is to design the REST API in an editor, such as the link:https://editor.swagger.io/[Swagger editor], before any code.
With this approach, you can spot any problems in the design before implementation.
In large companies, it is important to have consistent, usable APIs reviewed and verified by the relevant people that it is a good API design.
This API design then forms a contract and must be implemented as agreed.

You can write this API design in YAML or JSON, which can then be used to generate the documentation and, optionally, even stubs for the API code itself.
You can then also augment the documentation with annotations in the code as described.

For more information, see https://openliberty.io/guides/microprofile-openapi.html#using-pregenerated-openapi-documents[Using pregenerated OpenAPI documents].

== Filter components in and out of API documentation

Filters give the users the flexibility to modify the document after it is generated.
With filters, you can implement an interface in your application.
So when a component of the documentation is processed, it calls your implementation and you can either add or remove content.

== View and format API documentation

The documentation that is generated for the REST API is available at the `/openapi` endpoint of your web service.
The documentation is formatted by using the standard OpenAPI user interface (UI) and a default stylesheet.

Ready to try out documenting APIs with Open Liberty for yourself? Check out the guide for link:https://openliberty.io/guides/microprofile-openapi.html[Documenting RESTful APIs].
