// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:seo-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:page-layout: general-reference
:page-type: general
= Documenting microservice APIs with OpenAPI

OpenAPI is a standardized mechanism to describe REST APIs. The MicroProfile OpenAPI specification is an official set of annotations and interfaces to help developers generate OpenAPI documentation for Java RESTful APIs.

OpenAPI, previously known as Swagger, defines a standard interface for documenting and exposing RESTful APIs. This standard interface enables both humans and computers to process a web service available through its REST API without directly accessing the source code of the web service. MicroProfile OpenAPI provides a set of Java interfaces and programming models that enable Java developers to natively produce OpenAPI documents from their JAX-RS applications.

Developers can communicate with the REST API in their web service only if they have the relevant information to do so. It is important to document APIs when they are published so that other developers can use them.

There are two main ways to generate a link:https://swagger.io/docs/specification/about/[OpenAPI] document. The developer can generate documentation of the REST API from the source code of the REST API itself. The reference document thus produced, lists all the API endpoints and descriptions of how to use them. Alternatively, the developer can start by designing the API in the form of structured documentation that they can then augment with annotations in the code. The developer can even generate the stubs for the source code, including client libraries for the API, from this manually created documentation.

== Processing annotations

You can augment the existing code with OpenAPI annotations, which provide detailed documentation for the REST API.

For example, the following code example shows JAX-RS code to request the list of host names in the inventory. The code has been annotated with OpenAPI annotations to provide more useful and explanatory information about the operation:

[source,java]
----
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @APIResponse(
        responseCode = "200",
        description = "host:properties pairs stored in the inventory.",
        content = @Content(
            mediaType = "application/json",
            schema = @Schema(
                type = SchemaType.OBJECT,
                implementation = InventoryList.class)))
    @Operation(
        summary = "List inventory contents.",
        description = "Returns the currently stored host:properties pairs in the "
        + "inventory.")
    public InventoryList listContents() {
        return manager.list();
    }
----

In the following OpenAPI documentation example that is generated from the example code, the JAX-RS framework generates the path /inventory/systems based on the value of the @Path annotation, and the value of the operationId key (listContents) based on the name of the method (listContents()). The other parts of the document are generated from the OpenAPI annotations with which the developer annotated the code. For example, the @Operation annotation provides more meaningful information about what the operation does and why; in this case, the operation returns a list of the host names with properties of each host that are currently stored by the inventory web service. This is described by the summary and description keys in the @Operation annotation:

[source,java]
----
/inventory/systems:
  get:
    summary: List inventory contents.
    description: Returns the currently stored host:properties pairs in the inventory.
    operationId: listContents
    responses:
      200:
        description: host:properties pairs stored in the inventory.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryList'
----

The information provided through the OpenAPI annotations augment the basic API documentation that is generated by the JAX-RS framework.

For examples of annotations, see link:https://www.openliberty.io/docs/ref/microprofile/3.0/#package=org/eclipse/microprofile/openapi/annotations/package-frame.html&class=org/eclipse/microprofile/openapi/annotations/Components.html[Annotation Samples]

== Manually created REST API documentation

You can generate the static files before any code with an editor like Swagger editor. In this approach, popularly known as the 'design first' approach, the API contract is designed first before writing any code. The API contract acts as the central draft, often referred to as the "source of truth". This approach is considered efficient as it helps to spot issues in the design, before writing any code rather than after the implementation.

You can use a static OpenAPI file in YAML format or JSON format.

For examples of Static OpenAPI files, see link:https://github.com/eclipse/microprofile-open-api/wiki/Static-File-Samples[Static File Samples].

== Filter

With link:https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/OASFilter.java[OASFilter], you can receive callbacks for various key OpenAPI elements. To use OASFilter, create an implementation of the interface and register it using the `mp.openapi.filter` configuration key, where the value is the fully qualified name of the filter class.

For examples of OASFilter, see link:https://github.com/eclipse/microprofile-open-api/wiki/OASFilter-Samples[OASFilter Samples].

== Viewing and formatting API documentation

The native OpenAPI UI from Open Liberty is built from the open source link:https://github.com/swagger-api/swagger-ui[Swagger UI] and renders the generated `/openapi` document into a user friendly page. It can `Try out` each endpoint, making an invocation to the backend from the UI.

You can also link:https://www.ibm.com/support/knowledgecenter/en/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_api_mpopenapi_custom.html[customize] the UI available from the endpoint `/openapi/ui`.
