// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: MicroProfile Metrics 2.0 introduces multiple changes that must be considered when you migrate applications from MicroProfile Metrics 1.x. These changes include both architectural and API changes.
:seo-title: Migrating applications from MicroProfile Metrics 1.x to MicroProfile Metrics 2.0
:seo-description: MicroProfile Metrics 2.0 introduces multiple changes that must be considered when you migrate applications from MicroProfile Metrics 1.x. These changes include both architectural and API changes.
:page-layout: general-reference
:page-type: general
= Migrating applications from MicroProfile Metrics 1.x to MicroProfile Metrics 2.0

MicroProfile Metrics 2.0 introduces several changes that must be considered when you migrate applications from MicroProfile Metrics 1.x. These changes include both architectural and API changes. To review a detailed list of updates that are included in MicroProfile Metrics 2.x, see the https://github.com/eclipse/microprofile-metrics/releases[MicroProfile Metrics specification].

== Counter and Concurrent Gauge

In MicroProfile Metrics 1.x, the behavior of the counter metric was either monotonic or non-monotonic. A monotonic counter was only able to count incrementally, whereas a non-monotonic counter was able to be both incremented and decremented. In MicroProfile Metrics 2.x, this dual behavior is separated. A counter in MicroProfile Metrics 2.x is inherently monotonic, and a new type of metric, called a concurrent gauge, is introduced with this release. The concurrent gauge metric exhibits the behavior of what was formerly the non-monotonic counter. Neither the counter metric nor the concurrent gauge metric has the monotonic parameter.

The following example shows how a counter metric is used in MicroProfile Metrics 1.x:
----
@Counted(name=“countConcurrent")
void somethingToCountInParallel() {
    // method logic here...
}

@Counted(name=“countSequential“, monotonic=true)
void somethingToCount() {
     // method logic here...
}
----

The following example shows how a counter metric is used in MicroProfile Metrics 2.x:
----
NEED EXAMPLE HERE
----

== Metadata

With MicroProfile Metrics 2.x, the Metadata object cannot be directly constructed. It can be created only with the use of a MetadataBuilder object, and the Metadata object that is constructed is immutable. Additionally, tag values are no longer associated with Metadata objects.

The following example shows how a Metadata object is constructed in MicroProfile Metrics 1.x:
----
Metadata servletCounterMetadata = new Metadata("servletCounter", "Servlet Counter Display Name", "This is a description", MetricType.Counter, MetricUnits.NONE, "tagKey=tagValue");
servletCounterMetadata.setName("newName");
----

The following example shows how a Metadata object is constructed in MicroProfile Metrics 2.x:
----
Metadata servletCounterMetadata = Metadata.builder().withName("servletCounter").withDisplayName("Servlet Counter Display Name").withDescription("This is a description").withType(MetricType.Counter).withUnits(MetricUnits.NONE).build();
----

== Tags

The metric tags are no longer associated with Metadata objects. With MicroProfile Metrics 2.x, tags are independent entities within the MetricRegistry. This change comes along with the introduction of multi-dimensional metrics. In Microprofile Metrics 1.x, metrics were one-dimensional meaning that only one metric of any metric name was able to be created. Also, only one set of tags was able to be associated with a metric name. In MicroProfile Metrics 2.x, there can be multiple metrics with the same name and of the same type if the metrics have a different set of tags. The Java API introduced a Tag object that must be created and passed into the MetricRegistry when you register a metric programmatically. The following example shows how a Tag object is constructed and used in MicroProfile Metrics 2.x:

----
Tag firstTag = new Tag("TagOneName", "TagOneValue");
Tag secondTag = new Tag("TagTwoName", "TagTwoValue");
metricRegistry.counter(servletCounterMetadata, firstTag, secondTag);
----

== Prometheus/OpenMetric + JSON output

----
This section is in progress.
----
