:page-layout: general-reference
:page-type: general
:page-description: Microservice architecture is a popular approach for building cloud-native applications in which each capability is developed as an independent service. It enables small, autonomous teams to develop, deploy, and scale their respective services independently.
:page-categories: MicroProfile
:seo-title: MicroProfile simplifies developing cloud-native Java microservices
:seo-description: Microservice architecture is a popular approach for building cloud-native applications in which each capability is developed as an independent service. It enables small, autonomous teams to develop, deploy, and scale their respective services independently.
= Configuring Open Liberty as an SSO provider in a dev/test environment

In an increasingly fragile world of the Internet, user credentials are precious commodities that need to be protected. With Single Sign On (SSO), users can not only sign up easily but also don’t need to be worried that that their details are being accessed by anyone. Open Liberty is a lightweight framework to help you build fast and efficient cloud-native apps while at the same time perform identity management for you.

You can configure Open Liberty as an SSO provider, so that web users can authenticate once when accessing Liberty resources such as HTML, JavaServer Pages (JSP) files, and servlets, or accessing resources in multiple Liberty servers that share the same Lightweight Third Party Authentication (LTPA) keys.

== Open IDConnect

OpenID Connect (OIDC) is a simple identity protocol over OAuth 2.0 and is becoming the accepted Internet Single Sign-on (SSO) protocol. OIDC works well with cloud, mobile, and native applications. OIDC lets a client  request the identity of the user as an ID token in a standardized, REST-like manner.

The client application here operates as an OpenID Connect Relying Party (RP); and relies on Open Liberty as the OpenID Connect Provider (OP) to do its user authentication. The RP receives user identity information from the OP and passes the identity information in the ID token to the back-end Liberty application server in the HTTP Request header. The application server can extract user identity information from the HTTP header to perform further authorization.

Some of the benefits of using Liberty as the OP are, Liberty OP can be integrated with the Liberty LDAP user registry.(linking), Liberty OP can be configured as token services by delegating user authentication to SAML identity provider or another OpenID Connect provider, Liberty OP is highly customizable, and you can customize the claims in ID Token, userinfo, login form, consent form.


== Configuring Open Liberty as an SSO provider

You can configure a Liberty server to act as an OpenID Connect Provider by enabling the openidConnectServer-1.0 feature in Liberty.

The OpenID Connect Provider (openidConnectServer-1.0) feature can be configured to manage user authentication for use by OpenID Connect clients and microservices. The OpenID Connect Provider can work directly with a user registry such as LDAP or act as an identity broker and delegate to another security provider.

Add the `openidConnectServer-1.0` Liberty feature and any other needed features to the `server.xml` file. The `transportSecurity-1.0` feature is also required for the `openidConnectServer-1.0` feature.

[source, java]
----
<feature>openidConnectServer-1.0</feature>
<feature>transportSecurity-1.0</feature>
----

Define an `OAuth` service provider. The configuration of an `OAuth` service provider includes the appropriate `oauth-roles`, `oauthProvider`, and user registry elements. Any user that is authorized to use OpenID Connect must also be mapped to the authenticated `oauth-role`.

In the following example, the OP expects the client's SSL port to be set to 443.

[source, java]
----
<openidConnectProvider id="OidcConfigSample" oauthProviderRef="OAuthConfigSample" />

<oauthProvider id="OAuthConfigSample">
<localStore>
<client name="client01" secret="{xor}LDo8LTor"
displayname="client01"
scope="openid profile email">
   <redirect>https://server.example.com:443/oidcclient/redirect/client01</redirect>
   <redirect>https://server2.example.com:443/oidcclient/redirect/client01</redirect>
</client>
</localStore>
</oauthProvider>
----

Add an `openidConnectProvider` element whose `oauthProviderRef` attribute references the configured `oauthProvider`. Each `oauthProvider` can be referenced only by one `openidConnectProvider`, and two or more `openidConnectProvider` elements cannot reference to the same `oauthProvider`. The name attribute and the secret attribute of the client element must match the client ID and the client secret of the corresponding OpenID Connect Client.

Configure the truststore of the server to include the signer certificates of the OpenID Connect Relying Parties, or clients, that are supported.

Modify the SSL configuration of the server to use the configured truststore.

[source, java]
----
<sslDefault sslRef="DefaultSSLSettings" />
<ssl id="DefaultSSLSettings" keyStoreRef="myKeyStore" trustStoreRef="myTrustStore" />
<keyStore id="myKeyStore" password="{xor}Lz4sLCgwLTs=" type="jks" location="${server.config.dir}/resources/security/BasicKeyStore.jks" />
<keyStore id="myTrustStore" password="{xor}Lz4sLCgwLTs=" type="jks" location="${server.config.dir}/resources/security/BasicTrustStore.jks" />
----

OpenID Connect is configured to use the default SSL configuration that is specified by the server. Therefore, the default SSL configuration for the server must use the truststore that is configured for OpenID Connect.
