// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:seo-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:page-layout: general-reference
:page-type: general
= OpenAPI documentation for microservices


OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice. With OpenAPI you can describe REST APIs and easily generate API documentation from the APIs themselves. so that other developers can look up how to use your API in their own microservice and enable their microservice to call yours. Alternative you can also write the API doc first and generating the API from the doc.
 MicroProfile OpenAPI is a specification outlined as an official set of annotations and interfaces that help developers successfully generate OpenAPI v3 documentation for their Java RESTful APIs.

You can provide input for the generation of the resulting OpenAPI document in multiple ways.

== Annotations

Using annotations means developers don’t have to re-write the portions of the OpenAPI document that are already covered by the JAX-RS framework (e.g. the HTTP method of an operation). This is the most common path, so definitely check out some of the examples to get familiar with some of these annotations and their generated output.
Because all JAX-RS annotations are processed by default, you can augment the existing code with OpenAPI annotations without needing to rewrite portions of the OpenAPI document that are already covered by the JAX-RS framework.

== Static OpenAPI files

Take the initial output from /openapi as a starting point to document your APIs via Static OpenAPI files. It’s worth mentioning that these static files can also be written before any code, which is an approach often adopted by enterprises that want to lock-in the contract of the API. In this case, we refer to the OpenAPI document as the "source of truth", by which the client and provider must abide.

The MicroProfile Config API externalizes configuration from microservices, keeping it separate from the source code. With MicroProfile Config, external configuration can be injected into services in the containers without repackaging them.

Applications can use MicroProfile Config as a single API to retrieve configuration information from different sources. Configuration data can come from different locations and in different formats – link:/docs/ref/config/[system properties], link:/docs/ref/config/[system environment variables], properties files, XML files, or data sources. In MicroProfile Config, these data sources are called ConfigSources. The same configuration property can be defined in multiple ConfigSources. A prioritization can be used to determine which ConfigSource is used for the property value. Each ConfigSource has a specified priority, which is defined by its ordinal value. A higher ordinal means that the values taken from this ConfigSource override ConfigSources with a lower ordinal value.

== Programming model

Use the API interfaces to provide a bootstrap (or complete) OpenAPI model tree.

== Filter

Additionally, a Filter is described which can update the OpenAPI model after it has been built from the previously described documentation mechanisms.
