// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Before you run a container in production, harden the container image to remove any potential vulnerabilities that might allow exploitation of your server config or install.
:seo-title: Operating system security hardening
:seo-description: Before you run a container in production, harden the container image to remove any potential vulnerabilities that might allow exploitation of your server config or install.
:page-layout: general-reference
:page-type: general
= Operating system security hardening

Operating system (OS) intrusions occur when unauthorized users can log in to the OS and gain access to sensitive resources.
Before you run a container in production, harden the container image to remove any potential vulnerabilities that might allow exploitation of your server config or install.

== Open Liberty Docker images
A container that runs in production should have only the tools and packages that you need to run your application. You can find Open Liberty Docker images and related information in link:https://hub.docker.com/_/open-liberty[Docker Hub].

The simplest way to securely run Open Liberty is to start with an existing Open Liberty Docker image, which is already set up with basic security protocols.
Although Open Liberty Docker images have basic security already configured, it is recommended that you take steps to harden an image if you intend to use it in production.
Check the following things about your Open Liberty image to verify it's hardened for production:

* Confirm that the Open Liberty server's identity doesn't own the server's config and only has read access to it.
Use the `WLP_OUTPUT_DIR` environment variable to point to the logs. The server ID only owns the directory or file where `WLP_OUTPUT_DIR` points.
* Ensure that any sensitive information in the `server.xml` file is AES encrypted.
* Disable all non-TLS ports by setting ports to `-1` in the `httpEndpoint` stanza's 'httpPort' argument.
* Use the link:/docs/ref/feature/#transportSecurity.html[Transport Security feature] instead of the link:/docs/ref/feature/#ssl.html[SSL feature].
* Add `webAppSecurity ssoRequiresSSL=’true’ to the `server.xml` file.
* Add `webAppSecurity httpOnlyCookies=’true’ to the `server.xml` file.
* Set `httpOptions removeServerHeader="true"` in the `server.xml` file.
* Set `webContainer disableXPoweredBy="true"` in the `server.xml` file.

If you extend an Open Liberty image for production use, opt for the leanest possible configuration by adding only tools and packages that are essential to your application.
Using a minimal image reduces the number of OS vulnerabilities that you bundle with your application.

== Stay current with Open Liberty
Keep your version of Open Liberty up to date.
Open Liberty's zero migration policy means that you can move to a later version without changing anything in your server config.
Staying on the latest version also ensures that you get the latest link:/docs/ref/general/#security-vulnerabilities.html[security fixes] because updates are first released in the current version.
After security fixes are released for the current version of Open Liberty, they are rolled back to older releases.
Container images in Docker Hub are updated every time a new version of Open Liberty is released.
Use the most recent images from Docker Hub for the containers that you run in production.

== Installation validation
You can validate your Open Liberty server installation by running the `/<wlp_install_dir/bin/productInfo validate` command.
This command uses an MD5 checksum to check your installation for errors or potential vulnerabilities.
The output message that you receive indicates whether Open Liberty was validated successfully.

== UNIX file permissions
A critical aspect of OS security is ensuring that files and directories have the appropriate permissions, and users and groups for the file are configured properly.
All UNIX files have the following attributes where permissions are assigned: *owner*, *group*, and *other*.
For each of these three, there are 3 bits assigned as an octal digit. The first bit indicates Read access, the second, Write access and the third, Execute access.
For example, when all three bits are on for an attribute, this is represented as a `7` which indicates all access: read, write, and execute.
A file with '770' permissions means that the file owner and any user in the file's group have read, write, and execute. All others have no permissions.
Generally, the last digit file permission should end in a `0` because other shouldn't have access to protected information.

By default, Open Liberty Docker images run with `USER 1001` (non-root) as part of group 0. This is to ensure these images do not run as root by default. For more information on Open Liberty docker images, refer to :
https://hub.docker.com/_/open-liberty

== Access control
It is critical to control users' access levels so that all users have the appropriate access to Open Liberty files. Users should have minimal access, based on their needs.
Different types of users (ie: Administrators, Developers, Database support, etc.) might have a need to access the config and/or logs. The following provides guidance on this:

* *The ID that the Open Liberty server uses to run*: This ID needs to read its config and write to logs, but when hardening a server, this ID should be configured with only read access to its own configuration files.
This ID can also own files, or it can be a separate ID from the file owner.

* *Users who are responsible for administering the server*: These users likely require read and write access to the server's configuration files.
Best practice: Don't share login IDs or passwords among administrators and instead set up the server configuration file system owner with a dedicated ID and permit administrators to use SUDO to switch user to this ID in order to update the configuration.

* *Users who are involved in server-related activities*: Some of these users need read access to view the logs, while other users might need limited write access.

* *Unauthorized users*: These users shouldn't have access to the config or product file systems and be treated as part of the other group. 

== Processing include files
Include files can hold portions of the config outside of the `server.xml` file.
These files are helpful in two primary situations:

* When sensitive information needs to be available for select users/groups (ie: database admins) but not the larger group with read access to the server's configuration.
* When a user needs to update only their portion of the server config.
In this situation, it is important to ensure that the user can't override config in the `server.xml` file by using the `onConflict` tag in the `<include>` element, as shown in the following example:
+
[source,xml]
----
<include location="myIncludeFile.xml" onConflict="IGNORE"/>
----
+
In this example, Open Liberty ignores XML elements in the `myIncludeFile.xml` file that are also found in the  `server.xml` file.

== Password encryption
Use AES encryption for passwords instead of Base64 encoding.
You can use the `securityUtility` command with Open Liberty for plain text encryption.
AES encryption is also preferable to XOR encryption because any XOR-encoded password is visible to any administrator.
// Insert an embedded link to the `securityUtility` command topic when it's complete

With AES encryption, the default encryption key that is used for decrypting can be overridden by setting the `wlp.password.encryption.key` property.
This property must not be set in the `server.xml` file, but in a separate config file that is included by the `server.xml` file.
This separate config file must contain only a single property declaration, and must be stored outside the normal config directory for the server.
