// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Choose how to package and deploy your application with Open Liberty to meet your needs.
:seo-title: Packaging and deploying applications
:seo-description: Choose how to package and deploy your application with Open Liberty to meet your needs.
:page-layout: general-reference
:page-type: general
= Package and deploy applications with Open Liberty

You can choose among different options for packaging, containerizing, and deploying applications with Open Liberty.
However, the simplest workflow for developing your cloud-native applications is to build applications with Maven or Gradle, containerize with Docker, and deploy to the cloud with Kubernetes or OpenShift.

== Maven and Gradle build tools
link:https://maven.apache.org/[Maven] is a build automation tool that makes managing your builds and dependencies easier.
With Maven, you use a Project Object Model (POM) file written in XML to define information about your project, and Maven downloads and installs all dependencies for you.
The link:https://github.com/OpenLiberty/ci.maven[Open Liberty Maven plug-in] helps manage your Open Liberty server and applications.
With Maven, you use a POM (Project Object Model) file written in XML to define information about your project, and Maven downloads and installs all dependencies for you.
The link:https://github.com/OpenLiberty/ci.maven[Open Liberty Maven plug-in] helps you develop and package applications with Open Liberty.
To learn more about the Open Liberty Maven plug-in, check out this guide on link:/guides/maven-intro.html[Building a web application with Maven].

Like Maven, link:https://gradle.org/[Gradle] is a build tool that provides dependency management for your projects.
However, Gradle has it's own domain-specific language (DSL) that's based on Groovy.
Similar to the Maven plug-in, the link:https://github.com/OpenLiberty/ci.gradle[Open Liberty Gradle plug-in] provides tasks for you to manage your server and applications.
However, Gradle has it's own domain-specific language that's based on Groovy.
Similar to the Maven plug-in, the link:https://github.com/OpenLiberty/ci.gradle[Open Liberty Gradle plug-in] provides tasks for you to develop and package applications with Open Liberty.
While Maven build scripts are written in XML, Gradle build scripts are made up of incremental tasks that form a program.
To learn more about the Open Liberty Gradle plug-in, check out this guide on link:https://openliberty.io/guides/gradle-intro.html[Building a web application with Gradle].

== Server packages
Open Liberty supports different server package types.
The supported package types are `zip`, `jar`, `tar`, and `tar.gz`.
If you don't specify a package type, then `zip` is the default, meaning that your application and an Open Liberty installation are packaged into a ZIP file.

=== Building a WAR deployment artifact
First, you must build your application into a WAR deployment artifact.
Use Maven or Gradle to build your application into a WAR file so that it can be packaged and deployed on Open Liberty.

For more information about Open Liberty packaging options with Maven, see the link:https://github.com/OpenLiberty/ci.maven/blob/master/docs/package.md#package[`package` goal in the Maven documentation]. For more information about Open Liberty packaging options with Gradle, see the link:https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyPackage.md#libertypackage-task[`libertyPackage` task in the Gradle documentation].
Specify `war` as the packaging type in your `pom.xml` file (for Maven) or in your `build.gradle` file (for Gradle). Then, package your application with Maven or Gradle. The result is a WAR deployment artifact that you can deploy on Open Liberty.

=== Packaging for containerization
Use Maven or Gradle to package an application before you containerize it.
Maven and Gradle both work well as part of continuous integration and continuous deployment (CI/CD) pipelines.

== Server packages
Open Liberty supports different server package types.
The supported package types are `zip`, `jar`, `tar`, and `tar.gz`.
If you don't specify a package type, then `zip` is the default, meaning that your application and an Open Liberty installation are packaged into a ZIP file.

For more information about Open Liberty packaging options with Maven, see the link:https://github.com/OpenLiberty/ci.maven/blob/master/docs/package.md#package[`package` goal in the Maven documentation]. For more information about Open Liberty packaging options with Gradle, see the link:https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyPackage.md#libertypackage-task[`libertyPackage` task in the Gradle documentation].

=== Packaging for containerization
Use Maven or Gradle to package an application before you containerize it.
Maven and Gradle both work well as part of continuous integration and continuous deployment (CI/CD) pipelines.

When you package an application for containerization and cloud deployment, specify `usr` in the `include` parameter or attribute.
This option packages only relevant files in the `wlp.user.dir` directory, effectively excluding the runtime binary files from the compressed file.

=== Packaging into a WAR deployment artifact
You can also choose to package your application into a WAR deployment artifact for deployment on an Open Liberty server.
Use Maven or Gradle to package your application into a WAR file so that it can be manually deployed on Open Liberty.

Specify `war` as the packaging type in your `pom.xml` file (for Maven) or in your `build.gradle` file (for Gradle). Then, package your application with Maven or Gradle. The result is a WAR deployment artifact that you can deploy on Open Liberty.

=== Packaging into a runnable JAR file
If you want to package locally, you can package your application and an Open Liberty installation into a link:/docs/ref/general/#runnablejarfiles.html[runnable JAR file].
The JAR file is portable and ready to deploy both the application and server together.
This local packaging method can be useful for debugging and testing during development.

To package into a runnable JAR file, specify `runnable` as the package type in the `include` parameter or attribute.
You can also specify the `minify` option in the `include` property or attribute so that your runnable JAR file contains only what you need to run your application.

== Containerization
After you package your application into a server package with `usr` contents and build it with Maven or Gradle, you can containerize it for cloud deployment.
Containerizing your server package bundles together the environment that your application needs to run.
With Docker containers, you have the portability to run your application on any machine that is running Docker.

A Docker image is a multi-layered file that serves as a template for a Docker container.
The simplest way to containerize your server package is by using the latest link:https://hub.docker.com/_/open-liberty[Open Liberty Docker images], which include the most recent feature versions and link:/docs/ref/general/#security-vulnerabilities.html[security fixes].
If you want to build your own Docker image, you need to create a link:https://docs.docker.com/engine/reference/builder/[Dockerfile].
A Dockerfile is a text file that contains commands about how an image is built.
If you choose to create your own Docker image, make sure to follow link:/docs/ref/general/#server-configuration-hardening.html[server configuration hardening best practices].

Once you have a Dockerfile, you can run the `docker build` command to build an image for the container.
Finally, the `docker run` command runs your container that houses the application.

To learn more about running applications with Open Liberty Docker images, see this guides on link:/guides/containerize.html[Containerizing microservices].

== Deployment
You can deploy web applications and enterprise applications on Open Liberty.
Deploy containerized applications to the cloud, or, for traditional environments, deploy a WAR deployment artifact on Open Liberty.

=== Deploying containerized applications
If you containerized your server package, you can deploy it to link:https://kubernetes.io/[Kubernetes] or link:https://www.openshift.com/[OpenShift].
Kubernetes is an orchestration and automation platform that is used for managing and scaling containers.
For a step-by-step introduction to Kubernetes, check out the link:https://openliberty.io/guides/kubernetes-intro.html[Deploying microservices to Kubernetes guide].
OpenShift is a project that is built on Kubernetes and adds functionality to meet enterprise needs.
For a step-by-step introduction to OpenShift, check out the link:https://openliberty.io/guides/cloud-openshift.html[Deploying microservices to OpenShift guide].

There are different cloud solutions that can run your Kubernetes or OpenShift workloads, including Amazon Web Services (AWS), Azure, IBM Cloud, and Google Cloud Platform (GCP).
Go to the link:https://openliberty.io/guides/?search=deploy[Open Liberty deployment guides] to learn the specifics of deploying to each of these services.
A cloud-based infrastructure enables you to focus on development without getting hung-up in deployment infrastructure issues.

=== Deploying a WAR file on an Open Liberty server
Deploy an application on Open Liberty by either dropping the application into the `dropins` directory, or by adding an application entry to the server config.

If you drop an application into the `dropins` directory, the application is automatically deployed.
You can otherwise deploy an application by specifying the link:https://openliberty.io/docs/ref/config/#application.html[`application` element] in the `server.xml` file.
The location can be on the file system or at a URL.
If you put an application in the `dropins` directory, don't include an entry for the application in the `server.xml` file.
If you do, the server tries to load the application twice and an error might occur.

After you deploy your application on Open Liberty, use link:/docs/ref/command/#server-commands.html[`server` commands] to manage the server that your application is running on.

== See also

* To learn how to update and deploy an application on Open Liberty with Maven and Docker, see this guide about link:https://openliberty.io/guides/getting-started.html[Getting started with Open Liberty].

* Have a Spring Boot application? To learn how to containerize, package, and run a Spring Boot application on an Open Liberty server without modification, see the guide about link:https://openliberty.io/guides/spring-boot.html[Containerizing, packaging, and running a Spring Boot application].
