// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty supports AES encryption for passwords that are stored in the `server.xml` file. When you use this option for protecting system passwords in the Open Liberty configuration, you need to understand the limits to the protection it provides.
:seo-title: Password encryption - openliberty.io
:seo-description: Open Liberty supports AES encryption for passwords that are stored in the `server.xml` file. When you use this option for protecting system passwords in the Open Liberty configuration, you need to understand the limits to the protection it provides.
:page-layout: general-reference
:page-type: general
= Password encryption

Open Liberty supports AES encryption for passwords that are stored in the `server.xml` file.
When you use this option for protecting system passwords in the Open Liberty configuration, you need to understand the limits to the protection it provides.
For information about how to obfuscate passwords for Open Liberty, see the link:docs/ref/general/securityUtility.adoc[`securityUtility` command].

== Password encryption with Open Liberty

Encrypting a password in the Open Liberty configuration doesn’t guarantee that the password is secure or protected.
It means that someone who can see the encrypted password but doesn’t know the encryption key cannot easily recover the password.

The application server process requires access to both the encrypted password and the decryption key, so both these items need to be stored on the file system that is accessible to the server runtime environment.
The encryption key is also required by anyone who encrypts a password that is placed in the server configuration.
For an attacker that has access to the same set of files as the Open Liberty server instance, applying AES encryption to the password provides no additional security over XOR encoding.

However, there are still reasons why you might consider encrypting passwords in the Open Liberty configuration.
The Open Liberty configuration is highly composable and sharable.
As such, it can be configured without an administration subsystem, so any XOR-encoded password is visible to any administrator.

Because of these design features, consider whether passwords are sensitive and need to be encrypted.
If passwords aren't sensitive, encoding them might provide little value.
If passwords are sensitive, either the configuration files that contain the passwords are security sensitive and access needs to be controlled, or the passwords are encrypted and the encoding key is protected as security sensitive.

== Server configuration files

In Open Liberty, the encryption key used for decrypting can be overridden from the default by setting the `wlp.password.encryption.key` property.
To ensure that the file that contains the key isn’t included when you run the `server dump` or `server package` command, don’t set this property in the `server.xml` file that stores the password.
Instead, set it in a separate configuration file that’s included by the `server.xml` file:

[source,xml]
----
<server>
  ...
  <include location="${shared.config.dir}/key.xml" />
</server>
----

This separate configuration file must contain only a single property declaration, and it must be stored outside the normal configuration directory for the server.

== See also

* For more information about the server configuration files, see the link:/docs/ref/config/#serverConfiguration.html[Server configuration overview].
* For information about how to obfuscate passwords for Open Liberty, see the link:docs/ref/general/securityUtility.adoc[`securityUtility` command].
