:page-layout: general-reference
:page-type: general
:page-description: The request timing feature automatically detects slow requests and logs the information when the request is completed.
:page-categories: MicroProfile
:seo-title: The request timing feature automatically detects slow and hung requests
:seo-description: The request timing feature automatically detects slow and hung requests and logs the information when the request is completed.
= Slow and hung request detection

When an application takes longer than expected to complete a request, the request can be logged as slow or hung.
Your applications need a continuous monitoring tool to detect and analyze slow and hung requests.
The link:https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html[Request Timing] feature automatically detects slow and hung requests and provides detailed information to help you find the root cause.

The `requestTiming` feature diagnoses the cause of slow web requests in application servers.
Thus, the `requestTiming` feature identifies requests that have run for longer than a slow request threshold, which you can configure.
For each request that takes too long to complete, request timing prints a warning message along with the details captured for the request into the log file.
A maximum of three messages are printed per slow request after which request timing stops monitoring the request.
The `requestTiming` feature assigns a slow or hung request a request ID that is logged along with the completion time and other information about the request.

The `requestTiming` feature also detects hung requests.
The hung request detection works similarly to slow request detection.
A request is considered to be hung when it runs for longer than a hung request threshold.
For a hung request, apart from printing a warning message along with the relevant details, the `requestTiming` feature initiates Java cores.
Three Java cores are generated for a hung request, each a minute apart.
If a previously hung request is completed, a detailed message is logged, including the ID and time of completion of the request.

== Configure slow and hung request detection

You can enable the Request Timing feature by adding `requestTiming-1.0` to the list of features in the `server.xml` file.

[source,java]
----
<featureManager>
      ...
      <feature>requestTiming-1.0</feature>
      ...
</featureManager>
----

The slow and hung request thresholds are configured by setting the `slowRequestThreshold` and `hungRequestThreshold` attributes on the `requestTiming` element in your `server.xml` file.
These attributes specify global slow and hung request thresholds for all requests that are timed.
For more details about default and configured thresholds in the Request Timing feature, see link:https://draft-openlibertyio.mybluemix.net/docs/ref/config/#requestTiming.html.

== Detect slow requests

When a request runs for longer than the `slowRequestThreshold`, the Request Timing feature generates a warning message in the messages log file.
The message includes details about the request and events that made up the request.
The default threshold value is 10 seconds.

The following example shows the format of a log message:

[source,java]
----
TRAS0112W: Request <(Request ID)> has been running on thread <THREADID> for at least <DURATION>. The following stack trace shows that this thread is currently running.
<STACK TRACE>
<DURATION AND OPERATIONS Table>
----

The message helps you analyze the reason behind the slow request, though it is difficult to determine whether the request is hung at that point or is still running slowly.
To address this issue, three messages are displayed for any slow request at the interval specified by the `<slowRequestThreshold>` attribute.
The stack trace data gives the information about the method that is running, while the request data gives details about the request, like the request ID and duration.
The three stack traces and logged details of the request help you to better understand which parts of the code are taking the longest to run.
No further warnings are logged about the request unless the duration of the request crosses the hung request detection threshold.

== Detect hung requests

If the request exceeds the `hungRequestThreshold`, a warning message is generated in the messages log file with the details about the request and events that made up the request.
A series of three Java cores is taken with a 1-minute delay between them.
Further Java cores are created only if new requests are detected to be hanging.

The following log message sample shows the log messages for a request that crossed the hung request detection threshold.
The default duration value is 10 min.
The value that is configured in the following example is 4 min.

[source,java]
----
[WARNING ] TRAS0114W: Request AAA7WlpP7l7_AAAAAAAAAAA was running on thread 00000021 for at least 240001.015ms. The following table shows the events that have run during this request.
Duration       Operation
240001.754ms + websphere.servlet.service | TestWebApp | TestServlet?sleepTime=480000
     0.095ms       websphere.session.setAttribute | mCzBMyzMvAEnjMJJx9zQYIw | userID
     0.007ms       websphere.session.setAttribute | mCzBMyzMvAEnjMJJx9zQYIw | visitCount
----

The `requestTiming` feature runs all the time and enables slow and hung requests to be documented when they occur, without the need for problem recreation to collect more data.
The `requestTiming` feature logs when a slow request is detected and when it completes.
Users can view information about a slow request that completed with the request id and the amount of time it took for the request to complete.
In addition to the global settings for slow and hung request thresholds, you can set thresholds for specific servlets or JDBC requests.
For more information, see link:https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html[Request Timing].
