// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Securing cloud-native applications is an important part of your development process as applications move from monolithic to microservices architecture.
:seo-title: Securing cloud-native microservices
:seo-description: Securing cloud-native applications is an important part of your development process as applications move from monolithic to microservices architecture.
:page-layout: general-reference
:page-type: general
= Securing cloud-native microservices

Securing cloud-native applications is an important part of your development process as applications move from monolithic to microservices architecture.
Rather than being an afterthought, security needs take precedence in the development cycle.
There are several ways in which you can ensure the security of your cloud-native microservices.

== Defense in-depth

A simple firewall does not provide adequate security in a microservices context.
You need to apply multiple layers of security to ensure that your application is safe.
In a complex  and distributed microservices environment, where multiple processes exist, a single point security like the API gateway is inadequate.
Processes like for example authentication and authorization, provide defense in depth security.


== Addressing the changed scenario

As applications move from the monolithic to microservices based environment, the security scenario needs to change too.
Network security provides security at an external level. (first line of denfense)
However, in a microservices environment your applications need to be secured internally at a granular level.

== Using an API gateway

Microservices communicate with each other through APIs.
Every point of communication offers vulnerabilities to security.
Security needs to be implemented at the access level through authentication and authorization
An API Gateway provides an entry point for client requests and protects the microservices from the client.
Thus the client does not have any access to the microservices.

== Monitoring security and tracing

Monitoring microservices is complex, and end to end monitoring  is important.
Automation in testing the containers is helpful in a microservices context.
Prometheus is an open source monitoring platform for microservices and a part of the Cloud Native Computing Foundation
Distributed Tracing offers a solution in tracking an troubleshooting points of failure in a system
