// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Securing cloud-native applications is an important part of your development process as applications move from monolithic to microservices architecture.
:seo-title: Securing cloud-native microservices
:seo-description: Securing cloud-native applications is an important part of your development process as applications move from monolithic to microservices architecture.
:page-layout: general-reference
:page-type: general
= Securing cloud-native microservices

Securing cloud-native microservices addresses the vulnerabilities in your applications based on microservices architecture.
The increased productivity, faster development, and extensive scalability in modern cloud-native microservices makes them more complex than their monolithic counterparts and results in security issues related to distributed communication, monitoring challenges, cloud specific vulnerabilities, and technological diversity concerns.

As applications move from the monolithic to microservices-based architecture, the security scenario evolves accordingly.
Microservices communicate in a distributed manner and the points of communication are vulnerable to security attacks.
Also, monitoring microservices can be complicated due to their complex nature, leading to challenges in security assessments.
Moreover, the cloud environment comes with its own vulnerabilities, which is addressed by the cloud shared responsibility model.
Furthermore, the technologically diversity of cloud native microservices technologies increases the chances for security vulnerabilities in microservices, as each technology must be identified and inspected for vulnerabilities.
The prevalence of fast-paced development cycles in microservice-based architectures hinders comprehensive security tests in development pipelines.
Consequently, vulnerable microservices could be pushed to production environments.

== Distributed communications and defense-in-depth

Microservices communicate over networks which may be insecure and exposed to security attacks.
A successful attack against these communication processes could negatively impact on microservices cooperation and orchestration as well as compromise the security of the application.
As a developer, you need to identify the services with the most sensitive information and then apply a number of security layers to protect them.
In this way, you can make sure that any potential attacker cannot crack the security on a single go, and has to go forward and try to crack the defense mechanism of all the layers.

An API Gateway API Gateway supports multiple mechanisms for controlling and managing access to your API.
An API gateway establishes a single entry point for all requests coming from all clients.
It subsequently knows how to provide an interface for all of your microservices.
By using this technique you can secure all of your microservices behind a firewall, allowing the API gateway to handle external requests and then talk to the microservices behind the firewall.

Many intrusions and more complex threats start at the access, authentication, or authorization levels. Organizations that expose an API for access outside of their organization should be sure to deploy some form of API gateway for security purposes. Whether using a device-based approach or an intelligent reverse proxy, API requests should all be inspected and authenticated. Also, API requests should be appropriately vetted, so that only the requests fitting desired criteria are permitted. Further, to ensure auditability, each and every transaction should be logged.
TLS may be used to encrypt API traffic to further secure data and communications. All API clients should be authenticated through the use of an application identifier, as well as a user identifier, such as via an SSL/TLS certificate. An OAuth authentication token may also be used. Requiring anonymous API requests to employ a unique user identifier is a must, and other traffic control policies, such as response limiting should be applied in addition to logging

== Monitoring challenges
Monitoring microservices is complex, and end-to-end monitoring is important.
Monitoring is a critical piece of the control systems of microservices,
The more complex your software gets, the harder it is to understand its performance and troubleshoot problems.
Monitoring needs an overhaul to perform well in a microservice environment.
You can't afford to run a distributed system without a solid, advanced, and reliable monitoring platform.
To avoid such challenges, you can use a method known as Distributed Tracing.
Distributed tracing is a method to pinpoint the failures and identify the reason behind it.
Not only this, but you can also identify the place at which failure is happening.
So, it is very easy to track down, which microservice is facing a security issue.
The one that was built specifically with microservices in mind and has been around the block is Prometheus.
Prometheus is an open source monitoring platform for microservices and a part of the Cloud Native Computing Foundation.

== Cloud-specific vulnerabilities

CNA are deployed in cloud environments, hence become vulnerable to the peculiar security issues affecting the cloud i.e. cloud-specific vulnerabilities
The Cloud Security Shared Responsibility Model [3] explicity proposed an approach for resolving these cloud-specific vulnerabilities.
The cloud shared responsibility model denotes that CSPs are responsible for the security of the cloud and customers are responsible for securing the data they put in the cloud. Depending on the type of deployment—IaaS, PaaS, or SaaS—customer responsibilities will be determined.
While IaaS customers retain a lot of control, they can lean on CSPs to manage security from a physical, infrastructure, network, and virtualization standpoint.
In PaaS, customers focus on deploying and managing applications (as well as managing data, assets, and permissions), CSPs take control of operating the underlying infrastructure, including guest operating systems.
SaaS places the most responsibility on the CSP. With the CSP managing the entire infrastructure as well as the applications, customers are only responsible for managing data, as well as user access/identity permissions.

== Technological diversity concerns

Microservices are built with different business capabilities by different development teams, which may use different technologies i.e. different programming languages and frameworks.
The motivation for this approach is to use the best tool for specific problems.
While this feature aids in productivity, it complicates security.
Applying vulnerability detection techniques in this application requires employment of different configuration for each microservice based on the development language.
This is imperative given the uniqueness of vulnerabilities per technology.
Furthermore, developers integrate several open source components while developing, according to OWASP [27], these components could be laden with vulnerabilities.

== Defense in depth

A simple firewall does not provide adequate security in a microservices context.
You need to apply multiple layers of security to ensure that your application is safe.
In a complex and distributed microservices environment, where multiple processes exist, a single point of security at the network level is inadequate.
Processes like authentication and authorization, hashing passwords, and encryption provide defense-in-depth security.



== Application Programming Interface (API) gateway for security

Microservices communicate with each other through APIs.
Every point of communication entails security vulnerabilities.
An API Gateway provides an entry point for client requests and protects the microservices from the client through authentication and authorization.
Thus, client does not interact with the microservices directly.

== Monitoring security and tracing

Monitoring microservices is complex, and end-to-end monitoring  is important.
Prometheus is an open source monitoring platform for microservices and a part of the Cloud Native Computing Foundation.
In the distributed tracing method of monitoring microservices, a unique ID is generated at login, which helps in tracing and troubleshooting the transaction.
