// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Securing cloud-native applications is an important part of your development process as applications move from monolithic to microservices architecture.
:seo-title: Securing cloud-native microservices
:seo-description: Securing cloud-native applications is an important part of your development process as applications move from monolithic to microservices architecture.
:page-layout: general-reference
:page-type: general
= Securing cloud-native microservices

Securing cloud-native microservices addresses the vulnerabilities in your applications based on microservices architecture.
The increased productivity, faster development, and extensive scalability in modern cloud-native microservices makes them more complex than their monolithic counterparts. This complexity results in security issues in the cloud native microservices related to distributed communication, monitoring challenges, cloud specific vulnerabilities, and technological diversity concerns.

As applications move from the monolithic to microservices-based architecture, the security scenarios change accordingly.
Microservices communicate in a distributed manner and the points of communication are vulnerable to security attacks.
Also, monitoring microservices can be complicated due to their complex nature, leading to challenges in security assessments.
Moreover, the cloud environment comes with its own vulnerabilities, which are addressed by the cloud shared responsibility model.
Furthermore, the technological diversity of cloud native microservices can create security issues.
The prevalence of fast-paced development cycles in microservice-based architectures hinders comprehensive security tests in development pipelines.
Consequently, vulnerable microservices could be pushed to production environments.

== Distributed communications and defense-in-depth

Microservices communicate over networks which may be insecure and exposed to security attacks.
A successful attack against these communication processes could negatively impact on microservices cooperation and orchestration as well as compromise the security of the application.
As a developer, you need to identify the services with the most sensitive information and then apply a number of security layers to protect them.
In this way, you can make sure that any potential attacker cannot crack the security in a single go, and has to go forward and try to crack the defense mechanism of all the layers.

An API Gateway API Gateway supports multiple mechanisms for controlling and managing access to your API.
Many intrusions and more complex threats start at the access, authentication, or authorization levels.
Organizations that expose an API for access outside of their organization should be sure to deploy some form of API gateway for security purposes.
An API gateway establishes a single entry point for all requests coming from all clients.
It subsequently knows how to provide an interface for all of your microservices.
By using this technique you can secure all of your microservices behind a firewall, allowing the API gateway to handle external requests and then talk to the microservices behind the firewall.

== Monitoring challenges

Monitoring is critical to microservices.
In a complex cloud-native microservices environment, it is difficult to understand performance and troubleshoot problems.
The monitoring needs a change in perspective to work well for microservices.
You can't afford to run a distributed system without a solid, advanced, and reliable monitoring platform.
To address such challenges, you can use Distributed Tracing.
Distributed tracing is a method to pinpoint the failures in the system and identify the reason behind it.
Furthermore, you can also identify the place where failure occurs.
So, it is very easy to track down, which microservice is facing a security issue.
Prometheus was built specifically for microservices.
Prometheus is an open source monitoring platform for microservices and a part of the Cloud Native Computing Foundation.

== Cloud-specific vulnerabilities

CNA are deployed in cloud environments, hence become vulnerable to the peculiar security issues affecting the cloud i.e. cloud-specific vulnerabilities
The Cloud Security Shared Responsibility Model, explicityy proposed an approach for resolving these cloud-specific vulnerabilities.
The cloud shared responsibility model denotes that CSPs are responsible for the security of the cloud and customers are responsible for securing the data they put in the cloud. Depending on the type of deployment—IaaS, PaaS, or SaaS—customer responsibilities will be determined.
While IaaS customers retain a lot of control, they can lean on CSPs to manage security from a physical, infrastructure, network, and virtualization standpoint.
In PaaS, customers focus on deploying and managing applications (as well as managing data, assets, and permissions), CSPs take control of operating the underlying infrastructure, including guest operating systems.
SaaS places the most responsibility on the CSP. With the CSP managing the entire infrastructure as well as the applications, customers are only responsible for managing data, as well as user access/identity permissions.

== Technological diversity concerns

Microservices are built with different business capabilities by different development teams, which may use different technologies i.e. different programming languages and frameworks.
The motivation for this approach is to use the best tool for specific problems.
While this feature aids in productivity, it complicates security.
Applying vulnerability detection techniques in this application requires employment of different configuration for each microservice based on the development language.
This is imperative given the uniqueness of vulnerabilities per technology.
Furthermore, developers integrate several open source components while developing, according to OWASP, these components could be laden with vulnerabilities.
