// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Authentication verifies the user identity based on the user credentials while authorization determines user access to restricted resources.
:seo-description: Authentication verifies the user identity based on the user credentials while authorization determines user access to restricted resources.
:page-layout: general-reference
:page-type: general
= Securing cloud native microservices

Cloud native applications are mostly microservices-based applications in a containerized environment. The microservices communicate among themselves and with other services. Applications run on different infrastructures with different security models. Any weak interaction in this complex environment is a cause for trouble. Developers need to make sure that their applications are secure. You can configure cloud native applications in Open Liberty to use external security providers for authentication and authorization.

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#authentication.html[Authentication] verifies the user identity based on user credentials while https://draft-openlibertyio.mybluemix.net/docs/ref/general/#authorization.html[authorization] determines user access to restricted resources. Jakarta EE Security configures authentication and authorization with annotations in servlets and provides `SecurityContext` API for programmatic security.

== Authentication

Applications in the cloud deal with many users and services who try to access the application resources.
Authentication verifies identity, where the user or service credentials are checked against a database for verification purposes.

Authentication happens when the application starts. The most common authentication is the username and password method. A request to access an application resource is verified against the user registry and the information
 is then returned to the application in a token form.

== Authorization

Authorization decides whether a user or service has the permissions to access resources. Authorization usually follows authentication.

In an application with restricted access, users and groups are mapped to different roles. Access to resources is based on the specific roles and how they are mapped. The authorization service grants access to the resource if the user or service is mapped to the required role or is part of a group that is mapped to the role. The service then returns a result back to the application.

== Jakarta EE security

You can configure an application in Open Liberty to use external security providers for authentication and authorization. This configuration ensures that the application never directly accesses or stores the user credentials. External security providers also save the application developers and administrators the effort of managing user accounts.

Jakarta EE Security provides the capability to configure authentication and authorization in Open Liberty. Jakarta EE Security also provides the `SecurityContext` API for programmatic security checks in application code.

Open Liberty conforms to the Jakarata EE specification for application security. It also complies with more specifications and provides extra features that are useful for securing microservices.

- `mpjwt-1.1` - This feature allows securing microservices with JSON web tokens(JWT) sent in an HTTP header. It complies with the `microprofile-jwt` specification.

- `jwt-1.0` - This feature provides convenience APIs for building and by using JWTs, so you can build one to send downstream to a secured microservice, or inspect one that was received.

- `socialLogin-1.0`, `openIdConnectClient-1.0`, `samlWeb-2.0`, `spnego-1.0` - These features allow use of external security providers to authenticate users. OpenID Connect providers issue a JWT that can be propagated downstream to secured microservices by using APIs these features provide.

For more information, see, https://openliberty.io/guides/security-intro.html.
