//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The securityUtility command supports plain text encryption and TLS certificate creation for Open Liberty.
:seo-title: securityUtility command
:seo-description: The securityUtility command supports plain text encryption and TLS certificate creation for Open Liberty.
:page-layout: general-reference
:page-type: general
= securityUtility command

The `securityUtility` command supports plain text encryption and TLS certificate creation for Open Liberty.

You can call the tool directly from the command line or allow the server to call it to create a default TLS certificate and keystore on server startup.

== Usage examples

Encode the `GiveMeLiberty` password with AES encryption:

----
securityUtility encode --encoding=aes GiveMeLiberty
----

Create a TLS certificate for the `myserver` server that is valid for 365 days with the `mypassword` password:

----
securityUtility createSSLCertificate --server=myserver --password=mypassword --validity=365 --subject=CN=myCompany,O=myOrg,C=myCountry
----

Get help information about the *createSSLCertificate* task:

----
securityUtility help createSSLCertificate
----

== Syntax

// Question for Ajay: Where should this command be run from?
Run the command from the `path_to_liberty/bin` directory.

----
securityUtility task [options]
----

task::
The task for the tool to perform.

options::
One or more optional parameters that are different based on the value of *task*.

== Tasks and options

=== encode

This task encodes the provided text by using Base64.
If no options are specified, the command enters interactive mode.
Otherwise, the provided text is encoded.
Text with spaces must be put in quotation marks.
The options included in the following table are available for the *encode* task:

[%header,cols=2*]
|===
|Option
|Description

|--encoding=encoding_type
|Specifies how to encode the password.
Supported encodings are `xor`, `aes`, and `hash`.
If this option is not provided, a default encoding of `xor` is used.
{empty} +
{empty} +
You can use the hash encoding option to encode passwords for the link:/docs/ref/general/#basic-registry.html[basic user registry].
As of 19.0.0.2, you can also use the option to encode passwords for the link:/docs/ref/config/#quickStartSecurity.html[quickStartSecurity element].

|--key=encryption_key
|Specifies the key to be used when you encode with AES encryption.
This string is hashed to produce an encryption key that is used to encrypt and decrypt the password.
The key can be provided to the server by defining the `wlp.password.encryption.key` variable whose value is the key.
If this option is not provided, a default key is used.

|--listCustom
a|Displays the information of the custom password encryption in JSON format.
The information consists of:

* name: The custom password encryption algorithm name.
* featurename: The feature name.
* description: The description of the custom password encryption.

|--notrim
|Specifies whether space characters are removed from the beginning and end of the specified text.
If this option is specified, the provided text is encoded as it is.
If this option is not specified, space characters from the beginning and end of the specified text are removed.

a|_text_
|The text to be encoded.

|===

=== createSSLCertificate

This task creates a default keystore that includes a TLS certificate for use in a server or client configuration.

Keystore details::

* location: From 19.0.0.3, in the `resource/security/key.p12` file of the server or client directory.
Through 19.0.0.2, in the `resource/security/key.jks` file of the server or client directory.
* type: From 19.0.0.3, the type is PKCS12.
Through 19.0.0.2, the type is JKS.
* password: Password that is provided with the `--password` option.
The password is needed to open the keystore file and retrieve the key from the keystore file.

Certificate details::

* type: Self-signed certificate.
* size: 2048 by default, can be customized with the `--keySize` option.
* signature algorithm: SHA256withRSA, can be customized with the `--sigAlg` option.
* validity: 365 days, can be customized with the `--validity` option.
* SubjectDN: `CN=<hostname>,OU=<client or server name>,O=ibm,C=us`, can be customized with the `--subject` option.

The options included in the following table are available for the *createSSLCertificate* task:

[%header,cols=2*]
|===
|Option
|Description

|--server=name
|Specifies the name of the Open Liberty server for which the keystore and certificate is created.
This option cannot be used if the `--client` option is specified.

|--client=name
|Specifies the name of the Open Liberty client for which the keystore and certificate is created.
This option cannot be used if the `--server` option is specified.

|--keyType=keystore type
|This option is available starting in 19.0.0.5.
Specifies the keystore type to generate.
To generate a JKS keystore, specify the `--keyType` option with the value of `JKS`.
By default, a PKCS12 keystore is generated.
However, to explicitly specify the generation of a PKCS12 keystore, specify the `--keyType` option with the value of `PKCS12`.
{empty} +
{empty} +
A PKCS12 keystore has a number of advantages over a JKS keystore.
The PKCS12 keystore is more extensible, supports stronger cryptographic algorithms, and is widely adopted.
The PKCS12 format is frequently the format that certificate authorities provide when they issue certificates.

|--keySize=size
|Specifies the certificate key bit size.
The default value is 2048.

|--password=password
|Specifies the password to be used in the keystore, which must be at least six characters in length.
This option is required.

|--passwordEncoding=password_encoding_type
|Specifies how to encode the keystore password. Supported encoding values are `xor` or `aes`.
If this option is not provided, a default value of `xor` is used.

|--passwordkey=password_encryption_key
|Specifies the key to use to encode the keystore password by using AES encryption.
This string is hashed to produce an encryption key that is used to encrypt and decrypt the password.
The key can be provided to the server by defining the `wlp.password.encryption.key` variable whose value is the key.
If this option is not provided, a default key is used.

|--validity=days
|Specifies the number of days that the certificate is valid, which must be equal to or greater than 365.
If this option is not provided, a default value of `365` is used.

|--subject=DN
|Specifies the Distinguished Name (DN) for the certificate subject and issuer.
If this option is not provided, a default value of `CN=<hostname>,OU=<server or client name>,O=ibm,C=us` is used.
{empty} +
{empty} +
The CN value is retrieved by using a Java method to get the machine's local hostname.
If the hostname cannot be resolved, the IP address is returned.

|--sigAlg
|Specifies the signature algorithm that is used to sign the self-signed certificate.
The signature algorithm that is supported depends on what is supported by the underlying JRE.
Stronger signature algorithms might require the JRE to have the unrestricted policy file in place.
{empty} +
{empty} +
The command accepts SHA256withRSA, SHA1withRSA, SHA384withRSA, SHA512withRSA, SHA1withECDSA, SHA256withECDSA, SHA384withECDSA, and SHA512withECDSA.
The signature algorithms that end with RSA create certificates with RSA keys.
The signature algorithms that end with ECDSA create certificates with Elliptical Curve (EC) keys.
{empty} +
{empty} +
If you use certificates that are created with EC keys, then include a customized ciphers list in your TLS configuration to include EC ciphers.

|--extInfo
|This option is available starting in 19.0.0.6.
Specifies any X.509 certificate extension information that it uses to create the default certificate.
By default, the Subject Alternative Name extension is added to the certificate with the host name of the server.
If the `--extInfo` option is used, the value is passed directly to the `keytool` command.
Use the syntax of the `--ext` flag on the `keytool` command.

|===

=== help

This task prints help information for a specified task.
