// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Transport Layer Security (TLS) is a security protocol that uses verified certificates and encryption keys to secure communications over the internet.
:page-layout: general-reference
:seo-title: Secure communication with TLS
:seo-description: Transport Layer Security (TLS) is a security protocol that uses verified certificates and encryption keys to secure communications over the internet.
:page-layout: general-reference
:page-type: general
= Secure communication with Transport Layer Security (TLS)

Transport Layer Security (TLS) is a security protocol that uses verified certificates and encryption keys to secure communications over the internet. TLS is an update to the Secure Sockets Layer (SSL) protocol.

You can enable TLS on your Open Liberty servers to protect communications among applications and services.
TLS helps ensure that sensitive data such as user passwords, credit card numbers, and other personal information can be transmitted securely between a client and server. It is also an important protocol for link:/docs/ref/general/#single-sign-on.html[single sign-on (SSO) authentication].
By securing the transmission of JSON Web Tokens with TLS, you can help ensure that user credentials are not exposed or tampered with as they are passed among different applications and services.

Although SSL is still used, it entails many known security vulnerabilities that can be avoided by using TLS instead.
Most websites now use TLS, which can be easily identified by the presence of the padlock icon in the address bar of an internet browser.
In order for a website to comply with the secure HTTPS protocol, its communications must be encrypted according to the TLS protocol. Most web browsers flag sites that do not comply with the HTTPS protocol as `not secure`.

== TLS protocol

TLS provides end-to-end authentication, confidentiality, and data integrity for internet communications.
Before any data is sent between a client and server, TLS confirms that each party is who they claim to be through the exchange of asymmetrically encrypted keys and digitally signed certificates.
During the TLS handshake, the client and server agree upon an encryption algorithm and a shared secret key that are used for that session only.
Any data that is transmitted is encrypted by using that algorithm and key, which only the communicating parties can access.
Furthermore, TLS-secured messages establish data integrity by creating a digital signature that the receiver uses to verify that a message was not tampered with during transmission.

=== TLS handshakes

The TLS handshake is a process by which a client and server set the terms for secure communications during a connection.
The handshake occurs before any data is exchanged.
Through this process, client and server agree on a version of the TLS protocol, select cryptographic algorithms that are called cipher suites, and authenticate one another by exchanging and verifying digital certificates.
These digital certificates are data files that contain cryptographic keys and other identifying information about a client or server. TLS certificates are digitally signed by a certificate authority, which acts as a trusted third party that can verify the identity of the parties that are exchanging information.

If one or both parties do not recognize a TLS certificate, the handshake fails and the secure connection is not established. A handshake can fail for different reasons, such as an expired or revoked certificate, or a mismatch between the TLS versions that are used by the client and server.

== TLS and Open Liberty

To configure TLS for your Open Liberty applications, enable link:/docs/ref/feature/#transportSecurity-1.0.html[the Transport Security feature]. You can configure TLS to specify how the details of the handshake and other aspects of the protocol are implemented for your application.

You can also create and configure a TLS certificate for your Open Liberty server by specifying the `createSSLCertificate` action for link:/docs/ref/general/#securityUtility.html[the securityUtility command].

== TLS and SSL

TLS updates and replaces SSL, which is now deprecated though still in use in some older devices.
TLS is more secure than SSL, thanks to stronger encryption algorithms and better message authentication.
TLS addresses many known security vulnerabilities from SSL, and adds extra capabilities, such as secure remote passwords and Kerberos support.
Although TLS replaces SSL for most websites, the term SSL is still widely used as a colloquialism and in many cases can refer to either SSL or TLS-enabled connections.
TLS and SSL are not interoperable, though TLS does provide compatibility support for older devices that still use SSL.

When you configure TLS for Open Liberty by enabling link:/docs/ref/feature/#transportSecurity-1.0.html[the Transport Security feature], the link:/docs/ref/feature/#ssl-1.0.html[Secure Socket Layer feature] is also enabled by default.

== See also

To learn more about the TLS protocol, check out link:https://www.internetsociety.org/deploy360/tls/basics/[TLS Basics] from the Internet Society.
