// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The metrics contained in this reference list are all available for Open Liberty. Use metric data to effectively monitor the status of your microservice systems.
:seo-title: Metrics reference list - openliberty.io
:seo-description: The metrics contained in this reference list are all available for Open Liberty. Use metric data to effectively monitor the status of your microservice systems.
:page-layout: general-reference
:page-type: general
= Securing cloud-native microservices.

<<<<<<< Updated upstream
The metrics reference list includes all the metrics that are available for Open Liberty. Use metric data to effectively monitor the status of your microservice systems.

Securing your cloud-native applications is an important part of your development process as applications move from monolithic to microservices architecture.

There are several ways in whcih you can ensure the security of your cloud-native microservices.

== Defense in-depth

== Addressing the changed scenario

=======
Securing cloud-native applications is an important part of your development process as applications move from monolithic to microservices architecture.

Rather than being an afterthought, security needs take precedence in the development cycle.

There are several ways in which you can ensure the security of your cloud-native microservices.

== Defense in-depth

A simple firewall does not provide adequate security in a microservices context.

You need to apply multiple layers of security to ensure that your application is safe, for example authentication and authorization.


== Addressing the changed scenario

As applications move from the monolithic to microservices based environment, the security scenario needs to change too.

>>>>>>> Stashed changes
== Using an API gateway

== Monitoring security and tracing
