// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Securing cloud-native applications is an important part of your development process as applications move from monolithic to microservices architecture.
:seo-title: Securing cloud-native microservices
:seo-description: Securing cloud-native applications is an important part of your development process as applications move from monolithic to microservices architecture.
:page-layout: general-reference
:page-type: general
= Securing cloud-native microservices

Securing cloud-native microservices addresses the vulnerabilities in your applications based on microservices architecture.
The increased productivity, faster development, and extensive scalability in modern cloud-native microservices makes them more complex than their monolithic counterparts.
This complexity results in security issues related to distributed communication, monitoring challenges, cloud-specific vulnerabilities, and technological diversity concerns.

Microservices communicate in a distributed manner and the points of communication are vulnerable to security attacks.
Also, monitoring microservices can be complicated due to their complex nature, leading to challenges in security assessments.
Moreover, the cloud environment comes with its own vulnerabilities, which are addressed by the link:https://cloud.ibm.com/docs/overview?topic=overview-shared-responsibilities[cloud shared responsibility model].
Furthermore, the technological diversity of cloud-native microservices can create security issues.
The prevalence of fast-paced development cycles in microservice-based architectures hinders comprehensive security tests in development pipelines.
Consequently, vulnerable microservices could be pushed to production environments.

== Distributed communications and defense-in-depth

Microservices communicate over networks that might be insecure and exposed to security attacks.
A successful attack against these communication processes might negatively impact the cooperation and orchestration of microservices and compromise the security of the application.
As a developer, you need to identify the services with the most sensitive information and then apply a number of security layers to protect them.
With multiple layers, you can make sure that a potential attacker can't crack the security in a single go, and instead must try to crack the defense mechanism of all layers.
An API Gateway supports multiple mechanisms for controlling and managing access to your API.
Many intrusions and more complex threats start at the access, authentication, or authorization levels.
Organizations that expose an API for access outside of their organization should deploy some form of API gateway for security purposes.
An API gateway establishes a single entry point for all requests coming from all clients.
Subsequently, it provides an interface for all of your microservices.
With this technique, you can secure all of your microservices behind a firewall, allowing the API gateway to handle external requests and talk to the microservices behind the firewall.

== Monitoring challenges

Monitoring is critical to microservices.
In a complex cloud-native microservices environment, it is difficult to understand performance and troubleshoot problems.
Developers think about monitoring differently for it to work well with microservices.
You can't afford to run a distributed system without a solid, advanced, and reliable monitoring platform.
To address such challenges, you can use distributed tracing.
Distributed tracing is a method that pinpoints the failures in the system and identifies the reason behind it.
You can also identify where failure occurs.
As a result, it is easy to track down which microservice is facing a security issue.
link:https://prometheus.io/[Prometheus] was built specifically for microservices.
Prometheus is an open source monitoring platform for microservices and a part of the Cloud Native Computing Foundation.

== Cloud-specific vulnerabilities

The cloud environment makes microservices susceptible to peculiar security issues that affect the cloud, which are known as cloud-specific vulnerabilities.
The Cloud Security Shared Responsibility Model (CSSM), explicitly proposed an approach for resolving these cloud-specific vulnerabilities.
The CSSM denotes that security providers are responsible for the security of the cloud and customers are responsible for securing the data that they put in the cloud.
Customer responsibilities are determined based the type of deployment, for example, IaaS, PaaS, or SaaS.
While IaaS customers retain a lot of control, they can lean on security providers to manage security from a physical, infrastructure, network, and virtualization standpoint.
In PaaS, customers focus on deploying and managing applications, as well as managing data, assets, and permissions, and security providers take control of operating the underlying infrastructure, including guest operating systems.
SaaS places the most responsibility on the security providers.
Security providers manage the entire infrastructure and the applications. Customers are only responsible for managing data and user access and identity permissions.

== Technological diversity concerns

Microservices are built with different business capabilities by different development teams, which can use different technologies, for example, different programming languages or frameworks.
The motivation for this approach is to use the best tools for specific problems.
While this aspect of microservice development aids in productivity, it complicates security.
Applying vulnerability detection techniques requires the use of different configurations for each microservice based on the development language.
This is imperative given the uniqueness of vulnerabilities per technology.
Furthermore, developers integrate several open source components, and according to the Open Web Application Security Project (OWASP), these components might be laden with vulnerabilities.
