//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The `securityUtility createSSLCertificate` command supports TLS certificate creation for Open Liberty.
:seo-title: securityUtility createSSLCertificate - OpenLiberty.io
:seo-description: The `securityUtility createSSLCertificate` command supports TLS certificate creation for Open Liberty.
:page-layout: general-reference
:page-type: general
= securityUtility createSSLCertificate

The `securityUtility createSSLCertificate` command supports TLS certificate creation for Open Liberty.

This command creates a default keystore that includes a TLS certificate for use in a server or client configuration.
The following details apply to the default keystore and TLS certificate that are created when you run the command:

* Keystore details:

** location: From 19.0.0.3, the location is the `resource/security/key.p12` file of the server or client directory.
Through 19.0.0.2, the location is the `resource/security/key.jks` file of the server or client directory.
** type: From 19.0.0.3, the type is PKCS12.
Through 19.0.0.2, the type is JKS.
The type can be cusomized with the `--keyType` option.
** password: The password that is provided with the `--password` option.
The password is required to open the keystore file and retrieve the key.

* Certificate details:

** type: The type is a self-signed certificate.
** size: The size is 2048, and it can be customized with the `--keySize` option.
** signature algorithm: The signature algorithm is SHA256withRSA, and it can be customized with the `--sigAlg` option.
** validity: The validity period is 365 days, and it can be customized with the `--validity` option.
** subject DN: The subject DN is `CN=<hostname>,OU=<client or server name>,O=ibm,C=us`, and it can be customized with the `--subject` option.
** Subject Alternative Name (SAN): hostname

== Usage example

Create a TLS certificate for the `myserver` server that is valid for 365 days with the `mypassword` password:

----
securityUtility createSSLCertificate --server=myserver --password=mypassword --validity=365
----

== Syntax

Run the command from the `path_to_liberty/bin` directory.

----
securityUtility createSSLCertificate [options]
----

options::
One or more optional parameters.

== Options

[%header,cols=2*]
|===
|Option
|Description

|--client=name
|Specifies the name of the Open Liberty client for which the keystore and certificate are created.
This option cannot be used if the `--server` option is specified.

|--extInfo
|This option is available starting in 19.0.0.6.
Specifies any X.509 certificate extension information that it uses to create the default certificate.
By default, the Subject Alternative Name extension is added to the certificate with the host name of the server.
If the `--extInfo` option is used, the value is passed directly to the link:https://docs.oracle.com/en/java/javase/13/docs/specs/man/keytool.html[`keytool` command].
Use the syntax of the `--ext` flag on the `keytool` command.

|--keySize=size
|Specifies the certificate key bit size.
The default value is 2048.

|--keyType=keystore_type
|This option is available starting in 19.0.0.5.
Specifies the keystore type to generate.
To generate a JKS keystore, specify the `--keyType` option with the value of `JKS`.
By default, a PKCS12 keystore is generated.
However, to explicitly specify the generation of a PKCS12 keystore, specify the `--keyType` option with the value of `PKCS12`.
{empty} +
{empty} +
A PKCS12 keystore has a number of advantages over a JKS keystore.
The PKCS12 keystore is more extensible, supports stronger cryptographic algorithms, and is widely adopted.
Certificate authorities frequently issue certificates in the PKCS12 format.

|--password=password
|Specifies the password to be used in the keystore, which must be at least six characters in length.
This option is required.

|--passwordEncoding=password_encoding_type
|Specifies how to encode the keystore password. Supported encoding values are `xor` or `aes`.
If this option is not provided, a default value of `xor` is used.

|--passwordKey=password_encryption_key
|Specifies the key to use to encode the keystore password by using AES encryption.
This string is hashed to produce an encryption key that is used to encrypt and decrypt the password.
You can provide the key by defining the `wlp.password.encryption.key` variable as the key value.
If this option is not provided, a default key is used.

|--server=name
|Specifies the name of the Open Liberty server for which the keystore and certificate are created.
This option cannot be used if the `--client` option is specified.

|--sigAlg
|Specifies the signature algorithm that is used to sign the self-signed certificate.
The signature algorithm that is supported depends on what is supported by the underlying JRE.
Stronger signature algorithms might require the JRE to have the unrestricted policy file in place.
{empty} +
{empty} +
The command accepts SHA256withRSA, SHA1withRSA, SHA384withRSA, SHA512withRSA, SHA1withECDSA, SHA256withECDSA, SHA384withECDSA, and SHA512withECDSA.
The signature algorithms that end with RSA create certificates with RSA keys.
The signature algorithms that end with ECDSA create certificates with Elliptical Curve (EC) keys.
{empty} +
{empty} +
If you use certificates that are created with EC keys, then include a customized ciphers list that includes EC ciphers in your TLS configuration.

|--subject=DN
|Specifies the distinguished name (DN) for the certificate subject and issuer.
If this option is not provided, a default value of `CN=<hostname>,OU=<server or client name>,O=ibm,C=us` is used.
{empty} +
{empty} +
The CN value is retrieved by using a Java method to get the machine's local hostname.
If the hostname cannot be resolved, the IP address is returned.

|--validity=days
|Specifies the number of days that the certificate is valid, which must be equal to or greater than 365.
If this option is not provided, a default value of `365` is used.

|===
