// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Authentication verifies the user identity based on the user’s credentials while authorization determines user access to restricted resources.
:seo-description: Authentication verifies the user identity based on the user’s credentials while authorization determines user access to restricted resources.
:page-layout: general-reference
:page-type: general
= Securing cloud native microservices

Authentication verifies the user identity based on the user’s credentials while authorization determines user access to restricted resources.

Cloud native applications are microservice oriented, containerized, and scalable applications built with cloud computing resources. You can configure cloud native applications in Open Liberty to use external security providers to handle authentication and authorization.

Jakarta EE Security configures authentication and authorization with annotations in servlets and provides SecurityContext API for programmatic security.

== Authentication and authorization in securing cloud-native microservices

Authentication verifies the user identity, whereas authorization determines whether a user has access to a certain role within the system.

== Authentication

Authentication verifies the user identity. Credentials are gathered, for example, User ID and password. Cache is checked to see if any user subject is available. If no subject is found, then the JAAS service is called. The JAAS service calls a set of login modules. One or more login modules create the subject based on credentials. The login module then calls the configured user registry for validation of credentials.•	Upon successful validation, relevant user information is collected and a SSO token is created and stored in the subject as credentials. After successful authentication, the SSO is sent back to the browser in a cookie.
The default name of the configurable cookie is ltpaToken2.

On subsequent calls, the token information is used to authenticate the user. If this authentication fails, the authentication service tries to use other authentication data, such as the user ID and password, if they still exist in the request.




== Authorization
Authorization in Liberty determines whether a user has access to a certain role within the system. Authorization specifies access rights to resources. It usually follows authentication that confirms an identity. Whereas authentication answers the question: Are you who you say you are?; authorization answers the question: Do you have permission to do what you are trying to do?
