// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: It is important to harden your Open Liberty server for production to reduce vulnerabilities and prevent security intrusions.
:seo-title: Security hardening for production - OpenLiberty.io
:seo-description: It is important to harden your Open Liberty server for production to reduce vulnerabilities and prevent security intrusions.
:page-layout: general-reference
:page-type: general
= Security hardening for production

Hardening is a general term that is used to describe the measures that are taken to enhance your system security against potential threats and risks in production.
It is important to harden your Open Liberty server configuration, application configuration, and network to reduce vulnerabilities and prevent security intrusions.

Different types of security intrusions can threaten different parts of your system.
You can employ best practices to make each part less vulnerable.
Security intrusions and vulnerabilities can be broken down into different groups:

* <<#server-configuration,Server configuration>>
* <<#network,Network>>
* <<#application-configuration,Application configuration>>

[#server-configuration]
== Server configuration
Operating system (OS) intrusions occur when users with local access attempt to cause damage or extract sensitive information.
One example of this type of intrusion is malware.
If malware is introduced into a system, unauthorized users might be able to access the server configuration and its contents.

=== Server configuration hardening considerations
* Open Liberty Docker images
* Current Open Liberty version
* Installation validation
* UNIX file permissions
* Access control
* Include file processing
* Automated updates
* Password encryption

To learn about server configuration hardening best practices, see link:/docs/ref/general/#server-configuration-hardening.html[Server configuration security hardening].

[#network]
== Network
Network intrusions occur when unauthorized users monitor or alter network traffic.
Replay attacks and man-in-the-middle (MITM) attacks are two examples of network intrusions.

=== Network hardening considerations
* Firewalls
* Security in container environments
* TLS connectivity
* LTPA
* Welcome page and headers
* Session overflow
* JMX connector

To learn about network hardening best practices, see link:/docs/ref/general/#network-hardening.html[Network security hardening].

[#application-configuration]
== Application configuration
Application configuration intrusions occur when external users run applications that derive or inherit privileges that they are not authorized to.
One example of this type of intrusion happens when an application inherits the identity of the server, giving the application unauthorized permissions.

=== Application configuration hardening considerations
* User roles and access
* Web server document root
* Secure servlets
* File serving and directory browsing
* Confidential transport guarantee

To learn about application configuration hardening best practices, see link:/docs/ref/general/#application-configuration-hardening.html[Application configuration security hardening].
