// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Before you run a container in production, harden the container image to remove any potential vulnerabilities that might allow exploitation of your server configuration or installation.
:seo-title: Operating system security hardening - OpenLiberty.io
:seo-description: Before you run a container in production, harden the container image to remove any potential vulnerabilities that might allow exploitation of your server configuration or installation.
:page-layout: general-reference
:page-type: general
= Server configuration security hardening

Operating system (OS) intrusions occur when unauthorized users are able to log in to the OS and gain access to sensitive resources.
Employ best practices with Open Liberty to harden your server configuration against potential OS attacks.

One of the ways to protect against improper access to Open Liberty code is to ensure that the file system where Open Liberty binary files are located is mounted read-only.
Another best practice is to ensure that the Open Liberty server configuration file system, which is the path where the `WLP_USER_DIR` environment variable points, is only writable to authorized server administrators.

== Open Liberty Docker images
A container that runs in production must have only the tools and packages that you need to run your application.
Before you run a container in production, harden the container image to remove any potential vulnerabilities that might allow exploitation of your server configuration or installation.

The simplest way to securely run Open Liberty is to start with an existing Open Liberty Docker image, which is already set up with basic security protocols.
Although Open Liberty Docker images have basic security that's already configured, take steps to harden an image if you intend to use it in production.
You can find Open Liberty Docker images and related information in link:https://hub.docker.com/_/open-liberty[Docker Hub].
Check the following things about your Open Liberty image to verify that it's hardened for production:

* Confirm that the Open Liberty server identity doesn’t own the directory where the server configuration is stored (`WLP_USER_DIR`) and has only read access to it.
Set the `WLP_OUTPUT_DIR` environment variable to point to the server logs with the same server identity as the owner of this directory.
* Ensure that any sensitive information in the `server.xml` file is link:/docs/ref/general/#securityUtility.html[AES encrypted].
* Disable all non-TLS ports by setting ports to `-1` in the `httpPort` argument of the `httpEndpoint` stanza.
* Use the link:/docs/ref/feature/#transportSecurity-1.0.html[Transport Security feature] instead of the link:/docs/ref/feature/#ssl-1.0.html[SSL feature].
* Add the `webAppSecurity ssoRequiresSSL=’true’` statement to the `server.xml` file.
* Add the `webAppSecurity httpOnlyCookies=’true’` statement to the `server.xml` file.
* Set the `httpOptions removeServerHeader="true"` statement in the `server.xml` file.
* Set the `webContainer disableXPoweredBy="true"` statement in the `server.xml` file.

If you extend an Open Liberty image for use in production, opt for the leanest possible configuration by adding only tools and packages that are essential to your application.
Using a minimal image reduces the number of OS vulnerabilities that you bundle with your application.

== Current Open Liberty version
Keep your version of Open Liberty up to date.
The zero migration policy of Open Liberty means that you can move to a later version without changing anything in your server configuration.
Staying on the latest version also ensures that you get the latest link:/docs/ref/general/#security-vulnerabilities.html[security fixes] because updates are first released in the current version.
After security fixes are released for the current version of Open Liberty, they are rolled back to older releases.
Container images in Docker Hub are updated every time a new version of Open Liberty is released.
Use the most recent images from Docker Hub for the containers that you run in production.

== Installation validation
You can validate your Open Liberty server installation by running the `/<wlp_install_dir/bin/productInfo validate` command.
This command uses an MD5 checksum to check your installation for errors or potential vulnerabilities.
The output message that you receive indicates whether the Open Liberty installation was validated successfully.

== UNIX file permissions
A critical aspect of server security is ensuring that files and directories have the appropriate permissions, and users and groups are configured properly.
All UNIX files have the following attributes: *file owner*, *group*, and *other*.
For each of these attributes, 3 bits are assigned as an octal digit.
The first bit indicates read access.
The second bit indicates write access.
The third bit indicates execute access.
For example, a `7` represents that all 3 bits are on for an attribute, which indicates read, write, and execute access.
A file with `770` permissions means that the file owner and any user in the group have read, write, and execute access.
All others have no permissions.
Generally, the last digit in the file permissions ends in `0` so that others don't have access to protected information.

Ensure that only administrative users are attached to the group that has write access to the server configuration files.

By default, Open Liberty Docker images run with `USER 1001`, a non-root user, as part of group `0`.
This setting ensures that these images don't run as root by default.

== Access control
It is critical to control users' access levels so that users have the appropriate access to Open Liberty files.
Non-administrative users require minimal access, based on their needs.
Different types of users might need to access the configuration or logs.
These users might include administrators, developers, or database support personnel.
The following points provide guidance on controlling users' access:

* *The ID that the Open Liberty server uses to run*:
This ID needs to read its configuration and write to logs.
However, when hardening a server, this ID must be configured only with read access to its own configuration files.
This ID can also own files, or it can be a separate ID from the file owner.

* *Users who are responsible for administering the server*:
These users likely require read and write access to the server configuration files.
A best practice is to not share login IDs or passwords among administrators.
Instead, set up the server configuration file system owner with a dedicated ID, and permit administrators to use sudo to switch to this ID to update the config.

* *Users who are involved in server-related activities*:
Some of these users need read access to view the logs, while other users might need limited write access.

* *Unauthorized users*:
These users are treated as part of the other group, so they don't have access to the configuration or product file systems.

== Include file processing
Include files can hold portions of the configuration outside of the `server.xml` file.
These files are helpful in two primary situations:

* When sensitive information needs to be available for select users or groups, for example, database administrators, but not the larger group with read access to the server configuration.
* When a user needs to update only a portion of the server configuration.
In this situation, it is important to ensure that a user can't override configuration in the `server.xml` file.
To prevent users from overriding configuration in the `server.xml` file, use the `onConflict` tag in the `<include>` element:
+
[source,xml]
----
<include location="myIncludeFile.xml" onConflict="IGNORE"/>
----
+
In this example, Open Liberty ignores XML elements in the `myIncludeFile.xml` file that are also found in the  `server.xml` file.

== Automated updates
Configuration updates must be carefully controlled in production environments to reduce the possibility that unknown changes or vulnerabilities are deployed to users.
You can disable automated configuration updates so that your production environment isn't changed unless you manually update it.

By default, each server contains a monitored application directory that's named `/dropins`.
When an application is placed in this directory, the server automatically deploys and starts the application.
If you update configuration in the `server.xml` file or `/dropins` directory, the server automatically deploys the configuration changes.

Each server also contains a monitored directory that's named `/dropins/configDropins` for configuration snippets.
If you update the configuration in this directory, the server automatically deploys the configuration changes.

To ensure that you deploy only explicitly pre-configured applications where their configuration is in the `server.xml` file, disable monitoring of the `/dropins` directory:

[source,xml]
----
<applicationMonitor updateTrigger="mbean" dropinsEnabled="false" />
----

You can also disable automatic configuration updates in the `server.xml` file by using the following configuration statement:

[source,xml]
----
<config updateTrigger="mbean" />
----

== Password encryption
Use AES encryption for passwords instead of Base64 encoding.
You can use the link:/docs/ref/general/#securityUtility.html[`securityUtility` command] with Open Liberty for plain text encryption.
AES encryption is also preferable to XOR encryption because an XOR-encoded password is visible to any administrator

With AES encryption, the default encryption key that is used for decryption can be overridden by setting the `wlp.password.encryption.key` property.
This property must not be set in the `server.xml` file, but in a separate configuration file that is included by the `server.xml` file.
This separate configuration file must contain only a single property declaration, and must be stored outside the normal configuration directory for the server.

== Other potential vulnerabilities

Hardening your server configuration is crucial to sealing off vulnerabilities and preventing attackers from gaining access to sensitive resources in your configuration file system.
Protecting these points of attack hardens your server configuration for use in production, but you need to consider other security vulnerabilities before your container and application are production-ready.
You must also ensure that you harden your link:/docs/ref/general/#application-hardening.html[application configuration] and your link:/docs/ref/general/#network-hardening.html[network] to keep your application and users safe in production.
