// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: SSO configuration with JSON Web Tokens - OpenLiberty.io
:seo-description:
= SSO configuration with JSON Web Tokens

JSON Web Token (JWT) is a standard that is used to propagate the user identity that is established by Single sign-on (SSO) between different microservice applications. By configuring SSO user authentication with a JWT, you can manage the identity that is shared between applications.

== Enabling identity management with SSO
To propagate user identity across different services with a JWT, a JWT that represents the user's identity can be obtained from an SSO method that uses OpenID Connect (OIDC). A JWT can also be created programmatically through another security method. The OIDC standard for authentication provides a framework that enables identity management with SSO. Within this framework, the Social Media Login SSO method provides a simplified process that establishes user identity. For more information, see  https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-social-config.html[SSO configuration with social media login].


== Propagating user identity with JSON Web Tokens

After the user identity is established with an SSO method, such as Social Media Login, you can use the JWT to propagate the identity to back-end services. The JWT uses claims to transfer authentication and group membership information about a user between services. The claims can verify who the user is, when the user requests were made, and any other types of information that the user agreed to be handled by you. Each consumer of the token can verify that they can trust the claims in it, by verifying that they trust the issuer's signature of the token. After the consumer verifies the signature, they know that the content of the token hasn't been altered since it was created. This JWT format allows each of the involved parties to easily agree on a specific set of claims that facilitate the propagation of the user's identity. This propagation of the user's identity can be further defined by the MicroProfile JWT feature.


== Securing microservices with MicroProfile JSON Web Tokens
The MicroProfile JWT feature extends the capabilities of the standard JWT format by providing more support to secure microservices. The MicroProfile JWT feature is designed to verify claims between two services and make accessing claim information simpler for application developers. This verification depends on the agreement between identity providers and service providers. By using the MicroProfile JWT format, the identity providers issue tokens in a way that the service providers can understand to gather information about a user.

=== MicroProfile JSON Web Token required claims
The MicroProfile JWT feature contains required claims, which must be specified to propagate user identity. A claim is a piece of information that is asserted about a subject that is represented as a name-value pair, which consists of a claim name and a claim value. The following example shows the required claims that are specified in a JSON file:

----
{
    "typ": "JWT",
   "alg": "RS256",
   "kid": "abc-1234567890"
}
{
      "iss": "https://server.example.com",
      "aud": "s6BhdRkqt3",
      "jti": "a-123",
      "exp": 1311281970,
      "iat": 1311280970,
      "sub": "24400320",
      "upn": "jdoe@server.example.com",
      "groups": ["red-group", "green-group", "admin-group", "admin"],
}
----

For more information, see https://www.eclipse.org/community/eclipse_newsletter/2017/september/article2.php#Minimum%20MP-JWT%20Required%20Claims#Minimum%20MP-JWT%20Required%20Claims[Eclipse MicroProfile - JWT RBAC Security (MP-JWT)].

=== Using JSON Web Tokens with JAX-RS applications
The MicroProfile JWT specification defines how a JWT interacts with Java EE and Jakarta EE container security so that the JWT is easily used with JAX-RS applications. For more information, see https://openliberty.io/guides/microprofile-jwt.html[Securing microservices with JSON Web Tokens].
