// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: SSO configuration with SPNEGO - OpenLiberty.io
:seo-description:

= SSO configuration with SPNEGO

The Simple and Protected GSS-API Negotiation Mechanism (SPNEGO) provides web authentication of HTTP requests to access applications. By configuring single sign-on (SSO) with SPNEGO, you can securely negotiate and authenticate HTTP requests for protected resources in applications.

SPNEGO is an extension of the Kerberos Protocol that enables the secure negotiation of a mutually supported authentication method between different applications. When a user accesses an application, an HTTP request is sent to the service that supports the application in an attempt to authenticate the user. With SPNEGO web authentication enabled on an application that supports Open Liberty application security, the authentication of HTTP requests that is initiated by the user generates an SPNEGO token.

When the service receives this token, the SPNEGO web authentication decodes and retrieves the user identity from the SPNEGO token. The identity is then used to make authorization decisions for the application.

== Kerberos Protocol
The Kerberos protocol provides a secure method of authentication between the user and the service that is being accessed. The protocol uses cryptography to enable both the user and the service to establish identities for secure web authentication. To enable the cryptography, Kerbero uses a trusted authority to issue secret keys for the encryption and decryption of credentials that is called the Key Distribution Center (KDC). The KDC contains a database of usernames and passwords for both users and Kerberos-enabled services to manage identities.

This Kerberos database is stored in the Microsoft Active Directory. The Microsoft Active Directory stores the identity information of users, applications, and resources in a centralized data repository. You can use the Microsoft domain controller to access this data to manage the authentication and authorization of different identities from a centralized location. The Microsoft Active Directory and the associated KDC are required to enable the operation of SPNEGO.

== SPNEGO web authentication flow
