// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: SSO configuration with LTPA cookies - OpenLiberty.io
:seo-description:
= SSO configuration with LTPA cookies

Lightweight Third Party Authentication (LTPA) provides single sign-on (SSO) configuration support to authenticate users only once when they are accessing applications. With LTPA enabled, you can encrypt, digitally sign, and securely transmit authentication-related data between applications.

== LTPA protocol
Secure communication between applications can be enabled by using the LTPA protocol. The LTPA protocol provides the SSO feature that requires a user to authenticate their identity only once when they are connected to an application. After the connection to the application is established, the user can access resources in other applications that exist on the same server without getting prompted to authenticate.

To enable the SSO feature, cryptographic keys are used to encrypt and decrypt user data that passes between microservices with the LTPA protocol. When all the services that are involved use the same user registry, the keys must be shared between different services for the resources in one service to access resources in other services. The configured user registry that is required with must be a centrally shared repository so that users and groups are the same, regardless of the service.
To enable the SSO feature, cryptographic keys are used to encrypt and decrypt user data that passes between applications with the LTPA protocol. When all the applications that are involved use the same user registry, the keys must be shared between different applications for the resources in one application to access resources in other applications. The configured user registry that is required with LTPA must be a centrally shared repository so that users and groups are the same, regardless of the application.

=== Configuring LTPA
When security is enabled for an Open Liberty application, LTPA is configured by default during the application start time. The default location of the automatically generated LTPA keys files is `${server.output.dir}/resources/security/ltpa.keys`. The LTPA keys are encrypted with a randomly generated key and a default password of `WebAS` is initially used to protect the keys. The password is required when you import the LTPA keys into another application. To protect the security of the LTPA keys, you must change the password. When the LTPA keys are exchanged between applications, this password must match across each application to enable SSO. You can also configure a application to use a custom LTPA keys file and expiration time in addition to your user-defined password. The following example shows the configuration of a `<ltpa>` element in a server.xml file with sample values:
----
<ltpa keysFileName="yourLTPAKeysFileName.keys" keysPassword="keysPassword" expiration="120" />
----

LTPA creates a token that contains user information, an expiration time, and is signed by the keys that exist within the application. The LTPA token is time-sensitive with a default expiration time of 120 minutes. Each of the involved applications must have their time and date synchronized. If this is not achieved, LTPA tokens are prematurely expired and cause authentication or validation failures. Coordinated Universal Time (UTC) is used by default, and all other applications must have the same UTC time.

If the receiving application use the same keys as the originating application, the token can be decrypted to obtain the user information, which then is validated to make sure that the token is not expired and that the user information in the token is valid in its registry. On successful validation, the resources in the receiving applications are accessible after the authorization check.

Each application must have valid credentials. When the credentials expire, the application is required to communicate to the user registry to authenticate. Extending the time that the LTPA token remains cached presents an increased security risk that must be considered when you are defining your security policies.

If key sharing is required between different applications, you can copy the keys from one application to another. For security purposes, the keys are encrypted with a randomly generated key, and a user-defined password is used to protect the keys. This same password is needed when you are importing the keys into another application. The password is used only to protect the keys, and is not used to generate the keys.

=== Customizing SSO configuration with LTPA cookies
With SSO configuration support, you must authenticate only once when you access resources such as HTML, JavaServer Pages (JSP) files, and servlets or access resources in multiple applications that share LTPA keys.

When a user passes authentication on one of the applications that are accessed, authentication information that is generated by the application is transported to the web browser in a cookie. The application uses the cookie to propagate the authentication information to other applications. When SSO is enabled, the LTPA token passes to other applications through cookies for web resources.

The default cookie name that is used to store the SSO token is `ltpaToken2`. If you want to use a different name for the cookie, you can customize the cookie name by using the `ssoCookieName` attribute of the `<webAppSecurity>` element. If you customize the cookie name, you must ensure that all the applications that participate in SSO use the same cookie name. The following example specifies that the user logs out after the HTTP session expires and sets the name of the SSO cookie as `myCookieName`:
----
<webAppSecurity logoutOnHttpSessionExpire="true"  ssoCookieName="myCookieName" />
----
