// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: SSO configuration with social logins - OpenLiberty.io
:seo-description:
= SSO configuration with social media login

Social Media Login is a form of single sign-on (SSO) that enables users to sign in to applications by using their existing social media account instead of creating an account specifically for the application. By configuring SSO with Social Media Login, you can simplify the registrations and logins for both users and the applications that are accessed.

== Enabling Social Media Login
When you enable social media login, the user authentication process is simplified for each of the parties that are involved. With social media login, the user accesses an application and selects a social network platform. After a social network platform is selected, a login request is sent to the social network platform to confirm the user's identity. After the user's identity is confirmed by the social network platform, a current user of the platform gets access to the application. A new user is registered as a new user and then logged into the application.

In Open Liberty, social media login is enabled by the https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html[Social Media Login feature]. The Social Media Login feature handles the authentication requirements of the application such as user and password management by using the credentials that are supplied and protected by the social network platform.  With this feature, the managers of the application are not solely responsible for securing the personal information of users and the user does not have to register for multiple online accounts, which leads to faster and more secure access.

You can enable social media login for any social media platform that uses the OAuth or OpenID Connect (OIDC) standard for authentication. OIDC is a SSO method that enables applications to assign user authentication to authorization servers that return the application claims about the authenticated user and authentication event with a standard process to the application that provides the user access. The OIDC authorization process involves specific roles that enable the identity management for secure applications. The OpenID provider (OP) is an authorization server that implements OIDC, can authenticate a user, return claims about the authenticated user, and the authentication event to a relying party or application. The Relying Party is the application that delegates user authentication to an OP and requests claims about the user from the OP.

During the OIDC authorization process, a browser accesses a protected application and is redirected to the OP. The OP interacts with the user to authenticate them. After authentication, the user's browser is redirected back to the application. The application or its container then contacts the OP and obtains a JWT that contains claims about the user, and completes authentication and authorization. If successful, the user is granted access to the application. The application can access the claims that are sent in the JWT.

To use OIDC, the application must be configured to enable the feature. However, if you use the Social Media Login feature, the entire OIDC authorization process is handled by the social media platform, which makes the process simpler.


== Configuring authentication with Social Media Login
If multiple social media providers are configured to protect a request, Open Liberty provides a default social media selection form. With the social media selection form, you can choose between available social media login providers to authenticate yourself for a protected resource request.

The options that appear on the default selection form are only the providers that are configured to protect the original resource request. Any providers that are not configured to protect the original request are not shown as options. Additionally, if only one provider is configured to protect a certain request, the selection page is not displayed. Instead, you are automatically redirected to that provider to authenticate.

The following example shows the configuration of a form for multiple-provider protected endpoints. The `facebookLogin` and the `twitterLogin` elements are configured to protect all requests because they do not specify the `authFilterRef` attribute which determines whether certain HTTP servlet requests are processed by certain social media providers:
----
<facebookLogin clientId="..." clientSecret="..." />
<twitterLogin consumerKey="..." consumerSecret="..." />
<githubLogin clientId="..." clientSecret="..." authFilterRef="filter_helloworld" />
<authFilter id="filter_helloworld">
  <requestUrl id="myRequestUrl" urlPattern="helloworld" matchType="contains" />
</authFilter>
----
=== Configuring a custom social media selection form
With Open Liberty, you can specify the location of your own selection form if you do not want to use the default page that is provided. Any custom selection page needs to receive the following HTTP request parameters and use those values to construct a valid web page:

request_url::
The original protected resource request URL, including request parameters if any are present. The custom selection page should submit the social media provider that the user selects back to this URL. For example, if the custom selection page uses an HTML form to display the social media options, the action attribute of the form should be set to this URL. Additionally, request parameters should be included as hidden inputs within the form.
request_method::
The HTTP request method of the original protected resource request. The custom selection page should use the same HTTP request method to submit the social media provider that the user selects back to the original request URL.
submit_param_name::
The name that needs to be used for the parameter or header that specifies the social media provider ID that is selected by the user. When the custom selection page submits the social media provider that the user selects back to the original request URL, the configuration ID of the social media provider needs to be specified by a parameter or header with this name.
configuration::
A JSON object that contains information about each of the social media providers that are configured to authenticate the original request.
social-media::
The top-level key that maps to a JSON array of social media configurations. Each social media configuration is a JSON object with the following entries:


When a protected resource request is received, the application determines that multiple providers protect the request and that a custom selection page is configured. The request is redirected to the custom selection page as shown in the following example:
----
HTTP/1.1 302 Found
Location: https://myhost.com/myApp/customSelection?
    request_url=https%3A%2F%2Fmyhost.com%2Facme%3Fproduct_id%3D123%26product_name%3Danvil
    &request_method=GET
    &submit_param_name=social_login_hint
    &configuration=%7B%22social-media%22%3A%5B%7B%22id%22%3A%2213579%22%2C%22display-name%22%3A%22Twitter%22%2C%22website%22%3A%22https%3A%2F%2Fwww.twitter.com%22%7D%2C%7B%22id%22%3A%2224680%22%2C%22display-name%22%3A%22Google%22%2C%22website%22%3A%22https%3A%2F%2Fwww.google.com%22%7D%2C%7B%22id%22%3A%22-123456%22%2C%22display-name%22%3A%22An%20OAuth%20Provider%22%7D%5D%7D
----
