// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: SSO configuration with social logins - OpenLiberty.io
:seo-description:
= SSO configuration with Social Login

Social Login is a form of single sign-on (SSO) that enables users to sign in to applications by using their existing social media account instead of creating an account specifically for the application. By configuring SSO with Social Login, you can simplify the registrations and logins for both users and the applications that are accessed.

== Configuring authentication with Social Login
With Social Login, the user accesses an application and selects a social network platform. After a social network platform is selected, a login request is sent to the social network platform to confirm the user's identity. After the user's identity is confirmed by the social network platform, a current user of the platform gets access to the application. A new user is registered as a new user and then logged into the application.

You can enable social login for any social media platform that uses the OAuth or OpenID Connect (OIDC) standard for authentication. OIDC is a SSO method that enables applications to assign user authentication to authorization servers that return the application claims about the authenticated user and authentication event with a standard process to the application that provides the user access. The OIDC authorization process involves specific roles that enable the identity management for secure applications. The OpenID provider (OP) is an authorization server that implements OIDC, can authenticate a user, return claims about the authenticated user, and the authentication event to a relying party or application. The Relying Party is the application that delegates user authentication to an OP and requests claims about the user from the OP.

During the OIDC authorization process, a browser accesses a protected application and is redirected to the OP. The OP interacts with the user to authenticate them. After authentication, the user's browser is redirected back to the application. The application or its container then contacts the OP and obtains a JWT that contains claims about the user, and completes authentication and authorization. If successful, the user is granted access to the application. The application can access the claims that are sent in the JWT.

To use OIDC, the application must be configured to enable the feature. However, if you use the Social Login feature, the entire OIDC authorization process is handled by the social media platform.

When you enable Social Login, the user authentication process is simplified for each of the parties that are involved. The Social Login feature handles the authentication requirements of the application such as user and password management by using the credentials that are supplied and protected by the social network platform.  With this feature, the managers of the application are not solely responsible for securing the personal information of users and the user does not have to register for multiple online accounts, which leads to faster and more secure access.
