// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty provides an auto-tuning algorithm that controls the size of its thread pool. For most applications that run on Open Liberty, it is not necessary to tune the size of the thread pool.
:page-layout: general-reference
:seo-title: The Open Liberty auto-tuning thread pool
:seo-description: Open Liberty provides an auto-tuning algorithm that controls the size of its thread pool. For most applications that run on Open Liberty, it is not necessary to tune the size of the thread pool.
:page-layout: general-reference
:page-type: general
= The Open Liberty auto-tuning thread pool

Open Liberty provides an auto-tuning algorithm that controls the size of its thread pool.
For most applications that run on Open Liberty, it is not necessary to tune the size of the thread pool.

All the application code in Open Liberty runs in a single thread pool that is called the default executor.
The size of this pool is set by an auto-tuning controller, which works well for a wide range of workloads.
The default executor pool is the set of threads where your application code runs.
Open Liberty uses other threads for tasks like serving the OSGi framework, collecting JVM garbage, and providing Java NIO transport functions.
However, these threads are not directly relevant to application performance and most of them are not configurable.

== Autonomic thread pool tuning
The Open Liberty thread pool autonomic tuning process runs every 1.5 seconds.
The thread pool controller maintains a set of data about the thread pool performance since the server was started.
The controller records the throughput (tasks that are completed by the thread pool per controller cycle) at the various pool sizes that were previously tried.
This historical throughput data is then compared to the current cycle’s throughput to decide the optimal pool size.
At each cycle, the pool size can be incrementally increased or decreased, or left unchanged.

In some cases, there is no historical data to guide the decision.
For example, if the pool is growing with each cycle and the current cycle is at the largest size so far, there is no data about throughput for larger pool sizes.
In such a case, the controller flips a coin to decide whether to grow the pool.
Then, it readjusts for the next cycle based on the results of that decision.
This process is analogous to a human thread pool tuner who tries various thread pool sizes to see how they perform and decides on an optimal value for the configuration and workload.

During each 1.5-second cycle, the thread pool controller runs through the following auto-tuning operations:

. Wakes up and checks whether the threads in the pool are hung. If there are tasks in the queue and no tasks were completed in the previous cycle, the controller considers the threads to be hung. In this case, the controller increases the thread pool size as specified by settings and skips to step 5.

. Updates the historical data set with the number of tasks completed in the most recent controller cycle. Performance is recorded as a weighted moving average for each pool size, so it reflects historical results but adjusts quickly to changing workload characteristics.

. Uses historical data to predict whether performance would be better at smaller or larger pool sizes. If there is no historical data for the smaller or larger pool size, decides whether to grow or shrink the pool.

. Adjusts pool size (increase, decrease, or unchanged) based on predicted performance, within bounds specified in settings.

. Goes back to sleep.

There are a various factors other than the thread pool size that can affect throughput in the Open Liberty server.
The relationship between pool size and observed throughput is not perfectly smooth or continuous.
Therefore, to improve the predictions derived from the historical throughput data, the controller considers not just the closest larger and smaller pool size performance, but also includes several increments in each direction.

=== Resolving hangs

In some application scenarios, all the threads in the pool can become blocked by tasks that must wait for other work to finish before they can run.
In these cases, the server can become hung at a certain pool size.
To resolve this type of situation, the thread pool controller enters a hang resolution mode.

Hang resolution adds threads to the pool to allow the server to resume normal execution.
Hang resolution also shortens the controller cycle duration to break out of the deadlock quickly.

When the controller observes that tasks are being completed again, normal operation resumes.
The controller cycle returns to its normal duration, and pool size is adjusted based on the usual throughput criteria.

== When to tune the Open Liberty thread pool
In most environments, configurations, and workloads, the Open Liberty thread pool does not require configuration or tuning.
Open Liberty uses auto-tuning  to determine how many threads are needed to provide optimal server throughput.
The thread pool controller continually adjusts the number of threads in the pool within the defined bounds for coreThreads and maxThreads.
However, there are some situations in which setting the `coreThreads` or `maxThreads` attributes might be necessary.

=== Threading settings

The following configuration settings are available for the Open Liberty default executor pool:

* `coreThreads` +
This setting specifies the minimum number of threads in the pool (minimum 4).
Open Liberty creates a new thread for each piece of offered work until the number of threads equals the value of this attribute.
If `coreThreads` is not configured, it defaults to a multiple of the number of CPUs (hardware threads) available to the Open Liberty process.
+
If Open Liberty is running in a shared environment, the thread pool controller cannot account for other processes with which it is sharing the available CPUs.
In these cases, the default `coreThreads` value might cause Open Liberty to spin up more threads than is optimal, considering the other processes that are competing for CPU resources.
In this situation, you can limit `coreThreads` to a value that reflects only the proportion of the CPU resources that Open Liberty needs to run.

* `maxThreads` +
This setting specifies the maximum number of threads in the pool.
The default value is -1, which is equal to `MAX_INT` or, effectively unlimited.
+
In some environments, there is a hard limit on the number of threads that a process can spin up.
Currently, Open Liberty has no way to know whether such a cap applies, or what the value is.
If Open Liberty is running in a thread-limited environment, the operator can configure the `maxThreads` attribute to an acceptable value.

The Open Liberty thread pool controller is designed to handle a wide range of workloads and configurations . There might be some edge cases where you need to adjust the `coreThreads` and `maxThreads` settings. However, try the default behavior first to make sure you actually need to make adjustments.
