// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.
:page-layout: general-reference
:seo-title: What is Open Liberty
:seo-description: Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.
:page-layout: general-reference
:page-type: general
= What is Open Liberty?

Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.

With Open Liberty, you can add and remove modular features from the latest versions of Jakarta EE and Eclipse MicroProfile. This modular structure simplifies microservice development, so you run so you run only the features that your application needs. Furthermore, with Open Liberty zero migration architecture, you can upgrade to the latest version with minimal impact to your current applications and configurations. Open Liberty is compatible with MicroProfile and with the Jakarta EE Full Platform and Web Profile specifications. For the latest updates about Open Liberty features and capabilities, see the link:https://openliberty.io/blog/[Open Liberty blog] and https://openliberty.io/docs/[Open Liberty docs].

////
new list pending benefit by persona content
Open Liberty offers the following benefits:

* A lightweight edition that corresponds to the Jakarta EE Full Platform and Web Profile specifications.
* Excellent development and production runtime environments for web applications.
* A smaller footprint for faster download and startup, giving more development time and faster time to deployment.
* Ease of packaging applications for deployment, including configuration.
////

== Feature management

Features are the discrete functional units with which you control the runtime environment. Features provide the programming models and services that support your applications. Open Liberty features are pluggable, so your existing features are supported in new product versions. New APIs and behaviors are added in new features and feature versions, so that you can choose the appropriate feature version for your application.

You can add, remove, and update features as needed, with minimal impact to your application. When the feature configuration is changed, Open Liberty reevaluates the code that is required for the newly requested features by starting and stopping parts of the runtime as necessary, without having to restart the server. You specify features in your `server.xml` file or other system configuration files, and you can freely mix MicroProfile, Jakarta EE, and other features according to the needs of your applications. Open Liberty features are configured by default, so that you need to specify only configuration that overrides or makes additions to the default settings.

For a full list of available features and their configuration elements, see link:/docs/ref/feature/#featureOverview.html[Server Features].

== Server configuration

Open Liberty follows a principle of configuration by exception, which allows for succinct config files. The runtime environment operates from a set of built-in config default settings. You specify config only when you want to override the default settings. Open Liberty monitors the server XML config for updates and dynamically reloads whenever changes are detected. For more information, see link:/docs/ref/config/#serverConfiguration.html[Server Configuration].

== Developer experience



Open Liberty provides a diverse library of interactive and static developer guides that are designed to give you firsthand experience with the configuration and features that support cloud native development. The guides cover a wide range of development and production use cases and can be adapted as reference templates for developing your own applications. link:/guides/[Browse the guides] and learn how to build, package, and deploy robust applications and microservices with Open Liberty.

== Security

Open Liberty supports application security from development to test to production with a robust set of security features. During development and testing, Open Liberty's built-in basic user registry and the QuickStart security element offer easily configurable security frameworks to test access to your application in a lightweight, self-contained manner. After deployment, the link:/docs/ref/feature/#appSecurity.html[Application Security] feature provides the core capability for the Jakarta EE Security API, while the link:/docs/ref/feature/#transportSecurity.html[Transport Security] feature enables TLS connections using HTTPS. The link:/docs/ref/feature/#ldapRegistry.html[LDAP User Registry] feature supports authentication and authorization from external LDAP registries. Open Liberty also provides features to support a range of single sign-on options, including link:/docs/ref/feature/#jwtSso.html[JSON Web Tokens], link:/docs/ref/feature/#jwtSso.html[OpenID Connect], link:/docs/ref/feature/#samlWeb.html[SAML web], and link:/docs/ref/feature/#spnego.html[SPNEGO].

== Optimized for cloud-native development

If you are running Java applications in a cloud, the supporting runtime needs to fit the cloud environment. Open Liberty is an application server that is designed with modern cloud-native application development in mind. Deployable to any Kubernetes cloud, Open Liberty lets you focus on developing your microservices, without worrying about low-level infrastructure details. Whether you're a small team of developers or an enterprise-scale organization running hundreds of containers, your containerized applications running on Open Liberty are simple to deploy, manage, and scale. Check out our guides to learn how you can easily deploy to link:/guides/okd.html[OKD], link:/guides/cloud-openshift.html[OpenShift], link:/guides/cloud-azure.html[Azure Kubernetes Service], link:/guides/cloud-aws.html[Amazon Web Services], link:/guides/cloud-ibm.html[IBM Kubernetes Service], and more.

== The Open Liberty auto-tuning thread pool

Application code in Open Liberty runs in a single thread pool that is called the default executor. The size of this pool is set by an auto-tuning controller, which can manage a wide range of workloads. For most applications that run on Open Liberty, it is not necessary to tune the size of the thread pool. For more information, see link:/docs/ref/general/#Threading.html[The Open Liberty thread pool].

== Zero migration

With the Open Liberty zero migration policy, you focus on writing your applications, not the APIs changing under you. Zero-migration architecture means that you can use existing, unmodified configuration and application files with an updated version of Open Liberty without unwanted or unexpected change in behavior. Open Liberty offers full compatibility between product versions and pluggable features so that your existing APIs and behaviors are supported in each new product version.

Open Liberty does not modify user configuration files, which are fully compatible between versions. You can use a single version of your configuration files across multiple versions. Files that you created for a previous version of Open Liberty can be used with a later version. Files that you create for later versions can be used with previous versions. As a result, if all configured features are installed, you can use a single set of configuration files across multiple versions without modifications. Any configuration settings that do not apply to a particular version of Open Liberty are ignored.
