// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.
:page-layout: general-reference
:seo-title: What is Open Liberty
:seo-description: Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.
:page-layout: general-reference
:page-type: general
= What is Open Liberty

Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.

With Open Liberty, you can add and remove modular features from the latest versions of Jakarta EE and Eclipse MicroProfile. This modular structure simplifies microservice development, so you run Just enough Application Server to support the features that your application needs. Furthermore, with Open Liberty zero migration architecture, you can upgrade to the latest version with minimal impact to your current applications and configurations. Open Liberty is compatible with the Jakarta EE Full Platform and Web Profile specifications and with MicroProfile. For the latest updates about Open Liberty features and capabilities, see the link:https://openliberty.io/blog/[Open Liberty blog] and https://openliberty.io/docs/[Open Liberty docs].

Open Liberty offers developers the following benefits:

* A lightweight edition that corresponds to the Java EE Web Profile specification.
* Excellent development and production runtime environments for web applications.
* A smaller footprint for faster download and startup, giving more development time and faster time to deployment.
* Ease of packaging applications for deployment, including configuration.
* The ability to run applications that are written for Open Liberty on WebSphere Application Server traditional.
* The ability to extend the Open Liberty capabilities by adding custom features that use a product extension System Programming Interface (SPI).

== Zero migration

With the Open Liberty zero migration policy, you focus on writing your applications, not the APIs changing under you. Zero-migration architecture means that you can use existing, unmodified configuration and application files with an updated version of Open Liberty without unwanted or unexpected change in behavior. Open Liberty offers full compatibility between product versions and pluggable features so that your existing APIs and behaviors are supported in each new product version.

Open Liberty does not modify user configuration files, which are fully compatible between versions. You can use a single version of your configuration files across multiple versions. Files that you created for a previous version of Open Liberty can be used with a later version. Files that you create for later versions can be used with previous versions. As a result, if all configured features are installed, you can use a single set of configuration files across multiple versions without modifications. Any configuration settings that do not apply to a particular version of Open Liberty are ignored.

== Server configuration

Open Liberty follows a principle of configuration by exception, which allows for succinct config files. The runtime environment operates from a set of built-in config default settings. You specify config only when you want to override the default settings. For more information, see link:/docs/ref/config/#serverConfiguration.html[Server Configuration].

== Feature management

Features are the discrete functional units with which you control the pieces of the runtime environment that are loaded into a particular server. Features provide the programming models and services that support your applications. For a full list of available features and their configuration elements, see link:/docs/ref/feature/#featureOverview.html[Server Features].

== The Open Liberty auto-tuning thread pool

Application code in Open Liberty runs in a single thread pool that is called the default executor. The size of this pool is set by an auto-tuning controller, which works well for a wide range of workloads. For most applications that run on Open Liberty, it is not necessary to tune the size of the thread pool. For more information, see link:/docs/ref/general/#Threading.html[The Open Liberty thread pool].

== Open Liberty developer guides

Open Liberty provides a diverse library of interactive and static developer guides that are designed to give you firsthand experience with the configuration and features that support cloud native development. The guides cover a wide range of development and production use cases and can be adapted as reference templates for developing your own applications. link:/guides/[Browse the guides] and learn how you to build, package, and deploy robust applications and microservices with Open Liberty.
