// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.
:page-layout: general-reference
:seo-title: What is Open Liberty
:seo-description: Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.
:page-layout: general-reference
:page-type: general
= What is Open Liberty

Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.

With Open Liberty, you can add and remove modular features from the latest versions of Jakarta EE and Eclipse MicroProfile. This modular structure simplifies microservice development, so you run Just enough Application Server to support the features that your application needs. Furthermore, with Open Liberty zero migration architecture, you can upgrade to the latest version with minimal impact to your current applications and configurations. Open Liberty is compatible with the Jakarta EE 8 Full Platform and Web Profile specifications and with MicroProfile 3.0. Open Liberty is deployed on every major developer platform, including Docker, Kubernetes, and Cloud Foundry. For the latest updates about Open Liberty features and capabilities, see the link:https://openliberty.io/blog/[Open Liberty blog] and https://openliberty.io/docs/[Open Liberty docs].

Open Liberty offers developers the following benefits:
* A lightweight edition that corresponds to the Java EE Web Profile specification.
* Excellent development and production runtime environments for web applications.
* A smaller footprint for faster download and startup, giving more development time and faster time to deployment.
* Ease of packaging applications for deployment, including configuration.
* The ability to run applications that are written for Open Liberty on WebSphere Application Server traditional.
* The ability to extend the Open Liberty capabilities by adding custom features that use a product extension System Programming Interface (SPI).

== Server configuration

Open Liberty follows a principle of configuration by exception, which allows for succinct config files. The runtime environment operates from a set of built-in config default settings. You only specify config that overrides the default settings. For more information, see link:/docs/ref/config/#serverConfiguration.html[Server Configuration].

== Feature Management

Features are the discrete units of functionality by which you control the pieces of the runtime environment that are loaded into a particular server. Features provide the programming models and services that support your applications. For a full list of avaialble features and their configuration elements, see link:/docs/ref/feature/#featureOverview.html[Server Features].

== Open Liberty Guides

Open Liberty provides a diverse library of interactive and static user guides that are designed to give you firsthand experience with the configuration and features that support cloud native development. The guides cover a wide range of development and production use cases and can be adapted as reference templates for developing your own applications. link:/guides/[Browse our guides] and learn what Open Liberty can do for you.

For the latest updates about Open Liberty features and capabilities, see the link:https://openliberty.io/blog/[Open Liberty blog] and https://openliberty.io/docs/[Open Liberty docs].
