// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Running an Open Liberty server as a Windows service
:seo-description:
:page-layout: general-reference
:page-type: general
= Running an Open Liberty server as a Windows service

You can register an Open Liberty server as a Microsoft Windows Service program when you run on Windows operating systems. You can also use the Microsoft Windows Services program to enable Open Liberty to start automatically as a Windows service when the Windows server starts.

Set the `JAVA_HOME` environment variable in the `server.env` file before you run the following commands. See the link:/docs/ref/config/[Server configuration overview] for more information. Use the following commands to register, unregister, start, and stop an Open Liberty server as a Windows service:

* Register the `myserver` server as a Windows service:
+
----
server registerWinService myserver
----
+
After you register, you can find and administer the Open Liberty server as a service by using the Windows `regedit` program. Entries for the service in the registry are in the following locations:
+
----
HKEY_LOCAL_MACHINE->SOFTWARE->Wow6432Node->Apache Software Foundation->Procrun 2.0->serverName
HKEY_LOCAL_MACHINE->SYSTEM->CurrentControlSet->services->serverName
----

* Unregister the `myserver` server:
+
----
server unregisterWinService myserver
----

* Start the `myserver` server as a Windows service:
+
----
server startWinService myserver
----

* Stop the `myserver` server:
+
----
server stopWinService myserver
----

== Syntax

Run the command from `path_to_liberty/bin`.

----
server registerWinService serverName
----

serverName::
The name of the server to run the command against. The Windows service display name is `serverName`.

== Installing a fix pack

When you use archives to install a fix pack, the fix pack installation directory can differ from the directory where the Open Liberty server was running before you installed the fix pack. If you are running an Open Liberty server as a Windows service, unregister the Open Liberty server before you install the fix pack. After you install the fix pack, register the Open Liberty server as a Windows service again.

If you need to manually remove Liberty as a Windows service, update the Windows registry by using the Windows `regedit` program. The entries that need to be removed from the Windows Registry are in the following locations:
----
HKEY_LOCAL_MACHINE->SOFTWARE->Wow6432Node->Apache Software Foundation->Procrun 2.0->serverName
HKEY_LOCAL_MACHINE->SYSTEM->CurrentControlSet->services->serverName
----
