// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Running an Open Liberty server as a Windows service
:seo-description:
:page-layout: general-reference
:page-type: general
= Running an Open Liberty server as a Windows service

You can register an Open Liberty server as a service when you run on Windows. Registering the server as a service enables the Open Liberty server to start automatically when Windows starts.

Before you run the Windows service commands, set the `JAVA_HOME` environment variable in the `server.env` file. For more information about setting environment variables, see the link:/docs/ref/config/[Server configuration overview]. Run these commands from `path_to_liberty/bin` by using the following syntax, where `serverName` is the Windows service display name and the name of the server to run the command against:

----
server registerWinService serverName
----

''''

Use the following commands to register, unregister, start, and stop an Open Liberty server as a Windows service:

* Register the `myserver` server as a Windows service:
+
----
server registerWinService myserver
----

* Unregister the `myserver` server:
+
----
server unregisterWinService myserver
----

* Start the `myserver` server as a Windows service:
+
----
server startWinService myserver
----

* Stop the `myserver` server:
+
----
server stopWinService myserver
----

== Installing a fix pack

When you install a fix pack, it is common to install it in a parallel installation directory. If you follow this practice, unregister the Open Liberty server that uses the old fix pack, install the new fix pack, and register the server as a Windows service again.

If you need to manually remove Open Liberty as a Windows service, update the Windows Registry by using the Windows `regedit` program. The entries that need to be removed from the Windows Registry are in the following locations:
----
HKEY_LOCAL_MACHINE->SOFTWARE->Wow6432Node->Apache Software Foundation->Procrun 2.0->serverName
HKEY_LOCAL_MACHINE->SYSTEM->CurrentControlSet->services->serverName
----
