// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: auditReader utility - OpenLiberty.io
:seo-description: Decrypt and unsign an audit log that is encrypted, signed, or both. It is an action of the auditUtility command
= auditUtility auditReader command

The `auditReader` utility can be used to decrypt and unsign an audit log that is encrypted, signed, or both. It is an action of the `auditUtility` command.

The `auditUtility auditReader` command takes the location of a signed or encrypted audit log and produces a readable audit log in JSON format as its output. The command supports only the JKS, PKCS12, and JCEKS keystore types. The `auditUtility auditReader` command must specify the location of the audit log to be read and the location of the output file.

If the audit log file is encrypted, the command must specify `encrypted=true`, along with the keystore type and password of the keystore that stores the certificate that is used to encrypt the log. If the keystore for decrypting the audit log is in a path other than the path shown in the audit log header, the command must also specify the location of the keystore that is used to encrypt the log.

If the audit log file is signed, the command must specify `signed=true`, along with the keystore type and password of the keystore that stores the certificate that is used to sign the log. If the keystore for unsigning the audit log is in a path other than the path shown in the audit log header, then the command must specify the location of the keystore that is used to sign the log.

== Usage

Get help using the `auditUtility` command:

----
auditUtility help
----


Encrypted audit logs:

----
auditUtility auditReader

--auditFileLocation=c:/LibertyInstall/dev/build.image/wlp/usr/servers/myserver/logs/audit.log

--outputFilelocation=c:/decryptedAuditLogs/decrypted_audit.log

--encrypted=true

--encKeyStoreLocation=c:/LibertyInstall/dev/build.image/wlp/usr/server/myserver/mykeystore.jks

--encKeyStorePassword=Liberty

--encKeyStoreType=JKS
----

Signed audit logs:

----
auditUtility auditReader

--auditFileLocation=c:/LibertyInstall/dev/build.image/wlp/usr/servers/myserver/logs/audit.log

--outputFilelocation=c:/unsignedAuditLogs/unsigned_audit.log

--signed=true

--signingKeyStoreLocation=c:/LibertyInstall/dev/build.image/wlp/usr/server/myserver/mySiginingKeystore.PKCS12

--signingKeyStorePassword=Liberty

--signingKeyStoreType=PKCS12
----


Audit logs that are both signed and encrypted:

----
auditUtility auditReader

--auditFileLocation=c:/LibertyInstall/dev/build.image/wlp/usr/servers/myserver/logs/audit.log

--outputFilelocation=c:/decryptedeAndUnsignedAuditLogs/decryptedAndUnsigned_audit.log

--encrypted=true

--encKeyStoreLocation=c:/LibertyInstall/dev/build.image/wlp/usr/server/myserver/mykeystore.jks

--encKeyStorePassword=Liberty

--encKeyStoreType=JKS

--signed=true

--signingKeyStoreLocation=c:/LibertyInstall/dev/build.image/wlp/usr/server/myserver/mySiginingKeystore.PKCS12

--signingKeyStorePassword=Liberty

--signingKeyStoreType=PKCS12
----



== Options

The following options are available for the `auditUtility auditReader` command:

[%header,cols=2*]
|===
|Option
|Description

|--auditFileLocation=[_location of encrypted, signed, or encrypted and signed audit log_]
|Specify the fully qualified location of the audit log to decrypt and unsign.

|--outputFileLocation=[_location of resulting decrypted and unsigned audit log_]
|Specify the fully qualified location of the resulting output log.

|--debug=[true|false]
|Optional. Specify true to enable trace. Debug is disabled by default.

|===

For decrypting, include the following encryption options:

[%header,cols=2*]
|===
|Option
|Description

|--encrypted=[true|false]
|Specify true if the audit log is encrypted and false if it is not encrypted.

|--encKeyStoreLocation=[_keystore URL_]
|Specify the fully qualified file URL location of the keystore that stores the certificate that is used to decrypt the audit records.

|--encKeyStorePassword=[_password_]
|Specify the password for the keystore that contains the certificate that is used to decrypt the audit records.

|--encKeyStoreType=[JKS|JCEKS|PKCS12]
|Specify the type of the encryption keystore. Supported keystore types are JKS, JCEKS, and PKCS12.

|===


For unsigning, include the following signing options:

[%header,cols=2*]
|===
|Option
|Description

|--signed=[true|false]
|Specify true if the audit log is signed and false if it is not signed.

|--signingKeyStoreLocation=[_keystore URL_]
|Specify the fully qualified file URL location of the keystore that stores the certificate that is used to unsign the audit records.

|--signingKeyStorePassword=[_password_]
|Specify the password for the keystore that contains the certificate that is used to unsign the audit records.

|--signingKeyStoreType=[JKS|JCEKS|PKCS12]
|Specify the type of the signing keystore. Supported keystore types are JKS, JCEKS, and PKCS12.

|===

