== Examples

=== Configure JPA logging

The Open Liberty logging component supports viewing, tracing, and troubleshooting the runtime behavior of an application. When the Java Persistence API feature is enabled, all JPA logging and tracing is routed through the Open Liberty logging component.

You can customize the level of detail for JPA logging by specifying the `logging` element in your `server.xml` file, as shown in the following example:

[source,xml]
----
<logging  traceSpecification="JPA=all"
  traceFileName="trace.log"
  maxFileSize="20"
  maxFiles="10"
  traceFormat="BASIC" />
----

In this example, the `JPA=all` value you for the `traceSpecification` attribute specifies that all JPA container trace and EclipseLink trace categories are enabled.

EclipseLink is the default JPA provider implementation for Open Liberty, which recognizes EclipseLink-specific trace categories. The following trace strings are supported for JPA in Open Liberty:

* `JPA=all`
+
Enables JPA container trace and all EclipseLink categories
+
* `eclipselink=all`
+
Enables all EclipseLink trace
+
  ** EclipseLink specific log categories
+
`sql`, `transaction`, `event`, `connection`, `query`, `cache`, `propagation`, `sequencing`, `ejb`, `dms`, `metadata`, `weaver`, `properties`, `server`


You can specify Eclipse-specific trace categories by using the following syntax for the `traceSpecification` attribute: `eclipselink.*=all`. For example, to enable EclipseLink SQL trace, you would specify the following configuration:

[source,xml]
----
<logging  traceSpecification="eclipselink.sql=all"
  traceFileName="trace.log"
  maxFileSize="20"
  maxFiles="10"
  traceFormat="BASIC" />
----

For more information about the available EclipseLink trace categories, see the https://www.eclipse.org/eclipselink/api/2.6/org/eclipse/persistence/logging/SessionLog.html[SessionLog interface].

For more information about configuring logging for your EclipseLink JPA instance, see https://wiki.eclipse.org/EclipseLink/Examples/JPA/Logging[EclipseLink: How To Configure Logging].

For more information about Open Liberty logging, see xref:ROOT:log-trace-configuration.adoc[Log and trace configuration].
