// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.
:page-layout: general-reference
:seo-title: About Open Liberty
:seo-description: Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.
:page-layout: general-reference
:page-type: general
= About Open Liberty

Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.

With Open Liberty, you can add and remove modular features from the latest versions of Eclipse MicroProfile and Jakarta EE.
This modular structure simplifies application development, so you run only the features that your application needs.
Furthermore, thanks to zero-migration architecture, you can upgrade to the latest version of Open Liberty with minimal impact on your current applications and configurations.
Open Liberty is compatible with MicroProfile and with the Jakarta EE Full Platform and Web Profile specifications.
For updates about Open Liberty features and capabilities, see the link:https://openliberty.io/blog/[Open Liberty blog] and https://openliberty.io/docs/[Open Liberty Docs].

Open Liberty provides a diverse library of interactive and static developer guides that are designed to give you firsthand experience with the configuration and features that support cloud-native development.
The guides cover a wide range of development and production scenarios and can be adapted as reference templates for developing your own applications. link:/guides/[Browse the guides] and learn how to build, package, and deploy applications and microservices with Open Liberty.


== Develop cloud-native Java applications and microservices

Open liberty is designed to simplify and accelerate application development. Open Liberty offers a low-memory footprint and some of link:/blog/2019/10/30/faster-startup-open-liberty.html[the fastest start-up times of any lightweight Java server]: one second or less for simple configurations on processors that are used in current laptops and servers.
Faster start-up times enable faster development and test cycles.

=== Choose the right-size image for your applications

Open Liberty is a fully-modular runtime. You pick and choose the capabilities that you need for your application.  Open Liberty  is a flexible solution for developing and deploying applications that can scale from small microservices all the way up to full modern enterprise monoliths, and anything in-between. 

The following table shows disk and memory measurements for three example Open Liberty runtime packages. The example in the first row contains all the latest APIs for both Java EE or Jakarta EE and MicroProfile, all you need for a modern cloud-native monolith. The example in the second row contains enough runtime to support MicroProfile 3.3, all you need for a typical microservice. The example in the third row contains just enough runtime to run Servlet 4.0, the absolute minimum you need to run a simple web framework.  For each of these use cases, Open Liberty disk and memory requirements scale to match the needs of the system so that only the necessary resources are consumed.  

.Example runtime packages
[%header,cols="6,3,3"]
|===

|Package
|Size on disk
|Memory

|Java EE 8/Jakarta EE 8 + MicroProfile 3.3
|121MB
|165MB

|MicroProfile 3.3       
|59MB
|113MB

|Servlet 4.0
|24MB
|72MB

|===

////
commenting out per GC email comment
=== Mix and match features
Open Liberty features are pluggable, so that your existing features are supported in new product versions. You can add, remove, and update features as needed, with minimal impact on your application. When the feature configuration is changed, Open Liberty reevaluates the code by starting and stopping parts of the runtime as necessary, without having to restart the server. For a full list of available features and their configuration elements, see xref:reference:feature/feature-overview[Feature overview].


You can freely mix MicroProfile, Jakarta EE, and other features, according to the needs of your applications. Open liberty maintains regular 4-weekly releases, so new versions of features are available quickly. For more information, see xref:microprofile.adoc[MicroProfile].
////

=== Deploy, test, and debug with container-aware, continuos-delivery focused developer tools

Open Liberty has a strong focus on helping developers to be productive with tools of their choice.  Open Liberty integrates with the most popular build tools, Maven and Gradle, including the release of all the runtime binary files to Maven Central. 

Maven and Gradle support also enable Open Liberty xref:development-mode.adoc[development mode], so the  code and configuration changes that you make take immediate effect on a local running server. Run your server in development mode for automatic reload and deployment, on-demand testing, and debugger support.
With dev mode, Open Liberty automatically detects changes in your code, compiles them, and deploys them to your running server.
You can run tests on demand, or even automatically, so that you get immediate feedback on your changes. Development mode removes the need for a full rebuild and redeploy and greatly reduces the time that is needed to develop and test updates to your applications.

True-to-production integration testing helps you test your applications in the same environment that you use in production. You can run true-to-production integration tests for your Open Liberty applications by using the xref:integration-testing.adoc[MicroShed testing framework]. MicroShed provides the ability to run JUnit integration tests against an Open Liberty application that is running in a container, including integration with containers that running databases and Kafka.

=== Stay current and secure with continuous delivery and zero migration

Modernizing your applications to cloud-native and microservices  often leads to a shift in runtime ownership responsibility. A single multidisciplinary team develops, packages, and deploys an application (for example, microservice) as an immutable container that includes the server runtime.

Previously, the operations team would manage the small number of server runtime instances, carefully rolling out major version or service releases upgrades, and ensuring critical security interim fixes were applied. The development team is now responsible for the maintenance of the runtime, which is part of the container contents. Development teams might deliver scores of applications, each of which embeds a runtime. These teams are responsible for ensuring those runtimes are current and free from vulnerabilities. 

Open Liberty addresses this challenge with a continuous delivery release cycle.  A new release of the runtime arrives every 4 weeks. Every Open Liberty release is available in Maven Central and Docker Hub, making it simple to pick up the latest updates through build automation. Development teams can simply rebuild their containers to pull in the latest release. 

With Open Liberty zero-migration architecture, you focus on writing your applications, not the APIs changing under you.
Zero-migration architecture means that you can use existing, unmodified configuration and application files with an updated version of Open Liberty, without unexpected changes in behavior. In just a matter of minutes, you can move up to the latest version Open Liberty without having to change your application code or configuration.

Open Liberty offers full compatibility between product versions so that your existing APIs and behaviors are supported in each new release. For more information, see xref:zero-migration-architecture.adoc[Zero-migration architecture].

The combination of continuous delivery releases and zero migration architecture makes it easy to stay up-to-date with fixes and improvements and gives you the flexibility to invest in application changes on your own schedule.


== Deploy in containers to any cloud
Open Liberty can be containerized and deployed to any Kubernetes cloud. For more information, see the guides to learn how you can easily deploy to link:/guides/okd.html[OKD], link:/guides/cloud-openshift.html[OpenShift], link:/guides/cloud-azure.html[Azure Kubernetes Service], link:/guides/cloud-aws.html[Amazon Web Services], link:/guides/cloud-ibm.html[IBM Kubernetes Service], and more.

=== Protect applications and servers
Open Liberty supports application security with a robust set of security features.
During development and testing, Open Liberty's built-in xref:user-registries-application-security.adoc#_basic_user_registries_for_application_development[basic user registry and the QuickStart security element] offer easily configurable security frameworks to test access to your application in a lightweight, self-contained manner.
The `securityUtility` command supports plain text encryption, so you can easily xref:password-encryption.adoc[secure user passwords] with hash encoding.

After deployment, the xref:reference:feature/appSecurity-3.0.adoc[Application Security feature] provides the core capability for the Jakarta EE Security API, while the xref:reference:feature/transportSecurity-1.0.adoc[Transport Security feature] enables secure TLS connections by using HTTPS.
The xref:user-registries-application-security.adoc#_ldap_user_registries_for_applications_in_production[LDAP User Registry] feature supports authentication and authorization to external LDAP registries.
Open Liberty also provides features to support xref:single-sign-on.adoc[a range of single sign-on options], including JSON Web Tokens, OpenID Connect, SAML Web, and SPNEGO.

=== Optimize container orchestration with auto-tuning and Kubernetes native integration

Efficient container orchestration is integral to delivering of cloud-native microservices. Container-based microservices need a runtime that can achieve optimum application performance, regardless of where the container is deployed.

Containerization poses challenges to performance tuning. Open Liberty addresses these challenges with effective default settings that rarely require adjustment. Furthermore, the Open Liberty thread pool is auto-tuning. Application code in Open Liberty runs in a single thread pool that is called the default executor.
The size of this pool is set by xref:thread-pool-tuning.adoc[an auto-tuning controller], which can manage a wide range of workloads.
A properly tuned thread pool can maximize throughput, reduce response times, and increase the capacity for concurrent requests.

To build dependable applications, developers need secure, supported Docker images. For each new release of Open Liberty, new Universal Base Image-based images are uploaded to Docker Hub. These images are maintained so that fixes to critical security vulnerabilities are automatically applied. 

Kubernetes is the industry standard for container orchestration. With Kubernetes-based platforms, such as OpenShift, you can deploy containers and scale them up or down according to the needs of your application. Kubernetes operators are software extensions for Kubernetes that help you configure and manage containerized applications. The Open Liberty Operator greatly simplifies deployment and configuration of applications, clustering, persistence integration, service binding, problem determination, and more.





////
// removing for redundancy
=== Deploy with zero migration
Zero migration is the ability to use existing, unmodified user files with an updated version of the product runtime files, without any unwanted or unexpected changes in behavior. Open Liberty does not modify user configuration files, which are fully compatible between versions.
You can use a single version of your configuration files across multiple versions.
Files that you created for a previous version of Open Liberty can be used with a later version.
Files that you create for later versions can be used with previous versions.
As a result, if all configured features are installed, you can use a single set of configuration files across multiple versions without modifications.


=== Separate configuration from code
Open Liberty follows a principle of configuration by exception, which allows for succinct config files.
The runtime environment operates from a set of built-in config default settings.
You specify config only when you want to override the default settings.
Open Liberty monitors the server XML config for updates and dynamically reloads whenever changes are detected.
For more information, see xref:reference:config/server-configuration-overview.adoc[Server configuration].

Throughout the development, testing, and production lifecycle of your application, you can easily specify changes to configuration according to the deployment context. With MicroProfile Config, you can build your app once and deploy it many times through your CI/CD pipeline by changing the configuration for each deployment. For more information, see link:/guides/microprofile-config.html[Configuring microservices].
////

== Monitor applications in the cloud

Distributed tracing helps you track the flow of a request as it moves through an application.
Tracing creates observability, so you can debug errors and better understand throughput. With Open Liberty, it's simple to implement a standard system to trace requests through an application and record the results to customizable logs.

////
commenting out per GC email comment
=== Customize logs
You can specify custom fields in your Open Liberty logs to capture detailed information about specific requests, users, or behaviors. Custom fields can help sort and filter your logs, so you can better understand what's happening in your application. For more information, see link:https://openliberty.io/blog/2019/12/03/custom-fields-json-logs.html[
Adding custom fields to JSON logs in Open Liberty].
////

=== Gather and analyze metrics
You can xref:microservice-observability-metrics.adoc[gather detailed metrics on your applications] that run on Open Liberty with MicroProfile metrics. Metrics are essential to building observability into applications so that operations teams can monitor application behavior effectively. After you configure metrics, you can link:/blog/2020/01/29/alerts-slack-prometheus-alertmanager-open-liberty.html[get alerts from your Open Liberty apps in Slack using Prometheus Alertmanager]. You can also link:/blog/2020/01/23/Kibana-dashboard-visualizations.html[compile the data from your logs into visualizations in dashboards like Kibana] to spot potential problems in your Open Liberty server in real time.
