// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: You can configure access to a NoSQL database with a CDI producer.
:seo-title: Access NoSQL databases
:seo-description: You can configure access to a NoSQL database with a CDI producer.
:page-layout: general-reference
:page-type: general
= Access NoSQL databases with CDI

NoSQL, or a 'not only SQL', database provides flexible schemas for potentially large amounts of unstructured data.
You can access a NoSQL database with Open Liberty without enabling any feature in the `server.xml` file.

== Access MongoDB with CDI

You can configure access to any version of MongoDB with a CDI producer.
For more information, see https://openliberty.io/guides/cdi-intro.html[Injecting dependencies into microservices].

This example demonstrates how to create a CDI producer to inject a MongoDatabase instance:

```
@ApplicationScoped
public class MongoProducer {

    @Produces
    public MongoClient createMongo() {
        return new MongoClient(new ServerAddress(), new MongoClientOptions.Builder().build());
    }

    @Produces
    public MongoDatabase createDB(MongoClient client) {
        return client.getDatabase("testdb");
    }

    public void close(@Disposes MongoClient toClose) {
        toClose.close();
    }
}
```
The `createMongo()` producer method returns an instance of MongoClient.
The `createDB()` producer method returns an instance of MongoDatabase that depends on the MongoClient.
The `close()`` method is a clean-up function for the MongoClient that closes the connection to the MongoDatabase instance.

You can use the CDI producer that you created to inject a MongoDatabase instance in the application:

```
@Inject
MongoDatabase db;

@POST
@Path("/add")
@Consumes(MediaType.APPLICATION_JSON)
public void add(CrewMember crewMember) {
    MongoCollection<Document> crew = db.getCollection("Crew");
    Document newCrewMember = new Document();
    newCrewMember.put("Name",crewMember.getName());
    crew.insertOne(newCrewMember);
}

```
Additionally, you can include authentication and configure the MongoDB driver with MicroProfile Config.
For more information, see link:https://openliberty.io/blog/2019/02/19/mongodb-with-open-liberty.html[Access any version of MongoDB with Open Liberty using CDI].

## Access CouchDB with CDI

To access https://couchdb.apache.org/[CouchDB] with CDI in Open Liberty, you can replace the MongoClient in the example with any any CouchDB client or https://www.ibm.com/cloud/cloudant[Cloudant].

## See also

Guide: https://openliberty.io/guides/mongodb-intro.html[Persisting data with MongoDB]
