// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: You can configure access to a NoSQL database with a CDI producer.
:seo-title: Access NoSQL databases
:seo-description: You can configure access to a NoSQL database with a CDI producer.
:page-layout: general-reference
:page-type: general
= Access NoSQL databases with CDI

Not only SQL (NoSQL) databases provide flexible schemas for potentially large amounts of structured, semi-structured, and unstructured data.
You can access a NoSQL database with a Contexts and Dependency Injection (CDI) producer in Open Liberty.

Before Open Liberty version 19.0.0.6, using MongoDB or Couch DB databases required you to enable the MongoDBb or CouchDBb feature.
The Mongo DB feature was stabilized in version 19.0.0.4 and the CouchDB feature was stabilized in version 19.0.0.6.
To connect to these databases in version 19.0.0.6 and later, you can https://openliberty.io/guides/cdi-intro.html[configure a CDI producer in your application code].

== Access MongoDB with CDI

You can configure access to any version of https://www.mongodb.com/[MongoDB] with a CDI producer.
This example demonstrates how to create a CDI producer to inject a `MongoDatabase` instance:

```
@ApplicationScoped
public class MongoProducer {

    @Produces
    public MongoClient createMongo() {
        return new MongoClient(new ServerAddress(), new MongoClientOptions.Builder().build());
    }

    @Produces
    public MongoDatabase createDB(MongoClient client) {
        return client.getDatabase("testdb");
    }

    public void close(@Disposes MongoClient toClose) {
        toClose.close();
    }
}
```
The `createMongo()producer` method returns a `MongoClient` instance.
The `createDB()producer` method returns a `MongoDatabase` instance that depends on the `MongoClient` instance.
The `close()` method is a clean-up function for the `MongoClient` instance that closes the connection to the `MongoDatabase` instance.
You can use the CDI producer that you created as shown in the following example:

```
@Inject
MongoDatabase db;

@POST
@Path("/add")
@Consumes(MediaType.APPLICATION_JSON)
public void add(CrewMember crewMember) {
    MongoCollection<Document> crew = db.getCollection("Crew");
    Document newCrewMember = new Document();
    newCrewMember.put("Name",crewMember.getName());
    crew.insertOne(newCrewMember);
}

```

== Secure your CDI producer

A CDI producer can be tailored to your needs.
The `createMongo` method can be enhanced to include authentication with a username and an encoded password for additional security:

```
@Produces
public MongoClient createMongo() {
    String password = PasswordUtil.passwordDecode(encodedPass);
    MongoCredential creds = MongoCredential.createCredential(user, dbName, password.toCharArray());
    return new MongoClient(new ServerAddress(), creds, new MongoClientOptions.Builder().build());
}
```
You need to enable the feature:passwordUtilities[display=Password Utilities] feature in the `server.xml` file to include authentication with a username and an encoded password:

```
<feature>passwordUtilities-1.0</feature>
```

You can enable TLS for your database connection.
Add the `JSSEHelper` class to the `createMongo` method to get the `SSLContext` class, as shown in the following example:

```
@Produces
public MongoClient createMongo() throws SSLException {
    String password = PasswordUtil.passwordDecode(encodedPass);
    MongoCredential creds = MongoCredential.createCredential(user, dbName, password.toCharArray());
    SSLContext sslContext = JSSEHelper.getInstance().getSSLContext("defaultSSLConfig", Collections.emptyMap(), null);
    return new MongoClient(new ServerAddress(hostname, port), creds, new MongoClientOptions.Builder()
                           .sslEnabled(true)
                           .sslContext(sslContext)
                           .build());
}
```

You can configure access to any version of https://couchdb.apache.org/[CouchDB] with a CDI producer in Open Liberty.
To access CouchDB with CDI, you can replace the MongoClient in the previous examples with any any CouchDB client or the https://www.ibm.com/cloud/cloudant[Cloudant] service.

== Configure MongoDB with MicroProfile Config

You can configure the MongoDB driver with MicroProfile Config.
To configure the MongoDB driver, add the following  code to your CDI producer:

```
@Inject
@ConfigProperty(name = "mongo.hostname", defaultValue = "localhost")
String hostname;

@Inject
@ConfigProperty(name = "mongo.port", defaultValue = "27017")
int port;

@Inject
@ConfigProperty(name = "mongo.dbname", defaultValue = "testdb")
String dbName;

@Inject
@ConfigProperty(name = "mongo.user")
String user;

@Inject
@ConfigProperty(name = "mongo.pass.encoded")
String encodedPass;
```
Add the following snippet to your  `microprofile-config.properties` or `server.env` file, to pull the values for `user` and `encodedPass` into the `MongoProducer` class:
```
mongo.user=sampleUser
mongo.pass.encoded={aes}APtt+/vYxxPa0jE1rhmZue9wBm3JGqFK3JR4oJdSDGWM1wLr1ckvqkqKjSB2Voty8g==

```
For more information, see link:https://openliberty.io/blog/2019/02/19/mongodb-with-open-liberty.html[Access any version of MongoDB with Open Liberty using CDI].


## See also

Guide: https://openliberty.io/guides/mongodb-intro.html[Persisting data with MongoDB]
Blog: https://openliberty.io/blog/2019/02/19/mongodb-with-open-liberty.html?_ga=2.207768594.1663611092.1606818058-1399812591.1606212512[Access any version of MongoDB with Open Liberty using CDI]
