// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: You can use the Elastic Stack to analyze your Open Liberty logs. The Elastic Stack, sometimes know as the ELK stack, is a widely used open source platform to collect, manage, and build dashboards for log data.
:seo-title: You can use the Elastic Stack to analyze your Open Liberty logs. The Elastic Stack, sometimes know as the ELK stack, is a widely used open source platform to collect, manage, and build dashboards for log data.
:page-layout: general-reference
:page-type: general
= Analyzing JSON logs with Elastic Stack

You can collect logs and events from your Open Liberty server and display them in a dashboard for analysis and troubleshooting purposes. Use JSON logging to emit logs from Open Liberty and send them to link:https://www.elastic.co/log-monitoring[the Elastic Stack], where they can be managed and visualized.

== About this task

The Elastic Stack is a log analysis platform that consists of link:https://www.elastic.co/elasticsearch/[Elasticsearch], link:https://www.elastic.co/logstash/[Logstash], link:https://www.elastic.co/kibana/[Kibana], and link:https://www.elastic.co/beats/[Beats]. You can use these products to collect, parse, and visualize your Open Liberty log data.

If your Open Liberty server is deployed in a managed environment, such as a Kubernetes cluster, your logs are typically aggregated by agents in that environment.

In cases where your server logs are not managed by an external agent, you might be able to configure https://www.elastic.co/beats/filebeat[Filebeat] to forward your logs to Logstash. If you can install Filebeat on the same host as your Open Liberty server, you can configure Open Liberty to write logs in JSON format and Filebeat can forward the logs.

If it is not possible to install Filebeat on the same host as your Open Liberty server, you can use the Open Liberty Logstash collector feature to forward your logs to Logstash. This feature internally collects log data at run time and sends it directly to a Logstash server. For more information, see xref:forwarding-logs-logstash.adoc[Forwarding logs and events to Logstash with Logstash collector].

The following procedure assumes that your Open Liberty server is in an environment where Filebeat has access to the Open Liberty server logs.


== Before you begin

- Set up Filebeat, Logstash, Elasticsearch and Kibana by following link:https://www.elastic.co[the instructions from Elastic].
- Set your Open Liberty `messages.log` file xref:log-trace-configuration.adoc#_json_logging[to JSON format].

== Procedure

Complete the following steps to configure your Elasticsearch, Logstash, Kibana, and Filebeat products to use and visualize your logs.

. Start the Open Liberty server.

. Download the `liberty_logstash.conf` sample Logstash configuration file from the directory that corresponds to your version of the Elastic stack in link:https://github.com/WASdev/sample.dashboards[Sample dashboards for Liberty].

. In the Logstash configuration file, customize the Beats port, `port:port_number`, and the Elasticsearch hosts value `Elasticsearch_host_name:port_number` with your port number and Elasticsearch hostname.

. Download the sample Filebeat configuration file for your Filebeat version from link:https://github.com/WASdev/sample.dashboards[Sample dashboards for Liberty].
+
- For Filebeat 5.x, use the `liberty_filebeat5.yml` file.
- For Filebeat 6.x, use the `liberty_filebeat6.yml` file
- For Filebeat 7.x, use the `liberty_filebeat7.yml` file

. In the Filebeat configuration file, change the path of the log to the location of the `messages.log` file.

. Start Elasticsearch, Logstash, Kibana, and Filebeat. +
See link:https://www.elastic.co/[the Elastic website] for instructions.

. Open Kibana in a browser and create an index.
+
Click **Management** > **Index Patterns**.

- For Kibana 7, 6 and 5.6:
** Enter `logstash-*` as the **Index Pattern**.
** Click **Advanced Options** and enter `logstash-*` as the **Index Pattern ID**.
** Select `ibm_datetime` as the **Time filter** field name and click **Create**.

- For Kibana 5.0-5.5:
** Select `ibm_datetime` as the **Time filter** field name and click **Create**.

. Download one or more of the sample dashboards from the directory that corresponds to your version of Kibana in link:https://github.com/WASdev/sample.dashboards[Sample dashboards for Liberty.]
+
- For Kibana 5.x, download JSON files that start with `kibana5`.
- For Kibana 6.x, download JSON files that start with `kibana6`.
- For Kibana 7.x, download JSON files that start with `kibana7`.

. Import the dashboard into Kibana.
+
Click **Management** > **Saved Object** > **Import** and select a dashboard that you downloaded in step 8.

. View the dashboard.
+
Click **Dashboard** > **Open** and select the dashboard that you imported in step 9.

== Results

You can now send your Open Liberty logs to the Elastic Stack and analyze them by using the provided sample Kibana dashboards.

== See also

- To learn more about log management solutions for Open Liberty, see xref:log-management.adoc[Log management].
- To learn about Open Liberty logs and logging configuration options, see xref:log-trace-configuration.adoc[Log and trace configuration].
