// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: You can set authentication filters to specify the authentication mechanisms that process different types of HTTP servlet requests.
:seo-title: Authentication filters
:seo-description: You can set authentication filters to specify the authentication mechanisms that process different types of HTTP servlet requests.
:page-layout: general-reference
:page-type: general
= Authentication filters

An authentication filter specifies how a request for application resources is authenticated. You can set authentication filters to process different types of HTTP servlet requests with different authentication mechanisms, such as SPNEGO or JSON Web Tokens.

For example, if two applications are running on the same Open Liberty server, an authentication filter can specify different types of authentication for each application. In this case, a web application can be secured with a social media login, while a microservice on the same server is secured by a lightweight directory access protocol (LDAP) registry.

Similarly, in a single application where different kinds of protected resources require different types of authentication, filters can control how authentication is managed for each resource. For example, in a banking application, resources for customers might be accessible through social media login while resources for administrators are secured by SPNEGO authentication.

Authentication mechanisms in Open Liberty are managed by the server configuration. In the `server.xml` file, you can specify filters to control which authentication mechanism processes certain types of requests. For example, you can filter requests that contain the `/mywebapp` URL pattern to be processed by social media login, and requests that contain the `/EmployeeRoleServlet` URL pattern to be processed by SPNEGO. You can configure filters to look for different characteristics of a request, such as URL pattern, IP address, domain name, browser type, and more.

Open Liberty supports authentication filters for various authentication mechanisms, including the following options:

* xref:reference:feature/mpJwt-1.1.adoc[JSON Web Tokens]
* xref:reference:feature/samlWeb-2.0.adoc[SAML web]
* xref:reference:feature/spnego-1.0.adoc[Simple and Protected GSSAPI Negotiation Mechanism (SPNEGO)]
* xref:reference:feature/#socialLogin-1.0.adoc[Social Media Login]

For example, you can configure an authentication filter on the link:/docs/ref/feature/#socialLogin-1.0.html[Social Media Login] feature to specify a particular type of social media credentials for requests from a web application. In the following example, request URLs that contain the `/mywebapp` pattern are authenticated by using Google credentials:

include::reference/feature/socialLogin/examples.adoc[tag=authfilter]

For more authentication filter configuration examples, see the following features:

* xref:reference:feature/spnego-1.0.adoc[Simple and Protected GSSAPI Negotiation Mechanism (SPNEGO): Apply SPNEGO authentication to a subset of HTTP requests]
* xref:reference:feature/mpJwt-1.1.adoc[MicroProfile JSON Web Token: Specify login with Micrprofile JSON Web Token for only a subset of applications, URLs, browsers, or IP addresses]

== See also

Authentication filters give you nuanced control over how you manage authentication to the protected resources in your application. For more information, see link:/docs/ref/config/#authFilter.html[Authentication Filter].
