// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: You can set authentication filters to specify the authentication mechanisms that secure different types of HTTP servlet requests.
:seo-title: Authentication filters
:seo-description: You can set authentication filters to specify the authentication mechanisms that secure different types of HTTP servlet requests.
:page-layout: general-reference
:page-type: general
= Authentication filters

An authentication filter specifies how a request for application resources is authenticated. You can set authentication filters to secure different types of HTTP servlet requests with different authentication mechanisms, such as SPNEGO or JSON Web Tokens.

Authentication mechanisms in Open Liberty are managed by the server configuration. In an application where different kinds of protected resources require different authentication mechanisms, authentication filters can control how authentication is managed for each resource. You can configure authentication filters in your `server.xml` file to look for different characteristics of a request, such as URL pattern, IP address, domain name, browser type, and more.

For example, in a banking application, resources for customers might be accessible through social media login while resources for administrators are secured by SPNEGO. In that case, you can configure an authentication filter to secure requests that contain the `/mywebapp` URL pattern with social media login. You can set another authentication filter to secure requests that contain the `/EmployeeRoleServlet` URL pattern with SPNEGO.

Open Liberty supports authentication filters for various authentication mechanisms, including xref:reference:feature/mpJwt-1.1.adoc#_specify_login_with_microprofile_jwt_for_a_subset_of_applications_urls_browsers_or_ip_addresses[JSON Web Tokens], xref:reference:feature/spnego-1.0.adoc#_apply_spnego_authentication_to_a_subset_of_http_requests[Simple and Protected GSSAPI Negotiation Mechanism (SPNEGO)], and xref:reference:feature/socialLogin-1.0.adoc#_request_log_in_with_a_social_media_id_for_only_a_subset_of_applications_urls_browsers_or_ip_addresses[Social Media Login].

For example, you can configure an authentication filter for the feature:socialLogin[display=Social Media Login] feature to secure requests from a web application with Google credentials. In the following example, request URLs that contain the `/mywebapp` pattern are authenticated by using Google credentials:

include::../../reference/pages/feature/socialLogin/examples.adoc[tag=authfilter]

You can also specify a piped list of values to filter to an authentication mechanism. In the following example, a piped list of web applications is specified. To process an incoming request with the mechanism that uses this filter, the request must target any of the `myApp1`, `myApp2`, or `myApp3` applications.

[source,xml]
----
<authFilter id="myAuthFilter">
         <webApp id="myWebApp" name="myApp1|myApp2|myApp3" matchType="contains"/>
</authFilter>
----

For more information, see xref:reference:config/authFilter.adoc[the authFilter element documentation].

== See also

* xref:reference:feature/spnego-1.0.adoc#_apply_spnego_authentication_to_a_subset_of_http_requests[Simple and Protected GSSAPI Negotiation Mechanism (SPNEGO): Apply SPNEGO authentication to a subset of HTTP requests]
* xref:reference:feature/mpJwt-1.1.adoc#_configure_authentication_filter_to_login_with_microprofile_jwt[MicroProfile JSON Web Token: Specify login with Micrprofile JSON Web Token for only a subset of applications, URLs, browsers, or IP addresses]

* xref:reference:feature/samlWeb/examples.adoc#authfilter[Configure SAML authentication for a subset of requests]
