// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: You can set authentication filters to specify the authentication mechanisms that secure different types of HTTP servlet requests.
:seo-title: Authentication filters
:seo-description: You can set authentication filters to specify the authentication mechanisms that secure different types of HTTP servlet requests.
:page-layout: general-reference
:page-type: general
= Authentication filters

An authentication filter specifies how a request for application resources is authenticated. You can set authentication filters to secure different types of HTTP servlet requests with different authentication mechanisms, such as SPNEGO or JSON Web Tokens.

Authentication mechanisms in Open Liberty are managed by the server configuration. In an application where different kinds of protected resources require different authentication mechanisms, authentication filters can control how authentication is managed for each resource. You can configure authentication filters in your `server.xml` file to look for different characteristics of a request, such as URL pattern, IP address, domain name, browser type, and more.

For example, in a banking application, resources for customers might be accessible through social media login while resources for administrators are secured by SPNEGO. In that case, you can configure an authentication filter to secure requests that contain the `/mywebapp` URL pattern with social media login. You can set another authentication filter to secure requests that contain the `/EmployeeRoleServlet` URL pattern with SPNEGO.

Open Liberty supports authentication filters for various authentication mechanisms, including xref:reference:feature/mpJwt-1.1.adoc#_specify_login_with_microprofile_jwt_for_a_subset_of_applications_urls_browsers_or_ip_addresses[JSON Web Tokens], xref:reference:feature/spnego-1.0.adoc#_apply_spnego_authentication_to_a_subset_of_http_requests[Simple and Protected GSSAPI Negotiation Mechanism (SPNEGO)], and xref:reference:feature/socialLogin-1.0.adoc#_request_log_in_with_a_social_media_id_for_only_a_subset_of_applications_urls_browsers_or_ip_addresses[Social Media Login].

For example, you can configure an authentication filter for the link:/docs/ref/feature/#socialLogin-1.0.html[Social Media Login] feature to secure requests from a web application with Google credentials. In the following example, request URLs that contain the `/mywebapp` pattern are authenticated by using Google credentials:

include::../../reference/pages/feature/socialLogin/examples.adoc[tag=authfilter]

== Supported elements
The `authFilter` element supports the following configuration elements:

- `userAgent` +
The value for this element is compared against a corresponding header value from the incoming HTTP servlet request, which identifies the client software that is used by the originating request. For web client browsers, this value reflects the browser type that is used to initiate the request, such as Chrome, Firefox, or Safari. In the following example, incoming requests from a Firefox browser are processed by an authentication mechanism that specifies the `myAuthfilter` authentication filter: +
[source,java]
---
<authFilter id="myAuthFilter">
         <userAgent id="myUserAgent" agent="Firefox" matchType="equals"/>
</authFilter>
---

- `host` +
The host element is compared against the `Host` HTTP request header, which identifies the target hostname of the incoming request. In the following example, incoming requests for the `host.example.com` host are processed by an authentication mechanism that specifies the `myAuthfilter` authentication filter: +
[source,java]
---
<authFilter id="myAuthFilter">
         <host id="myHost" name="host.example.com" matchType="contains"/>
</authFilter>
---

- `webApp` +
The webApp element specifies the application, or list of applications, that are hosted on the Open Liberty server that is protected by this authentication filter.
In the following example, incoming requests that target the `myApp1` application are processed by an authentication mechanism that specifies the `myAuthfilter` authentication filter:
+
[source,java]
---
<authFilter id="myAuthFilter">
         <webApp id="myWebApp" name="myApp" matchType="contains"/>
</authFilter>
---

- `remoteAddress` +
The value for the `remoteAddress` element is compared against the remote TCP/IP address of the client application that sent the HTTP request.
In the following example, incoming requests from the IP address `127.0.0.1` are processed by an authentication mechanism that specifies the `myAuthfilter` authentication filter: +
[source,java]
---
<authFilter id="myAuthFilter">
         <remoteAddress id="myRemoteAddress" ip="127.0.0.1" matchType="equals"/>
</authFilter>
---

- `requestUrl` +
The `requestUrl` element is compared against the URL that is used by the client application to make the request.
In the following example, any incoming request with a request URL that contains the `/SimpleServlet` URL pattern is processed by an authentication mechanism that specifies the `myAuthfilter` authentication filter:
+
[source,java]
---
<authFilter id="myAuthFilter">
         <requestUrl id="myRequestUrl" urlPattern="/SimpleServlet" matchType="contains"/>
</authFilter>
---

- `requestHeader` +
The `requestHeader` element is compared against the request header of the incoming request. In the following example, any request with the `email` request header is processed by an authentication mechanism that specifies the `myAuthfilter` authentication filter:
+
[source,java]
---
<authFilter id="myAuthFilter">
         <requestHeader id="myRequestHeader" name="email" matchType="contains"/>
</authFilter>
---


For more information, see xref:reference:config/authFilter.adoc[the authFilter element documentation].

== See also

* xref:reference:feature/spnego-1.0.adoc#_apply_spnego_authentication_to_a_subset_of_http_requests[Simple and Protected GSSAPI Negotiation Mechanism (SPNEGO): Apply SPNEGO authentication to a subset of HTTP requests]
* xref:reference:feature/mpJwt-1.1.adoc#_specify_login_with_microprofile_jwt_for_a_subset_of_applications_urls_browsers_or_ip_addresses[MicroProfile JSON Web Token: Specify login with Micrprofile JSON Web Token for only a subset of applications, URLs, browsers, or IP addresses]
