// Copyright (c) 2025 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The Bring your own AES-256 key feature allows you to supply a Base64-encoded 256-bit AES key for password encryption in Open Liberty. By providing a pre-generated key, you can avoid deriving a key from a passphrase during server startup and improve performance when encrypted values are processed.
:seo-title: Bring your own AES-256 key for Liberty passwords
:page-layout: general-reference
:page-type: general


= Bring your own AES-256 key for Liberty passwords

The Bring your own AES-256 key feature allows you to supply a Base64-encoded 256-bit AES key for password encryption in Open Liberty. By providing a pre-generated key, you can avoid deriving a key from a passphrase during server startup and improve performance when encrypted values are processed.

In earlier versions, Open Liberty supported the `wlp.password.encryption.key` variable, which accepted a password and derived an AES key by repeatedly hashing the password with a salt over many iterations. This derivation increased CPU cost overhead and slowed server startup.

By specifying the `wlp.aes.encryption.key` configuration variable with a Base64-encoded 256-bit AES key, you bypass key derivation. The encoded password format remains unchanged, which supports migrations from traditional WebSphere Application Server (tWAS). Future migration tooling will allow tWAS encryption keys to be exported for use with Liberty.

== Generate a 256-bit AES key

You can obtain a 256-bit AES key from your security infrastructure or generate one by using the `securityUtility generateAESKey` command.

To generate a random AES key, run the following command.

[source,sh]
----
securityUtility generateAESKey
----

To derive a key from a passphrase, specify the `--key` option. 

[source,sh]
----
securityUtility generateAESKey --key=<password>
----

Optionally, To generate a key and automatically create an XML configuration file, use the following example.

[source,sh]
----
securityUtility generateAESKey --createConfigFile=myAesConfig.xml
----

== Configure the AES key in Liberty

To configure the AES key directly in your `server.xml` file, add the following variable definition.

[source,xml]
----
<variable name="wlp.aes.encryption.key" value="<your_aes_key>" />
----

Or to load the AES key from an external configuration file (such as the one generated by `generateAESKey --createConfigFile`),  include the file by using the following configuration.

[source,xml]
----
<include location="/path/to/aesConfig.xml" />
----

== Encode passwords with the AES key

You can encode passwords that use the AES-256 key by running the `securityUtility encode` command.

To specify the Base64-encoded key directly, use the following options.

[source,sh]
----
securityUtility encode --encoding=aes --base64Key=<your_base64_key> <password>
----

To use an XML or Java properties file that contains the AES key variable, specify the `--aesConfigFile` option:

[source,sh]
----
securityUtility encode --encoding=aes --aesConfigFile=<xml_or_properties_file> <password>
----

Copy the resulting encrypted value into your Liberty configuration.

[NOTE]
====
For best performance, re-encode all passwords by using the new AES-256 key. Open Liberty supports older password formats, but full migration provides consistent startup performance.
====

== Updated command options

Several Liberty utilities now support Base64-encoded AES keys and AES key configuration files.

The following example shows how to specify an AES configuration file when installing assets by using the `configUtility install` command:

[source,sh]
----
configUtility install --aesConfigFile=myAesConfig.xml
----

You can also use an AES key configuration file when creating a collective:

[source,sh]
----
collective create --aesConfigFile=aesKeys.properties
----

To provide the AES key directly when joining a collective, specify the `--base64Key` option:

[source,sh]
----
collective join --base64Key=<your_base64_key>
----

The following example shows how to replicate configuration updates by using an AES key configuration file:

[source,sh]
----
collective replicate --aesConfigFile=aesConfig.xml
----

[NOTE]
====
All Liberty command-line utilities that support AES encryption accept either of the following options:

* `--base64Key`: Provide the Base64-encoded AES key directly.
* `--aesConfigFile`: Provide a configuration file that defines either `wlp.aes.encryption.key` or `wlp.password.encryption.key`.

You can use it with the `securityUtility`, `configUtility`, and `collective` commands.
====

== Updated certificate and key management tasks

The `securityUtility createSSLCertificate` and `securityUtility createLTPAKeys` commands support AES-based encryption options.

To generate an SSL certificate by using a Base64-encoded AES key for encrypting the keystore password, run the following command:

[source,sh]
----
securityUtility createSSLCertificate \
  --passwordBase64Key=<your_base64_key> \
  --outputFile=mySSL.p12
----

The following example shows how to create LTPA keys by using a configuration file that contains the AES key definition:

[source,sh]
----
securityUtility createLTPAKeys \
  --aesConfigFile=aesConfig.xml \
  --outputFile=myLTPA.keys
----

== New securityUtility task

The `generateAESKey` task generates a Base64-encoded 256-bit AES key for the `wlp.aes.encryption.key` variable.

To display command usage, see the following syntax:

[source,sh]
----
securityUtility generateAESKey [options]
----

=== Description

Generates a value for the `wlp.aes.encryption.key` configuration variable. If no options are specified, a random AES key is generated.

=== Options

`--createConfigFile=<name>`::  
Creates an XML file that contains the generated AES key in the `wlp.aes.encryption.key` variable. If this option is omitted, the generated key is written to the console.

`--key=<string>`::  
Derives an AES key from the provided passphrase. If omitted, a random AES key is generated.

== Configuration reference

The following variable, task, and command options support the Bring your own AES-256 key feature.

[cols="30,70", options="header"]
|===
| Name | Description

| `wlp.aes.encryption.key`
| Stores a Base64-encoded 256-bit AES key for password encryption. Only one AES-related variable can be defined in a configuration file.

| `generateAESKey`
| A `securityUtility` task that generates an AES-256 key and optionally writes it to an XML configuration file.

| `--base64Key=<value>`
| Specifies a Base64-encoded 256-bit AES key that is used to encrypt and decrypt passwords. Cannot be combined with `--aesConfigFile` or `--key`.

| `--aesConfigFile=<file>`
| Specifies an XML or properties file that contains either the `wlp.password.encryption.key` or `wlp.aes.encryption.key` variable. Only one variable can be present in a file. Cannot be combined with `--base64Key` or `--key`.

| `--passwordBase64Key=<value>`
| Used by SSL certificate and LTPA key utilities to encrypt generated passwords by using a Base64-encoded AES-256 key. Cannot be combined with `--aesConfigFile` or `--passwordKey`.
|===

