// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty supports two JMX connectors, local connector and REST connector.
:seo-title: Designing cloud-native microservices
:seo-description: Open Liberty supports two JMX connectors, local connector and REST connector.
:page-layout: general-reference
:page-type: general
= Configuring JMX connections

You can monitor and manage registered resources in your Open Liberty server by using Jakarta Management Extensions (JMX) management beans (MBeans).
You can access individual JMX MBeans by remotely connecting to the Open Liberty MBean server through a secure JMX connection to the Open Liberty REST connector.

== Configuring a secure remote JMX connection to Open Liberty

You can configure a secure JMX connection by enabling the feature:restConnector[display=Admin REST connector feature], configuring Transport Layer Security (TLS), and adding at least one user to the administrator or reader management roles.
By default, the Admin REST Connector feature enables the feature:transportSecurity[display=Transport Security feature], which supports TLS connections.
Remote access with a JMX connection is protected by a single administrator or reader role through the HTTPS port that is defined by the default config:httpEndpoint[display=HTTP Endpoint] element.

You can access an Open Liberty REST connector from a Java client or directly through an HTTPS call to the JMX endpoints of the administrative REST APIs.
A Java client uses the client-side of the REST connector, which is in the `wlp/clients/restConnector.jar` file and implements the `javax.management.MBeanServerConnection` interface.
HTTPS calls use the server-side of the REST connector.
Any programming language that can make HTTPS calls can use the REST APIs.


To configure a secure JMX connection, complete the following steps:

. Enable the feature:restConnector[display=Admin REST connector feature] and Configure TLS certificates in your `server.xml` file.
Ensure that the CN value of the certificate `subjectDN` entry is the host name of the machine where the server is running.
If you plan to use the `jConsole` tool that the trust store contains the certificate of the server in the `jConsole` connection.

. link:/docs/latest/reference/feature/appSecurity-3.0.html#_configure_rest_api_management_roles[Configure at least one user or group to the administrator or reader role] in your `server.xml` file.
For testing and development purposes, you can quickly configure a single user in the administrator role by link:/docs/latest/reference/feature/appSecurity-3.0.html#_configure_a_basic_user_registry_with_quickstart_security[configuring QuickStart security].

. Access the REST connector by using a Java client application, through the https://docs.oracle.com/en/java/javase/17/management/using-jconsole.html#GUID-77416B38-7F15-4E35-B3D1-34BFD88350B5[jConsole tool] that is provided by the Java SDK, or by making HTTPS calls directly to the server.

== See also

link:/docs/latest/introduction-monitoring-metrics.html#_jmx_metrics[JMX metrics]
