// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty supports two JMX connectors, local connector and REST connector.
:seo-title: Designing cloud-native microservices
:seo-description: Open Liberty supports two JMX connectors, local connector and REST connector.
:page-layout: general-reference
:page-type: general
= Configuring JMX connections

Java Management Extensions (JMX) is a standard for monitoring and managing registered resources in the server.
You can configure a JMX connector for your application to access the MBeanServer on Open Liberty, by using the REST connector feature.

== Configuring a secure remote JMX connection to Open Liberty

An application deployed on Open Liberty has unrestricted access to its MBeanServer directory.
You can get a secure JMX connection for your application remotely with the feature:restConnector[display=Admin REST Connector] feature by using SSL.
The REST connector feature includes the feature:ssl[display=Secure Socket Layer] feature.
Remote access with the REST connector is protected by a single administrator role through the HTTPS port that is defined by the default `httpEndpoint` element.
HTTPS calls use the server-side of the connector with any programming language that can make HTTPS calls, such as C++, JavaScript, and curl, to use the REST APIs.
A Java client uses the client-side of the connector, which is in the `wlp/clients/restConnector.jar` file and implements the `javax.management.MBeanServerConnection` interface.


JMX connectors can be accessed on Open Liberty with a REST connector by using SSL.

To get a secure JMX connection remotely, enable the Admin REST Connector feature.

Configure the xref:secure-communication-tls.adoc[Secure communication with Transport Layer Security (TLS)], by enabling the feature:transportSecurity[display=Transport Security] feature.
Then, xref:application-configuration-hardening.adoc#user-roles-access[configure a user or group] to the administrator role in the `server.xml` file.

You can also access xref:introduction-monitoring-metrics.adoc#_jmx_metrics[JMX metrics] with monitoring tools like JConsole.
