// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty supports two JMX connectors, local connector and REST connector.
:seo-title: Designing cloud-native microservices
:seo-description: Open Liberty supports two JMX connectors, local connector and REST connector.
:page-layout: general-reference
:page-type: general
= Configuring JMX connections

Java Management Extensions (JMX) is a standard for monitoring and managing registered resources in the server.
You can configure a JMX connector for your application to access the MBeanServer on Open Liberty, by using the REST connector feature locally or remotely.



== Configuring a secure remote JMX connection to Open Liberty

An application deployed on Open Liberty has unrestricted access to its MBeanServer directory.
The REST connector is enabled through the `restConnector` feature.
Remote access through the REST connector is protected by a single administrator role through the HTTPS port that is defined by the default `httpEndpoint` element.
HTTPS calls use the server-side of the connector with any programming language that can make HTTPS calls, such as C++, JavaScript, and curl, to use the REST APIs.
A Java client uses the client-side of the connector, which is in `wlp/clients/restConnector.jar` file and implements the `javax.management.MBeanServerConnection` interface.


JMX connectors can be accessed on Open Liberty by with a Rest connector by using SSL.
The REST connector feature already includes the `ssl-1.0` feature.

To get a secure JMX connection remotely, enable the Open Liberty link:https://openliberty.io/docs/20.0.0.10/reference/feature/restConnector-2.0.html[restConnector] feature.

Configure the link:https://openliberty.io/docs/20.0.0.11/secure-communication-tls.html[SSL certificates], by enabling the link:https://openliberty.io/docs/20.0.0.11/reference/feature/transportSecurity-1.0.html[transportSecurity] feature.
Then, link:https://openliberty.io/docs/20.0.0.10/application-configuration-hardening.html#user-roles-access[configure a user or group] to the administrator role in the `server.xml` file.

Thus, with the `restConnector` feature you can access the JVM’s MBeanServer, either locally or remotely.
