// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty supports two JMX connectors, local connector and REST connector.
:seo-title: Designing cloud-native microservices
:seo-description: Open Liberty supports two JMX connectors, local connector and REST connector.
:page-layout: general-reference
:page-type: general
= Configuring JMX connection

Open Liberty supports two JMX connectors: local connector and REST connector.
Each connector is enabled through a different feature.

== Configuring local JMX connection to Open Liberty

You can access the local Java Management Extensions (JMX) connector on Open Liberty.

=== About this task

The local connector is enabled through the `localConnector-1.0` feature.
Access through the local connector is protected by the policy that is implemented by the SDK in use.
Currently, the SDKs require that the client runs on the same host as Open Liberty, and under the same user ID.


=== Procedure

The following steps describe how to configure and access the local connector on Liberty:


1. Enable the local connector by using the following code in the `server.xml` file, inside the `featureManager` element:

[source, xml]
----
<feature>localConnector-1.0</feature>
----

2. Access the local connector by using the JConsole tool or the JMX client that is installed on the same host.
   - Copy the contents of ``${server.output.dir}/logs/state/com.ibm.ws.jmx.local.address` directory to the clipboard.
   - For the JConsole tool, paste the contents of the clipboard into the Remote Process field.
     If you select the local process `ws-server.jar defaultServer` instance on the connection panel, then click Connect to connect to the MBeanServer by using the JDK bridge.
     The Liberty bridge is more reliable.
   - For the JMX client, paste the contents of the clipboard into the constructor of a `javax.management.remote.JMXServiceURL` object.
    Use that JMXServiceURL to establish a connection through `javax.management.remote.JMXConnectorFactory` instance.
    If the JMX client is running on the same JVM as Liberty, you do not have to use the connector, instead you can access the MBeanServer directly.

== Configuring secure JMX connection to Liberty

You can access the secured Java Management Extensions (JMX) connectors on Liberty by using SSL.

=== About this task

The REST connector is enabled through the `restConnector-2.0` feature.
The `restConnector-2.0` feature supersedes the `restConnector-1.0` feature.
Remote access through the REST connector is protected by a single administrator role through the HTTPS port that is defined by the default `httpEndpoint` element.
In addition, SSL is required to keep the communication confidential.
The REST connector features already include the `ssl-1.0` feature.


=== Procedure

The following section describes how to configure and access the REST connector on Open Liberty:

1. Enable the REST connector by using the following code in the `server.xml` file, inside the featureManager element.

[source, xml]
----
<feature>restConnector-2.0</feature>
----

2.  Configure SSL certificates in the `server.xml` file.
Ensure that the CN value of the certificate subjectDN is the hostname of the machine where the server is running.
Also, ensure that the truststore contains the certificate of the server in the jConsole connection.

3.  Configure a user or group to the administrator role in the `server.xml` file.

4. Access the REST connector.
You can access an Open Liberty REST connector from a Java client or directly through an HTTPS call.
A Java client uses the client-side of the connector, which is in `wlp/clients/restConnector.jar` file and implements the `javax.management.MBeanServerConnection` interface.
HTTPS calls use the server-side of the connector.
For HTTPS calls on the server-side, any programming language that can make HTTPS calls, such as C++, JavaScript, curl, Ruby, and Perl, can use the REST APIs.
The REST APIs contain endpoints for management (JMX), file transfer, collective routing, and collective deployment.
