// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty supports two JMX connectors, local connector and REST connector.
:seo-title: Designing cloud-native microservices
:seo-description: Open Liberty supports two JMX connectors, local connector and REST connector.
:page-layout: general-reference
:page-type: general
= Configuring JMX connections

You can configure a Java Management Extensions (JMX) connector for your application to access an MBean server on Open Liberty.
The JMX connector can be configured locally or remotely, to manage  registered JMX resources in the server.

With the `localConnector-1.0` feature, you can access a local JMX connector that is built into the JVM and get the JMX connector address.
 The local connector can only be used on the same host machine by a client that has the same user ID and the same JDK as the server process.
Therefore, the `localConnector-1.0` feature can be used only for local connections.
`restConnector-1.0` provides a direct and reliable method to access the JVM’s MBeanServer, either locally or remotely.

== Configuring local JMX connection to Open Liberty

The local connector feature helps you to access the local JMX connector on Open Liberty to manage JMX resources.
To enable the `localConnector-1.0` feature see the feature documentation.
Use JConsole tool or the JMX client that is installed on the same host to access the local connector.

For the JConsole tool , copy the contents of  the `${server.output.dir}/logs/state/com.ibm.ws.jmx.local.address` directory into the Remote Process field.
Then click Connect, to use the JDK bridge to connect to the MBeanServer.

For the JMX client, copy the contents of the `${server.output.dir}/logs/state/com.ibm.ws.jmx.local.address` directory into the constructor of a `javax.management.remote.JMXServiceURL` object.
Then, use the `JMXServiceURL` to establish a connection through `javax.management.remote.JMXConnectorFactory` instance.


== Configuring secure remote JMX connection to Liberty

You can access the secured Java Management Extensions (JMX) connectors on Liberty by using SSL.

=== About this task

The REST connector is enabled through the `restConnector-2.0` feature.
The `restConnector-2.0` feature supersedes the `restConnector-1.0` feature.
Remote access through the REST connector is protected by a single administrator role through the HTTPS port that is defined by the default `httpEndpoint` element.
In addition, SSL is required to keep the communication confidential.
The REST connector features already include the `ssl-1.0` feature.


=== Procedure

The following section describes how to configure and access the REST connector on Open Liberty:

1. Enable the REST connector by using the following code in the `server.xml` file, inside the `featureManager` element.

[source, xml]
----
<feature>restConnector-2.0</feature>
----

2.  Configure SSL certificates in the `server.xml` file.
Ensure that the CN value of the certificate subjectDN is the hostname of the machine where the server is running. Also, ensure that the truststore contains the certificate of the server in the jConsole connection.

3.  Configure a user or group to the administrator role in the `server.xml` file.

4. Access the REST connector.
You can access an Open Liberty REST connector from a Java client or directly through an HTTPS call.
A Java client uses the client-side of the connector, which is in `wlp/clients/restConnector.jar` file and implements the `javax.management.MBeanServerConnection` interface.
HTTPS calls use the server-side of the connector.
For HTTPS calls on the server-side, any programming language that can make HTTPS calls, such as C++, JavaScript, curl, Ruby, and Perl, can use the REST APIs.
The REST APIs contain endpoints for management (JMX), file transfer, collective routing, and collective deployment.
