// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//    https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: A container image is a layered executable software package that contains everything you need to build and run a containerized application. You can use an Open Liberty container image to build an application image that meets your development needs.
:seo-title: Open Liberty container images
:seo-description: A container image is a layered executable software package that contains everything you need to build and run a containerized application. You can use an Open Liberty container image to build an application image that meets your development needs.
:page-layout: general-reference
:page-type: general
= Open Liberty container images

A container image is a layered executable software package that contains everything you need to build and run a containerized application. You can use an Open Liberty container image to build an application image that meets your development needs.

Open Liberty container images are available from the IBM Container Registry (ICR). You can pull images from ICR without authentication.

== Container images on IBM Container Registry

You can append an Open Liberty container image tag to the `icr.io/appcafe/open-liberty:` source to specify the details of the container image that you pull from ICR. For more information, see the <<#build,Build an application image>> section.

Select from the following container image tags for the latest Open Liberty release from ICR.

NOTE: The final Liberty release that will publish container images built on UBI Standard will be `26.0.0.12`. Avoid trouble by using an image based on UBI Micro or UBI Minimal instead of UBI Standard. For more information, see announcement at https://www.ibm.com/support/pages/node/7268632[IBM Support page].

* `kernel-slim-java25-openj9-ubi-micro`
* `kernel-slim-java21-openj9-ubi-micro`
* `kernel-slim-java17-openj9-ubi-micro`
* `kernel-slim-java11-openj9-ubi-micro`
* `kernel-slim-java8-openj9-ubi-micro`
* `kernel-slim-java8-ibmjava-ubi-micro`

* `full-java25-openj9-ubi-micro`
* `full-java21-openj9-ubi-micro`
* `full-java17-openj9-ubi-micro`
* `full-java11-openj9-ubi-micro`
* `full-java8-openj9-ubi-micro`
* `full-java8-ibmjava-ubi-micro`

* `kernel-slim-java25-openj9-ubi-minimal`
* `kernel-slim-java21-openj9-ubi-minimal`
* `kernel-slim-java17-openj9-ubi-minimal`
* `kernel-slim-java11-openj9-ubi-minimal`
* `kernel-slim-java8-openj9-ubi-minimal`
* `kernel-slim-java8-ibmjava-ubi-minimal`

* `full-java25-openj9-ubi-minimal`
* `full-java21-openj9-ubi-minimal`
* `full-java17-openj9-ubi-minimal`
* `full-java11-openj9-ubi-minimal`
* `full-java8-openj9-ubi-minimal`
* `full-java8-ibmjava-ubi-minimal`

* `kernel-slim-java17-openj9-ubi`
* `kernel-slim-java11-openj9-ubi`
* `kernel-slim-java8-openj9-ubi`
* `kernel-slim-java8-ibmjava-ubi`

* `full-java17-openj9-ubi`
* `full-java11-openj9-ubi`
* `full-java8-openj9-ubi`
* `full-java8-ibmjava-ubi`

* `beta`
* `latest`

These tags pull the latest version because they do not specify a version number. You can specify a version other than the latest version in the image tag. If you do not specify a tag value, `latest` is used by default. For more information about these tag values, see the <<#tags,Container image tags naming conventions>> section.

After the initial release of the Liberty container images, they are refreshed regularly (every 1-2 weeks) to include fixes for the operating system (OS) and Java. For more information on the full list of supported Open Liberty container images, see the link:https://github.com/OpenLiberty/ci.docker/blob/main/docs/icr-images.md[IBM Container Registry (ICR) page on the Open Liberty GitHub repository].

If you have an IBM Cloud ID, you can generate a list of the currently available images in ICR by using the link:https://cloud.ibm.com/docs/cli?topic=cli-getting-started[IBM Cloud CLI] with the link:https://cloud.ibm.com/docs/Registry?topic=Registry-containerregcli[IBM Cloud Container Registry CLI plug-in] installed. Authentication is required only to list the images. You can pull images from ICR without authentication. To list the images, run the following commands.

----
ibmcloud login
ibmcloud cr region-set global
ibmcloud cr images --restrict appcafe/open-liberty
----

[#build]
== Build an application image

You can use an Open Liberty container image tag in a `Dockerfile` or `Containerfile` file to build an application image that adds a single application and its corresponding configuration. Do not configure the container manually after it is started, except for debugging purposes, because these changes are not reflected in new containers that are created from the image.

Set your image template similar to the following example, which uses the `kernel-slim-java25-openj9-ubi-micro` tag to build an image that uses the latest Open Liberty release with the OpenJ9 distribution of Java 25.

[source,dockerfile]
----
FROM icr.io/appcafe/open-liberty:kernel-slim-java25-openj9-ubi-micro

# Add a Liberty server configuration including all necessary features
COPY --chown=1001:0  server.xml /config/

# This script adds the requested XML snippets to enable Liberty features and grow the image to be fit-for-purpose.
# This option is available only in the 'kernel-slim' image type. The 'full' and 'beta' tags already include all features.
RUN features.sh

# Add interim fixes (optional)
COPY --chown=1001:0  interim-fixes /opt/ol/fixes/

# Add an application
COPY --chown=1001:0  Sample1.war /config/dropins/

# This script adds the requested server configuration, applies any interim fixes, and populates caches to optimize the runtime.
RUN configure.sh
----

A template like this example results in a container image that has your application and configuration preinstalled, which means you can create new fully configured containers at any time. For more information about the different arguments and environment variables that you can specify to customize your application image, see the link:https://github.com/OpenLiberty/ci.docker#readme[Open Liberty container image GitHub documentation].


You can also use xref:instanton.adoc[Open Liberty InstantOn] to improve the startup time of your application container image.


[#tags]
== Container image tags naming conventions

Open Liberty container image tags use the following naming convention.
[subs=+quotes]
----
<optional fix pack version-><liberty image type>-<java version>-<java type>-<base image type>
----

The following tag values determine the resources that are included in a container image.

Fix pack version::
This value is optional. If you do not specify a fix pack version, your container image includes the latest release of Open Liberty. In addition to the latest release, the three most recent quarterly fix pack releases are always maintained for the `kernel-slim` and `full` image types.
+
Open Liberty quarterly release versions end in `.3`, `.6`, `.9`, or `.12`. For example, if the latest Open Liberty release is `26.0.0.9`, then the `26.0.0.6` and `26.0.0.3` releases are also maintained in ICR. To pull one of these release versions instead of the latest, add your chosen release version to the beginning of any of the `kernel-slim` or `full` image tags in the previous list. For example, if `26.0.0.6` is a recent quarterly release, you can pull an image that includes the `26.0.0.6` release with a Semeru distribution of Java 25 by specifying the `25.0.0.6-full-java25-openj9-ubi-micro` tag.  The `beta` image is available only for the latest beta release of Liberty and includes the latest Java JRE.

Liberty image type::
Two different image types are available: `kernel-slim` or `full`. The `full` type provides a server with all Open Liberty features and packages installed.
+
The `kernel-slim` type provides just the bare minimum server, which you can customize by adding only the features that your application needs. This image type supports the best practice for production images because you end up with a more lightweight image that packages only what is essential for your application. For more information, see the <<#build,Build an application image>> section.

Java version::
This value determines the version of Java SE that the runtime uses. Tags are available for all Java long term support (LTS) releases that are listed on the xref:java-se.adoc[Java SE Support page].

Java type::
This value determines the type of Java SE distribution that the runtime uses. Current options are IBM Semeru Runtime with Eclipse OpenJ9, named `openj9` and, for Java SE 8 only, the IBM SDK, Java Technology Edition, named `ibmjava`.
+
Both the `ibmjava` and `openj9` Java types support the Linux x86_64 (`amd64`), Linux on Power (`ppc64le`), and Linux on IBM Z (`s390x`) architectures. Only images that use the `openj9` Java type support the Linux on ARM (`arm64`) architecture.
+
Liberty images based on Universal Base Image (UBI) Micro or Minimal include JRE of IBM Semeru Runtime 25, 21, 17, 11 or 8 or IBM Java 8. This combination offers a compact and effective Java runtime.
+
Java 8, 11 and 17 images with the `openj9` type and based on UBI 8 standard include IBM Semeru Runtime for the respective Java version with the JDK. Java 8 images with the `ibmjava` type and based on UBI 8 standard include IBM Java 8 JRE.

Base image type::
Liberty images are available with three different types of Red Hat Universal Base Image (UBI): UBI Micro, UBI Minimal, or UBI Standard. 
Image tags based on UBI Micro end with `-ubi-micro`. Image tags based on UBI Minimal end with `-ubi-minimal`. Image tags based on UBI Standard end with `-ubi`. 
UBI Minimal offers a minimized pre-installed content set and the package manager `microdnf` for adding additional packages. 
Liberty images with Java 21 and higher are only available on UBI Minimal. 
`ubi` offers the standard images with access to `yum` repositories and includes utilities such as `python`, `tar`, and `gzip`. 
The version of UBI Minimal for `26.0.0.7+` is UBI 10 Minimal. 
The version of UBI Minimal for `26.0.0.6` and prior releases is UBI 9 Minimal. The version of UBI Standard is UBI 8 Standard.

In addition to the tags that follow this naming convention, Open Liberty offers the following preformatted tags that pull particular images.

* `latest`: This tag simplifies pulling the full latest Open Liberty release with the latest Java JRE. It is an alias for the `full-java25-openj9-ubi-micro` tag. If you do not specify a tag value, `latest` is used by default.
* `beta`: This tag is based on Universal Base Image (UBI) Micro and the latest Java JRE and provides the most recent beta release of Liberty, which includes all the features and capabilities from the most recent release, plus new and updated features that are currently in development. The beta image supports only the Linux x86_64 (`amd64`) architecture.

[#retrieve]
== Retrieving Open Liberty version from the container image

An Open Liberty image includes the `liberty.version` label and the `io.openliberty.version` label that specifies the Liberty version of the image.
You can use the `skopeo` command to determine the Liberty version of the specified image.

----
skopeo inspect docker://<open-liberty-image> | grep liberty.version
----

The `skopeo` command outputs the following example.

----
        "io.openliberty.version": "<liberty-version>",
        "liberty.version": "<liberty-version>",
----
