// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
= Open Liberty container images

A container image is a layered executable software package that contains everything you need to build and run a containerized application. Open Liberty offers a collection of container image tags, which you can choose from to obtain a container image that meets the needs of your application

Open Liberty container images are available from link:https://www.ibm.com/cloud/container-registry[IBM Container Registry (ICR)] at `icr.io/appcafe/open-liberty`. One advantage of using ICR instead of Docker Hub isn that ICR doesn't impose rate limits on image pulls. Images can be pulled from ICR without authentication. Only images with Universal Base Image (UBI) as the operating system are available in ICR.


Open Liberty container image tags use the following naming convention.
[subs=+quotes]
----
< _optional_fixpack_version_ >-< _liberty_image_flavor_ >-< _java_version_ >-< _java_type_ >-ubi
----

To pull a specific image, append a tag to `icr.io/appcafe/open-liberty`.
For example, to pull an image of the latest release with all features and packages that uses the OpenJ9 distribution of Java 17, use the following command.
----
icr.io/appcafe/open-liberty:full-java17-openj9-ubi
----

The images for the latest release and the most recent two quarterly releases are available at all times and are refreshed regularly. To pull the latest release, use one of the version-less tags. To pull either of the most recent quarterly releases, append the release number to the beginning of your chosen image tag. For example to pull an image of the 22.0.0.9 release in the same configuration as the previous example, use the following command.

----
icr.io/appcafe/open-liberty:22.0.0.9-full-java17-openj9-ubi
----

The following customizable tag values determine the resources that are included in a container image. For a list of the available tags, see xxxxxx.

Liberty image flavor::
Three different image flavors are available: `kernel-slim`, `full`, or `beta`. The `full` flavor provides a server with all Open Liberty features and packages installed. The `kernel-slim` flavor provides just the bare minimum server, which you can customize by adding only the features that your application needs. The `beta` flavor provides the most recent beta release, which include all the features and capabilities from the most recent Open Liberty release, plus new and updated features that are currently in development.

Java version::
This option determines the version of Java SE that the runtime uses.

Java type::
This option determines the type of Java distribution that the runtime uses. Current option are Open J9 and, for Java 8 only, the IBM SDK, Java Technology Edition.


== Supported container image tags

The following Open Liberty container image tags are supported in IBM Container Registry
