// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Open Liberty container images
:seo-description: A container image is a layered executable software package that contains everything you need to build and run a containerized application. Open Liberty offers a collection of container image tags, which you can choose from to obtain a container image that meets the needs of your application.
:page-layout: general-reference
:page-type: general
= Open Liberty container images

A container image is a layered executable software package that contains everything you need to build and run a containerized application. Open Liberty offers a collection of container image tags, which you can choose from to obtain a container image that meets the needs of your application.

Open Liberty container images are available from link:https://www.ibm.com/cloud/container-registry[IBM Container Registry (ICR)] by using the link:https://cloud.ibm.com/docs/cli?topic=cli-getting-started[IBM Cloud CLI] and appending your chosen image tag to `icr.io/appcafe/open-liberty:`. One advantage of using ICR instead of Docker Hub is that ICR doesn't impose rate limits on image pulls. Images can be pulled from ICR without authentication. Only images with Universal Base Image (UBI) as the operating system are available in ICR.

== Container image tag names
Open Liberty container image tags use the following naming convention.
[subs=+quotes]
----
_<optional fix pack version>_-_<liberty image type>_-_<java version>_-_<java type>_-ubi
----

The following tag values determine the resources that are included in a container image.

Fixpack version::
This value is optional. If you do not specify a fix pack version, your container image includes the latest release of Open Liberty. In addition to the latest release, the two most recent quarterly fix pack releases are always available in ICR. For more information, see the <<#pull,Pull a container image from ICR>> section.

Liberty image type::
Three different image types are available: `kernel-slim`, `full`, or `beta`. The `full` type provides a server with all Open Liberty features and packages installed. The `kernel-slim` type provides just the bare minimum server, which you can customize by adding only the features that your application needs. The `beta` type provides the most recent beta release, which includes all the features and capabilities from the most recent release, plus new and updated features that are currently in development.

Java version::
This option determines the version of Java SE that the runtime uses.

Java type::
This option determines the type of Java SE distribution that the runtime uses. Current options are Open J9 and, for Java SE 8 only, the IBM SDK, Java Technology Edition.

[#tags]
== Supported container image tags

The following Open Liberty container image tags are supported in IBM Container Registry.

----
kernel-slim-java8-openj9-ubi
kernel-slim-java8-ibmjava-ubi
kernel-slim-java11-openj9-ubi
kernel-slim-java17-openj9-ubi

full-java8-openj9-ubi
full-java8-ibmjava-ubi
full-java11-openj9-ubi
full-java17-openj9-ubi

beta-ubi
beta-java11-ubi
beta-java17-ubi
----

[#pull]
== Pull a container image from ICR

To pull a container image that includes the latest version of Open Liberty, append one of the previously listed tags to `icr.io/appcafe/open-liberty:`.

For example, to pull an image of the latest release version with all features and packages that uses the OpenJ9 distribution of Java 17, use the following command.
----
icr.io/appcafe/open-liberty:full-java17-openj9-ubi
----

Specifying any of these tags without including a version number results in the latest version of Open Liberty being included in the container image that you pull. In addition to the latest version, the two most recent quarterly release versions are also always available for the `kernel-slim` or `full` image types. The `beta` images are available only for the latest beta release.

Open Liberty quarterly release versions end in `3`, `6`, `9`, or `12`. For example, if the latest Open Liberty release is `22.0.0.10`, then the `22.0.0.9` and `22.0.0.6` releases are also available for the `kernel-slim` or `full` image types in ICR. To pull one of these release versions instead of the latest, add your chosen release version to the beginning of one of the previously listed `kernel-slim` or `full` image tags.

For example, to pull an image of the 22.0.0.9 release in the same configuration as the previous example, use the following command.

----
icr.io/appcafe/open-liberty:22.0.0.9-full-java17-openj9-ubi
----

However, `22.0.0.9` images are only available while that release is one of the two most recent quarterly releases. With the release of `23.0.0.3`, the `22.0.0.9` images are no longer available, as the two most recent quarterly releases are then `22.0.0.12` and `23.0.0.3`.

You can generate a list of the currently available images by using the https://cloud.ibm.com/docs/cli?topic=cli-getting-started[IBM Cloud CLI]. Authentication is required only to list the images. Images can be pulled from ICR without authentication. To list the images, log in with an IBMid before you run the following commands.

----
ibmcloud cr region-set global
ibmcloud cr images --restrict appcafe/open-liberty
----


For more information about Open Liberty container images, see the link:https://github.com/OpenLiberty/ci.docker#readme[Open Liberty container image GitHub documentation].
