// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: OpenShift is a Kubernetes-based application platform. After you write your applications, you can containerize and deploy them to OpenShift to orchestrate and automate your containers.
:seo-title: Deployment on OpenShift - OpenLiberty.io
:seo-description: OpenShift is a Kubernetes-based application platform. After you write your applications, you can containerize and deploy them to OpenShift to orchestrate and automate your containers.
:page-layout: general-reference
:page-type: general
= Deployment on OpenShift

OpenShift is a Kubernetes-based container application platform that you can use to build, containerize, and deploy your applications so that they're highly available and scalable.
You can also use the Open Liberty Operator to simplify deploying and managing your applications in the cloud.

After you develop and containerize your applications, your containers need to communicate with other containers that are running databases, security systems, or other microservices.
Containers also need to scale as services are needed.
https://www.openshift.com/[OpenShift] provides features that automate and manage containers to meet the needs of developers and operations teams.

== Running applications on OpenShift
One of the benefits of running your applications on OpenShift is that you can deploy them to a cloud-hosted Infrastructure as a Service (IaaS) solution, or to your current on-premises structure.
You can use the https://docs.openshift.com/online/starter/cli_reference/openshift_cli/getting-started-cli.html[OpenShift CLI] or https://docs.openshift.com/online/starter/cli_reference/openshift_developer_cli/understanding-odo.html[OpenShift Do CLI] to develop your applications.
Then, containerize applications in Open Liberty containers and deploy them to an OpenShift cluster.

For a step-by-step tutorial on deploying microservices to OpenShift, see the link:/guides/cloud-openshift.html[Deploying microservices to OpenShift guide].
To learn more about how your applications on Open Liberty can be used with the different OpenShift deployment options, see the https://www.openshift.com/learn/topics/deploy[OpenShift documentation].

== Open Liberty Operator
https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Operators are extensions to Kubernetes] that are customized to automate tasks beyond the initial automation that Kubernetes or OpenShift provide.
The Open Liberty Operator has a capability level of five, which means that it has the highest level of enterprise capabilities, including auto-scaling, service binding, OpenShift certificate management integration, and https://kappnav.io/[Kubernetes Application Navigator (kAppNav)] integration.

With the Open Liberty Operator, you can make applications highly available by configuring horizontal auto-scaling, which creates or deletes application instances based on resource availability and consumption.
The Operator also helps manage application deployments.
For example, after you upload a new container tag for a new version of an application, update the `applicationImage` field in the Operator deployment file with the new container tag.
Then, the Operator updates the application on a rolling basis.

This Operator also offers other production-grade capabilities, including simple configuration of persistent or advanced storage and the ability to delegate xref:reference:feature/socialLogin-1.0.adoc[single-sign on (SSO) to external providers].
The Operator automates updates of binding information among applications, meaning that it connects applications and maintains information about whether a particular application produces or consumes a service.

You can https://operatorhub.io/operator/open-liberty[install the Open Liberty Operator] from OperatorHub for use on Kubernetes or OpenShift.
The https://access.redhat.com/containers/#/registry.connect.redhat.com/ibm/open-liberty-operator[Operator is also available as a Red Hat-certified Operator] from OpenShift Container Platform (OCP).

== See also
Guide: link:/guides/kubernetes-intro.html[Deploying microservices to Kubernetes]
