// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general

= Develop with Liberty Tools

Liberty Tools is a set of capabilities for the Eclipse IDE, Visual Studio Code, and Intellij IDEA development environments. These capabilities enable fast, iterative development with Liberty dev mode and Maven or Gradle build automation tools. 

Liberty Tools automatically detects any projects that specify the https://github.com/OpenLiberty/ci.maven[Liberty Maven plug-in] or the  https://github.com/OpenLiberty/ci.gradle[Liberty Gradle plug-in] in the project `pom.xl` file. These projects are added to a special Liberty dashboard view in Eclipse IDE or Visual Studio Code, or to the Liberty Tools window in Intellij IDEA. From there, you can access a command menu to manage your projects. 

Liberty Tools also provides helpful language-support features such as code completion, hover descriptions, and configuration diagnostics for the MicroProfile API, Jakarta EE API, and Liberty configuration files.

== Minimum requirements

To use Liberty Tools, your project must specify the Liberty Maven plug-in or the Liberty Gradle plug-in in the project `pom.xl` file. A minimum level of `3.7.1` for the Liberty Maven plug-in or `3.5.1` for the Liberty Gradle plug-in is recommended. 

Language support features are available for MicroProfile 3.0 and 4.0 APIs and Jakarta EE 9.0 and later APIs.

== Develop, test, and debug in your editor

Use Liberty Tools to stop, start, or interact with xref:development-mode.adoc[Liberty dev mode] from the Liberty dashboard in Eclipse IDE or Visual Studio Code or the Liberty Tools window in Intellij IDEA. Liberty dev mode automatically detects, recompiles, and deploys code changes whenever you save a new change. It also runs unit and integration tests on demand and can attach a debugger to the running server to step through your code at any time. 
Liberty tools brings these dev mode features directly into the command menu for the Liberty projects in your editor. With a just few clicks, you can start and stop your Liberty application, run tests, and view test reports.

== Configure with core language support for Liberty, MicroProfile, and Jakarta EE 

Liberty Tools helps you quickly and easily edit your application and configuration files by providing language support features for MicroProfile, Jakarta EE, and Liberty configuration files.

=== Liberty configuration files

The following language support features are available for select Liberty configuration files.

* Code completion
+
Start typing a Liberty property, variable, or XML configuration to view a list of possible options
* Hover support
+ 
Hover your cursor over Liberty properties, variables, or XML configuration to view a description.
* Configuration diagnostics
+ 
Spot potential problems in your configuration, such as invalid values.

These features are available for the following Liberty configuration files.

* `server.env`
* `bootstrap.properties`
* `server.xml` and any XML files that are referenced through the `include` element in the `server.xml` file.
* Any XML files that contain the `server` root element and exist in the `src/main/liberty/config`, `configDropins/overrides`, `configDropins/defaults`, `usr/shared/config`, or `usr/servers` directory.

=== MicroProfile APIs

Language support for MicroProfile 3.0 and 4.0 APIs includes the following features.

* Completion, hover, validation, and Quick Fix support for MicroProfile properties in `microprofile-config.properties` files and for MicroProfile code in Java files
* Definition  and format support for MicroProfile properties in `microprofile-config.properties` files
* Outline support (flat or tree view) in `microprofile-config.properties` files
* VS Code CodeLens support for MicroProfile in Java files

=== Jakarta EE APIs

Language support for the Jakarta EE API 9.0 and later includes code completion, diagnostics, and quick fixes for select Jakarta EE APIs that are found on a project's class path.

== Try it out

You can get Liberty Tools for your development environment directly from your vendor's marketplace.

- https://plugins.jetbrains.com/plugin/14856-liberty-tools[Liberty Tools for Intellij IDEA] in the Jet Brains Marketplace
- https://marketplace.visualstudio.com/items?itemName=Open-Liberty.liberty-dev-vscode-ext[Liberty Tools for VS Code] in the Visual Studio Code marketplace
- Liberty Tools for Eclipse IDE in the Eclipse Marketplace

To learn more, check out the documentation for each project in GitHub.

- https://github.com/OpenLiberty/liberty-tools-eclipse[Liberty Tools for Eclipse]
- https://github.com/OpenLiberty/liberty-tools-intellij[Liberty Tools for IntelliJ IDEA]
- https://github.com/OpenLiberty/liberty-tools-vscode[Liberty Tools for Visual Studio Code]