// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general

= Develop with Liberty Tools

Liberty Tools are intuitive developer tools for the Eclipse IDE, Visual Studio Code, and IntelliJ IDEA development environments. These tools enable fast iterative development with Liberty dev mode and Maven or Gradle. 

Liberty Tools automatically detect Liberty Maven or Gradle projects. These projects are added to a special Liberty dashboard view in Eclipse IDE or Visual Studio Code, or to the Liberty tool window in IntelliJ IDEA. From there, you can access a command menu to manage your projects. 

Liberty Tools also provide helpful language-support features such as code completion, hover descriptions, and configuration diagnostics for MicroProfile API, Jakarta EE API, and Liberty configuration and Java files.

== Minimum requirements

To use Liberty Tools with dev mode, your project must specify the https://github.com/OpenLiberty/ci.maven[Liberty Maven plug-in] or the https://github.com/OpenLiberty/ci.gradle[Liberty Gradle plug-in] in the project `pom.xml` or `build.gradle` file. For the best experience, always use the latest available version of either plug-in. 

Although you can run your Liberty applications on any xref:java-se.adoc[supported Java SE version], Java 17 is required to run Liberty Tools in your IDE. 

== Develop, test, and debug in your editor

Use Liberty Tools to stop, start, or interact with xref:development-mode.adoc[Liberty dev mode] from the Liberty dashboard in Eclipse IDE or Visual Studio Code or the Liberty tool window in IntelliJ IDEA. Liberty dev mode automatically detects, recompiles, and deploys code changes whenever you save a new change. It also runs unit and integration tests on demand and can attach a debugger to the running server to step through your code at any time. 
Liberty Tools bring these dev mode features directly into the command menu for the Liberty projects in your editor. With just a few clicks, you can start and stop your Liberty application, run tests, and view test reports.

== Write code with editing support for Liberty configuration, MicroProfile, and Jakarta EE 

Liberty Tools help you quickly and easily edit your application and configuration files by providing language support features for MicroProfile, Jakarta EE, and Liberty configuration and Java files.

=== Liberty configuration files

The following language support features are available for select Liberty configuration files.

* Code completion: start typing a Liberty property, variable, or XML configuration to view a list of possible options.
* Hover support: hover your cursor over Liberty properties, variables, or XML configuration to view a description.
* Configuration diagnostics: spot potential problems in your configuration, such as invalid values.

These features are available for the following Liberty configuration files.

* `server.env`
* `bootstrap.properties`
* `server.xml` and any XML files that are referenced through the `include` element in the `server.xml` file
* Any XML files that contain the server root element and exist in the `configDropins/overrides`, `configDropins/defaults`, `usr/shared/config`, or `usr/servers` directory

=== MicroProfile APIs

Language support for MicroProfile 3.0 and later APIs includes the following features.

* Completion, hover, validation, and quick fix support for MicroProfile properties in `microprofile-config.properties` files and for MicroProfile code in Java files
* Definition  and format support for MicroProfile properties in `microprofile-config.properties` files
* Outline support (flat or tree view) in `microprofile-config.properties` files
* CodeLens support for MicroProfile in Java files

=== Jakarta EE APIs

Language support for the Jakarta EE API 9.x and 10.0 APIs includes the following features for select Jakarta EE APIs that are found in Java files on a project's class path. 

* Code completion
* Diagnostics
* Quick fixes   

== Try it out

You can get Liberty Tools for your development environment directly from your vendor's marketplace.

- https://plugins.jetbrains.com/plugin/14856-liberty-tools[Liberty Tools for IntelliJ IDEA] in the Jet Brains Marketplace
- https://marketplace.visualstudio.com/items?itemName=Open-Liberty.liberty-dev-vscode-ext[Liberty Tools for Visual Studio Code] in the Visual Studio Code Marketplace
- https://marketplace.eclipse.org/content/liberty-tools[Liberty Tools for Eclipse IDE in the Eclipse Marketplace]

To learn more, check out the documentation for each project in GitHub.

- https://github.com/OpenLiberty/liberty-tools-eclipse[Liberty Tools for Eclipse IDE]
- https://github.com/OpenLiberty/liberty-tools-intellij[Liberty Tools for IntelliJ IDEA]
- https://github.com/OpenLiberty/liberty-tools-vscode[Liberty Tools for Visual Studio Code]