// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:seo-description: OpenAPI is a standardized mechanism for developers to describe REST APIs  for generating structured documentation in a microservice.
:page-layout: general-reference
:page-type: general
= API documentation with OpenAPI

The MicroProfile OpenAPI specification is a MicroProfile community programming model for the OpenAPI specification.
With MicroProfile OpenAPI specification, Java developers can generate structured documentation from their JAX-RS applications.

Structured documentation helps other developers and microservices understand and communicate with your microservice.
Developers can write a web service to communicate with the REST API of another web service only if they have the relevant information to do so.
MicroProfile OpenAPI specification facilitates this communication by generating human and machine-readable documentation on a simple interface without the need to access the source code.

There are two main approaches to generate an OpenAPI document, the code-first approach and the design-first approach.
In the code-first approach, the developer can generate documentation of the REST API from the source code.
Thus, developers don’t need to rewrite the portions of the OpenAPI document that are already covered by the JAX-RS framework.
The reference document that is produced, lists all the API endpoints and descriptions of how to use them.
Alternately, in the design-first approach, you can include a pre-generated OpenAPI document that was written separately from the code.
You can also use a set of predefined models to manually create all elements of the OpenAPI tree.
You can even generate the stubs for the source code, including client libraries for the API, from this manually created documentation.

== The code-first approach

In the code-first approach, you can generate basic API documentation from your JAX-RS application; the JAX-RS annotations are processed by default.
Then, you can augment the existing JAX-RS annotations with OpenAPI annotations, which are processed to generate the documentation.
Adding annotations takes less work and gives useful explanation of the different parts of the API.

In the following example, the OpenAPI annotations `@APIResponses`, `@Operation`, and `@Parameter` are added to the two JAX-RS methods, `getPropertiesForHost()` and `listContents()`.

[source,java]
----

/inventory/systems/{hostname}:
  get:
    summary: Get JVM system properties for particular host
    description: Retrieves and returns the JVM system properties from the system
      service running on the particular host.
    operationId: getPropertiesForHost
    parameters:
    - name: hostname
      in: path
      description: The host for whom to retrieve the JVM system properties for.
      required: true
      schema:
        type: string
      example: foo
    responses:
      404:
        description: Missing description
        content:
          text/plain: {}
      200:
        description: JVM system properties of a particular host.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Properties'

/inventory/systems:
  get:
    summary: List inventory contents.
    description: Returns the currently stored host:properties pairs in the inventory.
    operationId: listContents
    responses:
      200:
        description: host:properties pairs stored in the inventory.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryList'
----

The information that is provided through the OpenAPI annotations augments the basic API documentation that is generated by the JAX-RS framework.

See the https://openliberty.io/docs/20.0.0.8/reference/javadoc/microprofile-3.3-javadoc.html[MicroProfile OpenAPI Javadoc] for the annotations that are available.

== The design-first approach

An alternative approach is to design the REST API in an editor, such as the link:https://editor.swagger.io/[Swagger editor], before you write any code.
With this approach, you can spot any problems in the design before implementation.
In large companies, it is important to have consistent, usable APIs that are reviewed by subject matter experts to verify the quality of the API design.
This API design then forms a contract and must be implemented as agreed.

You can write this API design in YAML or JSON, which can then be used to generate the documentation and, optionally, even stubs for the API code itself.
You can then also augment the documentation with annotations in the code as described.

For more information, see https://openliberty.io/guides/microprofile-openapi.html#using-pregenerated-openapi-documents[Using pregenerated OpenAPI documents].

== Filter components in and out of API documentation

Filters give the users the flexibility to modify the document after it is generated.
With link:https://download.eclipse.org/microprofile/microprofile-open-api-1.1.2/microprofile-openapi-spec.html#_filter[filters], you can implement an interface in your application.
So when a component of the documentation is processed, it calls your implementation and you can either add or remove content.

== Viewing and formatting API documentation

The documentation that is generated for the REST API is available at the `/openapi` endpoint of your web service.
The documentation is formatted by using the standard OpenAPI user interface (UI) and a default stylesheet.

== See also

Ready to try out documenting APIs with Open Liberty for yourself? Check out the guide for link:https://openliberty.io/guides/microprofile-openapi.html[Documenting RESTful APIs].
