// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: MicroProfile Config is an API that externalizes the configuration from microservices, keeping it separate from the source code. MicroProfile Config can be used by applications as a single API that can retrieve configuration information from different sources.
:seo-description: MicroProfile Config is an API that externalizes the configuration from microservices, keeping it separate from the source code. MicroProfile Config can be used by applications as a single API that can retrieve configuration information from different sources.
:page-layout: general-reference
:page-type: general
= External configuration of microservices

:MP: MicroProfile

:JWT: Java Web Token

:FT: Fault Tolerance

Microservices are deployed in multiple environments.
Externalizing the configuration with MicroProfile Config helps microservices to run in different environments without a change in code.

== Separating the configuration and code

During their lifecycle, microservices are deployed repeatedly across development, test, and production environments.
They need different configuration data, for example, deployment-specific external URLs or credentials that change regularly.
Microservices must run in these conditions without a change in code.

Backing services require changes in connection details in the application source code, for example, in databases, messaging services, and API accessible consumer services.
Your application needs to swap between local and external services without a code change.

In the cloud, microservices deployed to Kubernetes clusters must communicate.
Therefore, port binding, or knowing which port to connect to, is important.
As instances of microservices are created and destroyed to scale the application up and down in Kubernetes, port numbers can change.
You need to assign new port numbers to the microservices and inject information during startup without changing the code.
For more information, see link:/guides/kubernetes-microprofile-config.html[Configuring microservices running in Kubernetes].

Thus, it is important to change the configuration of microservices without updating or recompiling the code.

== MicroProfile Config

feature:mpConfig[display=MicroProfile Config] separates the configuration from code.
With MicroProfile Config, you can inject the external configuration into services in the containers without repackaging them.

Applications can use MicroProfile Config as a single API to retrieve configuration information from different sources such as xref:reference:config/server-configuration-overview.adoc[system properties, system environment variables], properties files, XML files, or data sources.
In MicroProfile Config, these data sources are called configuration sources.
The same configuration property can be defined in link:/guides/microprofile-config-intro.html#configuring-with-the-properties-file[multiple configuration sources].

With MicroProfile Config, you can https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#_simple_dependency_injection_example[inject an individual property into a class], or link:/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#_aggregate_related_properties_into_a_cdi_bean[inject multiple properties in one CDI bean].
You can also retrieve values from configuration https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#_aggregate_related_properties_into_a_cdi_bean[without using a CDI bean].

=== Default configuration sources

MicroProfile Config has five default configuration sources.
You can prioritize which configuration source to use for the property value.
Each configuration source has a specified priority, which is defined by its ordinal value.
A higher ordinal means that the values taken from this https://javadoc.io/static/org.eclipse.microprofile/microprofile/4.0.1/index.html?overview-summary.html[configuration source] override configuration sources with a lower ordinal value.
The following table describes the default configuration sources in MicroProfile Config and their corresponding values.

[cols="1,1,2"]
|===
|Configuration Source |Default ordinal values |Example

|All `META-INF/microprofile-config.properties` found on the class path
|100
|port=9080

|Environment variables
|300
|port=9080

|System properties
|400
|port=9080

|Defined as a variable element in the Liberty `server.xml` file
|500
| `<variable name="port" value="9080"/>`

|Defined as an appProperties property element in the Liberty `server.xml` file
|600
| `<appProperties><property name="port" value="9080"/></appProperties>`

|===

An optional default value can be specified by using link:/docs/21.0.0.1/reference/javadoc/microprofile-3.3-javadoc.html[Java annotations] and applies if the application does not find  the configuration values in any of the ConfigSources.
For more information, see link:/guides/microprofile-config-intro.html[Separating configuration from code in microservices].

MicroProfile Config can configure other MicroProfile capabilities.
It externalizes the configuration of keystores when microservices are secured.
For example, in MicroProfile JSON Web Token, the public key location and verification can be set in properties files.
If the location of the key repository changes, you can easily update it.
MicroProfile Config is also used in the configuration of channel attributes. For example, in {MP} Reactive Messaging, it can set the connection details of messaging channels, connectors, and the topic names that the application uses to produce messages. MicroProfile Config helps override values in fault tolerance. For example, in {MP} {FT}, it can set the value of an annotation so that you can change the value if the tolerance is too low or too high.

== See also

link:https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#release_notes_20[Release Notes for MicroProfile Config 2.0]
