// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-description:  
:page-layout: general-reference
:page-type: general
= Provide and consume gRPC services on Open Liberty

gRPC is an open source, universal remote procedural call (RPC) framework that can run in any environment and connects clients and services in language-agnostic way. You can provide and consume gRPC services from your web applications that run on Open Liberty.

== What is gRPC?

The link:https://grpc.io/[gRPC] framework was designed to efficiently connect microservices. It enables services and clients that use different networks, platforms and coding languages to call and implement functions through a common service definition contract. For example, you can create a gRPC service in Java with clients in Python and Go. Each application has to worry only about calling or implementing functions in its own language because gRPC handles the transmission of the calls and the generation of code in each language.

Like other RPC frameworks, gRPC defines a service contract with explicit methods, parameters, and return types. On the server side, a server implements the service interface, which is defined in a protocol buffer `.proto` file. The client is provided with stubs that define the same interfaces that are provided by the server, so the
client application can invoke remote service methods as if they were local. gRPC transport is built on top of HTTP/2, which supports high performance bidirectional connections.

gRPC uses link:https://developers.google.com/protocol-buffers/docs/reference/overview[protocol buffers] as its interface design language (IDL). Protocol buffers allow for simple service definitions and provide a language independent means to serialize structured data in remote procedural calls. They define messages that can then be compiled into any link:https://grpc.io/docs/languages[supported programming language] so that you can seamlessly transfer data structures between endpoints, even when those endpoints are working in different programming languages.


== gRPC and Open Liberty

You can build and deploy new gRPC-enabled applications on Open Liberty to provide new gRPC services or to consume external gRPC services. To enable support for gRPC on Open Liberty add the feature:grpc[display=gRPC] or feature:grpcClient[display=gRPC Client] feature to your `server.xml` file.

The gRPC feature enables web applications to define and provide gRPC services. It works by scanning web applications for gRPC service implementations, through implementors of the link:https://grpc.github.io/grpc-java/javadoc/io/grpcBindableService.html[io.grpc.BindableService] API. The web app must include the protocol buffer compiler-generated code for the services it intends to provide, and additionally the service class must provide a no-argument constructor. The web app does not need to include any core gRPC libraries; those are provided by the Liberty runtime. Any configurations that specified in the config:grpc[] element in your `server.xml` file or on the services themselves by the `@GrpcService` annotation are applied to the service when it is started. After a gRPC service is scanned and started, it becomes accessible to remote gRPC clients on the configured HTTP ports.

If you configure gRPC in your `server.xml` file, you must specify requires the `target` attribute to configure a target filter  so the runtime can map the configuration to the applicable gRPC service. Similarly, any `serverInterceptor` classes that are specified in the `serverInterceptors` class must be configured and packaged such that any targeted gRPC services can load the configured ServerInterceptor class

=== Application requirements

=== Application security with gRPC

=== Try it out
