// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:  A health check is a special REST API implementation that you can use to  validate the status of a microservice and its dependencies. MicroProfile Health enables microservices in an application to self-check their health and then publishes the overall health status to a defined endpoint.
:seo-title: Enabling health checking of microservices
:seo-description:  A health check is a special REST API implementation that you can use to  validate the status of a microservice and its dependencies. MicroProfile Health enables microservices in an application to self-check their health and then publishes the overall health status to a defined endpoint.
:page-layout: general-reference
:page-type: general
= Health checks for microservices

A health check is a special REST API implementation that you can use to validate the status of a microservice and its dependencies. MicroProfile Health enables microservices in an application to self-check their health and then publishes the overall health status to a defined endpoint.

A health check can assess anything that a microservice needs, including dependencies, system properties, database connections, endpoint connections, and resource availability.
Services report as their availability by implementing the API provided by https://github.com/eclipse/microprofile-health[MicroProfile Health]. When a microservice is available, it reports an `UP` status. If a microservice is unavailable, it reports a `DOWN` status. A service orchestrator can then use these status reports to decide how to manage and scale the microservices within an application. Health checks can also interact with https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/[Kubernetes liveness and readiness probes].

For example, in a microservices-based banking application, you might implement health checks on the login microservice, the balance transfer microservice, and the bill pay microservice. If a health check on the balance transfer microservice detects a bug or deadlock, it returns a `DOWN` status. In this case, if the `/health/live` endpoint is configured in a Kubernetes liveness probe, the probe restarts the microservice automatically. Restarting the microservice saves the user from encountering downtime or an error and preserves the functions of the other microservices in the application.

== MicroProfile Health endpoints and annotations

MicroProfile Health provides the following three endpoints:

- `/health/ready`: returns the readiness of a microservice, or whether it is ready to process requests. This endpoint corresponds to the Kubernetes readiness probe.
- `/health/live`: returns the liveness of a microservice, or whether it encountered a bug or deadlock. If this check fails, the microservice is not running and can be stopped. This endpoint corresponds to the Kubernetes liveness probe, which automatically restarts the pod if the check fails.
- `/health`: aggregates the responses from the `/health/live` and `/health/ready` endpoints. This endpoint corresponds to the deprecated `@Health` annotation and is only available to provide compatibility with MicroProfile 1.0. If you are using MicroProfile 2.0 or higher, use the `/health/ready` or `/health/live` endpoints instead.

To implement readiness or liveness health checks, add either the `@Liveness` or `@Readiness` annotation to your code. These annotations link the provided endpoints to Kubernetes liveness and readiness probes.

The following example demonstrates the `@Liveness` annotation, which checks the heap memory usage. If memory consumption is less than 90%, it returns an `UP` status. If memory usage exceeds 90%, it returns a `DOWN` status:

[source,java]
----
@Liveness
@ApplicationScoped
public class MemoryCheck implements HealthCheck {
 @Override
 public HealthCheckResponse call() {
        // status is up if used memory is < 90% of max
        MemoryMXBean memoryBean = ManagementFactory.getMemoryMXBean();
        long memUsed = memoryBean.getHeapMemoryUsage().getUsed();
        long memMax = memoryBean.getHeapMemoryUsage().getMax();

        HealthCheckResponse response = HealthCheckResponse.named("heap-memory")
                .withData("used", memUsed)
                .withData("max", memMax)
                .state(memUsed < memMax * 0.9)
                .build();
        return response;
    }
}
----

The following example shows the JSON response from the `/health/live` endpoint if heap memory usage is less than 90%. The first status indicates the overall status of all health checks that are returned from the endpoint. The second status indicates the status of the particular check that is specified by the preceding `name` value, which in this example is `heap-memory`. In order for the overall status to be `UP`, all checks that are run on the endpoint must pass:

[source,java]
----
{
  "status": "UP",
  "checks": [
    {
      "name": "heap-memory",
      "status": "UP",
      "data": {
        "used": "1475462",
        "max": ”51681681"
      }
    }
  ]
}
----

The next example shows the `@Readiness` annotation, which checks for an available database connection. If the connection is successful, it returns an `UP` status. If the connection is unavailable, it returns a `DOWN` status:

[source,java]
----
@Readiness
@ApplicationScoped
public class DatabaseReadyCheck implements HealthCheck {

    @Override
    public HealthCheckResponse call() {

        if (isDBConnected()) {
           return HealthCheckResponse.up(“databaseReady”);
        }
        else {
           return HealthCheckResponse.down(“databaseReady”);
        }
    }
}
----

The following example shows the JSON response from the `/health/ready` endpoint if the database connection is unavailable. The first status indicates the overall status of all health checks returned from the endpoint. The second status indicates the status of the particular check that is specified by the preceding `name` value, which in this example is `databaseReady`. If any check that runs on the endpoint fails, the overall status is `DOWN`.

[source,java]
----
{
  "status": ”DOWN",
  "checks": [
    {
      "name": ”databaseReady",
      "status": ”DOWN",
    }
  ]
}
----



== See also:

- Guide: link:/guides/microprofile-health.html[Adding health reports to microservices]
- Guide: link:/guides/kubernetes-microprofile-health.html[Checking the health of microservices on Kubernetes].
- xref:reference:feature/mpHealth-2.2.adoc[MicroProfile Health feature]
- https://github.com/eclipse/microprofile-health[MicroProfile Health on GitHub]
