// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:  A health check is a special REST API implementation that you can use to  validate the status of a microservice and its dependencies. MicroProfile Health enables microservices in an application to self-check their health and then publishes the overall health status to a defined endpoint.
:seo-title: Enabling health checking of microservices
:seo-description:  A health check is a special REST API implementation that you can use to  validate the status of a microservice and its dependencies. MicroProfile Health enables microservices in an application to self-check their health and then publishes the overall health status to a defined endpoint.
:page-layout: general-reference
:page-type: general
= Health checks for microservices

A health check is a special REST API implementation that you can use to validate the status of a microservice and its dependencies. MicroProfile Health enables microservices in an application to self-check their health and then publishes the overall health status to a defined endpoint.

A health check can assess anything that a microservice needs, including dependencies, system properties, database connections, endpoint connections, and resource availability.
A microservice is considered available if all the configured health checks are successful. If one or more health checks fail, a microservice is considered unavailable.
Services can report their availability to a defined endpoint by implementing the API that is provided by https://github.com/eclipse/microprofile-health[MicroProfile Health]. When a microservice is available, it reports an `UP` status. If a microservice is unavailable, it reports a `DOWN` status. A service orchestrator can then use these status reports to decide how to manage and scale the microservices within an application. Health checks can also interact with https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/[Kubernetes liveness and readiness probes].

For example, in a microservices-based banking application, you might implement health checks on the login microservice, the balance transfer microservice, and the bill pay microservice. If a health check on the balance transfer microservice detects a bug or deadlock, it returns a `DOWN` status. In this case, if the `/health/live` endpoint is configured in a Kubernetes liveness probe, the probe restarts the microservice automatically. Restarting the microservice saves the user from encountering downtime or an error and preserves the functions of the other microservices in the application.

You can use MicroProfile Health with Open Liberty by enabling the feature:mpHealth[display=MicroProfile Health] feature in your `server.xml` file.

== MicroProfile Health endpoints and annotations

MicroProfile Health provides the following three endpoints:

- `/health/ready` +
This endpoint returns the readiness of a microservice, or whether it is ready to process requests. This endpoint corresponds to the Kubernetes readiness probe.
- `/health/live` +
This endpoint returns the liveness of a microservice, or whether it encountered a bug or deadlock. If this check fails, the microservice is not running and can be stopped. This endpoint corresponds to the Kubernetes liveness probe, which automatically restarts the pod if the check fails.
- `/health` +
This endpoint aggregates the responses from the `/health/live` and `/health/ready` endpoints. This endpoint corresponds to the deprecated `@Health` annotation and is only available to provide compatibility with MicroProfile 1.0. If you are using MicroProfile 2.0 or higher, use the `/health/ready` or `/health/live` endpoints instead. The `@Health` annotation is not available in MicroProfile 4.0 or later or MicroProfile Health 3.0 or later.

To implement readiness or liveness health checks, create a class in your application that implements xref:reference:javadoc/microprofile-3.3-javadoc.adoc#class=org/eclipse/microprofile/health/HealthCheck.html&package=allclasses-frame.html[the HealthCheck interface] and add either the `@Liveness` or `@Readiness` annotation to it. These annotations specify the conditions that determine whether the health check passes or fails. 
You can view the results of the health checks by navigating to one of the endpoint URLs, for example `http://localhost:9443/health/live` or `http://localhost:9443/health/ready`, where `9443` is the port number for your application. For more information, see link:/guides/microprofile-health.html[Adding health reports to microservices].

The following example demonstrates the `@Liveness` annotation in a class that implements the `HealthCheck` interface. In this case, the @Liveness annotation checks the heap memory usage. If heap memory usage is less than 90%, it returns an `UP` status. If memory usage exceeds 90%, it returns a `DOWN` status:

[source,java]
----
@Liveness
@ApplicationScoped
public class MemoryCheck implements HealthCheck {
 @Override
 public HealthCheckResponse call() {
        MemoryMXBean memoryBean = ManagementFactory.getMemoryMXBean();
        long memUsed = memoryBean.getHeapMemoryUsage().getUsed();
        long memMax = memoryBean.getHeapMemoryUsage().getMax();

        HealthCheckResponse response = HealthCheckResponse.named("heap-memory")
                .withData("used", memUsed)
                .withData("max", memMax)
                .status(memUsed < memMax * 0.9)
                .build();
        return response;
    }
}
----
For MicroProfile Health versions 2.x and earlier, the `.status` response is replaced by the `.state` response in the `HealthCheckResponse` class.

The following example shows the JSON response from the `/health/live` endpoint if heap memory usage is less than 90%. The first status indicates the overall status of all health checks that are returned from the endpoint. An `UP` status indicates that all the configured checks passed and that the service is available. A `DOWN` status indicates that one or more checks failed and the service is unavailable. The second status indicates the status of the particular check that is specified by the preceding `name` value, which in this example is `heap-memory`. Because the liveness check passed and it is the only check that is configured, the overall status is `UP`:

[source,java]
----
{
  "status": "UP",
  "checks": [
    {
      "name": "heap-memory",
      "status": "UP",
      "data": {
        "used": "1475462",
        "max": ”51681681"
      }
    }
  ]
}
----

The next example shows the `@Readiness` annotation on a class that implements the `HealthCheck` interface. In this case, the readiness annotation checks for an available database connection. If the connection is successful, it returns an `UP` status. If the connection is unavailable, it returns a `DOWN` status:

[source,java]
----
@Readiness
@ApplicationScoped
public class DatabaseReadyCheck implements HealthCheck {

    @Override
    public HealthCheckResponse call() {

        if (isDBConnected()) {
           return HealthCheckResponse.up(“databaseReady”);
        }
        else {
           return HealthCheckResponse.down(“databaseReady”);
        }
    }
}
----

The following example shows the JSON response from the `/health/ready` endpoint if the database connection is unavailable. The first status indicates the overall status of all health checks returned from the endpoint. The second status indicates the status of the particular check that is specified by the preceding `name` value, which in this example is `databaseReady`. In this example, the readiness check failed and returned a `DOWN` status so the overall status is also `DOWN`:

[source,java]
----
{
  "status": ”DOWN",
  "checks": [
    {
      "name": ”databaseReady",
      "status": ”DOWN",
    }
  ]
}
----

In MicroProfile Health versions 2.0 and later, the overall default readiness status is `DOWN`, with an empty response, until all the deployed applications in Open Liberty are started. In MicroProfile Health versions 3.0 and later, the `mp.health.default.readiness.empty.response=UP` xref:external-configuration.adoc[MicroProfile Config] property is available. You can specify this property to change the overall default readiness status to `UP` while deployed applications are starting up.

== See also:

- Guide: link:/guides/microprofile-health.html[Adding health reports to microservices]
- Guide: link:/guides/kubernetes-microprofile-health.html[Checking the health of microservices on Kubernetes].
- feature:mpHealth[display=MicroProfile Health] feature
- https://github.com/eclipse/microprofile-health[MicroProfile Health on GitHub]
