// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//    https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: OThe following sections describe the current limitations and known issues with using Open Liberty InstantOn.
:seo-title: Open Liberty InstantOn
:seo-description: The following sections describe the current limitations and known issues with using Open Liberty InstantOn.
:page-layout: general-reference
:page-type: general
= InstantOn limitations and known issues

The following sections describe the current limitations and known issues with using Open Liberty InstantOn.

== Jakarta Transactions configuration limitations
Open Liberty Transaction Manager support for InstantOn has limitations with respect to updating configurations when restoring the application process. The configuration attributes for the config:transaction[display=Transaction Manager] must remain constant between the InstantOn checkpoint and restore. This is true only for the configuration attributes specified directly with the `<transaction/>` server configuration element. For example, `recoveryGroup` and `recoverIdentity`. The values for these configuration attributes must not change between checkpoint and restore.

This implies that xref:transaction-service#cloud[Transaction recovery in a cloud environment] will not work as designed because the `recoverIdentity` cannot be parameterized with something like the following which gives a unique `recoverIdentity` for each instance of the application:

[source,xml]
----
<transaction
  ...
  recoveryGroup="peer-group-name"
  recoveryIdentity="${HOSTNAME}${wlp.server.name}"
  ...
/>
----

== Jakarta Transaction before checkpoint
Open Liberty InstantOn does not allow transactions to begin before a checkpoint is performed for the application process. This is possible if the application has <<#early-startup-code,early startup code>> which attempts to start a transaction. Consider the following `Servlet`:

[source,java]
----
@WebServlet(urlPatterns = { "/StartupServlet" }, loadOnStartup = 1)
public class StartupServlet extends HttpServlet {
    @Override
    public void init() {
        UserTransaction ut = UserTransactionFactory.getUserTransaction();
        try {
            ut.begin();
            ...
            ut.commit();
        } catch (Exception e) {
            // something went wrong
        }
    }

}
----

This `Servlet` example uses `loadOnStartup = 1` which will cause the servlet to be initialized before the checkpoint when using the  <<#after-app-start,afterAppStart>> option. The runtime will detect this and log the following message:

[source,text]
----
[WARNING ] WTRN0155W: An application began or required a transaction during the server checkpoint request. The following stack trace for this thread was captured when the transaction was created: 
----

This warning will be followed by a stacktrace which helps identify the application code that is attempting to begin a transaction. The server will then fail to successfuly checkpoint and the following error will be logged:

[source,text]
----
WTRN0154E: The server checkpoint request failed because the transaction service is unable to begin a transaction. 
----

This can be avoided by using the <<#before-app-start,beforeAppStart>> option or by modifying the component not to be <<#early-startup-code, early startup code>>. In this example that would be done by removing the attribute `loadOnStartup = 1`.

== Accessing MicroProfile Configuration too early
If an application has <<#early-startup-code,early startup code>> then it is possible the application may get injected with a configuration value from MicroProfile configuration before a checkpoint is performed for the application process when using the <<#after-app-start,afterAppStart>> option. If such a configuration value changes at the time the application image container is run then it is possible that the application will be using the old, stale value that was set when the application process checkpoint was performed.

The Open Liberty runtime detects this situation and will log a warning message when the application container image is run indicating that a configuration value has changed. The following example uses a configuration key `example_config` with a default value set to `"theDefault"`. When performing the checkpoint, the environment configuration source is not available to populate MicroProfile configuration values. If this `@Inject` of the configuration is contained in a CDI bean that is created and used before the checkpoint is performed then the value of `"theDefault"` will get injected.

[source,java]
----
    @Inject
    @ConfigProperty(name = "example_config", defaultValue = "theDefault")
    String exampleConfig;
----

When the InstantOn application container image is run, the environment variable `EXAMPLE_CONFIG` may be used to provide an updated value. The runtime will detect this and log the following message:

[source,text]
----
[WARNING ] CWWKC0651W: The MicroProfile configuration value for the key example_config has changed since the checkpoint action completed on the server. If the value of the key changes after the checkpoint action, the application might not use the updated value.

----

In this situation the checkpoint option <<#before-app-start,beforeAppStart>> can be used. Another option is to use a link:https://download.eclipse.org/microprofile/microprofile-config-3.0/microprofile-config-spec-3.0.html#_dynamic_configsource[Dynamic ConfigSource]. The above example can be modified to use a dynamic ConfigSource by using the `Provider<String>` type for the `exampleConfig` variable:

[source,java]
----
    @Inject
    @ConfigProperty(name = "example_config", defaultValue = "theDefault")
    Provider<String> exampleConfig;
----

Each call to the `get()` method of the `Provider<String>` will return the current value of the `ConfigProperty`.  This allows the application to access the updated configuration value when the application process is restored during the InstantOn application container run.

== Injection of a DataSource too early
If an application has <<#early-startup-code,early startup code>> then it is possible the application may get injected with `DataSource` before a checkpoint is performed for the application process when using the <<#after-app-start,afterAppStart>> option. It is likely, in a cloud environment, that the configuration of the `DataSource` will need to change at the time the application image container is run. Consider the following `Servlet` example:

[source,java]
----
@WebServlet(urlPatterns = "/ExampleServlet", loadOnStartup = 1)
public class ExampleServlet extends HttpServlet {
    @Resource(shareable = false)
    private DataSource exampleDataSource;
    ...
}
----

This `Servlet` example uses `loadOnStartup = 1` which will cause the servlet to be initialized before the checkpoint when using the  <<#after-app-start,afterAppStart>> option. The deployment information related to the `DataSource` likely will need to be configured when deploying the application to the cloud. Consider the following Open Liberty `server.xml` configuration.

[source,xml]
----
  <!-- these are place holders so we don't have to have the env set before checkpoint -->
  <variable name="DB2_DBNAME" defaultValue="placeholder" />
  <variable name="DB2_HOSTNAME" defaultValue="placeholder" />
  <variable name="DB2_PASS" defaultValue="placeholder" />
  <variable name="DB2_PORT" defaultValue="45000" />
  <variable name="DB2_PORT_SECURE" defaultValue="45001" />
  <variable name="DB2_USER" defaultValue="placeholder" />


  <dataSource id="DefaultDataSource">
    <jdbcDriver libraryRef="DB2Lib"/>
    <properties.db2.jcc
      databaseName="${DB2_DBNAME}" serverName="${DB2_HOSTNAME}" portNumber="${DB2_PORT}"
      downgradeHoldCursorsUnderXa="true"/>
    <containerAuthData user="${DB2_USER}" password="${DB2_PASS}"/>
    <recoveryAuthData user="${DB2_USER}" password="${DB2_PASS}"/>
  </dataSource>
----

This configuration uses placeholder values for things like the database name, hostname, ports, user and password. This allow the values to be updated with environment variable values or other configuration mechanisms as decribed in link:/guides/kubernetes-microprofile-config.html[Configuring microservices running in Kubernetes]. These are configurations that should not be hard coded into an application image and must be able to be updated when deploying the application to the cloud.

If an application is injected with a `DataSource` before the checkpoint and the configuration of the `DataSource` changes then the application will be restarted when the InstantOn application container image is run with the updated configuration. This can be avoided by using the <<#before-app-start,beforeAppStart>> option or by modifying the component not to be <<#early-startup-code, early startup code>>. In this example that would be done by removing the attribute `loadOnStartup = 1`.

== Use of product extensions and user features
Current InstantOn only supports a subset of Open Liberty features for InstantOn as described in <<#supported-features,Open Liberty InstantOn supported features>>. Any public features that are enabled outside of the supported set of features for InstantOn will cause checkpoint to fail with an error message like the following:

[source,sh]
----
CWWKC0456E: A checkpoint cannot be taken because the following features configured in the server.xml file are not supported for checkpoint: [usr:exampleFeature-1.0]
----

This error will occur for any configured features that are not supported for InstantOn. This includes Liberty product extension and Liberty user features.

== Update configuration with bootstrap.properties file
When an InstantOn application container image is run the xref:reference:bootstrap-properties.adoc[bootstrap.properties] file is not read. Values that must be able to be configured when running an InstantOn application container image should come from alternative sources such as environment variables or other configuration mechanisms as described link:/guides/kubernetes-microprofile-config.html[Configuring microservices running in Kubernetes]

== Java SecurityManager is not supported
If Open Liberty is configured to run with the `SecurityManager` then InstantOn will detect this during a checkpoint and will fail with the following message:

[source,sh]
----
CWWKE0958E: The server checkpoint request failed because the websphere.java.security property was set in the bootstrap.properties file. This property enables the Java Security Manager and is not valid when a server checkpoint occurs.
----

== Updating JVM options
InstantOn does not currently support changing the xref:reference:config/server-configuration-overview.adoc#jvm-options[jvm.options] when restoring the InstantOn application process. Any JVM options required to be set for the JVM process must be defined during the InstantOn container image build.

The IBM Semeru JVM does have limited support for setting JVM options on restore with the use of the `OPENJ9_RESTORE_JAVA_OPTIONS` environment variable. See the Java link:https://www.eclipse.org/openj9/docs/criusupport/[CRIU Support] documentation for more information.

== SELinux limitations
If link:https://www.redhat.com/en/topics/linux/what-is-selinux[SELinux] mode is configured to be `enforcing` then SELinux may prevent CRIU from successfully performing a checkpoint of the application process when using the <<#checkpoint_script,checkpoint.sh script>> in the image template `Dockerfile` or `Containerfile`. If the SELinux setting `virt_sandbox_use_netlink` is disabled then the required `netlink` Linux system calls will get blocked. This prevents CRIU from performing a successful checkpoint of the application process during the container image build. Open Liberty InstantOn will detect this and log the following:

[source,sh]
----
CWWKE0962E: The server checkpoint request failed. The following output is from the CRIU /logs/checkpoint/checkpoint.log file that contains details on why the checkpoint failed.
Warn  (criu/kerndat.c:1103): $XDG_RUNTIME_DIR not set. Cannot find location for kerndat file
Error (criu/libnetlink.c:84): Can't send request message: Permission denied
..
Error (criu/cr-dump.c:2099): Dumping FAILED.
CWWKE0963E: The server checkpoint request failed because netlink system calls were unsuccessful. If SELinux is enabled in enforcing mode, netlink system calls might be blocked by the SELinux "virt_sandbox_use_netlink" policy setting. Either disable SELinux or enable the netlink system calls with the "setsebool virt_sandbox_use_netlink 1" command.
----

To work around this limitation the `virt_sandbox_use_netlink` SELinux setting can be enabled with the command `setsebool virt_sandbox_use_netlink 1` or SELinux `enforcing` mode can be disabled altogether. Another option to work around this issue is to use the <<#three_step_process,three step process>>. The three step process requires the use of a `--privileged` container which grants the running container performing the application process checkpoint access to the `netlink` system calls.

== Yama Linux Security Module limitations
If link:https://www.kernel.org/doc/Documentation/security/Yama.txt[Yama] is configured with one of the following modes then CRIU will not be able to checkpoint or restore the application process in running containers:

- 2 - admin-only attach
- 3 - no attach 

When this happens the `/logs/checkpoint/restore.log` will contain the following error:

[source,sh]
----
Error (criu/arch/x86/kerndat.c:178): 32: ptrace(PTRACE_TRACEME) failed: Operation not permitted
----

For CRIU checkpoint and restore to work Yama must be configured with one of the following modes:

- 0 - classic ptrace permissions
- 1 - restricted ptrace

The supported public cloud Kubernetes services have the default for Yama set to mode `1` which allows CRIU to checkpoint and restore by default:

- link:https://aws.amazon.com/eks/[Amazon Elastic Kubernetes Service (EKS)]
- link:https://azure.microsoft.com/en-us/products/kubernetes-service[Azure Kubernetes Service (AKS)]

== Access to Linux system calls
As described in <<#required-system-calls,Required Linux system calls>> there are a number of Linux system calls that are required by CRIU in order to restore the application process. This may require additional configuration to grant the required system calls to the running container when using InstantOn. The supported public cloud Kubernetes Service environments currently allow the required system calls used by CRIU by default. No additional configuration should be required when using:

- link:https://aws.amazon.com/eks/[Amazon Elastic Kubernetes Service (EKS)]
- link:https://azure.microsoft.com/en-us/products/kubernetes-service[Azure Kubernetes Service (AKS)]

For example, if access is not granted to the system call `clone3` then the `/logs/checkpoint/restore.log` will contain the following error:

[source,sh]
----
Error (criu/kerndat.c:1377): Unexpected error from clone3: Operation not permitted
----

== Running without the necessary Linux capabilities
Errors will occur during checkpoint and restore if the required <<#linux-capabilities, Linux capabilities>> are not granted. If the required capabilities are not granted for checkpoint then the following error will occur during the InstantOn container image build:

[source,sh]
----
Can't exec criu swrk: Operation not permitted
Can't read request: Connection reset by peer
Can't receive response: Invalid argument
[ERROR   ] CWWKC0453E: The server checkpoint request failed with the following message: Could not dump the JVM processes, err=-70
----

The "Operation not permitted" message is an indication that the required Linux capabilities have not been granted. If using the  If using the <<#checkpoint_script,checkpoint.sh>> script then the following error will be observed during the `RUN checkpoint.sh` instruction:

[source,sh]
----
Error: building at STEP "RUN checkpoint.sh afterAppStart": while running runtime: exit status 74
----

To avoid these error, grant the container image build the Linux capabilities `CHECKPOINT_RESTORE`, `SYS_PTRACE` and `SETPCAP`. If the <<#three_step_process,three step process>> is used to build the container image then make sure the container running the checkpoint step is a `--privileged` container.

If the required capabilities are not granted for restore then the following error will occur when trying to run the InstantOn application container image:

[source,sh]
----
/opt/ol/wlp/bin/server: line 1430: /opt/criu/criu: Operation not permitted
CWWKE0961I: Restoring the checkpoint server process failed. Check the /logs/checkpoint/restore.log log to determine why the checkpoint process was not restored. Launching the server without using the checkpoint image.
----

The "Operation not permitted" message is an indication that the required Linux capabilities have not been granted for restore.

== Supported processors
At this time, the only supported processor is X86-64/AMD64. Additional processors are expected to be supported in later releases of Open Liberty InstantOn.

