// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
// This doc is hosted in the Red Hat Runtimes documentation. Any changes made to this doc also need to be made to the version that's located in the PurpleLiberty GitHub repo (https://github.com/PurpleLiberty/docs).
//
:page-layout: general-reference
:page-type: general
:page-description: MicroShed testing helps you to write integration tests by using Testcontainers framework for Java microservice applications. With MicroShed testing you can test your Open Liberty application from outside the container so you are testing the exact same image that runs in production.
:page-categories: MicroShed testing
:seo-title: Testing in a container with MicroShed testing
:seo-description:  MicroShed testing helps you to write integration tests by using Testcontainers for Java microservice applications. With MicroShed testing, you can test your Open Liberty application from outside the container so you are testing the exact same image that runs in production.
= True-to-production integration testing

TestContainers is a Java library that facilitates the creation of integration tests that closely resemble production environments. It enables developers to test their applications within the same container used in production, thus reducing discrepancies between development and deployment settings.

By using the https://www.testcontainers.org/[Testcontainers] framework, developers can analyze their applications externally, without accessing internal application details. This approach ensures that integration tests accurately evaluate various test classes and components. Although integration tests require more setup and configuration time compared to unit tests, they provide a comprehensive assessment of the application’s behavior in a realistic environment.

Unit tests focus on testing individual modules or components of an application and are quicker to run. Due to shorter development cycles and time constraints, developers often prioritize running unit tests. However, with TestContainers, developers can efficiently write and run integration tests that closely resemble real-world production scenarios.

TestContainers enables developers to create integration tests that closely resemble production environments. Integrating with the TestContainers framework streamlines the process of writing and running true-to-production integration tests, enabling a more efficient workflow.

----
This will be removed

MicroShed Testing is a Java library that helps you write true-to-production integration tests for your application in an environment similar to production.
To minimize the parity issues between development and production, you can test your application in the same container that you use in production.

https://microshed.org/microshed-testing/[MicroShed Testing] uses the https://www.testcontainers.org/[Testcontainers] framework to analyze your application from outside the container without accessing the application internals.
You can use MicroShed Testing to develop integration tests for your Open Liberty application.

You need to make sure that your application works accurately in production, similar to the development environment.
Integration tests assess multiple test classes and components, but integration tests take longer to set up and configure than unit tests.
Alternatively, unit tests are shorter and involve testing individual modules of an application.
With shorter development cycles and limited time available, developers often run unit tests.
MicroShed Testing helps you write and run true-to-production integration tests for your applications, and streamlines your integration tests with the Testcontainers framework for an efficient workflow.
----

== Development and production parity

https://12factor.net/dev-prod-parity[Development and production parity] is one of the factors in the https://12factor.net/[twelve-factor app], which is a methodology to build modern applications.
The idea behind development and production parity is to keep the development, staging, and production environments similar, regarding time, personnel, and tools.
To simplify the development process, developers often use tools in development that are different from production.
For example, you might use a local Maven build to build a project for your application in development, but the application might be deployed to a container in production.
Differences between the environments can cause a test to fail in production, though the test passes in the development environment.
TestContainers helps achieve development and production parity by testing the application in an environment similar to production.

----
This will be replaced

MicroShed Testing helps achieve development and production parity by testing the application in an environment similar to production.
----

== Writing integration tests with the Testcontainers framework

You can write integration tests by using the Testcontainers framework and deploy your applications in different environments by using containers. Testcontainers provides a powerful way to create and manage containers within a test environment. 
Testcontainers is a Java library for MicroProfile and https://jakarta.ee/[Jakarta EE] developers to test their applications in an environment similar to production.
Testcontainers enables developers to achieve development and production parity by testing their applications in an environment similar to production.

----
This will be removed
== Writing integration tests with the Microshed Testing library

You can deploy your applications in different environments with containers.
With the Testcontainers framework, you can use containers in a test environment.
Microshed Testing is a Java library for MicroProfile and https://jakarta.ee/[Jakarta EE] developers to test their applications in an environment similar to production.
Microshed Testing implements the Testcontainers framework to support development and production parity in testing.
----

With MicroShed Testing, you can write an integration test that looks like the following example:


```java

@MicroShedTest
public class BasicJAXRSServiceTest {

    @Container
    public static ApplicationContainer app = new ApplicationContainer()
                    .withAppContextRoot("/myservice");

    @RESTClient
    public static PersonService personSvc;

    @Test
    public void testGetPerson() {
        Long bobId = personSvc.createPerson("Bob", 24);
        Person bob = personSvc.getPerson(bobId);

        assertEquals("Bob", bob.name);
        assertEquals(24, bob.age);
        assertNotNull(bob.id);
    }

    @Test
    public void testGetUnknownPerson() {
        assertThrows(NotFoundException.class, () -> personSvc.getPerson(-1L));
    }
}
```

The `@MicroShedTest` annotation searches for a `Dockerfile` or `Containerfile` file in the repository, starts the application in a container, and waits for the application to be ready before the test starts.
The `@Container` annotation injects a REST Client proxy of the PersonService class, which helps you send HTTP requests on the running application container.
The `@RESTClient` annotation sends an HTTP POST request to the running container, which triggers the PersonService#createPerson endpoint and returns the generated ID.
By using the generated ID, you can send an HTTP GET request to read the record that was created.
The JSON response automatically converts to a Person object by using a JSON-B token.
The `@Test` annotation sends an HTTP GET request to find a Person object with the `-1` ID, which does not exist.
The annotation asserts that the application container returns an HTTP 404 exception.

== See also

Guide: https://openliberty.io/guides/microshed-testing.html[Testing a MicroProfile or Jakarta EE application]
