// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Jakarta EE is an open source Java platform for building enterprise applications. It includes and extends the Java Platform, Standard Edition (Java SE), by providing specifications for common standard services such as naming, transaction management, concurrency, security, and database access.
:seo-title: Jakarta EE
:page-layout: general-reference
:page-type: general
= Jakarta EE

Jakarta EE is an open source Java platform for building enterprise applications. It includes and extends the Java Platform, Standard Edition (Java SE), by providing specifications for common services such as transaction management, security, and database access.

https://jakarta.ee[Jakarta EE] specifies APIs and a runtime environment to develop and run secure, scalable networked applications. It also defines a container model to manage application components. Jakarta EE application servers such as Open Liberty host these containers and provide standardized system services that any application that is developed for Jakarta EE specifications can use. These open source specifications make applications more portable and resilient and help developers focus on writing applications rather than managing infrastructure.

Jakarta EE is widely used for enterprise applications in banking, e-commerce, travel, and more. The system services that it enables are especially valuable to cloud-native and microservice-based applications. These services abstract away some of the complexity of handling requests from web-based clients, communicating with databases, and implementing security measures. Jakarta EE provides APIs to facilitate these functions and many others in a standardized way so that enterprise Java applications can carry out their business logic, regardless of the environment in which they run.

== Java platforms

Jakarta EE was formerly known as Java EE, one of four Java platforms owned by the Oracle corporation that are designed to standardize and simplify Java application development. Oracle moved Java EE to the open source Eclipse foundation in 2017, at which time its name was changed to Jakarta EE. The other three platforms are Java SE, which provides the core functions of the Java language, Java ME, whcih provides resources for mobile and small device applications, and JavaFX, which provides graphics and media packages for rich client applications. All Java platforms provide an API to standardize application development and a Java Virtual Machine (JVM), which is a program that runs Java applications.

Jakarta EE consists of a superset of Java SE and a collection of APIs that are specifically designed for networked enterprise application development.





== Java EE and Jakarta EE

== Jakarta EE and Open Liberty
