// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
// https://creativecommons.org/licenses/by-nd/4.0/
//
//
// Contributors:
// IBM Corporation
//
//
//
//
:page-description: If you are updating your application from using Jakarta EE 9.1 features to using Jakarta EE 10.1 features, certain changes in API behavior might require you to update your application code.
:projectName: Open Liberty
:page-layout: general-reference
:page-type: general
= Differences between Jakarta EE 10.0 and 9.1

If you are updating your application from using Jakarta EE 9.1 features to using Jakarta EE 10.0 features, changes in API behavior might require you to update your application code. These changes apply to the Jakarta Contexts and Dependency Injection (CDI) and Jakarta RESTful Web Services APIs and the Open Liberty features that support them.

[#cdi]
== Differences between Jakarta Contexts and Dependency Injection 4.0 and 3.0

Although Open Liberty xref:zero-migration-architecture.adoc[zero migration] architecture simplifies migrating your server configuration between versions, the following changes might require updates to relevant application code. CDI 4.0 introduces Build Compatible Extensions, observable container state events, and changes how empty and unversioned `beans.xml` files are handled. Several previously deprecated APIs are removed in this release.

=== Build Compatible Extensions

CDI provides Portable Extensions to customize the CDI application initialization lifecycle. In CDI 4.0, Build Compatible Extensions make implementing extensions amenable to build-time processing. To implement a build compatible extension, provide an implementation of the `BuildCompatibleExtension` interface that is declared in the  `META-INF/services` directory. The implementation can provide methods that are annotated with one of the following extension annotations, each of which corresponds to an extension execution phase.

* `@Discovery`
* `@Enhancement`
* `@Registration`
* `@Synthesis`
* `@Validation`

For example, as part of the `Enhancement` phase, the implementation in the following example adds a `MyQualifier` annotation to the `MyService` type.

[source,java]
----
public class MyExtension implements BuildCompatibleExtension {
    @Enhancement(type=MyService.class)
    public void addMyQualifier(ClassConfig clazz) {
        clazz.addAnnotation(MyQualifier.class)
    }
}
----

=== Startup and Shutdown events

Two new observable container state events are available in CDI 4.0: `Startup` and `Shutdown`. Applications can listen for these events to be notified when the CDI container is starting up and being shut down. The following example listens for `Startup` and `Shutdown` events and prints a notification for each to the console when it receives the event.

[source,java]
----
@ApplicationScoped
public class MyObserver {
    public void observeStartup(@Observes Startup startupEvent) { {
        System.out.println("CDI Container is starting");
    }

    public void observeShutdown(@Observes Shutdown shutdownEvent) { {
        System.out.println("CDI Container is stopping");
    }
}
----

You can control the order among multiple observable container state methods by using the `@Priority` annotation.

=== Empty beans.xml files

In previous versions of CDI, an archive that contained an empty `beans.xml` file was treated as an explicit bean archive, the equivalent of setting the `bean-discovery-mode="all"` attribute in the file. In CDI 4.0, an empty `beans.xml` file causes an archive to be treated as an implicit bean archive, the equivalent of setting the `bean-discovery-mode="annotated"` attribute in the file. If necessary, you can <<cdiConfiguration, set the emptyBeansXmlCDI3Compatibility attribute>> to enable compatibility with previous versions. If you set this attribute to `true` in CDI 4.0, any archives that contain an empty `beans.xml` file are treated as explicit beans archives.

=== Unversioned beans.xml files

In previous versions of CDI, a nonempty `beans.xml` file that did not include a `version` attribute defaulted to the `bean-discovery-mode="all"` attribute. In CDI 4.0, it defaults to the `bean-discovery-mode="annotated"` attribute. Therefore, by default, only objects with CDI bean-defining annotations are discovered as CDI beans. However, always properly specify a version for all `beans.xml` files, as shown in the following example.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://jakarta.ee/xml/ns/jakartaee"
    xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/beans_4_0.xsd"
    version="4.0"
    bean-discovery-mode="annotated">
</beans>
----

=== Programmatic lookup of beans and instances

In CDI 4.0, a new Handle API is available to simplify programmatic inspection of bean metadata. This API avoids the need to create instances before they are required. You can obtain a `Handle`  instance by using the Instance API, as shown in the following example.

[source,java]
----
public interface Handle<T> extends AutoCloseable {
        T get();
        Bean<T> getBean();
        void destroy();
        void close();
}
----

=== Removed APIs

The following previously deprecated CDI APIs are removed in CDI 4.0.

* `@New` qualifier, which replaced by `@Dependent` beans.
* `Bean#isNullable()`, not used by the implementation since CDI 1.1.
* `BeanManager#createInjectionTarget(AnnotatedType)`, replaced by `BeanManager#getInjectionTargetFactory(AnnotatedType)`
* `BeforeBeanDiscovery#addAnnotatedType(AnnotatedType)`, replaced by `BeforeBeanDiscovery#addAnnotatedType(AnnotatedType, String)`

[#cdiConfiguration]
=== Server.xml configuration element and attribute updates
In the Liberty feature:cdi-4.0[display=Jakarta Contexts and Dependency Injection 4.0] feature, the config:cdi12[] configuration element is superseded by the config:cdi[] element, which applies to CDI versions 1.2 and later. The following `server.xml` file example shows the element with two attributes that are specified.

[source,xml]
----
<cdi enableImplicitBeanArchives="false" emptyBeansXmlCDI3Compatibility="true"/>
----

The `enableImplicitBeanArchives` attribute is the same as it was in previous versions.
If this attribute is set to `true`, which is the default, then archives with no `beans.xml` file are treated as implicit bean archives and scanned for classes that have bean defining annotations.
If this attribute is set to `false`, then archives that do not contain a `beans.xml` file are not scanned for annotated classes.

The `emptyBeansXmlCDI3Compatibility` attribute applies only to CDI 4.0.
If this attribute is set to `true`, an archive that contains an empty `beans.xml` file is treated as an explicit bean archive, as it was in CDI 3.0 and earlier.
If this attribute set to `false`, which is the default, then an archive that contains an empty `beans.xml` file is treated as an implicit bean archive.

[#restfulws]
== Differences between Jakarta RESTful Web Services 3.1 and 3.0

[#appAuth]
== Differences between Jakarta Authorization 2.1 and 2.0

The feature:appAuthorization-2.1[display=Jakarta Authorization 2.1] feature (`appAuthorization-2.1`) feature introduces the following changes.

=== New methods for the jakarta.security.jacc.PolicyConfigurationFactory abstract class

The `jakarta.security.jacc.PolicyConfigurationFactory` abstract class implements the following two
new methods to  retrieve the Policy Configuration interface (`PolicyConfiguration`).

* `public abstract PolicyConfiguration getPolicyConfiguration();`
* `public abstract PolicyConfiguration getPolicyConfiguration(String contextID);`

The methods are available in addition to the following method that was available in previous versions.

`public abstract PolicyConfiguration getPolicyConfiguration(String contextID, boolean remove);`

=== New methods for the `jakarta.security.jacc.PolicyConfiguration` interface

The `jakarta.security.jacc.PolicyConfiguration` interface defines three new methods to read
permissions.

* `public abstract Map<String, PermissionCollection> getPerRolePermissions();`
* `public abstract PermissionCollection getUncheckedPermissions();`
* `public abstract PermissionCollection getExcludedPermissions();`

For more information, see the https://jakarta.ee/specifications/authorization/2.1/apidocs/jakarta.security.jacc/jakarta/security/jacc/package-summary.html[Jakarta Authorization 2.1 Javadoc].

[#appAuthn]
== Differences between Jakarta Authentication 3.0 and 2.0

The feature:appAuthentication-2.1[display=Jakarta Authentication 3.0] feature (`appAuthentication-3.0`) feature introduces changes to the`jakarta.security.auth.message.config.AuthConfigFactory` abstract class. This class implements two new methods to register and remove a server authentication module. Before this version of the feature, support was available only to register and remove a configuration provider.

* `public abstract String registerServerAuthModule(ServerAuthModule serverAuthModule, Object context);`
* `public abstract void removeServerAuthModule(Ojbect context);`

For more information, see the https://jakarta.ee/specifications/authentication/3.0/apidocs/jakarta.security.auth.message/module-summary.html[Jakarta Aithentication Javadoc].

== See also

* xref:jakarta-ee.adoc[Jakarta EE overview]
