// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Jakarta EE is an open source Java platform for building enterprise applications. It includes and extends the Java Platform, Standard Edition (Java SE), by providing specifications for common standard services such as naming, transaction management, concurrency, security, and database access.
:seo-title: Jakarta EE
:page-layout: general-reference
:page-type: general
= Jakarta EE

Jakarta EE is an open source Java platform for building enterprise applications. It includes and extends the Java Platform, Standard Edition (Java SE), by providing specifications for common services such as transaction management, security, and database access.

https://jakarta.ee[Jakarta EE] specifies APIs and a runtime environment to develop and run secure, scalable networked applications. It also defines a container model to manage application components. Jakarta EE application servers such as Open Liberty host these containers and provide standardized system services that any application that is developed for Jakarta EE specifications can use. These open source specifications make applications more portable and resilient and help developers focus on writing applications rather than managing infrastructure.

Jakarta EE is widely used for enterprise applications in banking, e-commerce, travel, and more. The system services that it enables are especially valuable to cloud-native and microservice-based applications. These services abstract away some of the complexity of handling requests from web-based clients, communicating with databases, and implementing security measures. Jakarta EE provides APIs to facilitate these functions and many others in a standardized way so that enterprise Java applications can carry out their business logic, regardless of the environment in which they run.

== Java platforms

Jakarta EE was formerly known as Java EE, one of four Java platforms owned by the Oracle corporation that are designed to standardize and simplify Java application development. Oracle moved Java EE to the open source Eclipse foundation in 2017, at which time its name was changed to Jakarta EE. The other three platforms are Java SE, which provides the core functions of the Java language, Java ME, which provides resources for mobile and small device applications, and JavaFX, which provides graphics and media packages for rich client applications.

All Java platforms provide an API to standardize application development and a Java Virtual Machine (JVM), which is a program that runs Java applications.
Jakarta EE consists of a superset of Java SE and a collection of APIs that are specifically designed for networked enterprise application development. The Java SE platform that is included with Jakarta EE provides the Java Runtime Environment (JRE), which is used to run Java applications, and the Java Software Development Kit (SDK), which is a collection of tools for developing Java applications. The JRE includes the JVM and the Java Class Library (JCL), which is a set of dynamically loadable libraries that the JVM can call at runtime. These libraries enable Java applications to be operating system independent by supplying many of common functions that are provided by modern operating systems.

The following diagram shows the relationship between these components of the Jakarta EE platform:

* Jakarta EE: A platform for developing and running  multitiered, web-based applications that includes Java SE and a collection of APIs to standardize common services
** Java SE: A platform for developing and running Java applications that includes the Java SDK and JRE
*** Java SDK: A collection of software development tools that includes the JRE, a set of API classes, and a Java compiler
*** JRE: a runtime environment for Java applications that includes the JVM and JCL
*** JVM: a virtual machine that interprets and executes Java application functions
*** JCL: a collection of standard code libraries that provides basic functions, such as container classes and regular expression processing, regardless of the underlying operating system where an application runs.


image::

=== Platform versions
Java SE has evolved through a series of versions as more classes were added to the JCL, new APIs were introduced, and some older functions were deprecated and replaced. Currently, the only versions of Java SE that are maintained with long term support are Java SE 8 and Java SE 11.
Java EE 8 was the last release of the platform by the Oracle corporation before it was moved to the Eclipse foundation, which first released the platform as Jakarta EE 8. Jakarta EE 9 arrived in 2020. The primary change in this release was to replace the `javax.*` namespace with `jakarta.*`. 

== Jakarta EE APIs

== Jakarta EE and Open Liberty
