// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title:
:page-layout: general-reference
:page-type: general
= Jakarta EE

Jakarta EE is an open source Java platform for building enterprise applications. It includes and extends the Java Platform, Standard Edition, (Java SE) by providing specifications for common standard services such as naming, transaction management, concurrency, security, and database access.

https://jakarta.ee[Jakarta EE], formerly known as Java EE, specifies an API and runtime environment to develop and run secure, scalable networked applications. It also defines a container model that manages application components. Jakarta EE application servers such as Open Liberty host these containers and provide standardized system services that any application that is developed for Jakarta EE specifications can use. These open source specifications help developers focus on writing applications rather than managing infrastructure and make applications more portable and resilient.

Jakarta EE is widely used for business applications in banking, e-commerce, travel, and more. The system services that it enables are especially valuable to cloud-native and microservice-based applications. These services abstract away some of the complexity of coordinating, securing, and responding to requests from web based clients. 

== Java SE

== Java EE and Jakarta EE

== Jakarta EE and Open Liberty
