// Copyright (c) 2018,2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
= Java SE support

Open Liberty requires a Java SE runtime.
It can run by using either a JRE (Java Runtime Environment) or a JDK (Java SE Development Kit) distribution.
Open Liberty runs on any of the Java SE versions that are listed in the table below.

Always run Open Liberty on the most recent service release of your chosen Java version.
A new version of Java SE is released every six months.
Unless the prior version is designated as a Long Term Support (LTS) release, it no longer receives service updates for function and security.
Whenever a non-LTS release is replaced by the next version, the Open Liberty project no longer validates the runtime against the older version.

== Choosing a JVM

There are two commonly used Java Virtual Machine (JVM) implementations and one implementation of the class libraries.
The two JVM implementations are: Eclipse OpenJ9 and HotSpot.
These JVM implementations provide similar throughput performance, but make different tradeoffs regarding memory footprint and startup.
As a result Open Liberty recommends using a Java distribution that packages Eclipse OpenJ9 because it uses less memory and starts more quickly while providing the same throughput.
The main Java distribution using Eclipse OpenJ9 is IBM Semeru which uses the OpenJDK class libraries, but uses Eclipse OpenJ9 as the JVM.
IBM Semeru provides uncertified Open Edition releases under a GPLv2 with classpath exception license, and Certified Edition releases under an IBM license.

== Supported Java SE releases

.Supported Java Releases
[%header,cols=5]
|===
|Java version
|LTS Release
|Eclipse OpenJ9 Download
|HotSpot Download
|Migration Advice

|8
|&check;
|https://developer.ibm.com/languages/java/semeru-runtimes/downloads/?version=8[IBM Semeru 8]
|https://adoptium.net/?variant=openjdk8&jvmVariant=hotspot[Eclipse Adoptium 8]
|

|11
|&check;
|https://developer.ibm.com/languages/java/semeru-runtimes/downloads/?version=11[IBM Semeru 11]
|https://adoptium.net/?variant=openjdk11&jvmVariant=hotspot[Eclipse Adoptium 11]
|https://docs.oracle.com/en/java/javase/11/migrate/index.html#JSMIG-GUID-C25E2B1D-6C24-4403-8540-CFEA875B994A[Java SE 11 migration guide]

|17
|&check;
|
|https://adoptium.net/?variant=openjdk17&jvmVariant=hotspot[Eclipse Adoptium 17]
|https://docs.oracle.com/en/java/javase/17/migrate/toc.htm[Java SE 17 migration guide]
|===
