// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: JAX-RS integration with CDI
:seo-description:
:page-layout: general-reference
:page-type: general
= JAX-RS integration with CDI

In Open Liberty, Jakarta RESTful Web Services (JAX-RS 2.0) can integrate with the Contexts and Dependency Injection (CDI) specification. By integrating JAX-RS 2.0 with CDI, you can annotate CDI beans or managed beans as REST endpoints and use CDI injection for web services.

JAX-RS 2.0 in Open Liberty supports CDI-style beans as root resource classes, providers, and application subclasses. Providers and application subclasses must be singletons or use the application scope. The CDI specification makes it easier to integrate various kinds of Jakarta EE various  in a loosely coupled but type-safe way. It provides a common mechanism to inject components such as enterprise beans or managed beans into other components such as JavServer Pages (JSP) files or other enterprise beans.

For CDI, you can use the `@ApplicationScoped` and `@Inject` annotations with application-scoped beans in your application code, as shown in the following example:


[source,java]
----
@ApplicationScoped
@Path("/ApplicationScopedResource")
public class ApplicationScopedResource {

    private @Inject
    SimpleBean injected;

...

}
----

== Restrictions on JAX-RS 2.0 with CDI

JAX-RS 2.0 in Open Liberty is subject to the following restrictions:

- If the xref:reference:feature/cdi-2.0.adoc[Contexts and Dependency Injection] feature is not enabled in your `server.xml` file, the runtime has no CDI support. Therefore, if you use a  CDI annotation in a Java class, the JAX-RS 2.0 engine uses the Java class as a plain old Java object (POJO) class.
- If a resource class with the `@Path` annotation implements a JAX-RS provider interface or declares with the `@Provider` annotation, then this class works as both a resource and a provider. In this case, the JAX-RS 2.0 engine uses only one instance of this class that is shared by the resource and the provider. The lifecycle of the instance is singleton.
- If a class is registered in both the `getClasses` and `getSingletons` methods of the application class, the JAX-RS 2.0 engine uses the instance from the `getSingletons` method and ignores the `getClasses` instance.
- If a RESTful resource is also a CDI-managed bean and its scope is `javax.enterprise.context.Dependent`, the `PreDestroy` method cannot be called because of the CDI restriction.

== JAX-RS 2.0 scope and CDI scope lifecycles

The scope of a bean defines the lifecycle of its instances. JAX-RS and CDI have slightly different scopes. If the scope lifecycle of JAX-RS and CDI are in conflict, see the following table for the result:

.JAX-RS 2.0 scope and CDI scope lifecycle
[%header,cols="6,9,9,9"]
|===
| Application|JAX-RS 2.0 Scope|CDI Scope annotation|Result
|Resource|perRequest|@ApplicationScoped|singleton
|Resource|perRequest|@RequestScoped    |perRequest
|Resource|perRequest|@Dependent        |perRequest
|Resource|perRequest|@SessionScoped    |session
|Resource|singleton |@ApplicationScoped|singleton
|Resource|singleton |@RequestScoped    |perRequest
|Resource|singleton |@Dependent        |singleton
|Resource|singleton |@SessionScoped    |session
|Provider|singleton |@ApplicationScoped|singleton
|Provider|singleton |@RequestScoped    |singleton
|Provider|singleton |@Dependent        |singleton
|Provider|singleton |@SessionScoped    |singleton
|===

For more information, see xref:cdi-beans.adoc#_cdi_scopes[CDI scopes].

=== JAX-RS 2.0 scope and CDI scope lifecycle conflict messages
The following warning messages are displayed when the scope lifecycle of JAX-RS 2.0 and CDI conflict. They are warning messages and no actions are required.

`CWWKW1001W: The scope {1} of JAXRS-2.0 Resource {0} does not match the CDI scope {2}. Liberty gets resource instance from {3}.`
This message is displayed if the JAXRS-2.0 resource scope does not match the CDI scope and the resource instance exists in CDI, so Liberty gets the resource instance from CDI. Instance does not include CDI injection if it is from JAXRS.

`CWWKW1002W: The CDI scope of JAXRS-2.0 Provider {0} is {1}. Liberty gets the provider instance from {2}.`
This message is displayed if the provider instance is Singleton only. Liberty gets the provider instance from CDI if the CDI scope of the provider is Dependent or ApplicationScoped. Instance does not include CDI injection if it is from JAXRS.
