// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
// https://creativecommons.org/licenses/by-nd/4.0/
//
//
// Contributors:
// IBM Corporation
//
//
//
//
:page-description: If you need to enable tracing for your third party JDBC driver for debugging purposes, or to submit a ticket.
:projectName: Open Liberty
:page-layout: general-reference
:page-type: general

= JDBC Tracing for Open Liberty

JDBC tracing for Open Liberty enables tracing for your third-party JDBC driver for debugging purposes, or to submit a ticket.
In order to collect JDBC trace you will need to enable tracing for your JDBC driver in Liberty, configure the logging level, and optionally provide driver specific configurations when applicable.

== Understanding Open Liberty Tracing

You can use one of the following two options for driver-specific custom trace facilities.

* Use the Java™ built-in logging mechanism, `java.util.logging`, if the driver supports it.
* Configure a custom trace setting as a vendor property.

For a more detailed article on Open Liberty tracing please read the https://openliberty.io/docs/latest/log-trace-configuration.html[Log and trace configuration] documentation.

== Understanding your JDBC Driver
Your thrid-party JDBC driver will either use the native Java logging library, or some other logging library such as SLF4J or Log4J.
If your JDBC driver uses the JUL library, then you can enable logging for your JDBC driver by providing a trace specification corresponding to the package name used by the driver.
If your JDBC driver uses some other logging library, then Open Liberty will provide a logwriter that will generate logs based off of the JDBC specification methods (getConnection, executeQuery, etc.).

The following table lists the most common JDBC drivers, if they support JUL, and the recommended trace specification (package name or logwriter).

.Third-Party JDBC Drivers
|===
| JDBC Driver | Uses JUL | Trace Specification

|**DB2 JCC**
|True
|com.ibm.db2

|**Derby**
|False - Print writer
|com.ibm.ws.derby.logwriter

|**Informix using JDBC**
|True
|com.informix

|**Informix using DB2 JCC**
|True
|com.ibm.db2

|**Microsoft SQL Server JDBC**
|True
|com.microsoft.sqlserver.jdbc

|**Microsoft SQL Server DataDirect**
|False
|com.ibm.ws.sqlserver.logwriter

|**Oracle**
|True
|oracle

|**PostreSQL**
|False - SLF4J
|com.ibm.ws.postgresql.logwriter

|**Sybase**
|False
|com.ibm.ws.sybase.logwriter

|**Other databases (for example MySQL)**
|False - Unknown
|com.ibm.ws.database.logwriter

|===

== Recommended Trace Configuration for Support

The following examples contain the trace configuration when enabling trace for JDBC support.

.bootstrap.properties
[source, properties]
----
com.ibm.ws.logging.trace.specification=*=info:RRA=all
com.ibm.ws.logging.max.files=10
com.ibm.ws.logging.max.file.size=100
----

.server.xml
[source, xml]
----
<logging traceSpecification="*=info:RRA=all" maxFiles=10 maxFileSize=100 />
----

== Enabling trace for your JDBC driver

If the driver you are using has custom trace settings, you set them as JDBC driver vendor properties in the `server.xml` file.
You also add the logwriter name to the trace specification in the `bootstrap.properties` file.
The following sub-sections contain JDBC driver specfic configuration.

=== DB2 JCC

.bootstrap.properties
[source, properties]
----
com.ibm.ws.logging.trace.specification=*=info:RRA=all:com.ibm.db2=all
----

.server.xml
[source, xml]
----
<logging traceSpecification="*=info:RRA=all:com.ibm.db2=all" ... />
<datasource ...>
  <!-- traceLevel -1 is equivalent to ALL -->
  <propertes.db2.jcc traceLevel="-1"/>
</datasource>
----

=== Derby

.bootstrap.properties
[source, properties]
----
com.ibm.ws.logging.trace.specification=*=info:RRA=all:com.ibm.ws.derby.logwriter=all
----

.server.xml
[source, xml]
----
<logging traceSpecification="*=info:RRA=all:com.ibm.ws.derby.logwriter=all" />
----

=== Informix using JDBC

.bootstrap.properties
[source, properties]
----
com.ibm.ws.logging.trace.specification=*=info:RRA=all:com.informix=all
----

.server.xml
[source, xml]
----
<logging traceSpecification="*=info:RRA=all:com.informix=all" />
----

=== Informix using DB2 JCC

.bootstrap.properties
[source, properties]
----
com.ibm.ws.logging.trace.specification=*=info:RRA=all:com.ibm.db2=all
----

.server.xml
[source, xml]
----
<logging traceSpecification="*=info:RRA=all:com.ibm.db2=all" />

<datasource ... >
  <!-- traceLevel -1 is equivalent to ALL -->
  <properties.informix.jcc traceLevel="-1"/>
</datasource>
----

=== Microsoft SQL Server JDBC driver

.bootstrap.properties
[source, properties]
----
com.ibm.ws.logging.trace.specification=*=info:RRA=all:com.microsoft.sqlserver.jdbc=all
----

.server.xml
[source, xml]
----
<logging traceSpecification="*=info:RRA=all:com.microsoft.sqlserver.jdbc=all" />
----

=== Microsoft SQL Server DataDirect driver

.bootstrap.properties
[source, properties]
----
com.ibm.ws.logging.trace.specification=*=info:RRA=all:com.ibm.ws.sqlserver.logwriter=all
----

.server.xml
[source, xml]
----
<logging traceSpecification="*=info:RRA=all:com.ibm.ws.sqlserver.logwriter=all" />
----

=== Oracle

.bootstrap.properties
[source, properties]
----
com.ibm.ws.logging.trace.specification=*=info:RRA=all:oracle=all
----

.server.xml
[source, xml]
----
<logging traceSpecification="*=info:RRA=all:oracle=all" />
<library id="oracleDebug">
    <file name="${path.to.oracle.dir}/ojdbcX_g.jar"/>
</library>
----

.jvm.options
[source, txt]
----
-Doracle.jdbc.Trace=true
----

=== PostreSQL

.bootstrap.properties
[source, properties]
----
com.ibm.ws.logging.trace.specification=*=info:RRA=all:com.ibm.ws.postgresql.logwriter=all
----

.server.xml
[source, xml]
----
<logging traceSpecification="*=info:RRA=all:com.ibm.ws.postgresql.logwriter=all" />
----

=== Sybase

.bootstrap.properties
[source, properties]
----
com.ibm.ws.logging.trace.specification=*=info:RRA=all:com.ibm.ws.sybase.logwriter=all
----

.server.xml
[source, xml]
----
<logging traceSpecification="*=info:RRA=all:com.ibm.ws.sybase.logwriter=all" />
----

=== Other databases

.bootstrap.properties
[source, properties]
----
com.ibm.ws.logging.trace.specification=*=info:RRA=all:com.ibm.ws.database.logwriter=all
----

.server.xml
[source, xml]
----
<logging traceSpecification="*=info:RRA=all:com.ibm.ws.database.logwriter=all" />
----
