// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title:
:page-layout: general-reference
:page-type: general
= JSON log format

Logs provide valuable insights into the performance of your applications, but they can be difficult to parse and understand without special log analysis tools. JSON is a standard log data format that is used by many popular log analysis tools and platforms, such as the Elastic Stack and Splunk.

JSON is a structured data format that is compact and human-readable. It is also standardized, which means that log analysis tools can parse it efficiently, regardless of the application.
When you configure your logs to output in JSON format, you can aggregate, manage, and analyze them with any platform or service that reads JSON. Log analysis platforms can help you get a comprehensive view of what's going on in your application, as well as troubleshoot particular issues your users are experiencing. You can even add your own custom JSON fields to the logs to gather data about a particular user or session.

== Configure Open Liberty logs in JSON format

There are three different options to configure your logs in JSON format:

- the `bootstrap.properties` file
- environmental variables
- the `server.xml` file

Which option is best for you depends on the details of your applications and server configuration. For more information, see xref:log-trace-configuration.adoc#_json_logging[the JSON logging section of Log and trace configuration].

=== Change default field names

In some cases, you might want to change the default field names in your Open Liberty logs to match the field names from other containers in the configuration. For example, an Open Liberty message is referred to by the field name `message`, while another container’s message might be referred to by a field called `log`. In this case, two different visualizations of the messages would show in the logs on a dashboard. However, if you modify the Open Liberty output field names to  match the field names from the other container, the fields can all be viewed in the same visualization. For more information, see xref:log-trace-configuration.adoc#_configuring_json_field_names[the Configuring JSON field names section of Log and trace configuration].

=== Add custom fields

You can also add custom fields to your JSON log output so you can better understand certain aspects of your application performance. For example, if you want to check all the requests that originated from a particular user, you can add a custom field to the logs for that user's ID. Furthermore, you can add another field for session ID, so that you can diagnose issues with a specific session that is associated with the user. Any dashboards that you build from this logging configuration can display these custom fields. For more information, see **link pending**.

=== Make your logs more human-readable

Although JSON is considered a human-readable format, JSON logs output to a single line and can be difficult to read at a glance. link:https://stedolan.github.io/jq/[jq] is an open source  command-line JSON processor that you can use to output your JSON logs in a more human-readable format. With jq, you can parse your logs so that each field is on its own line. You can also customize your query to include only certain logs or fields within a log in the output. For more information, see https://stedolan.github.io/jq/manual/[the jq documentation].

== See also

- For an overview of JSON logging configuration in Open Liberty, check out link:https://developer.ibm.com/technologies/java/videos/use-json-logging-in-open-liberty/[this video from IBM Developer].
- To learn more about log management solutions for Open Liberty, see xref:log-management.adoc[Log management].
- To learn about Open Liberty logs and logging configuration options, see xref:log-and-trace-configuration.adoc[Log and trace configuration].
