// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: JSON logging events - OpenLiberty.io
:seo-description: The JSON logging events that can be captured from the Open Liberty server runtime environment and applications.
= JSON log events reference list

Open Liberty generates JSON logging events from the server runtime and applications. You can use these events to gather and analyze data that can help to better understand the behavior of applications.

The following types of events are generated by Open Liberty:

* <<Message log events, Message log events>>
* <<Trace log events, Trace log events>>
* <<FFDC log events, FFDC log events>>
* <<HTTP access log events, HTTP access log events>>
* <<Supported audit events and their audit data, Audit Events>>


== Message log events
The following table provides the fields for message log events and a description for each field:

.Message log event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event.
|host |Host name of the server that was the source of the event.
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the event.
|message |The message from log record, starting with the message ID.
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_datetime |Time at which the event occurred.
|ibm_messageId |Message ID in the log line, which can be used to find out specific types of errors, for example, SRVE0250I
|module |Logger name from log record.
|loglevel |Severity indicator (F = Fatal, E = Error, W = Warning, A = Audit, I = Info, O = SystemOut, R = SystemErr)
|ibm_methodName |Method name from log record.
|ibm_className |Class name from log record.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ext_thread |Thread name of the thread that was the source of the event
|===

The following example shows a message log event:

[source,json]
----
{
    "type":"liberty_message",
    "host":"9e1eceec70c1",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"defaultServer",
    "message":"BADAP0004W: BadApp Angry for test",
    "ibm_threadId":"0000009f",
    "ibm_datetime":"2020-05-04T12:33:26.064+0000",
    "ibm_messageId":"BADAP0004W",
    "module":"com.ibm.ws.lumberjack.badness.Angry",
    "loglevel":"WARNING",
    "ibm_methodName":"doGet",
    "ibm_className":"Angry",
    "ibm_sequence":"1588595606064_0000000000024",
    "ext_thread":"Default Executor-thread-108"
}
----

== Trace log events
The following table provides the fields for trace log events and a description for each field:

.Trace log event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event.
|host |Host name of the server that was the source of the event.
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the event.
|message |The message from log record.
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_datetime |Time at which the event occurred.
|ibm_messageId |Message ID in the log line, which can be used to find out specific types of errors, for example, SRVE0250I
|module |Logger name from log record.
|loglevel |Severity indicator (1 = Fine, 2 = Finer, 3 = Finest, > = Entry, < = Exit)
|ibm_methodName |Method name from log record.
|ibm_className |Class name from log record.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ext_thread |Thread name of the thread that was the source of the event
|===

The following example of shows a trace log event:

[source,json]
----
{
    "type":"liberty_trace",
    "host":"9e1eceec70c1",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"defaultServer",
    "message":"BadApp Angry test",
    "ibm_threadId":"0000009f",
    "ibm_datetime":"2020-05-04T12:33:26.066+0000",
    "ibm_messageId":"BADAP0001W",
    "module":"com.ibm.ws.lumberjack.badness.Angry",
    "loglevel":"FINE",
    "ibm_methodName":"doGet",
    "ibm_className":"Angry",
    "ibm_sequence":"1588595606066_0000000000001"
    "ext_thread":"Default Executor-thread-108"
}
----

== FFDC log events
The following table provides the fields for first failure data capture (FFDC) events and a description for each field:

.FFDC log event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event.
|host |Host name of the server that was the source of the event.
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the event.
|ibm_datetime |Time at which the event occurred.
|message |The message from log record.
|ibm_className |The class that emitted the FFDC entry.
|ibm_exceptionName |The exception that was reported in the FFDC entry.
|ibm_probeID |The unique identifier of the FFDC point within the class.
|ibm_threadId |The thread ID of the FFDC incident.
|ibm_stackTrace |The stack trace of the FFDC incident.
|ibm_objectDetails |The incident details for the FFDC incident.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).

|===

The following example shows a FFDC log event:
[source,json]
----
{
    "type":"liberty_ffdc",
    "host":"252ecfa1f755",
    "ibm_userDir":"\/opt\/ibm\/wlp\/usr\/",
    "ibm_serverName":"defaultServer",
    "ibm_datetime":"2020-03-24T19:08:14.579+0000",
    "message":"A metric named   com.acmeair.web.AuthServiceRest.com.acmeair.web.AuthServiceRest.login with tags app=\"acmeair-authservice-java\" already exists",
    "ibm_className":"com.ibm.ws.microprofile.metrics.impl.MetricRegistryImpl",
    "ibm_exceptionName":"java.lang.IllegalArgumentException",
    "ibm_probeID":"656",
    "ibm_threadId":"00000275",
    "ibm_stackTrace":"java.lang.IllegalArgumentException: A metric named com.acmeair.web.AuthServiceRest.com.acmeair.web.AuthServiceRest.login with tags app=\"acmeair-authservice-java\" already exists\n\tat ...",
    "ibm_objectDetails":"Object type = com.ibm.ws.microprofile.metrics.impl.MetricRegistryImpl\n  metrics = class java.util.concurrent.ConcurrentHashMap@f445b6cd\n...",
    "ibm_sequence":"1585076894579_0000000000001"
}
----

== HTTP access log events
The following table provides the fields for HTTP access log events and a description for each field:

.HTTP access log event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event.
|host |Host name of the server that was the source of the event.
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the event.
|ibm_remoteHost |Remote host IP address, for example, 127.0.0.1
|ibm_requestProtocol |Protocol type, for example, HTTP/1.1.
|ibm_userAgent |The userAgent value in the request.
|ibm_requestHeader_{headername} |Header value from the request.
|ibm_requestMethod |HTTP verb, for example, GET
|ibm_responseHeader_{headername} |Header value from the response.
|ibm_requestPort |Port number of the request.
|ibm_requestFirstLine |First line of the request.
|ibm_responseCode |HTTP response code, for example, 200.
|ibm_requestStartTime |The start time of the request.
|ibm_remoteUserID |Remote user according to the WebSphere Application Server specific $WSRU header
|ibm_uriPath |Path information for the requested URL. This path information does not contain the query parameters, for example, `/pushworksserver/push/apps/tags`.
|ibm_elapsedTime |Time that is taken to serve the request, in microseconds.
|ibm_accessLogDatetime |The time when the message to the access log is queued to be logged.
|ibm_remoteIP |Remote IP address, e.g. 127.0.0.1
|ibm_requestHost |Request host IP address, for example, 127.0.0.1.
|ibm_bytesSent |Response size in bytes excluding headers.
|ibm_bytesReceived |Bytes received in the URL, for example, 94.
|ibm_cookie_{cookiename} |Cookie value from the request.
|ibm_requestElapsedTime |The elapsed time of the request - millisecond accuracy, microsecond precision.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).

|===

The following example shows a HTTP access log event:

[source,json]
----
{
    "type":"liberty_accesslog",
    "host":"79e8ad2347b3",
    "ibm_userDir":"\/opt\/ibm\/wlp\/usr\/",
    "ibm_serverName":"defaultServer",
    "ibm_remoteHost":"172.27.0.10",
    "ibm_requestProtocol":"HTTP\/1.1",
    "ibm_userAgent":"Apache-CXF/3.3.3-SNAPSHOT",
    "ibm_requestHeader_headername":"header_value"
    "ibm_requestMethod":"GET",
    "ibm_responseHeader_connection":"Close",
    "ibm_requestPort":"9080",
    "ibm_requestFirstLine":"GET \/favicon.ico HTTP\/1.1",
    "ibm_responseCode":200,
    "ibm_requestStartTime":"2020-07-14T13:28:19.887-0400",
    "ibm_remoteUserID":"user",
    "ibm_uriPath":"\/favicon.ico",
    "ibm_elapsedTime":834,
    "ibm_accessLogDatetime":"2020-07-14T13:28:19.887-0400",
    "ibm_remoteIP":"172.27.0.9",
    "ibm_requestHost":"172.27.0.9",
    "ibm_bytesSent":15086,
    "ibm_bytesReceived":15086,
    "ibm_cookie_cookiename":"cookie_value",
    "ibm_requestElapsedTime":3034,
    "ibm_datetime":"2020-07-14T13:28:19.887-0400",
    "ibm_sequence":"1594747699884_0000000000001"
}
----

== Supported audit events and their audit data

The Liberty Audit feature captures auditable events from the server runtime environment and applications. You can use the data that is generated from the audit events to analyze the configured environment.

The audit events are captured in the following formats to help identify different areas where the configured environment can be improved:

* <<SECURITY_AUDIT_MGMT, Management of the audit service (SECURITY_AUDIT_MGMT)>>
* <<SECURITY_MEMBER_MGMT, SCIM operations/member management (SECURITY_MEMBER_MGMT)>>
* <<SECURITY_API_AUTHN, Servlet 3.0 APIs: login/authenticate (SECURITY_API_AUTHN)>>
* <<SECURITY_API_AUTHN_TERMINATE, Servlet 3.0 APIs: logout (SECURITY_API_AUTHN_TERMINATE)>>
* <<SECURITY_AUTHN_TERMINATE, Form Logout (SECURITY_AUTHN_TERMINATE)>>
* <<SECURITY_AUTHN, Basic Authentication (SECURITY_AUTHN)>>
* <<SECURITY_AUTHN, Client certificate authentication (SECURITY_AUTHN)>>
* <<SECURITY_AUTHN, Form Login Authenication (SECURITY_AUTHN)>>
* <<SECURITY_AUTHN_DELEGATION, Servlet runAs delegation (SECURITY_AUTHN_DELEGATION)>>
* <<SECURITY_AUTHN_DELEGATION, EJB delegation (SECURITY_AUTHN_DELEGATION)>>
* <<SECURITY_AUTHN_FAILOVER, Failover to basic authentication (SECURITY_AUTHN_FAILOVER)>>
* <<SECURITY_AUTHZ, Unprotected servlet authorization (SECURITY_AUTHZ)>>
* <<SECURITY_AUTHZ, JACC web authorization (SECURITY_AUTHZ)>>
* <<SECURITY_AUTHZ, JACC EJB authorization (SECURITY_AUTHZ)>>
* <<SECURITY_AUTHZ, EJB authorization (SECURITY_AUTHZ)>>
* <<SECURITY_JMS_AUTHN, JMS Authentication (SECURITY_JMS_AUTHN)>>
* <<SECURITY_JMS_AUTHZ, JMS Authorization (SECURITY_JMS_AUTHZ)>>
* <<SECURITY_SAF_AUTHZ, SAF Authorization Service API request (SECURITY_SAF_AUTHZ)>>
* <<SECURITY_SAF_AUTHZ_DETAILS, SAF Authorization Exception (SECURITY_SAF_AUTHZ_DETAILS)>>
* <<JMX_MBEAN_REGISTER, JMX MBean registration (JMX_MBEAN_REGISTER)>>
* <<JMX_MBEAN, JMX MBean Operations (JXM_MBEAN)>>
* <<JMX_MBEAN_ATTRIBUTES, JMX MBean attribute operations (JMX_MBEAN_ATTRIBUTES)>>
* <<JMX_NOTIFICATION, JMX Notifications (JMX_NOTIFICATION)>>

=== SECURITY_AUDIT_MGMT

The SECURITY_AUDIT_MGMT event captures the start and stop of the Audit Service and implemented handlers such as the default AuditFileHandler.


The following table provides the fields for the SECURITY_AUDIT_MGMT event to capture the audit information from the management of the audit service.

.SECURITY_AUDIT_MGMT event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `AuditService` in the case of the audit service; `AuditHandler: <name of handler implementation>` in the case of a handler start
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.typeURI |Unique URI of the target of the event: `server/audit/start` in the case of an AuditService or handler start; `server/audit/stop` in the case of an AuditService or handler stop
|===


The following example shows the SECURITY_AUDIT_MGMT event capturing the start of the Audit Service and AuditFileHandler:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"TestServer.audit",
    "ibm_datetime":"2018-07-10T16:15:35.110-0400",
    "ibm_sequence":"1536171863908_0000000000001",
    "ibm_threadId":"00000013",
    "ibm_audit_eventName":"SECURITY_AUDIT_MGMT",
    "ibm_audit_eventSequenceNumber":"0",
    "ibm_audit_eventTime":"2018-07-10T16:15:34.339-0400",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:TestServer.audit",
    "ibm_audit_observer.name":"AuditService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:TestServer.audit",
    "ibm_audit_target.typeURI":"service/audit/start"
}

{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"TestServer.audit",
    "ibm_datetime":"2018-07-10T16:15:35.740-0400",
    "ibm_sequence":"1536171863908_0000000000002",
    "ibm_threadId":"00000013",
    "ibm_audit_eventName":"SECURITY_AUDIT_MGMT",
    "ibm_audit_eventSequenceNumber":"1",
    "ibm_audit_eventTime":"2018-07-10T16:15:34.471-0400",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:TestServer.audit",
    "ibm_audit_observer.name":"AuditHandler:AuditFileHandler",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:TestServer.audit",
    "ibm_audit_target.typeURI":"service/audit/start"
}
----


=== SECURITY_MEMBER_MGMT

You can use the SECURITY_MEMBER_MGMT event to capture the audit information from SCIM operations or member management. The following table provides the fields for the SECURITY_Member_MGMT event and a description of each field.

.SECURITY_MEMBER_MGMT event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_initiator.host.address |Host address of the initiator of the event
|ibm_audit_initiator.host.agent |Name of monitoring agent associated with initiator
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `SecurityService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success.
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., and HTTP or HTTPS associated with the request
|ibm_audit_target.action |What action was being performed on the target
|ibm_audit_target.appname |Name of the application to be accessed or run on the target
|ibm_audit_target.credential.token |Token name of user performing action
|ibm_audit_target.credential.type |Token type of user performing action
|ibm_audit_target.entityType |Generic name of the member being acted upon: PersonAccount, Group
|ibm_audit_target.host.address |Host and port of the target
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.method |Method being invoked on the target, i.e.,GET, POST
|ibm_audit_target.name |Name of the target. Note that the name will include "urbridge", "scim" or "vmmservice", depending on the flow of the request (for example, is it a call coming through scim).
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.repositoryId |Repository identifier associated with the target
|ibm_audit_target.session |Session identifier associated with the target
|ibm_audit_target.uniqueName |Unique name of the member being acted upon
|ibm_audit_target.typeURI |Unique URI of the target of the event: server/vmmservice/<action>
|===

The following example shows a SECURITY_MEMBER_MGMT user record creation action:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"scim.custom.repository.audit",
    "ibm_datetime":"2018-07-24T14:59:82.321-0400",
    "ibm_sequence":"1536329056532_0000000000047",
    "ibm_threadId":"000000a5",
    "ibm_audit_eventName":"SECURITY_MEMBER_MGMT",
    "ibm_audit_eventSequenceNumber":"13",
    "ibm_audit_eventTime":"2018-07-24T14:58:45.284-0400",
    "ibm_audit_initiator.host.address":"127.0.0.1",
    "ibm_audit_initiator.host.agent":"Java/1.8.0",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:scim.custom.repository.audit",
    "ibm_audit_observer.name":"SecurityService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"HTTPS",
    "ibm_audit_target.action":"create",
    "ibm_audit_target.appname":"RESTProxyServlet",
    "ibm_audit_target.credential.token":"adminUser",
    "ibm_audit_target.credential.type":"BASIC",
    "ibm_audit_target.entityType":"PersonAccount",
    "ibm_audit_target.host.address":"127.0.0.1:63571",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:scim.custom.repository.audit",
    "ibm_audit_target.method":"POST",
    "ibm_audit_target.name":"/ibm/api/scim/Users",
    "ibm_audit_target.realm":"sampleCustomRepositoryRealm",
    "ibm_audit_target.repositoryId":"sampleCustomRepository",
    "ibm_audit_target.session":"myQz9fZu2ZUW0nEUWvEaiQC",
    "ibm_audit_target.typeURI":"service/vmmservice/create",
    "ibm_audit_target.uniqueName":"cn=usertemp,o=ibm,c=us"
}
----

The following example shows a SECURITY_MEMBER_MGMT user lookup action:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"scim.custom.repository.audit",
    "ibm_datetime":"2018-07-24T14:59:82.433-0400",
    "ibm_sequence":"1536329056532_0000000000048",
    "ibm_threadId":"000000a5",
    "ibm_audit_eventName":"SECURITY_MEMBER_MGMT",
    "ibm_audit_eventSequenceNumber":"14",
    "ibm_audit_eventTime":"2018-07-24T14:58:45.343-0400",
    "ibm_audit_initiator.host.address":"127.0.0.1",
    "ibm_audit_initiator.host.agent":"Java/1.8.0",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:scim.custom.repository.audit",
    "ibm_audit_observer.name":"SecurityService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"HTTPS",
    "ibm_audit_target.action":"get",
    "ibm_audit_target.appname":"RESTProxyServlet",
    "ibm_audit_target.credential.token":"adminUser",
    "ibm_audit_target.credential.type":"BASIC",
    "ibm_audit_target.entityType":"PersonAccount",
    "ibm_audit_target.host.address":"127.0.0.1:63571",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:scim.custom.repository.audit",
    "ibm_audit_target.method":"POST",
    "ibm_audit_target.name":"/ibm/api/scim/Users",
    "ibm_audit_target.realm":"sampleCustomRepositoryRealm",
    "ibm_audit_target.repositoryId":"sampleCustomRepository",
    "ibm_audit_target.session":"myQz9fZu2ZUW0nEUWvEaiQC",
    "ibm_audit_target.typeURI":"service/vmmservice/get",
    "ibm_audit_target.uniqueName":"cn=usertemp,o=ibm,c=us"
}
----


=== SECURITY_API_AUTHN

You can use the SECURITY_API_AUTHN event to capture the audit information from the login and authentication for servlet 3.0 APIs. The following table provides the fields for the SECURITY_API_AUTHN event and a description of each field.

.SECURITY_API_AUTHN event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_initiator.host.address |Host address of the initiator of the event
|ibm_audit_initiator.host.agent |Name of monitoring agent associated with initiator
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `SecurityService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., HTTP or HTTPS, associated with the request
|ibm_audit_target.appname |Name of the application to be accessed or run on the target
|ibm_audit_target.credential.token |Token name of user performing action
|ibm_audit_target.credential.type |Token type of user performing action. BASIC, FORM or CLIENTCERT
|ibm_audit_target.host.address |Host and port of the target
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.method |Method being invoked on the target, i.e.,GET, POST
|ibm_audit_target.name |Context root
|ibm_audit_target.params |Names and values of any parameters sent to the target with the action
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.session |HTTP session ID
|ibm_audit_target.typeURI |Unique URI of the target of the event: `service/application/web`
|===

The following example shows a SECURITY_API_AUTHN event that results in a redirect:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"com.ibm.ws.webcontainer.security.fat.loginmethod.audit",
    "ibm_datetime":"2018-07-24T17:03:25.628-0400",
    "ibm_sequence":"1536329078239_0000000000020",
    "ibm_threadId":"000000b7",
    "ibm_audit_eventName":"SECURITY_API_AUTHN",
    "ibm_audit_eventSequenceNumber":"2",
    "ibm_audit_eventTime":"2018-07-24T17:03:24.142-0400",
    "ibm_audit_initiator.host.address":"127.0.0.1",
    "ibm_audit_initiator.host.agent":"Apache-HttpClient/4.1.2 (java 1.5)",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:com.ibm.ws.webcontainer.security.fat.loginmethod.audit",
    "ibm_audit_observer.name":"SecurityService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"failure",
    "ibm_audit_reason.reasonCode":"401",
    "ibm_audit_reason.reasonType":"HTTP",
    "ibm_audit_target.appname":"ProgrammaticAPIServlet",
    "ibm_audit_target.credential.token":"user2",
    "ibm_audit_target.credential.type":"BASIC",
    "ibm_audit_target.host.address":"127.0.0.1:8010",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:com.ibm.ws.webcontainer.security.fat.loginmethod.audit",
    "ibm_audit_target.method":"GET",
    "ibm_audit_target.name":"/basicauth/ProgrammaticAPIServlet",
    "ibm_audit_target.params":"testMethod=login,logout,login&user=user2&password=*******", "ibm_audit_target.realm":"BasicRealm",
    "ibm_audit_target.session":"MDqMWXO--7cmdu4Oqkt8J3i",
    "ibm_audit_target.typeURI":"service/application/web"
}
----

=== SECURITY_API_AUTHN_TERMINATE

You can use the SECURITY_API_AUTHN_TERMINATE event to capture the audit information from the log out for servlet 3.0 APIs. The following table provides the fields for the SECURITY_API_AUTHN_TERMINATE event and a description of each field.

.SECURITY_API_AUTHN_TERMINATE event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_initiator.host.address |Host address of the initiator of the event
|ibm_audit_initiator.host.agent |Name of monitoring agent associated with initiator
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `SecurityService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., HTTP or HTTPS, associated with the request
|ibm_audit_target.appname |Name of the application to be accessed or run on the target
|ibm_audit_target.credential.token |Token name of user performing action
|ibm_audit_target.credential.type |Token type of user performing action. BASIC, FORM or CLIENTCERT
|ibm_audit_target.host.address |Host and port of the target
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.method |Method being invoked on the target, i.e.,GET, POST
|ibm_audit_target.name |Context root
|ibm_audit_target.params |Names and values of any parameters sent to the target with the action
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.session |HTTP Session ID
|ibm_audit_target.typeURI |Unique URI of the target of the event: `service/application/web`
|===

The following example shows a successful SECURITY_API_AUTHN_TERMINATE event:

[source, json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"com.ibm.ws.webcontainer.security.fat.loginmethod.audit",
    "ibm_datetime":"2018-07-24T17:03:25.845-0400",
    "ibm_sequence":"1536329078239_0000000000021",
    "ibm_threadId":"000000b7",
    "ibm_audit_eventName":"SECURITY_API_AUTHN_TERMINATE",
    "ibm_audit_eventSequenceNumber":"3",
    "ibm_audit_eventTime":"2018-07-24T17:03:24.193-0400",
    "ibm_audit_initiator.host.address":"127.0.0.1",
    "ibm_audit_initiator.host.agent":"Apache-HttpClient/4.1.2 (java 1.5)",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr:com.ibm.ws.webcontainer.security.fat.loginmethod.audit",
    "ibm_audit_observer.name":"SecurityService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"HTTP",
    "ibm_audit_target.appname":"ProgrammaticAPIServlet",
    "ibm_audit_target.credential.token":"user1",
    "ibm_audit_target.credential.type":"BASIC",
    "ibm_audit_target.host.address":"127.0.0.1:8010",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:com.ibm.ws.webcontainer.security.fat.loginmethod.audit",
    "ibm_audit_target.method":"GET",
    "ibm_audit_target.name":"/basicauth/ProgrammaticAPIServlet",
    "ibm_audit_target.params":"testMethod=login,logout,login&user=user2&password=*******",
    "ibm_audit_target.realm":"BasicRealm",
    "ibm_audit_target.session":"MDqMWXO--7cmdu4Oqkt8J3i",
    "ibm_audit_target.typeURI":"service/application/web"
}
----

=== SECURITY_AUTHN

You can use the SECURITY_AUTHN event to capture the audit information from basic authentication, form login authentication, client certificate authentication, and JASPI authentication. The following table provides the fields for the SECURITY_AUTHN event and a description of each field.

.SECURITY_AUTHN event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_initiator.host.address |Host address of the initiator of the event
|ibm_audit_initiator.host.agent |Name of monitoring agent associated with initiator
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `SecurityService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., HTTP or HTTPS, associated with the request
|ibm_audit_target.appname |Name of the application to be accessed or run on the target
|ibm_audit_target.credential.token |Token name of user performing action
|ibm_audit_target.credential.type |Token type of user performing action. BASIC, FORM or CLIENTCERT
|ibm_audit_target.host.address |Host and port of the target
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.method |Method being invoked on the target, i.e.,GET, POST
|ibm_audit_target.name |Context root
|ibm_audit_target.params |Names and values of any parameters sent to the target with the action
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.session |HTTP session ID
|ibm_audit_target.typeURI |Unique URI of the target of the event: `service/application/web`
|===

The following example shows a successful SECURITY_AUTHN event:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"com.ibm.ws.webcontainer.security.fat.loginmethod.audit",
    "ibm_datetime":"2018-07-24T17:04:53.213-0400",
    "ibm_sequence":"1536171867413_0000000000003",
    "ibm_threadId":"00000050",
    "ibm_audit_eventName":"SECURITY_AUTHN",
    "ibm_audit_eventSequenceNumber":"6",
    "ibm_audit_eventTime":"2018-07-24T17:03:28.652-0400",
    "ibm_audit_initiator.host.address":"127.0.0.1",
    "ibm_audit_initiator.host.agent":"Apache-HttpClient/4.1.2 (java 1.5)",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:com.ibm.ws.webcontainer.security.fat.loginmethod.audit",
    "ibm_audit_observer.name":"SecurityService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"HTTP",
    "ibm_audit_target.appname":"ProgrammaticAPIServlet",
    "ibm_audit_target.credential.token":"user1",
    "ibm_audit_target.credential.type":"BASIC",
    "ibm_audit_target.host.address":"127.0.0.1:8010",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:com.ibm.ws.webcontainer.security.fat.loginmethod.audit",
    "ibm_audit_target.method":"GET",
    "ibm_audit_target.name":"/basicauth/ProgrammaticAPIServlet",
    "ibm_audit_target.params":"testMethod=login,logout,login&user=invalidUser&password=*********",
    "ibm_audit_target.realm":"BasicRealm",
    "ibm_audit_target.session":"vvmysQmVNHt4OfCRNIflZBt",
    "ibm_audit_target.typeURI":"service/application/web"
}
----


=== SECURITY_AUTHN_DELEGATION

You can use the SECURITY_AUTHN_DELEGATION event to capture the audit information from Servlet runAs delegation and EJB delegation. The following table provides the fields for the SECURITY_AUTHN_DELEGATION event and a description of each field.

.SECURITY_AUTHN_DELEGATION event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_initiator.host.address |Host address of the initiator of the event
|ibm_audit_initiator.host.agent |Name of monitoring agent associated with initiator
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `SecurityService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., HTTP or HTTPS, associated with the request
|ibm_audit_target.appname |Name of the application to be accessed or run on the target
|ibm_audit_target.credential.token |Token name of user performing action
|ibm_audit_target.credential.type |Token type of user performing action. BASIC, FORM or CLIENTCERT
|ibm_audit_target.delegation.users |List of users in the delegation flow, starting with the initial user invoking the action
|ibm_audit_target.host.address |Host and port of the target
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.method |Method being invoked on the target, i.e.,GET, POST
|ibm_audit_target.name |Context root
|ibm_audit_target.params |Names and values of any parameters sent to the target with the action
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.runas.role |RunAs role name used in the delegation
|ibm_audit_target.session |HTTP session ID
|ibm_audit_target.typeURI |Unique URI of the target of the event: `service/application/web`
|===



The following example shows a successful SECURITY_AUTHN_DELEGATION event:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"com.ibm.ws.ejbcontainer.security.fat.audit",
    "ibm_datetime":"2018-07-16T14:39:22.521-0400",
    "ibm_sequence":"1536329023162_0000000000001",
    "ibm_threadId":"00000080",
    "ibm_audit_eventName":"SECURITY_AUTHN_DELEGATION",
    "ibm_audit_eventSequenceNumber":"12",
    "ibm_audit_eventTime":"2018-07-16T14:38:02.281-0400",
    "ibm_audit_initiator.host.address":"127.0.0.1",
    "ibm_audit_initiator.host.agent":"Apache-HttpClient/4.1.2 (java 1.5 ",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:com.ibm.ws.ejbcontainer.security.fat.audit",
    "ibm_audit_observer.name":"SecurityService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"EJB",
    "ibm_audit_target.appname":"SecurityEJBA01Bean",
    "ibm_audit_target.credential.token":"user2",
    "ibm_audit_target.credential.type":"BASIC",
    "ibm_audit_target.delegation.users":"user:BasicRealm/user2;user:BasicRealm/user99",
    "ibm_audit_target.host.address":"127.0.0.1:8010",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:com.ibm.ws.ejbcontainer.security.fat.audit",
    "ibm_audit_target.method":"GET",
    "ibm_audit_target.name":"/securityejb/SimpleServlet",
    "ibm_audit_target.params":"testInstance=ejb01&testMethod=runAsSpecified",
    "ibm_audit_target.realm":"BasicRealm",
    "ibm_audit_target.runas.role":"Employee",
    "ibm_audit_target.session":"b3g01JoFvsy7uKDNBqH7An-",
    "ibm_audit_target.typeURI":"service/application/web"
}
----

=== SECURITY_AUTHN_FAILOVER

You can use the SECURITY_AUTHN_FAILOVER event to capture the audit information from failover to basic authentication. The following table provides the fields for the SECURITY_AUTHN_FAILOVER event and a description of each field.

.SECURITY_AUTHN_FAILOVER event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_initiator.host.address |Host address of the initiator of the event
|ibm_audit_initiator.host.agent |Name of monitoring agent associated with initiator
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `SecurityService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., HTTP or HTTPS associated with the request
|ibm_audit_target.appname |Name of the application to be accessed or run on the target
|ibm_audit_target.authtype.failover |Name of failover authentication mechanism
|ibm_audit_target.credential.token |Token name of user performing action
|ibm_audit_target.credential.type |Token type of user performing action. BASIC, FORM, or CLIENTCERT
|ibm_audit_target.host.address |Host and port of the target
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.method |Method being invoked on the target, i.e.,GET, POST
|ibm_audit_target.name |Context root
|ibm_audit_target.params |Names and values of any parameters sent to the target with the action
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.session |HTTP session ID
|ibm_audit_target.typeURI |Unique URI of the target of the event: `service/application/web`
|===

The following example shows a SECURITY_AUTHN_FAILOVER event:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/", 
    "ibm_serverName":"com.ibm.ws.webcontainer.security.fat.clientcertfailover.audit",
    "ibm_datetime":"2018-07-24T17:06:42.201-0400",
    "ibm_sequence":"1541329052120_0000000000001",
    "ibm_threadId":"00000010",
    "ibm_audit_eventName" "SECURITY_AUTHN_FAILOVER",
    "ibm_audit_eventSequenceNumber":"4",
    "ibm_audit_eventTime":"2018-07-24T17:05:03.777-0400",
    "ibm_audit_initiator.host.address":"127.0.0.1",
    "ibm_audit_initiator.host.agent":"Apache-HttpClient/4.1.2 (java 1.5)",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/",
    "ibm_audit_observer.name":"SecurityService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"HTTPS",
    "ibm_audit_target.appname":"ClientCertServlet",
    "ibm_audit_target.authtype.failover":"BASIC",
    "ibm_audit_target.authtype.original":"CLIENT_CERT",
    "ibm_audit_target.credential.token":"LDAPUser1",
    "ibm_audit_target.credential.type":"BASIC",
    "ibm_audit_target.host.address":"127.0.0.1:8020",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/",
    "ibm_audit_target.method":"GET",
    "ibm_audit_target.name":"/clientcert/SimpleServlet",
    "ibm_audit_target.realm":"SampleLdapIDSRealm",
    "ibm_audit_target.session":"-7moVRZaL1mU2SVf0RHP28x",
    "ibm_audit_target.typeURI":"service/application/web"
}
----


=== SECURITY_AUTHN_TERMINATE

You can use the SECURTIY_AUTHN_TERMINATE event to capture the audit information from a form logout. The following table provides the fields for the SECURITY_AUTHN_TERMINATE event and a description of each field.

.SECURITY_AUTHN_TERMINATE event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_initiator.host.address |Host address of the initiator of the event
|ibm_audit_initiator.host.agent |Name of monitoring agent associated with initiator
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `SecurityService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., HTTP or HTTPS, associated with the request
|ibm_audit_target.appname |Name of the application to be accessed or run on the target
|ibm_audit_target.authtype.failover |Name of failover authentication mechanism
|ibm_audit_target.authtype.original |Name of original authentication mechanism
|ibm_audit_target.credential.token |Token name of user performing action
|ibm_audit_target.credential.type |Token type of user performing action. BASIC, FORM or CLIENTCERT
|ibm_audit_target.host.address |Host and port of the target
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.method |Method being invoked on the target, i.e.,GET, POST
|ibm_audit_target.name |Context root
|ibm_audit_target.params |Names and values of any parameters sent to the target with the action
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.session |HTTP session ID
|ibm_audit_target.typeURI |Unique URI of the target of the event: `service/application/web`
|===

The following example shows a SECURITY_AUTHN_TERMINATE event:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"com.ibm.ws.webcontainer.security.fat.formlogout.audit",
    "ibm_datetime":"2018-07-24T17:03:24.122-0400",
    "ibm_sequence":"1521382001206_0000000000003",
    "ibm_threadId":"0000000a",
    "ibm_audit_eventName":"SECURITY_AUTHN_TERMINATE",
    "ibm_audit_eventSequenceNumber":"13",
    "ibm_audit_eventTime":"2018-07-24T17:02:50.813-0400",
    "ibm_audit_initiator.host.address":"127.0.0.1",
    "ibm_audit_initiator.host.agent":"Apache-HttpClient/4.1.2 (java 1.5)",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:com.ibm.ws.webcontainer.security.fat.formlogout.audit",
    "ibm_audit_observer.name":"SecurityService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"HTTP",
    "ibm_audit_target.credential.token":"user1",
    "ibm_audit_target.credential.type":"FORM",
    "ibm_audit_target.host.address":"127.0.0.1:8010",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:com.ibm.ws.webcontainer.security.fat.formlogout.audit",
    "ibm_audit_target.method":"POST",
    "ibm_audit_target.name":"/formlogin/ibm_security_logout",
    "ibm_audit_target.realm":"BasicRealm",
    "ibm_audit_target.session":"oNbsJSCYJrg2SPqzlL-5YxG",
    "ibm_audit_target.typeURI":"service/application/web"
}
----

=== SECURITY_AUTHZ

You can use the SECURITY_AUTHZ event to capture the audit information from Jacc web authorization, unprotected servlet authorization, Jacc EJB authorization, and EJB authorization. The following table provides the fields for the SECURITY_AUTHZ event and a description of each field.

.SECURITY_AUTHZ event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_initiator.host.address |Host address of the initiator of the event
|ibm_audit_initiator.host.agent |Name of monitoring agent associated with initiator
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `SecurityService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., HTTP and HTTPS, associated with the request
|ibm_audit_target.appname |Name of the application to be accessed or run on the target
|ibm_audit_target.credential.token |Token name of user performing action
|ibm_audit_target.credential.type |Token type of user performing action. BASIC, FORM or CLIENTCERT
|ibm_audit_target.ejb.beanname |EJB bean name (for EJB authorization)
|ibm_audit_target.ejb.method.interface |EJB method interface (for EJB authorization)
|ibm_audit_target.ejb.method.signature |EJB method signature (for EJB authorization)
|ibm_audit_target.ejb.module.name |EJB module name (for EJB authorization)
|ibm_audit_target.host.address |Host and port of the target
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.method |Method being invoked on the target, i.e.,GET, POST
|ibm_audit_target.name |Context root
|ibm_audit_target.params |Names and values of any parameters sent to the target with the action
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.role.names |Roles identified as being needed (if not permit all for EJBs)
|ibm_audit_target.session |HTTP session ID
|ibm_audit_target.typeURI |Unique URI of the target of the event: `service/application/web`
|===

The following example shows a successful WEB authorization event:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"com.ibm.ws.ejbcontainer.security.fat.audit",
    "ibm_datetime":"2018-07-16T14:38:32.111-0400",
    "ibm_sequence":"1502020152076_0000000000001",
    "ibm_threadId":"000000a2",
    "ibm_audit_eventName":"SECURITY_AUTHZ",
    "ibm_audit_eventSequenceNumber":"4",
    "ibm_audit_eventTime":"2018-07-16T14:37:56.259-0400",
    "ibm_audit_initiator.host.address":"127.0.0.1",
    "ibm_audit_initiator.host.agent":"Apache-HttpClient/4.1.2 (java 1.5)",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:com.ibm.ws.ejbcontainer.security.fat.audit",
    "ibm_audit_observer.name":"SecurityService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"HTTP",
    "ibm_audit_target.appname":"SecurityEJBServlet",
    "ibm_audit_target.credential.token":"user2",
    "ibm_audit_target.credential.type":"BASIC",
    "ibm_audit_target.host.address":"127.0.0.1:8010",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:com.ibm.ws.ejbcontainer.security.fat.audit",
    "ibm_audit_target.method":"GET",
    "ibm_audit_target.name":"/securityejb/SimpleServlet",
    "ibm_audit_target.params":"testInstance=ejb01&testMethod=runAsSpecified",
    "ibm_audit_target.realm":"BasicRealm",
    "ibm_audit_target.role.names":"[AllAuthenticated]",
    "ibm_audit_target.session":"NNLU_QCIGIOPHhKLWY1BxVJ",
    "ibm_audit_target.typeURI":"service/application/web"
}
----

The following example shows a successful EJB authorization:
[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"com.ibm.ws.ejbcontainer.security.fat.audit",
    "ibm_datetime":"2018-07-16T14:38:45.326-0400",
    "ibm_sequence":"1502020152076_0000000000002",
    "ibm_threadId":"000000a2",
    "ibm_audit_eventName":"SECURITY_AUTHZ",
    "ibm_audit_eventSequenceNumber":"5",
    "ibm_audit_eventTime":"2018-07-16T14:37:56.719-0400",
    "ibm_audit_initiator.host.address":"127.0.0.1",
    "ibm_audit_initiator.host.agent":"Apache-HttpClient/4.1.2 (java 1.5)",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:com.ibm.ws.ejbcontainer.security.fat.audit",
    "ibm_audit_observer.name":"SecurityService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"EJB Permit All",
    "ibm_audit_target.appname":"securityejb",
    "ibm_audit_target.credential.token":"user2",
    "ibm_audit_target.credential.type":"BASIC",
    "ibm_audit_target.ejb.beanname":"SecurityEJBA01Bean",
    "ibm_audit_target.ejb.method.interface":"Local",
    "ibm_audit_target.ejb.method.signature":"runAsSpecified:",
    "ibm_audit_target.ejb.module.name":"SecurityEJB.jar",
    "ibm_audit_target.host.address":"127.0.0.1:8010",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:com.ibm.ws.ejbcontainer.security.fat.audit",
    "ibm_audit_target.method":"runAsSpecified",
    "ibm_audit_target.name":"/securityejb/SimpleServlet",
    "ibm_audit_target.params":"testInstance=ejb01&testMethod=runAsSpecified",
    "ibm_audit_target.realm":"BasicRealm",
    "ibm_audit_target.session":"NNLU_QCIGIOPHhKLWY1BxVJ",
    "ibm_audit_target.typeURI":"service/application/web"
}
----

=== SECURITY_JMS_AUTHN

You can use the SECURITY_JMS_AUTHENTICATION event to capture the audit information from JMS authentication. The following table provides the fields for the SECURITY_JMS_AUTHENTICATION event and a description of each field.

.SECURITY_JMS_AUTHN event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_initiator.host.address |Host address of the initiator of the event
|ibm_audit_initiator.host.agent |Name of monitoring agent associated with initiator
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `JMSMessagingImplementation`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., and HTTP(S), JMS, EJB, etc. associated with the request
|ibm_audit_target.credential.token |Token name of user performing action
|ibm_audit_target.credential.type |Token type of user performing action
|ibm_audit_target.host.address |Host and port of the target
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.messaging.busname |Name of messaging bus
|ibm_audit_target.messaging.callType |Identifies if call is remote or local
|ibm_audit_target.messaging.engine |Name of messaging engine
|ibm_audit_target.messaing.loginType |Name of the login algorithm used, i.e., Userid+Password
|ibm_audit_target.messaging.remote.chainName |If the operation is remote, the name of the remote chain name
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.typeURI |Unique URI of the target of the event: `service/jms/messaging`
|===

The following example shows a successful SECURITY_JMS_AUTHN event:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"TestServer.audit",
    "ibm_datetime":"2018-07-19T18:34:72.599-0400",
    "ibm_sequence":"1587056204736_0000000000001",
    "ibm_threadId":"00000003",
    "ibm_audit_eventName":"SECURITY_JMS_AUTHN",
    "ibm_audit_eventSequenceNumber":"10",
    "ibm_audit_eventTime":"2018-07-19T18:33:51.135-0400",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:TestServer.audit",
    "ibm_audit_observer.name":"JMSMessagingImplementation",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"JMS",
    "ibm_audit_target.credential.token":"validUser",
    "ibm_audit_target.credential.type":"BASIC",
    "ibm_audit_target.host.address":"127.0.0.1:53166",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:TestServer.audit",
    "ibm_audit_target.messaging.busname":"defaultBus",
    "ibm_audit_target.messaging.callType":"remote",
    "ibm_audit_target.messaging.engine":"defaultME",
    "ibm_audit_target.messaging.loginType":"Userid+Password",
    "ibm_audit_target.messaging.remote.chainName":"InboundBasicMessaging",
    "ibm_audit_target.realm":"customRealm",
    "ibm_audit_target.typeURI":"service/jms/messagingEngine"
}
----

=== SECURITY_JMS_AUTHZ

You can use the SECURITY_JMS_AUTHZ event to capture the audit information from JMS authorization. The following table provides the fields for the SECURITY_JMS_AUTHZ event and a description of each field.

.SECURITY_JMS_AUTHZ event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_initiator.host.address |Host address of the initiator of the event
|ibm_audit_initiator.host.agent |Name of monitoring agent associated with initiator
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `JMSMessagingImplementation`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., and HTTP(S), JMS, EJB, etc. associated with the request
|ibm_audit_target.credential.token |Token name of user performing action
|ibm_audit_target.credential.type |Token type of user performing action
|ibm_audit_target.host.address |Host and port of the target
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.messaging.busname |Name of messaging bus
|ibm_audit_target.messaging.callType |Identifies if call is remote or local
|ibm_audit_target.messaging.destination |Name of messaging destination
|ibm_audit_target.messaging.engine |Name of messaging engine
|ibm_audit_target.messaging.jmsActions |List of actions the credential is allowed
|ibm_audit_target.messaging.jmsResource |Name of the JMS resource, i.e., QUEUE, TOPIC, TEMPORARY DESTINATION
|ibm_audit_target.messaging.operationType |Name of the operation that is being requested
|ibm_audit_target.messaging.remote.chainName |If the operation is remote, the name of the remote chain name
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.typeURI |Unique URI of the target of the event: `service/jms/messaging`
|===

The following example shows a successful SECURITY_JMS_AUTHZ event:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"TestServer.audit",
    "ibm_datetime":"2018-07-19T18:34:96.324-0400",
    "ibm_sequence":"1587056204736_0000000000002",
    "ibm_threadId":"00000003",
    "ibm_audit_eventName":"SECURITY_JMS_AUTHZ",
    "ibm_audit_eventSequenceNumber":"11",
    "ibm_audit_eventTime":"2018-07-19T18:33:51.247-0400",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:TestServer.audit",
    "ibm_audit_observer.name":"JMSMessagingImplementation",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"JMS",
    "ibm_audit_target.credential.token":"validUser",
    "ibm_audit_target.credential.type":"BASIC",
    "ibm_audit_target.host.address":"127.0.0.1:53166",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:TestServer.audit",
    "ibm_audit_target.messaging.busname":"defaultBus",
    "ibm_audit_target.messaging.callType":"remote",
    "ibm_audit_target.messaging.destination":"BANK",
    "ibm_audit_target.messaging.engine":"defaultME",
    "ibm_audit_target.messaging.jmsActions":"[BROWSE, SEND, RECEIVE]",
    "ibm_audit_target.messaging.jmsResource":"queue",
    "ibm_audit_target.messaging.operationType":"SEND",
    "ibm_audit_target.messaging.remote.chainName":"InboundBasicMessaging",
    "ibm_audit_target.realm":"customRealm",
    "ibm_audit_target.typeURI":"service/jms/messagingResource"
}
----


=== SECURITY_SAF_AUTHZ

You can use the SECURITY_SAF_AUTHZ event to capture the audit information from a request to the SAF Authorization Service API. The following table provides the fields for the SECURITY_SAF_AUTHZ event and a description of each field.

.SECURITY_SAF_AUTHZ event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `JMXService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_target.access.level |Level of access requested
|ibm_audit_target.applid |Identifier of APPL class
|ibm_audit_target.authorization.decision |True if user is authorized to access SAF resource in SAF Class, otherwise false
|ibm_audit_target.credential.token |Token name of user that performs action
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.racf.reason.code |RACF reason code
|ibm_audit_target.racf.return.code |RACF return code
|ibm_audit_target.saf.class |Name of SAF Class that contains SAF resource
|ibm_audit_target.saf.profile |Name of SAF resource user requests access to
|ibm_audit_target.saf.return.code |SAF return code
|ibm_audit_target.typeURI |Unique URI of the target of the event:  service/application/web
|ibm_audit_target.user.security.name |Username whose access to a SAF resource is being checked
|===

The following example shows a successful SECURITY_SAF_AUTHZ event:

[source,json]
----

{
   "type":"liberty_audit",
   "host":"sage.xyz.com",
   "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
   "ibm_serverName":"TestServer.audit",
   "ibm_datetime":"2018-07-19T18:34:96.324-0400",
   "ibm_sequence":"1587056204736_0000000000002",
   "ibm_threadId":"00000003",
   "ibm_audit_eventName": "SECURITY_SAF_AUTHZ",
   "ibm_audit_eventSequenceNumber": "4",
   "ibm_audit_eventTime": "2019-04-29T19:45:16.161+0000",
   "ibm_audit_observer.id": "websphere: sage.xyz.com:/opt/ol/wlp/usr/:TestServer.audit",
   "ibm_audit_observer.name": "SecurityService",
   "ibm_audit_observer.typeURI": "service/server",
   "ibm_audit_outcome": "success",
   "ibm_audit_target.access.level": "READ",
   "ibm_audit_target.applid": "BBGZDFLT",
   "ibm_audit_target.authorization.decision": "true",
   "ibm_audit_target.credential.token": "WSGUEST",
   "ibm_audit_target.id": "websphere: sage.xyz.com:/opt/ol/wlp/usr/:TestServer.audit",
   "ibm_audit_target.racf.reason.code": "0",
   "ibm_audit_target.racf.return.code": "0",
   "ibm_audit_target.saf.class": "EJBROLE",
   "ibm_audit_target.saf.profile": "BBGZDFLT.AUTHSERV",
   "ibm_audit_target.saf.return.code": "0",
   "ibm_audit_target.typeURI": "service/application/web",
   "ibm_audit_target.user.security.name": "WSGUEST"
}
----

=== SECURITY_SAF_AUTHZ_DETAILS

You can use the SECURITY_SAF_AUTHZ_DETAILS event to capture the audit information from a SAF Authorization event that is configured to throw a SAF Authorization Exception on failure. The following table provides the fields for the SECURITY_SAF_AUTHZ_DETAILS event and a description of each field.

.SECURITY_SAF_AUTHZ_DETAILS event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `JMXService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_target.access.level |Level of access requested
|ibm_audit_target.applid |Identifier of APPL class
|ibm_audit_target.authorization.decision |True if user is authorized to access SAF resource in SAF Class, otherwise false
|ibm_audit_target.credential.token |Token name of user that performs action
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.racf.reason.code |RACF reason code
|ibm_audit_target.racf.return.code |RACF return code
|ibm_audit_target.saf.class |Name of SAF Class that contains SAF resource
|ibm_audit_target.saf.profile |Name of SAF resource user requests access to
|ibm_audit_target.saf.return.code |SAF return code
|ibm_audit_target.typeURI |Unique URI of the target of the event:  service/application/web
|ibm_audit_target.user.security.name |Username whose access to a SAF resource is being checked
|===

[source,json]
----

{
   "type":"liberty_audit",
   "host":"sage.xyz.com",
   "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
   "ibm_serverName":"TestServer.audit",
   "ibm_datetime":"2018-07-19T18:34:96.324-0400",
   "ibm_sequence":"1587056204736_0000000000002",
   "ibm_threadId":"00000003",
   "ibm_audit_eventName": "SECURITY_SAF_AUTHZ",
   "ibm_audit_eventSequenceNumber": "5",
   "ibm_audit_eventTime": "2019-04-30T13:59:11.688+0000",
   "ibm_audit_observer.id": "websphere: sage.xyz.com:/opt/ol/wlp/usr/:TestServer.audit",
   "ibm_audit_observer.name": "SecurityService",
   "ibm_audit_observer.typeURI": "service/server",
   "ibm_audit_outcome": "success",
   "ibm_audit_target.access.level": "READ",
   "ibm_audit_target.applid": "BBGZDFLT",
   "ibm_audit_target.authorization.decision": "true",
   "ibm_audit_target.credential.token": "WSGUEST",
   "ibm_audit_target.id": "websphere: sage.xyz.com:/opt/ol/wlp/usr/:TestServer.audit",
   "ibm_audit_target.racf.reason.code": "0",
   "ibm_audit_target.racf.return.code": "0",
   "ibm_audit_target.saf.class": "EJBROLE",
   "ibm_audit_target.saf.profile": "BBGZDFLT.AUTHSERV",
   "ibm_audit_target.saf.return.code": "0",
   "ibm_audit_target.typeURI": "service/application/web",
   "ibm_audit_target.user.security.name": "RSTUSR1"
}
----

=== JMX_MBEAN_REGISTER

You can use the JMX_MBEAN_REGISTER event to capture the audit information from JMX MBean registration. The following table provides the fields for the JMX_MBEAN_REGISTER event and a description of each field.

.JMX_MBEAN_REGISTER event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_initiator.host.address |Host address of the initiator of the event
|ibm_audit_initiator.host.agent |Name of monitoring agent associated with initiator
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `JMXService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., and HTTP(S), JMS, EJB, etc. associated with the request, or the state behind the outcome
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.jmx.mbean.action |MBean action being performed: register, unregister
|ibm_audit_target.jmx.mbean.name |Name of the MBean being acted upon
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.typeURI |Unique URI of the target of the event: `server/mbean`
|===

The following example shows a successful JMX_MBEAN_REGISTRATION event:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"jmxConnectorAuditServer",
    "ibm_datetime":"2018-07-25T18:43:28.130-0400",
    "ibm_sequence":"1592033306612_0000000000003",
    "ibm_threadId":"0000003f",
    "ibm_audit_eventName":"JMX_MBEAN_REGISTER",
    "ibm_audit_eventSequenceNumber":"12",
    "ibm_audit_eventTime":"2018-07-25T18:42:40.772-0400",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:jmxConnectorAuditServer",
    "ibm_audit_observer.name":"JMXService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"Successful MBean registration",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:jmxConnectorAuditServer",
    "ibm_audit_target.jmx.mbean.action":"registerMBean",
    "ibm_audit_target.jmx.mbean.name":"web:name=ClassLoaderMBean",
    "ibm_audit_target.realm":"QuickStartSecurityRealm",
    "ibm_audit_target.typeURI":"server/mbean"
}
----

=== JMX_MBEAN

You can use the JMX_MBEAN event to capture the audit information from JMX_MBEAN operations. The following table provides the fields for the JMX_MBEAN event and a description of each field.

.JMX_MBEAN event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_initiator.host.address |Host address of the initiator of the event
|ibm_audit_initiator.host.agent |Name of monitoring agent associated with initiator
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `JMXService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., and HTTP(S), JMS, EJB, etc. associated with the request, or the state behind the outcome
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.jmx.mbean.action |MBean action being performed: query, create, invoke
|ibm_audit_target.jmx.mbean.name |Name of the MBean being acted upon
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.typeURI |Unique URI of the target of the event: `server/mbean`
|===

The following example shows a successful query of an MBean JMS_MBEAN event:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"jmxConnectorAuditServer",
    "ibm_datetime":"2018-07-25T18:43:02.822-0400",
    "ibm_sequence":"1592033306612_0000000000002",
    "ibm_threadId":"0000003f",
    "ibm_audit_eventName":"JMX_MBEAN",
    "ibm_audit_eventSequenceNumber":"24",
    "ibm_audit_eventTime":"2018-07-25T18:42:44.119-0400",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:jmxConnectorAuditServer",
    "ibm_audit_observer.name":"JMXService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"Successful query of MBeans",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:jmxConnectorAuditServer",
    "ibm_audit_target.jmx.mbean.action":"queryMBeans",
    "ibm_audit_target.jmx.mbean.name":"java.lang:type=Threading",
    "ibm_audit_target.realm":"QuickStartSecurityRealm",
    "ibm_audit_target.typeURI":"server/mbean"
}
----

=== JMX_MBEAN_ATTRIBUTES

You can use the JMX_MBEAN_ATTRIBUTES event to capture the audit information from JMX MBEAN attribute operations. The following table provides the fields for the JMX_MBEAN_Attributes event and a description of each field.

.JMX_MBEAN_ATTRIBUTES event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_initiator.host.address |Host address of the initiator of the event
|ibm_audit_initiator.host.agent |Name of monitoring agent associated with initiator
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `JMXService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., and HTTP(S), JMS, EJB, etc. associated with the request, or the state behind the outcome
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.jmx.mbean.action |MBean action being performed on the MBean attribute(s). getAttribute(s) and setAttributes(s) are supported.
|ibm_audit_target.jmx.mbean.attribute.names |Name of the attributes(s) being acted upon
|ibm_audit_target.jmx.mbean.name |Name of the MBean being acted upon
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.typeURI |Unique URI of the target of the event: `server/mbean`
|===

The following example shows a successful JMX_MBEAN_ATTRIBUTES event:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"jmxConnectorAuditServer",
    "ibm_datetime":"2018-07-25T18:43:92.347-0400",
    "ibm_sequence":"1592033306612_0000000000008",
    "ibm_threadId":"0000002c",
    "ibm_audit_eventName":"JMX_BEAN_ATTRIBUTES",
    "ibm_audit_eventSequenceNumber":"43",
    "ibm_audit_eventTime":"2018-07-25T18:42:51.070-0400",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:jmxConnectorAuditServer",
    "ibm_audit_observer.name":"JMXService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"Successful retrieval of MBean attributes",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:jmxConnectorAuditServer",
    "ibm_audit_target.jmx.mbean.action":"getAttributes",
    "ibm_audit_target.jmx.mbean.attribute.names":"[TotalStartedThreadCount = 132][CurrentThreadCpuTimeSupported = true]",
    "ibm_audit_target.jmx.mbean.name":"java.lang:type=Threading",
    "ibm_audit_target.realm":"QuickStartSecurityRealm",
    "ibm_audit_target.typeURI":"server/mbean"
}
----

=== JMX_NOTIFICATION

You can use the JMX_NOTIFICATION event to capture the audit information from JMX notifications. The following table provides the fields for the JMX_NOTIFICATION event and a description for each field.

.JMX_NOTIFICATION event fields
[cols=",",options="header",]
|===
|FIELDS |DESCRIPTION
|type |A string that identifies the type of event
|host |Host name of the server that was the source of the event
|ibm_userDir |User directory of the server that was the source of the event.
|ibm_serverName |Server name of the server that was the source of the
event.
|ibm_datetime |Time at which the event occurred.
|ibm_sequence |Sequence number of event (useful for sorting records with the same time stamp).
|ibm_threadId |Thread ID in the log line, for example, 00000015. The thread ID is a string and not a number.
|ibm_audit_eventName |Name of the audit event
|ibm_audit_eventSequenceNumber |Sequence number of the audit event
|ibm_audit_eventTime |Time the event occurred
|ibm_audit_observer.id |Identifier of the observer of the event
|ibm_audit_observer.name |Name of the observer of the event: `JMXService`
|ibm_audit_observer.typeURI |Unique URI of the observer of the event: `service/server`
|ibm_audit_Outcome |Outcome of the event
|ibm_audit_reason.reasonCode |A value indicating the underlying success or error code for the outcome. In general, a value of 200 means success
|ibm_audit_reason.reasonType |A value indicating the underlying mechanism, i.e., and HTTP(S), JMS, EJB, etc. associated with the request, or the state behind the outcome
|ibm_audit_target.id |Identifier of the target of the action
|ibm_audit_target.jmx.mbean.action |MBean action being performed on the MBean attribute(s)
|ibm_audit_target.jmx.notification.filter |Name of the notification filter
|ibm_audit_target.jmx.notification.listener |Name of the notification listener
|ibm_audit_target.jmx.notification.name |Name of the notification
|ibm_audit_target.realm |Realm name associated with the target
|ibm_audit_target.typeURI |Unique URI of the target of the event: `server/mbean/notification`
|===

The following example shows a successful JMX_NOTIFICATION:

[source,json]
----
{
    "type":"liberty_audit",
    "host":"sage.xyz.com",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"jmxConnectorAuditServer",
    "ibm_datetime":"2018-07-25T19:28:34.664-0500",
    "ibm_sequence":"1503082313712_0000000000003",
    "ibm_threadId":"000000a8",
    "ibm_audit_eventName":"JMX_NOTIFICATION",
    "ibm_audit_eventSequenceNumber":"37",
    "ibm_audit_eventTime":"2018-07-25T19:27:24.303-0500",
    "ibm_audit_observer.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:jmxConnectorAuditServer",
    "ibm_audit_observer.name":"JMXService",
    "ibm_audit_observer.typeURI":"service/server",
    "ibm_audit_outcome":"success",
    "ibm_audit_reason.reasonCode":"200",
    "ibm_audit_reason.reasonType":"Successful add of notification listener",
    "ibm_audit_target.id":"websphere: sage.xyz.com:/opt/ol/wlp/usr/:jmxConnectorAuditServer",
    "ibm_audit_target.jmx.mbean.action":"addNotificationListener",
    "ibm_audit_target.jmx.notification.filter":"com.ibm.ws.jmx.connector.server.rest.notification.ClientNotificationFilter",
    "ibm_audit_target.jmx.notification.listener":"com.ibm.ws.jmx.connector.server.rest.notification.ClientNotificationListener",
    "ibm_audit_target.jmx.notification.name":"web:name=Notifier1",
    "ibm_audit_target.realm":"QuickStartSecurityRealm",
    "ibm_audit_target.typeURI":"server/mbean/notification"
}
----



