// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Kerberos authentication with Open Liberty
:seo-description: You can configure your Open Liberty server to use Kerberos credentials to authenticate to to protected resources such as JDBC data sources, LDAP user registries, and more.
:page-layout: general-reference
:page-type: general
= Kerberos authentication with Open Liberty

Kerberos is a network authentication protocol through which a client and server can authenticate one another by communicating with a trusted third-party Key Distribution Center (KDC). You can configure your Open Liberty server to use Kerberos credentials to authenticate to protected resources such as JDBC data sources, LDAP user registries, and more.

== Global Kerberos configuration for Open Liberty

Kerberos authentication in Open Liberty builds on the https://docs.oracle.com/en/java/javase/11/docs/api/jdk.security.auth/com/sun/security/auth/module/Krb5LoginModule.html[Kerberos Login Module] and the Java Generic Security Service (JGSS) API that are  provided by the Java SDK.

The optional xref:reference:config/kerberos.adoc[kerberos element] provides configuration options for any Open Liberty features that use Kerberos credentials. If you have any Kerberos-enabled features configured for your server, you can specify this element in your `server.xml` file, as shown in the following example:

[source,xml]
----
<featureManager>
  <feature>jdbc-4.2</feature>
</featureManager>

<kerberos keytab="${server.config.dir}/security/krb5.keytab" configFile="${server.config.dir}/security/krb5.conf"/>
----

The `keytab` and `configFile` attributes are both optional. If you don't specify these attributes, Open Liberty resolves their values according to the following priority:

1. The default locations that are defined by the Java SDK, such as the `{user.home}/krb5.keytab` file or a location that is specified by Java SDK-defined system properties
2. The default locations that are defined by the operating system, such as the `/etc/krb5.keytab` file or a location that is specified by operating system-defined environment variables

On the Windows operating system, the default Kerberos configuration file name is `krb5.ini`. On other operating systems, the file name is `krb5.conf`.

This example shows a Kerberos configuration for the xref:reference:feature/jdbc-4.2.adoc[Java Database Connectivity feature]. Several Open Liberty features support the `kerberos` element. To determine whether a feature supports this element, see the list of feature configuration elements in the reference documentation for the feature.


== See also
- xref:kerberos-authentication-jdbc.adoc[Kerberos authentication for JDBC data sources]
- Placeholder: Kerberos authentication for LDAP user registries
- https://web.mit.edu/kerberos/[Kerberos: The Network Authentication Protocol]
