// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title:
:seo-description:
:page-layout: general-reference
:page-type: general
= Kerberos Authentication for JDBC data sources

Kerberos is a network authentication protocol through which a client and server can authenticate one another by communicating with a trusted third-party Key Distribution Center (KDC). You can configure your Open Liberty server to use Kerberos credentials to authenticate to a database that is backed by a Java Database Connectivity (JDBC) data source.

Applications that run on an Open Liberty server might need to access protected resources in a database, such as user account information or sales transaction records. In cases where such a database is protected by Kerberos authentication, your Open liberty server can  supply the necessary credentials to access protected resources and confirm the authenticity of the database.

== Global Kerberos configuration for Open Liberty

Kerberos authentication in Open Liberty builds on the https://docs.oracle.com/en/java/javase/11/docs/api/Java SDK.security.auth/com/sun/security/auth/module/Krb5LoginModule.html[Kerberos Login Module] and Java Generic Security Service (JGSS) API that are  provided by the Java SDK.

The optional xref:reference:config/kerberos.adoc[kerberos] element provides configuration options for any Open Liberty features that use Kerberos credentials. If you have any Kerberos-enabled features configured for your server, you can specify this element in your `server.xml` file, as shown in the following example:

[source,xml]
----
<featureManager>
  <jdbc-4.2>
</featureManager>

<kerberos keytab="${server.config.dir}/security/krb5.keytab" configFile="${server.config.dir}/security/krb5.conf"/>
----

This example shows a Kerberos configuration for the xref:reference:feature/jdbc-4.2.adoc[Java Database Connectivity feature]. Several different features support the `kerberos` element. To determine whether a feature supports this element, see the feature documentation.

The `keytab` and `configFile` attributes are both optional. If you do not specify these attributes, Open Liberty resolves their values according to the following priority:

1. The default locations that are defined by the Java SDK, such as the `{user.home}/krb5.keytab` file or a location that is specified by Java SDK-defined system properties
2. The default locations that are defined by the operating system, such as the `/etc/krb5.keytab` file or a location that is specified by OS-defined environment variables

On the Windows operating system, the default Kerberos config file name is `krb5.ini`. On other operating systems, the file name is `krb5.conf`.

== Kerberos configuration for JDBC data sources

To configure Kerberos authentication for JDBC data sources, you must enable the xref:reference:feature/jdbc-4.2.adoc[Java Database Connectivity feature]. For more information about JDBC data source connections, see xref:relational-database-connections-JDBC.adoc#_data_source_configuration[Data source configuration].
After the Kerberos global configuration is defined, a Kerberos principal can be configured on an `authData` element in the `server.xml` file, as shown in the following example:

[source,xml]
----
<authData id="myKerberosAuth" krb5Principal="krbUser" krb5TicketCache="security/krb5cc_krbUser"/> // <!--1-->

<library id="db2DriverLib">
  <fileset dir="db2"/>
</library>

<dataSource jndiName="jdbc/krb/basic" containerAuthDataRef="myKerberosAuth"> // <!--2-->
  <jdbcDriver libraryRef="db2DriverLib"/>
  <properties.db2.jcc databaseName="${DB2_DBNAME}" serverName="${DB2_HOSTNAME}" portNumber="${DB2_PORT}"/>
</dataSource>
----

<1> The `krb5TicketCache` attribute is optional. If this attribute is not specified, Open Liberty checks the default Kerberos credential cache location of the Java SDK or the operating system.
<2> The `containerAuthDataRef` attribute references the `authData` element to authenticate the database connection.

Optionally, you can specify the `recoveryAuthDataRef` attribute on the `dataSource` element to use alternative values for the  `krb5Principal` and `krb5TicketCache` attributes for authentication during XA recovery. If the `recoveryAuthDataRef` attribute is not specified, the `authData` element that is referenced by the `containerAuthDataRef` attribute is used for authentication during XA recovery.

== Compatibility with SPNEGO authentication

Open Liberty also supports xref:configuring-spnego-authentication.adoc[SPNEGO authentication] for web authentication and JDBC data source authentication. To use SPNEGO authentication with a JDBC datasource, it is not required to configure a `containerAuthDataRef` or `recoveryAuthDataRef` on your `datasource` element. The `kerberos` element is optional, but can be used to customize `keytab` file and `configFile` file locations that are used for SPNEGO authentication.

For example, the following configuration enables a JDBC data source to use SPNEGO authentication to an IBM Db2 data source:

[source,xml]
----
<featureManager>
  <feature>jdbc-4.2</feature>
  <feature>spnego-1.0</feature>
  <feature>appSecurity-2.0</feature>
</featureManager>

<spnego servicePrincipalNames="HTTP/my.spnego.server.com" authFilterRef="myAuthFilter"/>
<authFilter id="myAuthFilter">
  <requestUrl urlPattern="/MySpnegoServlet" matchType="contains"/>
</authFilter>

<kerberos keytab="security/krb5.keytab" configFile="security/krb5.conf"/>

<library id="db2DriverLib">
  <fileset dir="${server.config.dir}/db2"/>
</library>

<dataSource jndiName="jdbc/spnegoAuth">
  <jdbcDriver libraryRef="db2DriverLib"/>
  <properties.db2.jcc databaseName="${DB2_DBNAME}" serverName="${DB2_HOSTNAME}" portNumber="${DB2_PORT}"/>
</dataSource>
----

== See also
- xref:configuring-spnego-authentication.adoc[Configuring SPNEGO authentication]
- xref:relational-database-connections-JDBC.adoc[Relational database connections with JDBC]
- https://web.mit.edu/kerberos/[Kerberos]
