// Copyright (c) 2024 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//    https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
// IBM Corporation
//
:page-layout: general-reference
:page-type: general
:page-description: The Liberty-Kafka connector offers a range of properties to fine-tune its operation. You can set these properties on the Liberty-Kafka connector to define certain behaviors during operation.
:page-categories: MicroProfile Reactive Messaging
:seo-title: Liberty-Kafka connector options and channel properties
:seo-description: The Liberty-Kafka connector offers a range of properties to fine-tune its operation. You can set these properties on the Liberty-Kafka connector to define certain behaviors during operation.


[#connectoroptionschannelprop]
= Liberty-Kafka connector options and channel properties

The Liberty-Kafka connector offers a range of properties to fine-tune its operation. You can set these properties on the Liberty-Kafka connector to define certain behaviors during operation.

You can use all these options as attributes on either the connector or a channel that uses the Liberty-Kafka connector. If you specify the option on both the channel and the connector, the channel takes precedence.

To secure communication with Kafka brokers, set the necessary security properties in the xref:microprofile-config-properties.adoc#react[microprofile-config.properties] file.

==  Managing incoming channels with Liberty-Kafka connector properties

The Liberty Kafka connector, which is designed for integration with the MicroProfile Reactive Messaging framework, provides a robust solution for managing incoming channels that connect to Kafka topics. The Liberty Kafka connector offers a set of properties that you can use to fine-tune how messages are received from Kafka topics. These properties are essential for controlling various aspects of message processing, such as specifying the topics to subscribe to, managing acknowledgment strategies, and handling message acknowledgment limits. 


.Properties supported by the Liberty-Kafka connector for incoming channels
[cols="a,a,a",width="100%"]
|===
|Property Name |Default |Description

|topic
|The name of the channel.
|The Kafka topic that the channel is to either send or receive messages from.

|unacked.limit
|Defaults to the value of `max.poll.records` if set, or to 500.
|The number outstanding unacknowledged messages. 
 {empty} +
 If this limit is reached, the connector stops retrieving records from Kafka until some messages are acknowledged.

|fast.ack
|- MicroProfile Reactive Messaging 1.0 - `False`
 {empty} +
 - MicroProfile Reactive Messaging 3.0 - `true`
|Defines the acknowledge behavior of the Liberty-Kafka connector within the MicroProfile Reactive Messaging framework for `incoming` channels in relation to activities with the Kafka topic.
 {empty} +
If the value of `fast.ack` is `false`, the acknowledgment is not reported as complete until the partition offset is committed to the Kafka broker. If an error occurs during this process, then the acknowledgment is reported as failed.
 {empty} +
If the value of `fast.ack` is `true`, and the acknowledgment is reported as complete when the Kafka connector receives the acknowledgment signal. For more information, see <<#fastack,fast.ack>>.

|context.service
|If the `concurrent-x.y` feature is enabled. the default context service is used.
 {empty} +
 If the concurrent feature is not enabled, the built in Liberty context service is used with a set list of context types to capture and apply around asynchronous tasks.
|Enabling the concurrent feature is needed for the `context.service` option to be effective for the Liberty-Kafka connector. 
 {empty} +
This setting specifies the Context Service that is used for Asynchronous tasks.

|<any other property>
|Uses the Kafka Client default
|All other properties are passed directly as config parameters to the KafkaConsumer API. A list of required and optional properties can be found in the http://kafka.apache.org/documentation.html#consumerconfigs[Kafka documentation].

|===


[#fastack]
=== fast.ack
Properties like `fast.ack` allow for control over message acknowledgment processes, improving the efficiency of message processing. 

In the following example, in the `microprofile-config.properties` file of the application, the `fast.ack` setting is defaulted to `false` for the connector, affecting all channels in the application. However, for a distinct incoming channel called `foo`, this setting is overridden to `true`. This alteration favors a quicker acknowledgment approach, which enhances the handling performance for messages that arrive on this channel.

----
mp.messaging.connector.liberty-kafka.fast.ack=false

mp.messaging.incoming.foo.connector=liberty-kafka
mp.messaging.incoming.foo.fast.ack=true
----


==  Managing outgoing channels with Liberty-Kafka connector properties
The Liberty Kafka connector is a vital tool for applications that are integrating with Kafka, especially for managing outgoing messages. It offers a suite of configurable properties that are designed to fine-tune how messages are dispatched to Kafka topics. The `topic` property dictates the destination topic for your messages, while the `context.service` property enhances performance by managing asynchronous tasks efficiently. Using these properties, you can optimize the performance and reliability of outgoing message channels. By customizing the context service for different parts of an application, you can isolate specific operations for better performance management. This control over outgoing messages not only enhances application responsiveness but also secures a robust and flexible integration with Kafka that can meet complex requirements.

.Properties supported by the Liberty-Kafka connector for outgoing channels
[cols="a,a,a",width="100%"]
|===
|Property Name |Default |Description

|topic
|The name of the channel.
|The Kafka topic that the channel is to either send or receive messages from.


|context.service
|If the `concurrent-x.y` feature is enabled. the default context service is used.
 {empty} +
 If the concurrent feature is not enabled, the built in Liberty context service is used with a set list of context types to capture and apply around asynchronous tasks.
|Enabling the concurrent feature is needed for the `context.service` option to be effective for the Liberty-Kafka connector. 
 {empty} +
This setting specifies the Context Service that is used for Asynchronous tasks. For more information, see <<#contextservice,context.service>>.

|<any other property>
|Uses the Kafka Client default
|All other properties are passed directly as config parameters to the KafkaProducer API. A list of required and optional properties can be found in the http://kafka.apache.org/documentation.html#producerconfigs[Kafka documentation].

|===

[#contextservice]
=== context.service
The `context.service` attribute specifies the Context Service for asynchronous operations, critical for performance tuning. 
Context Services that are defined within the application itself cannot be used with the Liberty-Kafka connector. 

In the following example, the `server.xml` file defines three different context services, each with a unique identifier (`rst`, `uvw`, and `xyz`).
----
<contextService id=“rst”/>
<contextService id=“uvw”/>
<contextService id=“xyz”/>
----

The `microprofile-config.properties` file is part of the application's configuration and specifies how MicroProfile features should be used within the application.
----
mp.messaging.connector.liberty-kafka.context.service=rst

mp.messaging.incoming.def.connector=liberty-kafka
mp.messaging.incoming.foo.connector=liberty-kafka
mp.messaging.incoming.foo.context.service=uvw
mp.messaging.outgoing.bar.connector=liberty-kafka
mp.messaging.outgoing.bar.context.service=xyz
----

In the example, the property `mp.messaging.connector.liberty-kafka.context.service=rst` indicates that the Kafka connector that is used for handling messaging between services uses the `rst` context service by default for its operations.

The application has three channels (`def`, `foo`, and `bar`), which are logical endpoints for incoming and outgoing messages. The configuration for these channels specifies which Kafka connector to use (`liberty-kafka`) and for two of the channels (`foo` and `bar`), overrides the default context service with their own (`uvw` and `xyz`, respectively).
The `def` channel does not specify its own `context.service`, so it inherits the default one (`rst`) defined at the connector level.

By defining separate context services, the application can isolate certain operations or configurations, which can be useful in complex applications or during integration with external systems.
These configurations demonstrate the flexibility and control that you have over message processing in Open Liberty applications.