// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general

= Develop with Liberty Tools

Liberty Tools are a set of extensions for the Eclipse IDE, Visual Studio Code, and Intellij IDEA development environments. These extensions enable fast, iterative development with Liberty dev mode and Maven or Gradle build automation tools. 

Liberty Tools automatically detects any projects that specify the Liberty Maven plug-in or Liberty Gradle plug-in in the `pom.xl` file. These projects are added to a special Liberty dashboard view in Eclipse IDE or Visual Studio Code or the Liberty Tools window in Intellij IDEA. From there, you can access a command menu to manage your projects.  

Liberty Tools also provides helpful, time-saving features such as code completion, hover descriptions, and configuration diagnostics for the MicroProfile API, Jakarta EE API, and Liberty configuration files.

== Develop, test, and debug in your editor

You can use Liberty Tools extensions to stop, start or interact with Liberty dev mode from the Liberty dashboard view in Eclipse IDE or Visual Studio Code or the Liberty Tools window in Intellij IDEA. Liberty dev mode automatically detects, recompiles, and deploys code changes whenever you save a new change. It also runs unit and integration tests on demand and can attach a debugger to the running server to step through your code at any time. 

Liberty tools brings these dev mode features directly into the command menu for the Liberty projects in your editor. With a just few clicks, you can start and stop your Liberty application, run tests, and view test reports.

== Configure with core language support for Liberty, MicroProfile, and Jakarta EE 

Liberty tools helps you quickly and easily edit your application and configuration files by providing language support features for MicroProfile, Jakarta EE, and Liberty configuration files.

The following language support features are available for select Liberty configuration files.

* Code completion: start typing a Liberty property, variable, or XML configuration to view a list of possible options
* Hover support: hover your cursor over Liberty properties, variables, or XML configuration to view a description
* Configuration diagnostics: diagnostics highlight potential problems in your configuration, such as invalid values.

These features are available for the following Liberty configuration files.

* `server.env`
* `bootstrap.properties`
* `server.xml` and any XML files that are referenced through the `include` element in the `server.xml` file.
* Any XML files that contain the `server` root element and exist in the `src/main/liberty/config`, `configDropins/overrides`, `configDropins/defaults`, `usr/shared/config`, or `usr/servers` directory.

Language support for MicroProfile includes the following features.



== Try it out