= Linking a Repository to a Provider

When there is only one Jakarta Data provider that handles the type of entity, it is unnecessary for the Repository to specify which Jakarta Data provider to use.

However, when multiple Jakarta Data providers coexist in a system and handle the same entity type, the Repository must specify a provider name to disambiguate which Jakarta Data provider is to be used.

The built-in Jakarta Data provider for Liberty uses the provider name, *Liberty*. It is included in the `data-1.0` feature.

Alternatively, third-party Jakarta Data providers can be used in Liberty by including the `dataContainer-1.0` feature which will only provide the Jakarta Data API (without the built-in Jakarta Data Provider).


== Hibernate ORM Provider Name example

[source,java]
----
@Repository(provider = "Hibernate", dataStore = "MyPersistenceUnit")
public interface Employee extends CrudRepository<Employee, Long> {
}
----


=== Eclipse JNoSQL Provider Name example

[source,java]
----
@Repository(provider = "Eclipse_JNoSQL")
public interface Cars extends BasicRepository<Car, String> {
}
----


== Built-in Provider Name example

[source,java]
----
@Repository(provider = "Liberty", dataStore = "java:app/env/jdbc/MyDataSourceRef")
public interface Products extends CrudRepository<Product, String> {
}
----

