// Copyright (c) 2013, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
= Logstash collector events reference list


You can use the xref:reference:logstashCollector-1.0.adoc[Logstash collector feature] to send log events to a remote Logstash server so that you can manage and visualize them with products such as Elasticsearch and Kibana. Each type of log event has its own set of fields that you can use to customize your Kibana dashboard.

If your Open Liberty server is deployed in an environment that manages your logs, such as a Kubernetes cluster, the managing agent can transfer your log data to Logstash. However, some server configurations cannot use an external agent to manage log data. In these cases, you can use the Open Liberty Logstash collector feature to internally collect your log data at run time and send it to a Logstash server. For more information, see xref:forwarding-logs-logstash.adoc[Forwarding logs and events to Logstash with Logstash collector].

The Logstash collector feature captures log events at run time, breaks them into fields, and securely forwards them to the configured Logstash log collection server. You can configure the feature to send one or more of the following types of data:


- <<Message events,Message log events>>
- <<Trace events,Trace log events>>
- <<HTTP access log events,HTTP access log events>> from the Open Liberty server
- <<FFDC events,First failure data capture (FFDC) log events>>
- <<Garbage collection events,Garbage collection events>> for IBM JDKs
- <<Audit events,Audit events>>


== Event types

The Logstash collector feature sends each event as a set of field name-value pairs. In addition to a set of common fields that are available for all event types, each type of event has its own unique fields. These fields are useful when you xref:forwarding-logs-logstash.adoc[create your own Kibana dashboards].

In addition to the default log and trace framework, the Logstash collector feature forwards message events and trace events when binary logging is enabled.
For more information about log event types, see xref:log-management.adoc[Log management].

=== Common event fields


The following table lists the fields that are common and present in all events. Column one contains the name of the field and column two contains the description of the field.

.Common event fields
[%header,cols="3,6"]
|===

|Field name
|Description of field

|`type`
|A string that identifies the type of event

|`datetime`
|Time at which the event occurred

|`hostName`

|The hostname of the server that was the source of the event. For more information, see <<Server and host names in virtualized environments>>.

|`wlpUserDir`
|The user directory of the server that was the source of the event, for example, `D:\wlp\usr`

|`serverName`
|The server name of the server that was the source of the event, For more information, see <<Server and host names in virtualized environments>>.

|`sequence`
|The sequence number of the event, which is useful for sorting records with the same time stamp

|`tags`
|The tags that are associated with the server from which the event originated

|===

=== Audit events


The following table lists the fields that are available for the audit event type, which is specified as `type: liberty_audit`. Column one contains the name of the field and column two contains a description of the field.

.Audit event fields
[%header,cols="3,6"]
|===

|Field name
|Description of field

|`threadId`
|	The thread ID of the Audit incident

|===

=== Message events

The following table lists the fields that are available for the message event type, which is specified as `type: liberty_message`. Column one contains the name of the field and column two contains the description of the field.

.Message event fields
[%header,cols="3,6"]
|===

|Field name
|Description of field

|`severity`
|Indicates the severity of the event by using one of the following codes: F = Fatal, E = Error, W = Warning, A = Audit, I = Info, O = SystemOut, R = SystemErr

|`messageId`
|The message ID in the log line, which can be used to find out specific types of errors, for example, `SRVE0250I`


|`methodName`
|The method name from the log record

|`className`
|The class name from the log record

|`loggerName`
|The logger name from the log record

|`threadId`
|The thread ID in the log line, for example, `00000015`. The thread ID is a string and not a number.

|`message`
|The message from the log record, starting with the message ID

|===

=== Trace events

The following table lists the fields that are available for the trace event type, which is specified as `type: liberty_trace`. Column one contains the name of the field and column two contains a description of the field.

.Trace event fields
[%header,cols="3,6"]
|===

|Field name
|Description of field

|`severity`
|Indicates the severity of the event by using one of the following codes: F = Fatal, E = Error, W = Warning, A = Audit, I = Info, O = SystemOut, R = SystemErr

|`methodName`
|The method name from the log record

|`className`
|The class name from the log record

|`loggerName`
|The logger name from the log record

|`threadId`
|The thread ID in the log line, for example, `00000015`. The thread ID is a string and not a number.

|`message`
|The message from the log record, starting with the message ID

|===

=== HTTP access log events

The following table lists the fields that are available for the HTTP access log event type, which is specified as `type: liberty_accesslog`. Column one contains the name of the field and column two contains a description of the field.

.HTTP access log event fields
[%header,cols="3,6"]
|===

|Field name
|Description of field

|`uriPath`
|The path information for the requested URL. This path information does not contain the query parameters, for example, `/pushworksserver/push/apps/tags`.

|`requestMethod`
|The HTTP verb, for example, `GET`

|`remoteHost`
|The remote host IP address, for example, `127.0.0.1`

|`userAgent`
|The `userAgent` value in the request

|`requestProtocol`
|The protocol type, for example, HTTP/1.1

|`queryString`
|The string that represents the query string from the HTTP request, for example, `color=blue&size=large`

|`bytesReceived`
|The bytes received in the URL, for example, `94`

|`responseCode`
|The HTTP response code, for example, `200`

|`elapsedTime`
|The time that is taken to serve the request, in microseconds

|`requestHost`
|The request host IP address, for example, `127.0.0.1`

|`requestPort`
|The port number of the request

|===

=== FFDC events
The following table lists the fields that are available for the FFDC event type, which is specified as `type: liberty_ffdc`. Column one contains the name of the field and column two contains a description of the field.

.FFDC event fields
[%header,cols="3,6"]
|===

|Field name
|Description of field

|`className`
|The class that emitted the FFDC entry

|`exceptionName`
|The exception that was reported in the FFDC entry

|`probeID`
|The unique identifier of the FFDC point within the class

|`stackTrace`
|The stack trace of the FFDC incident

|`objectDetails`
|The incident details for the FFDC incident

|`threadId`
|The thread ID of the FFDC incident

|===

=== Garbage collection events

The garbage collection event type is available only for IBM JDKs. The following table lists the fields that are available for the garbage collection event type, which is specified as `type: liberty_gc`. Column one contains the name of the field and column two contains a description of the field.

.Garbage collection event fields
[%header,cols="3,6"]
|===

|Field name
|Description of field

|`heap`
|The total heap that is currently available

|`usedHeap`
|The amount of heap that is being used

|`maxHeap`
|The maximum heap that the JVM allows

|`duration`
|The duration for which garbage collection was run, in microseconds

|`gcType`
|The type of garbage collection event, for example, Nursery, Global

|`reason`
|The reason for the garbage collection.

|===

== Server and host names in virtualized environments

When Open Liberty servers are running in Docker containers or other virtualized environments, the `hostName` and `serverName` fields are automatically set according to certain variables in the configuration.

The `hostName` field is set to the first of the following values that is available:

- The value of the `CONTAINER_HOST` environment variable
- The value of the `${defaultHostName}` Open Liberty configuration variable
- The canonical hostname as reported by the JDK

The `serverName` field is set to the first of the following values that is available:

- The value of the `CONTAINER_NAME` environment variable
- The value of the `${wlp.server.name}` Open Liberty configuration variable


When Open Liberty servers run in Docker containers or other virtual environments that you manage, set the `CONTAINER_HOST` and `CONTAINER_NAME` environment variables when you run your image. These environment variables ensure that the Logstash collector feature tags the records that it sends with the appropriate host and container name, which aids in problem determination. If you do not set these environment variables, you might find it difficult to determine which container sent which events when you use a dashboard that shows events from multiple containers.

When you start a Docker container, use a command similar to the following example to set these environment variables:

[source,command]
----
docker run -d -e LICENSE=accept -e CONTAINER_NAME=yourContainerName -e CONTAINER_HOST=yourContainerHost --name=yourContainerName yourImageName
----

When Open Liberty servers run in the IBM Cloud® Kubernetes Service, the `CONTAINER_HOST` and `CONTAINER_NAME` are already set for you.
