// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-description:
:page-layout: general-reference
:page-type: general
= Enable observability with MicroProfile Telemetry

MicroProfile Telemetry helps you collect n and analyze data on the paths that application requests take through services. With MicroProfile Telemetry 2.0 and later, you can manage logs, metrics, and traces in a standardized way by using the OpenTelemetry protocol.

MicroProfile Telemetry is based on the https://opentelemetry.io/[OpenTelemetry project], a collection of open source vendor-independent tools, APIs, and SDKs for creating and managing trace data. You can enable MicroProfile Telemetry for Open Liberty by adding the feature:mpTelemetry[display=MicroProfile Telemetry] feature to your `server.xml` file and configuring the feature to connect to your distributed trace service.

The following sections explain how to prepare your Open Liberty runtime and application code to use MicroProfile Telemetry.


- <<#global, Enabling MicroProfile Telemetry for Open Liberty>>
- <<#traces, Collecting traces>>
- <<#logs, Collecting logs>>
- <<#metrics, Collecting metrics>>
- <<#trouble, Troubleshooting>>

[#global]
== Enabling MicroProfile Telemetry for Open Liberty

To enable MicroProfile Telemetry in your Open Liberty runtime, you must add the MicroProfile Telemetry feature to your `server.xml` file and enable the OpenTelemetry SDK.

. Enable the feature:mpTelemetry[display=MicroProfile Telemetry] feature in your `server.xml` file. To export metrics or logs, you must enable `mpTelemetry-2.0` or later.

. OpenTelemetry is disabled by default. To enable the generation of traces, set the `otel.sdk.disabled=false` property.
+
You can configure how MicroProfile Telemetry collects and exports logs, metrics, and traces by specifying configuration properties in any of the xref:external-configuration.adoc#default[config sources that are available to MicroProfile Config]. Alternatively, if you choose to set these configuration properties by using environment variables, make the key name uppercase and convert any punctuation to underscores. For example, the `otel.sdk.disabled=false` property is equivalent to the `OTEL_SDK_DISABLED=false` environment variable.

[#traces]
== Configuring Open Liberty to use MicroProfile Telemetry to collect traces

One way to increase observability of an application is by emitting traces. Traces represent requests and consist of multiple spans. A span represents a single operation in a request. It includes a name, time-related data, log messages, and metadata to collect data about what happens during a transaction.

MicroProfile Telemetry replaces MicroProfile OpenTracing. For more information about migrating your applications from MicroProfile OpenTracing to MicroProfile Telemetry, see xref:reference:diff/mp-50-60-diff.adoc#telemetry[Differences between MicroProfile Telemetry 1.0 and MicroProfile OpenTracing 3.0].

. Enable the MicroProfile Telemetry feature and specify a MicroProfile Config property or environment variable to enable the OpenTelemetry SDK.
+
For more information, see <<#global,Enabling MicroProfile Telemetry for Open Liberty>>

. Configure a trace storage system by specifying an exporter definition that includes the exporter type and endpoint.
+
For example, to use a Jaeger server, you might add configuration similar to the following example to your `bootstrap.properties` file:
+
[source,properties]
----
otel.sdk.disabled=false
otel.traces.exporter=otlp
otel.exporter.otlp.endpoint=http://localhost:4317/
----
+
Alternatively, to use a Zipkin server, you might add configuration similar to the following example to your `bootstrap.properties` file:
+
[source,properties]
----
otel.sdk.disabled=false
otel.traces.exporter=zipkin
otel.exporter.zipkin.endpoint=http://localhost:9411/api/v2/spans
----

. Optionally, set other MicroProfile Config properties to configure trace details.
+
For example, if you want to export traces to Open Liberty log files, set the following property:
+
[source,properties]
----
otel.traces.exporter=logging
----
+
For more information about the available properties, see xref:microprofile-config-properties.adoc#telemetry[MicroProfile Config properties: MicroProfile Telemetry].

. Depending on how you choose to instrument your application code for tracing, further configuration might be required.
+
For more information, see xref:telemetry-trace.adoc#t[Code instrumentation for MicroProfile Telemetry tracing].

[#logs]
== Configuring Open Liberty to use MicroProfile Telemetry to collect logs

To enable MicroProfile Telemetry to collect and export logs in your Open Liberty runtime, add the MicroProfile Telemetry feature 2.0 or later to your `server.xml` file and enable the OpenTelemetry SDK. Optionally, you can specify MicroProfile Config properties to configure how MicroProfile Telemetry collects and exports logs.

. Enable the MicroProfile Telemetry feature 2.0 or later and specify a MicroProfile Config property or environment variable to enable the OpenTelemetry SDK.
+
For more information, see <<#global,Enabling MicroProfile Telemetry for Open Liberty>>.

. Optionally, enable the MicroProfile Telemetry feature to collect logs from different sources in the Open Liberty runtime environment.
+
Configure the `source` attribute for the `mpTelemetry` element with a comma-separated list of comma-separated log sources:
+
[source,xml]
----
<mpTelemetry source="message, trace, ffdc"/>
----
+
The `mpTelemetry` configuration element is optional. If you do not specify it, or if you do not include the `source` attribute, the default configuration source is `message`. For more information, see feature:mpTelemetry-2.0[display=Collect logs from a specified source].

. Optionally, configure the log sources that MicroProfile Telemetry collects and where the logs are exported.
+
You can configure how MicroProfile Telemetry collects and exports logs by specifying configuration properties in any of the xref:external-configuration.adoc#default[config sources that are available to MicroProfile Config], or by specifying environment variables.

.. Change the log exporter that MicroProfile Telemetry uses.
+
By default, all OpenTelemetry data is exported to link:https://opentelemetry.io/docs/languages/java/exporters/#otlp[OTLP]. You can change this setting by specifying the `otel.logs.exporter` property.
+
For example, to send logs to the `console.log` file for debugging purposes, you might add configuration similar to the following example to your `bootstrap.properties` file:
+
[source,properties]
----
otel.sdk.disabled=false
otel.logs.exporter=console
----
+
If you set this property to `console`, all the logs are exported to standard out (`stdout`) and the `console.log` file. The `console.log` file contains the usual logs, along with duplicate OpenTelemetry-mapped logs. This setting is only for debugging purposes because the `console.log` file does not roll over and might affect performance if it gets too large. If you set this property to `none`, no logs are exported
+
.. Configure MicroProfile Telemetry to use the OpenTelemetry Batch LogRecord Processor.
+
By default, the SimpleLogRecordProcessor is enabled, so the records are sent immediately. However, if you want to send the records in batches, you can also configure the following logging-specific Batch LogRecord Processor properties or environment variables:
+
* `otel.blrp.schedule.delay` or `OTEL_BLRP_SCHEDULE_DELAY`
* `otel.blrp.max.queue.size` or `OTEL_BLRP_MAX_QUEUE_SIZE`
* `otel.blrp.max.export.batch.size` or `OTEL_BLRP_MAX_EXPORT_BATCH_SIZE`
* `otel.blrp.export.timeout` or `OTEL_BLRP_EXPORT_TIMEOUT`
+
For more information, see the OpenTelemetry link:https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#batch-logrecord-processor[Batch LogRecord Processor] documentation.

For more information about the available properties, see xref:microprofile-config-properties.adoc#telemetry[MicroProfile Config properties: MicroProfile Telemetry].

[#metrics]
== Configuring Open Liberty to use MicroProfile Telemetry to collect metrics

To enable MicroProfile Telemetry to collect and export metrics in your Open Liberty runtime, add the MicroProfile Telemetry 2.0 feature to your `server.xml` file and enable the OpenTelemetry SDK. Optionally, you can specify MicroProfile Config properties to configure how MicroProfile Telemetry collects and exports metrics.

. Enable the MicroProfile Telemetry feature 2.0 or later and specify a MicroProfile Config property or environment variable to enable the OpenTelemetry SDK.
+
For more information, see <<#global,Enabling MicroProfile Telemetry for Open Liberty>>

. Optionally, change the log exporter that MicroProfile Telemetry uses.
+
By default, all OpenTelemetry data is exported to link:https://opentelemetry.io/docs/languages/java/exporters/#otlp[OTLP]. You can change this setting by specifying the `otel.metrics.exporter` property or the `OTEL_METRICS_EXPORTER` environment variable.
+
For example, to export metrics to Open Liberty log files, specify the following property:
+
----
otel.metrics.exporter=logging
----

. Optionally, change the metric export interval.
+
By default, metric data is exported at an interval of 60 seconds. To modify the export interval, specify the `otel.metric.export.interval` property or the `OTEL_METRIC_EXPORT_INTERVAL` environment variable. Specify the value in milliseconds. For more information, see link:https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#periodic-exporting-metricreader[Periodic exporter MetricReader] in the OpenTelemetry documentation.

To separately configure multiple applications in a server, you can configure OpenTelemetry with application configuration. However, you cannot collect runtime-level metrics this way.

Depending on how you choose to instrument your application code for metrics, further configuration might be required.



=== Custom metrics

You can use the metrics API to define custom metrics in your application code, as shown in the following example:

[source,java]
----
class WithCounter {
    @Inject
    Meter meter;

    private LongCounter counter;

    @PostConstruct
    public void init() {
        counter = meter
                    .counterBuilder("new_subscriptions")
                    .setDescription("Number of new subscriptions")
                    .setUnit("1")
                    .build();
    }

    void subscribe(String plan) {
        counter.add(1,
            Attributes.of(AttributeKey.stringKey("plan"), plan));
    }
}
----

In this example, `Meter` is used to define an instrument, in this case a Counter. Application code then can record measurement values along with other attributes. Measurement aggregations are computed separately for each unique combination of attributes.

For a full list of available metrics, see link:https://opentelemetry.io/docs/specs/otel/metrics/api/#meter-operations[Meter operations] in the OpenTelemetry documentation.


[#trouble]
== Troubleshooting MicroProfile Telemetry
The following information can help you determine the cause of common problems and error messages.

Previous spans are incorrectly shown as current or parent spans::

If the `Scope` instance is not closed correctly, the context and baggage values of previous spans might remain when the next operation executes. Alternatively, the current span might remain and be picked up as the parent of the next operation that executes.
+
Always close the `Scope` instance when you exit an operation. This configuration stops the span from being current and makes the previous span current again. Use a `try-with-resources` block, which automatically closes the `Scope` instance at the end of the block, as shown in the following example:
+
[source, java]
----
Span span = tracer.spanBuilder("PerformingOperation").startSpan();
try (Scope scope = span.makeCurrent()) {
    ...
} finally {
    span.end();
}
----

You receive the `CWMOT5100I` message that tracing is disabled::

If you enable the `mpTelemetry-1.1` or `mpTelemetry-1.0` feature, you must also set the `otel.sdk.disabled=false` property in any of the configuration sources that are accessible through MicroProfile Config to enable tracing.

You receive the CWMOT5003W message that the application attempted to acquire MicroProfile Telemetry after shut down::

Review the application to see why it attempted to use MicroProfile Telemetry after it shut down. Actions that might trigger MicroProfile Telemetry include calling a method that is annotated with `@WithSpan` or making a request with a JAX-RS Client or MP Rest Client.

You receive either of the CWMOT5006W or CWMOT5007 warning message that conflicting configuration is specified for otel.sdk.disabled::

Specify the settings to enable or disable OpenTelemetry instances by using either environment variables or MicroProfile Config sources, but not both. If you see these warnings, the other MicroProfile Config source to look at is your `server.xml` file.

////
+
Different versions of the MicroProfile Telemetry feature are compatible with different MicroProfile versions, Jakarta and Java Enterprise Editions, and the Open Liberty umbrella features that support them. Both feature:mpTelemetry-1.0[] and feature:mpTelemetry-1.1[] are compatible with feature:jakartaee-10.0[] and feature:microProfile-6.0[]. However, `mpTelemetry-1.1` is also compatible with the following earlier umbrella features:
+
*  feature:javaee-7.0[] and feature:microProfile-1.4[]
*  feature:jakartaee-8.0[] and feature:microProfile-4.1[]
*  feature:jakartaee-9.1[] and feature:microProfile-5.0[]
////
