// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-description:
:page-layout: general-reference
:page-type: general
= Enable distributed tracing with MicroProfile Telemetry

In microservice applications, sources of latency or inaccuracy can be difficult to determine because relationships and dependencies among the constituent services are not always obvious. MicroProfile helps you collect data on the paths that application requests take through services.

One way to increase observability of an application is by emitting traces. Traces represent requests and consist of multiple spans. A span represents a single operation in a request and contains a name, time-related data, log messages, and metadata to gather data about what occurs during a transaction.

MicroProfile Telemetry is based on the https://opentelemetry.io/[OpenTelemetry project], which is a collection of open source vendor-agnostic tools, APIs, and SDKs for creating and managing telemetry data.

== Instrumentation types

MicroProfile Telemetry supports tracing data instrumentation in three different ways: automatic instrumentation, manual instrumentation, or agent instrumentation. The data can then be exported to tracing systems like https://www.jaegertracing.io/[Jaeger] or https://zipkin.io/[Zipkin]

=== Automatic instrumentation
With automatic instrumentation, you can observe traces without modifying the source code in your Jakarta RESTful web service (formerly JAX-RS) applications. To start emitting traces with automatic instrumentation, enable the feature:mpTelemetry[MicroProfile Telemetry] feature in your `server.xml` file. By default, MicroProfile Telemetry tracing is off. To enable tracing, specify either the `otel.experimental.sdk.enabled=true` MicroProfile Config property or the `OTEL_EXPERIMENTAL_SDK_ENABLED=true` environment variable for your server.

You can configure how MicroProfile Telemetry collects and exports traces by specifying configuration properties in any of the xref:external-configuration.adoc#default[config sources that are available to MicroProfile Config]. For more information about the available properties, see xref:microprofile-config-properties.adoc#telemetry[MicroProfile Config properties: MicroProfile Telemetry].

For example, you might create a `microprofile-config.properties` file that specifies the following properties.

[source,properties]
----
otel.experimental.sdk.enabled=true
otel.service.name=exampleServiceName
otel.traces.exporter=jaeger
otel.exporter.jaeger.endpoint=http://localhost:14250
----

This configuration results in spans for the example service that are exported to Jaeger at the `\http://localhost:14250` endpoint.

Alternatively, you can specify the configuration by using  environment variables in your `server.env` file. For more information, see the https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md[OpenTelemetry environment variable specification].

=== Manual instrumentation
The automatic instrumentation only instrument Jakarta RESTful web service applications. To get further spans on other operations, such as database calls, you can add manual instrumentation to the source code for those operations. For more information, see the https://opentelemetry.io/docs/instrumentation/java/manual[OpenTelemetry manual instrumentation documentation].

=== Agent instrumentation
The OpenTelemetry Java agent enables Java applications to generate and capture telemetry data automatically. To enable the java agent on your Open Liberty application, https://github.com/open-telemetry/opentelemetry-java-instrumentation#getting-started[download the latest version from OpenTelemetry] and add the following line to your `jvm.options` file.

[subs=+quotes]
----
java -javaagent: _path/to/opentelemetry-javaagent.jar_
----

You can configure the agent with https://github.com/open-telemetry/opentelemetry-java-instrumentation#configuring-the-agent[environment variables and system properties]. You can find a list of supported libraries and frameworks in the https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md#libraries--frameworks[Open Telemetry Java instrumentation documentation].
