// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-description:
:page-layout: general-reference
:page-type: general
= Enable distributed tracing with MicroProfile Open Telemetry

In microservice applications, sources of latency or inaccuracy can be difficult to determine because relationships and dependencies among the conastiuent services are not always obvious. MicroProfile helps you collect data on the paths that application requests take through services.

One way to increase observability of an application is by emitting traces. Traces represent requests and consist of multiple spans. A span represents a single operations in a request and contains a name, time-related data, log messages, and metadata to gather data about what occurs during a transaction.

== Instrumentation types

MicroProfile Telemetry instruments tracing data in two different ways: automatic instrumentation or manual instrumentation. The data can then be exported to tracing systems like https://www.jaegertracing.io/[Jaeger] or https://zipkin.io/[Zipkin]

=== Automatic instrumentation
With automatic instrumentation, you can observe traces without modifying the source code in your Jakarta RESTful web service (formerly JAX-RS) applications. To start emitting traces with automatic instrumentation, enable the feature:mpTelemetry[MicroProfile Telemetry] feature in your `server.xml` file. By default, MicroProfile Telemetry tracing is off. To enable tracing, specify either the `otel.experimental.sdk.enabled=true` MicroProfile Config property or the `OTEL_EXPERIMENTAL_SDK_ENABLED=true` environment variable for your server.

You can configure how MicroProfile Telemetry collects and exports traces by specifying configuration properties in in any of the config sources that are available to MicroProfile Config. For more information on these properties, see xref:microprofile-config-properties.adoc#telemetry[MicroProfile Config properties: MicroProfile Telemetry]. Alternatively, you can specify the configuration by using  environment variables in your `server.env` file. For more information, see the https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md[OpenTelemetry environment variable specification].

=== Manual instrumentation

The automatic instrumentation only instrument Jakarta RESTful web service applications. To get further spans on other operations such as database calls, manual instrumentation can be added to those source code.

See OpenTelemetry's manual instrumentation documentation.

=== Agent instrumentation
The OpenTelemetry Java agent enables Java applications to generate and capture telemetry data automatically. To enable the java agent on your Open Liberty application, download the latest version here and add the following to your jvm.options file.

java -javaagent:path/to/opentelemetry-javaagent.jar

The agent is configurable with environment variables and system properties. A list of supported libraries and frameworks can be found in the Java Instrumentation documentation.
