// Copyright (c) 2023 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
// https://creativecommons.org/licenses/by-nd/4.0/
//
//
// Contributors:
// IBM Corporation
//
//
//
//
:page-description: If you are updating your application from using MicroProfile 5.0 features to using MicroProfile 6.0 features, changes in API behavior might require you to update your application code.
:projectName: Open Liberty
:page-layout: general-reference
:page-type: general
= Differences between MicroProfile 6.0 and 5.0

If you are updating your application from using MicroProfile 5.0 features to using MicroProfile 6.0 features, changes in API behavior might require you to update your application code.

[#metrics]
== Differences between MicroProfile Metrics 5.0 and earlier versions

Changes in MicroProfile Metrics 5.0 affect the `metrics` endpoint syntax and the formatting of the Prometheus name, base metrics, and metric types.

=== Metric endpoints

MicroProfile Metrics 5.0 does not support JSON-formatted output. Furthermore, syntax for the endpoints URLs uses query string parameters for the scope and metric name values. Earlier versions of the feature support JSON out and use path parameters for the scope and metric name values. For more information, see xref:microservice-observability-metrics.adoc#50[Microservice observability with metrics]


=== Metric units
In previous releases, the units that a metric is displayed in can differ from the unit that is recorded internally because the Prometheus exporter scales metrics to a base unit.
For example, while the `ft.<name>.bulkhead.executionDuration` metric is recorded internally in nanoseconds, the Prometheus output is in seconds. +
{empty} +
In MicroProfile Metrics 5.0, the unit that is internally recorded is reflected in the Prometheus output. The metrics are not scaled to a base unit. 

=== Metric registry scope
In previous releases, the metric registry scope that a metric was associated with was indicated by a prefix of `base_` or `vendor_` in the Prometheus formatted name. In MicroProfile Metrics 5.0, this information is displayed with an `mp_scope` tag, for example, `{mp_scope="base"}`.

=== REST.Request metric
In previous releases of MicroProfile Metrics, the `REST.Request` metric was instrumented with a `SimpleTimer` metric type. In MicroProfile Metrics 5.0 the `SimpleTimer` metric type is no longer available and the metric is instrumented with a `Timer` metric type.

=== Histogram metric
In MicroProfile Metrics 5.0, metrics that are instrumented with a `Histogram` metric type have fewer formatted outputs than in previous releases, due to the the removal of the `min`, `mean` and `stddev` values. Furthermore, the formatting of the Prometheus output has changed. The suffix that defines the `Histogram` value trails after the unit suffix. For example, `bulkhead_waitingDuration_max_seconds` becomes `bulkhead_waitingDuration_seconds_max`.




