// Copyright (c) 2023 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
// https://creativecommons.org/licenses/by-nd/4.0/
//
//
// Contributors:
// IBM Corporation
//
//
//
//
:page-description: If you are updating your application from using MicroProfile 5.0 features to using MicroProfile 6.0 features, changes in API behavior might require you to update your application code.
:projectName: Open Liberty
:page-layout: general-reference
:page-type: general
= Differences between MicroProfile 6.0 and 5.0

If you are updating your application from using MicroProfile 5.0 features to using MicroProfile 6.0 features, changes in API behavior might require you to update your application code.

== Differences between MicroProfile Metrics 5.0 and earlier versions

Changes in MicroProfile Metrics 5.0 affect the `metrics` endpoint syntax and the formatting of the Prometheus name, base metrics, and metric types.

=== Metric registry scope
In previous releases, the metric registry scope that a metric was associated with was indicated by a prefix of `base_` or `vendor_` in the Prometheus formatted name. In MicroProfile Metrics 5.0, this information is displayed with an `mp_scope` tag, for example, `{mp_scope="base"}`.

=== REST.Request metric
In previous releases of MicroProfile Metrics, the `REST.Request` metric was instrumented with a `SimpleTimer` metric type. In MicroProfile Metrics 5.0 the `SimpleTimer` metric type is no longer available and the metric is instrumented with a `Timer` metric type.

=== Histogram metric
In MicroProfile Metrics 5.0, metrics that are instrumented with a `Histogram` metric type have fewer formatted outputs than in previous releases, due to the the removal of the `min`, `mean` and `stddev` values. Furthermore, the formatting of the Prometheus output has changed. The suffix that defines the `Histogram` value trails after the unit suffix. For example, `bulkhead_waitingDuration_max_seconds` becomes `bulkhead_waitingDuration_seconds_max`.


