// Copyright (c) 2019, 2023 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Building observability into microservices externalizes the internal status of a system so operations teams can monitor systems more effectively. You can make your Open Liberty applications more observable by providing detailed log and metric data, enabling distributed tracing, and configuring application health checks.

:seo-title: Observability - OpenLiberty.io
:seo-description: Building observability into microservices externalizes the internal status of a system so operations teams can monitor systems more effectively. You can make your Open Liberty applications more observable by providing detailed log and metric data, enabling distributed tracing, and configuring application health checks.

:page-layout: general-reference
:page-type: general
= Observability 

Building observability into microservices externalizes the internal status of a system so operations teams can monitor systems more effectively. You can make your Open Liberty applications more observable by providing detailed log and metric data, enabling distributed tracing, and configuring application health checks.

Observability is key to identifying and understanding the root causes of bugs, bottlenecks, and other inefficiencies in your application systems. When developers have access to detailed feedback about how systems are performing, they can not only fix problems more quickly, they can plan and develop new features that more dependably support their users' needs. Open Liberty provides a robust framework for building observable applications and integrates with numerous third party monitoring tools.

The following topics provide information help you build observable applications with Open Liberty.

xref:microservice-observability-metrics.adoc[Microservice observability with metrics]::
Open Liberty uses MicroProfile Metrics to expose metrics that describe the internal state of many Open Liberty components. MicroProfile Metrics provides a `/metrics` endpoint from which you can access all metrics that are emitted by an Open Liberty server and deployed applications.

xref:introduction-monitoring-metrics.adoc[Monitoring with metrics]::
Two kinds of metrics are available to monitor your Open Liberty applications: REST endpoint-style metrics that are provided by MicroProfile Metrics, and Java Management Extensions (JMX) metrics. MicroProfile Metrics and JMX metrics can be used separately or in conjunction to improve the observability of your application systems.

xref:micrometer-metrics.adoc[Choose your own monitoring tools with Micrometer]::
The Open Liberty MicroProfile Metrics 5.0 feature integrates with the Micrometer metrics technology to transfer metric data to multiple third-party monitoring systems. With Micrometer, you can instrument your code in a standardized way to visualize metrics results in the monitoring system of your choice. 

xref:health-check-microservices.adoc[Health checks for microservices]::
A health check is a special REST API implementation that you can use to validate the status of a microservice and its dependencies. With MicroProfile Health, microservices can self-check their health and publish their overall status to a defined endpoint.

xref:microprofile-telemetry.adoc[Enable distributed tracing with MicroProfile Telemetry]::
In microservice applications, sources of latency or inaccuracy can be difficult to determine because relationships and dependencies among the constituent services are not always obvious. MicroProfile Telemetry helps you collect data on the paths that application requests take through services.

xref:log-trace-configuration.adoc[Log and trace configuration]::
Open Liberty has a unified logging component that handles messages that are written by applications and the runtime, and provides First Failure Data Capture (FFDC) capability. Logging data that is written by applications by using the `System.out`, `System.err`, or `java.util.logging.Logger` streams is combined into the server logs.


For hands-on tutorials on different observability configurations for Open Liberty, check out our link:/guides/#observability[Observability guides].


