// Copyright (c) 2019, 2023 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Building observability into applications externalizes the internal status of a system so operations teams can monitor systems more effectively. Open Liberty provides a robust framework for building observable applications and integrates with numerous third party monitoring tools.
:seo-title: Observability - OpenLiberty.io
:seo-description: Building observability into applications externalizes the internal status of a system so operations teams can monitor systems more effectively. Open Liberty provides a robust framework for building observable applications and integrates with numerous third party monitoring tools.
:page-layout: general-reference
:page-type: general
= Observability 

Observable applications externalize the internal status of a system so operations teams identify and understand the root causes of bugs, bottlenecks, and other inefficiencies. Open Liberty provides a robust framework for developing observable applications and integrates with numerous third-party monitoring tools.

The following topics provide information to help you develop observable applications with Open Liberty.

xref:microservice-observability-metrics.adoc[Microservice observability with metrics]::
Open Liberty uses MicroProfile Metrics to expose metrics that describe the internal state of many Open Liberty components. MicroProfile Metrics provides a `/metrics` endpoint from which you can access all metrics that are emitted by an Open Liberty server and deployed applications.

xref:micrometer-metrics.adoc[Choose your own monitoring tools with Micrometer]::
The Open Liberty MicroProfile Metrics 5.0 feature integrates with the Micrometer metrics technology to transfer metric data to multiple third-party monitoring systems. With Micrometer, you can instrument your code in a standardized way to visualize metrics results in the monitoring system of your choice. 

xref:health-check-microservices.adoc[Health checks for microservices]::
A health check is a special REST API implementation that you can use to validate the status of a microservice and its dependencies. With MicroProfile Health, microservices can self-check their health and publish their overall status to a defined endpoint.

xref:microprofile-telemetry.adoc[Enable distributed tracing with MicroProfile Telemetry]::
In microservice applications, sources of latency or inaccuracy can be difficult to determine because relationships and dependencies among the constituent services are not always obvious. MicroProfile Telemetry helps you collect data on the paths that application requests take through services.

For hands-on tutorials on different observability configurations for Open Liberty, check out our link:/guides/#observability[Observability guides].


