// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The Open Liberty Operator can be used to deploy and manage applications that are running on Open Liberty into Kubernetes clusters.
:seo-title: Open Liberty Operator - OpenLiberty.io
:seo-description: The Open Liberty Operator can be used to deploy and manage applications that are running on Open Liberty into Kubernetes clusters.
:page-layout: general-reference
:page-type: general
= Open Liberty Operator

Operators are extensions to Kubernetes that are customized to automate tasks beyond the initial automation that Kubernetes or OpenShift provide.
The Open Liberty Operator helps you deploy and manage applications on Kubernetes-based clusters.

== What is the Open Liberty Operator?
When you deploy an application with the operator, the operator watches Open Liberty resources and compares the current state of resources to the desired state of resources that you configure.
When a discrepancy exists between the current state and the desired state, the operator creates, updates, or deletes Kubernetes resources, including `Deployments`, `Services`, and `Routes`, to return to the desired state.
Without the operator, you must manually create `Deployments`, `Services`, `Routes`, and other Kubernetes resources, which can be a time-consuming learning curve.
With the operator, specify details for your application, including your application image, service port, and whether to expose the application outside the cluster, and the operator creates and manages all Kubernetes resources.
Now, you manage only a single `OpenLibertyAppllication` resource instead of many resources.
In addition, the operator continuously monitors the events that are related to the application in the cluster and takes necessary actions to synchronize data and resources.
Because the operator helps you manage Kubernetes resources, you can focus on your application while the operator handles many of the cloud deployment details.

The Open Liberty Operator is based on the generic https://operatorhub.io/operator/runtime-component-operator[Runtime Component Operator], so common functionality exists between these two operators.
See the Open Liberty Operator documentation if you want to learn more about the https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.adoc#common-component-documentation[common documentation that applies to both operators].
The architecture of the Open Liberty Operator follows the basic controller pattern, meaning that the operator container and controller are deployed to a Kubernetes Pod.
Then, the operator listens for incoming resources with the `kind: OpenLibertyApplication` statement.
When you create an `OpenLibertyApplication` custom resource (CR), the operator manages the Kubernetes resources that the application needs to run on your cluster.

== Operator capabilities
The Open Liberty Operator has a capability level of five, which means that it has the highest level of enterprise capabilities, including the following capabilities:

* **High availability that's provided by horizontal auto-scaling**
+
You can configure horizontal auto-scaling to create and delete instances of your application based on resource consumption.
This ability to run multiple instances of your application and auto-scale them means that your application is made highly available.

* **Enhanced deployment management**
+
With the Open Liberty Operator, you can more easily manage applications that are deployed to Kubernetes.
For example, in the operator deployment file, you can specify an https://docs.openshift.com/container-platform/3.9/architecture/core_concepts/builds_and_image_streams.html#image-streams[image stream] in the `applicationImage` field.
Then, after you upload a new container tag for a new version of an application, the operator updates the application on a rolling basis.

* **Automated service binding**
+
The operator automates updates of binding information among applications, meaning that it connects applications and maintains information about whether a particular application produces or consumes a service.
With this information, the operator automatically handles Kubernetes-level details, including creating and injecting Kubernetes Secrets, so that your applications can connect to required services without interruption.

* **Single-sign on (SSO) delegation**
+
With Open Liberty, you can xref:single-sign-on.adoc[delegate SSO authentication to external providers].
The Open Liberty Operator enables easier configuration and management of single sign-on information for your applications.
For more information about SSO configuration with the operator, see the https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.adoc#single-sign-on-sso[Open Liberty Operator documentation].

* **OpenShift Serverless (Knative) integration**
+
You can integrate the operator with https://www.openshift.com/learn/topics/serverless[Knative].
When the operator is integrated with Knative, you deploy your serverless runtime component by using a single toggle.
The operator converts all of its generated resources into Knative resources, which allows your pod to automatically scale to 0 when it's idle.

* **Kubernetes Application Navigator (kAppNav) integration**
+
The operator can automatically configure integration with https://kappnav.io/[kAppNav].
With this integration, you can monitor resources of your application and receive alerts when the health status of a component changes.
From an integrated pane, you can also access operations-focused capabilities, such as enabling trace for a component and viewing Kibana or Grafana dashboards.

* **OpenShift certificate management integration**
+
The operator https://cert-manager.io/[takes advantage of the cert-manager tool], if it's installed on the Kubernetes cluster.
The cert-manager tool allows the operator to automatically provision Transport Layer Security (TLS) certificates for pods and routes.
Certificates are mounted into containers from a Kubernetes Secret so that the certificates are automatically refreshed when they're updated.

Go to the documentation in OperatorHub for a https://operatorhub.io/operator/open-liberty[complete list of the enterprise capabilities that are offered by the operator].

== Serviceability and observability with the operator
You can https://github.com/application-stacks/runtime-component-operator/blob/master/doc/user-guide.adoc#Persistence[enable persistence for your application] by specifying only the size of storage and where you want the storage to be mounted.
Then, the operator creates and manages the storage claim for you.
An advanced mode is available that allows the configuration of extra details of the persistent volume claim.
You can also configure and use a single storage for serviceability-related operations, such as gathering server memory dumps and server traces.
For more information about how to request server memory dumps and server traces, see the https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.adoc#day-2-operations[Open Liberty Operator documentation].

After you configure the operator, you can integrate Open Liberty with logging and monitoring tools in the Kubernetes cluster.
You can select different types of Open Liberty data that you want to monitor, depending on your needs.
If you need to visualize and track logging events, https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/observability-deployment-rhocp4.2-4.5.adoc#how-to-deploy-kibana-dashboards-to-monitor-open-liberty-logging-events[deploy one of the provided Open Liberty Kibana dashboards].
You can monitor Open Liberty metrics by using https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/observability-deployment-rhocp4.2-4.5.adoc#microprofile-metrics[MicroProfile Metrics], https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/observability-deployment-rhocp4.2-4.5.adoc#enabling-prometheus-to-scrape-data[Prometheus], and https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/observability-deployment-rhocp4.2-4.5.adoc#visualizing-your-data-with-grafana[Grafana] to gather, scrape, and visualize metric data.
You can also enable https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/observability-deployment-rhocp4.2-4.5.adoc#how-to-use-health-info-with-service-orchestrator[MicroProfile Health] to perform liveness checks and readiness checks so that Kubernetes can check the health of your containers.


== Operator installation and configuration
You can https://operatorhub.io/operator/open-liberty[install the Open Liberty Operator] from OperatorHub for use on Kubernetes or OpenShift.
The https://access.redhat.com/containers/#/registry.connect.redhat.com/ibm/open-liberty-operator[Operator is also available as a Red Hat-certified Operator] from OpenShift Container Platform (OCP).
Go to the Open Liberty Operator documentation for https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.adoc#operator-installation[information about how to install the operator].
The Open Liberty Operator documentation also provides details about configuring the operator, including the following information:

* https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.adoc#basic-usage[Basic configuration]

* https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.adoc#custom-resource-definition-crd[Custom Resource Definition (CRD) parameters]

* https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.adoc#open-liberty-environment-variables[Open Liberty console logging environment variables]

* https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.adoc#storage-for-serviceability[Persistent storage specifications]

== See also

* link:/guides/cloud-openshift-operator.html[Guide: Deploying an application to OpenShift by using Kubernetes Operators]
* https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/observability-deployment-rhocp4.2-4.5.adoc[Observability with the Open Liberty Operator]
* https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/troubleshooting.adoc[Troubleshooting the Open Liberty Operator]
