// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The Open Liberty Operator can be used to deploy and manage applications that are running on Open Liberty into Kubernetes clusters.
:seo-title: Open Liberty Operator - OpenLiberty.io
:seo-description: The Open Liberty Operator can be used to deploy and manage applications that are running on Open Liberty into Kubernetes clusters.
:page-layout: general-reference
:page-type: general
= Open Liberty Operator

Add a short description

Add a paragraph about what the operator is and how it's generally helpful

== Operator capabilities
The Open Liberty Operator has a capability level of five, which means that it has the highest level of enterprise capabilities, including the following capabilities:

* **High availability that's provided by horizontal auto-scaling**
+
You can configure horizontal auto-scaling to create and delete instances of your application based on resource consumption.
This ability to run multiple instances of your application and auto-scale them means that your application is made highly available.

* **Enhanced deployment management**
+
With the Open Liberty Operator, you can more easily manage applications that are deployed to Kubernetes.
For example, after you upload a new container tag for a new version of an application, update the `applicationImage` field in the operator deployment file with the new container tag.
Then, the operator updates the application on a rolling basis.

* **Automated service binding**
+
The operator automates updates of binding information among applications, meaning that it connects applications and maintains information about whether a particular application produces or consumes a service.
With this information, the operator automatically handles Kubernetes-level details, including creating and injecting Kubernetes Secrets, so that your applications can connect to required services without interruption.

* **Simplified persistence and advanced storage**
+
Enable persistence for your application by specifying only the size of storage and where you want the storage to be mounted.
Then, the operator creates and manages that storage for you.
An advanced mode is available that allows the configuration of extra details of the persistent volume.
You can also configure and use a single storage for serviceability-related operations, such as gathering server traces and memory dumps.

* **Single-sign on (SSO) delegation**
+
With Open Liberty, you can xref:single-sign-o.adoc[delegate SSO authentication to external providers].
The Open Liberty Operator enables easier configuration and management of single sign-on information for your applications.

* **Kubernetes Application Navigator (kAppNav) integration**
+
The operator can automatically configure integration with https://kappnav.io/[kAppNav].
With this integration, you can monitor resources of your application and receive alerts when the health status of a component changes.
From an integrated pane, you can also access operations-focused capabilities, such as enabling trace for a component and viewing Kibana or Grafana dashboards.

* **OpenShift certificate management integration**
+
The operator https://cert-manager.io/[takes advantage of the cert-manager tool], if it's installed on the Kubernetes cluster.
The cert-manager tool allows the operator to automatically provision Transport Layer Security (TLS) certificates for pods and routes.
Certificates are mounted into containers from a Kubernetes Secret so that the certificates are automatically refreshed when they're updated.

Go to the documentation in OperatorHub for a https://operatorhub.io/operator/open-liberty[complete list of the capabilities that are offered by the operator].

== Observability with the operator


== Operator installation and configuration
You can https://operatorhub.io/operator/open-liberty[install the Open Liberty Operator] from OperatorHub for use on Kubernetes or OpenShift.
The https://access.redhat.com/containers/#/registry.connect.redhat.com/ibm/open-liberty-operator[Operator is also available as a Red Hat-certified Operator] from OpenShift Container Platform (OCP).
Go to the Open Liberty Operator documentation for information about https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.adoc#operator-installation[installing the operator].
