// Copyright (c) 2020, 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty supports AES encryption for passwords that are stored in the `server.xml` file. When you use this option for protecting system passwords in the Open Liberty configuration, understand the limits to the protection it provides.
:seo-title: Password encryption - OpenLiberty.io
:seo-description: Open Liberty supports AES encryption for passwords that are stored in the `server.xml` file. When you use this option for protecting system passwords in the Open Liberty configuration, understand the limits to the protection it provides.
:page-layout: general-reference
:page-type: general


= Password encryption limitations

Open Liberty supports the Advanced Encryption Standard (AES) encryption for passwords that are stored in the `server.xml` file.
When you use this option for protecting passwords in the Open Liberty configuration, understand the limitations to the protection that AES encryption provides. Currently, Open Liberty supports AES-128 encryption.

Encrypting a password in the Open Liberty configuration does not guarantee that the password is secure or protected.
Encrypting a password means that someone who can see the encrypted password cannot easily recover the password unless they know the encryption key.
The application server process requires access to the encrypted password and the decryption key, so these items must be stored on the file system that is accessible to the server runtime environment.
The encryption key is also required by anyone who encrypts a password that is placed in the server configuration.
If an attacker has access to the same set of files as the Open Liberty server, applying AES encryption to the password provides no additional security over XOR encoding.
However, there are reasons why you might consider encrypting passwords in the Open Liberty configuration.

The Open Liberty configuration is composable and sharable.
Open Liberty is designed to be configured without an administration subsystem, so any XOR-encoded password is visible to any administrator.
Because of these design features, consider whether passwords are sensitive and need to be encrypted.

* If passwords are not sensitive, encoding them might provide little value.
* If passwords are sensitive, protect the configuration files or the encoding key, depending on the scenario.

Either the configuration files that contain the passwords are sensitive and access to these files must be controlled, or the passwords are encrypted and the encoding key is protected as sensitive.

For more information about how to obfuscate passwords for Open Liberty, see the xref:reference:command/securityUtility-encode.adoc[securityUtility encode command].


== Encryption key protection

In Open Liberty, the default key that is used for encrypting and decrypting can be overridden by setting the `wlp.password.encryption.key` property.

Set the property in a separate configuration file that is included in the `server.xml` file, as shown in the following example.

[source,xml]
----
<server>
  ...
  <include location="/protected/key.xml" />
</server>
----

This separate configuration file must contain only a single property declaration, and it must be stored outside the normal configuration directory for the server.


It is preferred that you do not set the `wlp.password.encryption.key` property in the `server.xml` file that stores the password.

Otherwise, the file that contains the key might be included when you run the `server dump` or `server package` commands.

The separate configuration file must contain only a single property declaration, as shown in the following example.

[source,xml]
----
<variable name="wlp.password.encryption.key" value="yourKey" />
----

== See also

* xref:reference:config/server-configuration-overview.adoc[Server configuration overview]
* xref:reference:command/securityUtility-encode.adoc[securityUtility encode command]
