// Copyright (c) 2024 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-description:
:page-layout: general-reference
:page-type: general
= Prepare your development environment for MicroProfile Telemetry

Before you manually instrument your code to use MicroProfile Telemetry to collect metrics and traces, you must enable MicroProfile Telemetry in your development environment by editing your runtime configuration. You must also add the OpenTelemetry API and annotations as a dependency on your build path.

Before you xref:telemetry-trace.adoc[manually instrument your code to collect traces] or xref:custom-mptelemetry-metrics.adoc[define custom metrics], complete the following prerequisites.

. Enable MicroProfile Telemetry, as described in xref:microprofile-telemetry.adoc#global[Enabling MicroProfile Telemetry for Open Liberty].

. xref:class-loader-library-config.adoc#3rd-party[Enable third-party APIs] for your application by adding the following code in your `server.xml` file:
+
[source,xml]
----
<webApplication id="app-name" location="app-name.war">
    <classloader apiTypeVisibility="+third-party"/>
</webApplication>
----

. Add the `opentelemetry` API and OpenTelemetry instrumentation annotations as a provided dependency to your build path. For example, with Maven, add the following code to your `pom.xml` file.
+
[source,xml]
----
    <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-api</artifactId>
        <version>1.39.0</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>io.opentelemetry.instrumentation</groupId>
        <artifactId>opentelemetry-instrumentation-annotations</artifactId>
        <version>1.39.0-alpha</version>
        <scope>provided</scope>
    </dependency>
----

After you complete those prerequisites, you're ready to instrument your code.

== See also
- xref:telemetry-trace.adoc[Code instrumentation for MicroProfile Telemetry tracing]
- xref:custom-mptelemetry-metrics.adoc[Define custom MicroProfile Telemetry metrics]
