
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Relational database connections with JDBC
:seo-description: You can configure a data source and a JDBC driverr so an application that is running on your Open Liberty server can connect with a database.
:page-layout: general-reference
:page-type: general
= Relational database connections with JDBC

Java applications connect to and interact with relational databases through the Java Database Connectivity (JDBC) API. You can configure a data source and a JDBC driver so an application that is running on your Open Liberty server can connect with a relational database.

Applications communicate with relational databases to retrieve many different kinds of information, such as flight schedules, product inventories, and customer purchase histories. https://docs.oracle.com/javase/tutorial/jdbc/overview/index.html[The JDBC API] provides an adapter layer between applications and relational databases by providing details about a database to an application in a standardized way. In Open Liberty, interactions with the JDBC API are configured by the xref:reference:feature/jdbc-4.2.adoc[Java Database Connectivity feature].

== JDBC driver library configuration

To connect with a relational database, you need a JDBC driver, which is typically provided by the database vendor. You can configure JDBC drivers to define data sources, from which you obtain connections to the database. To configure a JDBC data source in your Open Liberty server configuration, you must enable the xref:reference:feature/jdbc-4.2.adoc[Java Database Connectivity feature] and specify a library that contains your JDBC driver. In the following example, the `library` element specifies the location of the directory that contains a JDBC driver JAR file:


[source,xml]
----
<featureManager>
    <feature>jdbc-4.3</feature>
</featureManager>

<library id="jdbcLib">
    <fileset dir="jdbc" includes="*.jar"/>
</library>
----

Open Liberty recognizes the implementation class names of various data source types for commonly used JDBC drivers. In most cases, you specify only the location of the JDBC driver.

If you use Maven to build your application, you can download and deploy the JDBC driver by adding code that is similar to the following example to your `pom.xml` file. In this example, the `com.ibm.db2:jcc:11.5.4.0' dependency is copied to the `${server.config.dir}/jdbc` directory at build time to deploy the IBM Db2 JDBC driver:

[source,xml]
----
<plugin>
 <groupId>io.openliberty.tools</groupId>
 <artifactId>liberty-maven-plugin</artifactId>
 <version>3.3-M2</version>
 <configuration>
  <copyDependencies>
   <dependency>
    <filter>com.ibm.db2:jcc:11.5.4.0</filter>
    <location>jdbc</location>
   </dependency>
  </copyDependencies>
 </configuration>
</plugin>
----

== Data source configuration

You can configure any JDBC driver with Open Liberty, which has built-in configuration for many common vendor databases. The following example shows the basic pattern to configure a data source in your `server.xml` file or an included file:

[source,xml]
----
<library id="jdbcLib">
    <fileset dir="jdbc" includes="*.jar"/>
</library>

<dataSource jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="jdbcLib"/>
    <properties serverName="localhost" portNumber="5432"
                databaseName="myDB"
                user="exampleUser" password="examplePassword"/>
</dataSource>
----

In this example, the `dataSource` element references the library that contains the JDBC driver JAR file and specifies several JDBC vendor properties with the `properties` attribute. Every JDBC driver provides a different collection of properties that can be configured on its `dataSource` implementation classes. If the JDBC driver data source has setter methods with a String or primitive parameter, you can configure these properties by specifying the `properties` attribute in the `dataSource` element.

The following example shows the basic configuration to specify JDBC vendor properties in the `dataSource` element:

[source,xml]
----
<properties someProperty="someValue" anotherProperty="5" />
----

For example, the following sample shows `currentLockTimeout` property on the Db2 JDBC driver's data source classes:

[source,java]
----
public void setCurrentLockTimeout(int lockTimeout);
public int getCurrentLockTimeout();
----

You can configure this setting with the following configuration in your `server.xml` file:

[source,xml]
----
<dataSource jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="jdbcLib"/>
    <properties serverName="localhost" portNumber="1234" databaseName="myDB"
                user="exampleUser" password="examplePassword"
                currentLockTimeout="30s"/>
</dataSource>
----

After you configure a data source, you can quickly test the configuration to see if your Open Liberty server can access your database. For more information, see xref:testing-database-connections.adoc[Testing database connections].

[#default]
=== Default data source configuration

If you enable any Java EE or Jakarta EE features in Open Liberty, you can configure a default data source. To configure a default data source, set the ID of the `dataSource` element to `DefaultDataSource`, as shown in the following example:

[source,xml]
----
<dataSource id="DefaultDataSource">
<jdbcDriver libraryRef="jdbcLib"/>
<properties serverName="localhost" portNumber="5432"
            databaseName="myDB"
            user="exampleUser" password="examplePassword"/>
</dataSource>
----


== Common data source configuration examples

The following examples show sample configurations for commonly used vendor databases. For applicable vendors, examples are provided for how to configure the database locally in a Docker container for testing and development purposes.

=== PostgreSQL configuration

Get the https://mvnrepository.com/artifact/org.postgresql/postgresql[PostgreSQL JDBC Driver from the Maven Central].

The following example shows a sample data source configuration for a PostgreSQL database:

[source,xml]
----
<dataSource jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="jdbcLib"/>
    <properties.postgresql serverName="localhost" portNumber="5432"
                databaseName="myDB"
                user="exampleUser"
                password="examplePassword"/>
</dataSource>
----

To run a Postgres Docker container locally, run the following command:

[source,command]
----
docker run -it --rm=true --memory-swappiness=0 --ulimit memlock=-1:-1 \
           --name postgres-liberty \
           -e POSTGRES_USER=exampleUser \
           -e POSTGRES_PASSWORD=examplePassword \
           -e POSTGRES_DB=myDB \
           -p 5432:5432 \
           postgres:10.5
----

=== IBM Db2

Get the https://mvnrepository.com/artifact/com.ibm.db2/jcc[IBM Data Server Driver For JDBC and SQLJ from Maven Central].

The following example shows a sample data source configuration for an IBM Db2 database:

[source,xml]
----
<dataSource jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="jdbcLib"/>
    <properties.db2.jcc serverName="localhost" portNumber="50000"
                databaseName="test"
                user="db2inst1"
                password="foobar1234"/>
</dataSource>
----

To run a Db2 Docker container locally, run the following command:

[source,command]
----
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 \
           --name db2-liberty \
           -e AUTOCONFIG=false -e ARCHIVE_LOGS=false -e LICENSE=accept \
           -e DBNAME=test \
           -e Db2INSTANCE=db2inst1 \
           -e Db2INST1_PASSWORD=foobar1234 \
           -p 50000:50000 \
           --privileged \
           ibmcom/db2:11.5.0.0a
----

=== Microsoft SQLServer

Get the  https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc[Microsoft JDBC Driver For SQL Server from Maven Central].

The following example shows a sample data source configuration for a Microsoft SQLServer database:

[source,xml]
----
<dataSource jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="jdbcLib"/>
    <properties.microsoft.sqlserver serverName="localhost" portNumber="1433"
                databaseName="tempdb"
                user="sa"
                password="examplePassw0rd"/>

</dataSource>
----

To run a SQL Server Docker container locally, run the following command:

[source,command]
----
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 \
           --name mssql-liberty \
           -e ACCEPT_EULA=Y \
           -e SA_PASSWORD=examplePassw0rd \
           -p 1433:1433 \
           mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
----

=== MySQL

Get the https://mvnrepository.com/artifact/mysql/mysql-connector-java[MySQL Connector/J JDBC driver from Maven Central].

The following example shows a sample data source configuration for a MySQL database:

[source,xml]
----
<dataSource jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="jdbcLib"/>
    <properties serverName="localhost" portNumber="3306"
                databaseName="myDb"
                user="exampleUser"
                password="examplePassword"/>
</dataSource>
----

To run a MySQL Docker container locally, run the following command:
[source,command]
----
docker run --ulimit memlock=-1:-1 -it --rm=true --memory-swappiness=0 \
           --name mysql-liberty \
           -e MYSQL_DATABASE=myDB \
           -e MYSQL_USER=exampleUser \
           -e MYSQL_PASSWORD=examplePassword \
           -p 3306:3306 \
           mysql:8
----

=== Oracle

Get the  https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc8[Oracle JDBC driver from Maven Central].

The following example shows a sample data source configuration for an Oracle database:

[source,xml]
----
<dataSource jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="jdbcLib"/>
    <properties.oracle URL="jdbc:oracle:thin:@//localhost:1521/myDB"
                user="exampleUser"
                password="examplePassword"/>
</dataSource>
----

=== Embedded Derby

Get the  https://mvnrepository.com/artifact/org.apache.derby/derby/10.14.2.0[Apache Derby Database Engine and Embedded JDBC Driver from Maven Central].

The following example shows a sample data source configuration for a Derby database in an embedded environment:

[source,xml]
----
<dataSource jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="jdbcLib"/>
    <properties.derby.embedded databaseName="memory:myDB" createDatabase="create"/>
</dataSource>
----

=== Generic database that is unknown to Open Liberty

The following example shows a sample data source configuration for a generic database that Open Liberty does not recognize by default. Specify the type of the data source by using the `type` attribute of the `dataSource` element. The value for the `type` attribute can be one of the interface class names that are described in the <<#types,Data source types>> section. Then, specify the mapping of interface class name to the driver implementation of that class on the `jdbcDriver` element, as shown in the following example:

[source,xml]
----
<dataSource id="myDB" jndiName="jdbc/myDB" type="javax.sql.XADataSource">
    <jdbcDriver libraryRef="jdbcLib"
               javax.sql.XADataSource="com.example.jdbc.SampleXADataSource"/>
    <properties serverName="localhost" portNumber="1234"
                databaseName="myDB"
                user="exampleUser"
                password="examplePassword"/>
</dataSource>
----



For more information, see the xref:reference:feature/jdbc-4.2.adoc[Java Database Connectivity feature].

[#types]
=== Data source types

To access a database from your Open Liberty application, your application code must implement the `javax.sql.DataSource` interface. Open liberty provides a managed implementation of this interface, which is backed by the data source or driver implementation that your JDBC driver provides. For Open Liberty, your JDBC driver must provide at least one of the following types of data sources or a `java.sql.Driver` driver implementation with the `ServiceLoader` facility:

- `javax.sql.DataSource`
This type of data source is the basic form. It does not provide the interoperability that enhances connection pooling and cannot participate as a two-phase capable resource in transactions that involve multiple resources.

- `javax.sql.ConnectionPoolDataSource`
This type of data source is enabled for xref:reference:feature/jdbc-4.2.adoc#_connection_pool_configuration[connection pooling]. It cannot participate as a two-phase capable resource in transactions that involve multiple resources.

- `javax.sql.XADataSource`
This type of data source is both enabled for connection pooling and is able to participate as a two-phase capable resource in transactions that involve multiple resources. The `javax.sql.XADataSource` data source type is essentially a superset of the capabilities that are provided by the `javax.sql.DataSource` and `javax.sql.ConnectionPoolDataSource` data source types. However, some JDBC vendors might have subtle differences in behavior or limitations that are not spelled out in the JDBC specification.

- `java.sql.Driver`
The `java.sql.Driver` driver implementation provides a basic way to connect to a database. This implementation requires a URL and is typically used in Java SE applications. Like `javax.sql.DataSource`, it does not provide interoperability that enhances connection pooling and cannot participate as a two-phase capable resource in transactions that involve multiple resources. To work with Open Liberty, this implementation must provide the `ServiceLoader` facility, which Open Liberty uses to discover JDBC driver implementations for a URL.

If the `type` attribute is not specified in the data source configuration, Open Liberty chooses the data source type in the following order, depending on which type is available.

If you are using the xref:reference:feature/jdbc-4.3.adoc[jdbc-4.3 feature] or higher, or if you are referencing <<#default,the default data source>>, Open Liberty chooses the data source type in the following order, depending on availability:

. `javax.sql.XADataSource`
. `javax.sql.ConnectionPoolDataSource`
. `javax.sql.DataSource`

If you are using the xref:reference:feature/jdbc-4.2.adoc[jdbc-4.2], xref:reference:feature/jdbc-4.1.adoc[4.1], or xref:reference:feature/jdbc-4.0.adoc[4.0] feature and you are not referencing the default data source, then Open Liberty chooses the data source type in the following order, availability:

. `javax.sql.ConnectionPoolDataSource`
. `javax.sql.DataSource`
. `javax.sql.XADataSource`

== Application configuration for relational database connections

To use a data source that is  configured in your `server.xml` file, you can either inject or look it up by referencing the value of the `jndiName` attribute in your application code. The following examples assume a `jndiName` value of `jdbc/myDB` is specified in the `dataSource` element in the `server.xml` file.

In a web component or enterprise bean component, you can inject the data source with application code similar to the following example:

[source,java]
----
@Resource(lookup = "jdbc/myDB")
DataSource myDB;
----

If `myDB` is configured as the <<#default,default data source>>, you can omit the `lookup` object, as shown in the following example:

[source,java]
----
@Resource
DataSource myDB;
----

When the xref:reference:feature/jndi-1.0.adoc[Java Naming and Directory Interface feature] is enabled in your `server.xml` file, you can obtain a reference to the data source from your application by JNDI lookup, as shown in the following example:

[source,java]
----
DataSource myDB = InitialContext.doLookup("jdbc/myDB");
----

If `myDB` is configured as the default data source, the JNDI lookup can specify a `java:comp/DefaultDataSource` value instead of the JNDI name for the data source, as shown in the following example:

[source,java]
----
DataSource myDB = InitialContext.doLookup("java:comp/DefaultDataSource");
----



== See also
xref:data-persistence-jpa.adoc[Data persistence with the Java Persistence API]
