// Copyright (c) 2020,20225 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Alternatives to REST
:seo-description:
:page-layout: general-reference
:page-type: general
= Alternatives to REST for client-server communications

Although REST is a widely adopted pattern for communications among microservices, Open Liberty supports alternative options that might be better suited for some application scenarios. These alternatives include GraphQL, gRPC, and WebSocket.

REST is by far the most common architectural style for microservices, thanks to its simplicity, flexibility, and scalability. However, it comes with tradeoffs that can make it a less than ideal solution for some use cases. Issues such as over-fetching and under-fetching of data, lack of real-time communication, and tight coupling between client and server can lead to performance and maintenance concerns for certain types of applications. To address these issues, you can use alternative protocols and frameworks that specifically address the shortcomings of REST.

* xref:microprofile-graphql.adoc[GraphQL]: This open source query language and runtime can simplify retrieving data from multiple sources, such as APIs, databases, and other services. It directly addresses problems with over-fetching and under-fetching of data that might occur with REST APIs.
* xref:web-socket.adoc[WebSocket]: This protocol enables real-time bidirectional communication between a server and one or more clients, which is not feasible in REST architecture.
* xref:grpc-services.adoc[gRPC]: This framework provides efficient data serialization and multiplexing capabilities for high-performance applications that require high throughput and low latency. It also enables efficient communication between services and applications in various languages and platforms.

Ultimately, the framework that you choose depends on the specific needs of your application, including factors like performance requirements, data complexity, and the technologies you're already using.

== See also

link:/guides/#rest_alternatives[Guides: REST alternatives]

// assisted by watsonx with latest GenAI contribution: Granite-3-8b-instruct
