// Copyright (c) 2020,2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Alternatives to REST
:seo-description:
:page-layout: general-reference
:page-type: general
= Alternatives to REST for client-server communications

Although REST is a widely adopted pattern for communications among microservices, Open Liberty supports alternative options that might be better suited for some application scenarios. These alternatives include GraphQl, gRPC, and WebSocket.

Despite the ubiquity of REST-style communication among microservices, REST comes with tradeoffs in capability and performance that can make it a less than ideal solution for some use cases. Issues such as over-fetching and under-fetching of data, lack of real-time communication, and tight coupling between client and server can lead to performance and maintenance concerns for certain types of applications. To address these issues, developers can use alternative protocols and technologies that specifically address the shortcomings of REST.

For example, xref:microprofile-graphql.adoc[GraphQL] is an open source data query and manipulation language for APIs that directly addresses problems with over-fetching and under-fetching of data that might occur with REST APIs. Similarly, the xref:web-socket.adoc[WebSocket] protocol enables real-time bidirectional communication between a server and one or more clients, which is not feasible in REST architecture. High-performance applications that require high throughput and low latency can benefit from the efficient data serialization and multiplexing capabilities that xref:grpc-services.adoc[gRPC] provides.

Ultimately, the framework you choose depends on the specific needs of your application, including factors like performance requirements, data complexity, and the technologies you're already using.

// assisted by watsonx with latest GenAI contribution: Granite-3-8b-instruct
