// Copyright (c) 2020,2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Alternatives to REST
:seo-description:
:page-layout: general-reference
:page-type: general
= Alternatives to REST for client-server communications

Although REST is a widely adopted pattern for communications among microservices, Open Liberty supports alternative options that might be better suited to some application scenarios. These alternatives include GraphQl, gRPC, and WebSocket.

Despite the ubiquity of REST-style communication among microservices, REST comes with tradeoffs in capability and performance that can make it a less than ideal solution for some use cases. Issues such as over-fetching and under-fetching of data, lack of real-time communication, and tight coupling between client and server can lead to performance and maintenance concerns for certain types of applications. To address these issues, developers can use alternative protocols and technologies that specifically address the shortcomings of REST. 

For example, GraphQL is an open source data query and manipulation language for APIs that directly addresses problems with over-fetching and under-fetching of data that might occur with REST APIs. Similarly, WebSocket is a protocol that enables real-time bidirectional communication between a server and one or more clients, which is not feasible in REST architecture.


The following topics provide information about REST alternatives that you can implement with Open Liberty.

xref:microprofile-graphql.adoc[Build GraphQL applications with MicroProfile GraphQL]::
MicroProfile GraphQL is an API for building services that exercise fine-grained control over the data that they request and receive. A GraphQL service can simplify data retrieval by collating data from multiple sources into a single object.

xref:grpc-services.adoc[Provide and consume gRPC services on Open Liberty]::
gRPC is an open source remote procedural call (RPC) framework that connects clients and services in language-agnostic way. You can provide and consume gRPC services from your web applications that run on Open Liberty.

xref:web-socket.adoc[Send bidirectional messages between services with WebSocket]::
The WebSocket protocol supports real-time bidirectional messaging between a client and server. The Open Liberty Jakarta WebSocket feature supports applications that use this protocol.

