// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: This task demonstrates run an Open Liberty application with Federal Information Processing Standards (FIPS) enabled.
:seo-title: Running Open Liberty in a FIPS-enabled cluster - OpenLiberty.io
:seo-description: This task demonstrates run an Open Liberty application with Federal Information Processing Standards (FIPS) enabled.
:page-layout: general-reference
:page-type: general
= Running Open Liberty in a FIPS-enabled cluster

This task demonstrates how to run an Open Liberty application with Federal Information Processing Standards (FIPS) enabled by doing the following things:

. <<create-image-fips,Creating an Open Liberty Docker image that has FIPS enabled>>
. <<deploy-image-cluster,Deploying the Open Liberty image to your OpenShift Cluster>>
. <<verify-fips,Verifying that FIPS is enabled on the Open Liberty server>>

== Before you begin

* Deploy an OpenShift Container Platform (OCP) cluster.
If you want to run Open Liberty on a FIPS-enabled OCP cluster, see the https://docs.openshift.com/container-platform/4.6/installing/installing-fips.html[OpenShift documentation].
* Install the xref:open-liberty-operator.adoc[Open Liberty Operator].

[#create-image-fips]
== Creating an Open Liberty Docker image that has FIPS enabled

. https://github.com/OpenLiberty/ci.docker#container-images[Create an Open Liberty Docker image]. To enable FIPS for Open Liberty, use the Open Liberty image that uses the IBM JDK.

. Ensure that SSL is enabled for your Open Liberty server by adding the feature:transportSecurity[display=Transport Security feature] (`transportSecurity-1.0`) to your `server.xml` file.

. Set the `com.ibm.jsse2.usefipsprovider` system property to enable FIPS mode in the `IBMJSSE2` provider.
To set this property, create or update the `jvm.options` file in the server configuration directory, as shown in the following example:
+
----
#cat jvm.options
-Dcom.ibm.jsse2.usefipsprovider=true
----

. Ensure that the `com.ibm.crypto.fips.provider.IBMJCEFIPS` Java Cryptography Extension (JCE) FIPS provider is included in the provider list in the `java.security` file, which is located in the `JAVA_HOME/jre/lib/security` directory.

. Run the https://www.openshift.com/blog/transferring-files-in-and-out-of-containers-in-openshift-part-1-manually-copying-files[oc rsync command] and the `vi` command to copy the `java.security` file from the existing Open Liberty container with the IBM JDK and update it to add the FIPS provider:
+
----
$ oc rsync <pod-name>:/opt/ibm/java/jre/lib/security/java.security .
$ vi java.security
----
+
If the FIPS provider is successfully updated, you see the following output:
+
----
#Added the security.provider.1=com.ibm.crypto.fips.provider.IBMJCEFIPS on top
security.provider.1=com.ibm.crypto.fips.provider.IBMJCEFIPS
----

. Check that the `server.xml`, `jvm.options`, and `java.security` files were updated to the appropriate locations, as shown in the following example:
+
----
FROM openliberty/open-liberty:20.0.0.12-full-java8-ibmjava-ubi

COPY --chown=1001:0 src/main/liberty/config /config/
COPY --chown=1001:0 <app> /config/apps
COPY --chown=1001:0 java.security /opt/ibm/java/jre/lib/security
RUN configure.sh
----

. Login to your OCP cluster by using the `oc login` command.

. Create a project for your Open Liberty application by running the following command:
+
----
$ oc new-project ol-app
----

. Run the following command to build the updated Open Liberty image:
+
----
$ docker build -t <image_name> -f Dockerfile.ibmjdk .
----

. Log in to your image registry and push the image.
In this example, we use the OCP internal registry:
+
----
$ docker tag default-route-openshift-image-registry.apps.example.ibm.com/ol-app/<image_name>
$ docker push default-route-openshift-image-registry.apps.example.ibm.com/ol-app/<image_name>
----

[#deploy-image-cluster]
== Deploying the Open Liberty image to your OpenShift Cluster
In this example, we use the Open Liberty Operator to deploy the Open Liberty image.
It's important that route for the application is enabled so that SSL can use FIPS.
The following example file shows how you might configure the Open Liberty Operator for deployment to an OCP cluster:

----
$ cat app-deploy_ssl.yaml
apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: inventory-ibmjdk
spec:
  replicas: 1
  applicationImage: default-route-openshift-image-registry.apps.example.ibm.com/ol-app/inventory_ibmjdk
  expose: true
  route:
    termination: reencrypt
  service:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: inventory-ibmjdk-svc-tls
    certificateSecretRef: inventory-ibmjdk-svc-tls
    port: 9443
----

. Deploy the application to OCP by running the following command:
+
----
$ oc deploy -f app-deploy_ssl.yaml
----

. Check the pod and route of your application:
+
----
$ oc get pods
inventory-ibmjdk-687487479-4rxk7   1/1     Running   0          36h
$ oc get routes|grep jdk
inventory-ibmjdk   inventory-ibmjdk-ol-app.apps.example.ibm.com          inventory-ibmjdk   9443-tcp   reencrypt     None
----

. Open a browser and access the route that was returned in the previous step, for example, https://inventory-ibmjdk-ol-app.apps.example.ibm.com.

[#verify-fips]
== Verifying that FIPS is enabled on the Open Liberty server

. Enable trace by updating the `jvm.options` file to add the following property and rebuild the Open Liberty image and redeploy the new image to OCP:
+
----
-Djavax.net.debug=all
----

. Access the Open Liberty application at the same route that you accessed in the previous section, for example, https://inventory-ibmjdk-ol-app.apps.example.ibm.com.

. Check the logs on the Open Liberty container, as shown in the following example:
+
----
$oc rsh inventory-ibmjdk-687487479-4rxk7 bash
bash-4.4$ more /logs/messages.log
...
[12/10/20 1:39:30:329 UTC] 0000002a SystemOut                                                    O IBMJSSE2 will use default FIPS provider IBMJCEFIP
S
[12/10/20 1:39:30:330 UTC] 0000002a SystemOut                                                    O Installed Providers =
[12/10/20 1:39:30:331 UTC] 0000002a SystemOut                                                    O      IBMJCEFIPS
[12/10/20 1:39:30:331 UTC] 0000002a SystemOut                                                    O      IBMJSSE2
[12/10/20 1:39:30:331 UTC] 0000002a Syste mOut                                                    O      IBMJCE
[12/10/20 1:39:30:332 UTC] 0000002a SystemOut
...
$  grep ClientHello /logs/messages.log
[12/10/20 1:41:05:885 UTC] 00000042 SystemOut                                                    O *** ClientHello, TLSv1.2
----
