// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: MicroProfile helps developers to design and implement cloud-native applications that follow the twelve-factor methodology using microservices.
:seo-title: Designing cloud-native microservices
:seo-description: MicroProfile helps developers to design and implement cloud-native applications that follow the twelve-factor methodology using microservices.
:page-layout: general-reference
:page-type: general
= Securing cloud-native microservices

Securing your application from vulnerabilities is important.
It is helpful to ensure application security earlier and rather than later during development, to prevent  unauthorized access to your application.

xref:authentication.adoc[Authentication] ensures  user identity.
When users try to access your application you need to verify if the users are what they claim to be.

Authorization (link to authorization topic)(xref:authorization.adoc) ensures that the user has the right permissions to access the information they request.
You can assign roles to users and groups to authorize user access to different resources.

You can use different authentication and authorization strategies to secure your application during development and production.

== For development purposes

You can create a basic registry, which is a text-based user registry(xref:user-registries-application-security.html#_basic_user_registries_for_application_development), directly in the applications `server.xml` file, or a quickstart registry if you just need a single user for a start. (Link: User registries topic (ideally to the basic registries section - talk to David about adding anchors to the sections in that topic?).
You can also encrypt the password so it's not stored in plain text in your app: Link: securityUtility command (xref:password-encryption.adoc). For more information on securing your application, see Link: "Securing a web application" guide(xref:security-intro.adoc).


For production purposes

For production, you can use Single sign-on (SSO) so that the user can log into the application without creating a separate account.
If there already exists a user registry, for example, an LDAP registry, you could set up authentication with Security Assertion Markup Language (SAML)(xref:single-sign-on.adoc#_saml). Or in the case of  Windows Active Directory, you can use Simple and Protected GSS-API Negotiation (SPNEGO)(single-sign-on.adoc#_spnego) for authentication.
If there aren't requirements to use an existing user registry, you could just use a social media provider, for example, the Social Media Login feature (single-sign-on.adoc#_social_media_login),  so that the social media platform manages the user registry and login procedure for you.( Link: Social media login guide ,not quite published yet but will be soon)(xref:social-login.adoc).

To permit services within the application to access info from other services on behalf of the user, your application needs to generate a JWT which the service can send with its request to another service to show it has permission to request that info. Link: JWT guide(xref:microprofile-jwt.adoc). (Also https://openliberty.io/blog/2019/08/29/securing-microservices-social-login-jwt.html but maybe not the best place to link to? Not sure - see what you think).
Encrypt traffic between services with TLS so that no one can intercept data or tokens being transmitted between services or between the client and a service.

Finally, before production, make sure you work through the advice for hardening your app in Link: Security hardening for production topics.
