// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: MicroProfile helps developers to design and implement cloud-native applications that follow the twelve-factor methodology using microservices.
:seo-title: Designing cloud-native microservices
:seo-description: MicroProfile helps developers to design and implement cloud-native applications that follow the twelve-factor methodology using microservices.
:page-layout: general-reference
:page-type: general
= Securing cloud-native microservices

Securing your application from vulnerabilities is important.
It is helpful to ensure application security earlier and rather than later during development, to prevent  unauthorized access to your application.

xref:authentication.adoc[Authentication] ensures  user identity.
When users try to access your application you need to verify if the users are what they claim to be.

xref:authorization.adoc[Authorization] ensures that the user has the right permissions to access the information they request.
You can assign roles to users and groups to authorize user access to different resources.

You can use different authentication and authorization strategies to secure your application during development and production.

== For development purposes

You can create a basic registry, which is a text-based xref:user-registries-application-security.html#_basic_user_registries_for_application_development[user registry], directly in the applications `server.xml` file, or a quickstart registry if you just need a single user for a start.
You can also xref:password-encryption.adoc[encrypt] the password so it's not stored in plain text in your application. For more information on securing your application, see the xref:security-intro.adoc[Securing a web application] guide.


== For production purposes

For production, you can use xref:single-sign-on.adoc[Single sign-on] (SSO) so that the user can log into the application without creating a separate account.
If there already exists a user registry, for example, an Lightweight Directory Access Protocol (LDAP) registry, you could set up authentication with xref:single-sign-on.adoc#_saml[Security Assertion Markup Language] (SAML).
Or in the case of  Windows Active Directory, you can use single-sign-on.adoc#_spnego[Simple and Protected GSS-API Negotiation] (SPNEGO) for authentication.
If there aren't requirements to use an existing user registry, you could just use a social media provider, for example, the Social Media Login feature (single-sign-on.adoc#_social_media_login), so that the social media platform manages the user registry and login procedure for you.for more information see, xref:social-login.adoc[Social media login] guide.

To permit services within the application to access info from other services on behalf of the user, your application needs to generate a xref:microprofile-jwt.adoc[JSON web token] JWT which the service can send with its request to another service to show it has permission to request that info.
Encrypt traffic between services with secure-communication-tls.adoc[Transport Layer Security] 9TLS0 so that no one can intercept data or tokens being transmitted between services or between the client and a service.

Finally, before production, make sure you work through the advice for xref:secure-communication-tls.adoc[hardening] your application.
