// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: It is important to harden your Open Liberty server for production to reduce vulnerabilities and prevent security intrusions.
:seo-title: Security hardening for production - OpenLiberty.io
:seo-description: It is important to harden your Open Liberty server for production to reduce vulnerabilities and prevent security intrusions.
:page-layout: general-reference
:page-type: general
= Security hardening for production

Hardening is a general term that is used to describe the measures that are taken to enhance your system security against potential threats and risks in production.
Harden your Open Liberty server configuration, application configuration, and network to reduce vulnerabilities and prevent security intrusions.

Different types of security intrusions can threaten different parts of your system.
You can employ best practices to make each part less vulnerable.
Security intrusions and vulnerabilities can be broken down into different groups:

* <<#server-configuration,Server configuration>>
* <<#network,Network>>
* <<#application-configuration,Application configuration>>


== Liberty CIS benchmarks
The https://www.cisecurity.org[Center for Internet Security] (CIS) benchmarks are a collection of industry-wide cybersecurity standards to configure networked digital resources and ensure their compliance with the established best practices for security and privacy. Open Liberty maintains security hardening guidelines that comply with the CIS benchmark standards.

You can access the benchmarks on the https://www.cisecurity.org/benchmark/websphere[CIS IBM WebSphere Benchmarks] page. Complete the information form to download the benchmarks.

If you have a free CIS user account, you can open tickets to address any questions or concerns with the benchmarks in the https://workbench.cisecurity.org/benchmarks/7724[Liberty benchmarks user portal].


[#server-configuration]
== Server configuration
Operating system intrusions occur when users with local access attempt to cause damage or extract sensitive information.
One example of this type of intrusion is malware.
If malware is introduced into a system, unauthorized users might be able to access the server configuration and its contents.
For more information, see xref:server-configuration-hardening.adoc[Server configuration security hardening].

=== Server configuration hardening best practices
* <<server-configuration-hardening.adoc#basic-best-practices,Follow basic guidelines to harden your Open Liberty server configuration.>>
* <<server-configuration-hardening.adoc#ol-images,Verify that your container image is secure for production.>>
* <<server-configuration-hardening.adoc#current-version,Stay up to date with Open Liberty.>>
* <<server-configuration-hardening.adoc#installation-validation,Validate your Open Liberty server installation.>>
* <<server-configuration-hardening.adoc#unix-file-permissions,Carefully configure file permissions.>>
* <<server-configuration-hardening.adoc#access-control,Control users' access based on their needs.>>
* <<server-configuration-hardening.adoc#user-registries,Choose a user registry option that is safe for production environments.>>
* <<server-configuration-hardening.adoc#include-file-processing, Use include files to hold portions of the configuration outside of the server.xml file when necessary.>>
* <<server-configuration-hardening.adoc#automated-updates,Disable automated configuration updates.>>
* <<server-configuration-hardening.adoc#client-data,Encrypt client data at rest, such as passwords.>>
* <<server-configuration-hardening.adoc#password-encryption,Use AES encryption for passwords.>>

[#network]
== Network
Network intrusions occur when unauthorized users monitor or alter network traffic.
Replay attacks and man-in-the-middle (MITM) attacks are two examples of network intrusions.
For more information, see xref:network-hardening.adoc[Network security hardening].

=== Network hardening best practices
* <<network-hardening.adoc#firewalls,Run production environments inside a firewall.>>
* <<network-hardening.adoc#rate-limiting,Enforce rate limitations>>
* <<network-hardening.adoc#security-in-containers,In container environments, isolate workloads from one another across a cluster of nodes.>>
* <<network-hardening.adoc#tls,Enable the Transport Security feature.>>
* <<network-hardening.adoc#ltpa,Follow Lightweight Third-Party Authentication (LTPA) single sign-on (SSO) best practices.>>
* <<network-hardening.adoc#virtual-hosts,Configure applications to run on a virtual host.>>
* <<network-hardening.adoc#welcome-page-headers,Disable the default Open Liberty welcome page and headers.>>
* <<network-hardening.adoc#session-overflow,Restrict the number of sessions that can be created for applications that use in-memory sessions.>>
* <<network-hardening.adoc#jmx-connector,If you use IBM HTTP Server, secure access to the Open Liberty JMX connector.>>

[#application-configuration]
== Application configuration
Application configuration intrusions occur when external users run applications that derive or inherit privileges that they are not authorized to have.
One example of this type of intrusion happens when an application inherits the identity of the server, giving the application unauthorized permissions.
For more information, see xref:application-configuration-hardening.adoc[Application configuration security hardening].

=== Application configuration hardening best practices
* <<application-configuration-hardening.adoc#user-roles-access,Carefully map roles.>>
* <<application-configuration-hardening.adoc#web-server-document-root,Keep sensitive information out of the WAR root.>>
* <<application-configuration-hardening.adoc#secure-servlets,Ensure that servlets are secured.>>
* <<application-configuration-hardening.adoc#file-serving-dir-browsing,Disable file serving and directory browsing.>>
* <<application-configuration-hardening.adoc#confidential-transport-guarantee,Require a confidential transport guarantee between the client and the server.>>
