// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Securing your application from vulnerabilities helps to make sure that your application is secure earlier, rather than later during development.
:seo-title: Designing cloud-native microservices
:seo-description: Securing your application from vulnerabilities helps to make sure that your application is secure earlier, rather than later during development.
:page-layout: general-reference
:page-type: general
= Securing cloud-native microservices

Securing your application from vulnerabilities is important.
It is helpful to make sure that your application is secure earlier, rather than later during development, to prevent unauthorized access to your application.

xref:authentication.adoc[Authentication] ensures  user identity.
When users try to access your application you need to verify if the users are who they claim to be.

xref:authorization.adoc[Authorization] ensures that the user has the right permissions to access the information they request.
You can assign roles to users and groups to authorize user access to different resources.

A user might be the employee of an organization who wants to log into the organization system for regular work.
The user might sometimes need to access external resources subscribed by the organization, for example, a peer reviewed journal.
It is important to identify the user and direct them to the right resources.
It is also important make sure that there are no security vulnerabilities in the system, or any unauthorized access to resources.
Authentication will ensure the identity of the user and give user access to the system.
Authorization will further filter user access based on the role of the user, and the groups that the user belongs to.
Single sign-on makes it easier for the user to log into external resources as it saves time and effort.

In the following diagram, a user requests access to the organization protected resources.
During authentication, the user request is routed to an Open ID Connect identity provider, which confirms the user identity and security roles.
The identity provider sends authentication data back to the application, where it is used to authorize user access to protected resources.
During authorization, Open Liberty checks the roles that are specified for the user against the roles that are defined for the application resources. The user is granted access to any resources that match their role.

(The illustration will be here)

You can use different authentication and authorization strategies to secure your application during development and production.

== For development purposes

You can create a basic registry, which is a text-based xref:user-registries-application-security.adoc#_basic_user_registries_for_application_development[user registry], directly in the applications `server.xml` file, or a quickstart registry if you just need a single user for a start.
You can also xref:password-encryption.adoc[encrypt] the password so it's not stored in plain text in your application. For more information on securing your application, see the link:/guides/security-intro.html[Securing a web application] guide.


== For production purposes

For production, you can use xref:single-sign-on.adoc[Single sign-on] (SSO), for example, Open ID Connect (OIDC), so that the user can log into the application without creating a separate account.
If there already exists a user registry, for example, an Lightweight Directory Access Protocol (LDAP) registry, you could set up authentication with xref:single-sign-on.adoc#_saml[Security Assertion Markup Language] (SAML).
Or in the case of  Windows Active Directory, you can use xref:single-sign-on.adoc#_spnego[Simple and Protected GSS-API Negotiation] (SPNEGO) for authentication.
If there aren't requirements to use an existing user registry, you could just use a social media provider, for example, the xref:single-sign-on.adoc#_social_media_login[Social Media Login] feature, so that the social media platform manages the user registry and login procedure for you.for more information see, link:/guides/social-media-login.html[Social media login] guide.

To permit services within the application to access info from other services on behalf of the user, your application needs to generate a link:/guides/microprofile-jwt.html[JSON web token] JWT which the service can send with its request to another service to show it has permission to request that info.
Encrypt traffic between services with xref:secure-communication-tls.adoc[Transport Layer Security] (TLS) so that no one can intercept data or tokens being transmitted between services or between the client and a service.

Finally, before production, make sure you work through the advice for xref:security-hardening.adoc[hardening] your application.
