// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: It is important to harden your Open Liberty server for production to reduce vulnerabilities and prevent security intrusions.
:seo-title: Security hardening for production - OpenLiberty.io
:seo-description: It is important to harden your Open Liberty server for production to reduce vulnerabilities and prevent security intrusions.
:page-layout: general-reference
:page-type: general
= Security hardening for production

Hardening is a general term that is used to describe the measures that are taken to enhance your system security against potential threats and risks in production.
It is important to harden your Open Liberty server configuration, application configuration, and network to reduce vulnerabilities and prevent security intrusions.

Different types of security intrusions can threaten different parts of your system.
You can employ best practices to make each part less vulnerable.
Security intrusions and vulnerabilities can be broken down into different groups:

* <<#server-configuration,Server configuration>>
* <<#network,Network>>
* <<#application-configuration,Application configuration>>

[#server-configuration]
== Server configuration
Operating system (OS) intrusions occur when users with local access attempt to cause damage or extract sensitive information.
One example of this type of intrusion is malware.
If malware is introduced into a system, unauthorized users might be able to access the server configuration and its contents.

=== Server configuration hardening best practices
* <<server-configuration-hardening.adoc#basic-best-practices,Follow basic guidelines to harden your Open Liberty server configuration.>>
* <<server-configuration-hardening.adoc#ol-docker-images,Verify that your Docker image is secure for production.>>
* <<server-configuration-hardening.adoc#current-version,Stay up to date with Open Liberty.>>
* <<server-configuration-hardening.adoc#installation-validation,Validate your Open Liberty server installation.>>
* <<server-configuration-hardening.adoc#unix-file-permissions,Carefully configure file permissions.>>
* <<server-configuration-hardening.adoc#access-control,Control users' access based on their needs.>>
* <<server-configuration-hardening.adoc#include-file-processing, Use include files to hold portions of the configuration when necessary.>>
* <<server-configuration-hardening.adoc#automated-updates,Disable automated configuration updates.>>
* <<server-configuration-hardening.adoc#password-encryption,Use AES encryption for passwords.>>

[#network]
== Network
Network intrusions occur when unauthorized users monitor or alter network traffic.
Replay attacks and man-in-the-middle (MITM) attacks are two examples of network intrusions.

=== Network hardening best practices
* <<network-hardening.adoc#firewalls,Run production environments inside a firewall.>>
* <<network-hardening.adoc#security-in-containers,In container environments, isolate workloads from one another across a cluster of nodes.>>
* <<network-hardening.adoc#tls,Enable the Transport Security feature.>>
* <<network-hardening.adoc#ltpa,Follow Lightweight Third-Party Authentication (LTPA) single sign-on (SSO) best practices.>>
* <<network-hardening.adoc#welcome-page-headers,Disable the default Open Liberty welcome page and headers.>>
* <<network-hardening.adoc#session-overflow,Restrict the number of sessions that can be created for applications.>>
* <<network-hardening.adoc#jmx-connector,If you use IBM HTTP Server (IHS), secure access to the Open Liberty JMX connector.>>

[#application-configuration]
== Application configuration
Application configuration intrusions occur when external users run applications that derive or inherit privileges that they are not authorized to.
One example of this type of intrusion happens when an application inherits the identity of the server, giving the application unauthorized permissions.

=== Application configuration hardening best practices
* <<application-configuration-hardening.adoc#user-roles-access,Carefully map user roles.>>
* <<application-configuration-hardening.adoc#web-server-document-root,Keep sensitive information out of the WAR root.>>
* <<application-configuration-hardening.adoc#secure-servlets,Ensure that servlets are secured.>>
* <<application-configuration-hardening.adoc#file-serving-dir-browsing,Disable file serving and directory browsing.>>
* <<application-configuration-hardening.adoc#confidential-transport-guarantee,Require a confidential transport guarantee between client and server.>>
