
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Securing your application from vulnerabilities helps to make sure that your application is secure earlier, rather than later during development.
:seo-title: Designing cloud-native microservices
:seo-description: Securing your application from vulnerabilities helps to make sure that your application is secure earlier, rather than later during development.
:page-layout: general-reference
:page-type: general
= Securing cloud-native microservices

Securing your application from vulnerabilities is important to prevent unauthorized access to your application.
Make sure that your application is secure earlier, rather than later during development, and not overlook the important security steps only to revisit them later.


If you are writing an application for a company employee directory, you can use Lightweight Directory Access Protocol (LDAP) for authentication, which makes traffic confidential and secure by using Transport Layer Security (TLS).
The identity provider sends authentication data back to the application, where it's used to authorize user access to protected resources.
You can further authorize access to the users of your of application based on their groups and roles.
For example, someone with a manager’s role can have a broader access to protected resources than someone with the role of an employee.
xref:authentication.adoc[Authentication] verifies the identity of the user and give user access to the system.
xref:authorization.adoc[Authorization] further filters user access based on the role of the user, and the groups that the user belongs to.
With single sign-on, the user to log into external resources, without the need for a separate account.

In the following diagram, Open Liberty acts as an OIDC provider where a client application requests the identity of the user as an ID token.
The client application, or Relying Party, requests information about a user from an OIDC Provider, or Open Liberty in this scenario.
After the users are authenticated by Open Liberty, they can access any Relying Party that is configured for Open Liberty, without having to manage unique accounts for each application or website.

(The illustration displayed here)

You can use different authentication and authorization strategies to secure your application during development and production.

== For development purposes

You can create a basic registry, which is a text-based xref:user-registries-application-security.adoc#_basic_user_registries_for_application_development[user registry], directly in the applications `server.xml` file, or a quickstart registry if you need a single user for a start.
You can also xref:password-encryption.adoc[encrypt] the password so it's not stored in plain text in your application.
For more information on securing your application, see the link:/guides/security-intro.html[Securing a web application] guide.


== For production purposes

For production, you can use xref:single-sign-on.adoc[Single sign-on] (SSO), for example, Open ID Connect (OIDC), so that the user can log in to the application without creating a separate account.
If there exists a user registry, for example, a Lightweight Directory Access Protocol (LDAP) registry, you can set up authentication with xref:single-sign-on.adoc#_saml[Security Assertion Markup Language] (SAML).
For Windows Active Directory, you can use xref:single-sign-on.adoc#_spnego[Simple and Protected GSS-API Negotiation] (SPNEGO) for authentication.
If there aren't requirements to use an existing user registry, you can use a social media provider, for example, the xref:single-sign-on.adoc#_social_media_login[Social Media Login] feature, so that the social media platform manages the user registry and login procedure for you.
For more information see, link:/guides/social-media-login.html[Social media login] guide.

Within the application, if you want to permit services to access information from other services on behalf of the user, your application needs to generate a link:/guides/microprofile-jwt.html[JSON web token] (JWT).
The service can send a JSON web token with its request to another service to that show it has permission to request that information.
Encrypt traffic between services with xref:secure-communication-tls.adoc[Transport Layer Security] (TLS) so that no one can intercept data or tokens being transmitted between services or between the client and a service.

Finally, before production, make sure that you work through the advice for xref:security-hardening.adoc[hardening] your application.
