:page-layout: general-reference
:page-type: general
:page-description:
:page-categories:
:seo-title: Send and receive multipart/form-data parts in JAX-RS
:seo-description:

= Send and receive multipart/form-data parts in JAX-RS

Multipart/form-data is a popular encoding type for HTTP requests that is used to send different types file data in a single request. You can configure JAX-RS resources that run on Open Liberty to send and receive multipart/form-data payloads to and from clients.

Multipart/form-data is an encoding type that enables an HTTP POST request to send different types of file data as parts of the same request. This encoding type is often used for form data in web applications, such as a form that allows you to upload your resume, a photo, and text for your name and address. JAX-RS resources can implement the multipart/form-data  encoding type to receive form data such as this from a client. They can also use this encoding type to send multipart payloads back to a client in response to an HTTP GET request.

You can send and receive multipart/form-data parts with JAX-RS resources in Open Liberty by enabling the feature:jaxrs[display=Java RESTful Services] feature and implementing the necessary methods in the JAX-RS resource code.

== Send multipart/form-data parts from JAX-RS resources

To send a multipart payload, you must send an array of objects as an instance of the `List<IAttachment>` method. Each object in that array represents a single attachment part. The following JAX-RS method example creates and sends a multipart request from a JAX-RS client:

[source,java]
----
List<IAttachment> attachments = new ArrayList<>();

attachments.add(AttachmentBuilder.newBuilder("fileid")
                                 .inputStream(new ByteArrayInputStream("person1234".getBytes()))
                                 .build());

attachments.add(AttachmentBuilder.newBuilder("description")
                                 .inputStream(new ByteArrayInputStream("XML file about person1234".getBytes()))
                                 .build());

File file = new File("/path/to/multipart-response/person.xml");
attachments.add(AttachmentBuilder.newBuilder("thefile")
                                 .inputStream("person.xml",new FileInputStream(file))
                                 .contentType(MediaType.APPLICATION_XML_TYPE)
                                 .build());

Client c = ClientBuilder.newClient();
WebTarget target = c.target("http://localhost:9080/myMultipartApp/person");
Response r = target.request(MediaType.TEXT_PLAIN)
                   .header("Content-Type", "multipart/form-data")
                   .post(Entity.entity(attachments, MediaType.MULTIPART_FORM_DATA_TYPE));

if(r.getStatus()==200 && "test".equals(r.readEntity(String.class)) {
    System.out.println("multipart upload succeeded");
}
----

In this example, the JAX-RS resource implements a method to send an XML file, along with an ID and description for the file, to a client in the same `POST` request.

If you are sending multipart payloads, do not close the InputStream class. Open Liberty closes it for you after the data is sent.  The server throws an `IOException` exception if the stream is closed beforehand. 

== Receive multipart/form-data parts with JAX-RS resources

To receive a multipart payload from an HTML form, a JAX-RS resource must implement a method to receive the multipart/form-data parts of an HTTP POST request. The following example shows an HTML form

[source,HTML]
----
<form action="http://www.example.com/" method="POST" enctype="multipart/form-data">
    <input type="text" name="fileid" />
    <br />
    <input type="text" name="description" />
    <br />
    <input type="file" name="thefile" />
    <br />
    <input type="submit" name="submit" value="submit"/>
</form>
----

To receive file data from a form such as this, you must declare a JAX-RS resource method to receive and echo multipart/form-data encoded content from an HTTP POST request, as shown in the following example:

[source,java]
----
@POST
@Consumes("multipart/form-data")
public Response postFormData(List <IAttachment> attachments) throws IOException{
    InputStream stream = null;
    for (IAttachment attachment : attachments) {
         if (attachment == null) {
             continue;
         }
         stream = attachment.getDataHandler().getInputStream();
         String fileName = null;
         String contentType = attachment.getDataHandler().getContentType();
         if (contentType != null && contentType.startsWith("application/octet-stream")) {
            fileName = attachment.getDataHandler().getName();
         }
         if (fileName == null) {
             StringBuilder sb = new StringBuilder();
             BufferedReader br = new BufferedReader(new InputStreamReader(stream));
             String line = null;
             try {
                 while ((line = br.readLine()) != null) {
                     sb.append(line);
                 }
             } catch (IOException e) {
                 e.printStackTrace();
             } finally {
                 if (br != null) {
                     try {
                         br.close();
                     } catch (IOException e) {
                         e.printStackTrace();
                     }
                 }
             }
             System.out.println("Non-file attachment value: " + sb.toString());
         } else {
             //handle the file as you want
             File tempFile = new File(fileName);
             System.out.println("File: " + tempFile.getAbsolutePath());
         }
    }
    if (stream != null) {
        stream.close();
    }
    return Response.ok("test").build();
}
----

You can implement your JAX-RS resource method to receive the data in parts, so you can process these parts yourself, if needed. The originator of the HTML form POST submission can generate a `Content-Transfer-Encoding` header for one or more parts of the multipart message. The JAX-RS resource attempts to auto-decode the payload of each part according to this header when the header is of `base64` or `quoted-printable` encoding type.

When you are receiving multipart payloads, Open Liberty does not close the `InputStream` class because the server does not know when the user application is done processing it.

== See also
