// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty operates from a set of built-in configuration default settings, and you can override default settings by editing the `server.xml` file. The features that you specify in the server configuration provide functionality for your application.
:seo-title: Server configuration and feature introduction - OpenLiberty.io
:seo-description: Open Liberty operates from a set of built-in configuration default settings, and you can override default settings by editing the `server.xml` file. The features that you specify in the server configuration provide functionality for your application.
:page-layout: general-reference
:page-type: general
:projectName: Open Liberty
= Server configuration and feature introduction

Open Liberty operates from a set of built-in configuration default settings, and you can override default settings by editing the `server.xml` file.
The features that you specify in the server configuration provide functionality for your application.

== Server configuration
include::reference:page$config/server-configuration-overview.adoc[tag=xml-intro]

The following files are also available to configure different aspects of your server configuration:

include::reference:page$config/server-configuration-overview.adoc[tag=file-intro]

If necessary, you can separate the server configuration into multiple files and use include files so that different people can manage the server configuration with different permissions.
You can also use variables to parameterize the server configuration.
include::reference:page$config/server-configuration-overview.adoc[tag=variable-sub-intro]

For more information about variable substition with Open Liberty, see the xref:reference:config/server-configuration-overview#variable-substitution.adoc[Variable substitution precedence section of the server configuration overview].

include::reference:page$config/server-configuration-overview.adoc[tag=dynamic-updates-intro]

For more details about the Open Liberty server configuration, see the xref:reference:config/server-configuration-overview.adoc[server configuration overview].

== Features
With Open Liberty, you can add and remove modular features to the Open Liberty kernel, depending on the capabilities that your application needs.
include::reference:page$feature/feature-overview.adoc[tag=feature-intro]
include::reference:page$feature/feature-overview.adoc[tag=feature-intro-2]

include::reference:page$feature/feature-overview.adoc[tag=using-features-intro]
include::reference:page$feature/feature-overview.adoc[tag=combining-intro]

For more details about Open Liberty features, see the xref:reference:feature/feature-overview.adoc[feature overview].
