:page-layout: general-reference
:page-type: general
:page-description: The request timing feature automatically detects slow requests and logs the information when the request is completed.
:page-categories: MicroProfile
:seo-title: The request timing feature automatically detects slow and hung requests
:seo-description: The request timing feature automatically detects slow and hung requests and logs the information when the request is completed.
= Slow and hung request detection

When an application takes longer than expected to complete a request, the request is logged as slow or hung.
Applications need a continuous monitoring tool to detect and analyze slow and hung requests.
The link:https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html[Request Timing] feature automatically detects slow and hung requests and provides detailed information to help you find the root cause.

The Request Timing feature identifies requests that run longer than a slow request threshold.
For each request that takes longer to complete, the Request Timing feature prints a warning message into the log file, with details about the request.
The Request Timing feature prints a maximum of three messages per slow request after which the feature stops monitoring the request.
The Request Timing feature assigns a request ID to a slow or hung request and logs the ID along with the completion time and other information about the request.

The Request Timing feature also detects hung requests.
The hung request detection works similarly to slow request detection.
When a request runs longer than a hung request threshold, the request is considered as hung.
The Request Timing feature initiates Java cores for a hung request, and prints a warning message with the relevant details.
Three Java cores are generated for a hung request, each core generated a minute apart.
If a previously hung request is completed, a detailed message is logged, including the ID and time of completion of the request.

A request can be slow because its code path length is long, or because a resource, which the request depends on, is busy.
For a slow request, users need to know what actions occurred during the processing of that request, and where in the request the processing is at.
Requests that take longer are typically blocked by lack of access to a shared resource, for example, a section of code that allows only serial access and transfers information sequentially.
Such longer requests are likely to be hung, and can be blocked for a long time or even indefinitely.
One particular form of hung request, called a deadlock, occurs when two threads are blocked waiting on each other to return shared resources.
For a hung request, users need to know where all the threads are at in their processing, and which locks the threads are waiting on.

The Request Timing feature runs continuously, and documents slow and hung requests as and when the requests occur, without the need for problem recreation to collect more data.
In addition to the global settings for slow and hung request thresholds, you can set thresholds for specific servlets or JDBC requests.
For more information about configuration, see the link:/docs/ref/feature/#requestTiming-1.0.html[Request Timing] feature.

== Detect slow requests

When a request runs longer than the slow request threshold, the Request Timing feature generates a warning message in the messages log file.
The message includes details about the request and events that create the request.
The default threshold value is 10 seconds.

The following example shows the format of a log message:

[source,java]
----
TRAS0112W: Request <(Request ID)> has been running on thread <THREADID> for at least <DURATION>. The following stack trace shows that this thread is currently running.
<STACK TRACE>
<DURATION AND OPERATIONS Table>
----

The message helps you analyze the reason for the slow request, though it's uncertain whether the request is hung at that point or is still running slowly.
To address this issue, the Request Timing feature displays three messages for any slow request at the interval that is specified by the `slowRequestThreshold` attribute.
The stack trace data gives the information about the method, while the request data gives details about the request, such as the request ID and duration.
The three stack traces and log details of the request help you understand which parts of the code are taking longer to run.
No further warnings about the request are logged unless the duration of the request crosses the hung request detection threshold.

== Detect hung requests

If the request exceeds the hung request threshold, the Request Timing feature generates a warning message in the messages log file with the request details and events that make up the request.
A series of three Java cores is recorded with a 1-minute delay among the cores.
Further Java cores are created if new requests are detected.

The following log message sample shows the log messages for a request that crosses the hung request detection threshold.
The default duration value is 10 min.
The value that is configured in the following example is 4 min.

[source,java]
----
[WARNING ] TRAS0114W: Request AAA7WlpP7l7_AAAAAAAAAAA was running on thread 00000021 for at least 240001.015ms. The following table shows the events that have run during this request.
Duration       Operation
240001.754ms + websphere.servlet.service | TestWebApp | TestServlet?sleepTime=480000
     0.095ms       websphere.session.setAttribute | mCzBMyzMvAEnjMJJx9zQYIw | userID
     0.007ms       websphere.session.setAttribute | mCzBMyzMvAEnjMJJx9zQYIw | visitCount
----
