// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open LIberty provides the default TLS certificate, keystore, and TLS/SSL configuration settings.
:seo-title: SSL Defaults
:seo-description: Open LIberty provides the default TLS certificate, keystore, and TLS/SSL configuration settings.
:page-layout: general-reference
:page-type: general

= Introduction

Open LIberty provides default TLS certificate, keystore, and TLS/SSL configuration settings. You can customize these defaults in your `server.xml` file.

Although the server creates a default keystore, TLS certificate, and TLS configuration settings, you must add the transport security feature to your `server.xml` file to enable TLS. For more information, see feature:transportSecurity[Configure transport layer security].

Proceed to identify the initial settings when the defaults are created.


== Default Certificate and keystore

As a convenience tool to help developers get up and running, you can use the `createSSLCertificate` command with the `securityUtility` command to create the default certificate.
You can run the command to specify options or a default certificate and keystore are created automatically on server startup, using the password from the keystore configuration in your `server.xml` file.

The server creates the default keystore and certificate if you have the `defaultKeyStore` keystore element in the `server.xml` file. For example.
----
<keyStore id="defaultKeyStore" password="yourPassword" />
----

If a keystore configuration for the `defaultKeyStore` element is in place and the keystore does not exist on server startup, the server calls the createSSLCertificate command to create the keystore with a password that is specified in the configuration.

.The default keystore details
[%header,cols=2*]
|===
|Keystore details
|Description

|Location
|The keystore file is called `key.p12` and is in the server or clients resources/security directory.

|Keystore type
|The keystore type is `PKCS12`.

|Password
|Password that is provided in the configuration

|===

.The default certificate that is created by Open Liberty
[%header,cols=2*]
|===
|Default certificate details
|Description

|Type
|The certificate is a self-signed certificate.

|Size
|The default certificate size is 2048.

|Signature algorithm
|The signature algorithm for the certificate is SHA256WITHRSA.

|Validity
|The certificate is valid for 365 days.

|SubjectDN
|The certificate gets created with `CN=<hostname>`,`OU=<client or server name>`,`O=ibm`,`C=US` as the SubjectDN.

|===

The `createSSLCertificate` command can be called on the command line if you would like to customize the certificate.

=== Default SSL configuration

The minimal configuration that is needed for SSL is a single keystore element called `defaultKeyStore`.
When the `defaultKeyStore` element exists in the configuration, the run time builds an SSL configuration that is called `defaultSSLConfig` around it.

You can run the `createSSLCertificate` command with the `securityUtility` command to specify options or a default keystore, TLS certificate, and TLS configuration settings are created automatically on server startup. For more information, see feature:transportSecurity[Configure transport layer security].
