// Copyright (c) 2020, 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:seo-description:
:page-layout: general-reference
:page-type: general
:seo-title: Testing database connections - OpenLiberty.io
= Validating server connections

Validating your server connections with REST endpoints provides a simple way to test that your application can access databases and other sources of data.

When you enable the Rest Connector (`restConnector`) feature, a set of REST endpoints are automatically enabled in your application. You can use these REST endpoints to validate the application's server connections. The REST endpoints run the same code as your application to help ensure that you validate your actual server configuration.

By itself, the Rest Connector feature enables you to view the current configuration of a server by using the `config` endpoint. If you also enable the JDBC, JCA, Cloudant, or JMS features, you can use the `validation` endpoint to validate the configuration.

The URLs for the `validation` and `config` endpoints are both generated by using a combination of the configuration element name (`configElementName`), and unique ID (`uid`):
----
/ibm/api/config/{configElementName}/{uid}
/ibm/api/validation/{configElementName}/{uid}
----

To list all instances of a specific `configElementname`, omit the `uid`. The output from the URLs without the `uid` contains instances that are defined in the `server.xml` file and any default instances that are defined by the features of the server.

== Before you begin

Ensure that the `config` endpoint is configured to require a minimum of `reader-role` access and the `validation` endpoint is configured to require `administrator-role` access. You can use any Open Liberty supported user registry to set up secure access. However, the following sections assume that you are using either QuickStart security or a basic registry with the application security (`appSecurity`) feature:

* <<Validating a connection to a database, Validating a connection to a database>>
* <<Validating JMS and JCA connection factories, Validating JMS and JCA connection factories>>

If any of the MicroProfile OpenAPI features are enabled, view the API documentation for the `config` and `validation` REST endpoints as dynamically generated OpenAPI documents by using the following URLs:

----
/openapi/platform/config
/openapi/platform/validation
----



== Validating a connection to a database

You can use a REST API to validate your server configuration. To complete this validation, you can configure a server, start the server to identify the uid of the data source, then use the uid to access the endpoint that validates the data source. The following example shows a sample `server.xml` configuration that uses the REST Connector and JDBC features. The configuration of these features in the `server.xml` file enable you to perform validation of a database connection. However, validation doesn't occur until the proper rest endpoint is accessed by determining the unique id of the datasource:
[source,xml]
----
<server>
  <featureManager>
    <feature>appSecurity-2.0</feature>
    <feature>restConnector-2.0</feature>
    <feature>jdbc-4.2</feature>
  </featureManager>

  <keyStore id="defaultKeyStore" password="Liberty"/>
  <quickStartSecurity userName="blogAdmin" userPassword="blogAdminPassword"/>

  <library id="derby">
    <file name="${server.config.dir}/derby/derby.jar"/>
  </library>

  <dataSource id="DefaultDataSource">
    <jdbcDriver libraryRef="derby"/>
    <properties.derby.embedded databaseName="memory:defaultdb" createDatabase="create" user="dbuser" password="dbpass"/>
  </dataSource>
...
</server>
----

Determine the unique id (UID) of the datasource that you want to verify by starting the server and viewing the data source configuration at the `https://localhost:9443/ibm/api/config/dataSource/` endpoint, where `9443` is the port number of your application. The UID of the datasource is specified by the `"uid": "DefaultDataSource"` field in the endpoint output, as shown in the following example:

----
{
   "configElementName": "dataSource",
   "uid": "DefaultDataSource",
   "id": "DefaultDataSource",
   "beginTranForResultSetScrollingAPIs": true,
   "beginTranForVendorAPIs": true,
   "connectionSharing": "MatchOriginalRequest",
   "enableConnectionCasting": false,
   "jdbcDriverRef": [
      {
         "configElementName": "jdbcDriver",
         "uid": "dataSource[DefaultDataSource]/jdbcDriver[default-0]",
         "libraryRef": [
            {
               "configElementName": "library",
               "uid": "derby",
               "id": "derby",
               "apiTypeVisibility": "spec,ibm-api,api,stable",
               "fileRef": [
                  {
                     "configElementName": "file",
                     "uid": "library[derby]/file[default-0]"
                     "name":/opt/ol/wlp/usr/custom.repository

                  }
               ]
            }
         ]
      }
   ],
   "statementCacheSize": 10,
   "syncQueryTimeoutWithTransactionTimeout": false,
   "transactional": true,
   "properties.derby.embedded": [
      {
         "createDatabase": "create",
         "databaseName": "memory:defaultdb",
         "password": "******",
         "user": "dbuser"
      }
   ],
   "api": [
      "/ibm/api/validation/dataSource/DefaultDataSource"
   ]
}
----

Use the datasource UID to validate the data source with a REST endpoint by adding the UID to the `https://localhost:9443/ibm/api/config/dataSource/` endpoint URL. The REST endpoint that is found in the `https://localhost:9443/ibm/api/validation/dataSource/{uid}` endpoint, such as the `https://localhost:9443/ibm/api/validation/dataSource/DefaultDataSource` endpoint, validates the data source connection.

Examine the output of the validation for success or failure. When the data source works properly, a success message appears, as shown in the following example:

----
{
   "uid": "DefaultDataSource",
   "id": "DefaultDataSource",
   "successful": true,
   "info": {
      "databaseProductName": "Apache Derby",
      "databaseProductVersion": "10.11.1.1 - (1616546)",
      "jdbcDriverName": "Apache Derby Embedded JDBC Driver",
      "jdbcDriverVersion": "10.11.1.1 - (1616546)",
      "schema": "DBUSER",
      "user": "dbuser"
   }
}
----

If the data source has a problem, a failure message displays, and details about the failure are displayed. In the following example, the `<jdbcDriver>` element references a `<library>` element that does not contain a valid `Datasource` implementation, which results in a failure:

----
{
  "uid": "DefaultDataSource",
  "id": "DefaultDataSource",
  "failure": {
    "class": "java.sql.SQLNonTransientException",
    "stack": [
      "com.ibm.ws.sage.xyz.service.classNotFound",
      "com.ibm.ws.sage.xyz.service.create",
      "com.ibm.ws.sage.xyz.service.createDefaultDataSource",
      // stack trace cut short
      "java.lang.Thread.run(Thread.java:785)"
    ],
    "cause": {
      "class": "java.lang.ClassNotFoundException",
      "message": "org.apache.derby.jdbc.EmbeddedXADataSource40",
      "stack": [
        "com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:499)",
        // stack trace cut short
        "java.lang.Thread.run(Thread.java:785)"
      ]
    }
  }
}
----

Cloudant databases can also be viewed and validated. For more information, see the xref:reference:feature/cloudant-1.0.adoc[Cloudant Integration] feature.

== Validating JMS and JCA connection factories
Use REST endpoints to validate your server configuration. The following JCA connection factory configuration example uses the REST Connector and JCA features, but you can also complete a similar JMS connection factory configuration with the JMS and REST Connector features. The configuration of these features in the `server.xml` file enable you to perform validation of a database connection. However, validation doesn't occur until the proper rest endpoint is accessed by determining the unique id of the connection factory:

[source,xml]
----
<server>
  <featureManager>
    <feature>appSecurity-2.0</feature>
    <feature>restConnector-2.0</feature>
    <feature>jca-1.7</feature>
  </featureManager>

  <keyStore id="defaultKeyStore" password="Liberty"/>

  <basicRegistry>
    <user name="blogAdmin" password="blogAdminPwd" />
    <user name="blogReader" password="blogReaderPwd" />
    <user name="blogUser" password="blogUserPwd" />
  </basicRegistry>
  <administrator-role>
    <user>blogAdmin</user>
  </administrator-role>
  <reader-role>
    <user>blogReader</user>
  </reader-role>

  <authData id="auth2" user="containerAuthUser2" password="2containerAuthUser"/>

  <connectionFactory id="cf1" jndiName="eis/cf1">
    <containerAuthData user="containerAuthUser1" password="1containerAuthUser"/>
    <properties.TestValidationAdapter.ConnectionFactory hostName="myhost.openliberty.io" portNumber="9876"/>
  </connectionFactory>
...
</server>
----

Determine the the unique id (UID) of the connection factory that you want to verify by starting the server and viewing the connection factory configuration at the `https://localhost:9443/ibm/api/config/connectionFactory` endpoint. The UID of the connection factory is specified by the `"uid": "cf1"` field in the endpoint output.

Use the connection factory UID to validate the connection factory with a REST endpoint by adding the UID to the `https://localhost:9443/ibm/api/config/connectionFactory` endpoint URL. The REST endpoints that validate a connection factory can be found at the `https://localhost:9443/ibm/api/validation/connectionFactory/{uid}` endpoint.

The JCA connection factory configuration can be viewed like data sources are viewed. The `https://localhost:9443/ibm/api/config/connectionFactory` endpoint is used to view all connection factories. The following example shows a JCA connection factory configuration with only one config element:

----
[
   {
      "configElementName": "connectionFactory",
      "uid": "cf1",
      "id": "cf1",
      "jndiName": "eis/cf1",
      "containerAuthDataRef": [
         {
            "configElementName": "containerAuthData",
            "uid": "connectionFactory[cf1]/containerAuthData[default-0]",
            "password": "******",
            "user": "containerAuthUser1"
         }
      ],
      "properties.TestValidationAdapter.ConnectionFactory": [
         {
            "hostName": "myhost.openliberty.io",
            "password": "******",
            "portNumber": 9876,
            "userName": "DefaultUserName"
         }
      ]
   }
]
----

To view an individual connection factory, append the uid to the endpoint URL:
`https://localhost:9443/ibm/api/config/connectionFactory/cf1`

Validation of a connection factory supports both container and application authentication by including the `auth` parameter in the endpoint URL. Additionally, when you use the `?auth=application` parameter, a user can be specified by including the `X-Validation-User` and `X-Validation-Password` headers. The `X-Validation-User` and `X-Validation-Password` headers provide a username and password when you are not using container authentication to validate the connection. The authentication alias can be specified by using the `authAlias` parameter in an endpoint URL, such as `https://localhost:9443/ibm/api/validation/connectionFactory/cf1?auth=container&authAlias=auth2`.

You can use the `https://localhost:9443/ibm/api/validation/connectionFactory/cf1?auth=container` endpoint URL to test the `cf1` UID with container authentication:

----
{
   "uid": "cf1",
   "id": "cf1",
   "jndiName": "eis/cf1",
   "successful": true,
   "info": {
      "resourceAdapterName": "TestValidationAdapter",
      "resourceAdapterVersion": "28.45.53",
      "resourceAdapterJCASupport": "1.7",
      "resourceAdapterVendor": "OpenLiberty",
      "resourceAdapterDescription": "This tiny resource adapter doesn't do much at all.",
      "eisProductName": "TestValidationEIS",
      "eisProductVersion": "33.56.65",
      "user": "containerAuthUser1"
   }
}
----
