// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:seo-description:
:page-layout: general-reference
:page-type: general
:seo-title: Testing database connections - OpenLiberty.io
= Testing database connections


== About this task

Testing your database connections with REST endpoints provides a simpler method of validating the server runtime environment. To test your database connection, you must validate the data source and view the data source configuration to confirm the validation.

With the Rest Connector feature, you can view the configuration of a server with the `/ibm/api/config` endpoint. REST endpoints that are used to validate database connections with the `/ibm/api/validation` parent endpoint are automatically enabled by combining the Rest Connector feature with other features that support configuration validation.

The `/ibm/api/validation` and `/ibm/api/config` are both generated by using a combination of the configuration element name, and unique ID, as shown in the following example:
----
/ibm/api/config/{configElementName}/{uid}
/ibm/api/validation/{configElementName}/{uid}
----

== Before you begin

You must complete authentication with the Open Liberty server to access the REST endpoints. The `/ibm/api/config` endpoint requires a minimum of `reader-role` access and the `/ibm/api/validation` endpoint requires `administrator-role` access.


== Procedure

. Validate the data source. +
You must use a REST endpoint that is found under the `https://localhost:9443/ibm/api/validation/dataSource/{uid}` endpoint to validate the data source. +
When the data source works properly, a success message appears, as shown in the following example:
+
----
{
   "uid": "DefaultDataSource",
   "id": "DefaultDataSource",
   "successful": true,
   "info": {
      "databaseProductName": "Apache Derby",
      "databaseProductVersion": "10.11.1.1 - (1616546)",
      "jdbcDriverName": "Apache Derby Embedded JDBC Driver",
      "jdbcDriverVersion": "10.11.1.1 - (1616546)",
      "schema": "DBUSER",
      "user": "dbuser"
   }
}
----
+
If the data source has a problem, a failure message displays, and details about the failure are displayed as shown in the following example:
+
----
{
  "uid": "DefaultDataSource",
  "id": "DefaultDataSource",
  "failure": {
    "class": "java.sql.SQLNonTransientException",
    "stack": [
      "com.ibm.ws.jdbc.internal.JDBCDriverService.classNotFound(JDBCDriverService.java:195)",
      "com.ibm.ws.jdbc.internal.JDBCDriverService.create(JDBCDriverService.java:297)",
      "com.ibm.ws.jdbc.internal.JDBCDriverService.createDefaultDataSource(JDBCDriverService.java:396)",
      // stack trace cut short
      "java.lang.Thread.run(Thread.java:785)"
    ],
    "cause": {
      "class": "java.lang.ClassNotFoundException",
      "message": "org.apache.derby.jdbc.EmbeddedXADataSource40",
      "stack": [
        "com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:499)",
        // stack trace cut short
        "java.lang.Thread.run(Thread.java:785)"
      ]
    }
  }
}
----

. View the data source configuration.
... Start the server.
... Access the `https://localhost:9443/ibm/api/config/dataSource/` endpoint to view all data source configurations. +
To view an individual data source, you can append the `uid` of the data source to reveal the `https://localhost:9443/ibm/api/config/dataSource/DefaultDataSource` endpoint as shown in the following example:
+
----
{
   "configElementName": "dataSource",
   "uid": "DefaultDataSource",
   "id": "DefaultDataSource",
   "beginTranForResultSetScrollingAPIs": true,
   "beginTranForVendorAPIs": true,
   "connectionSharing": "MatchOriginalRequest",
   "enableConnectionCasting": false,
   "jdbcDriverRef": [
      {
         "configElementName": "jdbcDriver",
         "uid": "dataSource[DefaultDataSource]/jdbcDriver[default-0]",
         "libraryRef": [
            {
               "configElementName": "library",
               "uid": "derby",
               "id": "derby",
               "apiTypeVisibility": "spec,ibm-api,api,stable",
               "fileRef": [
                  {
                     "configElementName": "file",
                     "uid": "library[derby]/file[default-0]",
                     "name":...
                  }
               ]
            }
         ]
      }
   ],
   "statementCacheSize": 10,
   "syncQueryTimeoutWithTransactionTimeout": false,
   "transactional": true,
   "properties.derby.embedded": [
      {
         "createDatabase": "create",
         "databaseName": "memory:defaultdb",
         "password": "******",
         "user": "dbuser"
      }
   ],
   "api": [
      "/ibm/api/validation/dataSource/DefaultDataSource"
   ]
}
----
