// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title:
:seo-description:
:page-layout: general-reference
:page-type: general
= Manage database transaction recovery with the transaction service

If an application uses two or more resources, the Open Liberty transaction service coordinates updates to all the resource managers under the control of a global transaction. You can configure the transaction service to control when and how database transactions are recovered.

The Open Liberty transaction service is activated by default when enable features that require the use of transactions, such as the feature:jpa[display=Java persistence API feature], the feature:jdbc[display=Java database connectivity feature], or the feature:wasJmsServer[display=Message server feature].

== Transaction service configuration


== How database transactions are recovered

== Transaction log management
and you can choose whether to store your transaction logs as operating system files or in a relational database.
