// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title:
:page-layout: general-reference
:page-type: general
= Troubleshooting Security

== Troubleshooting ACME certificates
If you experience problems with ACME certificate authority (CA) certificates, you can refer to error messages from your Open Liberty server or HTTP error messages to debug the problem. The following information can help determine the cause of common problems and error messages that are associated with ACME CA certificates.

To help troubleshoot problems with ACME CA certificates, you can enable trace by using the following trace specification:
----
ACMECA=all
----

The following sections describe common problems that you might encounter with ACME CA accounts and connections. For more information, see xref:acme-cert-management.adoc[Automated certificate management with ACME] and the feature:acmeCA[display=ACME Support] feature.

=== The certificate request times out
If the certificate request times out, you can set a longer timeout value by using the  `challengePollTimeout` and `orderPollTimeout` properties.

=== You received an HTTP code 429 message on a renew request
To prevent too many immediate certificate-renew requests and a possible negative impact on the server, certificate-renew requests are blocked for a small window of time. After this window expires, new requests can be made. The 429 message indicates when new requests can be made.

=== You received message that indicates the rate limit was exceeded
Some CA, such as LetsEncrypt, enforce a rate limit on requesting new certificates. If you are testing and request several certificates in a short amount of time, use an appropriate testing server. For example, https://letsencrypt.org/docs/staging-environment/[LetsEncrypt provides a staging server with higher rate limits].

=== The certificate is renewed at startup when it isn't expired
The following conditions can cause an unexpired certificate to be automatically renewed at startup:

* The certificate is marked as revoked.
* The certificate expiration date is within the window set by the `renewBeforeExpiration` property.
* The directory URI, the domain, or other account information was changed and a new certificate is required.
* The server was started with the `--clean` option and historical information on the certificate was removed.

=== The authorization challenge fails with a CWPKI2001E message

If the server fails to fetch a certificate, you might see an error message like the following example:
----
CWPKI0804E: SSL certificate creation error. The error is: CWPKI2001E: The ACME certificate authority at the http://my-configured-ca.com/directory URI responded that the authorization challenge failed for the mydomainname.com domain. The challenge status is INVALID.  The error is 'Fetching http://mydomainname.com/.well-known/acme-challenge/FXCFcGCv4Ov2ofJ2i-PgMsO1kECwKB0XfTzsPjNIXBs: Connection refused'.
----

If you see this message, verify that the provided domain name is accessible by the CA. Review the logs and confirm that the expected domain name or IP address is used for the `acme-challenge` web application. Look for the following message in the logs:

----
CWWKT0016I: Web application available (default_host): http://mydomainname.com:80/.well-known/acme-challenge/
----

To configure the hostname used for web applications, add or update the `host` attribute for the `httpEndpoint` configuration in your `server.xml` file.


=== After a failure to fetch the certificate, the keystore produces errors

If the server cannot fetch a certificate, an empty keystore is created. In older versions of Java, an empty keystore can cause an exception. Examples of this error include the following messages:
----
CWPKI2030E: The ACME service could not install a certificate under the default alias into the defaultKeyStore keystore. The error is 'The keystore [defaultKeyStore] is not present in the configuration'.```
----
----
CWWKS9582E: The [defaultSSLConfig] sslRef attributes required by the orb element with the defaultOrb id have not been resolved within 10 seconds. As a result, the applications will not start. Ensure that you included a keyStore element and that Secure Sockets Layer (SSL) is configured correctly. If the sslRef is defaultSSLConfig, then add a keyStore element with the ID value of `defaultKeyStore` and a password.
----

To work around this error after a failure to fetch the initial certificate, remove the empty keystore.

=== You received a CWPKI2058W warning message during a revocation check

When you run containerized versions of ACME CA servers, the Online Certificate Status Protocol (OCSP) responder URL that is defined in the certificate might not be reachable. You can override the OCSP responder URL in the certificate by specifying the `ocspResponderUrl` attribute in the `acmeRevocationChecker` element. If this URL is not configured, the following  warning can occur during revocation checks:

----
CWPKI2058W: Certificate revocation status checking ignored soft failures. Revocation checking might be incomplete. The failures are: '[java.security.cert.CertPathValidatorException: Unable to determine revocation status due to network error, java.security.cert.CertPathValidatorException: Unable to determine revocation status due to network error]'
----

If you see this network error warning and you are running with a test CA server, you can add a custom `ocspResponderUrl` URL. If the test CA does not support revocation testing, you can disable revocation testing by setting the `enabled` attribute on the `acmeRevocationChecker` element to `false`, as shown in the following example:

----
<acmeCA>
   ...
   <acmeRevocationChecker enabled="false" />
</acmeCA>
----


== Troubleshooting LDAP

=== You received an FFDC1015I error message that the configured LDAP server cannot be reached

If you are unable to reach the configured LDAP server, you might see an error message like the following example in the `messages.log` file:

----
FFDC1015I: An FFDC Incident has been created: javax.naming.ServiceUnavailableException: myldapserver.mycompany.com:636; socket closed com.ibm.ws.security.registry.ldap.internal.LdapRegistry 298
----

If you see this message, check your LDAP server to verify that it is running and that its IP address can be accessed from the Open Liberty server.

=== Connection with the LDAP server fails with an SSL handshake error.

If you enable SSL on your LDAP server without copying the signer of the LDAP server into the truststore that is referenced in the `LDAPSSLSettings` element, a connection with the LDAP server fails with an SSL handshake error. You might see the following message:

----
The javax.naming.CommunicationException: simple bind failed: myldapserver.mycompany.com:636 [Root exception is javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.g: PKIX path building failed: java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target]
----
Make sure that you copy the signer of the LDAP server into your truststore.

=== Login, authentication, or authorization is slow for LDAP or a federated repository.

Several reasons can exist for a slow login.
Review the following list for some common causes.

- If the LDAP configuration for referrals is set to `follow`, then any referrals to other LDAP instances are followed on LDAP requests.
This situation can result in contacting one or more additional LDAP servers, depending on your LDAP configuration, and thus, additional time is spent.
For example, the LDAP1 server could follow a referral to the LDAP2 server, which could follow a referral to the LDAP3 server.
If you do not need to acquire more information from other LDAP servers, set referrals to `ignore`.

- One LDAP server could be experiencing a problem and error that might not display in the JVM logs.
Examples include a TCP read timeout or a DNS issue when the LDAP server talks to a referred LDAP server.
To diagnose these situations, you can capture packets to see how many calls are being made and if any delays or errors exist due to an LDAP server that is following a referral.
A firewall or other software closes connections to LDAP.

- By default, a pool of LDAP connections is maintained to improve performance.
If a cached connection is closed remotely, a new connection is made and put back in the context pool.
This process can cause a delay and can cause errors to be logged in the JVM logs.
To avoid this situation, set the context pool timeout to less than the remote connection closure time.
For example, if a firewall closes the connection at 10 minutes, you could set the connection pool timeout for 9 minutes.
Instead of encountering a failed connection and creating a new connection, the expiration is checked on a connection from the pool and a new connection is created, skipping the failure step.
For example, you might receive the following error:

----
java.net.SocketException: Connection reset
----

- With federated repositories, all repositories and registries are checked to ensure that a unique user is in the realm.
If a repository or registry is responding slowly, every call is slow even if the user is not in the slow registry.
Ensure that all participating base entries are responding promptly.



=== Occasional connection exceptions accessing the LDAP server. For example, java.net.SocketException: Connection reset

If you experience problems with Kerberos authentication to an LDAP server, refer to error messages from your Open Liberty server or HTTP error messages to debug the problem. The following information can help determine the causes of common problems and error messages that are associated with Kerberos authentication to LDAP servers.

=== Users cannot log in, even if non-Kerberos enabled registries are available.
If multiple user registries are configured for an Open Liberty server, all basic, custom, and LDAP user registries are combined into a single federated user registry. By default, the server must successfully search for the user in all participating user registries to verify that the user is unique within the federated user registry. If a Kerberos-enabled LDAP server in a federated registry uses a Kerberos ticket cache to hold user credentials and the credentials expire, a search of the LDAP registry fails. To resolve the problem, renew the Kerberos ticket cache. For example, you can renew the Kerberos ticket cache by using https://docs.oracle.com/en/java/javase/11/tools/kinit.html#GUID-8AA6A058-419A-41D4-A61E-E5E1911E51E6[the Java kinit tool].

To avoid failures if a user registry is unavailable, configure the `allowOpIfRepoDown` attribute in your `server.xml` file. Set the `allowOpIfRepoDown` attribute to `true` on the `primaryRealm` subelement of the `federatedRepository` element, as shown in the following example:

[source,xml]
----
<federatedRepository>
        <primaryRealm name="FederatedRealm" allowOpIfRepoDown="true">
            <participatingBaseEntry name="o=SampleBasicRealm"/>
            <participatingBaseEntry name="o=ibm,c=us"/>
        </primaryRealm>
</federatedRepository>
----

For more information, see the feature:federatedRegistry[display=Federated User Registry feature].

=== Performance is slow when Kerberos is configured for a federated user registry.

Enabling the `allowOpIfRepoDown` attribute on the `federatedRepository` element can help avoid failures if one or more user registries in a federated user registry are unavailable.
However, this configuration might result in slower overall performance if Kerberos credentials are specified in a `ccache` file with the `krb5TicketCache` attribute.
When Kerberos credentials are in a `ccache` file, Open Liberty attempts to auto-renew credentials that are nearing the expiration time or expired.
This auto-renewal attempt can result in a slower performance.

To avoid this problem, you can specify Kerberos credentials in a `keytab` file with the `kerberos` element. Credentials in a `keytab` file do not expire so auto-renewal is not necessary. For more information, see xref:kerberos-authentication.adoc[Kerberos authentication for Open Liberty].

=== The Kerberos principal name is not in the Kerberos ticket cache file.

If the Kerberos principal name is not found in the Kerberos ticket cache file, Open Liberty logs the `CWIML` message type. A missing Kerberos principal name can occur for the following reasons:

- No credential was generated for the Kerberos principal name, which results in an incorrect Kerberos configuration.
- The Kerberos ticket cache contains an expired credential.

In either case, renew the Kerberos ticket cache to resolve the problem. For example, you can renew the Kerberos ticket cache by using https://docs.oracle.com/en/java/javase/11/tools/kinit.html#GUID-8AA6A058-419A-41D4-A61E-E5E1911E51E6[the Java kinit tool].

Depending on the type of Java SDK, the message that you can receive is similar to one of the following examples:

----
CWIML4507E: Kerberos login failed with the user1@SAMPLE.COM Kerberos principal and the C:\krb5\krb5-user1.cc Kerberos credential cache (ccache). javax.security.auth.login.LoginException: Unable to obtain password from user

CWIML4520E: The LDAP operation could not be completed. The LDAP naming exception javax.naming.AuthenticationException: GSSAPI [Root exception is javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Ticket expired (32))]] occurred during processing.

CWIML4520E: The LDAP operation could not be completed. The LDAP naming exception javax.naming.NamingException: CWIML4507E: Kerberos login failed with the user1@SAMPLE.COM Kerberos principal and the C:\krb5\krb5-user1.cc Kerberos credential cache (ccache). javax.security.auth.login.LoginException: Unable to obtain password from user
----

To review the expiration time of the Kerberos principal user, run https://docs.oracle.com/en/java/javase/11/tools/klist.html#GUID-205BCE0D-F5D4-4A9C-ACBC-46423BAF616F[the Java klist tool].

== Trobleshooting SSO

=== Single sign-on (SSO) does not work as servers don't share the Coordinated Universal Time and user registry

Different Open Liberty servers share LTPA keys, password, and `ssoCookieName` attribute of `webAppSecurity` element.
If these servers don't share the Coordinated Universal Time and user registry, SSO might not work.
Make sure that these servers share the Coordinated Universal Time and user registry.

=== You are prompted to enter the credential information again


The SSO might not work if the token expires.
Also, SSO can fail if the cookie is sent from a web browser after you change the user registry in an inconsistent manner.
For example, you modify the realm or remove the user that the cookie represents.
You might be prompted to enter the credential information again.
Make sure that the token is not expired and that you make consistent changes to the user registry.

== Troubleshooting SSL

=== You receive the CWWKS9105E message that the SSL port could not be determined for redirection

 If you try to access an application that redirects to an SSL port that is unavailable, you might see the following messages

 ----
 CWWKS9105E: Could not determine the SSL port for automatic redirection.
 ----

The port might be unavailable because of a missing SSL configuration or some error in the SSL configuration definition.
Check that the SSL configuration exist in the `server.xml` file and is correct.

=== A keystore element exists in the configuration without an ID field and gives you an FFDC1015I error

When a keystore element exists in the configuration without an ID field, you might receive the following errors

----
FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalArgumentException: Unknown, incomplete configuration: missing id field com.ibm.ws.config.internal.cm.ManagedServiceFactoryTracker aSyncReadNupdate. Exception thrown while trying to read configuration and update ManagedServiceFactory. Exception = java.lang.IllegalArgumentException: Unknown, incomplete configuration: missing id field" at ffdc_12.04.18_16.09.42.0.log
----

If you use a minimal SSL configuration, set the `ID` field to `defaultKeyStore`.

=== You get an error when you use a JDK from the WebSphere Application Server

If you use a JDK from the WebSphere Application Server, you might see the following error if SSL is enabled on your Open Liberty Server:

----
java.net.SocketException: java.lang.ClassNotFoundException: Cannot find the specified class com.ibm.websphere.ssl.protocol.SSLSocketFactory
      at javax.net.ssl.DefaultSSLSocketFactory.a(SSLSocketFactory.java:11)
      at javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:6)
      at com.ibm.net.ssl.www2.protocol.https.c.afterConnect(c.java:161)
      at com.ibm.net.ssl.www2.protocol.https.d.connect(d.java:36)
      at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1184)
      at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:390)
      at com.ibm.net.ssl.www2.protocol.https.b.getResponseCode(b.java:75)
      at com.ibm.ws.jmx.connector.client.rest.internal.RESTMBeanServerConnection.loadJMXServerInfo(RESTMBeanServerConnection.java:142)
      at com.ibm.ws.jmx.connector.client.rest.internal.RESTMBeanServerConnection.<init>(RESTMBeanServerConnection.java:114)
      at com.ibm.ws.jmx.connector.client.rest.internal.Connector.connect(Connector.java:315)
      at com.ibm.ws.jmx.connector.client.rest.internal.Connector.connect(Connector.java:103)
----

This error occurs because the WebSphere Application Server SSL socket factories are not supported by Liberty.
You can get past this problem by taking the following steps:

- Create a text file, such as my.java.security with the following two empty entries
----
ssl.SocketFactory.provider=
ssl.ServerSocketFactory.provider=
----

- Create a `jvm.options` file for your Liberty server
- Add the following property to your `jvm.options` file, that includes the full path to your text file that you just created

----
-Djava.security.properties=fullPathTo/my.java.security
----

If you want to make this more reusable, you can put the `my.java.security` file in your server directory, and then can use a relative path like this:

----
-Djava.security.properties=./my.java.security
----
