// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: A user registry is a data source that contains account information, such as usernames and passwords. An application server can retrieve this information to authenticate and authorize users.
:seo-title: User registries for application security
:seo-description: A user registry is a data source that contains account information, such as usernames and passwords. An application server can retrieve this information to authenticate and authorize users.
:page-layout: general-reference
:page-type: general
= User registries for application security

A user registry is a data source that contains account information, such as usernames and passwords. An application server can retrieve this information to xref:authentication.adoc[authenticate] and xref:authorization.adoc[authorize] users.

Microservice-based applications in production often run on an application server that delegates identity management to a xref:single-sign-on.adoc[single sign-on] provider, such as Google or Facebook. However, some enterprises maintain their own internal user registries, such as a Lightweight Directory Access Protocol (LDAP) registry. Furthermore, in test environments, a developer might want to set up a basic, file-based user registry within the application server to simplify security operations during the development process.

== Basic user registries for application development

A basic user registry is a local file-based data source that developers can configure to test application resource permissions. Open Liberty provides an easy-to-use basic user registry for development environments.

You can configure a basic user registry directly in the `server.xml` file. Although this registry is not secure enough for production environments, it can help simplify authentication and authorization scenarios during development and testing. For example, you can configure a basic user registry for your application that contains two users, their passwords, and one user group for the admin role. If you designate one of your two users as an admin, you can test access to your application resources for that role without having to connect to an external user registry.

The Application Security feature provides the core capabilities that support the basic user registry configuration. To set up a basic user registry, enable the Application Security feature and configure the `basicRegistry` element in your `server.xml` file. For more information, see xref:reference:feature/appSecurity-3.0.adoc[the Application Security feature].

=== QuickStart security

The simplest option for configuring a basic user registry is to enable QuickStart security. This option automatically configures a registry with only one user who is granted the administrator role. To use this element, the Application Security feature must be configured in the `server.xml` file. The registry that is configured by this option is not sufficiently secure for production environments. However, it is useful in test scenarios, particularly for testing secured JMX connections that require administrator access. For more information, see xref:reference:feature/appSecurity-3.0.adoc[the Application Security feature].

=== User password security

To help keep your basic user registry secure, do not store user passwords in plain text. You can obfuscate the passwords in your basic user registry with the hash option of the encode action on the `securityUtility` command.
You can use this command regardless of whether the registry is configured with the `basicRegistry` element or the `quickStartSecurity` element. For more information, see xref:password-encryption.adoc[Password encryption].

== LDAP user registries for applications in production

The Lightweight Directory Access Protocol (LDAP) is an open protocol that supports authentication and authorization services. LDAP specifies the language that application servers use to communicate with LDAP user registries, which store security information such as usernames, passwords, and user groups. LDAP user registries are often used to manage authentication within a specific domain, such as a corporate intranet or email system.  Organizations might set up an LDAP registry if they want to manage their own authentication, without relying on a third party. However, it is possible to configure authentication to an LDAP registry through an external identity provider.

Although a basic user registry might be sufficient during development and testing of an application, an LDAP user registry provides the extra security that is required for applications in production. If your app needs to control access to resources that are specific to a particular organization or enterprise, you might need to configure it to connect with an existing LDAP registry.

To configure Open Liberty to manage authentication with an LDAP user registry, add the xref:reference:feature/appSecurity-3.0.adoc[Application Security] and xref:reference:feature/ldapRegistry-3.0.adoc[LDAP User Registry] features to your `server.xml` file.
If you need to communicate with a TLS-enabled LDAP server, you must also add the xref:reference:feature/transportSecurity-1.0.adoc[Transport Security] feature.
For configuration examples, see xref:reference:feature/ldapRegistry-3.0.adoc[the LDAP User Registry feature].

=== LDAP registries and the Social Media Login feature

You can use the Social Media Login feature to help manage authentication with a configured LDAP registry.
Depending how you configure the feature, users can either supply their social media credentials to authenticate or choose between their LDAP login and their social media credentials.
For more information, see the example configurations for the xref:reference:feature/socialLogin-1.0.adoc[Social Media Login feature].

== Federated user registries

In cases where user and group information is spread across multiple registries, federation enables Open Liberty to use distributed user information in a unified manner, with a continuous store of information.
Different types of registries can be federated to combine information from LDAP, basic, and custom user registries and repositories into a common registry.

If multiple basic user registries are configured in your `server.xml` file, they are federated by default if you enable both the Application Security feature and the Federated User Registry feature. However, user registries that are configured with the `quickStartSecurity` element cannot be federated with other registries. For more information, see xref:reference:feature/federatedRegistry-1.0.adoc[the Federated User Registry feature].

LDAP registries are federated by default.
If you configure more than one LDAP registry in your `server.xml` file, then the registries are automatically federated into a common registry.
This default federation occurs regardless of whether the LDAP registries are separate data stores or two subtrees of the same LDAP registry.
Similarly, if one or more LDAP registries are configured with one or more basic or custom registries in the `server.xml` file, then they are federated by default.

You can adjust the configuration of federated registries by enabling xref:reference:feature/federatedRegistry-1.0.adoc[the Federated User Registry feature] and configuring the `federatedRepository` element. This configuration can be useful if you want to exclude certain registries from a federated group by selectively including only the registries you want to federate.
For more information, see xref:reference:config/federatedRepository.adoc[User Registry Federation].

== See also

- Guide: link:/guides/security-intro.html#configuring-the-user-registry[Configuring the user registry] in link:/guides/security-intro.html[Securing a web application]
- xref:reference:config/basicRegistry.adoc[Basic User Registry configuration]
- xref:reference:config/ldapRegistry.adoc[LDAP User Registry configuration]
