// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Signature files (*.sig) are produced for every package of an Open Liberty release. You can verify these signature files by using the corresponding public key that is provided on the IBM DHE download site.
:seo-description: Signature files (*.sig) are produced for every package of an Open Liberty release. You can verify these signature files by using the corresponding public key that is provided on the IBM DHE download site.
:page-layout: general-reference
:page-type: general

= Verifying Open Liberty release packages

Signature files are produced for every package of an Open Liberty release. You can use these signature files and the corresponding public key to verify the authenticity and integrity of an Open Liberty release package.

The Open Liberty project uses its private key to digitally sign each Open Liberty release. You can use the Open Liberty public key to check the signature, verify that the package was released by Open Liberty, and that it was not modified since its release.

You can verify a release package either locally, by using the `openssl` command and a `*.sig` file, or on Maven Central, by using the `gpg` command.


== Verifying Open Liberty packages with OpenSSL

To verify an Open Liberty release package locally, you must first download an Open Liberty `.zip` package, the corresponding `.sig` file, and the Open LIberty public key. You can then run the `openssl` command to verify the package.

1. Go to the **Downloads** section of the Open Liberty xref:https://www.openliberty.io/start/[Get Started page] and download an Open LIberty `.zip` package and its corresponding `.sig` file.

2. Obtain the public key file by using the public key link on the Get Started page.

3. After you download the files, you can run the following xref:https://www.openssl.org/docs/man1.1.1/man1/openssl-dgst.html[OpenSSL command] from the command line to verify the package.

[source,sh]
----
openssl dgst -sha256 -verify WebSphereLiberty_06-02-2021.pem -signature openliberty-javaee8-22.0.0.1.zip.sig openliberty-javaee8-22.0.0.1.zip
----

This example uses the `WebSphereLiberty_06-02-2021.pem` public key file and `openliberty-javaee8-22.0.0.1.zip.sig` signature file to verify the `openliberty-javaee8-22.0.0.1.zip` release package.
Replace the signature file and package version values according to the package that you want to verify. If the verification is successful, the command produces the following console output.

[source,sh]
----
Verified OK
----

== Verify Liberty packages on Maven Central

To verify Open Liberty packages on Maven Central, you must first download the public key to your local machine by using xref:https://gnupg.org/[the gpg or gpg2 command].
You must edit the trust level for the key owner. You can then use this key to remotely verify an Open Liberty .asc release file on Maven Central.

1. Run the following command to download the public key file. The key ID value for the public key is `46102B8E`.

[source,sh]
----
>gpg2 --keyserver hkp://keyserver.ubuntu.com --recv-keys 46102B8E
----

2. Use the `gpg2 --edit-key` command to xref:https://www.gnupg.org/gph/en/manual/x334.html[set the trust for the key owner] to 5.
When you run the `gpg2 --edit-key` command, the console displays information about the key owner, followed by an internal command prompt.
At this prompt, enter the trust command. You are then prompted to select a level of trust. Enter 5.

[source,sh]
----
gpg2 --edit-key "WebSphere Liberty"
   gpg> trust

  Set trust 5
----

3. Verify the file by running the following command. This example verifies the Open Liberty 22.0.0.1 release package.

[source,sh]
----
gpg2 --verify openliberty-runtime-22.0.0.1.zip.asc

----

4. If the verification is successful, the command produces the following output.

[source,sh]
----
gpg: assuming signed data in 'openliberty-runtime-22.0.0.1.zip'
gpg: Signature made Wed Nov 24 09:02:44 2021 EST
gpg:        using RSA key 91FFD9A642D060B66B802B9D4D210F6946102B8E
gpg: Good signature from "WebSphere Liberty (Works for IBM) <contbld@uk.ibm.com>" [ultimate]
gpg:        aka "WebSphereLiberty" [ultimate]

----
