// Copyright (c) 2023 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-title: Verify images for Open Liberty Operator
:seo-description: All images that are associated with the Open Liberty operator are digitally signed. Verify the downloaded images and ensure that the images are created by using the image signatures and uploaded by Open Liberty.
:page-layout:
:page-type:

= Verify images for Open Liberty Operator

All images that are associated with the Open Liberty operator are digitally signed. You can use the Open Liberty public key to check the signature, verify that the image was created by Open Liberty, and that it was not modified since its release.

== Before you begin

Before you can verify image signatures, you must install the following tools:

* https://gnupg.org/software/index.html[GNU Privacy Guard v2]
* https://www.redhat.com/en/topics/containers/what-is-skopeo#overview[Skopeo]

Also, the Open Liberty public key needs to be present on the same machine as these command-line tools. 

You can copy the following text box into a text editor and save it as a file named `olo.gpg`.

----

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGC2ygABEACk5ZG9XVP5amXUeipM1KiAow0U1bOH4s1RCSEPvtjsAQB/dmD0
C8SLvVpdxGoSRZlUl+616OdFq1TRGUg3nn13vHBm4rWacS/pcSZiISF0qIxI9Ooj
YRdVGKjNwjk6chsG7HjzNtsa8LyM431lmH9FqVvFw0tJwaKF3nG6cXTOgHbm3v3T
nsBk6tDpQ4ofbrZMo8uZNX3/j5+CqLiwFYkme2u0usgcL6UMHATxcyHeRiq5ZUu5
QxnwFuhWqsEUPpJyqP7lhzcfzS+LzlID3iM0G/0gVmqK6JAR3B4gejsEGCiigEIq
NfLTjOjDU59hsaH/SOSH6D6/ig8aGk/bSHUCcvKnhhS0+QZ2Ml8l3uRFyJiTA6IN
PWhfAlFVphDgqmn0Kl66gQvJdebbAkiDWuan+0uNi9EYZROCmSHgzTs2UoSdeY7D
3r3zXloWq9giCjfOA3EuOS06C1T7JsI6+1wmNywEOFU4N62UTmF0K/2S80KrSvpP
ZQuTWlGrGR/6KFzIfSvZCu2ZD1V0dQmP7kZSzxLTVpCufunSl2MBCcIrw6CXmt7h
s/y3/5ew6Ty/ZHn4xSUdrGeyvbdixLE/T+Aly+b2O/bPNG0YeadAIFZlD64sM1F/
5PTvzjpMtJVEwFngavJHiDufzGKAhyYvxgVn3CxFXVZJlhw2R/O5mtI2CQARAQAB
tBBXZWJTcGhlcmVMaWJlcnR5iQI5BBMBCAAjBQJgtsoAAhsvBwsJCAcDAgEGFQgC
CQoLBBYCAwECHgECF4AACgkQTSEPaUYQK45GbQ/+JrMdhDUu8vZJU/Rx/irLMMF6
1VFKmhypb1ZgV/Cewf5TdRak2P4uYaIwCvDQu57ZLa6DxB6W9ds6bZcKd+KlA7va
+yROesEnhoqHiM4S2ZON0thnB5KAYAAykRXQHMfcPg15mccFFuVisDhMUOEfRKjr
Hx1pRli42lqBqkar6WogXPJEF0MkEHpeszfwXZqi5WRZiBF3utQMmi32tidl/KsE
3DesTb2OD2D7qM+JekDNK9cR7QFBXjWDx9ieWHSRnAxEJSSfCJBz5c1BaXP65pkf
3dZTMRNxd4g8uPva6nntHky0ElGVzAWEVinjmwK6shHfMZKwLXIQCHroBk6ypmyc
xyEJbVaB+3bPzTglxjoxfVj5Sh1XeonBWm+D0KBxOI8ebI9zohOlaheDjvZUQgAm
cKFNpgDUqw2FX7taH+NR0PDXUKO/NXarRz5WYRB1W4Shs7I3TtxYguUJsIwNse7A
kjzqKqPPpsNfVXaGjL2IEO0R9WfttidNt14173o/luMGFayTSJ49NkcB2Srq02Ui
Z3nJXoIvrCEo5MSvDXlsOUb0v3syxoH929icCfMbgb5E6XFjMcS+hEmHjcQItxL2
agoIQIT4bqTTMHjk7JIqEGgAv+U3HaH6BjiX8YyuNUq2AsRaYpGTpndhaHxlMYhz
5OtUxMfNV7CySkicPCk=
=UQBR

-----END PGP PUBLIC KEY BLOCK-----

----

== Procedure

. Run the following command to Import the Open Liberty public key file to GPG:
+
----
sudo gpg2 --import olo.gpg
----
+
. Run the following command to calculate the fingerprint:
+
----
fingerprint=$(gpg2 -k | grep -B 1 OpenLiberty | head -n 1 | xargs)
----
+
. To create a directory for an image and pull the image into local storage using Skopeo, follow these steps:
* Create a directory with a name of your choice for the image. For example:
+
----
mkdir operator-image
----
+
* Use Skopeo to copy the Docker image to the newly created directory. For example:
+
----
skopeo copy docker://icr.io/cpopen/open-liberty-operator:1.1.0-amd64 dir:./operator-image
----
+
This command pulls the `icr.io/cpopen/open-liberty-operator:1.1.0-amd64` image and store it in the `operator-image` directory.
+
. Repeat this command for each of the images that you need to verify.
+
----
icr.io/cpopen/open-liberty-operator:1.1.0-amd64
icr.io/cpopen/open-liberty-operator-bundle:1.1.0
icr.io/cpopen/open-liberty-operator-catalog:1.1.0
----
+
. Run the `standalone-verify` command to verify the image by using the downloaded signature and repository.
+
----
skopeo standalone-verify <image_directory>/manifest.json <image_name> ${fingerprint} ./<image_directory>/signature-<x>
----
+
The `<image_directory>` refers to the location of the copied image. Replace `<x>` with `1` for the `open-liberty-operator-bundle` and `open-liberty-operator-catalog` images, or `2` for the `open-liberty-operator` image. For example:
+
----
skopeo standalone-verify ./operator-image/manifest.json icr.io/cpopen/open-liberty-operator:1.1.0-amd64  ${fingerprint} ./operator-image/signature-2
----

== Result

If the verification is successful, the following message is displayed:
----
Signature verified
----

