// Copyright (c) 2023 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:seo-description: 
:page-layout: general-reference
:page-type: general
= Send bidirectional messages between services with WebSocket

The WebSocket protocol supports real-time bidirectional messaging between a client and server. The Open Liberty Jakarta WebSocket feature supports applications that use this protocol.

== What is WebSocket?

The WebSocket protocol enables two-way communication between client and server endpoints on top of a Transmission Control Protocol (TCP) connection. The channel between client and server is bidirectional and full-duplex, which means that both client and server can send and receive messages simultaneously, without having to wait for a response. Furthermore, the connection remains open until it is explicitly closed, so messaging can occur in real time without interruptions. WebSocket is beneficial to applications that need to frequently send and receive messages with minimal latency, such as applications for chat, gaming, or virtual collaboration.

For example, an online multiplayer racing game might use the WebSocket protocol to receive each player's position while sending the location of the other players back out to each browser client.

A WebSocket connection is initiated by a client that sends a WebSocket handshake request to a server over HTTP. This request includes an HTTP upgrade request to upgrade the HTTP connection to a TCP connection where the actual WebSocket communication occurs. After the TCP connection is established, the server can send and receive messages among one or more clients simultaneously until the connection is closed.

=== WebSocket, REST, and server sent events

The WebSocket protocol can be an alternative to REST frameworks for some application needs, though the comparison is not one-to-one. Depending on the context, REST communication is still a preferred choice for many web applications, while others might benefit from server sent events (SSE), another alternative to WebSocket.

Any comparison between WebSocket and REST essentially boils down to a comparison between WebSocket and HTTP, the protocol that REST frameworks rely on. Although WebSocket uses HTTP to establish a connection, any ensuing messages are sent over a persistent TCP connection. The same connection can remain open for multiple messages. By contrast, REST requests establish a new TCP connection for each message, which can lead to higher overhead per message than with WebSocket. Furthermore, with WebSocket, a client and server can send and receive messages simultaneously, without having to wait for a response. This kind of communication which is not possible with REST frameworks, where a server must wait for a request before sending data to a client. Another advantage of WebSocket is the ability for a server to send messages to multiple clients at the same time. 

Although REST is the most common framework for many application requests, WebSocket might be preferred for scenarios that require a server to send and recieve multiple real-time, low-latency messages among one or more clients. For example, chat applications or multiplayer games might benefit from using WebSocket connections instead of REST over HTTP.

Server-Sent Events is an API that allows clients to subscribe to a stream of events that is pushed from a server. First, the client makes a connection with the server over HTTP. The server continuously pushes events to the client while the connection persists. SSE differs from traditional HTTP requests, which use one request for one response. SSE also differs from WebSockets in that SSE is unidirectional from the server to the client, while WebSockets allow for bidirectional communication. However, WebSockets can be more complex to set up that SSE, which works on top of HTTP and doesn't require a separate protocol. SSE is useful for Applications that need to send multiple low-latency messages from server to client but don't require bidirectional communication. For example, applications that use push notifications or provide realtime sports updates might benefit from using SSE instead of WebSockets.

== WebSockets and Open Liberty
To use WebSockets with your Open Liberty applications, enable the feature:websocket[display=Jakarta WebSocket] feature in your `server.xml` file. This feature enables support for WebSocket applications that use Jakarta WebSocket API.

You can learn how to use Jakarta WebSocket to send and receive messages between services in the link:/guides/jakarta-websocket.html[Bidirectional communication between services using Jakarta WebSocket] guide.
