// Copyright (c) 2020,2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.
:page-layout: general-reference
:seo-title: About Open Liberty
:seo-description: Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices.
:page-layout: general-reference
:page-type: general
= Why Open Liberty?

Open Liberty is a lightweight Java runtime for building cloud-native applications and microservices. It is compatible with MicroProfile and with the Jakarta EE Full Platform and Web Profile specifications.

With Open Liberty, you can add and remove modular features from the latest versions of xref:microprofile.adoc[Eclipse MicroProfile] and xref:reference:javadoc/liberty-javaee8-javadoc.adoc[Jakarta EE].
You run only the features that your application needs.
Furthermore, thanks to continuous delivery releases and zero-migration architecture, you can upgrade to the latest version of Open Liberty at any time, with minimal impact on your current applications and configurations.

WebSphere Liberty is an IBM product that is built on Open Liberty. Although these two runtimes are essentially the same, WebSphere Liberty supports extra features that long-time users might require, such as support for Java EE 6, z/OS operating systems, collectives, and network deployment clustering. For more information, see https://www.ibm.com/cloud/websphere-liberty[IBM WebSphere Liberty].


== Develop cloud-native Java microservices

Open Liberty helps developers to be productive with tools of their choice. We provide intuitive extensions for popular integrated development environments (IDEs), including https://marketplace.eclipse.org/content/ibm-liberty-developer-tools[Eclipse], https://marketplace.visualstudio.com/items?itemName=Open-Liberty.liberty-dev-vscode-ext[VS Code], and https://plugins.jetbrains.com/plugin/14856-open-liberty-tools[Intellij]. Open Liberty also integrates with https://github.com/OpenLiberty/ci.maven[Maven] and https://github.com/OpenLiberty/ci.gradle[Gradle], and releases all runtime binary files to https://mvnrepository.com/artifact/io.openliberty[Maven Central]. 

Maven and Gradle support enable Open Liberty xref:development-mode.adoc[development mode]. 
With development mode, Open Liberty automatically detects changes in your code, compiles them, and deploys them to your running server.
You can also run tests on demand, or even automatically, so that you get immediate feedback on your changes.

You can write and run true-to-production integration tests for your Open Liberty applications by using xref:integration-testing.adoc[MicroShed testing]. MicroShed runs JUnit integration tests against an Open Liberty application that is running in a container so that you test the exact same image that you use in production. Microshed is built on the https://www.testcontainers.org/[TestContainers] library and provides integration with applications that use Kafka messaging. For more information, see link:/guides/microshed-testing.html[Testing a MicroProfile or Jakarta EE application].

Open Liberty is a flexible solution for developing and deploying applications that can scale from small microservices all the way up to full modern enterprise monoliths, and anything in-between. Our modular structure ensures that you keep your application footprint as efficient as possible by adding only the features you need. Update the simple xref:reference:config/server-configuration-overview.adoc[XML configuration file] with the features you want and any dependencies are automatically added for you. Keeping your footprint small enables faster startup times. link:/blog/2019/10/30/faster-startup-open-liberty.html[Our tests] show startup times around one second for a simple REST application, significantly faster than other comparable application servers.

////
The following table shows disk and memory measurements for three example Open Liberty runtime packages. The example in the first row contains all the latest APIs for both Java EE or Jakarta EE and MicroProfile, all you need for a modern cloud-native monolith. The example in the second row contains enough runtime to support MicroProfile 3.3, all you need for a typical microservice. The example in the third row contains enough runtime to run Servlet 4.0, the absolute minimum you need to run a simple web framework. For each of these use cases, Open Liberty disk and memory requirements scale to match the needs of the system so that no unnecessary resources are used.  

.Example runtime packages
[%header,cols="6,3,3"]
|===

|Package contents
|Size on disk
|Memory

|Java EE 8/Jakarta EE 8 + MicroProfile 3.3
|121MB
|165MB

|MicroProfile 3.3       
|59MB
|113MB

|Servlet 4.0
|24MB
|72MB

|===



Furthermore, thanks to xref:zero-migration-architecture.adoc[zero-migration architecture], you can use existing, unmodified configuration and application files with an updated version of Open Liberty, without unexpected changes in behavior. You focus on writing your applications, not the APIs changing under you.
////

Open Liberty helps you develop secure applications.
During development and testing, our built-in xref:user-registries-application-security.adoc#_basic_user_registries_for_application_development[basic user registry and the QuickStart security element] offer easily configurable security frameworks to test access to your application in a lightweight, self-contained manner.
The xref:reference:command/securityUtility-encode.adoc[securityUtility encode command] supports plain text encryption, so you can easily xref:password-encryption.adoc[secure user passwords] with hash encoding. We also support xref:single-sign-on.adoc[a range of single sign-on options], including JSON Web Tokens, OpenID Connect, SAML Web, and SPNEGO.

== Deploy in containers to any cloud

Container-based microservices need a runtime that can achieve optimum application performance, regardless of where the container is deployed. Open Liberty deploys with fast throughput to any cloud environment. We offer production-ready docker images for many popular cloud services. For more information, check out our https://www.openliberty.io/guides/?search=cloud[cloud deployment guides].

Kubernetes operators are software extensions that help you configure and manage containerized applications. https://operatorhub.io/operator/open-liberty[The Open Liberty Operator] simplifies  cloud deployment, clustering, persistence integration, service binding, problem determination, and more.

////
A properly tuned thread pool can maximize throughput, reduce response times, and increase the capacity for concurrent requests.
However, containerization makes performance tuning more complex. Open Liberty addresses this complexity with effective default settings that rarely require adjustment. Additionally, the Open Liberty thread pool is auto-tuning. Application code in Open Liberty runs in a single thread pool that is called the default executor.
The size of this pool is set by xref:thread-pool-tuning.adoc[an auto-tuning controller], which can manage a wide range of workloads.
////
 

To address the challenges of maintaining cloud-native applications, Open Liberty provides a continuous-delivery release cycle. A new release of the runtime arrives every 4 weeks. Every Open Liberty release is available in Maven Central and Docker Hub, making it simple to pick up the latest updates through build automation. Development teams can simply rebuild their containers to pull in the latest release. And with xref:zero-migration-architecture.adoc[zero-migration architecture], the existing APIs and behaviors that your application relies on are preserved and supported in each new release. In just a matter of minutes, you can move up to the latest version Open Liberty without having to change your application code or configuration.

After deployment, we offer a range of features that support xref:security-hardening.adoc[security hardening for applications in production]. The xref:reference:feature/appSecurity-3.0.adoc[Application Security feature] provides the core capability for the Jakarta EE Security API, while the xref:reference:feature/transportSecurity-1.0.adoc[Transport Security feature] enables secure TLS connections by using HTTPS.
The xref:user-registries-application-security.adoc#_ldap_user_registries_for_applications_in_production[LDAP User Registry] feature supports authentication and authorization to external LDAP registries.

== Monitor microservices in the cloud

Distributed tracing helps troubleshoot microservices by examining and logging requests as they propagate through a distributed system. Without a distributed tracing system in place, analyzing the workflows of operations becomes difficult, particularly in regard to pinpointing when a request is received or when a response is sent back. Open Liberty supports various options to enable distributed tracing through link:https://www.openliberty.io/guides/?search=trace[MicroProfile OpenTracing].

Metrics are essential to building observability into applications so that operations teams can effectively monitor application behavior. You use metrics to help pinpoint issues, collect data for capacity planning, and decide when to scale a service to run with more or fewer resources. You can xref:microservice-observability-metrics.adoc[gather detailed metrics on your Open Liberty applications] with MicroProfile metrics.  https://github.com/eclipse/microprofile-metrics/[MicroProfile Metrics] provides a `/metrics` endpoint from which you can access all metrics that are emitted by your Open Liberty server and its deployed applications.

After you configure metrics, you can link:/blog/2020/01/29/alerts-slack-prometheus-alertmanager-open-liberty.html[get alerts from your Open Liberty apps by using Prometheus Alertmanager]. You can also link:/blog/2020/04/09/microprofile-3-3-open-liberty-20004.html#gra[compile your metrics data into visualizations in Grafana dashboards] to spot potential problems in your applications.

== Get the support you need

Whether you're an enterprise or a smaller crew, you can find an Open Liberty support option to suit your needs. We are supported by a thriving user community on https://stackoverflow.com/questions/tagged/open-liberty[Stack Overflow], https://github.com/OpenLiberty/[Github], https://gitter.im/OpenLiberty/[Gitter], and beyond. If you need more refined level of support, check out https://www.openliberty.io/support/[enterprise support from IBM].

== Try it out

Open Liberty provides a diverse library of developer guides that are designed to give you firsthand experience with the configuration and features that support cloud-native development.
The guides cover a wide range of development and production scenarios and can be adapted as reference templates for developing your own applications. link:/guides/[Browse the guides] and learn how to develop, build, test, and deploy applications and microservices with Open Liberty.
