// Copyright (c) 2024 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
// This doc is hosted in the Red Hat Runtimes documentation. Any changes made to this doc also need to be made to the version that's located in the PurpleLiberty GitHub repo (https://github.com/PurpleLiberty/docs).
//
:page-description:
:seo-title: Simplify feature selection with versionless features - OpenLiberty.io
:projectName: Open Liberty
:page-layout: feature
:page-type: overview
= Simplify feature selection with versionless features - OpenLiberty.io

Versionless features provide a generic way to specify Open Liberty features without having to specify a feature version. Versionless features automate version selection, so you can focus on application development without worrying about feature compatibility issues.

Versionless features are available for the MicroProfile, Jakarta EE, and Java EE platforms. Versionless features are supported only in server environments, not in client environments.


== Enabling versionless features

To use versionless features, you must declare a corresponding versioned platform. You can declare a platform in three different ways

* Specify a platform element inside the `featureManager` element of your `server.xml` file
* Specify the `PREFFERED_PLATFORM_VERSIONS` environment variable
* Enable one versioned feature from a supported platform in your `server.xml` file

[#platform]
=== Specify a platform element

You can declare a platform version by specifying a `platform` inside the `featureManager` element of your `server.ml` file. This method is the recommended best practice for specifying a platform for versionless features.

For example, following `server.xml` file configuration specifies a Jakarta EE platform of `jakartaee-9.1`, with associated versionless features for `servlet`, `persistence`, and `restfulWS`

[source,xml]
----
<featureManager>
    <platform>javaee-9.1</platform>
    <feature>servlet</feature>
    <feature>jpa</feature>
    <feature>jaxrs</feature>
</featureManager>
----

With this configuration, the built-in Open Liberty feature resolver automatically resolves each feature the version that are included in the Jakarta EE 9.1 platform.

Similarly, the following example enables versionless MicroProfile features that are included in the MicroProfile 5.0 platform:

[source,xml]
----
<featureManager>
  <platform>microProfile-5.0</platform>
  <feature>mpHealth</feature>
  <feature>mpMetrics</feature>
</featureManager>
----

=== Define a platform with an environment variable

Alternatively, you can declare a platform for versionless features by defining the `PREFERRED_PLATFORM_VERSIONS` in your `server.env` file, as shown in the following example:

[source,properties]
----
PREFERRED_PLATFORM_VERSIONS=microProfile-5.0
----

When this environment variable is set as shown in the previous example, you can specify versionless features in your server.xml file and the Open Liberty feature resolver automatically resolves them to the correct version. In this `server.xml` file example, the `mpHealth` and `mpMetrics` features resolve to versions that are included in MicroProfile 5.0:

[source,xml]
----
<featureManager>
    <feature>mpHealth</feature>
    <feature>mpMetrics</feature>
</featureManager>
----

Although you can also set the `PREFERRED_PLATFORM_VERSIONS` environment variable from the environment shell, setting it in your `server.env` file ensures that the variable is applied if you run the `server package` command to package the server.

If you set the `PREFERRED_PLATFORM_VERSIONS` environment variable as a true environment variable in the shell outside of the `server.env`` file, and you then run the `server package` command, the variable is not retained during packaging.

If this scenario occurs, the `server package` command issues  the following  warning:

----
CWWKE0969W: A manual PREFERRED_PLATFORM_VERSION environment variable was specified during server packaging.
----

You must then re-create the `PREFERRED_PLATFORM_VERSION` definition in the new environment where the packaged server runs with the same platform values that were specified in the prior environment.

=== Enable one versioned feature

When you declare a single versioned feature that is part of a MicroProfile, Java EE, or Jakarta EE platform, Open Liberty automatically resolves any versionless features that are associated with the platform to their compatible versions.

In the following example, the `microHealth-3.0` feature is part of the MicroProfile 4.0 platform, and no other MicroProfile platform. Consequently, Open Liberty automatically resolves the versionless `mpMetrics` and `mpConfig` features to the versions that are included in MicroProfile 4.0:

[source,xml]
----
<featureManager>
  <feature>mpHealth-3.0</feature>
  <feature>mpMetrics</feature>
  <feature>mpConfig</feature>
</featureManager>
----

== Available platforms and versionless features

== MicroProfile

.MicroProfile platforms and versionless features
[%header,cols=3*]
|===

|Platform versions
|Feature name
|Versionless feature short name

.9+a| * microProfile-1.2

* microProfile-1.3

* microProfile-1.4

* microProfile-2.0

* microProfile-2.1

* microProfile-2.2

* microProfile-3.0

* microProfile-3.2

* microProfile-3.3

* microProfile-4.0

* microProfile-4.1

* microProfile-5.0

* microProfile-6.0

* microProfile-6.1

|feature:mpConfig[display=MicroProfile Config]
|`mpConfig`


|feature:mpFaultTolerance[display=MicroProfile Fault Tolerance]
|`mpFaultTolerance`


|feature:mpHealth[display=MicroProfile Health]
|`mpHealth`


|feature:mpJwt[display=MicroProfile JSON Web Token]
|`mpJwt`



|feature:mpMetrics[display=MicroProfile Metrics]
|`mpMetrics`


|feature:mpOpenAPI[display=MicroProfile OpenAPI]
|`mpOpenAPI`


|feature:mpOpenTracing[display=MicroProfile Open Tracing]
|`mpOpenTracing`


|feature:mpRestClient[display=MicroProfile Rest Client]
|`mpRestClient`


|feature:mpTelemetry[display=MicroProfile Telemetry]
|`mpTelemetry`

|===

== Java EE and Jakarta EE

.Java EE and Jakarta EE platforms and versionless features
[%header,cols=3*]
|===

|Platform versions
|Feature name
|Versionless feature short name

.36+a| * javaee-7.0

* javaee-8.0

* jakartaee-9.1

* jakartaee-10.0


a| * Jakarta EE: feature:appAuthentication[display=MicroProfile Config]
* Java EE: feature:jaspic[display=MicroProfile Config]
a| * Jakarta EE: `appAuthentication`
* Java EE: `jaspic`


a| * Jakarta EE: feature:appAuthorization[display=MicroProfile Config]
* Java EE: feature:jacc[display=MicroProfile Config]
a| * Jakarta EE: `appAuthorization`
* Java EE: `jacc`


a|feature:appClientSupport[display=MicroProfile Health]
a|`appClientSupport`


a|feature:appSecurity[display=MicroProfile JSON Web Token]
a|`appSecurity`



a|feature:batch[display=MicroProfile Metrics]
a|`batch`


a|feature:beanValidation[display=MicroProfile OpenAPI]
a|`beanValidation`


a|feature:cdi[display=MicroProfile Open Tracing]
a|`cdi`


a|feature:concurrent[display=MicroProfile Rest Client]
a|`concurrent`


a| * Jakarta EE: feature:connectors[display=MicroProfile Config]
* Java EE: feature:jca[display=MicroProfile Config]
a| * Jakarta EE: `connectors`
* Java EE: `jca`

a| * Jakarta EE: feature:connectorsInboundSecurity[display=MicroProfile Config]
* Java EE: feature:jcaInboundSecurity[display=MicroProfile Config]
a| * Jakarta EE: `connectorsInboundSecurity`
* Java EE: `jcaInboundSecurity`

a| * Jakarta EE: feature:enterpriseBeans[display=MicroProfile Config]
* Java EE: feature:ejb[display=MicroProfile Config]
a| * Jakarta EE: `enterpriseBeans`
* Java EE: `ejb`

a| * Jakarta EE: feature:enterpriseBeansHome[display=MicroProfile Config]
* Java EE: feature:ejbHome[display=MicroProfile Config]
a| * Jakarta EE: `enterpriseBeansHome`
* Java EE: `ejbHome`

a| * Jakarta EE: feature:enterpriseBeansLite[display=MicroProfile Config]
* Java EE: feature:ejbLite[display=MicroProfile Config]
a| * Jakarta EE: `enterpriseBeansLite`
* Java EE: `ejbLite`

a| * Jakarta EE: feature:enterpriseBeansPersistentTimer[display=MicroProfile Config]
* Java EE: feature:ejbPersistentTimer[display=MicroProfile Config]
a| * Jakarta EE: `enterpriseBeansPersistentTimer`
* Java EE: `ejbPersistentTimer`

a| * Jakarta EE: feature:enterpriseBeansRemote[display=MicroProfile Config]
* Java EE: feature:ejbRemote[display=MicroProfile Config]
a| * Jakarta EE: `enterpriseBeansRemote`
* Java EE: `ejbRemote`

a| * Jakarta EE: feature:expressionLanguage[display=MicroProfile Config]
* Java EE: feature:el[display=MicroProfile Config]
a| * Jakarta EE: `expressionLanguage`
* Java EE: `el`

a| * Jakarta EE: feature:faces[display=MicroProfile Config]
* Java EE: feature:jsf[display=MicroProfile Config]
a| * Jakarta EE: `faces`
* Java EE: `jsf`

a|feature:j2eeManagement[display=MicroProfile Rest Client]
a|`j2eeManagement`

a|feature:jdbc[display=MicroProfile Rest Client]
a|`jdbc`

a|feature:jsonb[display=MicroProfile Rest Client]
a|`jsonb`

a|feature:jsonp[display=MicroProfile Rest Client]
a|`jsonp`

a| * Jakarta EE: feature:mail[display=MicroProfile Config]
* Java EE: feature:javaMail[display=MicroProfile Config]
a| * Jakarta EE: `mail`
* Java EE: `javaMail`

a|feature:managedBeans[display=MicroProfile Rest Client]
a|`managedBeans`

a|feature:mdb[display=MicroProfile Rest Client]
a|`mdb`

a| * Jakarta EE: feature:messaging[display=MicroProfile Config]
* Java EE: feature:jms[display=MicroProfile Config]
a| * Jakarta EE: `messaging`
* Java EE: `jms`

a| * Jakarta EE: feature:messagingClient[display=MicroProfile Config]
* Java EE: feature:wasJmsClient[display=MicroProfile Config]
a| * Jakarta EE: `messagingClient`
* Java EE: `wasJmsClient`

a| * Jakarta EE: feature:messagingSecurity[display=MicroProfile Config]
* Java EE: feature:wasJmsSecurity[display=MicroProfile Config]
a| * Jakarta EE: `messagingSecurity`
* Java EE: `wasJmsSecurity`

a| * Jakarta EE: feature:messagingServer[display=MicroProfile Config]
* Java EE: feature:wasJmsServer[display=MicroProfile Config]
a| * Jakarta EE: `messagingServer`
* Java EE: `wasJmsServer`

a| * Jakarta EE: feature:pages[display=MicroProfile Config]
* Java EE: feature:jsp[display=MicroProfile Config]
a| * Jakarta EE: `pages`
* Java EE: `jsp`

a| * Jakarta EE: feature:persistence[display=MicroProfile Config]
* Java EE: feature:jpa[display=MicroProfile Config]
a| * Jakarta EE: `persistence`
* Java EE: `jpa`

a| * Jakarta EE: feature:restfulWS[display=MicroProfile Config]
* Java EE: feature:jaxrs[display=MicroProfile Config]
a| * Jakarta EE: `restfulWS`
* Java EE: `jaxrs`

a| * Jakarta EE: feature:restfulWSClient[display=MicroProfile Config]
* Java EE: feature:jaxrsClient[display=MicroProfile Config]
a| * Jakarta EE: `restfulWSClient`
* Java EE: `jaxrsClient`

a|feature:servlet[display=MicroProfile Rest Client]
a|`servlet`

a|feature:websocket[display=MicroProfile Rest Client]
a|`websocket`

a| * Jakarta EE: feature:xmlBinding[display=MicroProfile Config]
* Java EE: feature:jaxb[display=MicroProfile Config]
a| * Jakarta EE: `xmlBinding`
* Java EE: `jaxb`

a| * Jakarta EE: feature:xmlWS[display=MicroProfile Config]
* Java EE: feature:jaxws[display=MicroProfile Config]
a| * Jakarta EE: `xmlWS`
* Java EE: `jaxws`

|===
