== Examples
With the RESTful Web Services Client APIs, you can specify properties on the client that configure settings like timeouts, proxy hosts, and SSL properties. You can set these properties in the Java code or in the server configuration. The following examples show how you can set `webTarget` values in the `server.xml` file so that you can change them without the need to edit and recompile the Java code.

=== Change settings when an application moves from development to production environments

If the application is deployed in a different environment, certain settings might need to change. For example, an application might initially be written to run in a development environment, where all remote RESTful services are available without a proxy server and can connect quickly, as shown in the following example:

[source,java]
----
public Widget getRemoteWidget(String id) {
    Client client = ClientBuilder.newClient();
    WebTarget target = client.target("https://somehost:9443/WidgetStore/widgets/");
    Widget widget = target.path(id).request().get(Widget.class);
    return widget;
}
----

However, when this application is deployed in a production environment it might be necessary to add new settings because remote RESTful services might need a proxy server to establish connections. You can specify new settings by adding the following configuration to your `server.xml` file:

[source,xml]
----
<webTarget uri="https://somehost:9443/WidgetStore*" proxyHost="myProxyHost" proxyPort="55555" proxyType="HTTP"
           connectionTimeout="60000" receiveTimeout="60000" />
----

This configuration alters the `webTarget` element in the Java code to use the `proxyHost` and `proxyPort` attributes to specify the values for a HTTP proxy server. The `connectionTimeout` and `receiveTimeout` attributes are used to set connection and receive timeouts of 60 seconds (60,000 milliseconds) instead of the default timeouts.

=== Modify SSL configuration in development

During development, an SSL certificate might not match the server hostname that tests the application because it matches the server hostname that deploys the application in production. The configuration can be changed during development to use a different SSL configuration or to disable hostname verification of SSL certificates:

[source,xml]
----
<webTarget uri="https://somehost:9443/WidgetStore*" sslConfig="mySSLRef" disableCNCheck="true" />
----

To maintain application security, do not disable SSL verification in production environments.

=== Set custom properties

If your application uses providers such as the `ClientRequestFilter` or `ClientResponseFilter` interfaces, they can read and react to custom properties that are set on the RESTful Web Services Client or the `WebTarget` interface. You can also change the Open Liberty client implementation behavior by setting custom properties. These properties can be set programmatically by using the `webTarget.property("myCustomProperty", "someValue")` configuration but you can also set custom properties by specifying the `WebTarget` element in your `server.xml` file:

[source,xml]
----
<webTarget uri="https://somehost:9443/WidgetStore*" myCustomProperty="prod" />
----

For a complete list of pre-defined properties, see config:webTarget[].

=== Enable MicroProfile JWT authentication for RESTful Web Services

If you add the RESTful Web Services Client feature to your server configuration along with the feature:mpJwt[display=MicroProfile JSON Web Token] feature, you can use MicroProfile JWT to authenticate RESTful Web Services. With the Open Liberty RESTful Web Services client, you can use MicroProfile JWT as an authentication method for RESTful Web Services, as shown in the following example:
[source,xml]
----
<webTarget uri="http://localhost:56789/protectedResourceWithMPJWT*" authnToken="mpjwt" />
----

The `authnToken` attribute in the `webTarget` element adds MicroProfile JWT as an authorization header when the RESTful Web Services service that is specified by the `http://localhost:56789/protectedResourceWithMPJWT*` endpoint URL in the `uri` attribute is called.
