
== Examples

=== Slow and hung request threshold configuration
The following example sets the slow and hung request thresholds for all requests. The `requestTiming` element detects requests as slow if the requests require more than 10 seconds to complete, or as hung if the requests do not complete in 10 minutes:
[source,xml]
----
<requestTiming slowRequestThreshold="10s" hungRequestThreshold="10m">
</requestTiming>
----

=== Configuring JDBC request thresholds
The following example sets the slow and hung JDBC request thresholds within the `requestTiming` element configuration. The `jdbcTiming` element detects that the JDBC request is slow if the request requires more than 500 ms to complete, or hung if the request does not complete in 5 minutes:
[source,xml]
----
<requestTiming slowRequestThreshold="10s" hungRequestThreshold="10m">
  <jdbcTiming dataSourceName="testDBSource" slowRequestThreshold="500ms" hungRequestThreshold="5m"/>
</requestTiming>
----
The `jdbcTiming` element configuration always overrides the `requestTiming` element configuration for the slow and hung request thresholds. The `jdbcTiming` element configuration can be only used to time a root level request.

=== Configuring servlet request thresholds
The following example sets the slow and hung request thresholds for two servlets within the `requestTiming` element configuration. The `servletTiming` element detects that the `Arm10Servlet` servlet request is hung if the request does not complete in 20 seconds. The servlet request from the `SecurityExchangeApp` application is detected as hung if the request does not complete in 2 hours:
[source,xml]
----
<requestTiming slowRequestThreshold="10s" hungRequestThreshold="10m">
  <servletTiming servletName="Arm10Servlet" hungRequestThreshold="20s"/>
  <servletTiming appName="SecurityExchangeApp" hungRequestThreshold="2h"/>
</requestTiming>
----
The `servletTiming` element configuration always overrides the `requestTiming` element configuration for the slow and hung request thresholds. The `servletTiming` element configuration can be only used to time a root level request.
