== Examples
With the JAX-RS Client APIs, you can specify properties on the client that configure settings like timeouts, proxy hosts, and SSL properties. You can set these properties in the Java code or in the server configuration. The following examples show how you can set `webTarget` values in the `server.xml` so that you can change them without having to edit and recompile the Java code.

=== Change values when an application moves from development to production environments

If the application is deployed in a different environment, certain settings might need to change. For example, an application might initially be written to run in a development environment, where all remote RESTful services are available without a proxy server and can connect very quickly:

[source,java]
----
public Widget getRemoteWidget(String id) {
    Client client = ClientBuilder.newClient();
    WebTarget target = client.target("https://somehost:9443/WidgetStore/widgets/");
    Widget widget = target.path(id).request().get(Widget.class);
    return widget;
}
----

However, when this application is deployed in a production environment it might be necessary to add new settings. You can specify new settings by adding the following configuration to your `server.xml` file:

[source,xml]
----
<webTarget uri="https://somehost:9443/WidgetStore*" proxyHost="myProxyHost" proxyPort="55555" proxyType="HTTP"
           connectionTimeout="60000" receiveTimeout="60000" />
----

This configuration alters the `WebTarget` in the Java code to use the specified HTTP proxy server (`myProxyHost:55555`) and use connection and receive timeouts of 60 seconds (60,000 milliseconds) instead of the default timeouts.

=== Simplify SSL configuration in development

During development, an SSL certificate might not match the server hostname on which the application is being tested because it matches the server hostname on which the application is ultimately be deployed in production. The configuration can be changed during development to use a different SSL configuration or to disable hostname verification of SSL certificates:

[source,xml]
----
<webTarget uri="https://somehost:9443/WidgetStore*" sslConfig="mySSLRef" disableCNCheck="true" />
----

To maintain application security, do not disable SSL verification in production environments.

=== Set custom properties

If your application uses providers such as the `ClientRequestFilter` or `ClientResponseFilter` interfaces, they can read and react to custom properties specified on the JAX-RS Client or the `WebTarget` interface. You can also change the Open Liberty client implementation behavior by specifying custom properties. These properties are normally specified programmatically by using the `webTarget.property("myCustomProperty", "someValue")` configuration but you can also specify custom properties by specifying the `WebTarget` element in your `server.xml` file:

[source,xml]
----
<webTarget uri="https://somehost:9443/WidgetStore*" myCustomProperty="prod" />
----

For a complete list of pre-defined properties, see config:webTarget[].

=== Enable MicroProfile JWT authentication for JAX-RS services

If you add the JAX-RS Client feature to your server configuration along with the feature:mpJwt[display=MicroProfile JSON Web Token] feature, you can use MicroProfile JWT to authenticate JAX-RS services. With the Open Liberty JAX-RS client, you can send MicroProfile JWT as an authentication method for JAX-RS services, as shown in the following example:
[source,xml]
----
<webTarget uri="http://localhost:56789/protectedResourceWithMPJWT*" authnToken="mpjwt" />
----

The `authnToken=“mpjwt”` attribute in the `webTarget` element adds MicroProfile JWT as an authorization header in the JAX-RS service that is specified by the `http://localhost:56789/protectedResourceWithMPJWT*` endpoint URL in the `uri` attribute.
