== Examples

=== Access security details with a context object

In JAX-RS applications, you can use annotations to access information from HTTP requests with dependency injections of context objects. Context objects can provide information that is associated with the application such as the specific HTTP request or response, or the application environment. In the following example, the `@Context` annotation injects the `SecurityContext` context object that provides access to security details:

[source,java]
----
@Context
SecurityContext sec;

@GET
@Path("/getGroups")
public Set<String> getGroups() {
       Set<String> groups = null;
       Principal user = sec.getUserPrincipal();
       if (user instanceof JsonWebToken) {
                JsonWebToken jwt = (JsonWebToken) user;
                groups= = jwt.getGroups();
       }
       return groups;
}
----

To access security details, the `SecurityContext` context object uses the `sec.getUserPrincipal()` method that determines the identity of the user that makes the HTTP request. The `if` statement specifies the `JSONWebToken` claims that identify the user.

=== Inject the MicroProfile JWT interface

You can inject interfaces in JAX-RS applications to access resources such as user details. In the following example, the `@Inject` annotation injects the `JsonWebToken` interface to obtain the `jwtPrincipal` object that contains details that identify the user:

[source,java]
----
@RequestScoped
public class JwtEndpoint {
       @Inject
       private JsonWebToken jwtPrincipal;
       @GET
       @Path("/getInjectedPrincipal")
       public String getInjectedJWT() {
          return  this.jwtPrincipal.getName();
       }
}
----
