= Audit 1.0
:linkcss:
:page-layout: feature
:nofooter:

// tag::description[]
The Liberty Audit feature is used to report and track auditable events to ensure the integrity of your system. The Liberty Audit feature introduces an infrastructure which serves two purposes:
 * Confirming the effectiveness and integrity of the existing configuration
 * Identifying areas where improvement to the configuration may be needed

 The Liberty Audit feature has the ability to capture the following auditable events:
 * Basic authentication
 * Start and stop of the Audit service
 * Form login authentication
 * Client certificate authentication
 * Servlet runAs delegation
 * Failover to basic authentication
 * Unprotected servlet authorization
 * Servlet 3.0 APIs: login/logout/authenticate
 * JACC web authorization
 * Form logout
 * JACC EJB authorization
 * EJB delegation
 * SCIM operations/member management
 * Dynamic audit feature handling
 * EJB authorization
 * JMX MBean operations
 * JMX Notifications
 * JMX MBean registration
 * JMX MBean attribute operations
 * JMS Authentication
 * JMS Authorization
 * OAuth application password and token management
 * SAF authorization

  The Liberty Audit feature supports the Cloud Auditing Data Federation (CADF) event model.  The CADF model describes a data model and associated schema definitions for an audit event. The feature provides a default implementation, the AuditFileHandler, which emits human-readable audit records to a file-based log.   Each audit record is emitted in JSON format.

// end::description[]
// tag::enable[]
== Enabling this feature
To enable the Audit 1.0 feature, add the following element declaration inside the featureManager element in your server.xml file:


----
<feature>audit-1.0</feature>
----
// end::enable[]
// tag::config[]

== Feature configuration elements
* config:administrator-role[]
* config:auditEvent[]
* config:auditFileHandler[]
* config:authCache[]
* config:authentication[]
* config:authorization-roles[]
* config:basicRegistry[]
* config:channelfw[]
* config:classloading[]
* config:federatedRepository[]
* config:httpAccessLogging[]
* config:httpDispatcher[]
* config:httpEncoding[]
* config:httpEndpoint[]
* config:httpOptions[]
* config:httpProxyRedirect[]
* config:jaasLoginContextEntry[]
* config:jaasLoginModule[]
* config:library[]
* config:ltpa[]
* config:mimeTypes[]
* config:quickStartSecurity[]
* config:remoteIp[]
* config:tcpOptions[]
* config:trustAssociation[]
* config:virtualHost[]
// end::config[]
// tag::apis[]
// end::apis[]
// tag::requirements[]

== Features that this feature enables
* feature:appSecurity-2.0[]
* feature:distributedMap-1.0[]
* feature:json-1.0[]
* feature:ssl-1.0[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.8
* JavaSE-11.0
// end::java-versions[]
// tag::dependencies[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the Audit 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.audit-1.0; type="osgi.subsystem.feature"
----
// end::feature-require[]
// tag::spi[]
// end::spi[]

This will enable the default audit file handler implementation without the need to explicitly configure the audit file handler. By specifying only the feature itself, all supported audit events with all possible outcomes will be emitted to the file-based audit log in readable format, i.e., neither encrypted nor signed.


== Audit File Handler

The audit file handler is made available by specifying the audit-1.0 feature.

The audit file handler can be customized by specifying any of the attributes below, along with the <auditFileHandler> element:

[cols=",,,,",options="header",]
|===
|*Attribute* |*Description* |*Value type* |*Default value* |
|maxFileSize |The maximum size (in MB) of each file-based audit log. maxFileSize=0 generates an unlimited sized single log |Integer |20 |
|maxFiles |The maximum number of archived file-based audit logs before the oldest archived log is overwritten. maxFiles=0 generates an unlimited number of logs |Integer |100 |
|logDirectory |The location of the audit logs |String |WLP_OUTPUT_DIR/serverName/logs |
|sign |Enable signing audit records |Boolean |false |
|encrypt |Enable encrypting audit records |Boolean |false |
|encryptAlias |Alias of the certificate used to encrypt audit records |String |n/a |
|encryptKeyStoreRef |Reference to key store containing the certificate to encrypt audit records |String |n/a |
|signingAlias |Alias of the certificate used to sign audit records |String |n/a |
|signingKeyStoreRef |Reference to key store containing the certificate to sign audit records |String |n/a |
|compact |Provides ability to produce compact JSON formatted audit records, one line per audit event |Boolean |false |
|===

When the maximum number of archived audit logs is reached, once the audit.log that is currently being written to reaches its maximum size, then the oldest archived audit log is overwritten.

Example: server.xml: Audit file handler with maxFiles, maxFileSize and compact mode specified:

[source,xml]
----
<featureManager>

<feature>appSecurity-2.0</feature>

<feature>[.underline]#jsp#-2.2</feature>

<feature>[.underline]#servlet#-3.1</feature>

<feature>audit-1.0</feature>

<feature>[.underline]#timedexit#-1.0</feature>

</featureManager>

<auditFileHandler maxFiles="50" maxFileSize="100" compact=”true”>

</auditFileHandler>
----

In this example, the audit logs will be written to the default $\{server.output.dir}/logs. Each audit file will have a maximum 100MB size before being archived and new audit records written to a new audit.log. The maximum number of archived audit logs will be 50. Once 50 audit logs are archived, and the current audit.log being written to reaches the 100MB size, then the oldest archived audit.log will be overwritten.

All audit events and possible outcomes will be emitted to the audit logs.

== Events

To specify only those audit events and outcomes that may be of relevance in an environment, the <event> element may be defined with the audit event name and outcome:

Example: server.xml: Specifying audit events and outcomes

----
<featureManager>

<feature>appSecurity-2.0</feature>

<feature>[.underline]#servlet#-4.0</feature>

<feature>audit-1.0</feature>

</featureManager>

<auditFileHandler

maxFiles="5"

maxFileSize="20"

compact="true">

<events name="AuditEvent_1" eventName="SECURITY_AUTHN" outcome="SUCCESS"/>

<events name="AuditEvent_2" eventName="SECURITY_AUTHN" outcome="REDIRECT"/> <events name="AuditEvent_3" eventName="SECURITY_AUTHN" outcome="FAILURE"/> <events name="AuditEvent_4" eventName="SECURITY_AUTHZ"/>

</auditFileHandler>
----

In this example, we will only be capturing security authentication events whose outcome is success, redirect or failure; and security authorization events whose outcome includes all supported outcomes.

Note that if an event is specified with only an outcome attribute, i.e., with no eventName specified, then no audit records will be produced. However, an eventName may be specified without an outcome attribute, in which case all possible outcomes for that eventName will be emitted.

== Encrypting and Signing Audit

It is important for the recorded audit data to be preserved in such a way that not only can the access be restricted but also so that the data itself is tamper-proof.

The ability to both encrypt and sign the audit records data is provided.

To encrypt audit records, the encrypt attribute must be specified in the auditFileHandler element, along with the alias name of the certificate used to encrypt the audit data, and the keystore in which that certificate exists.

To sign audit records, the sign attribute must be specified in the auditFileHandler element, along with the alias name of the certificate used to sign the audit data, and the keystore in which that certificate exists.

Note that SHA256withRSA is used as the default crypto algorithm for both encryption and signing.

Example: server.xml: Audit file handler with encryption and signing enabled

----
<featureManager>

<feature>appSecurity-2.0</feature>

<feature>[.underline]#jsp#-2.2</feature>

<feature>[.underline]#servlet#-3.1</feature>

<feature>audit-1.0</feature>

</featureManager>

<keyStore

id="auditEncKeyStore”

password="Liberty" location="$\{server.config.dir}/resources/security/AuditEncryptionKeyStore.jks"

type="JKS" />

<keyStore

id="auditSignKeyStore"

password="\{[.underline]#xor#}EzY9Oi0rJg=="

location="$\{server.config.dir}/resources/security/AuditSigningKeyStore2.[.underline]#jks#"

type="JKS" />

<auditFileHandler

encrypt="true"

encryptAlias="[.underline]#auditencryption#"

encryptKeyStoreRef="auditEncKeyStore"

sign="true"

signingAlias="auditsigning2"

signingKeyStoreRef="auditSignKeyStore"

</auditFileHandler>
----

All audit events and possible outcomes will be emitted to the audit logs.
