= Java Database Connectivity 4.0
:linkcss:
:page-layout: feature
:nofooter:

include::./gen/jdbc-4.0.gendoc[tag=description]

include::./gen/jdbc-4.0.gendoc[tag=enable]

== Examples

=== Simple DataSource example
To configure a data source, two configuration elements are typically required:

1. Shared library containing JDBC driver file(s)
2. One or more data source elements using the the shared library

The following example creates a data source that can be injected using the name `jdbc/myDataSource`. If the feature:jndi-1.0[] feature is enabled, that name can be used as a JNDI name:

[source,xml]
----
<library id="JdbcLib">
    <fileset dir="${server.config.dir}/jdbc"/>
</library>

<dataSource jndiName="jdbc/myDataSource">
   <jdbcDriver libraryRef="JdbcLib"/>
   <properties databaseName="myDB" serverName="mydb.mycompany.com" portNumber="50000"/>
</dataSource>
----

A servlet or EJB can then get it injected for use:

[source,java]
----
@Resource(name="jdbc/myDataSource")
private DataSource myDb;

public void insertRochester() throws SQLException {
    try (Connection con = myDataSource.getConnection()) {
       con.createStatement().executeUpdate("INSERT INTO CITIES VALUES('Rochester', 'MN', 'US')");
    }
}
----

=== DataSource with authentication

When connecting to remote databases, credentials typically need to be provided.
These can be configured using an `authData` element. The password can be in
plain text, xor, or aes encrypted. The `securityUtility encode` command can be
used to create an encoded password. The following example encodes `password` as the
password value:

[source,xml]
----
<authData id="dbCreds" user="dbUser" password="{aes}AEJrzAGfDEmtxI18U/qEcv54kXmUIgUUV7b5pybw/BzH" />

<dataSource jndiName="jdbc/myDataSource" containerAuthDataRef="dbCreds">
   <jdbcDriver libraryRef="JdbcLib"/>
   <properties databaseName="myDB" serverName="mydb.mycompany.com" portNumber="50000"/>
</dataSource>
----

=== Using JDBC driver classes from an application

Some applications make use of JDBC driver classes using `Connection.unwrap`. This
means the application needs to be able to view the JDBC driver classes. This is
done by configuring the application classloader to see the JDBC driver classes:

[source,xml]
----
<library id="JdbcLib">
    <fileset dir="${server.config.dir}/jdbc"/>
</library>

<webApplication location="myweb.war" >
    <classloader commonLibraryRef="JdbcLib" />
</webApplication>

<dataSource jndiName="jdbc/myDataSource">
   <jdbcDriver libraryRef="JdbcLib"/>
   <properties databaseName="myDB" serverName="mydb.mycompany.com" portNumber="50000"/>
</dataSource>
----

include::./gen/jdbc-4.0.gendoc[tag=config]

include::./gen/jdbc-4.0.gendoc[tag=apis]

include::./gen/jdbc-4.0.gendoc[tag=requirements]

include::./gen/jdbc-4.0.gendoc[tag=java-versions]

include::./gen/jdbc-4.0.gendoc[tag=dependencies]

include::./gen/jdbc-4.0.gendoc[tag=feature-require]

include::./gen/jdbc-4.0.gendoc[tag=spi]
