= LDAP User Registry 1.0
:linkcss: 
:page-layout: feature
:nofooter: 

include::./gen/ldapRegistry-3.0.gendoc[tag=description]

include::./gen/ldapRegistry-3.0.gendoc[tag=enable]


== Example server configuration

The password value can be plaintext, or the xor encoded value of the password.

In this example, the filters for Active Directory have been customized as an external `activedLdapFilterProperties` element, which is then referenced by the `ldapRegistry` element, and the default values of LDAP entity types, attributes, group configuration, context pool, and cache configuration are used.

[source,xml]
----
<<<<<<< HEAD
<feature>ldapRegistry-3.0</feature>
----
// end::enable[]
// tag::config[]

== Feature configuration elements
* config:activedLdapFilterProperties[]
* config:customLdapFilterProperties[]
* config:domino50LdapFilterProperties[]
* config:edirectoryLdapFilterProperties[]
* config:idsLdapFilterProperties[]
* config:iplanetLdapFilterProperties[]
* config:ldapRegistry[]
* config:netscapeLdapFilterProperties[]
* config:securewayLdapFilterProperties[]
// end::config[]
// tag::apis[]
// end::apis[]
// tag::requirements[]

== Features that this feature enables
* feature:federatedRegistry-1.0[]
// end::requirements[]
// tag::java-versions[]

== Supported Java versions

* JavaSE-1.8
* JavaSE-11.0
* JavaSE-12.0
// end::java-versions[]
// tag::dependencies[]

== Features that enable this feature
* feature:appSecurity-1.0[]
// end::dependencies[]
// tag::feature-require[]

== Developing a feature that depends on this feature
If you are developing a feature that depends on the LDAP User Registry 1.0 feature, include the following item in the Subsystem-Content header in the feature manifest file for your new feature:


[source,]
----
com.ibm.websphere.appserver.ldapRegistry-3.0; type="osgi.subsystem.feature"
=======
<server description="LdapRegistry sample configuration">

    <!-- Enable appSecurity-2.0 and ldapRegistry-3.0 features -->
    <featureManager>
        <feature>appSecurity-2.0</feature>
        <feature>ldapRegistry-3.0</feature>
    </featureManager>

    <!-- Sample configuration for LdapRegistry of Active Directory type.
         The password value can be plaintext, or the xor encoded value of the password.
         In this example, the filters for Active Directory have been customized as an external activedLdapFilterProperties element, which is then referenced by the ldapRegistry element. -->

    <ldapRegistry id="ActiveDirectoryLDAP" realm="SampleLdapADRealm" host="host.domain.com" port="389" ignoreCase="true" baseDN="cn=users,dc=domain,dc=com" bindDN="cn=myuser,cn=users,dc=domain,dc=com" bindPassword="mypassword" ldapType="Microsoft Active Directory" activedFilters="myactivedfilters">

        <contextPool enabled="true" initialSize="1" maxSize="0" timeout="0ms" waitTime="3000ms" preferredSize="3"/>
        <ldapCache>
            <attributesCache size="4000" timeout="1200ms" enabled="true" sizeLimit="2000"/>
            <searchResultsCache size="2000" timeout="600ms" enabled="true" resultsSizeLimit="1000"/>
        </ldapCache>
    </ldapRegistry>

    <activedLdapFilterProperties id="myactivedfilters" userFilter="(&(sAMAccountName=%v)(objectcategory=user))" groupFilter="(&(cn=%v)(objectcategory=group))" userIdMap="user:sAMAccountName" groupIdMap="*:cn" groupMemberIdMap="memberOf:member"/>

</server>
>>>>>>> draft
----




include::./gen/ldapRegistry-3.0.gendoc[tag=config]

include::./gen/ldapRegistry-3.0.gendoc[tag=apis]

include::./gen/ldapRegistry-3.0.gendoc[tag=requirements]

include::./gen/ldapRegistry-3.0.gendoc[tag=java-versions]

include::./gen/ldapRegistry-3.0.gendoc[tag=dependencies]

include::./gen/ldapRegistry-3.0.gendoc[tag=feature-require]

include::./gen/ldapRegistry-3.0.gendoc[tag=spi]
