== Examples

=== Managing audit log files

 
The following example shows how to increase the individual file size to 100 MB and reduce the maximum number of archived audit log files to 50. The example also specifies the `compact` attribute, which makes the log file that is written in JSON write the audit records all on the same line in the log file:

[source,xml]
----
<auditFileHandler maxFiles="50" maxFileSize="100" compact=”true”>
</auditFileHandler>
----


=== Specifying the logging of events

To specify only the audit events and outcomes that might be of relevance in an environment, the `<event>` element can be defined with the audit event name and outcome. The following example specifies audit events and outcomes in the `auditFileHandler` element:

[source,xml]
----
<auditFileHandler maxFiles="5" maxFileSize="20" compact="true">
    <events name="AuditEvent_1" eventName="SECURITY_AUTHN" outcome="SUCCESS"/>
    <events name="AuditEvent_2" eventName="SECURITY_AUTHN" outcome="REDIRECT"/>
    <events name="AuditEvent_3" eventName="SECURITY_AUTHN" outcome="FAILURE"/>
    <events name="AuditEvent_4" eventName="SECURITY_AUTHZ"/>
</auditFileHandler>
----


=== Encrypting and signing audit data

The following example shows the audit file handler with encryption and signing enabled. The `encrypt` and `sign` attributes must be specified in the `auditFileHandler` element along with the alias names of the certificates and the keystores in which the certificates exist. The `keystore` element contains the private or public key that is used to encrypt and sign the data:

[source,xml]
----
<keyStore id="auditEncKeyStore” password="Liberty" location="${server.config.dir}/resources/security/AuditEncryptionKeyStore.jks" type="JKS" />

<keyStore id="auditSignKeyStore" password="{xor}EzY9Oi0rJg==" location="${server.config.dir}/resources/security/AuditSigningKeyStore2.jks" type="JKS" />

<auditFileHandler encrypt="true" encryptAlias="#auditencryption#" encryptKeyStoreRef="auditEncKeyStore" sign="true" signingAlias="auditsigning2" signingKeyStoreRef="auditSignKeyStore"
</auditFileHandler>
----


