== Examples

You can require that users log in with a specific social media provider, or you can give them a list of providers so that they can choose which they prefer to log in with. You can also restrict when they have certain log in options based on browser type, the application, and so on. The following examples show how to configure different scenarios in your `server.xml`.

=== Request log in with a social media ID

A customizable selection form is presented so the user can choose which provider they prefer to sign in with. The following example shows how to configure your application to request that the user logs in with their Google ID:

[source,xml]
----
<googleLogin clientId="your_app_id" clientSecret="your_app_secret"  />

<!-- protected apps need to have a security constraint defined -->
<application type="war" id="formlogin" name="formlogin" location="${server.config.dir}/apps/formlogin.war">
    <application-bnd>
        <security-role name="Employee">
            <special-subject type="ALL_AUTHENTICATED_USERS" />
        </security-role>
    </application-bnd>
</application>
----

=== Provide a choice of social media providers to the user

You can provide the user with a choice of social media providers on a form from which they choose one to log in with. The following example presents the user with the choice of Google, GitHub, Facebook, LinkedIn, and Twitter with which to log in:

[source,xml]
----
<googleLogin clientId="your_app_id" clientSecret="your_app_secret"  />
<githubLogin   clientid="your_app_id"          clientSecret="your_app_secret"  />
<facebookLogin clientId="your_app_id"          clientSecret="your_app_secret"  />
<linkedinLogin clientId="your_app_id"          clientSecret="your_app_secret"  />
<twitterLogin  consumerKey="your_app_id"       consumerSecret="your_app_secret"/>

<!-- protected apps need to have a security constraint defined -->
<application type="war" id="formlogin" name="formlogin" location="${server.config.dir}/apps/formlogin.war">
    <application-bnd>
        <security-role name="Employee">
            <special-subject type="ALL_AUTHENTICATED_USERS" />
        </security-role>
    </application-bnd>
</application>
----

=== Request log in with a social media ID only if the users is also in another registry

You can restrict the presentation of a social media provider to only users who are also in another configured registry. For example, use the `mapToUserRegistry` attribute to configure your app so that only users in the company LDAP registry can log in with their Google ID:

[source,xml]
----
 <googleLogin  mapToUserRegistry="true" clientId="your app id"  clientSecret="your app secret"   />

 <ldapRegistry ...> ... </ldapRegistry>

----

For more information on configuring an LDAP registry, see the LDAP User Registry (feature:ldapRegistry[]) feature.

=== Request log in with a social media ID or with their account for the configured registry

You can give users the option of logging in with either a social media provider or with their account on the configured registry. For example, use the `enableLocalAuthentication` attribute to configure your app so that users can have the option of logging in with a Google ID or with their account on their company's LDAP registry:

[source,xml]
----
<!-- user will be presented choice menu of either Google or ldap -->
<googleLogin  clientId="your app id"  clientSecret="your app secret" />

<socialLoginWebapp enableLocalAuthentication="true">

<ldapRegistry id="ldap" ...> ... </ldapRegistry>

----

=== Request log in with a social media ID for only a subset of applications, URLs, browsers, or IP addresses

To protect only a subset of applications, URLs, or IP addresses, use an authentication filter.
The security configuration takes effect only when the conditions in the filter are met. For example,
you might want a web app to be secured with the Social Media Login feature and a microservice app to be secured with the MicroProfile JWT (feature:mp-jwt[]) feature:

// tag::authfilter[]
[source,xml]
----
<!-- only requests with "/mywebapp" in them will be authenticated using Google. -->
<googleLogin  authFilterRef="authFilter1" clientId="your app id"  clientSecret="your app secret" />

<authFilter id="authFilter1">
    <requestUrl
        id="myUrlFilter"
        urlPattern="/mywebapp"
        matchType="contains" />
</authFilter>
----
// end::authfilter[]

For more information, see config:authFilter[].

=== Provide other social media logins as options to the user

To authenticate with a social media provider that is not configured out-of-the-box with Open Liberty, use a
config:oauth2Login[] (for OAuth providers) or config:oidcLogin[] (for OpenID Connect providers) element.
These elements supply the configuration details needed to work with the provider. These details can usually be
obtained from the social media provider's developer instructions.  Here is an example for Instagram:

[source,xml]
----
<oauth2Login id="instagramLogin" clientId="client_id" clientSecret="client_secret"
    scope="basic public_content"   responseType="code"
    tokenEndpointAuthMethod="client_secret_post"
    authorizationEndpoint="https://api.instagram.com/oauth/authorize"
    tokenEndpoint="https://api.instagram.com/oauth/access_token"
    userApi="https://api.instagram.com/v1/users/self"
    userNameAttribute="username"
    website="https://www.instagram.com/developer/authentication/">
</oauth2Login>
----

// LC: Leaving the following links in the source for now to show where this topic should link to when the relevant equivalent topics are published in the Open Liberty docs (do not link to the KC from Open Liberty docs). Remove this commented section when the relevant links are added in future.
//More information on using the socialLogin feature is available https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_sociallogin.html[here].
//More information on using authentication filters is available https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_auth_filter.html[here].

The `socialLogin-1.0` feature can be configured to use OpenShift service accounts to authenticate and authorize protected resource requests.
This configuration allows server administrators to secure, for example, monitoring and metrics endpoints that might produce sensitive information but require repeated access by an automated process or non-human entity.
This security feature allows service accounts to authenticate themselves by providing in the request a service account token that was created within the OpenShift cluster.

The minimum configuration requires only that an `<okdServiceLogin>` element be specified:

[source,java]
----
<server>

<!-- Enable features -->
<featureManager>
  <feature>socialLogin-1.0</feature>
</featureManager>

<okdServiceLogin />

</server>
----

The minimum configuration assumes that the Liberty server is packaged and deployed within an OpenShift cluster.
By default, the `<okdServiceLogin>` element will be used to authenticate all protected resource requests that the Liberty server receives.

Incoming requests to protected resources must include a service account token.
The token must be specified as a bearer token in the Authorization header of the request.
The Liberty server will use the service account token to query information about the associated service account from the OpenShift cluster.
The OpenShift project that the service account is in will be used as the group for the service account when making authorization decisions.
Similarly, the name of the service account will be used as the user name.

If the Liberty server is not deployed within an OpenShift cluster, the `userValidationApi` attribute should be configured and set to the value for the appropriate User API endpoint in the OpenShift cluster:

`<okdServiceLogin userValidationApi="https://cluster.domain.example.com/apis/user.openshift.io/v1/users/~" />`

Multiple <okdServiceLogin> elements can be configured as long as each element has a unique id attribute specified. In those cases, authentication filters should also be configured to ensure the appropriate endpoints are protected by a unique `<okdServiceLogin>` instance.
