// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Contexts and Dependency Injection (CDI) is a framework that improves the structure of application code. It connects different components of an application.
:seo-description: Contexts and Dependency Injection (CDI) is a framework that improves the structure of application code. It connects different components of an application.
:page-layout: general-reference
:page-type: general
= Dependency injection in Microservices with MicroProfile (MP04)

Contexts and Dependency Injection (CDI) is a framework that improves the structure of application code.

The most fundamental services that are provided by CDI are

-	Contexts: This service helps you to bind the lifecycle and interactions of stateful components to well-defined, extensible contexts.
-	Dependency Injection: This service helps you to inject components into an application in a typesafe way.

CDI is an essential element in MicroProfile, as well as in Java EE and Jakarta EE, and connects different components of an application.

MicroProfile specifications take CDI-first approach. They rely on the CDI extension mechanism which implements additional functionalities and enhances existing standards with new capabilities.


== CDI beans
 
Beans are components that can be injected into each other with a dependency injection. Almost every plain old Java&trade object (POJO) with a constructor can be a bean. In CDI, a bean is a source of contextual objects that define application state and/or logic. The beans are managed by CDI containers by using bean-defining annotations. The container instantiates dependencies and controls when and how the components are instantiated and destroyed without your intervention.

Annotations are metadata about code. Use them to decorate a class, method, field, parameter, variable, constructor, or package. You can use annotations to define the scope in which the bean is stored.
= heading2



== CDI Scopes

Use scopes to define the state of a bean. CDI scope type annotations control the bean's lifecycle.

-Use the @ApplicationScoped class-level annotation if an instance is to live as long as the application is active.
-Use the @RequestScoped class-level annotation if a new instance of the bean is to be created for every request (a servlet request, for example).
-Use the @Dependent class-level annotation if the new instance belongs to another object. An instance of a dependent bean is never shared between different clients or different injection points. It is instantiated when the object it belongs to is created, and then destroyed when the object it belongs is destroyed.

If no class-level annotation is defined, @Dependent is the default.

Annotations that define CDI beans must be discovered. CDI annotation scanning can be enabled by using a beans.xml file in the META-INF folder for a .jar archive, or in the WEB-INF folder for a .war archive. This file can be empty, or it can contain something like the following content:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
            http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
      version="1.1" bean-discovery-mode="all">
  // enable interceptors; decorators; alternatives
</beans>
----

The presence of an empty beans.xml file, or a beans.xml with bean-discovery-mode="all", makes all of the potential objects CDI beans. Otherwise, only objects with CDI bean-defining annotations are CDI beans.

==CDI bean injection

CDI injects defined beans into other components through @Inject. For instance, the following POJO MyBean is a CDI bean:

[source,java]
----
@ApplicationScoped
public class MyBean {
	int i=0;
	public String sayHello() {
    	return "MyBean hello " + i++;
	}
}
----

As it is @ApplicationScoped, only one instance is created. In the following, MyRestEndPoint is @RequestScoped, which means an instance is created for each request. CDI injects the same MyBean instance into each.


@RequestScoped
@Path("/hello")
public class MyRestEndPoint {
	@Inject MyBean bean;

	@GET
	@Produces (MediaType.TEXT_PLAIN)
	public String sayHello() {
    	return bean.sayHello();
	}
}









=== See also:
- link:
- link:
- link:
