:page-layout: intro
:page-description: REST, as an architectural style, is one way to implement microservices. REST has become a valuable strategy for microservices, thanks to its simplicity, flexibility and scalability.
:page-categories: REST microservices
:page-permalink: /docs/intro/microprofile.html
:seo-title: REST Microservices
:seo-description: REST, as an architectural style, is one way to implement microservices. REST has become a valuable strategy for microservices, thanks to its simplicity, flexibility and scalability.

= RESTful Microservices

In microservices architecture, each application is designed as an independent service. These services request resources from one another, but are fully capable of operating independently. Any service can provide resources to other services, while also being a client that requests resources from another service. REST, as an architectural style, is one way to implement microservices. REST has become a valuable strategy for microservices, thanks to its simplicity, flexibility and scalability.


One of the strongest advantages of REST for microservices is the independence of client and server. Either can be implemented without any internal knowledge of the other. Therefore the code of the client can be altered without affecting the server, and vice versa, so each component can evolve independently. This separation also improves the flexibility of an interface across different platforms and enhances scalability. REST is therefore an especially good fit for microservices, which generally rely on small, autonomous teams to develop, deploy, and scale their respective services independently.

== MicroProfile and REST

https://openliberty.io/docs/intro/microprofile.html[Eclipse MicroProfile] provides a modular set of technologies that makes developing and using REST APIs easy. These technologies help document your REST API, provide fault tolerance, manage authentication and monitor the metrics and health of your microservice. Since most cloud-native microservices are based on REST APIs, MircoProfile is a valuable resource for building robust, scalable applications.

== Designing RESTfullly
Representational State Transfer (REST) is a methodology for remote data transfer between apps and systems. In a REST compliant (or RESTful) system, each unique URL is a representation of an object. You can access and manipulate the object using standard HTTP operations: 

- GET to retrieve it
- DELETE to delete it
- POST to create it
- PUT to update it. 

REST is not a set of protocols, but an architectural style that makes efficient and effective use of standard HTTP protocols. REST architecture is popular among developers because it's lightweight, concise and easy to build, with human-readable results.

=== What Makes an API RESTful?
The two most important features of a RESTful API are how it receives requests and how it sends responses. A RESTful API must be able to receive unknown attributes as part of a request, without issuing an error. Unknown attributes in a request should simply be ignored. Issuing an errors can lead to unnecessary failures, with negative consequences for the end user.

Secondly, the API should only return the attributes required by the client, without exposing internal service details. Only exposed the attributes needed by the client as part of the API.

RESTful APIs use standard HTTP verbs for CRUD operations, and must pay special attention to whether the operation is idempotent, or safe to retry multiple times.

- POST operations are used to create or update resources, but they can't be invoked repeatedly. If a POST resource is invoked multiple times, it creates a new, unique resource with each invocation.
- GET operations must be able to be invoked repeatedly, without causing side effects. They should only be used to retrieve information.
- PATCH operations enable partial resource updates. They can be invoked repeatedly, depending on how the delta is specified and then applied to the resource.
-DELETE operations  can be invoked multiple times. Even though a resource can only be deleted once, and the response code will be different on subsequent invocations (e.g. 404), the server remains in the same state through multiple invocations.

=== Generating RESTful APIs
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md[OpenAPI v3] is the official specification for RESTful services. https://openliberty.io/guides/microprofile-openapi.html[MicroProfile Open API] provides a Java API for the OpenAPI specification that you can use to expose API documentation for your REST APIs.

There are two ways to create an API:

- *Start with an OpenAPI Definition*: This approach begins by creating an OpenAPI definition in a language independent format (usually YAML). Then a code generator to creates a skeleton, and builds the service implementation from there. This pattern, favored by companies that have a central API design team, enables development and test to progress in parallel.
- *Start with code*: The code is the source of the API definition. This approach is beneficial for applications with an experimental aspect to them, since the API definition evolves as the services becomes more developed and defined. This approach is better suited to some languages than others, since it relies on tools that generate an OpenAPI definition from the code. Java, for example, has excellent support for generating OpenAPI documents from annotation-based REST frameworks.

In either case, working with an OpenAPI definition helps identify  where the API is inconsistent or difficult to understand from a consumer point of view. Build tools can use published or version-controlled OpenAPI definitions to flag breaking changes that could impact consumers.
