// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: SSO configuration with JSON Web Tokens - OpenLiberty.io
:seo-description:
= SSO configuration with JSON Web Tokens

JSON Web Tokens are used to propagate the user identity that is established by SSO between different applications. By configuring SSO user authentication with JSON Web Tokens, you can verify the security of an application.

== Propagating user identity with JSON Web Tokens

After the user identity is established, you can use JSON Web Tokens to ensure the security of your microservice applications. To secure applications, the following details can be verified with JSON Web Tokens when the user identity is shared between the applications:

* The request initiated from a user request
* The identity that the request was made on behalf of
* The request isn't a malicious replay of a previous request.
