// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: general-reference
:page-type: general
:seo-title: SSO configuration with LTPA cookies - OpenLiberty.io
:seo-description:
= SSO configuration with LTPA cookies

Lightweight Third Party Authentication (LTPA) provides single sign-on (SSO) configuration support to authenticate users when they are accessing application servers. With LTPA enabled, you can encrypt, digitally sign, and securely transmit authentication-related data between servers.

== LTPA protocol
Secure communication between application servers is enabled by using the LTPA protocol. The LTPA protocol provides the SSO feature that requires a user to authenticate their identity only when they are connected to a domain name system. After the connection to the DNS is established, the user can access resources in other servers that exist in the same domain without getting prompted to authenticate. The realm names on each system in the DNS domain are case-sensitive and must match identically.

To enable the SSO feature, Cryptographic keys are used to encrypt and decrypt user data that passes between servers with the LTPA protocol. When all the servers that are involved use the same user registry, the keys must be shared between different servers for the resources in one server to access resources in other servers. The configured user registry that is required with must be a centrally shared repository so that users and groups are the same, regardless of the server.

=== Customizing SSO configuration with LTPA cookies
When a user passes authentication on one of the servers that is accessed, authentication information that is generated by the server is transported to the web browser in a cookie. The server uses the cookie to propagate the authentication information to other servers. When SSO is enabled, the LTPA token passes to other servers through cookies for web resources.

LTPA creates a token that contains user information, an expiration time, and is signed by the keys that exist on the server. The LTPA token is time-sensitive with a default expiration time of 120 minutes. Each of the involved servers must have their time and date synchronized. If this is not achieved, LTPA tokens are prematurely expired and cause authentication or validation failures. Coordinated Universal Time (UTC) is used by default, and all other servers must have the same UTC time.

If the receiving servers use the same keys as the originating server, the token can be decrypted to obtain the user information, which then is validated to make sure that the token is not expired and that the user information in the token is valid in its registry. On successful validation, the resources in the receiving servers are accessible after the authorization check.

Each server must have valid credentials. When the credentials expire, the server is required to communicate to the user registry to authenticate. Extending the time that the LTPA token remains cached presents an increased security risk that must be considered when you are defining your security policies.

If key sharing is required between different servers, copy the keys from one server to another. For security purposes, the keys are encrypted with a randomly generated key, and a user-defined password is used to protect the keys. This same password is needed when you are importing the keys into another server. The password is used only to protect the keys, and is not used to generate the keys.

When security is enabled, LTPA is configured by default during the server start time.
