== Example

=== Configure JPA logging

The xref:ROOT:log-trace-configuration.adoc[Open Liberty logging component] supports viewing, tracing, and troubleshooting the runtime behavior of an application. When the Jakarta Persistence API (JPA) feature is enabled, all JPA logging and tracing is routed through the Open Liberty logging component.

You can customize the level of detail for JPA logging by specifying the `logging` element in your `server.xml` file, as shown in the following example:

[source,xml]
----
<logging  traceSpecification="JPA=all" />
----

In this example, the `JPA=all` value for the `traceSpecification` attribute specifies that all JPA container trace and EclipseLink trace categories are enabled. For more information about logging attributes, see xref:reference:config/logging.adoc[the logging element].


Open Liberty logging recognizes the following https://www.eclipse.org/eclipselink/api/2.6/org/eclipse/persistence/logging/SessionLog.html[EclipseLink-specific log categories]: `sql`, `transaction`, `event`, `connection`, `query`, `cache`, `propagation`, `sequencing`, `ejb`, `dms`, `metadata`, `weaver`, `properties`, `server`.

You can enable JPA container trace and all EclipseLink log categories by specifying the following configuration:

[source,xml]
----
<logging  traceSpecification="eclipselink=all" />
----

You can specify individual EclipseLink log categories by using the following syntax for the `traceSpecification` attribute: `eclipselink.{log-category}=all`.

For example, to enable EclipseLink SQL trace, you can specify a configuration similar to the following example:

[source,xml]
----
<logging  traceSpecification="eclipselink.sql=all" />
----

For more information about configuring logging for your EclipseLink JPA instance, see https://wiki.eclipse.org/EclipseLink/Examples/JPA/Logging[EclipseLink: How To Configure Logging].
