== Examples

=== Basic configuration to implement MicroProfile JWT

The `<mpJwt/>` element is required to configure the processing of the caller’s JWT.

The Secure Sockets Layer(SSL)and the JSON Web Token(JWT) uses a keystore by using the maven keytool plugin.The keystore is built by using the maven keytool plugin.The applicaton uses HTTP ports and contains the user and login endpoints. The MP JWT configuration injects the caller's JWT into a ResourceScoped bean for inspection.

[source,xml]
----
    <keyStore id="defaultKeyStore" location="keystore.jceks" type="JCEKS"
              password="secret" />
    <httpEndpoint id="defaultHttpEndpoint" host="*" httpPort="${http.port}"
                  httpsPort="${https.port}"/>
    <webApplication location="${app.name}" contextRoot="/" />
    <mpJwt id="jwtUserConsumer" keyName="default" audiences="simpleapp"
           issuer="${jwt.issuer}"/>
</server>
----

=== Specify login with Micrprofile JSON Web Token for only a subset of applications, URLs, browsers, or IP addresses

To protect only a subset of applications, URLs, or IP addresses, use an authentication filter. The security configuration takes effect only when the conditions in the filter are met. In the following example, requests that target the `myApp` application are processed by the mp-jwt feature:

[source,xml]
----
<mp-jwt authFilterRef="authFilter1" />
<authFilter id="myAuthFilter">
         <webApp id="myWebApp"
         name="myApp"
         matchType="contains"/>
</authFilter>
----
