== Examples

The `mpJwt` feature adds the libraries that are required for MicroProfile JWT implementation.

The `<mpJwt/>` element is required to configure the processing of the caller’s JWT.

[source,xml]
----
<server description="Backend server">
    <featureManager>
        <feature>mpJwt-1.1</feature>
        <feature>transportSecurity-1.0</feature>
        <feature>jaxrs-2.1</feature>
        <feature>jsonp-1.1</feature>
        <feature>cdi-2.0</feature>
        <feature>appSecurity-3.0</feature>
    </featureManager>
----

This is the keystore that is used by SSL and by JWT.
The keystore is built by using the maven keytool plugin,

    <keyStore id="defaultKeyStore" location="keystore.jceks" type="JCEKS"
              password="secret" />

These are the HTTP ports that the application uses,

    <httpEndpoint id="defaultHttpEndpoint" host="*" httpPort="${http.port}"
                  httpsPort="${https.port}"/>

The application that contains the user and login endpoints,

    <webApplication location="${app.name}" contextRoot="/" />

The MP JWT configuration that injects the caller's JWT into a
         ResourceScoped bean for inspection,

    <mpJwt id="jwtUserConsumer" keyName="default" audiences="simpleapp"
           issuer="${jwt.issuer}"/>
</server>

=== Specify login with Micrprofile JSON Web Token for only a subset of applications, URLs, browsers, or IP addresses

To protect only a subset of applications, URLs, or IP addresses, use an authentication filter. The security configuration takes effect only when the conditions in the filter are met. In the following example, requests that target the `myApp` application are processed by the mp-jwt feature:

[source,xml]
----
<mp-jwt authFilterRef="authFilter1" />
<authFilter id="myAuthFilter">
         <webApp id="myWebApp"
         name="myApp"
         matchType="contains"/>
</authFilter>
----
