
== Examples

=== Validating a connection to a database

When you enable the JDBC feature with the Admin REST Connector feature, you can use the `validation` endpoint to validate your server connection to a database. To validate the server connection to a database, you must specify the `validation` endpoint URL to generate output for the database that is configured with the `dataSource` element. The following example shows a Derby database configured as the default data source for an application:
[source,xml]
----
<library id="derby">
    <file name="${server.config.dir}/derby/derby.jar"/>
  </library>

  <dataSource id="DefaultDataSource">
    <jdbcDriver libraryRef="derby"/>
    <properties.derby.embedded databaseName="memory:defaultdb" createDatabase="create" user="dbuser" password="dbpass"/>
  </dataSource>
----

The `id` attribute in the `library` element is set to `derby` to identify the Derby database. The `name` attribute in the embedded `file` element specifies the location of the JAR file that builds the `derby` database. Within the `datasource` element, the `libraryRef` attribute is set to `derby` to reference the `library` element that contains the Derby database that is configured as the default data source. To configure the Derby database as the default data source, the `id` attribute in the `datasource` element is set to `DefaultDataSource`. For more information, see xref:validating-server-connections.adoc[Validating server connections].

=== Validating JCA connection factories

When you enable the JCA feature with the Admin REST Connector feature, you can use the `validation` endpoint to validate your server connection to connection factories. To validate the server connection to a connection factory, you must specify the `validation` endpoint URL to generate output for the connection factory that is configured with the `connectionFactory` element.  The following example shows a connection factory configured with container authentication:
[source,xml]
----
<resourceAdapter location="/test/TestValidationAdapter.rar"/>
 <connectionFactory id="cf1" jndiName="eis/cf1">
   <containerAuthData user="containerAuthUser1" password="1containerAuthUser"/>
   <properties.TestValidationAdapter.ConnectionFactory hostName="myhost.openliberty.io" portNumber="9876"/>
 </connectionFactory>
----

The `id` attribute specifies the `cf1` value that can be used as the uid of the `config` endpoint URL. For more information, see xref:validating-server-connections.adoc[Validating server connections].
