
== Examples

=== Auto federation of user registries

If two or more user registries are configured in your `server.xml` file or in a `userRegistry.xml` file, you can combine them into a single federated registry. To federate two or more user registries, enable both link:/docs/ref/feature/#appSecurity-3.0.html[the Application Security feature] and the Federated User Registry feature and the registries federate by default.

Any user registries, including basic, LDAP, and custom registries, that are defined in the same server configuration federate by default. However,  user registries that are configured with the `quickStartSecurity` element cannot be federated with other registries.

=== Custom federation of user registries

If you want to specify a subset of user registries to federate into custom federated repository,  you can define the `participatingBaseEntry` name attribute in the `federatedRepository` element. This can be useful if you want to exclude certain registries from a federated group by selectively including only the registries you want to federate.

The following example shows the federation of a basic registry and a custom registry in a custom federated repository:

[source,java]
----
<federatedRepository>
    <primaryRealm name="PrimaryRealm">
        <participatingBaseEntry name="o=SampleBasicRealm1"/>
        <participatingBaseEntry name="o=customRegistryRealm1"/>
    </primaryRealm>
</federatedRepository>
----

The participating base entry for a custom or basic registry is the `o` organization attribute set to equal the realm name of that registry, for example, `"o=RealmName"`. The realm name for a user registry is the value that is returned from the `getRealm()` method of that registry. The participating base entry for a custom repository is one of the base entries that is returned by the `getRepositoryBaseEntries()` method for that repository.
