
== Examples

=== Federation of basic registries

If two or more basic registries are configured in your server.xml file or in a userRegistry.xml file, you can combine them into a single federated registry.  To federate two or more basic registries, you must enable both link:/docs/ref/feature/#appSecurity-3.0.html[the Application Security feature] and the Federated User Registry feature, as shown in the following example:

[source,java]
----
<server description="Federation">
    <featureManager>
        <feature>appSecurity-3.0</feature>
        <feature>federatedRegistry-1.0</feature>
    </featureManager>

    <basicRegistry id="basic1" realm="SampleBasicRealm1">
        <user name="admin" password="password" />
        <user name="user1" password="password" />
            <user name="user2" password="password" />
        <group name="memberlessGroup" />
        <group name="adminGroup">
            <member name="admin"/>
        </group>
        <group name="users">
            <member name="user1"/>
            <member name="user2"/>
        </group>
    </basicRegistry>

    <basicRegistry id="basic2" realm="SampleBasicRealm2">
        <user name="user3" password="password123" />
        <user name="user4" password="password123" />
        <group name="memberlessGroup2" />
        <group name="users2">
            <member name="user3"/>
            <member name="user4"/>
        </group>
    </basicRegistry>
</server>
----

User registries that are configured with the `quickStartSecurity` element cannot be federated with other registries.
For information about basic user registries, see link:/docs/ref/general/#basic-registry.html[Basic user registries for application development].

=== Federation of custom registries

You can add basic or custom registries to a custom federated repository by defining the `participatingBaseEntry` name field in the `federatedRepository` element. The participating base entry for a custom or basic registry is the `o` organization attribute set to equal the realm name of that registry (`"o=RealmName"`). The realm name for a user registry is the value that is returned from the `getRealm()` method of that registry. The participating base entry for a custom repository is one of the base entries that is returned by the `getRepositoryBaseEntries()` method for that repository.

The following example shows the federation of a basic registry and a custom registry:

[source,java]
----
<federatedRepository>
    <primaryRealm name="PrimaryRealm">
        <participatingBaseEntry name="o=SampleBasicRealm1"/>
        <participatingBaseEntry name="o=customRegistryRealm1"/>
    </primaryRealm>
</federatedRepository>
----

=== Federation of LDAP registries

LDAP registries are federated by default. For configuration examples, see link:/docs/ref/feature/#ldapRegistry-3.0.html[LDAP User Registry].
