== Change the token expiration time

With JWT SSO you can use a JSON Web Token (JWT) as a Single-Sign-On (SSO).
The following example shows how you can configure JWT SSO to change the token expiration time.

[source, xml]
----
<jwtSso cookieName="myjwt" jwtBuilderRef="myBuilder"/>

 <jwtBuilder id="myBuilder" expiresInSeconds="1800"/>
----

The `jwtBuilderRef` attribute refers to the `jwtBuilder` element myBuilder.
The id attribute of the jwtBuilder element identifies the JWT builder, which is myBuilder in this example. The jwtBuilderRef attribute refers to the myBuilder JWT builder.
The expiresInSeconds attribute indicates that the token expiration time is set to 1,800 seconds for a newly generated token.

== Disable JWT cookies

By default, when a client is authenticated with Open Liberty through the JWT SSO feature, a JWT cookie is created and sent to the HTTP servlet.
The following example disables JWT cookies by specifying the `disableJwtCookie` attribute with a value of true in the `server.xml` file:
In this example configuration, JWT cookies are disabled, so a mechanism other than JWT cookies can be used for authentication.
The following example shows how to disable JWT cookies.

[source, xml]
----
<jwtSso id="sample" disableJwtCookie="true" />
----
