== Configuring JWT SSO to change the token expiration time

With JWT SSO you can use a JSON Web Token (JWT) as a Single-Sign-On (SSO).
The following example shows how you can configure the JWT SSO to change the token expiration time:

[source, xml]
----
<jwtSso cookieName="myjwt" jwtBuilderRef="myBuilder"/>

 <jwtBuilder id="myBuilder" expiresInSeconds="1800"/>
----

The `jwtBuilderRef` attribute refers to the `jwtBuilder` element `myBuilder`.
The `id` attribute for the `jwtBuilder` element  that is named `myBuilder` identifies the JWT builder.
The `expiresInSeconds` attribute indicates the token expiration time that is set to 1800 seconds for a newly generated token.

== Disabling JWT cookies

By default, when a client is authenticated with Open Liberty through the JWT SSO feature, a JWT cookie is created and sent to the HTTP servlet.
The following example disables JWT cookies by specifying the `disableJwtCookie` attribute with a value of `true` in the `server.xml` file:
In this example configuration, JWT cookies are disabled, so a mechanism other than JWT cookies can be used for authentication.

[source, xml]
----
<jwtSso id="sample" disableJwtCookie="true" />
----
