== Examples

=== Configuring an alternative JPA implementation

EclipseLink is the default JPA implementation for Open Liberty. If you want to configure an alternative implementation, specify the `defaultPersistenceProvider` attribute within the `jpa` element in your `server.xml` file. In the following example, Hibernate is specified as the JPA implementation for an application that is named `myApp`:

[source,xml]
----

<jpa defaultPersistenceProvider="org.hibernate.jpa.HibernatePersistenceProvider" />

<library id="HibernateLib">
    <fileset dir="resource1/jpa21_hibernate" includes="*.jar"/>
</library>

<application location="myApp.war">
   <classloader commonLibraryRef="HibernateLib"/>
</application>
----


The `library` element specifies a shared library for administrators. The `fileset` element specifies the base directory to search for files and the file patterns to include in search results. In this example, any files in the `resource1/jpa21_hibernate` directory with the `.jar` extension are included in search results.

To directly reference Hibernate APIs in your application, you must configure a shared library classloader within the `application` element. The `location` parameter specifies the location of the application files. The `classloader` element configures a shared library for the JPA persistence provider, which in this example is `HibernateLib`.
