== Examples

=== Configure a data source
To configure a data source, the following two configuration elements are typically required:

- A `library` element that specifies the location of the JDBC driver file or files
- One or more `dataSource` elements that reference the `library` element


The following example creates a data source that can be injected by using the `jdbc/myDataSource` name. If the feature:jndi-1.0[] feature is enabled, `jdbc/myDataSource` can be used as a JNDI name:

[source,xml]
----
<library id="JdbcLib">
    <fileset dir="server1/jdbc"/>
</library>

<dataSource jndiName="jdbc/myDataSource">
   <jdbcDriver libraryRef="JdbcLib"/>
   <properties databaseName="myDB" serverName="mydb.mycompany.com" portNumber="50000"/>
</dataSource>
----

A servlet or enterprise bean can then get the data source injected with code that is similar to the following example:

[source,java]
----
@Resource(name="jdbc/myDataSource")
private DataSource myDb;

public void insertRochester() throws SQLException {
    try (Connection con = myDataSource.getConnection()) {
       con.createStatement().executeUpdate("INSERT INTO CITIES VALUES('Rochester', 'MN', 'US')");
    }
}
----

=== Provide security credentials for data source authentication

To connect to remote databases, you typically must provide credentials.
These credentials can be configured by specifying an `authData` element. The password can be in
plain text, xor, or aes encrypted. You can use xref:reference:command/securityUtility-encode.adoc[the securityUtility encode command] to create an encoded password. The following example encodes `password` as the
password value:

[source,xml]
----
<authData id="dbCreds" user="dbUser" password="{aes}AEJrzAGfDEmtxI18U/qEcv54kXmUIgUUV7b5pybw/BzH" />

<dataSource jndiName="jdbc/myDataSource" containerAuthDataRef="dbCreds">
   <jdbcDriver libraryRef="JdbcLib"/>
   <properties databaseName="myDB" serverName="mydb.mycompany.com" portNumber="50000"/>
</dataSource>
----

For information about Kerberos and SPNEGO authentication for JDBC data sources, see xref:ROOT:kerberos-authentication-jdbc.adoc[Kerberos authentication for JDBC data sources]

=== Specify a default data source

If you enable any Java EE or Jakarta EE features in Open Liberty, you can configure a default data source. To configure a default data source, set the ID of the `dataSource` element to `DefaultDataSource`, as shown in the following example:

[source,xml]
----
<dataSource id="DefaultDataSource">
<jdbcDriver libraryRef="jdbcLib"/>
<properties serverName="localhost" portNumber="5432"
            databaseName="myDB"
            user="exampleUser" password="examplePassword"/>
</dataSource>
----

=== Enable an application to access to JDBC driver classes

Some applications make use of JDBC driver classes using `Connection.unwrap`. This
means the application needs to be able to view the JDBC driver classes. This is
done by configuring the application classloader to see the JDBC driver classes:

[source,xml]
----
<library id="JdbcLib">
    <fileset dir="server1/jdbc"/>
</library>

<webApplication location="myweb.war" >
    <classloader commonLibraryRef="JdbcLib" />
</webApplication>

<dataSource jndiName="jdbc/myDataSource">
   <jdbcDriver libraryRef="JdbcLib"/>
   <properties databaseName="myDB" serverName="mydb.mycompany.com" portNumber="50000"/>
</dataSource>
----

=== Customize connection pool settings

Connection pooling improves the efficiency of data source connections and operations. Connection pooling for JDBC data sources in Open Liberty is controlled by a connection manager. The connection manager for each data source has sensible default values, but these values can be customized if needed. Any `dataSource` element can specify xref:reference:config/dataSource.adoc#connectionManager[an optional connectionManager element] to customize the connection pool settings, as shown in the following example:


[source,xml]
----
<dataSource jndiName="jdbc/myDB">
  <jdbcDriver libraryRef="jdbcLib"/>
  <connectionManager maxPoolSize="10" minPoolSize="2"/>
  <properties ... />
</dataSource>
----

You can define multiple data sources and associate each with a different connection manager. However, you cannot associate multiple data sources with a single connection manager.
Using thread local storage for connections can increase performance for applications on multi-threaded systems. When you set the `numConnectionsPerThreadLocal` attribute for the `connectionManager` element to 1 or more, these connections per thread are stored in thread local storage. This setting can provide a major improvement on large multi-core (8+) machines by reserving the specified number of database connections for each thread.

For more information, see xref:ROOT:relational-database-connections-JDBC.adoc[Relational database connections with JDBC].
