
== Examples

=== Basic user registry configuration
You can configure Open Liberty to authenticate and authorize users by using a basic user registry. The basic user registry contains user credentials that applications need for security-related tasks. To configure a basic user registry, the Application Security feature must be enabled in the `server.xml` file. The following example shows the configuration of a basic user registry in the `server.xml` file:
[source,xml]
----
<basicRegistry id="basic" realm="WebRealm">
   <user name="Bob" password="bobpwd" />
   <user name="John" password="johnpwd" />
</basicRegistry>
----

To configure a basic user registry with multiple users, you can create groups for users with unique group names as shown in the following example:
[source,xml]
----
<basicRegistry id="basic" realm="WebRealm">
  <user name="Bob" password="bobpwd" />
  <user name="John" password="johnpwd" />
  <user name="user1" password="user1pwd"/>
  <user name="user2" password="user2pwd" />

  <group name="myAdmins">
    <member name="Bob" />
    <member name="user1" />
  </group>

  <group name="users">
    <member name="user1" />
    <member name="user2" />
  </group>
</basicRegistry>
----

For more information, see https://draft-openlibertyio.mybluemix.net/docs/ref/general/#basic-user-registries-application-development.html[Basic user registries for application development].

=== QuickStart security configuration
When you want to configure a basic user registry, you can use the `quickStartSecurity` element to automatically configure a registry that grants the administrator role to a user. The administrator role gives the user the authority to manage applications. To configure a basic user registry with the `quickStartSecurity` element, the Application Security feature must be enabled in the `server.xml` file. The following example shows the `server.xml` file configuration to define the username and password for a user that is granted the administrator role with the `quickStartSecurity` element:
[source,xml]
----
<quickStartSecurity userName="Bob" userPassword="bobpwd" />
----
For more information, see https://draft-openlibertyio.mybluemix.net/docs/ref/general/#basic-user-registries-application-development.html[Basic user registries for application development].

=== LTPA configuration
When the Application Security feature is enabled, Lightweight Third Party Authentication (LTPA) is enabled by default. The following example shows the configuration of the `ltpa` element in the `server.xml` file:
[source,xml]
----
<ltpa keysFileName="yourLTPAKeysFileName.keys" keysPassword="keysPassword" expiration="120" />
----

LTPA configuration can provide Single Sign-on (SSO) to secure applications. For more information, see https://draft-openlibertyio.mybluemix.net/docs/ref/general/#single-sign-on.html[Single sign-on (SSO)].
