
== Examples

- <<#config, Configure transport layer security (TLS)>>
- <<#keystore, Default keystore and TLS certificate configurations>>
- <<#alt, Specify an alternate SSL configuration as default>>
- <<#configure-specific, Configure specific TLS protocols>>
- <<#outbound, Configure outbound TLS>>
- <<#certs, Provide certificates from an environment variable or a file>>
- <<#hostverify, Hostname and IP address verification>>
- <<#cipher-config, Configuring TLS handshake ciphers>>


[#config]
=== Configure transport layer security (TLS)

To enable TLS connections, you must enable the Transport Security feature and add the `keyStore` element to your `server.xml` file.

The server creates a default `keystore` and certificate if you specify `defaultKeyStore` as the ID value for the `keyStore` element in your `server.xml` file. The following example shows the minimum configuration to specify a keystore:

[source,xml]
----
<keyStore id="defaultKeyStore" password="yourPassword"/>
----


[#keystore]
=== Default keystore and TLS certificate configurations

When the `defaultKeyStore` value is specified, Open Liberty builds a TLS configuration around it with an ID attribute value of `defaultSSLConfig`.
If the keystore does not exist on server startup, the server also creates a default keystore file.
In the default TLS configuration, this keystore file is used as both the keystore and truststore.

Open Liberty creates a keystore password when the server is created and puts it in the `${server.config.dir}/server.env` file that is in the server home directory unless the `--no-password` option is specified with the xref:reference:command/server-create.adoc[server create] command. If no `keyStore` element exists to create the default keystore file, this password is used to create a keystore file. This keystore file is then used as the default keystore file. Likewise, if a `defaultKeyStore` entry exists without a password in the `server.xml` file, the keystore password from the `server.env` file is used to open the file.

The `keystore_password` from the `server.env` file is also used as the LTPA keys password if the `keysPassword` attribute in the `ltpa` element in the `server.xml` file and the `ltpa_keys_password` environment variable in the `server.env` file are not defined. For more information, see the `keysPassword` description in the link:https://openliberty.io/docs/latest/reference/config/ltpa.html[LTPA] configuration element.

If you don't want to use the generated keystore password, remove the `keystore_password` entry from the `server.env` file. If a default keystore file was already generated with the password from the `server.env` file, you might need to remove it.

The following table lists the default keystore file details.

.The default keystore details
[%header,cols=2*]
|===
|Keystore details
|Description

|Location
|The keystore file is called `key.p12` and is in the server or client `${server.config.dir}/resources/security` directory.

|Keystore type
|The keystore type is `PKCS12`.

|Password
|The default password is the password that is specified in the `keyStore` element. If no password is provided in the `keyStore` element, `keystore_password` value from the `${server.config.dir}/server.env` file is used.
|===

This default configuration enables all TLS protocols.
The TLSv1, TLSv1.1, TLSv1.2, and  TLSv1.3 protocols are enabled according to what the Java SDK supports.
You can <<#configure-specific,configure specific TLS protocols>> instead of configuring and enabling all of them by default.

The default ciphers include all ciphers that are size 128-bit and higher.
Client authentication is not enabled by the default configuration.

If no certificate exists during TLS initialization, the server also creates a default certificate.
The default certificate is self-signed, with a certificate size of 2048 kb. The validity period is 365 days and the signature algorithm is `SHA256WITHRSA`.
The certificate is created with `CN=<hostname>`,`OU=<client or server name>`,`O=ibm`,`C=US` as the `subjectDN` attribute.
The hostname value is the hostname of the computer where the server is running.

You can also run the xref:reference:command/securityUtility-createSSLCertificate.adoc[securityUtility createSSLCertificate] command to create and customize the default certificate and keystore.

For more information, see xref:reference:config/ssl.adoc[SSL Repertoire].


[#alt]
=== Specify an alternate SSL configuration as default

You can designate a different `ssl` element in the configuration as the default SSL configuration by specifying the `sslRef` attribute on the `sslDefault` element, as shown in the following example:

[source,xml]
----
<sslDefault sslRef="customSSLConfiguration"/>
----


[#configure-specific]
=== Configure specific TLS protocols

Configure TLS protocols on the `sslProtocol` attribute if the underlying JDK support exists for the protocols. Create a comma-separated list from the `TLSv1`, `TLSv1.1`, `TLSv1.2`, and `TLSv1.3` protocol values. This list of protocols overrides the TLS protocols that are enabled in the default TLS configuration.

The TLSv1.3 and TLSv1.2 protocols are configured in the following example:

[source,xml]
----
<ssl id="myDefaultSSLConfig"
      keyStoreRef="defaultKeyStore"
      trustStoreRef="defaultTrustStore"
      sslProtocol="TLSv1.3, TLSv1.2" />
----

=== Use the Java Virtual Machine (JVM) default truststore

You can set the `trustDefaultCerts` attribute to `true` to specify that the JVM default truststore can be used, in addition to the configured truststore, as shown in the following example:

[source,xml]
----
<ssl id="myDefaultSSLConfig"
      keyStoreRef="defaultKeyStore"
      trustStoreRef="defaultTrustStore"
      trustDefaultCerts="true"/>
----


[#outbound]
=== Configure outbound TLS

You can configure Open Liberty to have a global outbound default TLS configuration that is different from the inbound default configuration. Outbound TLS filters are configured on the `outboundConnection` element that is nested in the `ssl` element. You can specify either a host or a host and port to indicate where the outbound SSL connection goes by setting attributes on the `outboundConnection` element.

In the following example, outbound TLS connections that go to any port on the `otherhost` host use the TLS configuration that is specified by the `defaultSSLConfig` value. All other outbound TLS connections use the outbound default TLS configuration that is specified by the `outboundSSLRef` attribute called `outboundSSLSettings`:

[source,xml]
----
<sslDefault outboundSSLRef=”outboundSSLSettings”/>

<ssl id="defaultSSLConfig"
      keyStoreRef="defaultKeyStore"
      trustStoreRef="defaultTrustStore" >
	<outboundConnection host=”otherhost”/>
</ssl>

<keyStore id="defaultKeyStore"
           location="key.p12"
           type="PKCS12"
           password=”yourpassword”/>

<keyStore id="defaultTrustStore"
           location="trust.p12"
           type="PKCS12"
           password="yourpassword"/>

<ssl id="outboundSSLSettings"
      keyStoreRef="outboundKeyStore"
      trustStoreRef="outboundTrustStore"/>

<keyStore id="outboundKeyStore"
           location="server1/outboundKeyFile.p12"
           password="yourpassword"/>

<keyStore id="outboundTrustStore"
           location="server1/outboundTrustFile.p12"
           password="yourpassword"/>
----


[#certs]
=== Provide certificates from an environment variable or a file

At startup, Open Liberty can read certificates from an environment variable so that they can be used to establish trust. To provide a certificate, set the `cert_(name of existing truststore)` environment variable to equal the value of the certificate or a file that contains one or more certificates. Certificates must be either DER encoded or in the PEM format. Environment variables are set in the `server.env` file.

Any value that does not start with the `-----BEGIN CERTIFICATE-----` tag is treated like a file.

In the following example, an environment variable supplies certificates to a truststore that is called `defaultKeyStore` from a file that is called `certs.crt`:

[source,xml]
----
cert_defaultKeyStore=/var/certs.crt
----

In the following example, an environment variable supplies a certificate to a truststore that is called `defaultKeyStore`:

[source,xml]
----
cert_defaultKeyStore="-----BEGIN CERTIFICATE-----
....
-----END CERTIFICATE-----"
----


[#hostverify]
=== Hostname and IP address verification

Hostname and IP address verification are enabled by default. This verification is enforced for target servers in all SSL connections through Open Liberty socket factories. However, you can specify a list of hostnames, IP addresses, or both to skip verification.

To disable hostname verification entirely, set the `verifyHostname` attribute within the `ssl` tag to `false`.

[source,xml]
----
<ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" trustStoreRef="defaultTrustStore" verifyHostname="false"/>
----

When hostname verification is enabled, you can skip verification for hostnames or IP addresses that are specified in the `skipHostnameVerificationForHosts` attribute within the `ssl` tag. The `skipHostnameVerificationForHosts` attribute is a comma-separated list of hostnames, IP addresses, or both.

[source,xml]
----
<ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" trustStoreRef="defaultTrustStore" skipHostnameVerificationForHosts="myHost.com"/>
----

The verification makes sure that the hostname or IP address in the URL matches the Subject Alternative Name (SAN) in the SSL certificate of the server. If the SAN is not found, the property makes sure that the hostname in the URL matches the Common Name (CN). If a mismatch exists, the SSL connection is rejected.

Typically, during hostname verification, when the hostname is used in the request, it checks against the `DNSName` entry in the SAN. If the SAN does not contain a `DNSName` entry, hostname verification uses the certificate owner's Common Name (CN). When an IP address is used in the request, hostname verification relies on the IP address information in the SAN only.

For more information, see xref:ROOT:troubleshooting.adoc#hostverify[Troubleshooting SSL and TLS].


[#cipher-config]
=== Configuring TLS handshake ciphers

The `enabledCiphers` attribute on the `ssl` element allows you to control which cipher suites are used during TLS handshakes. Open Liberty uses the effective JDK cipher list from the JDK, and the `securityLevel` attribute is no longer used. The `enabledCiphers` attribute supports three configuration modes:

1. **Default behavior**: If `enabledCiphers` is empty or not specified, the JDK's effective cipher list is used.

2. **Explicit list**: Provide a custom list of cipher suites, separated by spaces.

3. **Filtering syntax**: Add (`+`) or remove (`-`) cipher suites from the JDK's effective list. A wildcard (`*`) is supported for removal entries only, and must appear at the end of the pattern.

The following example shows the default behavior where no `enabledCiphers` attribute is specified:

[source,xml]
----
<ssl id="defaultSSL" keyStoreRef="defaultKeyStore" trustStoreRef="defaultTrustStore"/>
----

The JDK's effective cipher list varies depending on the Java version and security policies in use. This approach ensures that your server benefits from security updates and improvements provided by JDK updates.

The following example shows an explicit list of cipher suites:

[source,xml]
----
<ssl id="defaultSSL" enabledCiphers="TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA TLS_DHE_DSS_WITH_AES_256_CBC_SHA TLS_DHE_DSS_WITH_AES_128_CBC_SHA TLS_RSA_WITH_AES_128_GCM_SHA256"/>
----

When using an explicit list, you must manually update the configuration over time to include any new cipher suites introduced by JDK updates.

The following example shows the filtering syntax to remove all RSA key exchange cipher suites except `TLS_RSA_WITH_AES_128_GCM_SHA256`:

[source,xml]
----
<ssl id="defaultSSL" enabledCiphers="-TLS_RSA* +TLS_RSA_WITH_AES_128_GCM_SHA256"/>
----

This configuration starts with the JDK's effective cipher list, removes all cipher suites matching the pattern `TLS_RSA*`, and adds back `TLS_RSA_WITH_AES_128_GCM_SHA256`. The filtering syntax allows you to efficiently remove groups of cipher suites using wildcards, while implicitly starting from the full JDK effective cipher list. In contrast, the explicit list approach requires specifying every cipher suite that should be enabled for the TLS handshake.

[NOTE]
====
The explicit list and filtering syntax modes are mutually exclusive. If the `enabledCiphers` value contains both a static entry and a `+`/`-` entry, an error is logged, and the server ignores the `enabledCiphers` value by returning the effective JDK cipher list.
====

