== Examples

=== Configure REST API management roles

You can configure management roles for your Open Liberty server to grant users and groups that are defined in a user registry access to select administrative REST APIs. The administrator role (`administrator-role`) provides read and write access to administrative REST APIs. The reader role (`reader-role`) provides read-only access to administrative REST APIs. Users who are in the reader role can monitor the server but do not have permission to modify it in any way.

In the following example, a user who is named `Bob` and a group that is named `employees` are granted the reader role. A user who is named `Wanda` and a group that is named `managers` are granted the administrator role:

[source,xml]
----
<reader-role>
    <user>Bob</user>
    <group>employees</group>
</reader-role>

<administrator-role>
    <user>Wanda</user>
    <group>managers</group>
</administrator-role>
----Y
To map the dministrative role, use the basic registry.
The following example shows a basic registry that gives the user "bob" or the group "group1" administrator role.

[source,xml]
----
<basicRegistry>
    <user name="bob" password="bobpassword"/>
    <user name="joe" password="joepassword"/>
    <group name="group1" ...>
    </group>
</basicRegistry>

<administrator-role>
    <user>bob</user>
    <group>group1</group>
</administrator-role>
----
To quickly configure a single administrator for testing and development purposes, use the 'quickStartSecurity' element. This option automatically configures a registry with only one user who is granted the administrator role.
The following example shows the minimal required configuration.
[source,xml]
----
<featureManager>
    <feature>restConnector-2.0</feature>
</featureManager>
<quickStartSecurity userName="bob" userPassword="bobpassword" />
<keyStore id="defaultKeyStore" password="keystorePassword"/>
----
To map a role to a user or group that does not exist in the configured user registry, use access IDs. If a user or group is authenticated to a single-sign-on server, use the access ID syntax to specify the security realm where the user is authenticated. Access IDs in Open Liberty take the following formats.

* Access ID for a user:
+
[source,xml]
----
user:<security realm name>/<user name>
----

* Access ID for a group:
+
[source,xml]
----
group:<security realm name>/<group name>
----

To specify access IDs, you can use the `user-access-id` or `group-access-id` elements, as shown in the following example.

[source,xml]
----
<reader-role>
    <user-access-id>user:https://idp.example.com/bob@example.com</user-access-id>
    <group-access-id>group:https://idp.example.com/EmployeeGroups</group-access-id>
</reader-role>

<administrator-role>
    <user-access-id>user:https://idp.example.com/wanda@example.com</user-access-id>
    <group-access-id>group:https://idp.example.com/ManagerGroups</group-access-id>
</administrator-role>
----
