== Examples

=== Configure REST API management roles
When the REST connector feature is enabled, you can configure management roles for your Open Liberty server to grant users and groups that are defined in a user registry access to select administrative REST APIs. The administrator role ('administrator-role') provides read and write access to administrative REST APIs. The reader role (`reader-role`) provides read-only access to administrative REST APIs. Users who are in the reader role can monitor the server but do not have permission to modify it in any way. You can use any supported user registry.
The following example maps users  and groups that are defined in a basic user registry to reader and administrator roles.

[source,xml]
----
<basicRegistry>
    <user name="bob" password="bobpassword"/>
    <user name="wanda" password="wandapassword"/>
    <user name="todd" password="toddpassword"/>

    <group name="managers">
      <member name="wanda"/>
      <member name="todd"/> 
    </group>
</basicRegistry>

<administrator-role>
    <group>managers</group>
</administrator-role>

<reader-role>
    <user>bob</user>
</reader-role>
---
Three users are added to the user registry in the example. 
* The users "wanda" and "todd" are added to a group named as "managers". The "managers" group is granted the administrator role. 
* The user "bob" is granted the reader role.

To quickly configure a single administrator for testing and development purposes, use the 'quickStartSecurity' element. This option automatically configures a registry with only one user who is granted the administrator role.
The following example shows the minimal required configuration.

[source,xml]
---
<featureManager>
    <feature>restConnector-2.0</feature>
</featureManager>
<quickStartSecurity userName="bob" userPassword="bobpassword" />
<keyStore id="defaultKeyStore" password="keystorePassword"/>
----
To map a role to a user or group that does not exist in the configured user registry, use access IDs. If a user or group is authenticated to a single-sign-on server, use the access ID syntax to specify the security realm where the user is authenticated. Access IDs in Open Liberty take the following formats.

* Access ID for a user:
+
[source,xml]
----
user:<security realm name>/<user name>
----

* Access ID for a group:
+
[source,xml]
----
group:<security realm name>/<group name>
----

To specify access IDs, you can use the `user-access-id` or `group-access-id` elements, as shown in the following example.

[source,xml]
----
<reader-role>
    <user-access-id>user:https://idp.example.com/bob@example.com</user-access-id>
    <group-access-id>group:https://idp.example.com/EmployeeGroups</group-access-id>
</reader-role>

<administrator-role>
    <user-access-id>user:https://idp.example.com/wanda@example.com</user-access-id>
    <group-access-id>group:https://idp.example.com/ManagerGroups</group-access-id>
</administrator-role>
----
