== Examples

The Social Media Login feature provides a set of built-in configuration elements for popular social media providers, in addition to generic configuration elements.
The following examples show how to configure different scenarios in the `server.xml` file.

=== Request log in with a social media ID

If multiple social media providers are configured, a customizable selection form is presented.
Thus, the user can sign in with a social media provider of their choice.
The following example shows how to configure your application to request that the user logs in with their Google ID:

[source,xml]
----
<googleLogin clientId="your_app_id" clientSecret="your_app_secret"  />

<!-- protected apps need to have a security constraint defined -->
<application type="war" id="formlogin" name="formlogin" location="${server.config.dir}/apps/formlogin.war">
    <application-bnd>
        <security-role name="Employee">
            <special-subject type="ALL_AUTHENTICATED_USERS" />
        </security-role>
    </application-bnd>
</application>
----

=== Provide a choice of social media providers to the user


You can configure multiple social media providers for users to choose from.
The user receives a customizable selection form before authentication with the available providers.
The following example includes a choice of Google, GitHub, Facebook, LinkedIn, and Twitter:

[source,xml]
----
<googleLogin clientId="your_app_id" clientSecret="your_app_secret"  />
<githubLogin   clientid="your_app_id"          clientSecret="your_app_secret"  />
<facebookLogin clientId="your_app_id"          clientSecret="your_app_secret"  />
<linkedinLogin clientId="your_app_id"          clientSecret="your_app_secret"  />
<twitterLogin  consumerKey="your_app_id"       consumerSecret="your_app_secret"/>

<!-- protected apps need to have a security constraint defined -->
<application type="war" id="formlogin" name="formlogin" location="${server.config.dir}/apps/formlogin.war">
    <application-bnd>
        <security-role name="Employee">
            <special-subject type="ALL_AUTHENTICATED_USERS" />
        </security-role>
    </application-bnd>
</application>
----

=== Require authenticated users to also be present in the configured registry

You can restrict the presentation of a social media provider to only users who are also in another configured registry.
For example, use the `mapToUserRegistry` attribute to configure your app.
Thus, the user must authenticate through Google and also verify as an existing user in the company LDAP registry:

[source,xml]
----
 <googleLogin  mapToUserRegistry="true" clientId="your app id"  clientSecret="your app secret"   />

 <ldapRegistry ...> ... </ldapRegistry>

----

For more information on configuring an LDAP registry, see the LDAP User Registry (feature:ldapRegistry[]) feature.

=== Request log in with a social media ID or with their account for the configured registry

You can give users the option of logging in with either a social media provider or with their account on the configured registry.
For example, use the `enableLocalAuthentication` attribute to configure your app so that users can have the option of logging in with a Google ID or with their account on their company's LDAP registry:

[source,xml]
----
<!-- user will be presented choice menu of either Google or ldap -->
<googleLogin  clientId="your app id"  clientSecret="your app secret" />

<socialLoginWebapp enableLocalAuthentication="true">

<ldapRegistry id="ldap" ...> ... </ldapRegistry>

----

=== Request log in with a social media ID for only a subset of applications, URLs, browsers, or IP addresses

To protect only a subset of applications, URLs, or IP addresses, use an link:https://docs/ref/general/#authentication-filters-specifying-mechanism.html[authentication filter].
The security configuration takes effect only when the conditions in the filter are met. For example,
you might want a web app to be secured with the Social Media Login feature and a microservice app to be secured with the link:https://docs/ref/feature/#mp-jwt.html[MicroProfile JWT] feature:


// tag::authfilter[]
[source,xml]
----
<!-- only requests with "/mywebapp" in them will be authenticated using Google. -->
<googleLogin  authFilterRef="authFilter1" clientId="your app id"  clientSecret="your app secret" />

<authFilter id="authFilter1">
    <requestUrl
        id="myUrlFilter"
        urlPattern="/mywebapp"
        matchType="contains" />
</authFilter>
----
// end::authfilter[]

For more information, see the link:https://docs/ref/config/#authFilter.html[`authFilter`] configuration element..

=== Provide other social media logins as options to the user

To authenticate with a social media provider that isn't configured out-of-the-box with Open Liberty, use the link:https://docs/ref/config/#oauth2Login.html[`oauth2Login`] element for OAuth providers or the link:https://docs/ref/config/#oidcLogin.html[`oidcLogin`] element for OpenID Connect providers.
These elements supply the configuration details that are needed to work with the provider.
The details can usually be obtained from the developer instructions of the social media provider.
The following example configures Instagram as the social media provider::

[source,xml]
----
<oauth2Login id="instagramLogin" clientId="client_id" clientSecret="client_secret"
    scope="basic public_content"   responseType="code"
    tokenEndpointAuthMethod="client_secret_post"
    authorizationEndpoint="https://api.instagram.com/oauth/authorize"
    tokenEndpoint="https://api.instagram.com/oauth/access_token"
    userApi="https://api.instagram.com/v1/users/self"
    userNameAttribute="username"
    website="https://www.instagram.com/developer/authentication/">
</oauth2Login>
----

// LC: Leaving the following links in the source for now to show where this topic should link to when the relevant equivalent topics are published in the Open Liberty docs (do not link to the KC from Open Liberty docs). Remove this commented section when the relevant links are added in future.
//More information on using the socialLogin feature is available https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_sociallogin.html[here].
//More information on using authentication filters is available https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_auth_filter.html[here].

=== Use OpenShift service accounts to authenticate and authorize protected resource requests

The `socialLogin-1.0` feature can be configured to use OpenShift service accounts to authenticate and authorize protected resource requests.
With this configuration, server administrators can secure endpoints, for example, monitoring and metrics endpoints, that might produce sensitive information.
Thus, the service accounts can authenticate themselves by providing a service account token that was created within the OpenShift cluster in the request.

To configure the `socialLogin-1.0` feature, specify the `okdServiceLogin` element.

[source,xml]
----

<okdServiceLogin />

----

The `okdServiceLogin` element authenticates all protected resource requests received by Open Liberty.
The OpenShift project is used as the group for the service account for authorization decisions.
