== Examples

=== Minimal configuration for Open Liberty to act as an OpenID Connect client

To enable your Open Liberty server to act as an OpenID Connect Client, you must also enable the feature:transportSecurity[display=Transport Security] feature, xref:ROOT:user-registries-application-security.adoc[configure a user registry], and configure the truststore of the server to include the signer certificates of the OpenID Connect Providers that are supported.

User identities that are returned by an OpenID Connect Provider (OP) are not mapped to a registry user by default, so no users are required to be configured in the registry. However, if the `mapIdentityToRegistryUser` attribute of the config:openidConnectClient[] element is set to `true`, a user entry must exist for the identity that is returned from the OP in order for authentication and authorization to succeed.

OpenID Connect is configured to use the default TLS configuration that is specified by the server. Therefore, the default TLS configuration for the server must use the truststore that is configured for OpenID Connect. If a default outbound TLS configuration is specified, this configuration must use the truststore that is configured for OpenID Connect. For more information, see link:/docs/latest/reference/feature/transportSecurity-1.0.html#_configure_outbound_tls[Configure outbound TLS].

The following example shows the minimal configuration for the `openidConnectClient` element that works with the default OP.
The client must have a configured application available at the specified URL pattern that can handle redirect requests from an OP. This URL must also precisely match the redirect URL that is registered for the client with the OP.

[source,xml]
---
<openidConnectClient id="client01"
    clientId="client01"
    clientSecret="{xor}LDo8LTor"
    authorizationEndpointUrl="https://server.example.com:443/oidc/endpoint/OidcConfigSample/authorize"
    tokenEndpointUrl="https://server.example.com:443/oidc/endpoint/OidcConfigSample/token">
</openidConnectClient>
---
