
== Sub-elements

The `openidConnectClient` element supports the following sub-elements.

[cols="1,3",options="header"]
|===
|Sub-element |Description

|`protectedResourceMetadata`
|Optional. Enables serving of an OAuth 2.0 Protected Resource Metadata document (RFC 9728) and adds the `resource_metadata` URI to `WWW-Authenticate` headers on 401 responses. See <<#protected-resource-metadata,Serve OAuth protected resource metadata (RFC 9728)>>.
|===

== Examples

The following examples demonstrate configuration options for the OpenID Connect Client feature, which is specified on the `openidConnectClient` element in your `server.xml` file. For a full list of configuration attributes, see the config:openidConnectClient[] element.

- <<#minimal,Minimal configuration for Open Liberty to act as an OpenID Connect client>>
- <<#discovery,Configure a discovery endpoint for an OpenID Connect Provider>>
- <<#jwt,Configure JSON Web Token (JWT) authentication for OpenID Connect>>
- <<#signtoken,Accept signed tokens with signature algorithm validation>>
- <<#jwe,Accept tokens in JWE format>>
- <<#third,Configure a third-party OpenID Connect provider>>
- <<#filter,Support Multiple OpenID Connect Providers>>
- <<#privatekey,Use Private Key JWT for client authentication>>
- <<#ltpa,Disable LTPA cookies>>
- <<#oauth,Accept an OAuth 2.0 bearer access token without redirecting to an OpenID Connect provider>>
- <<#context,Modify the context root>>
- <<#params,Pass request parameters to OpenID Connect>>
- <<#access-token,Check the access token for user and group information>>
- <<#protected-resource-metadata,Serve OAuth protected resource metadata (RFC 9728)>>

[#minimal]
=== Minimal configuration for Open Liberty to act as an OpenID Connect client

To enable your Open Liberty server to act as an OpenID Connect (OIDC) client, you must configure the following prerequisites.

- Enable the OpenID Connect Client and feature:transportSecurity[display=Transport Security] features.
- xref:ROOT:user-registries-application-security.adoc[Configure a user registry].
+
User identities that are returned by an OIDC Provider (OP) are not mapped to a registry user by default, so no users are required to be configured in the registry. However, if the `mapIdentityToRegistryUser` attribute of the `openidConnectClient` element is set to `true`, a user entry must exist for the identity that is returned from the OP.
- Configure a truststore for the server that includes the signer certificates of the OIDC Providers that are supported. Truststores are configured on the config:keyStore[] element in the `server.xml` file.
+
OIDC uses the default TLS configuration that is specified by the server. Therefore, unless you specify an alternative TLS configuration for OIDC, the default TLS configuration for the server must reference the truststore that is configured for OIDC. The following example shows a default TLS configuration in the `server.xml` file that is modified to include a truststore that contains signer certificates for OIDC.
+
[source,xml]
----
<sslDefault sslRef="DefaultSSLSettings" />
<ssl id="DefaultSSLSettings" keyStoreRef="myKeyStore" trustStoreRef="OIDCTrustStore" />
<keyStore id="myKeyStore" password="{xor}EzY9Oi0rJg==" type="PKCS12" location="${server.config.dir}/resources/security/BasicKeyStore.p12" />
<keyStore id="OIDCTrustStore" password="{xor}EzY9Oi0rJg==" type="PKCS12" location="${server.config.dir}/resources/security/OIDCTrustStore.p12" />
----
+
If a default outbound TLS configuration is specified, this configuration must also use the truststore that is configured for OIDC. You can specify a TLS configuration for OIDC other than the default by referencing it from the `sslRef` attribute of the `openidConnectClient` element. Alternatively, you can specify a nondefault truststore for OIDC by referencing the truststore configuration from the `trustStoreRef` attribute for the `openidConnectClient` element. For more information, see link:/docs/latest/reference/feature/transportSecurity-1.0.html#_configure_transport_layer_security_tls[Configure TLS] and the config:openidConnectClient[] element.

The following example shows the minimal configuration for the `openidConnectClient` element to work with the default OP.

The client must have an application configured at the specified URL pattern to handle redirect requests from an OP. This URL must also precisely match the redirect URL that is registered for the client with the OP.

[source,xml]
----
<openidConnectClient id="client01"
    clientId="client01"
    clientSecret="{xor}LDo8LTor"
    authorizationEndpointUrl="https://server.example.com:443/oidc/endpoint/OidcConfigSample/authorize"
    tokenEndpointUrl="https://server.example.com:443/oidc/endpoint/OidcConfigSample/token">
</openidConnectClient>
----

This configuration assumes the following default values.

- `scope=openid profile`
+
You can use the `scope` attribute for the `openidConnectClient` element to specify required scopes. For example, you can change the required scope to `openid profile email`. For more information about OpenID scopes, see the https://openid.net/developers/specs/[OpenID Connect specification].
- The client registers the `\https://<host name>:<ssl port>/oidcclient/redirect/client01` redirect URL with the OP.
+
In this URL, both the hostname and SSL port are automatically resolved and `client01` is the value of the `id` attribute of the `openidConnectClient` element. If a proxy is in front of the RP, you can override the hostname and port by specifying the `redirectToRPHostAndPort` attribute, for example, `redirectToRPHostAndPort="https://<host name>:<ssl port>"`.

The OpenID Connect RP cannot route requests through a proxy host automatically. If you use a proxy to access the OP, the values for any OP-related URL properties must contain the proxy host and port, not the external OP host and port. In most cases, you can replace the OP host and port with the proxy host and port. The URL that you enter must be visible to both the RP and the client browser or application that is used to access the application that is hosted by the RP server. For further guidance on how to determine the correct URL to use, contact your proxy administrator.

[#discovery]
=== Configure a discovery endpoint for an OpenID Connect Provider

The following example shows a minimal configuration that automatically discovers the OP.

[source,xml]
----
<openidConnectClient id="RP"
    clientId="ebb996943plm4450bdb674c211a9fab0"
    clientSecret="g12ciZL1zsVYk6yXTMa2iopa8TBwC178CGq42mdJCALYCdQT1kE1ecB010GE"
    discoveryEndpointUrl="https://example.server.com/oidc/endpoint/OidcConfigSample/.well-known/openid-configuration">
</openidConnectClient>
----

If a discovery endpoint is configured, any other configured OIDC endpoints are ignored and replaced with the following discovered endpoints.

- `issuer`
- `authorization_endpoint`
- `token_endpoint`
- `userinfo_endpoint`
- `jwks_uri`
- `revocation_endpoint`

[#jwt]
=== Configure JSON Web Token (JWT) authentication for OpenID Connect

Any trusted party with a JWT can use that token to access the associated resources in Open Liberty. The Open Liberty server validates the JWT and creates the authenticated subject from it. To be accepted as an authentication token, the JWT must contain `iss`, `sub`, and `exp` claims and be signed with a recognized signature algorithm. Recognized signature algorithms are listed as possible values for the `signatureAlgorithm` attribute of the config:openidConnectClient[] element. An unsigned JWT is accepted when the `signatureAlgorithm` attribute is set to `none`. For more information about signature algorithm configuration options, see <<#signtoken,Accept signed tokens with signature algorithm validation>>. <<#jwe,JSON Web Encryption (JWE)>> is also supported.

To configure an Open Liberty server to accept a JWT as an authentication token, you must set the `inboundPropagation` attribute to `required`. You must also configure a truststore that includes the JSON Web Key (JWK) endpoint certificate so that the Open Liberty server can make TLS connections to the JWK endpoint. If the default truststore for your server does not include the JWK endpoint certificate, you can reference an alternative truststore from the `trustStoreRef` attribute for the `openidConnectClient` element.

In the following example, the default TLS configuration includes the JWK endpoint certificate. This example also assumes that the JWT issuer supports a JWK and the JWT is signed with the RS256 algorithm. The `issuerIdentifier` attribute is configured to match the JWT issuer `iss` claim.

[source,xml]
----
<openidConnectClient id="RS" inboundPropagation="required"
  jwkEndpointUrl="https://example.com/jwtserver/jwk" signatureAlgorithm="RS256"
  issuerIdentifier="https://idp.example.com:8020/jwt" >
</openidConnectClient>
----

The Open Liberty server expects each request to provide a valid JWT and does not create or use single-sign-on (SSO) cookies for JWT authentication. If you want the Open Liberty server to create SSO cookies, set the `authnSessionDisabled` attribute on the `openidConnectClient` element to `false`.

Open Liberty can use the issuer claim from a JWT or JSON web signature (JWS) access token to select an `openidConnectClient` configuration in the `server.xml` file with a matching issuer attribute.

The following `server.xml` file example shows two OpenID Connect client configurations, with a config:authFilter[Authentication Filter] configured to route requests to the `RP2` configuration. If a request with an issuer claim value of `https://hostname/op1` is presented, the `RP1` configuration is selected unless the `rp2filter` applies to the request.

[source,xml]
----
<openidConnectClient id="RP1" issuerIdentifier="https://hostname/op1"  ... />
<openidConnectClient id="RP2" issuerIdentifier="https://hostname/op2" authFilterRef="rp2filter" .../>

<authFilter id="rp2filter">
  ...
</authFilter>
----

Open Liberty selects the `openidConnectClient` configuration to use for a JWT request according to the following algorithm.

1. If the authentication filter matches the request in *only one* `openidConnectClient` configuration element, choose that configuration.
2. If the authentication filter matches the request in *multiple* `openidConnectClient` configuration elements, choose one of the configurations in a nondeterministic manner.
3. If the issuer claim from the JWT matches the `issuerIdentifier` attribute in *only one* `openidConnectClient` configuration element, choose that configuration.
4. If the issuer claim from the JWT matches the `issuerIdentifier` attribute in *multiple* `openidConnectClient` configuration elements, choose one of the configurations in a nondeterministic manner.
5. If there is *one* `openidConnectClient` configuration without an authentication filter, choose that configuration.
6. If there are *multiple* `openidConnectClient` configurations without an authentication filter, choose one of the configurations in a nondeterministic manner.
7. If no match is found, the request is not processed by `openidConnectClient`, and the system determines whether an alternative authentication method is available.

Claim to subject mapping::
If you do not define claim-to-subject mapping, the following default rules apply.
+
- The subject (`sub`) claim is used as the principal name and unique security name of the user.
- The issuer (`iss`) claim is the default realm and is used as the subject realm. If a `realmName` claim is included in the JWT, the `realmName` claim is used as the subject realm instead of the `iss` claim.
+
You can customize how JWT claims are mapped to the subject that Open Liberty creates by specifying the following `openidConnectClient` element attributes.

- `userIdentifier`
- `userUniqueIdentifier`
- `groupIdentifier`
- `realmName`
- `realmIdentifier`
+
If both the `realmName` and `realmIdentifier` attributes are configured, the `realmName` value takes precedence and the `realmIdentifier` value is ignored.
+
You can specify an alternative claim as the value for any of these attributes. For example, to use the `name` claim for the principal name instead of the `sub` claim, you can specify `userIdentifier="name"`. For more information about these attributes, see the config:openidConnectClient[] element.
+
You can also programmatically map JWT to subjects by implementing the `com.ibm.wsspi.security.oauth.UserCredentialResolver` service programming interface (SPI). For more information, see the Java documentation that is provided with the Open Liberty installation in the `${wlp.install.dir}/dev/spi/ibm/` directory.

JWT audiences::
To define a list of trusted audiences, configure the `audiences` attribute on the `openidConnectClient` element.
+
A valid JWT must satisfy one of the following conditions.

- If the `audiences` attribute is configured, the `aud` claim value in the JWT must be one of the configured audiences. To ignore the audience check, set the `audiences` attribute to `ALL_AUDIENCES`.
- If the `audiences` attribute is not configured, but the JWT contains an `aud` claim that is a valid URL, the URL for the resource that is being accessed must include the complete `aud` value as a prefix.
+
For example, the following audience is valid because the resource URL begins with the complete `aud` claim value from the JWT.

  ** Audience claim: `"aud":"https://<server>:<port>/something"`
  ** Resource service URL: `\https://<server>:<port>/something/specific`

Resource requests::
If a web client sends a JWT to an Open Liberty server in the request `Authorization` header or as a form-encoded body parameter, no extra server configuration is required. If the JWT is sent in a customized request header field, you must configure the `headerName` attribute for the `openidConnectClient` element to equal the name of the field, as shown in the following example.
+
[source,xml]
----
<openidConnectClient id="customHeader"
    ...
    headerName="jwt"
    ...
</openidConnectClient>
----
+
With this configuration, a web client can send the token on the `jwt` header field, as shown in the following resource request example.
+
----
GET /resource HTTP/1.1
Host: server.example.com
jwt: mF_9.B5f-4.1JqM
----

[#signtoken]
=== Accept signed tokens with signature algorithm validation

The OpenID Connect client validates the signature of ID tokens and access tokens to ensure their authenticity and integrity. To configure the Open Liberty OIDC client to process signed tokens, you must set the `signatureAlgorithm` attribute to either a single signature algorithm or to `FROM_HEADER` to use the algorithm specified in the token header.

==== Specify a fixed signature algorithm

You can configure the client to accept tokens signed with a specific algorithm by setting the `signatureAlgorithm` attribute to a recognized signature algorithm. When a fixed algorithm is specified, the client rejects any token that is not signed with that algorithm.

The following example shows a configuration that accepts only tokens signed with `RS256`:

[source,xml]
----
<openidConnectClient 
    id="RP"
    clientId="client01"
    clientSecret="{xor}LDo8LTor"
    signatureAlgorithm="RS256"
    jwkEndpointUrl="https://example.com/jwtserver/jwk"
    ...
/>
----

==== Use the signature algorithm from the token header

You can configure the client to use the signature algorithm from the token header by setting the `signatureAlgorithm` attribute to `FROM_HEADER`. This configuration allows the client to accept tokens signed with different algorithms without requiring separate client configurations.

When `signatureAlgorithm` is set to `FROM_HEADER`, the OpenID Connect client reads the `alg` claim from the JOSE header and uses that algorithm for signature verification. By default, when this option is selected, tokens signed with any Liberty-supported signature algorithm are accepted. For enhanced security, you can restrict which signature algorithms are permitted by configuring the `allowedSignatureAlgorithms` attribute. This attribute accepts a comma-separated list of algorithm names. Only tokens signed by algorithms in this list are validated.

The following example shows a configuration that accepts tokens signed with a mixed group of algorithms (`RS256`, `ES384`, or `HS512`):

[source,xml]
----
<openidConnectClient 
    id="RP"
    clientId="client02"
    clientSecret="{xor}LDo8LTor"
    signatureAlgorithm="FROM_HEADER"
    allowedSignatureAlgorithms="RS256, ES384, HS512"
    jwkEndpointUrl="https://example.com/jwtserver/jwk"
    ...
/>
----

==== Key selection for signature verification

When you use asymmetric algorithms and a trust store configuration, the client uses the following strategies to locate the appropriate public key for signature verification:

- With `FROM_HEADER`: The public keys must be prefixed with their corresponding algorithm for automatic selection. The client identifies the `alg` claim from the token header and searches the trust store for a key alias beginning with that value. For example, the alias `rs256_key` is used for tokens signed with `RS256`. If no algorithm-prefixed key is found, the client falls back to using the key specified by the `trustAliasName` attribute.

- Without `FROM_HEADER` (Single Algorithm): The client uses only the key specified by the `trustAliasName` attribute for signature verification.

Alternatively, for either of these configurations, you can configure JWK-based verification as described in xref:ROOT:json-web-token.adoc[Sign and verify JSON Web Tokens with JSON Web Keys].

[#jwe]
=== Accept tokens in JWE format

In version 22.0.0.1 and later, you can configure an Open Liberty OIDC client to process access and ID tokens that are in a JWE format. The corresponding OP must support creating JWE access or ID tokens. Configure the OP to use the OIDC client public key that is used to encrypt the Content Encryption Key, according to the OIDC Provider documentation.

The following example shows a configuration to accept JWTs in JWE format.

[source,xml]
----
<openidConnectClient id="JWE" inboundPropagation="required"
  jwkEndpointUrl="https://example.com/jwtserver/jwk" signatureAlgorithm="RS256"
  issuerIdentifier="https://idp.example.com:8020/jwt"
  keyManagementKeyAlias="privateKeyAlias"
  accessTokenCacheEnabled="true"
  accessTokenCacheTimeout="10s"
  tokenReuse="true">
</openidConnectClient>
----

* You must set the `keyManagementKeyAlias` attribute to the private key alias of the key management key that is used to decrypt the Content Encryption Key of the JWE format token. This key must exist in the keystore that is configured for OIDC.
* This example specifies optional attributes to configure the RP to cache access token validation results for inbound propagation.
  ** The `accessTokenCacheEnabled` attribute enables validation results to be cached.
  ** The `accessTokenCacheTimeout` attribute specifies a duration that the authenticated subject is cached.
  ** The `tokenReuse` attribute specifies that the OpenID Connect client must cache results for a JWT that includes a `jti` claim.

If you manage single sign-on (SSO) for OIDC with the feature:socialLogin[display=Social Login] feature, you can enable that feature to process tokens in JWE format. Specify the `keyManagementKeyAlias` attribute on the `oidcLogin` element. Set the value to the private key alias of the key management key that is used to decrypt the Content Encryption Key of the JWE format token. For more information, see config:oidcLogin[display=OIDC Social Login].

==== FIPS 140-3

The Semeru implementation of FIPS 140-3 requires the use of ECDH algorithms for key agreement during encryption. The FIPS module currently in use by IBM Semeru Runtimes might not fully support RSA-OAEP operations, or might require a workaround to support them. For more information or updates, check the link:https://www.ibm.com/support/pages/semeru-runtimes-getting-started[IBM Semeru Runtimes release information or version fixes]. In the meantime, to use RSA-OAEP when FIPS 140-3 is enabled, see the <<#oidc-sl-jwt-rsa-ex,OIDC Client, Social Login, or JWT using RSA-OAEP example>> section.

Use of ECDH algorithms requires the use of EC keys. See <<#gen-ec-keys,Generate EC keys for ECDH>>.

To set up your OIDC Client, Social Login, or JWT consumer to use ECDH-ES, add the EC private key to the keystore and configure the following depending on whether you are using `openidConnectClient`, `oidcLogin`, or `jwtConsumer`.

[source,xml]
----
<openidConnectClient keyManagementKeyAlias="myECPrivateKey" />
----

[source,xml]
----
<oidcLogin keyManagementKeyAlias="myECPrivateKey" />
----

[source,xml]
----
<jwtConsumer keyManagementKeyAlias="myECPrivateKey" />
----

`myECPrivateKey` is the alias for the EC private key.

To set up your JWT builder to use ECDH-ES, add the EC public key to the keystore and configure the following.

[source,xml]
----
<jwtBuilder keyManagementKeyAlgorithm="ECDH-ES" keyManagementKeyAlias="myECPublicKey" />
----

`myECPublicKey` is the alias for the EC public key.

[#oidc-sl-jwt-rsa-ex]
===== OIDC Client, Social Login, or JWT using RSA-OAEP example

If your OIDC Client, Social Login, or JWT configuration cannot support ECDH-ES, and you must use RSA-OAEP, add the following to the FIPS140-3-Liberty-Application.properties custom profile file created when FIPS 140-3 is configured:

[source,xml]
----
RestrictedSecurity.OpenJCEPlusFIPS.FIPS140-3-Liberty-Application.jce.provider.2 = sun.security.provider.Sun [+ \
    {MessageDigest, SHA-1, *, FullClassName:org.jose4j.jwa.AlgorithmFactory}, \
    {MessageDigest, SHA-1, *, FullClassName:org.jose4j.jwe.CipherUtil}, \
    {MessageDigest, SHA-1, *, FullClassName:org.jose4j.jwe.WrappingKeyManagementAlgorithm}]
RestrictedSecurity.OpenJCEPlusFIPS.FIPS140-3-Liberty-Application.jce.provider.4 = com.sun.crypto.provider.SunJCE [+ \
    {Cipher, RSA, *, FullClassName:org.jose4j.jwa.AlgorithmFactory}, \
    {Cipher, RSA, *, FullClassName:org.jose4j.jwe.CipherUtil}]
----

NOTE: This is an example. You might need different constraints based on your application.

This adds the constraints to the already registered Sun and SunJCE providers to enable the RSA-OAEP key agreement algorithm. The constraints to be added will be discovered through the troubleshooting process as described in link:https://www.ibm.com/docs/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_fips_troubleshoot.html[Troubleshooting FIPS 140-3 on Liberty]. For more information about the custom profile file, see link:https://www.ibm.com/support/pages/node/7113528#creatingextensionsofprofiles[Creating extensions of profiles].

[#gen-ec-keys]
===== Generate EC keys for ECDH

To use ECDH, configure the EC keys in the keystores.

You can generate the EC public and private key pair by using `securityUtility` or `keytool`, for example:

[source,xml]
----
./securityUtility createSSLCertificate --sigAlg=SHA256withECDSA --keySize=256 --server=myServer --validity=3650 --password=password
----

[source,xml]
----
keytool -genkeypair -alias eccert -keyalg EC -groupname secp256r1 -validity 3650 -storetype pkcs12 -keystore 
----

[#third]
=== Configure a third-party OpenID Connect provider

To configure the Liberty OIDC client to use a third-party OIDC Provider, such as Microsoft Azure or Google, you must configure the following attributes. Obtain these attribute values by calling the OP discovery endpoint, which provides a JSON document at the path that is formed by adding the `/.well-known/openid-configuration` string to the issuer URI. For example, for Google, this document is available at the `\https://accounts.google.com/.well-known/openid-configuration` URL.

- `jwkEndpointUrl`
+
Set this attribute to the URL of the OP JSON Web Key Set document that is defined by the `jwks_uri` value in the discovery file.
- `issuerIdentifier`
+
Set this attribute to the issuer as defined in the discovery file. An ID Token that does not contain this value as an `iss` claim is rejected.
- `signatureAlgorithm="RS256"`
+
The Liberty OIDC client default signature algorithm is HS256.
- `userIdentityToCreateSubject`
+
Set this attribute to a claim name that is used by the vendor ID Token that represents a user's unique identifier.
- `groupIdentifier`
+
Set the attribute to the claim name that represents the user's group memberships or roles.

The following example shows a configuration to connect to Google as an OIDC Provider.

[source,xml]
----
<openidConnectClient id="sample client"
    clientId="ebb996943plm4450bdb674c211a9fab0"
    clientSecret="g12ciZL1zsVYk6yXTMa2iopa8TBwC178CGq42mdJCALYCdQT1kE1ecB010GE"
    discoveryEndpointUrl="https://accounts.google.com/.well-known/openid-configuration"
    jwkEndpointUrl="https://www.googleapis.com/oauth2/v3/certs"
    issuerIdentifier="https://accounts.google.com"
    signatureAlgorithm="RS256"
    userIdentityToCreateSubject="email"
    groupIdentifier="aud">
</openidConnectClient>
----

[#filter]
=== Support Multiple OpenID Connect Providers

You can configure Open Liberty as an OIDC client to multiple OPs by creating multiple `openidConnectClient` elements and setting authentication filters to route incoming authentication requests to each configuration. Each `openidConnectClient` element defines one SSO relationship with one OIDC Provider. Use the `authFilterRef` attribute to specify the authentication filter for each `openidConnectClient` element.

In the following example, authentication requests that contain the `/mywebapp/members` URL pattern are filtered to the OP that is referenced by the `RP1` configuration. Authentication requests that contain the `/mywebapp/guests` URL pattern are filtered to the OP that is referenced by the `RP2` configuration.

[source,xml]
----
<openidConnectClient id="RP1"
    authFilterRef="authFilter1"
    clientId="RP1"
    clientSecret="{xor}LDo8LTor"
    authorizationEndpointUrl="https://server.example.com:443/oidc/endpoint/OidcConfigSample/authorize"
    tokenEndpointUrl="https://server.example.com:443/oidc/endpoint/OidcConfigSample/token">
</openidConnectClient>

<openidConnectClient id="RP2"
    authFilterRef="authFilter2"
    clientId="RP2"
    clientSecret="{xor}DLo8LTor"
    authorizationEndpointUrl="https://server.example2.com:443/oidc/endpoint/OidcConfigSample/authorize"
    tokenEndpointUrl="https://server.example2.com:443/oidc/endpoint/OidcConfigSample/token">
</openidConnectClient>

<authFilter id="authFilter1">
    <requestUrl
        id="myUrlFilter"
        urlPattern="/mywebapp/members"
        matchType="contains" />
</authFilter>

<authFilter id="authFilter2">
    <requestUrl
        id="myUrlFilter2"
        urlPattern="/mywebapp/guests"
        matchType="contains" />
</authFilter>
----

For more information, see xref:ROOT:authentication-filters.adoc[Authentication filters].

[#privatekey]
=== Use Private Key JWT for client authentication

OpenID Connect clients in Open Liberty support the `private_key_jwt` client authentication method with OpenID Connect token endpoints. OpenID Connect clients must provide authentication data to the OpenID Connect provider to access the provider's token endpoint. Clients can authenticate by using several different methods, but most of those methods require a client secret. The `private_key_jwt` authentication method allows clients to use asymmetric keys to create signed JWTs to authenticate instead of client secrets. By using this authentication method, OpenID Connect clients in Open Liberty no longer need a client secret.

Server administrators can enable this function by using the `private_key_jwt` option for the `tokenEndpointAuthMethod` attribute, and the `tokenEndpointAuthSigningAlgorithm` and `keyAliasName` attributes in the `openidConnectClient` element.

[source,xml]
----
<openidConnectClient id="myOidcClientUsingPrivateKeyJwt"
    tokenEndpointAuthMethod="private_key_jwt"
    tokenEndpointAuthSigningAlgorithm="E512"
    keyAliasName="privatekeyaliasES512"
    ...
/>
----

The `tokenEndpointAuthSigningAlgorithm` attribute specifies the signing algorithm to sign the JWT that is used for client authentication. The `keyAliasName` attribute points to the private key to use to sign the JWT. The private key must be present in the keystore that is specified by the `sslRef` attribute in the config:openidConnectClient[display=OpenID Connect client configuration]. OpenID Connect providers that support Private Key JWT client authentication typically provide an interface for administrators to upload their corresponding public key.

For more information about `private_key_jwt` client authentication, see the https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication[OpenID Connect core specification] and https://datatracker.ietf.org/doc/html/rfc7523[RFC 7523].

[#ltpa]
=== Disable LTPA cookies

The Open Liberty OIDC client automatically creates an SSO token after the ID Token is processed. You can configure the server not to create an SSO token by specifying the `disableLtpaCookie` attribute for the `openidConnectClient` element.

[source,xml]
----
<openidConnectClient id="nocookie"
    ...
    disableLtpaCookie="true"
    ...
</openidConnectClient>
----

When you set this attribute to `true`, the Open Liberty OIDC client accepts only authentication requests that were previously authenticated with the configured OP. The authentication session lifetime is limited to the lifetime of the ID Token from that OP.

[#oauth]
=== Accept an OAuth 2.0 bearer access token without redirecting to an OpenID Connect provider

You can configure an OIDC client to optionally accept a valid OAuth 2.0 bearer access token as an authentication token without redirecting the request to an OIDC provider. With this configuration, if a request contains a valid OAuth 2.0 bearer access token, the Open Liberty OIDC client automatically validates it and creates an authenticated subject based on the token validation result. If the request does not contain an access token or the access token is invalid, the Open Liberty OIDC client continues to redirect the user to an OIDC provider. This function enables the Open Liberty server to serve both browser clients and nonbrowser clients such as RESTful clients.

[source,xml]
----
<openidConnectClient id="nocookie"
    ...
    inboundPropagation="supported"
    ...
</openidConnectClient>
----

[#context]
=== Modify the context root

If your hosting environment does not allow access to the `/oidcclient` context root, you can modify the context root by configuring the config:oidcClientWebapp[] element. By default, the Open Liberty OIDC client redirect servlet listens on the `/oidcclient` context root, and the redirect URL format is `https://_host_name_: _ssl_port_/oidcclient/redirect/_configuration_ID_`. If you cannot use this context root, you can set a different context root.

For example, if your hosting environment requires that you use the `/example/openid` context root, add the following element in your `server.xml` file.

[source,xml]
----
<oidcClientWebapp contextPath="/example/openid" />
----

The resulting redirect URL format is `https://_host_name_: _ssl_port_/example/openid/redirect/_configuration_ID_`.

[#params]
=== Pass request parameters to OpenID Connect

To provide extra authorization parameters to the OP, configure `authzParameter` elements. For example, the following configuration properties pass `api_key` and `account` parameters to the authorization endpoint.

[source,xml]
----
<authzParameter name="api_key" value="567890" />
<authzParameter name="account" value="123456" />
----

To configure parameters for the token endpoint, use the `tokenParameter` element.

[#access-token]
=== Check the access token for user and group information

If `userIdentifier` or `groupIdentifier` values are not found in the ID token, Open Liberty can also check the access token and the `UserInfo` endpoint.

Set the `tokensOrderToFetchCallerClaims` attribute to `AccessToken IDToken Userinfo`, as shown in the following example.

[source,xml]
----
<openidConnectClient tokensOrderToFetchCallerClaims="AccessToken IDToken Userinfo"  userIdentifier="unique_name" groupIdentifier="aud" ... />
----

In this example, Open Liberty checks for `userIdentifier` and `groupIdentifier` values first in the access token, then in the ID token, and finally in the `UserInfo` endpoint. If the values are not found in any of those locations, an unauthorized response code is returned.

If the `tokensOrderToFetchCallerClaims` attribute is not specified, the default value is `IDToken` and Open Liberty checks only the ID token for user and group information.

[#protected-resource-metadata]
=== Serve OAuth protected resource metadata (RFC 9728)

OAuth 2.0 Protected Resource Metadata (https://datatracker.ietf.org/doc/html/rfc9728[RFC 9728]) allows a resource server to publish a well-known JSON document describing how clients can obtain access tokens. This enables MCP clients and other OAuth clients to automatically discover the authorization server without any prior configuration.

Add a `<protectedResourceMetadata>` sub-element to your `<openidConnectClient>` configuration. When the sub-element is present, Liberty:

* Serves the metadata document at `/.well-known/oauth-protected-resource/<protected-path>` for every path matched by the configured `authFilter`.
* Includes the `resource_metadata` URI in the `WWW-Authenticate` response header whenever a request to a protected resource is rejected with a 401 status code.

The `<protectedResourceMetadata>` sub-element is optional and accepts the following attributes.

[cols="1,1,1,3",options="header"]
|===
|Attribute |Type |Default |Description

|`advertisedScopes`
|String (comma-separated)
|—
|Scopes to publish in the metadata document, for example, `toys_browse, cart_read`.

|`jwtBuilderRef`
|String
|—
|Reference to a `<jwtBuilder>` element used to sign the metadata JWT.
|===

[source,xml]
----
<openidConnectClient id="protected-resource-demo"
    clientId="protected-resource"
    clientSecret="..."
    jwkEndpointUrl="https://auth.example.com/oidc/endpoint/SampleProvider/jwk"
    tokenEndpointAuthMethod="basic"
    issuerIdentifier="https://auth.example.com/oidc/endpoint/SampleProvider"
    authFilterRef="mcpAuthFilter"
    inboundPropagation="required">
    <protectedResourceMetadata
        advertisedScopes="toys_browse, toys_search, cart_read, cart_write"/>
</openidConnectClient>
----

==== Example: metadata document

When a client sends a `GET` request to `/.well-known/oauth-protected-resource/myApp/protected`, Liberty responds with the following document.

----
HTTP/1.1 200 OK
Content-Type: application/json

{
  "resource": "https://resource.example.com/myApp/protected",
  "authorization_servers": ["https://auth.example.com/oidc/endpoint/SampleProvider"],
  "scopes_supported": ["toys_browse", "toys_search", "cart_read", "cart_write"]
}
----

* `resource` — the absolute URL of the protected resource.
* `authorization_servers` — populated from the `issuerIdentifier` attribute of the matching `<openidConnectClient>`. If `issuerIdentifier` is not set, Liberty derives the authorization server from `validationEndpointUrl` by stripping its last path segment (for example, `\https://as.example.com/introspect` becomes `\https://as.example.com`). If neither is configured, the field is omitted.
* `scopes_supported` — present only when `advertisedScopes` is configured on `<protectedResourceMetadata>`; omitted otherwise.

NOTE: Requests for paths not protected by any `openidConnectClient` return a 404 response.

==== Example: 401 response with resource_metadata

When a request to a protected resource is rejected because no valid token is present, Liberty returns the following response.

----
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Bearer realm="oauth", resource_metadata="https://resource.example.com/.well-known/oauth-protected-resource/myApp/protected"
----

The `resource_metadata` URL points to the metadata document for the specific protected path. A client can follow this URL to discover the authorization server automatically.

==== Related information

* https://datatracker.ietf.org/doc/html/rfc9728[RFC 9728: OAuth 2.0 Protected Resource Metadata]
* https://modelcontextprotocol.io/specification/2025-06-18/basic/authorization#authorization-server-location[MCP Authorization specification]
