== Examples

=== Overriding the default HTTP/2 protocol configuration for Java servlet 4.0 and 3.1

When the Java servlet 4.0 feature is enabled in Open Liberty, the `HTTP/2` protocol is enabled by default for all secure and insecure ports. When the Java servlet 3.1 feature is enabled in Open Liberty, the HTTP/2 protocol is disabled by default for all secure and insecure ports. To override the default settings, you can configure individual ports of the Open Liberty server to use the `HTTP/2` protocol.

==== HTTP/2 protocol configuration for Servlet 4.0

To override the default `HTTP/2` configuration for the Java servlet 4.0 feature, you can add a `protocolVersion = "http/1.1"` attribute to the `httpEndpoint` element of the `server.xml` file:

[source,xml]
----
<httpEndpoint httpPort="9080"
              httpsPort="9043"
              id="defaultHttpEndpoint"
              protocolVersion="http/1.1">
</httpEndpoint>
----

==== HTTP/2 protocol configuration

To override the default  `HTTP/2` configuration for the Java servlet 3.1 feature, you can add the `protocolVersion = "http/2"` attribute to the `httpEndpoint` element of the server.xml file:

[source,xml]
----
<httpEndpoint httpPort="9080"
              httpsPort="9043"
              id="defaultHttpEndpoint"
              protocolVersion="http/2">
</httpEndpoint>
----
