== Examples

The following example shows how to configure the server to construct a JWT for an application:

[source, xml]
----
<keyStore id="defaultKeyStore" password="keyspass"/>

<jwtBuilder expiresInSeconds="600" id="myBuilder" issuer="https://example.com" keyAlias="default"/>

----
This `ID` element is used to identify the JWT builder.
The `issuer` element is a case-sensitive URL using the HTTP or HTTPS scheme, and the `expiry` element indicates the token expiration time in hours.

To obtain JWT from the JWT generation endpoint in the `jwt-1.0` feature, authenticate with your credentials to access the JWT generation endpoint at the following URL:

`https://localhost:9443/jwt/ibm/api/myBuilder/token`

After authentication succeeds, the MP-JWT format token is returned in JSON form.
The token contains the user ID and any groups to which the user belongs, as recorded in the user registry of the server.

Use the `<configId>` ID to refer to a corresponding `JWTBuilder` entry in the `server.xml` file.
Specify token attributes, such as issuer and expiration time, in the `JWTBuilder` entry.
If you do not define `JWTBuilder` elements in the `server.xml` file, use the `defaultJWT` element as the `<configId>` ID.

For JWT builder configuration attributes, see link:https://www.openliberty.io/docs/ref/config/#jwtBuilder.html[JWT Builder].

Configure the `JWTBuilder` in the `server.xml` file if another feature is using it. If a user’s application is using the `JWTBuilder` entry, they can either configure it in the `server.xml` file, or construct it programatically.
Within Open Liberty installation, the API documentation can be found at `/dev/api/ibm/javadoc/com.ibm.websphere.appserver.api.jwt_1.1-javadoc.zip`.
