== Examples

The JWT builder is used for the creation of JWTs.
The following example shows how to configure the server to construct a JWT for an application:

[source, xml]
----
<keyStore id="defaultKeyStore" password="keyspass"/>

<jwtBuilder expiresInSeconds="600" id="myBuilder" issuer="https://example.com" keyAlias="default"/>

----
The `ID` attribute for the `jwtBuilder` element is used to identify the JWT builder.
The `issuer` attribute is a case-sensitive URL that uses the HTTP or HTTPS scheme, and the `expiry` attribute indicates the token expiration time.

After you configure the `jwtBuilder`, you can generate a JWT from the JWT generation endpoint in the `jwt-1.0` feature and authenticate with your credentials to access the JWT generation endpoint at the following URL:

`https://localhost:9443/jwt/ibm/api/<ID>/token`

ID is the value of the `id` element in the `JWTBuilder` entry in the `server.xml` file.
If you do not define `JWTBuilder` elements in the `server.xml` file, use the `defaultJWT` element as the `ID`.
After authentication succeeds, the MP-JWT format token is returned in JSON form.
The token contains the user ID and any groups to which the user belongs, as recorded in the user registry of the server.
Specify token attributes, such as issuer and expiration time, in the `JWTBuilder` entry.
For JWT builder configuration attributes, see link:https://www.openliberty.io/docs/ref/config/#jwtBuilder.html[JWT Builder].

JWTBuilder can be used programmatically.
Within Open Liberty installation, the API documentation can be found at `/dev/api/ibm/javadoc/com.ibm.websphere.appserver.api.jwt_1.1-javadoc.zip`.
