== Examples

The `jwt-1.0` feature allows the runtime to create and consume JSON Web Token(JWT) tokens.


To obtain JWT from the JWT token generation endpoint in the `jwt-1.0` feature:

- Authenticate with your credentials to access the JWT token generation endpoint at the following URL:

`https://<host>:<port>/jwt/ibm/api/<configId>/token`

After authentication succeeds, the MP-JWT format token is returned in JSON form.
The token contains the user ID and any groups to which the user belongs, as recorded in the user registry of the server.

- Use the `<configId>` ID to refer to a corresponding JWTBuilder entry in the `server.xml` file.
Specify token attributes, such as issuer and expiration time, in the JWTBuilder entry.
- If you do not define JWTBuilder elements in the `server.xml` file, use the `defaultJWT` element as the `<configId>` ID.
- For JWT builder configuration attributes, see link:https://www.openliberty.io/docs/ref/config/#jwtBuilder.html[JWT Builder]
- JWT builders and consumers can also be constructed programatically. Within a liberty installation, the api documentation can be found at `/dev/api/ibm/javadoc/com.ibm.websphere.appserver.api.jwt_1.1-javadoc.zip`
