== Examples

The following example shows how to configure the server to construct a JWT token for the application:

[source, xml]
----
<keyStore id="defaultKeyStore" password="keyspass"/>

    <googleLogin clientId="your_client_id_from_Google_goes_here"
        clientSecret="your_client_secret_from_Google_goes_here"/>

    <jwtBuilder expiresInSeconds="600" id="myBuilder" issuer="https://example.com" keyAlias="default"/>

----

To obtain JWT from the JWT token generation endpoint in the `jwt-1.0` feature:

- Authenticate with your credentials to access the JWT token generation endpoint at the following URL:

`https://<host>:<port>/jwt/ibm/api/<configId>/token`

After authentication succeeds, the MP-JWT format token is returned in JSON form.
The token contains the user ID and any groups to which the user belongs, as recorded in the user registry of the server.

- Use the `<configId>` ID to refer to a corresponding JWTBuilder entry in the `server.xml` file.
Specify token attributes, such as issuer and expiration time, in the JWTBuilder entry.
- If you do not define JWTBuilder elements in the `server.xml` file, use the `defaultJWT` element as the `<configId>` ID.
- For JWT builder configuration attributes, see link:https://www.openliberty.io/docs/ref/config/#jwtBuilder.html[JWT Builder].
- JWT builders and consumers can also be constructed programmatically. Within a Open Liberty installation, the API documentation can be found at `/dev/api/ibm/javadoc/com.ibm.websphere.appserver.api.jwt_1.1-javadoc.zip`
