// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
// https://creativecommons.org/licenses/by-nd/4.0/
//
//
// Contributors:
// IBM Corporation
//
//
//
//
:page-description: The names and version numbers of some of the Open Liberty features that support the Jakarta EE platform are updated for the Jakarta EE 9.1 release. In some cases, you must change both the feature version and short name in your server configuration to update your server for Jakarta EE 9.1.
:projectName: Open Liberty
:page-layout: Jakarta EE 9
:page-type: feature updates
= Jakarta EE 9.1 feature updates

The names and version numbers of some of the Open Liberty features that support the Jakarta EE platform are updated for the Jakarta EE 9.1 release.
In some cases, you must change both the feature version and short name in your server configuration to update your server for Jakarta EE 9.1.

As part of the transition from Java EE to the open source Jakarta EE platform, the namespace of the underlying API packages changed from `javax` to `jakarta`. The Open Liberty features that support the Jakarta EE platform are also updated to reflect this change with the release of Open Liberty 21.0.0.12. For some Jakarta EE features, only the version number is changed. For others, both the feature version and short name are changed. If you are updating your server to Jakarta EE 9.1, you must specify the updated feature versions and short names in your `server.xml` file.

For example, the Contexts and Dependency Injection feature is updated from `cdi-2.0` to `cdi-3.0`. To update this feature for Jakarta EE 9.1, you need to update only the version number. However, in some cases, the feature short name is also changed, as with the Enterprise JavaBeans 3.2 feature (`ejb-3.2`), which was updated to Enterprise Beans 4.0 (`enterpriseBeans-4.0`). To update this feature, you must specify both the new version number and the new short name.

In the following `server.xml` file example, three Java EE features are specified.

[source,xml]
----
<server>
  <featureManager>
    <feature>servlet-4.0</feature>
    <feature>jpa-2.2</feature>
    <feature>jaxrs-2.1</feature>
  </featureManager>
</server>
----

To update this configuration to support Jakarta EE 9.1, you must specify the updated feature versions and short names. For the `servlet-4.0` feature, only the version number is changed. However, both the other features have updated version numbers and short names. The `jpa-2.2` feature becomes `persistence-3.0` and the `jaxrs-2.1` becomes `restfulWS-3.0`. The following example shows the updated configuration for Jakarta EE 9.1.

[source,xml]
----
<server>
  <featureManager>
    <feature>servlet-5.0</feature>
    <feature>persistence-3.0</feature>
    <feature>restfulWS-3.0</feature>
  </featureManager>
</server>
----

For features with updated short names, if the old short name is specified with a Jakarta EE 9.1 version number, the server does not start. In such cases, the server logs provide information to indicate which new feature short name must be specified.
For example, if `ejb-3.2` is incorrectly changed to `ejb-4.0`, the server logs indicate that `enterpriseBeans-4.0` must be used.

Open Liberty provides several convenience features, which can enable a whole set of features all at once. For example, the feature:jakartaee[display=Jakarta EE platform] feature enables all features that support the Jakarta EE platform. If you update this feature from the previous short name and version number, `javaee-8.0`, to `jakartaee-9.1`, all of the Jakarta EE 9.1 features are automatically enabled. For more information, see xref:reference:feature/feature-overview.adoc[Feature overview].

== Changes to feature short names and version numbers for Jakarta EE 9.1
These tables list the Open Liberty features that are updated for Jakarta EE 9.1. Table 1 lists the features for which only the version number is changed. Table 2 lists the features for which both the version number and short name are changed.

The following table lists features for which only the feature version is changed. To update one of these features for Jakarta EE 9.1, you must change only the feature version number in your `server.xml` file.

.Table 1: Jakarta EE 9.1 feature updates, version only
|===
| Feature name | Java EE/Jakarta EE 8 feature name | Jakarta EE 9.1 feature name

| Application Client Support for Server
| feature:appClientSupport-1.0[]
| feature:appClientSupport-2.0[]

| Application Security
| feature:appSecurity-3.0[]
| feature:appSecurity-4.0[]

| Batch API
| feature:batch-1.0[]
| feature:batch-2.0[]

| Bean Validation
| feature:beanValidation-2.0[]
| feature:beanValidation-3.0[]

| Contexts and Dependency Injection
| feature:cdi-2.0[]
| feature:cdi-3.0[]

| Concurrency Utilities
| feature:concurrent-1.0[]
| feature:concurrent-2.0[]

| Jakarta EE
| feature:jakartaee-8.0[]
| feature:jakartaee-9.1[]

| JavaScript Object Notation Binding
| feature:jsonb-1.0[]
| feature:jsonb-2.0[]

| JavaScript Object Notation Binding Container
| feature:jsonbContainer-1.0[]
| feature:jsonbContainer-2.0[]

| JavaScript Object Notation Processing
| feature:jsonp-1.1[]
| feature:jsonp-2.0[]

| JavaScript Object Notation Processing Container
| feature:jsonpContainer-1.1[]
| feature:jsonpContainer-2.0[]

| Java EE Managed Bean
| feature:managedBeans-1.0[]
| feature:managedBeans-2.0[]

| Message-Driven Beans
| feature:mdb-3.2[]
| feature:mdb-4.0[]

| Java Servlet
| feature:servlet-4.0[]
| feature:servlet-5.0[]

| Java EE Web Profile
| feature:webProfile-8.0[]
| feature:webProfile-9.1[]

| Java WebSocket
| feature:websocket-1.1[]
| feature:websocket-2.0[]
|===


The following table lists the features for which both the short name and the version number are changed. To update one of these features for Jakarta EE 9.1, you must change both the feature short name and version number in your `server.xml` file.

.Table 2: Jakarta EE 9.1 feature updates, short name and version
|===
|Jakarta EE 9.1 feature name | Java EE/Jakarta EE 8 short name and version | Jakarta EE 9.1 short name and version

| Jakarta Enterprise Beans
| feature:ejb-3.2[]
| feature:enterpriseBeans-4.0[]

| Jakarta Enterprise Beans Home Interfaces
| feature:ejbHome-3.2[]
| feature:enterpriseBeansHome-4.0[]

| Jakarta Enterprise Beans Lite
| feature:ejbLite-3.2[]
| feature:enterpriseBeansLite-4.0[]

| Jakarta Enterprise Beans Persistent Timers
| feature:ejbPersistentTimer-3.2[]
| feature:enterpriseBeansPersistentTimer-4.0[]

| Jakarta Enterprise Beans Remote
| feature:ejbRemote-3.2[]
| feature:enterpriseBeansRemote-4.0[]

| Jakarta Expression Language
| feature:el-3.0[]
| feature:expressionLanguage-4.0[]

| Jakarta Authorization
| feature:jacc-1.5[]
| feature:appAuthorization-2.0[]

| Jakarta Authentication
| feature:jaspic-1.1[]
| feature:appAuthentication-2.0[]

| Jakarta EE Platform
| feature:javaee-8.0[]
| feature:jakartaee-9.1[]

| Jakarta EE Application Client
| feature:javaeeClient-8.0[]
| feature:jakartaeeClient-9.1[]

| Jakarta Mail
| feature:javaMail-1.6[]
| feature:mail-2.0[]

| Jakarta XML Binding
| feature:jaxb-2.2[]
| feature:xmlBinding-3.0[]

| Jakarta RESTful Web Services
| feature:jaxrs-2.1[]
| feature:restfulWS-3.0[]

| Jakarta RESTful Web Services Client
| feature:jaxrsClient-2.1[]
| feature:restfulWSClient-3.0[]

| Jakarta XML Web Services
| feature:jaxws-2.2[]
| feature:xmlWS-3.0[]

| Jakarta Connectors
| feature:jca-1.7[]
| feature:connectors-2.0[]

| Jakarta Connectors Inbound Security
| feature:jcaInboundSecurity-1.0[]
| feature:connectorsInboundSecurity-2.0[]

| Jakarta Messaging
| feature:jms-2.0[]
| feature:messaging-3.0[]

| Jakarta Persistence
| feature:jpa-2.2[]
| feature:persistence-3.0[]

| Jakarta Persistence Container
| feature:jpaContainer-2.2[]
| feature:persistenceContainer-3.0[]

| Jakarta Server Faces
| feature:jsf-2.3[]
| feature:faces-3.0[]

| Jakarta Server Faces Container
| feature:jsfContainer-2.3[]
| feature:facesContainer-3.0[]

| Jakarta Server Pages
| feature:jsp-2.3[]
| feature:pages-3.0[]

| Messaging Server Client
| feature:wasJmsClient-2.0[]
| feature:messagingClient-3.0[]

| Messaging Server Security
| feature:wasJmsSecurity-1.0[]
| feature:messagingSecurity-3.0[]

| Messaging Server
| feature:wasJmsServer-1.0[]
| feature:messagingServer-3.0[]
|===

The link:https://github.com/eclipse/transformer[Eclipse Transformer] can help with moving your applications from Java EE and its `javax` namespace to Jakarta EE and its `jakarta` namespace. This tool is an open source project that was originally developed by members of the Open Liberty team and then contributed to the Eclipse Foundation.

== See also

* xref:ROOT:jakarta-ee.adoc[Jakarta EE overview]
* xref:diff/jakarta-ee10-diff.adoc[Differences between Jakarta EE 10 and 9.1]
* xref:diff/jakarta-ee-diff.adoc[Differences between Jakarta EE 9.1 and 8]
* xref:java-ee-api.html[Java EE API]
* xref:jakarta-ee-api.html[Jakarta EE API]
