// Copyright (c) 2023 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
// https://creativecommons.org/licenses/by-nd/4.0/
//
//
// Contributors:
// IBM Corporation
//
//
//
//
:page-description: If you are updating your application from using Jakarta EE 10 features to using Jakarta EE 11 features, certain changes in API behavior might require you to update your application code.
:projectName: Open Liberty
:page-layout: general-reference
:page-type: general
= Differences between Jakarta EE 11 and 10

If you are updating your application from using Jakarta EE 9.1 features to using Jakarta EE 10 features, changes in API behavior might require you to update your application code. These changes apply to several Jakarta EE APIs and the Open Liberty features that support them.

The following sections describe updates for different Jakarta EE 10 features

* <<global, Global differences between Jakarta EE 11 and 10>>
* <<persist,Jakarta Persistence 3.2>>
* <<express,Jakarta Expression Language 6.0>>
* <<faces,Jakarta Server Faces 4.1>>
* <<pages,Jakarta Server Pages 4.0>>
* <<websocket,Jakarta WebSocket 2.2>>
* <<servlet,Jakarta Servlet 6.1>>







[#global]
== Global differences between Jakarta EE 11 and 10

The following changes apply across the Jakarta EE 11 platform.

Content to be added here....

[#persist]
== Differences between Jakarta Persistence 3.2 and 3.1


The feature:persistence-3.2[display=Jakarta Persistence 3.2] feature (`persistence-3.2`) introduces updates that include modifications to the `EclipseLink` packages and adjustments to how certain Java types, such as Instant, are mapped in databases.

The following changes are introduced in Jakarta Persistence 3.2:

=== Package updates in EclipseLink

- The `SessionCustomizer` package is moved from `org.eclipse.persistence.config` to `org.eclipse.persistence.sessions`

- The `DescriptorCustomizer` package is moved from `org.eclipse.persistence.config` to `org.eclipse.persistence.descriptors`

- The `CacheIsolationType` package is moved from `org.eclipse.persistence.config` to `org.eclipse.persistence.annotations`

- The `PropertiesUtils` package is moved from `org.eclipse.persistence.config` to `org.eclipse.persistence.internal.helper`



=== Mapping change for Instant type

EclipseLink changed the default mapping of the `Instant` type from `BLOB` to `TIMESTAMP`. You must either regenerate the DDL files to align with the new type or override the mapping to preserve the previous behavior.


[#express]
== Differences between Jakarta Expression Language 6.0 and 5.0

The feature:expressionLanguage-6.0[display=Jakarta Expression Language 6.0] feature (`expressionLanguage-6.0`) introduces updates to the ELResolver capabilities by supporting additional Java types and aligning with newer JDK versions.


=== Key changes in Jakarta Expression Language 6.0

=== New additions

- Support for `java.lang.Record`, introduced in Java 17, is added through the new `jakarta.el.RecordELResolver` class. This support is enabled by default.

- Support for `java.lang.Optional`, introduced in Java 8, is added through the new `jakarta.el.OptionalELResolver` class. This support is available but NOT enabled by default.

- Arrays now support the `length` property through the official API.However, Open Liberty uses Tomcat’s Expression Language implementation, which has supported the `length` property for many years.

=== Removals

- The `getFeatureDescriptors` method is removed from the `jakarta.el.ELResolver` class.

- All references to `SecurityManager` are removed from within the API to align with the deprecation of SecurityManager in newer JDKs.



[#faces]
== Differences between Jakarta Server Faces 4.1 and 4.0

The feature:faces-4.1[display=Jakarta Faces 4.1] feature (`faces-4.1`) introduces general improvements, new convenience methods, and deprecations that are aimed at streamlining the API and aligning with recent platform changes.

=== Key changes in Jakarta Server Faces 4.1

=== New additions

- CDI lifecycle events like `@Initialized`, `@BeforeDestroyed`, and `@Destroyed` will now work for built-in scopes such as `@ViewScoped` and `@FlowScoped`.

-  You can now inject the Flow objects into backing beans using the `@Inject Flow currentFlow`.

- A new built-in `jakarta.faces.convert.UUIDConverter` UUID converter is now available through the API.

- The `setResponseContentLengthLong()` method is added to `jakarta.faces.context.ExternalContext` to support large response content lengths.

- The `rowStatePreserved` property is now supported by the `ui:repeat` tag, similar to how it works in `h:dataTable`.

- The default value of `jakarta.faces.FACELETS_REFRESH_PERIOD` is updated when `ProjectStage` is set to `Development`.

- The `jakarta.faces.application.FacesMessage` class now includes `equals()`, `hashCode()`, and `toString()` methods, which helps allow `FacesMessages` to be stored within `HashMaps`.

- More parts of the API now support generics, making the code easier to work with and safer at compile time.

=== Removals

The following items have been deprecated:

- Full State Saving (FSS) is deprecated. This was previously enabled through either `jakarta.faces.PARTIAL_STATE_SAVING` or `jakarta.faces.FULL_STATE_SAVING_VIEW_ID` settings.

- The classes `jakarta.faces.event.PreDestroyCustomScopeEvent` and `jakarta.faces.event.PostConstructCustomScopeEvent` are deprecated. These were overlooked during the removal of `@CustomScoped` in Faces 4.0.

- The `composite:extension` tag, which was never implemented, has been deprecated.

- All references to SecurityManager have been removed to align with recent Java platform changes.


[#pages]
== Differences between Jakarta Pages 4.0 and 3.1


Content to be added here....


[#websocket]
== Differences between Jakarta WebSocket 2.2 and 2.1


Content to be added here....



[#servlet]
== Differences between Jakarta Servlet 6.1 and 6.0


Content to be added here....












== See also

* xref:ROOT:jakarta-ee.adoc[Jakarta EE overview]
* xref:diff/jakarta-ee10-diff.adoc[Differences between Jakarta EE 10 and 9.1]
* xref:diff/jakarta-ee-diff.adoc[Differences between Jakarta EE 9.1 and 8.0]