// Copyright (c) 2023 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
// https://creativecommons.org/licenses/by-nd/4.0/
//
//
// Contributors:
// IBM Corporation
//
//
//
//
:page-description: MicroProfile 6.1 is a minor release. If you are updating your application from using MicroProfile 6.0 features to using MicroProfile 6.1 features, changes in API behavior might require you to update your application code.
:projectName: Open Liberty
:page-layout: general-reference
:page-type: general
= Differences between MicroProfile 6.1 and 6.0

MicroProfile 6.1 is a minor release. It includes Jakarta EE 10 Core Profile and replaces MicroProfile OpenTracing with MicroProfile Telemetry.

Therefore, MicroProfile OpenTracing moves out of the umbrella release and becomes a stand-alone specification. For more information about Jakarta EE 10 Core Profile, see the link:https://jakarta.ee/specifications/coreprofile/10/[Core Profile specification].

If you are updating your application from using MicroProfile 6.0 features to using link:https://github.com/eclipse/microprofile/releases/tag/6.1[MicroProfile 6.1] features, changes in API behavior might require you to update your application code. The following sections provide details about migrating your applications from MicroProfile 6.0 to 6.1:

- <<#metrics, Differences between MicroProfile Metrics 5.0 and 5.1>>
- <<#telemetry, Differences between MicroProfile Telemetry 1.0 and 1.1>>

[#metrics]
== Differences between MicroProfile Metrics 5.0 and 5.1

The MicroProfile Metrics 5.1 release introduces many changes to the specification and programming model that impact users who are migrating from MicroProfile Metrics 5.0.

[#telemetry]
== Differences between MicroProfile Telemetry 1.0 and 1.1

MicroProfile Telemetry 1.1 provides developers with the latest Open Telemetry technology; the feature now consumes OpenTelemetry-1.29.0, updated from 1.19.0. Consequently, a lot of the dependencies are now stable. The feature is compatible with Java EE 7 with MicroProfile 1.4, Java EE 8 with MicroProfile 4.1, Jakarta EE 9 with MicroProfile 5.0 and Jakarta EE 10 with MicroProfile 6.1. 

