// Copyright (c) 2024 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
// https://creativecommons.org/licenses/by-nd/4.0/
//
//
// Contributors:
// IBM Corporation
//
//
//
//
:page-description: MicroProfile 7.1 is a minor release. If you are updating your application from using MicroProfile 7.0 features to using MicroProfile 7.1 features, changes in API behavior might require you to update your application code.
:projectName: Open Liberty
:page-layout: general-reference
:page-type: general


= Differences between MicroProfile 7.1 and 7.0

MicroProfile 7.1 is a minor release. It includes minor changes for the MicroProfile OpenAPI 4.1 and Telemetry 2.1 features.

If you are updating your application from using MicroProfile 7.0 features to using link:https://github.com/eclipse/microprofile/releases/tag/7.1[MicroProfile 7.1] features, changes in API behavior might require you to update your application code. The following sections provide details about migrating your applications from MicroProfile 7.0 to 7.1:

- <<#openapi, Differences between MicroProfile OpenAPI 4.1 and 4.0>>
- <<#telemetry, Differences between MicroProfile Telemetry 2.1 and 1.1>>

[#openapi]
== Differences between MicroProfile OpenAPI 4.1 and 4.0
feature:mpOpenAPI-4.1[display=MicroProfile OpenAPI 4.1] adds the `getJsonSchemaDialect()` method and the `setJsonSchemaDialect()` method to set the default `jsonSchemaDialect` field by using the model API. 
MicroProfile OpenAPI 4.1 also adds the `getExtension()` method and the `hasExtension()` method to the `Extensible` model class. 

[#telemetry]
== Differences between MicroProfile Telemetry 2.1 and 1.1
feature:mpTelemetry-2.1[display=MicroProfile Telemetry 2.1] equips you with the most recent Open Telemetry technology. This feature now uses OpenTelemetry-1.48.0, upgraded from 1.39.0. 
You no longer have to add the following configuration to the `server.xml` to use the OpenTelemetry API:
----
<webApplication id="app-name" location="app-name.war">
    <classloader apiTypeVisibility="+third-party"/>
</webApplication>
----