// INSTRUCTION: Please remove all comments that start INSTRUCTION prior to commit. Most comments should be removed, although not the copyright.
// INSTRUCTION: The copyright statement must appear at the top of the file
//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//

= Java support in Open Liberty
// Choose a title that a developer would search for, given the subject of the article.
// PAs of Liberty 18.0.0.4, you can use any version or distribution of Java SE 11.

Java SE 8 and Java SE 11 are supported in Open Liberty. You can use any version or distribution of these versions. Because of changes in the Java SE platform that have occurred, zero-migration is not guaranteed.

== Java SE 8

For the Java SDK from IBM, the minimum supported level is IBM SDK, Java Technology Edition, Version 8. For the JDK from Oracle, the minimum supported level is Java 8 update 25.

On distributed platforms, 32-bit or 64-bit Java is supported. 

For Windows and Linux systems, you can use either the JDK from Oracle or the Java SDK from IBM. If you are developing applications on Windows or Linux, and you plan to deploy those applications to a server that is running on WebSphere Application Server traditional, use the Java SDK from IBM. For HP systems and Mac OS, use the JDK from Oracle. 

== Java SE 11

There are several Java 11 changes that impact Open Liberty. Between Java 8 and Java 11, several good enhancements such as local variables and the Flow API have been provided. However, there are also a few changes that are likely to cause problems for existing applications.

In Java 11, several modules (groupings of Java packages) were removed from JDK. With the removal of Java EE and CORBA APIs from the JDK, it is important to note that your applications may have been relying on some these removed packages. However, all of the removed packages are already provided by existing Open Liberty features.

The introduction of JPMS (Java Platform Module System) in Java 9 raised a major compatibility issue for most of the Java ecosystem due to restrictions affecting access between different Java modules. In Java 11, a "kill switch" (formally known as the --illegal-access=permit JVM option) has been introduced. It is enabled by default and allows code in unnamed modules to access and perform deep reflection on all named modules. It is important to note that eventually the kill switch will not be enabled by default, and later it will be removed entirely, so it is best to stop writing code that uses deep reflection and start migrating to alternative approaches.


== See also

* link:server-package.html[server package]

What guide can we link to?
