// INSTRUCTION: Please remove all comments that start INSTRUCTION prior to commit. Most comments should be removed, although not the copyright.
// INSTRUCTION: The copyright statement must appear at the top of the file
//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//

= Java 11 support
// Choose a title that a developer would search for, given the subject of the article.
// PAs of Liberty 18.0.0.4, you can use any version or distribution of Java SE 11.

You can use any version or distribution of Java SE 11. However, significant changes in the Java SE platform have occurred. Therefore, zero-migration is not guaranteed.


== What changed from Java SE 8?

Let's highlight some of the significant changes such as, incompatible Java changes.

*Incompatible Java changes*
Several JVM packages have moved. Historically, new Java SE versions have made few incompatible changes to the language, this changed with Java SE 9. The Liberty runtime will attempt to minimize the impact of these breaking changes on applications, however this may not always be possible.”

== Restrictions

`ssl-1.0 and transportSecurity-1.0`

For the ssl-1.0 and transportSecurity-1.0 features, the following restrictions apply:

Java SE 11 introduced a new TLS protocol version, TLSv1.3. This new protocol version is not backwards compatible with existing Liberty features.
So, this feature is globally disabled until changes to JavaSE code, Liberty code, or both are made to accommodate the use of TLSv1.3.


== Usage

This is where we can document that you start the JVM with the kill switch enabled.


== See also

* link:server-package.html[server package]

What guide can we link to?
