
== Examples

=== Monitoring with MicroProfile metrics configuration
The MicroProfile metrics feature can be used to monitor applications that are instrumented with the MicroProfile metrics API. The MicroProfile metrics API is a REST API that displays metrics for administrators to access. You can use the MicroProfile metrics feature to secure the REST API with authentication. The following example shows a basic security configuration for the REST API:
[source,xml]
----
<quickStartSecurity userName="theUser" userPassword="thePassword"/>
<keyStore id="defaultKeyStore" password="Liberty"/>
----

The MicroProfile metrics feature uses the default keystore to secure the endpoint.

=== MicroProfile metrics API authorization
Application developers can add their own custom metrics by using the MicroProfile metrics API alongside the metrics provided by Open Liberty. To allow a user or group of users to access the MicroProfile metrics API, you can map the `administrator` to the user or group from the configured user registry. The metrics API is protected by the Open Liberty `administrator` role. The following example shows a configuration to enable a user in the configured user registry and `AuthorizedGroup` to access the API:
[source,xml]
----
<basicRegistry id="basic" realm="WebRealm">
    <user name="bob" password="bobpwd" />
    <user name="alice" password="alicepwd" />
    <user name="carl" password="carlpwd" />

    <group name="AuthorizedGroup">
        <member name="alice" />
    </group>
</basicRegistry>

 <administrator-role>
     <user>bob</user>
     <group>AuthorizedGroup</group>
 </administrator-role>
----

=== REST endpoints
