
== Examples

=== Monitoring with MicroProfile metrics configuration
The MicroProfile metrics feature can be used to monitor applications that are instrumented with the MicroProfile metrics API. The MicroProfile metrics API is a REST API that displays metrics for administrators to access. You can use the MicroProfile metrics feature to secure the REST API with authentication. The following example shows a basic security configuration for the REST API:
[source,xml]
----
<quickStartSecurity userName="theUser" userPassword="thePassword"/>
<keyStore id="defaultKeyStore" password="Liberty"/>
----

The MicroProfile metrics feature uses the default keystore to secure the `/metrics` REST endpoint.

==== Securing the `/metrics` REST endpoint
The `/metrics` endpoint reveals all of the service metrics from the location where the application runs. These metrics can identify vital data within the application, such as the details of user requests, that could be exposed to unauthorized users if it is not properly secured. The following example shows how to secure the `/metrics` endpoint:

=== MicroProfile metrics API authorization
Application developers can add their own custom metrics by using the MicroProfile metrics API alongside the metrics provided by Open Liberty. Access to the MicroProfile metrics API can be provided through either a configured user registry or a specified SSO method such as JSON Web Token (JWT) by configuring the `administrator` role. With Open Liberty, you can map the `administrator` role to users so that they can access the MicroProfile metrics API. The MicroProfile metrics API is protected by the `administrator role` so users that are not mapped to the administrator role are not able to access the API.


==== Authorizing access to the metrics API with a basic user registry
To allow a user or group of users to access the MicroProfile metrics API, you can map the `administrator` to the user or group from the configured user registry. The metrics API is protected by the Open Liberty `administrator` role. The following example shows a configuration to enable a user in the configured user registry and `AuthorizedGroup` to access the API:
[source,xml]
----
<basicRegistry id="basic" realm="WebRealm">
    <user name="bob" password="bobpwd" />
    <user name="alice" password="alicepwd" />
    <user name="carl" password="carlpwd" />

    <group name="AuthorizedGroup">
        <member name="alice" />
    </group>
</basicRegistry>

 <administrator-role>
     <user>bob</user>
     <group>AuthorizedGroup</group>
 </administrator-role>
----

==== Authorizing access to the metrics API with SSO
