
== Examples

=== MicroProfile Metrics configuration
The MicroProfile Metrics feature can be used to monitor applications that are instrumented with the MicroProfile Metrics API. The MicroProfile Metrics API is a REST API that displays metrics for administrators to access. You can configure the MicroProfile Metrics feature to require authentication and authorization to access the `/metrics` endpoint. The following example shows a basic security configuration for the REST API:
[source,xml]
----
<quickStartSecurity userName="theUser" userPassword="thePassword"/>
<keyStore id="defaultKeyStore" password="Liberty"/>
----

By default, the MicroProfile metrics feature uses the default keystore to secure the `/metrics` REST endpoint.

=== Authorizing access to the metrics API with a basic user registry
The `/metrics` endpoint is used to access the metrics stored in the server. The metrics can include both information about server components, such as connection pools, and information that applications have chosen to create metrics for. In some cases, you may want to limit access to this data. To allow a user or group of users to access the MicroProfile Metrics API, you can map the `administrator` role to the user or group from the configured user registry. The MicroProfile Metrics API is protected by the Open Liberty `administrator` role. The following example shows a configuration to enable a user in the configured user registry and `AuthorizedGroup` to access the API:
[source,xml]
----
<basicRegistry id="basic" realm="WebRealm">
    <user name="bob" password="bobpwd" />
    <user name="alice" password="alicepwd" />
    <user name="carl" password="carlpwd" />

    <group name="AuthorizedGroup">
        <member name="alice" />
    </group>
</basicRegistry>

 <administrator-role>
     <user>bob</user>
     <group>AuthorizedGroup</group>
 </administrator-role>
----

=== Authorizing access to the metrics API with SSO
When you enable an SSO method, such as JWT, you can map the `administrator` role to the `user` or `group access-id` to authorize access to the MicroProfile metrics API. The following example shows the configuration to access the API when a SSO method is enabled. The `user-access-id` and `group-access-id` elements specify the realm that the authorized user or group belongs to.  The user `bob` and the `ManagedGroup` group both belong to the `https://idp.example.com` realm that is authorized to access the API:
[source,xml]
----
<administrator-role>
    <user-access-id>user:https://idp.example.com/bob</user-access-id>
    <group-access-id>group:https://idp.example.com/ManagingGroup</group-access-id>
</administrator-role>
----

=== Disabling metrics security
Although the default configuration for the MicroProfile Metrics feature is to secure the REST API, it is possible to disable metrics security. With secured authentication disabled, the metrics REST endpoint is not restricted only to HTTP, but is still accessible through the HTTPS protocol. The following example shows a MicroProfile Metrics configuration with security disabled:
[source,xml]
----
<mpMetrics authentication="false"/>
----
