== Examples

=== Minimum configuration

The acmeCA feature requires configuration. The minimum configuration requires the URL of a Certificate Authority (CA) provider and the name of one or more domains, as shown in the following example:

[source,xml]
----
<acmeCA directoryURI="https://acme.host.com/directory" >
    <domain>mtcrumpit.com</domain>
</acmeCA>
----

=== Provide an account contact

You can provide an account contact as part of your ACME CA feature configuration. This contact is important for cases where your CA needs to contact you, for example, to get approval for terms of service updates. If a CA modifies its terms of service, it might require you to agree to the new terms of service manually. If you specify a monitored email address in your feature configuration, the ACME CA server can warn you about new terms of service so that you can agree to them and avoid service disruption. Whenever you update your contact information in the feature configuration, the ACME service updates your account on the ACME CA server.

To provide an account contact, specify a monitored email address in the `accountContact` element, as shown in the following example:

[source,xml]
----
<acmeCA ...>
    <accountContact>mailto:thegrinch@mtcrumpit.com</accountContact>
</acmeCA ...>
----

If you do not provide an email address for your account, you won't be notified about upcoming certificate expirations or terms of service changes, which might result in loss of account access. Open Liberty issues a warning if an email address is not provided in the configuration.


=== Renew expiring or revoked certificates

You can configure the amount of time before a certificate expires that the ACME CA feature renews the certificate by specifying a value for the `renewBeforeExpiration` property, as shown in the following example:

----
<acmeCA ...>
    <renewBeforeExpiration>mailto:thegrinch@mtcrumpit.com</renewBeforeExpiration>
</acmeCA ...>
