== Examples

=== Default configuration

Open Liberty provides a default `defaultSP` service provider instance.
SAML Web Single Sign-On is configured by default in Open Liberty.
The SAML Web Single Sign-on feature activates the following two endpoints:

- AssertionConsumerService URL:
+
`https://<hostname>:<sslport>/ibm/saml20/defaultSP/acs`
+
The AssertionConsumerService URL endpoint on the service provider point of contact server receives assertions from the identity provider.

- Service Provider (SP) metadata URL:
+
`https://<hostname>:<sslport>/ibm/saml20/defaultSP/samlmetadata`
+
You can use a browser to download the metadata for this service provider by using this URL.
Then, provide the URL to the SAML identity provider to establish federation between this SP and Identity Provider.

=== Custom configuration

If you want to create a new service provider instance, and the default service provider instance is not longer needed, add the following code to the `server.xml` file:

[source, xml]
----
<samlWebSso20 id="defaultSP" enabled="false"/>
----

In the example, the `defaultSP` service provider instance is disabled by setting the `enabled` parameter to `false`.
