== Examples

=== Default configuration

Open Liberty provides a default `samlWebSso20` element.
This default configuration of the feature activates the following endpoints:

- The AssertionConsumerService URL is the endpoint on the service provider point of contact server that receives assertions.
+
`https://<hostname>:<sslport>/ibm/saml20/defaultSP/acs`

- Service Provider (SP) metadata URL is used to provide configuration information for the  service provider
+
`https://<hostname>:<sslport>/ibm/saml20/defaultSP/samlmetadata`

The preferred approach to configure SAML is to supply the metadata URL to the Identity Provider (IdP).
You can use a browser to download the metadata for this SP from this URL. Provide the URL to the SAML IdP to establish federation between this SP and IdP.

=== Custom configuration of the SAML web SSO

In most cases, exchange of the metadata files is sufficient for verification.
You can specify additional attributes if necessary.
For more information, see the feature configuration elements.
If you create a new service provider instance and the `defaultSP` instance is no longer required, then you must disable the `defaultSP` instance.
You can disable the `defaultSP` instance by adding the following code to the `server.xml` file:

[source, xml]
----
<samlWebSso20 id="defaultSP" enabled="false"/>

<samlWebSso20 id="newSP" allowCustomCacheKey="false"/>
----
