== Examples

=== Default configuration

Open Liberty provides a default `samlWebSso20` element.
This default configuration of the feature activates the following endpoints:

- AssertionConsumerService URL:
AssertionConsumerService URL (used by the provider to communicate with the server)

`https://<hostname>:<sslport>/ibm/saml20/defaultSP/acs`

- Service Provider (SP) metadata URL:(used to provide configuration information for the provider)

`https://<hostname>:<sslport>/ibm/saml20/defaultSP/samlmetadata`

The preferred approach to configure SAML is to supply the metadata URL to the identity provider (IdP).
You can use a browser to download the metadata for this SP by using this URL and provide the URL to the SAML IdP to establish federation between this SP and IdP.

=== Custom configuration

In most cases, exchange of the metadata files is sufficient.
Additional attribute can be specified if necessary.
If you create a new service provider instance and the `defaultSP` instance is no longer required, then you must disable the `defaultSP` instance.
You can disable the `defaultSP` instance by adding the following code to the `server.xml` file:

[source, xml]
----
<samlWebSso20 id="defaultSP" enabled="false"/>

<samlWebSso20 id="newSP" allowCustomCacheKey="false"/>
----
