== Examples

=== Default configuration

Open Liberty provides a default `samlWebSso20` element.
This default configuration of the feature activates the following endpoints:

- AssertionConsumerService URL:
AssertionConsumerService URL (used by the provider to communicate with the server)

`https://<hostname>:<sslport>/ibm/saml20/defaultSP/acs`

- Service Provider (SP) metadata URL:(used to provide configuration information for the provider)

`https://<hostname>:<sslport>/ibm/saml20/defaultSP/samlmetadata`

The preferred approach to configure SAML is to supply the metadata url to the identity provider (IdP).
If the IdP requires a file instead of a URL, use a browser to retrieve the data from that URL and supply the file.
Next, obtain the metadata file from the provider, rename it to `idpMetadata.xml`, and copy it to the `resources/security` directory on the server.

=== Custom configuration

In most cases, exchange of the metadata files is sufficient.
Additional attribute can be specified if necessary.
If you create a new service provider instance and the `defaultSP` instance is no longer required, then you must explicitly disable the `defaultSP` instance.
You can disable the `defaultSP` instance by adding the following code to the `server.xml` file:

[source, xml]
----
<samlWebSso20 id="defaultSP" enabled="false"/>

<samlWebSso20 id="newSP" allowCustomCacheKey="false"/>
----
