== Examples

=== Default configuration

You can enable the SAML Web Single Sign-on feature, to configure it automatically and activate two endpoints:

- `https://<hostname>:<sslport>/ibm/saml20/defaultSP/acs`
+
The AssertionConsumerService URL endpoint on the service provider point of contact server receives assertions.

- `https://<hostname>:<sslport>/ibm/saml20/defaultSP/samlmetadata`
+
The Service Provider metadata URL provides configuration information for the service provider.
You can use a browser to download the metadata for the service provider with this URL.
Further, you can provide the URL to the SAML identity provider to a establish federation between this Service Provider and Identity Provider.

=== Custom configuration

You can disable the default service provider instance when you add the following code to the `server.xml` file:

[source, xml]
----
<samlWebSso20 id="defaultSP" enabled="false"/>

<samlWebSso20 id="newSP" allowCustomCacheKey="false"/>
----

Thus, you can disable the default `defaultSP` service provider instance, and configure the new `newSP` service provider instance.
