== Examples

=== Default configuration

When you enable the SAML Web Single Sign-on feature, it is automatically configured and activates two endpoints:

- `https://<hostname>:<sslport>/ibm/saml20/defaultSP/acs`
+
The AssertionConsumerService URL is the endpoint on the service provider point of contact server that receives assertions.

- `https://<hostname>:<sslport>/ibm/saml20/defaultSP/samlmetadata`
+
Service Provider (SP) metadata URL is used to provide configuration information for the  service provider.
You can use a browser to download the metadata for this service provider by using this URL.
Further, you can provide it to the SAML identity provider to establish federation between this Service Provider and Identity Provider.

=== Custom configuration

You can disable the default service provider instance by adding the following code to the `server.xml` file:

[source, xml]
----
<samlWebSso20 id="defaultSP" enabled="false"/>

<samlWebSso20 id="newSP" allowCustomCacheKey="false"/>
----

The default service provider instance, `defaultSP`, is disabled and the new service provider instance, `newSP`, is configured.
