== Examples

=== Configure a BELL

The minimum `server.xml` configuration for the BELL feature requires a `library` element and a `bell` element that references the library.

[source,xml,subs="verbatim,quotes"]
----
<library id="servicesLib">
  <file name="_path to jar_">
</library>

<bell libraryRef="servicesLib" />
----

For any BELL configuration, the BELL feature discovers all services in the `META-INF/services` folder of the referenced library. Alternatively, you can configure the `service` attribute to specify a service for Open liberty to look up in the `META-INF/service` folder, as shown in the following example.

[source,xml,subs="verbatim,quotes"]
----
<bell libraryRef="servicesLib"
      service="_name.of.fully.qualified.api.or.spi.interface_" />
----

For all services that are discovered or specified, the BELL feature registers the service interface and implementation class as an OSGi service, which makes the service available to the Open Liberty runtime.

Be sure to enable the Open Liberty features that export the API or SPI packages that are required by the BELL service implementation classes.

=== Implement an SPI with BELL services

Shared libraries do not support visibility for SPI packages like they do for config:library[display=API packages]. When you deploy BELL services that implement interfaces in SPI packages, you must set the `spiVisibility` attribute to `true` in the BELL configuration. This attribute enables the referenced library to see SPI packages,

[source,xml]
----
<bell libraryRef="servicesLib" spiVisibility="true"/>
----

SPI visibility is disabled by default and applies only to the library that is referenced in the BELL configuration. SPI visibility is not supported for the Open Liberty `global` shared library.

For more information, see <<expose,Expose a REST endpoint for custom resources>>

=== Specify configuration properties in BELL services

Service implementation classes can receive properties that are declared in the BELL configuration. To configure properties, add a `properties` element to your BELL configuration and declare one or more `name="value"` attributes. Properties are `String` type and apply to any services that are provided by the referenced library that are enabled for property injection. The following example declares the `hello` and `serverHome` properties.

[source,xml]
----
<bell libraryRef="servicesLib">
  <properties hello="WORLD" serverHome="${server.output.dir}" />
</bell>
----

To enable property injection for a service, define a public constructor or a public method that is named `updateBell` with a single parameter of the `java.util.Map<String,String>` type within the service implementation class.

[source,java]
----
public class YourServiceImpl implements api.or.spi.Interface {
  java.util.Map props;
  public ServiceImpl(Map<String,String> bellProps) {props=bellProps;}
  // OR
  public void updateBell(Map<String,String> bellProps) {props=bellProps;}
}
----

At service creation, the BELL feature invokes the `updateBell` constructor or methods to inject an unmodifiable map that contains a `key/value` pair for each property. For the previous examples, the resulting map contains the pairs `"hello"/"WORLD"` and `"serverHome"/"<resolved value of ${server.out.dir}>"`

The BELL feature does not support nondestructive updates. When you update a BELL configuration while the server is running, the feature does not inject updated `properties` into existing service instances. However, it affords this future enhancement by allowing users to define the `updateBell` method within the service implementation class. If you define the `updateBell` method to receive properties, ensure that the class can tolerate multiple calls to the `updateBell` method on the same instance.

For more information, see <<expose,Expose a REST endpoint for custom resources>>


=== Configure a servlet filter for applications

In certain scenarios, a servlet filter implementation must be applied to all applications that are deployed to Open Liberty. For example, a servlet filter might be used to add new headers to each request. The `javax.servlet.ServletContainerInitializer` interface provides an `onStartup` method that you can use to add a servlet filter implementation class to all applications.

You can use the BELL feature to configure a library that provides a `ServletContainerInitializer` implementation as a service. The `ServletContainerInitializer` service `onStartup` method is called by Open Liberty for each application that starts. In the following example, a `ServletContainerInitializer` implementation is configured to add a servlet filter implementation with each `ServletContext` object that is in a Java file. The `ServletContext.addFilter(String, Filter)` method is used by the `onStartup` method to add the servlet filter implementation

[source,java]
----
public class SCI implements ServletContainerInitializer {
  @Override
  public void onStartup(Set<Class<?>> arg0, ServletContext arg1)
    throws ServletException {
    arg1.addFilter("myFilter", MyFilter.class).addMappingForUrlPatterns(null, false, "/*");
  }
}
----

To register the `ServletContainerInitializer` interface that adds the servlet filter for an application, a class name is specified in the library JAR file. The library JAR file contains a `META-INF/services/javax.servlet.ServletContainerInitializer` file that specifies the fully qualified `ServletContainerInitializer` implementation class name that is contained in the library. The following example uses the `file` element to specify a a path to the JAR file and add it to the library. It also specifies the service that the BELL feature looks up and registers.


[source,xml,subs="verbatim,quotes"]
----
<library id="servletExtLib">
  <file name="_path to jar_"/>
</library>

<bell libraryRef="servletExtLib"
      service="javax.servlet.ServletContainerInitializer" />
----

[#expose]
=== Expose a REST endpoint for custom resources

Open Liberty extenders use the https://www.ibm.com/docs/en/was-liberty/nd?topic=SSAW57_liberty/com.ibm.websphere.javadoc.liberty.doc/spi_liberty_core.html[REST Handler framework] SPI to expose REST endpoints (REST APIs) for custom resources. You can use the BELL feature to expose a REST endpoint by providing a service that implements the `com.ibm.wsspi.rest.handler.RESTHandler` REST Handler SPI interface.

In the following  service implementation class example, a library provides an implementation of the `RestHandler` interface. The library also provides a service resource called `BellEndpoint` that enables the REST Handler framework to register the service as a listener at a specified subroot of the `/ibm/api` URL path. This minimal service implementation class also defines a single-argument constructor to receive BELL configuration properties at service creation.

[source,java]
----
package your.org.rest.example;
import com.ibm.wsspi.rest.handler.*;

public class BellEndpoint implements RESTHandler {
  java.util.Map<String,String> props;
  public BellEndpoint(java.util.Map<String, String> bellProperties) {props=bellProperties;}
  @Override
  public void handleRequest(RESTRequest request, RESTResponse response) {...}
}
----

To enable the endpoint, the `META-INF/services/com.ibm.wsspi.rest.handler.RESTHandler` service resource file must contain the name of the service implementation class and the `com.ibm.wsspi.rest.handler.root` OSGi service property. This OSGI service property is required by the `RESTHandler` SPI to register the service as a listener for the specified subroot of the `/ibm/api` URL path. Set the property to euall th name of the enpoint that you want to expose on the `/ibm/api/` URL path.

You can configure OSGi properties that are specific to a service implementation class by adding one or more properties, prefixed by the `#` character, to the service resource. Add the properties immediately before the name of the service implementation class to which they apply. The BELL feature registers the service interface with the implementation class and the specific OSGi properties.

The `com.ibm.wsspi.rest.handler.root` OSGi property in the following example enables an endpoint with the `/ibm/api/bellEP` URL path.

[source,java]
----
#com.ibm.wsspi.rest.handler.root=/bellEP
your.org.rest.example.BellEndpoint
----

For this example, the following service resource and implementation class files are packaged in the `RestEpLib.jar` file, which is available to the Open Liberty server configuration.

- `META-INF/services/com.ibm.wsspi.rest.handler.RESTHandler`
- `your/org/rest/example/BellEndpoint.class`


The following example shows the BELL configuration in the `server.xml` to support the endpoint. The BELL configuration specifies the `spiVisibility="true"` attribute to enable the `RestEpLib` library to see the REST Handler SPI packages. The `RestEpLib.jar` library JAR is deployed at to the `${server.config.dir}/sharedlib` directory and the configuration declares one BELL property, `hello`.

[source,xml]
----
<library id=”RestEpLib">
  <fileset dir="${server.config.dir}/sharedLib" includes="RestEpLib.jar" />
</library>

<bell libraryRef=”RestEpLib” spiVisibility=”true">
  <properties hello=“WORLD” />
</bell>
----

The `server.xml` file requires more configuration than just the BELL to expose the endpoint. In addition to the BELL feature, you must enable the feature:restConnector[display=Admin REST Connector] (`restConnector-2.0`) and feature:transportSecurity[display=Transport Security] (`transportSecurity-1.0`) features. The Admin REST Connector feature exports the REST Handler framework SPI. Endpoint access requires secure transport and a user who is mapped to the administrator role. The Transport Security feature and the related `keyStore`, `basicRegistry` and `adminstrator-role` configurations support secure access to the endpoint. The following `server.xml` file example shows a possible configuration, including the BELL configuration from the previous example.

[source,xml]
----
<featureManager>
  <feature>bells-1.0</feature>
  <feature>restConnector-2.0</feature>
  <feature>transportSecurity-1.0</feature>
</featureManager>

<keyStore id="defaultKeyStore" password="keystorePassword" />
<basicRegistry>
  <user name="you" password="yourPassword" />
  <group name="yourGroup" />
</basicRegistry>
<administrator-role>
  <user>you</user>
  <group>yourGroup</group>
</administrator-role>

<library id=”RestEpLib">
  <fileset dir="${server.config.dir}/sharedLib" includes="RestEpLib.jar" />
</library>

<bell libraryRef=”RestEpLib” spiVisibility=”true">
  <properties hello=“WORLD” />
</bell>
----

When this server starts, the BELL feature uses the `RestEpLib` library to register the `RESTHandler` interface with the `BellEndpoint` class and the `com.ibm.wsspi.rest.handler.root=/bellEP` OSGi service property into the OSGi framework. The REST Handler framework then registers the service and makes the endpoint available at the `https://<host>:8020/ibm/api/bellEP` URL.

When you make calls to the endpoint, the REST Handler framework handles the initial request by getting an instance of the service. The BELL feature creates an instance of the `BellEndpoint` class that is injected with an unmodifiable map that contains the `"hello"/"WORLD"` key/value pair. The framework then services the initial and subsequent requests by calling the `handleRequest` method on the `BellEnpoint` instance.

For more information about extending the REST Handler framework, see the https://www.ibm.com/docs/en/was-liberty/nd?topic=SSAW57_liberty/com.ibm.websphere.javadoc.liberty.doc/spi_liberty_core.html[REST Handler SPI documentation].
