== Examples

=== Configuring a Servlet Filter for applications

Certain scenarios require the use of a `Filter` implementation that can be applied to all applications that are deployed to Open Liberty. For example, a `Filter` could be used to add new headers to each request. The `ServletContainerInitializer` interface provides a method called `onStartup` that can be used to add a `Filter` implementation class to all applications.

The BELLs feature can be used to configure a library that provides a `ServletContainerInitializer` implementation as a service. The `ServletContainerInitializer` service `onStartup` method is called by Open Liberty for each application that starts. In the following example, a `ServletContainerInitializer` implementation is configured to add a `Filter` implementation with each `ServletContext` object. The `ServletContext.addFilter(String, Filter)` method is used by the `onStartup` method to add the `Filter` implementation:

[source,java]
----
public class SCI implements ServletContainerInitializer {
  @Override
  public void onStartup(Set<Class<?>> arg0, ServletContext arg1)
    throws ServletException {
    arg1.addFilter("myFilter", MyFilter.class).addMappingForUrlPatterns(null, false, "/*");
  }
}
----

To register the `ServletContainerInitializer` interface that adds the Servlet Filter for an application, a class name is specified in the library JAR file as shown in the following example:

[source,xml]
----
<library id="init">
  <file name="path/to/jar"/>
</library>

<bell libraryRef="init"/>
----

The library JAR file contains a `META-INF/services/javax.servlet.ServletContainerInitializer` file that specifies the fully qualified `ServletContainerInitializer` implementation class name that is contained in the library.

=== Adding the shared library for a custom user registry

The BELLs feature can load a custom user registry with a custom user registry JAR file that is stored in a shared library on the server. The following example adds the `resources/sharedLib` shared library that contains the `bellsCur.jar` JAR file that the BELLs feature uses to load the custom user registry:

[source,xml]
----
<library id="bellsCurLib" name="bellsCurLib">
         <file name="${server.config.dir}/resources/sharedLib/bellsCur.jar"></file>
 </library>
 <bell libraryRef="bellsCurLib"></bell>
----
