// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:page-layout: general-reference
:seo-title: Open Liberty commands
:seo-description:
= Commands



== featureUtility commands

The `featureUtility` commands can help you install Open Liberty features and view your Maven repository settings.
You can install a single feature or a list of space-separated features with the xref:featureUtility-installFeature.adoc[featureUtility installFeature command].
If you need to install many features, you can install all of the features that are specified in your `server.xml` file with the xref:featureUtility-installServerFeatures.adoc[featureUtility installServerFeatures command].
To learn how you can modify the behavior of the `featureUtility` commands, see xref:featureUtility-modifications.adoc[Repository and proxy modifications].

== securityUtility commands

The `securityUtility` commands perform various security-related tasks for Open Liberty.
With the xref:securityUtility-encode.adoc[securityUtility encode command], you can obfuscate passwords with the encoding type that you choose.
You can use the xref:securityUtility-createLTPAKeys.adoc[securityUtility createLTPAKeys command] to create a set of LTPA keys for the server, or use the xref:securityUtility-createSSLCertificate.adoc[securityUtility createSSLCertificate command] to generate a self-signed TLS certificate.

== server commands

The `server` commands 
