// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description:
:page-layout: general-reference
:seo-title: Open Liberty commands
:seo-description:
= Commands

The following commands are available for use in Open Liberty:

* <<featureUtility,featureUtility commands>>
* <<securityUtility,securityUtility commands>>
* <<server,server commands>>

[#featureUtility]
== featureUtility commands

The `featureUtility` commands make it easier to install Open Liberty features and view your Maven repository settings.
When you need to install features, you can xref:command/featureUtility-installFeature.adoc[install a single feature or a list of space-separated features], or you can xref:command/featureUtility-installServerFeatures.adoc[install all the features that are specified in your server.xml file].
To learn how you can modify the behavior of the `featureUtility` commands, such as the shared and local feature repositories, see xref:command/featureUtility-modifications.adoc[Repository and proxy modifications].

[#securityUtility]
== securityUtility commands

The `securityUtility` commands help you accomplish various security-related tasks for Open Liberty.
With these commands, you can xref:command/securityUtility-encode.adoc[obfuscate passwords], xref:command/securityUtility-createLTPAKeys.adoc[create a set of LTPA keys for the server], or xref:command/securityUtility-createSSLCertificate.adoc[generate a default TLS certificate].
For more information about password encryption with Open Liberty, see xref:ROOT:password-encryption.adoc[Password encryption].

[#server]
== server commands

The `server` commands perform Open Liberty server functions that include xref:command/server-create.adoc[creating a server], xref:command/server-start.adoc[starting a server], and xref:command/server-stop.adoc[stopping a server].
You can also xref:command/server-dump.adoc[perform a server memory dump], which creates a snapshot of the server and saves the result into an archive file, or xref:command/server-debug.adoc[run a server in debug mode].
With these commands, you can manage basic operation of an Open Liberty server.
