// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Various commands are available for use in Open Liberty.
:page-layout: general-reference
:seo-title: Open Liberty commands
:seo-description: Various commands are available for use in Open Liberty.
= Commands

Various commands are available for use in Open Liberty.
You can use commands to complete tasks such as installing, securing, and administering the Open Liberty server.

You can get the help information for any of the commands by typing the command name followed by the `help` action.
For example, you can run the `server help` command to display help information about the `server` command and its available options.

You can also see the following documentation for more information about commonly used commands in Open Liberty:

* <<featureUtility,featureUtility commands>>
* <<securityUtility,securityUtility commands>>
* <<server,server commands>>
* <<springBootUtility,springBootUtility commands>>
* <<auditUtility, auditUtility command>>

[#featureUtility]
== featureUtility commands

The `featureUtility` commands make it easier to install Open Liberty features and view your Maven repository settings.
When you install features, you can xref:command/featureUtility-installFeature.adoc[install a single feature or a list of space-separated features], or you can xref:command/featureUtility-installServerFeatures.adoc[install all the features that are specified in your server.xml file].
To learn how you can modify the behavior of the `featureUtility` commands, such as the shared and local feature repositories, see xref:command/featureUtility-modifications.adoc[Modifications for featureUtility commands].

[#securityUtility]
== securityUtility commands

The `securityUtility` commands help you accomplish various security-related tasks for Open Liberty.
With these commands, you can xref:command/securityUtility-encode.adoc[obfuscate passwords], xref:command/securityUtility-createLTPAKeys.adoc[create a set of LTPA keys for the server], or xref:command/securityUtility-createSSLCertificate.adoc[generate a default TLS certificate].
For more information about password encryption with Open Liberty, see xref:ROOT:password-encryption.adoc[Password encryption limitations].

[#server]
== server commands

The `server` commands perform Open Liberty server functions that include xref:command/server-create.adoc[creating a server], xref:command/server-start.adoc[starting a server], and xref:command/server-stop.adoc[stopping a server].
You can also xref:command/server-dump.adoc[perform a server memory dump], which creates a snapshot of the server and saves the result into an archive file, or xref:command/server-debug.adoc[run a server in debug mode].
With these commands, you can manage basic operation of an Open Liberty server.

[#springBootUtility]
== springBootUtility commands

The `springBootUtility` commands help to deploy Spring Boot applications with Open Liberty. You can xref:command/springbootUtility-thin.adoc[create a thin Spring Boot application] and library cache from a fat Spring Boot application. For more information, see link:/guides/spring-boot.html[Containerizing, packaging, and running a Spring Boot application].

[#auditUtility auditReader]
== auditUtility auditReader command

The xref:command/auditUtility-auditReader.adoc[auditUtility auditReader] command decrypts and unsigns an audit log that is encrypted, signed, or both.
