//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The `featureUtility viewSettings` command allows you to view repository and proxy settings.
:seo-title: featureUtility viewSettings - OpenLiberty.io
:seo-description: The `featureUtility viewSettings` command allows you to view repository and proxy settings.
:page-layout: general-reference
:page-type: general
= featureUtility viewSettings

With the `featureUtility viewSettings` command, you can view Maven repository and proxy settings when Maven repositories other than Maven Central are configured.
When you run the command, the settings from the `featureUtility.properties` file are displayed.

== Usage example

Display detailed error messages for the validation of your `featureUtility.properties` file.
With this option, only lines with errors are displayed:

----
featureUtility viewSettings --viewValidationMessages
----

== Syntax

Run the command from the `_path_to_liberty_/bin` directory.

[subs=+quotes]
----
featureUtility _viewSettings_ [_option_]
----

option::
One optional parameter.

== Option

[%header,cols=2*]
|===
|Option
|Description

|--viewValidationMessages
|Displays detailed messages from the validation of the configured `featureUtility.properties` file.
Each message contains an error code, the line number where the error was found, and the cause of the error.

|===
