//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The `featureUtility find` command finds features in the repositories that are applicable to your configuration and allows you to view detailed information about them.
:seo-title: featureUtility find - OpenLiberty.io
:seo-description: The `featureUtility find` command finds features in the repositories that are applicable to your configuration and allows you to view detailed information about them.
:page-layout: general-reference
:page-type: general
= featureUtility find

The `featureUtility find` command finds features in the repositories that are applicable to your configuration and allows you to view detailed information about these features.

== Usage examples

Search Maven Central and all your configured Maven repositories for the MicroProfile Health 2.2 feature:

----
featureUtility find mpHealth-2.2
----

Search Maven Central and all your configured Maven repositories for all available features:

----
featureUtility find
----

== Syntax

Run the command from the `path_to_liberty/bin` directory.

----
featureUtility find searchString
----

searchString::
The `featureUtility find` command finds features with names or descriptions that match the _searchString_ in Maven Central and your configured Maven repositories.
If you do not specify a _searchString_, the `featureUtility find` command searches for all available features.
