//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The `featureUtility installServerFeatures` command installs the required features for a specified server.
:seo-title: featureUtility installServerFeatures - OpenLiberty.io
:seo-description: The `featureUtility installServerFeatures` command installs the required features for a specified server.
:page-layout: general-reference
:page-type: general
= featureUtility installServerFeatures

The `featureUtility installServerFeatures` command installs the required features that are listed in the `server.xml` file of a server.

== Usage example

Install the server features for the `myserver` server:

----
featureUtility installServerFeatures myserver
----

Install the features for the `myserver` server, which includes custom user features:

[subs=+quotes]
----
featureUtility installServerFeatures myserver --featuresBom=my.user.features:myBOM:<runtime-version>
----
In this example, the `<runtime-version>` value is the version of the Open Liberty server where you want to install the feature, for example, `21.0.0.11`.

== Syntax

Run the command from the `_path_to_liberty_/wlp/bin` directory.

[subs=+quotes]
----
featureUtility installServerFeatures _serverName_ [_options_]
----

serverName::
The name of the server to run the command against.

== Options

.Options for the featureUtility installServerFeatures command
[%header,cols=2*]
|===
|Option
|Description

|--acceptLicense
|Accepts the license agreement for the feature if the feature has a different license from the Liberty server into which it's installed.

|--featuresBom
|Specifies the Maven coordinates for a features BOM file. Use this option to install custom user features from a Maven repository. Ensure that the repository also contains the associated features JSON file in the same group ID as the BOM.

|--noCache
|Specifies that features that are installed from a remote repository, such as Maven Central, aren't cached locally.

|--verbose
|Displays additional debug information while the action runs.

|--verify=_verify_option_
a|Specifies how features must be verified. 
Supported values are `encode`, `skip`, `all`, and `warn`. If this option is not specified, the default value is `encode`.

* `encode`: Verifies the signatures of all Liberty features except for user features. It checks the integrity and authenticity of the features that are provided by the Liberty framework.
* `skip`: Choosing this option skips the verification process altogether. No feature signatures are downloaded or checked. It expedites the installation process but must be used with caution, as it bypasses an important security step.
* `all`: Verifies both the Liberty features and the user features. The features that are provided by the Liberty framework and any additional user features or components are checked for integrity.
* `warn`: Similar to the `all` option, warn also verifies both the Liberty features and user features. This option allows the process to continue, even if some feature signatures cannot be validated. A verification failure does not immediately end the installation process, but it results in a warning message.

|--to
|Specify the extension location to install user features. If this option is not specified, the feature is installed to default `{wlp.install.dir}/usr/extension` directory.

|===

== Exit codes
The following exit codes are available for the `featureUtility installServerFeatures` command:

.Exit codes for the featureUtility installServerFeatures command
[%header,cols="2,9"]
|===

|Code
|Explanation

|0
|OK. 0 indicates successful completion of the requested operation.

|20
|20 indicates that one or more arguments are not valid.

|21
|21 indicates that a runtime exception occurred because of one or more of the following conditions:
		- A runtime exception occurred during the installation of the `.esa` subsystem archive file.
		- A license is not accepted or acknowledged.
		- The `.esa` subsystem archive file did not extract correctly.

|22
|22 indicates that feature to be installed already exists.

|23
|23 indicates that the feature definition was not valid for one or more of the following reasons:
		- The feature does not have a valid manifest file.
		- The version of the feature is not supported in this Open Liberty environment.
		- The `.zip` or `.jar` file that contains the feature files does not exist.
|24
|24 indicates that the `.esa` subsystem archive file is missing content.

|25
|25 indicates that an I/O exception occurred during the installation of the `.esa` subsystem archive file.

|29
|29 indicates that the feature is not valid for the current product.

|33
|33 indicates that the connection to the repository failed.

|37
|37 indicates that the feature signature verification failed.
|===
