//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The `featureUtility installFeature` command installs features. You can install either a single feature or a list of space-separated features.
:seo-title: featureUtility installFeature - OpenLiberty.io
:seo-description: The `featureUtility installFeature` command installs features. You can install either a single feature or a list of space-separated features.
:page-layout: general-reference
:page-type: general
= featureUtility installFeature

The `featureUtility installFeature` command installs features.
You can install either a single feature or a list of space-separated features.

You can use the `featureUtility installFeature` command to install features into Open Liberty from Maven Central, or from a Maven repository that's hosted inside your firewall.

== Usage examples

Install the xref:reference:feature/mpHealth-2.2.adoc[MicroProfile Health 2.2 feature] from Maven Central:

----
featureUtility installFeature mpHealth-2.2
----

Install the MicroProfile Health 2.2 feature without caching the feature to the local Maven repository:

----
featureUtility installFeature mpHealth-2.2 --noCache
----

== Syntax

Run the command from the `path_to_liberty/bin` directory.

----
featureUtility installFeature [options]
----

options::
One or more optional parameters.

== Options

[%header,cols=2*]
|===
|Option
|Description

|--acceptLicense
|Accepts the license agreement for the feature if the feature has a different license from the Liberty server into which it's installed.

|_featureName_
|One or more features that are separated by a space.
Specify the feature shortname or the Maven coordinate.
If you specify a Maven coordinate, it must contain the group ID and the artifact ID, for example, `io.openliberty.features:mpHealth-2.0`.
{empty} +
{empty} +
If the version and packaging type aren't specified, the version defaults to the current runtime version and the packaging type defaults to ESA.

|--noCache
|Specifies that features installed from a remote repository, such as Maven Central, aren't cached locally.

|--verbose
|Displays additional debug information while the action runs.

|===
