//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The `featureUtility find` command finds features in the repositories that are applicable to your configuration and allows you to view detailed information about them.
:seo-title: featureUtility find - OpenLiberty.io
:seo-description: The `featureUtility find` command finds features in the repositories that are applicable to your configuration and allows you to view detailed information about them.
:page-layout: general-reference
:page-type: general
= featureUtility find

The `featureUtility find` command finds features in the repositories that are applicable to your configuration and allows you to view detailed information about these features.

== Usage examples

Search Maven Central and all your configured Maven repositories for the MicroProfile Health 2.2 feature:

----
featureUtility find mpHealth-2.2
----

Search Maven Central and all your configured Maven repositories for all available features:

----
featureUtility find
----

== Syntax

Run the command from the `_path_to_liberty_/wlp/bin` directory.

[subs=+quotes]
----
featureUtility find _searchString_
----

searchString::
The name of the feature that you want to find.
The `featureUtility find` command finds features with names or descriptions that match the search string in Maven Central and your configured Maven repositories.
If you do not specify a search string, the `featureUtility find` command searches for all available features.

== Exit codes
The following exit codes are available for the `featureUtility find` command:

.Exit codes for the featureUtility find command
[%header,cols="2,9"]
|===

|Code
|Explanation

|0
|This code indicates successful completion of the requested operation.

|20
|This code indicates that one or more arguments are not valid.

|21
|This code indicates that a runtime exception occurred during connection to a repository.
|===
