//
// Copyright (c) 2020, 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The `securityUtility encode` command supports plain text obfuscation for Open Liberty.
:seo-title: securityUtility encode - OpenLiberty.io
:seo-description: The `securityUtility encode` command supports plain text obfuscation for Open Liberty.
:page-layout: general-reference
:page-type: general
= securityUtility encode

The `securityUtility encode` command supports plain text obfuscation for Open Liberty.

This command obfuscates text that you provide, such as a password, based on the encoding type that you specify.

If no text is provided, the command enters interactive mode.
Interactive mode prompts you to enter and confirm your text input, rather than provide text on the same line as the command.

Enclose any text with spaces in quotation marks.
If your password includes special characters, you must escape each special character to help ensure that the password is properly encoded. For more information, see <<pw,Check passwords for special characters>>.


Starting in version 26.0.0.3, the `securityUtility encode --encoding=aes` command no longer uses a default encryption key.
One of the following arguments must now be specified: `--key`, `--base64Key`, `--aesConfigFile`, or `--keyring`.

For more information about limits to password encryption, see xref:ROOT:password-encryption.adoc[Password encryption limitations].

== Usage examples

Encrypt a password with Advanced Encryption Standard (AES) encryption by specifying an encryption key string.
After you enter this command, interactive mode prompts you for the password that you want to encrypt:

----
securityUtility encode --encoding=aes --key=<encryption_key_string>
----

Hash a password. After you enter this command, interactive mode prompts you for the password that you want to hash:

----
securityUtility encode --encoding=hash
----

Encode a password by using a Base64-encoded AES key, specify the key directly:

[source,sh]
----
securityUtility encode --encoding=aes --base64Key=<your_base64_key> MyPassword
----

Use a configuration file that contains the AES key variable, specify the `--aesConfigFile` option:

[source,sh]
----
securityUtility encode --encoding=aes --aesConfigFile=aesConfig.xml MyPassword
----

For example, `aesConfig.xml` could contain one of the following definitions:

[source,xml]
----
<variable name="wlp.aes.encryption.key" value="<your_aes_key>" />
----

or

[source,xml]
----
<variable name="wlp.password.encryption.key" value="yourKey" />
----

[NOTE]
====
The `aesConfigFile.xml` file must contain either the `wlp.aes.encryption.key` or `wlp.password.encryption.key` variable. Only one variable can be present in a file.
====

Hash a password. After you enter this command, interactive mode prompts you for the password that you want to hash:

----
securityUtility encode --encoding=hash
----


== Syntax

Run the command from the `_path_to_liberty_/wlp/bin` directory.

----
securityUtility encode [options]
----

== Options

.Options for the securityUtility encode command
[%header,cols=2*]
|===
|Option
|Description

|--encoding=_encoding_type_
|Specifies how to encode the password.
Supported encodings are `xor`, `aes`, `aes-128`, and `hash`.
The default encoding is `xor`.
`aes` encrypts by using an `aes-256` bit key.
`aes-128` can be used for compatibility with server versions before 25.0.0.2.
{empty} +
{empty} +
You can use the `hash` encoding type to encode passwords for a xref:ROOT:user-registries-application-security.adoc[basic user registry] or passwords for the xref:config/quickStartSecurity.adoc[quickStartSecurity element].


When FIPS 140-3 is enabled, both the `aes` and `hash` options use enhanced algorithms to encrypt and hash strings. Strings that were encrypted or hashed before the algorithms were enhanced might fail in FIPS 140-3 environments.


|--key=_encryption_key_
|Specifies the key to use when you encode with AES encryption.
This string is hashed to produce an encryption key that is used to encrypt and decrypt the password.
You can provide the key by defining the `wlp.password.encryption.key` property as the key value.
If this option isn't specified, a default key is used.
This option cannot be combined with `--base64Key` or `--aesConfigFile`.

|--listCustom
a|Displays the information of the custom password encryption in JSON format.
The information consists of the following things:

* `name`: The custom password encryption algorithm name.
* `featurename`: The feature name.
* `description`: The description of the custom password encryption.

|--notrim
|Specifies whether space characters are removed from the beginning and end of the specified text.
If this option is specified, the provided text is encoded as it is.
If this option isn't specified, space characters are removed from the beginning and end of the specified text.

|--base64Key=<key>
|Specifies a Base64-encoded 256-bit AES key that is used to encrypt and decrypt the password.
This option cannot be combined with `--aesConfigFile` or `--key`.

|--aesConfigFile=<file>
|Specifies an XML or Java properties file that contains either the `wlp.password.encryption.key` or `wlp.aes.encryption.key` variable.
Only one of these variables can be present in a file.
This option cannot be combined with `--base64Key` or `--key`.

|===

== Exit codes

The following exit codes are available for the `securityUtility encode` command:

.Exit codes for the securityUtility encode command
[%header,cols="2,9"]
|===

|Code
|Explanation

|0
|This code indicates successful completion of the requested operation.

|1
|This code indicates a generic error.

|2
|This code indicates that the server is not found.

|3
|This code indicates that the client is not found.

|4
|This code indicates that the path can not be created.

|5
|This code indicates that the file already exists.
|===


[#pw]
== Check passwords for special characters

If your password includes special characters, you must escape each special character to help ensure that the password is properly encoded.
Special characters and escape characters might vary according to your operating system.
For example, on Unix systems, `pa$$W0rd` must be provided as `pa\$\$W0rd`.

To check whether your password includes any characters that your operating system considers to be special characters, you can run the `echo` command.

On the command line, type `echo` followed by the password and review the output to determine whether it differs from your specified password. If any characters are changed, you must escape the characters.  The following example is for Ubuntu.

----
$ echo pa$$W0rd
pa683W0rd
// The dollar sign ($) special characters aren't encoded properly.

$ echo pa\$\$W0rd
pa$$W0rd
// Escape each special character individually to return the correct password to encode.

$ securityUtility encode pa\$\$W0rd
----