//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The `securityUtility encode` command supports plain text obfuscation for Open Liberty.
:seo-title: securityUtility encode - OpenLiberty.io
:seo-description: The `securityUtility encode` command supports plain text obfuscation for Open Liberty.
:page-layout: general-reference
:page-type: general
= securityUtility encode

The `securityUtility encode` command supports plain text obfuscation for Open Liberty.

This command obfuscates provided text, such as a password, based on the type that is specified.
If no text is provided, the command enters interactive mode.
Interactive mode prompts you to enter and confirm your text input, rather than providing text on the same line as the command.
Text with spaces must be put in quotation marks.
For more information about limits to password encryption, see xref:ROOT:password-encryption.adoc[Password encryption].

== Usage examples

Encrypt a password with AES encryption. After you enter this command, interactive mode prompts you for the password that you want to encrypt:

----
securityUtility encode --encoding=aes
----

Hash a password. After you enter this command, interactive mode prompts you for the password that you want to hash:

----
securityUtility encode --encoding=hash
----

== Syntax

Run the command from the `path_to_liberty/bin` directory.

----
securityUtility encode [options]
----

options::
One or more optional parameters.

== Options

[%header,cols=2*]
|===
|Option
|Description

|--encoding=encoding_type
|Specifies how to encode the password.
Supported encodings types are `xor`, `aes`, and `hash`.
If this option is not provided, a default encoding type of `xor` is used.
{empty} +
{empty} +
You can use the hash encoding option to encode passwords for the xref:ROOT:user-registries-application-security.adoc[basic user registry].
As of 19.0.0.2, you can also use this option to encode passwords for the xref:config/quickStartSecurity.adoc[`quickStartSecurity` element].

|--key=encryption_key
|Specifies the key to be used when you encode with AES encryption.
This string is hashed to produce an encryption key that is used to encrypt and decrypt the password.
You can provide the key by defining the `wlp.password.encryption.key` variable as the key value.
If this option is not provided, a default key is used.

|--listCustom
a|Displays the information of the custom password encryption in JSON format.
The information consists of:

* `name`: The custom password encryption algorithm name.
* `featurename`: The feature name.
* `description`: The description of the custom password encryption.

|--notrim
|Specifies whether space characters are removed from the beginning and end of the specified text.
If this option is specified, the provided text is encoded as it is.
If this option is not specified, space characters from the beginning and end of the specified text are removed.

|===
