//
// Copyright (c) 2025 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: The `securityUtility generateAESKey` command generates a Base64-encoded 256-bit AES key that can be used with the `wlp.aes.encryption.key` configuration variable for password encryption in Open Liberty.
:seo-title: securityUtility generateAESKey - OpenLiberty.io
:seo-description: The `securityUtility generateAESKey` command generates a 256-bit AES encryption key for use with password encryption in Open Liberty.
:page-layout: general-reference
:page-type: general


= generateAESKey

Generates a Base64-encoded 256-bit AES key that can be used with the `wlp.aes.encryption.key` configuration variable for password encryption in Open Liberty. 

You can generate a random AES key, derive a key from a passphrase, or create an XML configuration file that contains the generated key.


== Usage Examples

To generate a random 256-bit AES key, run the following command.

[source,sh]
----
securityUtility generateAESKey
----

To derive the AES key from a passphrase, specify the `--key` option.

[source,sh]
----
securityUtility generateAESKey --key=MyPassphrase
----

To generate an AES key and automatically create a configuration file, use the following example.

[source,sh]
----
securityUtility generateAESKey --createConfigFile=myAesConfig.xml
----


== Syntax

[source,sh]
----
securityUtility generateAESKey [options]
----

== Options

.Options for the securityUtility generateAESKey command
[%header,cols=2*]
|===
|Option
|Description

| --createConfigFile=<name>
| Creates an XML file that contains the generated AES key in the `wlp.aes.encryption.key` variable. 
If this option is not specified, the generated key is written to the console screen.

| --key=<string>
| This string is hashed to produce an encryption key that is used to encrypt and decrypt passwords. 
If this option is omitted, a random AES key is generated.

|===

