//
// Copyright (c) 2019, 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server start command

Starts the named Open Liberty server as a background process.

The standard output and error from the server process are redirected to the `WLP_OUTPUT_DIR/serverName/logs/console.log` file.

//See also:

//* Equivalent command for Maven.
//* Equivalent command for Gradle.
//* Start a Liberty server in the foreground.
//* Stop a Liberty server.
//* Create a Liberty server.
//* Start a Liberty server in debug mode.

== Usage examples

Start the `myserver` server in the background:

----
server start myserver
----

Start the `myserver` server in the background and set the `variable_name` variable to the `variable_value` value:

----
server start myserver -- --variable_name=variable_value
----

Start the `myserver` server without persistent cached data:

----
server start myserver --clean
----

== Syntax

Run the command from the `path_to_liberty/bin` directory.

----
server start serverName [options]
----

serverName::
The name of the server to run the command against.
If no server is specified, a server called `defaultServer` is automatically created to run the command against.

options::
One or more optional parameters.

== Options

[%header,cols=2*]
|===
|Option
|Description

|--clean
|Cleans all persistent cached information that is related to the specified server instance, which includes OSGi resolver metadata and persistent OSGi bundle data.
If you use this option, the server is required to recompute any cached data at the next startup, which might take more time than a restart that reuses cached data.

|--variable_name=variable_value
|Defines variables. Include `--` in the command before you specify the option, as shown in the usage example.
{empty} +
{empty} +
Variables that are specified on the command line override all other sources of variables and can't be changed after the server starts.

|===

== See also

* xref:server-run.adoc[server run]
* xref:server-stop.adoc[server stop]

== Exit codes

The following exit codes are available for the `server start` command and the equivalent executable JAR file `ws-server.jar`:

0::
    OK. 0 indicates successful completion of the requested operation.
1::
    1 indicates invocation of a redundant operation, such as starting a started server or stopping a stopper server.
    1 might also be returned if the JVM options that were used are not valid.
2::
    2 indicates that the server does not exist.
>=20::
    Exit codes greater than or equal to 20 indicate that an error occurred while performing the request.
    Messages are printed and captured in log files with more information about the error.

// Include description of server process
include::server-serverprocess.adoc[]
