//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server stop command

The `server stop` command stops the named Open Liberty server.

Normal server stop includes a 30 second quiesce stage before the server shuts down. This quiesce stage allows time for shutdown preparation, such as stopping inbound listeners but allowing existing requests to complete. Applying the `--force` option to the stop command skips the quiesce stage. The `--force` option has no effect if server stop was already initiated. If you use the `--force` option, you might see unexpected exceptions in the `messages.log` file that occur after the server received the server stop command.

== Usage examples

Stop the `myserver` server with the quiesce stage:

----
server stop myserver
----

Force the `myserver` server to stop without the quiesce stage:

----
server stop myserver --force
----

== Syntax

Run the command from the `_path_to_liberty_/wlp/bin` directory.

[subs=+quotes]
----
server stop _serverName_ [_options_]
----

serverName::
The name of the server to run the command against. If no server is specified, the action is performed against the default server instance, `defaultServer`, if it exists.

options::
One or more optional parameters.

== Options

.Options for the server stop command
[%header,cols=2*]
|===
|Option
|Description

|--force
|Skips the quiesce stage before the server is shut down.
{empty} +
{empty} +
Normal server stop includes a quiesce stage before the server is shut down. The quiesce stage, a period of 30 seconds, allows services to perform pre-shutdown work; for example, inbound listeners are stopped but existing requests are allowed to complete.
{empty} +
{empty} +
The `--force` option has no effect if server stop was already invoked. If you use the `--force` option, you might see unexpected exceptions in the `messages.log` file that occur after the `server stop` command was received by the server.
|
|--timeout
|Specifies the amount of time to wait for the server to stop.
{empty} +
The default time to wait for the server to stop is 30 seconds.
{empty} +
The format for the duration is `XXmXXs`. Where `m` stands for minutes and `s` stands for seconds. If no units are specified, the value is assumed to be seconds.The following examples show the different formats used for `--timeout`.
{empty} +
----
server stop                   // 30 seconds
server stop --timeout=45      // 45 seconds
server stop --timeout=45s     // 45 seconds
server stop --timeout=3m20s   // 3 minutes, 20 seconds
----
|===

== Exit codes

The following exit codes are available for the `server stop` command and the equivalent executable JAR file `ws-server.jar`:

.Exit codes for the server stop command
[%header,cols="2,9"]
|===

|Code
|Explanation

|0
|This code indicates successful completion of the requested operation.

|1
|This code indicates invocation of a redundant operation, such as starting a started server or stopping a stopper server.
1 might also be returned if the JVM options that were used are not valid.

|2
|This code indicates that the server does not exist.

|>=20
|Exit codes that are greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.
|===

== See also

* xref:command/server-run.adoc[server run]
* xref:command/server-start.adoc[server start]
