//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server create command

The `server create` command creates an Open Liberty server.

== Usage examples

Create a server called `myserver`:

----
server create myserver 
----

== Syntax

Run the command from the `_path_to_liberty_/wlp/bin` directory.

[subs=+quotes]
----
server create _serverName_ [_options_]
----

serverName::
A name for the server. If no server is specified, a server called `defaultServer` is automatically created.

This command is subject to the following naming constraints:

* Use only Unicode alphanumeric (e.g. 0-9, a-z, A-Z), underscore (_), dash (-), plus (+), and period (.) characters.
* Do not begin the name with a dash (-) or a period (.).
* Be aware that your file system, operating system, or compressed file directory might impose more restrictions.

When the server is created successfully, you receive the message: `Server _serverName_ created`.

A directory with the name of the new server is created under the `${wlp.user.dir}/servers` directory, which contains the configuration of the new server. The HTTP port numbers for the new server are assigned to default values and are shown in the generated `server.xml` file to make it easy to edit them.

If the specified server exists, then no server is created and you receive an exception message:

----
CWWKE0005E: The runtime environment could not be launched.
CWWKE0045E: It was not possible to create the server called server_name because
the server directory C:\wlp\usr\servers\server_name already exists.
----

== Exit codes

The following exit codes are available for the `server create` command and the equivalent executable JAR file `ws-server.jar`:

== Options

.Options for the server create command
[%header,cols=2*]
|===
|Option
|Description

|--no-password
|When this option is specified, no default keystore password is generated when the server is created.

|--template=_templateName_
|This option specifies the name of the template to use when a new server is created. The template is a customized `server.xml` or `client.xml` file with pre-configured features and settings for a particular programming model. By default, the available templates are in the `wlp/templates/servers` and `wlp/templates/clients` directories.
For example, `server create myServer --template=jakartaee10`
|===

.Exit codes for the server create command
[%header,cols="2,9"]
|===

|Code
|Explanation

|0
|This code indicates successful completion of the requested operation.

|1
|This code indicates invocation of a redundant operation. For example, starting a started server or stopping a stopped server. This code might also be returned by JVM if invalid Java options are used.

|>=20
|Exit codes that are greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.
|===

== See also

* xref:command/server-run.adoc[server run]
* xref:command/server-start.adoc[server start]
