//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
:page-layout: server-command
:page-type: command
= server version command

The `server version` command displays the version information of the named server and the current Java runtime environment. 

== Usage examples

Find out the version information of the `myserver` server:

----
server version myserver
----

== Syntax

Run the command from the `_path_to_liberty_/wlp/bin` directory.

[subs=+quotes]
----
server version _serverName_
----

serverName::
The name of the server to run the command against. If no server name is specified, the default `defaultServer` server name is used. If no server name is specified and no `defaultServer` server exists, the command displays the version of the Liberty installation.
+
If the named server specifies a particular Java virtual machine (JVM) with the `JAVA_HOME` variable in the `server.env` file, the command displays the version for that JVM. Otherwise, the system default version is displayed.


== Exit codes

The following exit codes are available for the `server version` command and the equivalent executable JAR file `ws-server.jar`:

.Exit codes for the server version command
[%header,cols="2,9"]
|===

|Code
|Explanation

|0
|This code indicates successful completion of the requested operation.

|1
|This code indicates invocation of a redundant operation. For example, starting a started server or stopping a stopped server. This code might also be returned by JVM if invalid Java options are used.

|>=20
|Exit codes that are greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.
|===

== See also

* xref:command/server-list.adoc[server list]
