//
// Copyright (c) 2019, 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server run command

Starts the named Open Liberty server as a foreground process.

The standard output and error from the server process are output to the foreground.

== Usage examples

Start the `myserver` server in the foreground:

----
server run myserver
----

Start the `myserver` server in the foreground and set the `variable_name` variable to the `variable_value` value:

----
server run myserver -- --variable_name=variable_value
----

== Syntax

Run the command from the `path_to_liberty/bin` directory.

----
server run serverName [options]
----

serverName::
The name of the server to run the command against.
If no server is specified, a server called `defaultServer` is automatically created to run the command against.

options::
One or more optional parameters.

== Options

[%header,cols=2*]
|===
|Option
|Description

|--variable_name=variable_value
|Defines variables.
Include `--` in the command before you specify the option, as shown in the usage example.
{empty} +
{empty} +
Variables that are specified on the command line override all other sources of variables and can't be changed after the server starts.

|===

== See also

* xref:command/server-start.adoc[server start]
* xref:command/server-stop.adoc[server stop]

== Exit codes

The following exit codes are available for the `server run` command and the equivalent executable JAR file `ws-server.jar`:

0::
    OK. 0 indicates successful completion of the requested operation.
1::
    1 indicates invocation of a redundant operation, such as starting a started server or stopping a stopper server.
    1 might also be returned if the JVM options that were used are not valid.
2::
    2 indicates that the server does not exist.
>=20::
    Exit codes greater than or equal to 20 indicate that an error occurred while performing the request.
    Messages are printed and captured in log files with more information about the error.

// Include description of server process
include::server-serverprocess.adoc[]
