//
// Copyright (c) 2019, 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server debug command

The `server debug` command starts the named Open Liberty server in debug mode.

This command runs the named server in the console foreground after a debugger connects to the debug port.
The standard output and error from the server process are output to the foreground.
The default port is `7777`.
You can use the `${WLP_DEBUG_ADDRESS}` variable to specify an alternative port.

//  See also:
//* Equivalent command for Maven.
//* Equivalent command for Gradle.
//* Start an Open Liberty server in the foreground.

== Usage examples

Start the `myserver` server in debug mode:

----
server debug myserver
----

Start the `myserver` server in debug mode and set the `variable_name` variable to the `variable_value` value:

----
server debug myserver -- --variable_name=variable_value
----

== Syntax

Run the command from the `_path_to_liberty_/wlp/bin` directory.

[subs=+quotes]
----
server debug _serverName_ [_options_]
----

serverName::
The name of the server to run the command against.
If no server is specified, a server called `defaultServer` is automatically created to run the command against.

== Option

.Option for the server debug command
[%header,cols=2*]
|===
|Option
|Description

|--variable_name=_variable_value_
|Defines variables. Include `--` in the command before you specify the option, as shown in the usage example.
{empty} +
{empty} +
Variables that are specified on the command line override all other sources of variables and can't be changed after the server starts.

|===


== Exit codes

The following exit codes are available for the `server debug` command and the equivalent executable JAR file `ws-server.jar`:

.Exit codes for the server debug command
[%header,cols="2,9"]
|===

|Code
|Explanation

|0
|This code indicates successful completion of the requested operation.

|1
|This code indicates invocation of a redundant operation, such as starting a started server or stopping a stopper server.
1 might also be returned if the JVM options that were used are not valid.

|>=20
|Exit codes that are greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.
|===


// Include description of server process
include::server-serverprocess.adoc[]

== See also

* xref:command/server-stop.adoc[server stop]
