//
// Copyright (c) 2019, 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server run command

The `server run` command starts the named Open Liberty server as a foreground process.

The standard output and error from the server process are output to the foreground.

== Usage examples

Start the `myserver` server in the foreground:

----
server run myserver
----

Start the `myserver` server in the foreground and set the `variable_name` variable to the `variable_value` value:

----
server run myserver -- --variable_name=variable_value
----

== Syntax

Run the command from the `_path_to_liberty_/wlp/bin` directory.

[subs=+quotes]
----
server run _serverName_ [_options_]
----

serverName::
The name of the server to run the command against.
If no server is specified, a server called `defaultServer` is automatically created to run the command against.

== Options

.Options for the server run command
[%header,cols=2*]
|===
|Option
|Description

|--variable_name=_variable_value_
|Defines variables.
Include `--` in the command before you specify the option, as shown in the usage example.
{empty} +
{empty} +
Variables that are specified on the command line override all other sources of variables and can't be changed after the server starts.

|===


// Include description of server process
include::server-serverprocess.adoc[]

== Exit codes

The following exit codes are available for the `server run` command and the equivalent executable JAR file `ws-server.jar`:

.Exit codes for the server run command
[%header,cols="2,9"]
|===

|Code
|Explanation

|0
|This code indicates successful completion of the requested operation.

|1
|This code indicates invocation of a redundant operation, such as starting a started server or stopping a stopper server.
1 might also be returned if the JVM options that were used are not valid.

|2
|This code indicates that the server does not exist.

|3
|This code indicates an unsupported action was called on a running server. For example, the server is running when the package action is called.

|>=20
|Exit codes that are greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.
|===

== See also

* xref:command/server-start.adoc[server start]
* xref:command/server-stop.adoc[server stop]
