
== Examples

=== Bind constants into the default JNDI namespace

The following example shows how to bind constants into the JNDI namespace:

[source,xml]
----
<jndiEntry jndiName="schoolOfAthens/defaultAdminUserName" value="plato" />
----

In this example, `plato` is specified as the value for the `defaultAdminUserName` object in the `schoolOfAthens` data source. This constant value is  available to an application at run time through the JNDi namespace.

You can look up constants by calling the `lookup` method  in your application code, as shown in the following example:

[source,java]
----
String defaultAdminUserName = InitialContext.doLookup("schoolOfAthens/defaultAdminUserName");
----

In this example, the `dolookup()` method returns the value the `schoolOfAthens/defaultAdminUserNameo` object to the application. As specified in the previous example, that value is the string `plato`.

The type of the object is determined by interpreting the value that is stored in the `jndiEntry` element as a Java literal string or primitive data type. If the parsing fails, the exact value is provided as an unmodified string. For more information, see https://docs.oracle.com/javase/7/docs/api/javax/naming/InitialContext.html[the java.lang.Object class].


=== Bind URLs into the JDNI namespace

The following examples shows how to bind an instance of `java.net.URL` into the JNDI namespace:

[source,xml]
----
<jndiURLEntry jndiName="urls/openLiberty" value="https://www.openliberty.io" />
----

In this example, the namespace supplies the `https://www.openliberty.io` as the value for the `openLiberty` `java.net.URL` class.
