//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
:page-layout: server-command
:page-type: command
= server WinService command

Register, unregister, start, and stop the named Open Liberty server as a Windows service.

The Windows service name and Windows service display name is `serverName`. After you register, you can find and administer the Open Liberty server as a service by using `regedit` from the Windows Registry program. Entries for the service in the registry are in the following locations:

----
HKEY_LOCAL_MACHINE->SOFTWARE->Wow6432Node->Apache Software Foundation->Procrun 2.0->serverName
HKEY_LOCAL_MACHINE->SYSTEM->CurrentControlSet->services->serverName
----

== Usage examples

Register the `myserver` server as a Windows service:

----
server registerWinService serverName
----

Unregister the `myserver` server:

----
server unregisterWinService myserver
----

Start the `myserver` server as a Windows service:

----
server startWinService myserver
----

Stop the `myserver` server:

----
server stopWinService myserver
----

Start or stop a server by using the server script on Windows systems:

----
server.bat start serverName
server.bat stop serverName
----

== Syntax

Run the command from `path_to_liberty/bin`.

----
server registerWinService serverName
----

serverName::
The name of the server to run the command against. If no server is specified, a server called `defaultServer` is automatically created to run the command against.

== See also

* command:server-start[]
* command:server-run[]
* command:server-stop[]

//See also:

//* Equivalent command for Maven.
//* Equivalent command for Gradle.
//* Create a Liberty server.
//* Start a Liberty server in debug mode.

== Exit codes

The following exit codes are available for the `server start` command and the equivalent executable JAR file `ws-server.jar`:

0::
    OK. 0 indicates successful completion of the requested operation.
1::
    1 indicates invocation of a redundant operation, such as starting a started server or stopping a stopper server. 1 might also be returned if the JVM options that were used are not valid.
2::
    2 indicates that the server does not exist.
>=20::
    Exit codes greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.

// Include description of server process
include::server-serverprocess.adoc[]
