//
// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server status command

Checks to see whether the specified server is running.

== Usage examples

Determine whether the `myserver` server in running:

----
server status myserver
----

== Syntax

Run the command from the `path_to_liberty/bin` directory.

----
server status serverName
----

serverName::
The name of the server to run the command against.

== See also

* link:#server-dump.html[server dump]
* link:#server-javadump.html[server javadump]

== Exit codes

The following exit codes are available for the `server status` command and the equivalent executable JAR file `ws-server.jar`:

0::
    OK. 0 indicates successful completion of the requested operation.
1::
    1 indicates invocation of a redundant operation, such as starting a started server or stopping a stopper server. 1 might also be returned if the JVM options that were used are not valid.
5::
    5 indicates that the server status is unknown. For example, the `workarea` directory is missing or the Attach API fails to work.
>=20::
    Exit codes greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.

// Include description of server process
include::server-serverprocess.adoc[]
