//
// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
:page-layout: server-command
:page-type: command
= server version command

Displays the version information of the named server and the current Java runtime environment.

== Usage examples

Find out the version information of the `myserver` server:

----
server version myserver
----

== Syntax

Run the command from the `path_to_liberty/bin` directory.

----
server version serverName
----

serverName::
The name of the server to run the command against. If no server is specified, a server called `defaultServer` is automatically created to run the command against.

== See also

* link:#server-list.html[server list]

== Exit codes

The following exit codes are available for the `server version` command and the equivalent executable JAR file `ws-server.jar`:

0::
    OK. 0 indicates successful completion of the requested operation.
1::
    1 indicates that the JVM options that were used are not valid.
>=20::
    Exit codes greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.
