////
 Copyright (c) 2018 IBM Corporation and others.
 Licensed under Creative Commons Attribution-NoDerivatives
 4.0 International (CC BY-ND 4.0)
   https://creativecommons.org/licenses/by-nd/4.0/
 Contributors:
     IBM Corporation
////
:page-layout: server-command
:page-type: reference
== Server process properties

The following JVM options are added:

* `-javaagent:wlp/bin/tools/ws-javaagent.jar` is required for server capabilities such as trace and monitoring.
* `-Xshareclasses` and related options are on Eclipse Open J9 to enable the shared class cache.
* `-XX:MaxPermSize` is set on HotSpot Java SE 7 to increase the size of the permanent generation space.
* `-Djava.awt.headless=true` avoids java.awt.HeadlessException on all platforms and focus-stealing problems on Mac OS X.

//For more information about the `server.env` and `jvm.options` file, see Customizing the Liberty environment.

The `server` command sets the `umask` value to deny all permissions to `Other` users before the command runs the action.

The current working directory of the server process is set to the server output directory.

The server command creates a process ID (PID) file when you start the server and deletes the PID file when you stop the server.
