//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server create command

Creates an Open Liberty server.


== Syntax

Run the command from `path_to_liberty/bin`.

----
server create serverName
----

serverName::
A name for the server. If no server is specified, a server called `defaultServer` is automatically created.

Naming constraints:

* Use only Unicode alphanumeric (e.g. 0-9, a-z, A-Z), underscore (_), dash (-), plus (+), and period (.) characters.
* Do not begin the with a dash (-) or period (.).
* Be aware that your file system, operating system, or compressed file directory might impose more restrictions.

When the server is created successfully, you receive message: `Server server_name created`

A directory with the name of the new server is created under the `${wlp.user.dir}/servers` directory, containing the configuration of the new server. The HTTP port numbers for the new server are assigned to default values and are shown in the generated `server.xml` file to make it easy to edit them.

If the specified server exists, no server is created and you receive an exception message:
----
CWWKE0005E: The runtime environment could not be launched.
CWWKE0045E: It was not possible to create the server called server_name because
the server directory C:\wlp\usr\servers\server_name already exists.
----


== Usage

Create a server called `myserver`:

----
server create myserver
----

== See also

* link:server-start.html[server start]
* link:server-run.html[server run]

// Include server script exit codes
include::server-exitcodes.adoc[]

// Include description of server process
include::server-serverprocess.adoc[]



// NOTE: This article is based on the following KC articles:
//* https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_admin_script.html
//* https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_setup_new_server.html
