//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
// Example title: Creating a RESTful web service
:page-layout: server-command
:page-type: command
= server help command

Displays information about the `server` command, with details about its actions and options.

== Usage examples

To get help on the `server` command:

----
server help
----

To get help on a specific `server` command action, such as `create`:

----
server help create
----

== Syntax

Run the command from the `/wlp/bin` directory.

----
server help [option]
----

option::
One optional parameter.

== Option

[%header,cols=2*]
|===
|Option
|Description

|actionName
|Specifies a `server` command action to show only the help for the action.
|===

== See also

* link:server-list.html[server list]
* link:server-version.html[server version]

== Exit codes

The following exit codes are available for the `server help` command and the equivalent executable JAR file `ws-server.jar`:

0::
    OK. 0 indicates successful completion of the requested operation.
1::
    1 indicates that the JVM options that were used are not valid.
>=20::
    Exit codes greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.
