////
 Copyright (c) 2018 IBM Corporation and others.
 Licensed under Creative Commons Attribution-NoDerivatives
 4.0 International (CC BY-ND 4.0)
   https://creativecommons.org/licenses/by-nd/4.0/

 Contributors:
     IBM Corporation
////

== Server process

// NOTE: LC: Should this info be broken out for the different commands or is the majority relevant to all commands? (currently an include in all command topics)
// BB: As it stands now, it can remain it's own topic that other command topics can point to.

The server process is created by using the environment variables that are specified in the `server.env` file. The following JVM options are added by default:

* The `-javaagent:wlp/bin/tools/ws-javaagent.jar` option is required for trace, monitoring, incremental publishing of applications, and other server capabilities.
* The `-Xshareclasses` and related options enable the shared class cache on supported IBM J9 virtual machines.
* The cache directory is set to `WLP_OUTPUT_DIR/.classCache`.
* The `-XX:MaxPermSize` option increases the size of the permanent generation for HotSpot virtual machines before Java 8. You can set the `WLP_SKIP_MAXPERMSIZE` environment variable to `true` to avoid this default option, which avoids warnings such as:

    `Java HotSpot(TM) Client VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0`

* The `-Djava.awt.headless=true` option avoids `java.awt.HeadlessException` on all platforms and focus-stealing problems on Mac OS X.

You can use the `jvm.options` file to override these default JVM options or add more JVM options. 
//For more information about the `server.env` and `jvm.options` file, see Customizing the Liberty environment.

By default, the `server` command sets the `umask` value to deny all permissions to `Other` users before the command runs the action. You can set the `WLP_SKIP_UMASK` environment variable to `true` in the `server.env` file to prevent the server command from modifying the umask. If you set the `WLP_SKIP_UMASK` environment variable, the server uses the `umask` value from the underlying process of the operation.

The current working directory of the server process is set to the server output directory.

The server command creates a process ID (PID) file when you start the server and deletes the PID file when you stop the server. By default, the PID file is set to `WLP_OUTPUT_DIR/.pid/serverName.pid`. The absolute path of the PID file can be changed by setting the `PID_FILE` environment variable, or the absolute path of the PID directory can be changed by setting the `PID_DIR` environment variable.

The standard output and error from the server process is output to the foreground console for the `server run` and `server debug` commands and is redirected to the `WLP_OUTPUT_DIR/serverName/logs/console.log` file by default when you use the start action. The log name can be changed by setting the `LOG_FILE` environment variable, and the log directory can be changed by setting the `LOG_DIR` environment variable. 
//For more information about the logging configuration, see Logging and Trace.

The `server stop` command prevents new application requests from entering the server, which allows existing requests some time to complete. After that time, the remaining server components are stopped and the server process exits. Application requests that do not complete in the allowed time fail but their exact behavior depends on their activity when the server components are stopped.
