//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server list command

Lists all the defined application servers in the Open Liberty installation.

== Usage examples

To list the servers in the Open Liberty installation:

----
server list
----

//* See also:
//* Stop a Liberty server.
//* Check the version of a Liberty server.
//* Pause a Liberty server.

== Syntax

Run the command from the `/wlp/bin` directory. The result lists the defined servers in the user directory, `/wlp/usr`.

----
server list
----

== See also

* link:server-version.html[server version]

== Exit codes

The following exit codes are available for the `server list` command and the equivalent executable JAR file `ws-server.jar`:

0::
    OK. 0 indicates successful completion of the requested operation.
1::
    1 indicates that the JVM options used are not valid.
>=20::
    Exit codes greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.
