////
 Copyright (c) 2018 IBM Corporation and others.
 Licensed under Creative Commons Attribution-NoDerivatives
 4.0 International (CC BY-ND 4.0)
   https://creativecommons.org/licenses/by-nd/4.0/

 Contributors:
     IBM Corporation
////
:page-layout: server-command
:page-type: reference
== Exit codes

The following exit codes are available for the `server` command and the equivalent executable JAR file ws-server.jar:

0::
    OK. 0 indicates successful completion of the requested operation. For server status, 0 indicates that the server is running.
1::
    For server status, 1 indicates that the server is not running. For other operations, it indicates invocation of a redundant operation. For example, starting a started server or stopping a stopped server. This code might also be returned by JVM if invalid Java options are used. 
2::
    The server does not exist.
3::
    An unsupported action was called on a running server. For example, the server is running when the package action is called.
4::
    An unsupported action was called on a stopped server. For example, the server is not running when the dump action is called.
5::
    Unknown server status. For example, the workarea directory is missing, or the Attach API fails to work.
>=20::
    Return codes greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error. 
