//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server resume command

Resumes all or specific inbound work for an Open Liberty server.

By pausing and resuming inbound work, you can isolate resources for auditing or debugging purposes without having to stop the server. You can resume all components that were paused or specific components that were paused.

* link:#server-pause.html[Pause all or specific inbound work for an Open Liberty server.]

== Usage examples

You can resume all components that were paused or specific components that were paused.

Resume all components on the `myserver` server:

----
server resume myserver
----

Resume two specific components on the `myserver` server, where the values of `target1` and `target2` are components that can be paused for each supported protocol:

----
server resume myserver --target=target1,target2
----

Resume the `db1HttpEndpoint` and `db2HttpEndpoint` HTTP endpoints on the `myserver` server:

----
server resume myserver --target=db1HttpEndpoint,db2HttpEndpoint
----

Resume the `Bean` MDB message endpoint on the `myserver` server:

----
server resume myserver --target=MDBApplication#MDBModule.jar#Bean
----

Resume the `db1HttpEndpoint` HTTP endpoint and the `Bean` MDB message endpoint on the `myserver` server:

----
server resume myserver --target=db1HttpEndpoint,MDBApplication#MDBModule.jar#Bean
----

== Syntax

Run the command from `path_to_liberty/bin`.

----
server resume serverName [options]
----

serverName::
The name of the server to run the command against. If no server is specified, a server called `defaultServer` is automatically created to run the command against.

options::
One or more optional parameters. If you do not specify any endpoints, the entire server is resumed.

== Options

[%header,cols=2*]
|===
|Option
|Description

|--target=http_endpoint,http_endpoint,...
|A comma-delimited list of HTTP endpoints to be resumed. Provide the ID of each HTTP endpoint as specified in the server configuration. For example, in the following configuration, you can resume the `db1HttpEndpoint` and `db2HttpEndpoint` endpoints:

`<httpEndpoint id="db1HttpEndpoint" host="\*" httpPort="8801" httpsPort="8811"/>`

`<httpEndpoint id="db2HttpEndpoint" host="*" httpPort="8802" httpsPort="8812"/>`

|--target=message_endpoint,message_endpoint,...

|A comma-delimited list of HTTP endpoints to be resumed. Provide the activation name of each MDB message endpoint in the format: `ApplicationName#ModuleName#BeanName`.
|===

== See also

* link:#server-debug.html[server debug]
* link:#server-pause.html[server pause]

== Exit codes

The following exit codes are available for the `server resume` command and the equivalent executable JAR file `ws-server.jar`:

0::
    OK. 0 indicates successful completion of the requested operation.
1::
    1 indicates that the JVM options that were used are not valid.
2::
    2 indicates that the server does not exist.
>=20::
    Exit codes greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.
