//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
// Example title: Creating a RESTful web service
:page-layout: server-command
:page-type: command
= server javadump command

Creates a snapshot of the JVM status of a server and saves the result into an archive file for further tuning and diagnosis.

The command is useful for diagnosing problems at the JVM level, such as hung threads, deadlocks, excessive processing, excessive memory consumption, memory leaks, and defects in the virtual machine. The server must be running for the command to capture results.

Each dump type creates a file, but not all dump types are supported by all virtual machines. The default directory for dump files is `${server.output.dir}`. To set a different default directory, you must use an IBM JVM and set the following environment variables:

* `IBM_HEAPDUMPDIR`
* `IBM_COREDIR`
* `IBM_JAVACOREDIR`

The resulting file is created by using UTF-8 encoding for entry names, so the tool that you use to open the file must be able to use UTF-8 encoding for entry names. The `jar` command in a Java SDK uses this format.


== Usage examples

To capture the JVM status of the `myserver` server:
----
server javadump myserver
----

To capture the JVM status of `myserver` and add a heap dump:
----
server javadump myserver --include=heap
----

To capture the JVM status of `myserver` and add heap and system dumps:
----
server javadump myserver --include=heap,system
----


== Syntax

Run the command from the `/wlp/bin` directory.

----
server javadump serverName [options]
----

serverName::
The name of the server to diagnose. If the named server is not running or does not exist, the command fails. If no server name is specified, the command uses defaultServer.

options::
One or more optional parameters.


== Options

[%header,cols=2*]
|===
|Option
|Description

|--include=diagnose_option,diagnose_option,...
|Specifies the type of diagnostic information to capture. The value of `--include` is a comma-delimited list, which can contain one or more of the following values:

* `heap` is used to help diagnose excessive memory consumption and memory leaks. The dump shows live objects in the memory and references between them. On IBM J9 virtual machines, the resulting file is named `heapdump.date.time.processID.sequenceNumber.phd`. On HotSpot virtual machines, the resulting file is named `java.date.time.processID.sequenceNumber.hprof`.

* `system` is also used to help diagnose excessive memory consumption and memory leaks, but a system dump also helps find defects in the virtual machine. System dumps are only supported on IBM J9 virtual machines. The resulting file is named `core.date.time.processID.sequenceNumber.dmp`.

|===

== See also

* link:server-list.adoc[server list]
* link:server-dump.adoc[server dump]

// Include server script exit codes
include::server-exitcodes.adoc[]

// Include description of server process
include::server-serverprocess.adoc[]


// From
// https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_command_server.html
// https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_setup_dump_server.html
