//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server start command

Starts the named Open Liberty server as a background process.

The standard output and error from the server process are redirected to the `WLP_OUTPUT_DIR/serverName/logs/console.log` file.

//See also:

//* Equivalent command for Maven.
//* Equivalent command for Gradle.
//* Start a Liberty server in the foreground.
//* Stop a Liberty server.
//* Create a Liberty server.
//* Start a Liberty server in debug mode.

== Usage examples

Start the `myserver` server in the background:

----
server start myserver
----

== Syntax

Run the command from `path_to_liberty/bin`.

----
server start serverName
----

serverName::
The name of the server to run the command against. If no server is specified, a server called `defaultServer` is automatically created to run the command against.

== See also

* link:server-run.html[server run]
* link:server-stop.html[server stop]

== Exit codes

The following exit codes are available for the `server start` command and the equivalent executable JAR file `ws-server.jar`:

0::
    OK. 0 indicates successful completion of the requested operation.
1::
    1 indicates invocation of a redundant operation, such as starting a started server or stopping a stopper server. 1 might also be returned if the JVM options that were used are not valid.
2::
    2 indicates that the server does not exist.
>=20::
    Exit codes greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.


// Include description of server process
include::server-serverprocess.adoc[]


// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
