//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server stop command

Stops the named Open Liberty server.

This command triggers the server to enter a quiesce phase before stopping. The quiesce phase prevents new application requests from entering the server and allows existing requests time to complete. After that time, the server shuts down and the server process exits.

//* Equivalent command for Maven.
//* Equivalent command for Gradle.
* link:#server-run.html[Start an Open Liberty server in the foreground.]
* link:#server-start.html[Start an Open Liberty server in the background.]

== Usage examples

Stop the `myserver` server with the quiesce stage:

----
server stop myserver
----

Force the `myserver` server to stop without the quiesce stage:

----
server stop myserver --force
----

== Syntax

Run the command from `path_to_liberty/bin`.

----
server stop serverName [options]
----

serverName::
The name of the server to run the command against. If no server is specified, the action is performed against the default server instance, `defaultServer`, if it exists.

options::
One or more optional parameters.

== Options

[%header,cols=2*]
|===
|Option
|Description

|--force
|Skips the quiesce stage before the server is shut down.
{empty} +
{empty} +
Normal server stop includes a quiesce stage before the server is shut down. The quiesce stage, a period of 30 seconds, allows services to perform pre-shutdown work; for example, inbound listeners are stopped but existing requests are allowed to complete.
{empty} +
{empty} +
The `--force` option has no effect if server stop was already invoked. If you use the `--force` option, you might see unexpected exceptions in the `messages.log` file that occur after the `server stop` command was received by the server.
|===

== See also

* link:#server-run.html[server run]
* link:#server-start.html[server start]

== Exit codes

The following exit codes are available for the `server stop` command and the equivalent executable JAR file `ws-server.jar`:

0::
    OK. 0 indicates successful completion of the requested operation.
1::
    1 indicates invocation of a redundant operation, such as starting a started server or stopping a stopper server. 1 might also be returned if the JVM options that were used are not valid.
2::
    2 indicates that the server does not exist.
>=20::
    Exit codes greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.
