// INSTRUCTION: Please remove all comments that start INSTRUCTION prior to commit. Most comments should be removed, although not the copyright.
// INSTRUCTION: The copyright statement must appear at the top of the file
//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
// Example title: Creating a RESTful web service
:page-layout: server-command
:page-type: overview
= Server commands overview 

// Start the introduction with "You'll explore how to..." or something similarly catchy:
Quickly interact with the Open Liberty server to complete actions like creating, starting, and stopping the server. Use the server commands for these basic operations and more.

// Write no more than two sentences, or about fifty words with meaningful information on what the user can accomplish with this guide.
// Do not start the introduction with "This guide...".

// See the REST guide at as an exemplar guide.
// https://openliberty.io/guides/rest-intro.html
// https://github.com/OpenLiberty/guide-rest-intro


== Common server commands and usage examples

// You can download released versions and nightly build artifacts of the Open Liberty server from:  https://www.openliberty.io/downloads/. Download to a directory of your choosing and then unzip. On Linux based systems you can use the following command:
// ----
// unzip javaee8.zip
// ----

=== Create a server

Run the link:server-create.html[server create] command from `_<path_to_liberty>_/bin` to create a server. 

----
server create myserver
----

=== Start the server

Run the link:server-start.html[server start] command from `_<path_to_liberty>_/bin` to start the server.

----
server start myserver
----

=== Stop the server

Run the link:server-stop.html[server stop] command from `_<path_to_liberty>_/bin`.

----
server stop myserver
----

== More server commands and usage examples

=== Debug the server

Run the link:server-debug.html[server debug] command from `_<path_to_liberty>_/bin`.

----
server debug myserver
----

=== Create and save a snapshot of the server

Run the link:server-dump.html[server dump] command from `_<path_to_liberty>_/bin` to create a dump file of thread information from the `myserver` server in a ZIP archive called `myserver.zip`.

----
server dump myserver --archive="myserver.zip" --include=thread
----

=== Get information about available server command actions and options

Run the link:server-help.html[server help] command to get help with the server commands.

----
server help 
----

=== Create a snapshot and save the JVM status of a server

Run the link:server-javadump.html[server javadump] command to capture the JVM status of the myserver server:

----
server javadump myserver 
----

=== List all Open Liberty server instances

Run the link:server-list.html[server list] command to list all the defined application servers in the Open Liberty installation:

----
server list
----

=== Package the server

Run the link:server-package.html[server package] command to package a server, its resources, and applications in a ZIP file that you can store, distribute, or deploy to a different location.

----
server package myserver --include=all
----

=== Pause all or specific inbound work 

Run the link:server-pause.html[server pause] command to pause all pausable components on the myserver server:

----
server pause myserver
----

=== Resume all or specific inbound work 

Run the link:server-resume.html[server resume] command to resume all paused components on the myserver server:

----
server resume myserver
----

=== Run a server in the foreground

Run the link:server-run.html[server resume] command to start myserver as a foreground process:

----
server run myserver
----
