//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server create command

Creates an Open Liberty server.

== Usage examples

Create a server called `myserver`:

----
server create myserver
----

== Syntax

Run the command from `path_to_liberty/bin`.

----
server create serverName
----

serverName::
A name for the server. If no server is specified, a server called `defaultServer` is automatically created.

Naming constraints:

* Use only Unicode alphanumeric (e.g. 0-9, a-z, A-Z), underscore (_), dash (-), plus (+), and period (.) characters.
* Do not begin the with a dash (-) or period (.).
* Be aware that your file system, operating system, or compressed file directory might impose more restrictions.

When the server is created successfully, you receive the message: `Server server_name created`.

A directory with the name of the new server is created under the `${wlp.user.dir}/servers` directory, containing the configuration of the new server. The HTTP port numbers for the new server are assigned to default values and are shown in the generated `server.xml` file to make it easy to edit them.

If the specified server exists, then no server is created and you receive an exception message:

----
CWWKE0005E: The runtime environment could not be launched.
CWWKE0045E: It was not possible to create the server called server_name because
the server directory C:\wlp\usr\servers\server_name already exists.
----

== See also

* link:server-run.html[server run]
* link:server-start.html[server start]

== Exit codes

The following exit codes are available for the `server create` command and the equivalent executable JAR file `ws-server.jar`:

0::
    OK. 0 indicates successful completion of the requested operation.
1::
    1 indicates that the JVM options that were used are not valid.
>=20::
    Exit codes greater than or equal to 20 indicate that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.
