////
 Copyright (c) 2018 IBM Corporation and others.
 Licensed under Creative Commons Attribution-NoDerivatives
 4.0 International (CC BY-ND 4.0)
   https://creativecommons.org/licenses/by-nd/4.0/

 Contributors:
     IBM Corporation
////

//seo_title: Server configuration (server.xml) - OpenLiberty.io

== Server configuration (server.xml)
:icons: font

Liberty is configured by exception. The runtime environment operates from a set of built-in configuration default settings, and you only need to specify configuration that overrides those default settings. You do this by editing either the `server.xml` file or another XML file that is included in `server.xml` at run time.

The following example shows the `server.xml` that is created by default for a new server:

[source,xml]
----

<?xml version="1.0" encoding="UTF-8"?>
<server description="new server">

    <!-- Enable features -->
    <featureManager> <!--1-->
        <feature>jsp-2.3</feature>
    </featureManager>

    <!-- To access this server from a remote client add a host attribute to the following element, e.g. host="*" -->
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" /> <!--2-->

    <!-- Automatically expand WAR files and EAR files -->
    <applicationManager autoExpand="true"/>  <!--3-->
</server>

----
<1> Contains all the Liberty features needed to run your application. Add features here as required for your application. Dependencies of these features are detected and loaded automatically by Liberty; you do not need to specify them here.
<2> Specifies the port numbers of the default HTTP endpoint for applications running on this server. Set the `host` attribute if running in a container etc.
<3> .....

NOTE: LC: Need other descriptions. And what are the other (if any) common sections you might include in your server.xml?

Add and remove features from server.xml to control the pieces of runtime environment that are loaded into a server. For a full list of features that you can include, see [Liberty features].

For a full list of settings you can configure in `server.xml`, see https://openliberty.io/docs/ref/config/[server.xml elements].

=== server.xml includes

You can separate out parts of the `server.xml` into other XML files that are included in the `server.xml`. 