//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: server-command
:page-type: command
= server pause command

Pauses all or specific inbound work for an Open Liberty server.

By pausing and resuming inbound work, you can isolate resources for auditing or debugging without having to stop the server. You can pause all components or specific components:

* Pause HTTP endpoints to isolate one or more resources associated with an HTTP endpoint; for example, a database.
* Pause message-driven bean (MDB) message endpoints to prevent the endpoints from receiving messages.

== Usage

To pause all pausable components on the `myserver` server:
----
server pause myserver
----

To pause the `db1HttpEndpoint` and `db2HttpEndpoint` HTTP endpoints on `myserver`:
----
server pause myserver --target=db1HttpEndpoint,db2HttpEndpoint
----

To pause the `Bean` MDB message endpoint on `myserver`:
----
server pause myserver --target=MDBApplication#MDBModule.jar#Bean
----

== Syntax

Run the command from the `/wlp/bin` directory.

----
server pause serverName [options]
----

serverName::
The name of the server with components you want to pause. If the named server is not running or does not exist, the command fails. If no server name is specified, the command uses defaultServer.
options::
One or more optional parameters. If you do not specify any options, all pausable components on the server are paused.


== Options

[%header,cols=2*]
|===
|Option
|Description

|--target=http_endpoint,http_endpoint,...
|A comma-delimited list of HTTP endpoints to pause. Provide the ID of each HTTP endpoint as specified in the server configuration. For example, the following configuration shows two endpoint IDs, `db1HttpEndpoint` and `db2HttpEndpoint`, that you can specify for the `--target` option:

`<httpEndpoint id="defaultHttpEndpoint" host="\*" httpPort="8800" httpsPort="8810"/>`

`<httpEndpoint id="db1HttpEndpoint" host="*" httpPort="8801" httpsPort="8811"/>`

`<httpEndpoint id="db2HttpEndpoint" host="*" httpPort="8802" httpsPort="8812"/>`

|--target=message_endpoint,message_endpoint,...

|A comma-delimited list of message endpoints to pause. Provide the activation name of each MDB message endpoint in the format: `ApplicationName#ModuleName#BeanName`.

|===

NOTE: LC: Can the types be combined in a single command? If so, we should mention it in the descriptions above and give an example in Usage below.



== See also

* link:server-resume.adoc[server resume]
* link:server-debug.adoc[server debug]

// Include server script exit codes
include::server-exitcodes.adoc[]

// Include description of server process
include::server-serverprocess.adoc[]



//NOTE: (LC) add info from:  https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_PauseResume_cmd.html
