//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
// Example title: Creating a RESTful web service
:page-layout: server-command
:page-type: overview
= Server commands overview

Quickly interact with the Open Liberty server to complete actions like creating, starting, and stopping the server. Use the server commands for these basic operations and more.


== Common server commands and usage examples

You can download released versions and nightly build artifacts of the Open Liberty server from:  https://www.openliberty.io/downloads/. Download to a directory of your choosing and then unzip. On Linux based systems you can use the following command:
----
unzip javaee8.zip
----

=== Create a server

Run the link:server-create.adoc[server create] command from `_<path_to_liberty>_/bin` to create a server.

----
server create myserver
----

=== Start the server

Run the link:server-start.adoc[server start] command from `_<path_to_liberty>_/bin` to start the server.

----
server start myserver
----

=== Stop the server

Run the link:server-stop.adoc[server stop] command from `_<path_to_liberty>_/bin`.

----
server stop myserver
----

== More server commands and usage examples

=== Debug the server

Run the link:server-debug.adoc[server debug] command from `_<path_to_liberty>_/bin`.

----
server debug myserver
----

=== Create and save a snapshot of the server

Run the link:server-dump.adoc[server dump] command from `_<path_to_liberty>_/bin` to create a dump file of thread information from the `myserver` server in a ZIP archive called `myserver.zip`.

----
server dump myserver --archive="myserver.zip" --include=thread
----

=== Get information about available server command actions and options

Run the link:server-help.adoc[server help] command from `_<path_to_liberty>_/bin`.

----
server help
----
