//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation

= server start command

Starts the named Open Liberty server as a Windows service (Windows only).


== Syntax

Run the command from the `path_to_liberty/bin` directory.

----
server registerWinService serverName
----

serverName::
The name of the server to run the command against. If no server is specified, a server called `defaultServer` is automatically created to run the command against.

The Windows service name and Windows service display name is `serverName`. After you register, you can find and administer the Open Liberty server as a service by using `regedit` from the Windows Registry program. Entries for the service in the registry are in the following locations:

----
HKEY_LOCAL_MACHINE->SOFTWARE->Wow6432Node->Apache Software Foundation->Procrun 2.0->serverName
HKEY_LOCAL_MACHINE->SYSTEM->CurrentControlSet->services->serverName
----


== Options

There are no optional parameters for this command.

== Usage

Start `myserver` server in the background:

----
server start myserver
----

== Usage examples

To start or stop a server by using the server script on Windows systems:

----
server.bat start serverName
server.bat stop serverName
----


== See also

link:server-stop.html[server stop]
link:server-run.html[server run]

//See also:

//* Equivalent command for Maven.
//* Equivalent command for Gradle.
//* Start a Liberty server in the foreground.
//* Stop a Liberty server.
//* Create a Liberty server.
//* Start a Liberty server in debug mode.


// Include server script exit codes
include::server-exitcodes.adoc[]

// Include description of server process
include::server-serverprocess.adoc[]



// From KC topic: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_setup_new_server_winserv.html
