== Change the token expiration time

With the `jwtSso` feature, you can use a JSON Web Token (JWT) as a Single-Sign-On (SSO) cookie.
The following example shows how you can configure the `jwtSso` feature to change the token expiration time:

[source, xml]
----
<jwtSso cookieName="myjwt" jwtBuilderRef="myBuilder"/>

 <jwtBuilder id="myBuilder" expiresInSeconds="1800"/>
----

The `jwtBuilderRef` attribute refers to the `jwtBuilder` element `myBuilder`.
The `id` attribute for the `jwtBuilder` element that is named `myBuilder` identifies the JWT builder.
The `expiresInSeconds` attribute indicates the token expiration time that is set to 1800 seconds for a newly generated token.

== Disable JWT cookies

By default, when a client is authenticated with Open Liberty through the JWT SSO feature, a JWT cookie is created and sent to the HTTP servlet.
In the following example, the JWT cookies are disabled by specifying the `disableJwtCookie` attribute with a value of `true` in the `server.xml` file.
You can use a mechanism other than JWT cookies for authentication, as the JWT cookies are disabled in this example:

[source, xml]
----
<jwtSso id="sample" disableJwtCookie="true" />
----

==  Configure authentication filter

You can configure an authentication filter to secure requests to access protected resources that are used with JWT SSO for authentication.
The `jwtSso` feature supports an authentication filter.
For more information on configuring the authentication filter, see xref:authentication-filters.adoc[Authentication filters].

[source, xml]
----
<jwtSso cookieName="myjwt" jwtBuilderRef="myBuilder" authFilterRef="myAuthFilter"/>

<authFilter id="myAuthFilter">
         <requestUrl id="myRequestUrl" urlPattern="/SimpleServlet" matchType="contains"/>
</authFilter>
----

In the example, request URLs that contain the `/SimpleServlet` pattern are authenticated by using JWT SSO authentication. 
If the `jwtSso` feature is enabled but does not include the `authFilterRef` attribute, all requests to access the protected resources that have an LTPA cookie are used for the JWT SSO authentication.
