== Examples

With the JSON Web Token Single Sign-On feature, you can configure JSON Web Tokens (JWT) as an authentication mechanism for single-sign-on (SSO) authentication.

The JWT SSO cookie is configured by enabling the JSON Web Token Single Sign-On feature.
When a user is authenticated, Open Liberty creates a signed JWT as an SSO cookie and returns it to the browser.
The browser can then include the JWT cookie in subsequent requests to the Open Liberty server.

=== Change the token expiration time

To customize the expiration time of a JWT, configure the `jwtBuilder` element, as shown in the following example:

[source, xml]
----
<jwtSso cookieName="myjwt" jwtBuilderRef="myBuilder"/>

 <jwtBuilder id="myBuilder" expiresInSeconds="1800"/>
----

The `jwtBuilderRef` attribute refers to the `jwtBuilder` element with the myBuilder ID.
The `id` attribute for the `jwtBuilder` element that is named `myBuilder` identifies the JWT builder.
The `expiresInSeconds` attribute indicates the token expiration time that is set to 1800 seconds for a newly generated token.

=== Disable JWT cookies

By default, when a client is authenticated with Open Liberty through the JWT SSO feature, a JWT cookie is created and sent to the HTTP servlet.
In the following example, the JWT cookies are disabled by specifying the `disableJwtCookie` attribute with a value of `true` in the `server.xml` file.
You can use a mechanism other than JWT cookies for authentication, as the JWT cookies are disabled in this example:

[source, xml]
----
<jwtSso id="sample" disableJwtCookie="true" />
----

===  Configure an authentication filter to provide access for protected resources with JWT SSO authentication

You can configure an authentication filter to specify whether certain requests for protected resources are authenticated with JWT SSO.
If the request meets the criteria that are specified in the authentication filter, then the request can authenticate with JWT to access the protected resource.
Conversely, if the request does not meet the criteria that are configured in the JWT SSO authentication filter, then the user is prompted to provide login credentials.
For more information, see xref:ROOT:authentication-filters.adoc[Authentication filters].

[source, xml]
----
<jwtSso cookieName="myjwt" jwtBuilderRef="myBuilder" authFilterRef="myAuthFilter"/>

<authFilter id="myAuthFilter">
         <requestUrl id="myRequestUrl" urlPattern="/SimpleServlet" matchType="contains"/>
</authFilter>
----

In the example, request URLs that contain the `/SimpleServlet` pattern are authenticated by using JWT SSO authentication.
If the `jwtSso` feature is enabled but `jwtSso` element does not include the `authFilterRef` attribute, all requests to access the protected resources that have a JWT cookie are used for the JWT SSO authentication.

=== Change JWT validation criteria

You can specify the `mpJwt` element to configure how incoming JWTs are validated and consumed by the server.
Only one `mpJwt` element can exist in the `server.xml` file.
In the following example, the `jwtBuilder` element specifies the issuer claim for JWTs that the server creates.
The `mpJwt` element specifies the issuer claim and key alias for incoming JWTs that the server receives:

[source, xml]
----
<jwtSso includeLtpaCookie="true" jwtBuilderRef="myBuilder">
<jwtBuilder id="myBuilder" issuer="http://server.example.com" />
<mpJwt id="myMpJwt" issuer="http://server.example.com"
keyName="myJwtSigner"/>
----

=== Use the JSON Web Key (JWK) endpoint to validate JWTs

The JWTs created by Open Liberty are signed by the issuer and verified by the consumer.
The consumer that uses the public key of the issuer later verifies the signature.
If you use multiple servers, you must store the public key of the issuer in the `truststore` file of the consumer.
Alternatively, you can also retrieve the key from the JWK endpoint of the issuer.

The default JWK endpoint is `http(s)://<host>:<port>/jwt/ibm/api/defaultJWT/jwk`.

To use a JWK endpoint for consuming JWTs, add the jwksUri attribute to the mpJwt configuration element:

[source, xml]
----
<mpJwt id="myMpJwt" jwksUri="https://localhost:19443/jwt/ibm/api/defaultJWT/jwk" />
----

To use the JWK endpoint for consuming JWTs, add the `jwksUri` attribute to the `mpJwt` configuration element.

[source, xml]
----
<mpJwt id="myMpJwt" jwksUri="https://localhost:19443/jwt/ibm/api/defaultJWT/jwk" />
----

If you specified a different builder, its JWK endpoint is `http(s)://<host>:<port>/jwt/ibm/api/(builderId)/jwk`.
In the example, the JWK endpoint specifies the JWT builder with the ID `myBuilder`.

[source, xml]
----
<jwtSso jwtBuilderRef="myBuilder"/> <jwtBuilder id="myBuilder" />
----
