== Examples

=== Configure MicroProfile JWT

The following example shows authentication with a JSON Web Token (JWT).
The `mpJwt` element defines the configuration to process the inbound JSON Web Tokens.
The `jwksUri` attribute points the `mpjwt` element towards the public key `https://localhost:19443/jwt/ibm/api/myBuilder/jwk`, to validate the JSON Web Token.
The `keyStore` element defines the key and trust store where the public key is stored.
The `keyStore` element validates the JSON Web Token when the JSON Web Key Set (JWKS) is not used:

[source,xml]
----
    <mpJwt id="mympjwt" issuer="https://example.com"
        jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk"/>

    <keyStore id="defaultKeyStore" password="keyspass"/>
----

=== Configure authentication filter to login with MicroProfile JWT

You can use an authentication filter to protect a subset of applications, URLs, or IP addresses,.
The security configuration works when the conditions in the filter are met.
In the following example, any requests to the `myApp` application are authenticated with the `mpJwt` feature.
The `authFilterRef` attribute  that is named `myAuthFilter` filters the login requests to the `myApp` application:

[source,xml]
----
<mpjwt authFilterRef="authFilter1" />
<authFilter id="myAuthFilter">
         <webApp id="myWebApp"
         name="myApp"
         matchType="contains"/>
</authFilter>
----

=== Import a truststore to verify a MicroProfile JWT

You can configure a truststore to verify JSON Web Tokens. The default keystore for MicroProfile does not contain the root certificates that are used to verify the authentication credentials that are stored in JSON Web Tokens. To verify JSON Web Tokens, you can import the default Java truststore as shown in the following example:

[source,xml]
----
<ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" trustStoreRef="defaultTrustStore" />
<keyStore id="defaultTrustStore" location="${javaKeystoreLocation}" type="JKS" password="changeit" />
<mpJwt id="mympjwt" issuer="https://example.com"
   jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk"/>
----

The `id` attribute in the `keyStore` element specifies the `“defaultTrustStore”` value to configure a truststore within the keystore.  A truststore contains the certificates that are used to validate the requests that are sent to applications with JSON Web Tokens. The `ssl` element is used to specify how the application validates the SSL connection to a server. Within the `ssl` element, the `id=defaultSSLconfig`  attribute sets the SSL configuration as the default SSL configuration for the server that the application connects to. The `trustStoreRef=“defaultTrustStore”` attribute configures the `ssl` element to reference the truststore so that the application recognizes the truststore when it attempts to connect to the server. The `jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk”` attribute specifies the JWK endpoint URL that the server uses to obtain the public keys from to verify the JWT.

=== Configure restriction of MicroProfile JWT authentication

By default, if the MicroProfile JWT feature is configured, all authorized requests from applications must include a valid JSON Web Token in the HTTP header of the API. To modify the default behavior to require JSON Web Tokens in only some applications, you can add the `ignoreApplicationAuthMethod=“false”` attribute to the `mpJwt` element as shown in the following example:

[source,xml]
----
<mpJwt ignoreApplicationAuthMethod=“false”/>
----

After you modify the authorization behavior, you can use either of two options to configure applications to use MicroProfile JWT as a login method. In the API, you can add an `@LoginConfig` annotation that contains the `authMethod = "MP-JWT"` attribute to specify MicroProfile JWT as the authentication method as shown in the following example:

[source,java]
----
@LoginConfig(authMethod = "MP-JWT", realmName = "MP-JWT")
----

You can also add `MP-JWT` to the `auth-method` element of the `web.xml` file to specify MicroProfile JWT as the authentication method in the `login-config` element as shown in the following example:

[source,xml]
----
<login-config> <auth-method>MP-JWT</auth-method> <realm-name>MP-JWT</realm-name></login-config>
----

=== Define role mapping for MicroProfile JWT

By default, JSON Web Tokens use the `upn` claim as the principal name and unique security name of the user. JSON Web Tokens also use the `groups` claim as the group name for security role mapping. To change the default mapping, you can use the `userNameAttribute` attribute to choose a claim for the user principal. You can also use the `groupNameAttribute` attribute to choose a claim for the group name as shown in the following example:

[source,xml]
----
<mpJwt  userNameAttribute="customclaim" groupNameAttribute="customclaim"/>
----

=== Validate MicroProfile JWT claims with the user registry

By default, JSON Web Tokens authenticate user claims without validation from the user registry. To modify this behavior, you can add the `mapToUserRegistry="true"` attribute to the `mpJwt` element to as shown in the following example:

[source,xml]
----
<mpJwt mapToUserRegistry="true"/>
----

The `mapToUserRegistry="true"` attribute forces JSON Web Tokens to validate user claims with the user registry.
