== Examples

=== Basic configuration to implement MicroProfile JWT

The following example shows that the service requires requests to be authenticated by using JWTs.
The `mpJwt` element defines configuration for processing the inbound JWT tokens.
The `jwksUri` attribute tells the `mpjwt` element where to obtain the public key from to validate the JWT.
The `keyStore` element defines the key and truststore where the public key is held to validate the JWT, when JSON Web Key Sets(JWKS) is not used:

[source,xml]
----
    <mpJwt id="mympjwt" issuer="https://example.com"
        jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk"/>

    <keyStore id="defaultKeyStore" password="keyspass"/>
----

=== Specify login with MicroProfile JWT for only a subset of applications, URLs, browsers, or IP addresses

To protect only a subset of applications, URLs, or IP addresses, use an authentication filter.
The security configuration takes effect only when the conditions in the filter are met.
In the following example, requests to the `myApp` application are authorized by using JWT:

[source,xml]
----
<mp-jwt authFilterRef="authFilter1" />
<authFilter id="myAuthFilter">
         <webApp id="myWebApp"
         name="myApp"
         matchType="contains"/>
</authFilter>
----
