== Examples

=== Basic configuration to implement MicroProfile JWT

The following example shows that the service needs the requests authentication with JWTs.
The `mpJwt` element defines configuration to process the inbound JWT tokens.
The `jwksUri` attribute tells the `mpjwt` element from where to obtain the public key to validate the JWT.
The `keyStore` element defines the key and truststore where the public key is held to validate the JWT when JSON Web Key Sets(JWKS) is not used:

[source,xml]
----
    <mpJwt id="mympjwt" issuer="https://example.com"
        jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk"/>

    <keyStore id="defaultKeyStore" password="keyspass"/>
----

=== Specify login with MicroProfile JWT for a subset of applications, URLs, browsers, or IP addresses

Use an authentication filter to protect a subset of applications, URLs, or IP addresses,.
The security configuration takes effect when the conditions in the filter are met.
In the following example, requests to the `myApp` application are authorized with JWT:

[source,xml]
----
<mp-jwt authFilterRef="authFilter1" />
<authFilter id="myAuthFilter">
         <webApp id="myWebApp"
         name="myApp"
         matchType="contains"/>
</authFilter>
----
