== Examples

=== Basic configuration to implement MicroProfile JWT

The following example shows that the service needs request authentication with a JSON Web Token (JWT).
The `mpJwt` element defines the configuration to process the inbound JSON Web Tokens.
The `jwksUri` attribute points the `mpjwt` element towards the public key to validate the JSON Web Token.
The `keyStore` element defines the key and truststore where the public key is stored, to validate the JSON Web Token when the JSON Web Key Sets(JWKS) are not used:

[source,xml]
----
    <mpJwt id="mympjwt" issuer="https://example.com"
        jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk"/>

    <keyStore id="defaultKeyStore" password="keyspass"/>
----

=== Specify login with MicroProfile JWT for a subset of applications, URLs, browsers, or IP addresses

You can use an authentication filter to protect a subset of applications, URLs, or IP addresses,.
The security configuration works when the conditions in the filter are met.
In the following example, requests to the `myApp` application are authorized with a JSON Web Token:

[source,xml]
----
<mpjwt authFilterRef="authFilter1" />
<authFilter id="myAuthFilter">
         <webApp id="myWebApp"
         name="myApp"
         matchType="contains"/>
</authFilter>
----

=== Import a Truststore to verify a MicroProfile JWT

You can configure a Truststore to verify JSON Web Tokens. The default Keystore for MicroProfile does not contain the root certificates that are used to verify the authentication credentials that are stored in JSON Web Tokens. To verify JSON Web Tokens, you can import the default Java Truststore as shown in the following example:

[source,xml]
----
<ssl id="defaultSSLConfig" keyStoreRef="defaultKeyStore" trustStoreRef="defaultTrustStore" />
<keyStore id="defaultTrustStore" location="${javaKeystoreLocation}" type="JKS" password="changeit" />
<mpJwt id="mympjwt" issuer="https://example.com"
   jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk"/>
----

The `id` attribute in the `keyStore` element specifies the `“defaultTrustStore”` value to configure a Truststore within the Keystore.  A Truststore contains the certificates that are used to validate the requests that are sent to applications with JSON Web Tokens. The `ssl` element is used to specify how the application validates the SSL connection to a server. Within the `ssl` element, the `id=defaultSSLconfig`  attribute sets the SSL configuration as the default SSL configuration for the server that the application connects to. The `trustStoreRef=“defaultTrustStore”` attribute configures the `ssl` element to reference the Truststore so that the application recognizes the Truststore when it attempts to connect to the server. The `jwksUri="https://localhost:19443/jwt/ibm/api/myBuilder/jwk”` attribute specifies the JWK endpoint URL that the server uses to obtain the public keys from to verify the JWT.

=== Configure the authentication method with MicroProfile JWT

By default, if the MicroProfile JWT feature is configured, all authorized requests from applications must include a valid JSON Web Token in the HTTP header of the API. To modify the default behavior to require JSON Web Tokens in only some applications, you can add the `ignoreApplicationAuthMethod=“false”` attribute to the `mpJwt` element as shown in the following example:

[source,xml]
----
<mpJwt ignoreApplicationAuthMethod=“false”/>
----

After you modify the authorization behavior, you can use either of two options to configure applications to use MicroProfile JWT as a login method. In the API, you can add an `@LoginConfig` annotation that contains the `authMethod = "MP-JWT"` attribute to specify MicroProfile JWT as the authentication method as shown in the following example:

[source,java]
----
@LoginConfig(authMethod = "MP-JWT", realmName = "MP-JWT")
----

You can also add `MP-JWT` to the `auth-method` element of the `web.xml` file to specify MicroProfile JWT as the authentication method in the `login-config` element as shown in the following example:

[source,xml]
----
<login-config> <auth-method>MP-JWT</auth-method> <realm-name>MP-JWT</realm-name></login-config>
----
