
== Examples

=== Slow and hung request threshold configuration
The request timing feature can track the duration of every request that comes into a system. You can configure the request timing feature to detect slow and hung requests. The request timing feature provides diagnostic information when the duration of any request exceeds the configured threshold.  The slow and hung request thresholds are configured by setting the `slowRequestThreshold` and `hungRequestThreshold` attributes within the `<requestTiming/>` element configuration in the `server.xml` file. Setting these attributes specifies a single slow and hung request threshold for all requests that are timed. The following example shows the `<requestTiming/>` element configuration with the embedded `<jdbcTiming/>` element configuration:
[source,xml]
----
<requestTiming slowRequestThreshold="10s" hungRequestThreshold="10m">
</requestTiming>
----

==== Customizing threshold configuration
You can also set different slow and hung request thresholds for different types of requests. An embedded `<servletTiming/>` or `<jdbcTiming/>` element configuration in the server.xml file overrides the configured slow and hung request thresholds that are defined in the `<requestTiming/>` element. A `<jdbcTiming/>` element configuration can set the slow and hung request threshold by datasource name, sql string, or both. The following example shows a `<jdbcTiming/>` element configuration that sets the slow and hung request threshold by datasource name:
[source,xml]
----
<requestTiming slowRequestThreshold="10s" hungRequestThreshold="10m">
  <jdbcTiming dataSourceName="testDBSource" slowRequestThreshold="500ms" hungRequestThreshold="5m"/>
</requestTiming>
----

The `<requestTiming/>` element configuration can also include the embedded `<servletTiming/>` element configuration for one specific servlet and one specific web application as shown in the following example:
[source,xml]
----
<requestTiming slowRequestThreshold="10s" hungRequestThreshold="10m">
  <servletTiming servletName="Arm10Servlet" hungRequestThreshold=”20s”/>
  <servletTiming appName="SecurityExchangeApp” hungRequestThreshold=”2h”/>
</requestTiming>
----

In both cases, the names are taken from the context information for the request, as reported by the https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#eventLogging-1.0.html[Event Logging feature]. The event log contains the type and context information for each request that was processed by the server. With type and context information, you can create a `<servletTiming/>` or `<jdbcTiming/>` element configuration in the `server.xml` file for the requests that require different threshold values.
