== Examples

=== Basic configuration

With the Logstash Collector feature, you can change the maximum number of characters that are allowed for the message field in a message or trace event or for the stack trace in an FFDC event. You can also limit the maximum number of events that are sent for each type of event per second. The following example sets the `maxFieldLength` parameter to 3000 characters and sets the `maxEvents` parameter to 10 events per second in the `logstashCollector` element.
This example configuration also sets two `tag` elements in the `logstashcollector` element to add custom tags that decorate events within the application:

[source,xml]
----
<logstashCollector
	source="message,trace,garbageCollection,ffdc,accessLog,audit"
	hostName="localhost"
	port="5043"
	sslRef="mySSLConfig"
	maxEvents="10"
	maxFieldLength="3000">
	<tag>serverRackA5</tag>
	<tag>billingAppTeam</tag>
</logstashCollector>
----

For more information, see xref:ROOT:forwarding-logs-logstash.adoc[Forwarding logs and events to Logstash with Logstash collector].


=== Replacing default HTTP access log fields

With the Logstash Collector feature, you can use the `jsonAccessLogFields` attribute to replace the default set of HTTP access log fields with a set of custom fields.
The following example shows a configuration to replace the default HTTP access log fields with custom fields that are specified by the `logFormat` attribute. xref:ROOT:access-logging.adoc[HTTP access logging] must be enabled for the Logstash collector feature to collect access log events.

[source,xml]
----
<httpEndpoint httpPort="9080" httpsPort="9443" id="defaultHttpEndpoint">
    <accessLogging logFormat='%R{W} %u %{my_cookie}C %s'/>
</httpEndpoint>
<logstashCollector
    source="accessLog"
    jsonAccessLogFields="logFormat">
</logstashCollector>
----
