== Examples

=== Default configuration

When the SAML Web Single Sign-on feature is enabled, Open Liberty provides a default SAML configuration with an ID value of `defaultSP`.
The SAML Web Single Sign-on feature activates the following two endpoints:

- `\https://<hostname>:<sslport>/ibm/saml20/defaultSP/acs`
+
The AssertionConsumerService URL endpoint on the service provider point of contact server receives assertions from the identity provider (IdP).

- `\https://<hostname>:<sslport>/ibm/saml20/defaultSP/samlmetadata`
+
The service provider metadata URL endpoint provides configuration information for the service provider.
You can download the metadata for the service provider from a browser with the service provider metadata URL.
You can also provide the service provider metadata URL to the SAML identity provider to establish a federation between the service provider and identity provider. The IdP metadata file must be named idpMetadata.xml and copied to the `resources/security` directory on the server.

The issuer name for SAML assertion is used as the security realm, and the `NameID` value is used as the principal to create an authenticated subject from the SAML assertion.
The SAML `AuthnRequest` instance is signed with a private key in the default keystore of the server if the `KeyStoreRef` attribute  is not specified. If the `keyAlias` attribute is not configured, then `samlsp` is the default key alias. If the `keyAlias` attribute is not configured and the keystore only contains one private key, the private key is used in the signature.

=== Customize the default configuration

You can customize the `defaultSP` service provider by adding a `samlWebSso20` element to your `server.xml` file and specifying a custom attribute configuration, as shown in the following example.

[source,xml]
----
<samlWebSso20  id="defaultSP"
       spHostAndPort="https://<host>:<port>"
       keyStoreRef="samlKeyStore"
       ... />
----

For more information about the available configuration attributes, see config:samlWebSso20[].

=== Specify a custom service provider instance

If you create a new service provider instance and the `defaultSP` default instance is no longer required, you must explicitly disable the `defaultSP` instance. To disable the default service provider instance and specify a new instance, add code that is similar to the following example to your `server.xml` file:

[source,xml]
----
<samlWebSso20 id="defaultSP" enabled="false"/>

<samlWebSso20 id="newSP" allowCustomCacheKey="false"/>
----

You must specify a URL-safe String that is not null as the ID value. If the `id` attribute is missing, then the configuration element is ignored.

You can create one or more  `samlWebSso20` elements with different ID values. For example, if you create a new element with `mySP` as the ID, you effectively create a new SAML service provider instance that has the following `AssertionConsumerService` URL: `https://<hostname>:<sslport>/ibm/saml20/mySP/acs`.

You can also configure multiple SP and IdP federation partners by creating multiple `samlWebSso20` elements and associating each of them with a  unique config:authFilter[] element. All `authFilters` must exclude each other. When multiple `samlWebSso20` elements are configured, each element can implement single-sign-on with its specified federated identity provider and according to its own authentication policy and consuming rules. For more information, see the following example.

=== Configure SAML authentication for a subset of requests

You can configure an authentication filter to specify whether certain requests for protected resources are authenticated with SAML.
If the request meets the criteria that are specified in the authentication filter, then the request can authenticate with SAML to access the protected resource.

[source, xml]
----
<samlWebSso20 id="mySP" authFilterRef="myAuthFilter".../>

<authFilter id="myAuthFilter">
         <requestUrl id="myRequestUrl" urlPattern="/SimpleServlet" matchType="contains"/>
</authFilter>
----

In the example, request URLs that contain the `/SimpleServlet` pattern are authenticated by using JWT SSO authentication.
If the SAML Web Single Sign-On feature is enabled but no authentication filter is configured, all unauthenticated requests are processed by SAML authentication.

You can also configure multiple SP and IdP federation partners by creating multiple `samlWebSso20` elements and associating each of them with a  unique config:authFilter[] element. All `authFilters` must exclude each other. When multiple `samlWebSso20` elements are configured, each element can implement single-sign-on with its specified federated identity provider and according to its own authentication policy and consuming rules. The follwing example shows a two mutually exclusive SAML configurations, each of which uses a different authentication filter to control the kinds of requests that it processes.

[source, xml]
----
<samlWebSso20 id="mySP" authFilterRef="myAuthFilter".../>
<samlWebSso20 id="altSP" authFilterRef="altAuthFilter".../>

<authFilter id="myAuthFilter">
         <requestUrl id="myRequestUrl" urlPattern="/SimpleServlet" matchType="contains"/>
         <requestUrl id="excludeRequestUrl" urlPattern="/example" matchType="notContain"/>
</authFilter>

<authFilter id="altAuthFilter">
        <requestUrl id="altRequestUrl" urlPattern="/example" matchType="contains"/>
         <requestUrl id="exclude2RequestUrl" urlPattern="/SimpleServlet" matchType="notContain"/>
</authFilter>
----

For more information, see xref:ROOT:authentication-filters.adoc[Authentication filters].

=== Configure a PKIX trust engine

The default trust engine for SAML on Open Liberty is the Metadata trust engine, which validates a signature against information that is provided in the configured IdP metadata. Alternatively, you can use a Public Key Infrastructure X.509 (PKIX) trust engine by specifying the `PKIXTrustEngine` element and defining the proper `trustAnchorRef` value, as shown in the following example.

[source,xml]
----
<samlWebSso20  id="defaultSP">
  <PKIXTrustEngine trustAnchorRef="samlKeyStore" />
</samlWebSso20>
----

The `trustAnchorRef` attribute specifies a reference to top-level `keyStore` element for a keystore that contains the public key to verify the signature of the SAML response and assertion.

=== Configure support for service provider-initiated unsolicited single sign-on

The Open Liberty SAML SP uses the configured IdP metadata to service a solicited SAML `AuthnRequest` instance. Open Liberty SP can also redirect unauthenticated requests to a preconfigured login application without using an `AuthnRequest` instance. This scenario is useful if a business application performs pre-authentication processing before a user can authenticate to the SAML IdP, or if the SAML IdP must be hidden from the Open Liberty SP.

To configure this scenario, set the `loginPageURL` value to a URL that can instruct a user to authenticate to the SAML IdP, as shown in the following example.

[source,xml]
----
<samlWebSso20  id="defaultSP" loginPageURL="https://example.com"/>
----

=== Use a LTPA cookie to maintain an authenticated session.

After SAML assertion is verified and processed, the Open Liberty SAML SP maintains an authenticated session between the browser and the SP without using an LTPA cookie. The authenticated session timeout is set to the value for `SessionNotOnOrAfter` in the `<saml:AuthnStatement>` instance. If this value is not presented, the timeout is set to the value for the `sessionNotOnOrAfter` attribute as configured in the `server.xml` file, with the default being 120 minutes. The session cookie name is automatically generated. You can customize the cookie name by using the attribute spCookieName to specify the wanted name.
If you want the Open Liberty SP to create an LTPA cookie from the SAML assertion and use the LTPA cookie for subsequent authentication requests, set the  `disableLtpaCookie` attribute to `false`. If you want to share this LTPA cookie with other servers, you must also set the add the configuration  `allowCustomCacheKey` attribute to `false`, as shown in the following example.

[source,xml]
----
<samlWebSso20  id="defaultSP" disableLtpaCookie="false" allowCustomCacheKey="false"/>
----

If you set both the `disableLtpaCookie` and `allowCustomCacheKey` attributes to `false`, ensure that a SAML user name is not directly authenticating to an on-premises user registry that prevents a user from having two accounts.

== Configure the service provider for Single Logout

The Open Liberty SAML Single Logout Service URL takes the following format: `https://<hostname>:<sslport>/ibm/saml20/<SP configuration ID>/slo`. You can find this URL and can be found from the Open Liberty SP metadata URL, which is `https://<hostname>:<sslport>/ibm/saml20/<SP configuration ID>/samlmetadata`.

For IdP-initiated single logout, no additional configuration step is required. Open Liberty SP listens to the logout request on the SingleLogoutService URL, and will automatically respond to the single logout request.

However, Open Liberty also supports service provider-initiated single logout. When you set the `spLogout` property to `true`, as shown in the following example, both the `ibm_security_logout` URL and the `HttpServletRequest.logout()` method are upgraded to perform SAML single logout.

[source,xml]
----
<samlWebSso20  id="sp2" ... spLogout="true"/>
----
