== Examples

* <<inmemory, Enable in-memory identity stores>>
* <<authmech, Configure a custom authentication mechanism handler>>
* <<builtin, Use multiple built-in authentication mechanisms>>


[#inmemory]
=== Enable in-memory identity stores

By default, the in-memory identity store is disabled for security reasons. To use the @InMemoryIdentityStoreDefinition annotation within your application for testing or development, you must explicitly set the allowInMemoryIdentityStores attribute to true on the webAppSecurity element in the `server.xml` file:

[source,xml]
----
<webAppSecurity allowInMemoryIdentityStores="true"/>
----

Once enabled, you can define users, passwords, and groups directly in your application code. The following example shows an in-memory identity store definition with multiple credentials:

[source,java]
----
@InMemoryIdentityStoreDefinition( 
    priority = 10, useFor = {VALIDATE, PROVIDE_GROUPS}, value = { 
        @Credentials(callerName = "jasmine", password = "secret1", groups = { "caller", "user" } ), 
        @Credentials(callerName = "bill", password = "{xor}LDo8LTorbg==", groups = { "foo", "bar" }), 
        @Credentials(callerName = "frank", groups = { "user" }, password = "{hash}ARAAAAAUUEJLREYyV...x2w==") 
        } 
)
----


[#authmech]
=== Configure a custom authentication mechanism handler

Jakarta Security 4.0 allows you to specify multiple HTTP authentication mechanisms within a single application. If you use custom qualifiers to differentiate between multiple mechanisms of the same type, you must provide a custom HttpAuthenticationMechanismHandler implementation to define the selection logic.

The following example shows a custom handler that routes requests to different authentication mechanisms based on the request URI:

[source,java]
----
@ApplicationScoped
public class CustomSecurityHandler implements HttpAuthenticationMechanismHandler {

@Inject @Admin
private HttpAuthenticationMechanism adminHAM; 

@Inject @User
private HttpAuthenticationMechanism userHAM; 

@Inject @BasicAuthenticationMechanism 
private HttpAuthenticationMechanism defaultHAM;

@Override
AuthenticationStatus validateRequest(HttpServletRequest request, HttpServletResponse response, HttpMessageContext httpMessageContext) throws AuthenticationException {
String path = request.getRequestURI();

// route to appropriate mechanism based on path
if (path.startsWith("/admin")) {
    return adminHAM.validateRequest(request, response, httpMessageContext);
} else if (path.startsWith("/user")) {
    return userHAM.validateRequest(request, response, httpMessageContext);
} 
// Default behavior
return defaultHAM.validateRequest(request, response, httpMessageContext);
}
}
----


[builtin]
=== Use multiple built-in authentication mechanisms

You can specify multiple built-in mechanisms, such as Basic and OpenID Connect, within the same application code. The container provides a default prioritization algorithm to select the mechanism if a custom handler is not provided. The following example shows an application class configured with three different authentication mechanism types:

[source,java]
----
@BasicAuthenticationMechanismDefinition(realmName = "basicAuth")

@OpenIdAuthenticationMechanismDefinition(
    providerURI = "https://samples.auth0.com/authorize",
    clientId="your_client_id",
    redirectURI= "https://openidconnect.net/callback",
    scope="openid profile email",
    responseType="code")

@FormAuthenticationMechanismDefinition(
    loginToContinue = @LoginToContinue(errorPage = "/login-error.html",
    loginPage = "/login.html"))

public class MySecureApplication extends Application { }
----
