== Examples

The OpenID Connect Provider (OP) feature can be configured to manage user authentication for OpenID Connect (OIDC) clients and microservices during development.
The OP feature can work directly with a user registry, such as LDAP, or act as an identity broker and delegate to another security provider.
In production, the application uses a cloud-hosted SSO provider.

Any user that is authorized to use OIDC must also be mapped to the authenticated OAuth role.

=== Managing OAuth clients with `localStore`

The following example shows how to create a basic configuration to run an OpenID Connect Provider.
This configuration is especially useful during development and testing before deployment to the cloud, where the application typically uses a cloud-based SSO provider instead.
The example uses a simple link:/docs/ref/feature/#appSecurity-3.0.html[basic registry], which is defined in the server configuration, to manage a single user:

[source,xml]
----
<keyStore id="defaultKeyStore" password="keyspass" />

<basicRegistry id="basic" realm="customRealm">
    <user
      name="demouser"
      password="demopassword" />
</basicRegistry>

<openidConnectProvider id="OP"
    oauthProviderRef="OAuth"
    signatureAlgorithm="RS256" keyStoreRef="defaultKeyStore"
    jwkEnabled="true">
</openidConnectProvider>

<oauthProvider id="OAuth" tokenFormat="mpjwt" >
    <localStore>
      <client displayname="RP" enabled="true"
            name="RP" secret="thesecret"
            scope="openid profile email"
            preAuthorizedScope="openid profile email">
            <redirect>https://localhost:19443/oidcclient/redirect/RP</redirect>
      </client>
    </localStore>
</oauthProvider>

<oauth-roles>
    <authenticated>
        <special-subject type="ALL_AUTHENTICATED_USERS" />
    </authenticated>
</oauth-roles>
----

The example configuration uses `localStore` to store client data and token status.
Thus, all client data and token status are held in memory, which works for test and development purposes.
However, if you want to reconfigure the server, the `localStore` might be cleared so it is not suitable to use for production purposes.
A database must be used instead.

If you use a database, replace the `localStore` section with link:https://www.openliberty.io/docs/ref/feature/#jdbc-4.3.html[JDBC] database configuration.
When you use a database, clients are not specified in the `server.xml` file.
Instead, they are added to the database through the registration endpoint.

In the example, `jwkEnabled` attribute for the `openidConnectProvider` element with the `id` attribute OP is set to true.
The `signatureAlgorithm` attribute specifies the signature algorithm RS256 to sign the ID token.
The `keyStoreRef` attribute is set to a default value `opKeyStore`.
The `oauthProviderRef` attribute references the `oauthProvider` element with the `id` attribute OAuth.
The `name` attribute of is set to the default `displayName` attribute RP.
The `tokenFormat` attribute is `mpjwt`, which is microprofile standardized format.
The `preAuthorizedScope` attribute points to the pre-approved `scope` attribute value of openid profile email.





=== Managing OAuth clients with an authenticated database

The following example uses a database as the store:

[source, xml]
----

<oauthProvider id="OAuth" tokenFormat="mpjwt" >
<localStore>
  <client displayname="RP" enabled="true"
        name="RP" secret="thesecret"
        scope="openid profile email"
        preAuthorizedScope="openid profile email">
        <redirect>https://localhost:19443/oidcclient/redirect/RP</redirect>
  </client>

  <clientManager>
     <user name="testuser" />
     <group name="oidcadmin" />
  </clientManager>
</localStore>
----


When you connect to a database, users in the `clientManager` role can add or modify clients by accessing the registration endpoint.
In the example the `clientManager` role is granted to the user `testuser` or members of the `oidcadmin` group.
