
== Examples

=== Bind constants into the default JNDI namespace

When you define a variable as a Java constant, you set a fixed value for it that cannot be changed. You can bind these constants into the default JNDI namespace, which provides a simple and portable way to pass server configuration values into an application.

The following example shows how to bind constants into the JNDI namespace:

[source,xml]
----
<jndiEntry jndiName="schoolOfAthens/defaultAdminUserName" value="plato" />
----

In this example, `plato` is specified as the value for the `schoolOfAthens/defaultAdminUserName` object. This constant is available to an application at run time through the JNDI namespace.

You can look up constants by calling the `dolookup()` method  in your application code, as shown in the following example:

[source,java]
----
String defaultAdminUserName = InitialContext.doLookup("schoolOfAthens/defaultAdminUserName");
----

In this example, the `dolookup()` method returns the value of the `schoolOfAthens/defaultAdminUserNameo` object to the application. As specified in the previous example, that value is the string `plato`.

The type of the object is determined by interpreting the value that is stored in the `jndiEntry` element as a Java literal string or primitive data type. If the parsing fails, the exact value is provided as an unmodified string. For more information, see https://docs.oracle.com/javase/7/docs/api/javax/naming/InitialContext.html[the java.lang.Object class].


=== Bind URLs into the JDNI namespace

You can bind an instance of the Java URL class into the JNDI namespace to connect applications on the server with a resource on the internet. The following example shows how to bind an instance of the `java.net.URL` class into the JNDI namespace:

[source,xml]
----
<jndiURLEntry jndiName="urls/openLiberty" value="https://www.openliberty.io" />
----

In this example, the namespace supplies the `https://www.openliberty.io` URL as the value for the `openLiberty` `java.net.URL` class.
