// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Defines the default port numbers of Open Liberty features and an example of how you can override the default port in your server configuration.
:seo-description: Defines the default port numbers of Open Liberty features and an example of how you can override the default port in your server configuration.
:page-layout: general-reference
:page-type: general
= Default port numbers

The Open Liberty kernel and some Open Liberty features use default TCP/IP port numbers. You can override the default port numbers by specifying a different port number in your server configuration.

== Runtime environment port numbers


The following table defines the default port numbers of Open Liberty features and provides examples of how you can override default ports in your server configuration.
[cols="a,a",width="100%"]
|===
|Feature|Default port and configuration example

|feature:enterpriseBeansRemote[display=Jakarta Enterprise Beans Remote]

| - IIOP port: 2809
  - IIOP/SSL port: 9402

To modify the default port, specify the `iiopPort` attribute for the `iiopEndpoint` element and the `iiopsPort` attribute for the `iiopsOptions` subelement in your `server.xml` file, as shown in the following example:
----
<iiopEndpoint id="defaultIiopEndpoint" iiopPort="2809">
   <iiopsOptions iiopsPort="9402" sslRef="defaultSSLConfig"/>
</iiopEndpoint>
----

For more information, see config:iiopEndpoint[].


|feature:servlet[display=Jakarta Servlet]

| - HTTP port: 9080
  - HTTPS port: 9443

To modify the default ports, specify the `httpPort` or `httpsPort` attributes for the `httpEndpoint` element in your `server.xml` file, as shown in the following example:
----
<httpEndpoint id="defaultHttpEndpoint"
    httpPort="9082"
    httpsPort="9445" />
----
For more information about HTTP endpoints, see config:httpEndpoint[display=HTTP Endpoint].

 |feature:sipServlet[display=SIP Servlet]

 | - TCP port: 5060
   - TLS port: 5061
   - UDP port: 5060

To modify the default ports, specify the `sipTCPPort`,`sipUDPPort`, or `sipTLSPort` attributes for the `sipEndpoint` element in your `server.xml` file, as shown in the following example:
----
<sipEndpoint id="defaultSipEndpoint"
   sipTCPPort="5062"
   sipUDPPort="5062"
   sipTLSPort="5063" />
----
For more information, see config:sipEndpoint[].

|feature:wasJmsServer[display=Message Server]

|   - Incoming unsecure port: 7276
    - Incoming secure port: 7286

To modify the default ports, specify the `wasJmsPort` or `wasJmsSSLPort` attributes for the `wasJmsEndpoint` element in your `server.xml` file, as shown in the following example:
----
<wasJmsEndpoint id="InboundJmsEndpoint"
   wasJmsPort="7278"
   wasJmsSSLPort="7288">
</wasJmsEndpoint>
----
For more information about WAS JMS endpoints, config:wasJmsEndpoint[display=WAS JMS Endpoint].

|feature:kernel[display=Liberty Kernel]

| For the command port, the Open Liberty server acquires a temporary port that is used by the command listener. You can configure this port in the `bootstrap.properties` file.

----
command.port=1
----
The default value for the `command.port` is `0`.

For more information, see xref:bootstrap-properties.adoc#command-port[Set the command port].
|===

For more information, see xref:config/server-configuration-overview.adoc[Server Configuration overview].
