// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: You can customize the Open Liberty environment by using specific variables
:seo-title: Default environment variables
:seo-description: You can customize the Open Liberty environment by using specific variables to support the placement of product binary files and shared resources in the read-only file systems.
:page-layout: general-reference
:page-type: general
= Default environment variables

The Open Liberty environment variables in the following list can be configured in the https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/reference/config/server-configuration-overview.html#server-env[server.env] file to customize the Liberty environment.
The `${wlp.install.dir}` configuration variable has an inferred location that is always set to the parent of the directory that contains the launch script.

[%header]
.Open Liberty default environment variables
[cols="a,a",width="100%"]
|===
|Environment Variable|Description

|JAVA_HOME

| A list of JVM command line options,
  for example, system properties or `-X` parameters.
  The value will be expanded by cmd.exe.

|LOG_DIR

| The log file directory.
  The default value is `%WLP_OUTPUT_DIR%\serverName\logs`.

|LOG_FILE

| The log file name.
  This log file is only used if the server is run in the
  background via the start action.

|WLP_USER_DIR

| The `user/custom` configuration directory that is used to store
  shared and server-specific configuration.
  See the  `README.TXT` file for details about shared resource locations.
  A server configuration is at the `%WLP_USER_DIR%\servers\serverName` location.
  The default value is the user directory in the install directory.

|WLP_OUTPUT_DIR

| The directory that contains output files for defined servers.
  This directory must have both read and write permissions for
  the user or users that start servers.
  By default, the server output logs and work area are stored
  at the `%WLP_USER_DIR%\servers\serverName` location
  alongside configuration and applications.
  If this variable is set, the output logs and work area
  are stored at the `%WLP_OUTPUT_DIR%\serverName` location.

|WLP_DEBUG_ADDRESS

| The port to use when running the server in debug mode.
  The default value is `7777`.

| WLP_DEBUG_SUSPEND

| Whether to suspend the JVM on startup or not. This can be
  set to `y` to suspend the JVM on startup until a debugger attaches,
  or set to `n` to startup without waiting for a debugger to attach.
  The default value is `y`.

| WLP_DEBUG_REMOTE

| Whether to allow remote debugging or not. This can be set
  to `y` to allow remote debugging. By default, this value is not
  defined, which does not allow remote debugging on newer JDK/JREs.
