// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty supports the full Jakarta Platform, Enterprise Edition (Jakarta EE). The Jakarta EE Javadoc documentation describes the packages and classes that are provided by the Jakarta EE API.
:seo-title: Jakarta EE API Javadoc documentation
:seo-description: Open Liberty supports the full Jakarta Platform, Enterprise Edition (Jakarta EE). The Jakarta EE Javadoc documentation describes the packages and classes that are provided by the Jakarta EE API.
:page-layout:
:page-type:
= Jakarta EE API

Open Liberty supports the full Jakarta Platform, Enterprise Edition (Jakarta EE). The Jakarta EE Javadoc documentation describes the packages and classes that are provided by the Jakarta EE API.

To view API documentation for Jakarta EE, select a Jakarta EE version from the table of contents.

Jakarta EE is an open source Java platform. Before Jakarta EE version 8, the platform was owned by the Oracle corporation and known as Java, Enterprise Edition (https://www.oracle.com/java/technologies/java-ee-glance.html[Java EE]). Open Liberty also supports Java EE versions 7 and 8. For Java EE API documentation, see xref:java-ee-api.adoc[Java EE API]. For more information about Java EE, Jakarta EE, and Open Liberty, see xref:ROOT:jakarta-ee.adoc[Jakarta EE overview]. 

