// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty supports the full Java™ Platform, Enterprise Edition (Java EE), versions 7 and 8. The Java EE Javadoc documentation describes the packages and classes that are provided by the Java EE API.
:seo-title: Java EE API Javadoc documentation
:seo-description: Open Liberty supports the full Java™ Platform, Enterprise Edition (Java EE), versions 7 and 8. The Java EE Javadoc documentation describes the packages and classes that are provided by the Java EE API.
:page-layout:
:page-type:
= Java EE API

Open Liberty supports the full Java™ Platform, Enterprise Edition (Java EE), versions 7 and 8. The Java EE Javadoc documentation describes the packages and classes that are provided by the Java EE API.

To view API documentation for Java EE, select a Java EE version from the table of contents.

Open Liberty also supports the xref:jakarta-ee-api.adoc[Jakarta EE Platform], which is the migration of Java EE from the https://www.jcp.org/en/home/index[Java Community Process] to the open source https://www.eclipse.org/[Eclipse Foundation]. For Jakarta EE API documentation, see xref:jakarta-ee-api.adoc[Jakarta EE API]. For more information about Java EE, Jakarta EE, and Open Liberty, see xref:ROOT:jakarta-ee.adoc[Jakarta EE overview]. 

