// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Two key sets of changes might impact the existing configuration when you upgrade from MicroProfile Config 1.x to 2.0.
:seo-title: Differences between MicroProfile Config versions
:seo-description: Two key sets of changes might impact the existing configuration when you upgrade from MicroProfile Config 1.x to 2.0.
:page-layout: general-reference
:page-type: general
= Differences between MicroProfile Config versions

Two key sets of changes might impact the existing configuration when you upgrade from MicroProfile Config 1.x to 2.0:

== SmallRye implementation of the specification

Open Liberty implements the MicroProfile Config specification for application configuration from different configuration sources.
In previous versions, Open Liberty implemented the specification in its own codebase.
However, for MicroProfile Config 2.0, Open Liberty consumes SmallRye implementation of the specification to produce the mpConfig 2.0 feature.
Any MicroProfile Config functionality that Open Liberty implemented beyond the scope of the specification is lost from the mpConfig 1.x to 2.0 feature.


* Converters for the `AtomicInteger` and `AtomicLong` properties are no longer provided because these properties are not widely used.
Converting an injected value to one of these types of properties might throw the exception `SRCFG02006: The property yourProperty cannot be converted to class java.util.concurrent.atomic.AtomicInteger/AtomicLong`.
If you need to convert a `String` type to `AtomicInteger` or `AtomicLong` type, you can convert to `Integer` or `Long` type.
Then, create an `AtomicInteger` or `AtomicLong` type from the `Integer` or `Long` type. Alternatively, you can create your own Converter for the `AtomicInteger` and `AtomicLong` properties.

** In the mpConfig 1.x to 2.0 feature, Converters are provided for `AtomicInteger` and `AtomicLong` properties.

* In the mpConfig 2.0 feature, caching is discontinued.
  Values that are looked up from MicroProfile Config are no longer cached.

** In the mpConfig 1.x to 2.0 feature, requests made for the same configuration key return the same object up to 5-seconds duration, without calling the configuration sources.


* When a converter for a specific type is not available, converters of its subtypes cannot be used.

** Converters for subtypes are available in the mpConfig 1.x to 2.0 feature.
For example, in the mpConfig 1.x to 2.0 feature, a Converter that is registered for the type `Dog` extends a type `Animal`.
When a type `Animal` is injected, the `Dog` Converter is used,

[source,java]
----
@Inject
@ConfigProperty(name = "DOG_KEY")
Animal myAnimal;
----

== Incompatible changes

Changes in the MicroProfile Config specification from 1.x to 2.0 introduced some incompatibility changes.
Some of these changes are by-products of new features, and others are intentional specification clarifications and changes.

* `ConfigSource.getPropertyNames()` is no longer a default method that is provided by the specification.
Any custom configuration sources that use this method need to implement the method, otherwise a `java.lang.AbstractMethodError` is thrown.

** In MicroProfile Config 1.x to 2.0, `ConfigSource.getPropertyNames()` method is provided by the specification, by default.

* Property expression is a new feature, which might impact existing configurations.
From MicroProfile Config 2.0, configuration properties can include references to other configuration properties by using the following syntax: `${anotherConfigPropertyName}`.
As such, any configuration properties that contain values with property expression syntax might behave differently.
The number of recursion lookups is limited for composed expressions.
Implementations are generally limited to 5, but can be higher.
When the number of allowed lookups exceeds the limit, an `IllegalArgumentException` error is thrown.
Variable replacement in config values is supported through the property expression feature.
This replacement allows config values to reference other config property values by using the `${}` syntax with a maximum recursive depth of 32.

** The property expression feature is not available in MicroProfile Config 1.x to 2.0.

* Configuration property value conversion rules are updated.
The empty value and other special characters are no longer valid for particular return types.
for example, attempting to call `getValue()` on an injected empty value ("") for type String throws a `java.util.NoSuchElementException` error.

** In MicroProfile Config 1.x to 2.0, empty value and other special characters were valid for particular return types.
