// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Signature files (*.sig) are produced for every package of an Open Liberty release. You can verify these signature files by using the corresponding public key that is provided on the IBM DHE download site.
:seo-description: Signature files (*.sig) are produced for every package of an Open Liberty release. You can verify these signature files by using the corresponding public key that is provided on the IBM DHE download site.
:page-layout: general-reference
:page-type: general

= Verifying Open Liberty release packages

Signature files (*.sig) are produced for every package of an Open Liberty release. You can verify these signature files by using the corresponding public key that is provided on the IBM DHE download site.

For example, IBM uses its private key to digitally sign the latest Open Liberty release. You can use the Open Liberty xref:https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/sign/public_keys/WebSphereLiberty_06-02-2021.pem[public key] to check the signature, verify that the Open Liberty release package was released by IBM and that it was not modified since its release.

To verify an Open Liberty release, you must download the following files.
* the xref:https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/sign/public_keys/WebSphereLiberty_06-02-2021.pem[public key]
* An Open Liberty `*.zip` package
* the `*.sig` file for the release package that you want to verify.

After you download the files, you can run the following xref:https://www.openssl.org/docs/man1.1.1/man1/openssl-dgst.html[OpenSSL command] from the command line to verify the package.

[source,sh]
----
openssl dgst -sha256 -verify WebSphereLiberty_06-02-2021.pem -signature openliberty-javaee8-21.0.0.8.zip.sig openliberty-javaee8-21.0.0.8.zip
----

This example uses the `WebSphereLiberty_06-02-2021.pem` public key file and `openliberty-javaee8-21.0.0.8.zip.sig` signature file to verify the `openliberty-javaee8-21.0.0.8.zip` release package.
Replace these values according to the package that you want to verify. If the verification is successful, the command produces the following console output.

[source,sh]
----
Verified OK
----

== Verify Liberty packages on Maven Central

To verify the packages use the following instructions:

[source,sh]
----
//GPG signing Verification
// download public key to local machine

>gpg2 --keyserver hkp://keyserver.ubuntu.com --recv-keys 46102B8E
(46102B8E is the key id for the WebSphere Liberty public key)

// Editing trust of key owner
gpg2 --edit-key "WebSphere Liberty"
   gpg> trust


      Set trust 1-5(should be 5)
// verify file

gpg2 --verify openliberty-runtime-21.0.0.7.zip.asc
----
