// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty includes tools for creating an XSD schema for the `server.xml` file.
:page-layout: general-reference
:seo-title: XSD schema for the server.xml file
:seo-description: Open Liberty includes tools for creating an XSD schema for the `server.xml` file.
:page-type: general
= XSD schema for the server.xml file

Open Liberty includes tools that can generate an XSD schema for autocompletion to edit the `server.xml` file.

== Generating XSD schema for Open Liberty with the Maven plug-in

For Maven based projects, run the Maven package command on your application to generate the`./target/liberty/wlp/bin/tools` directory that contains `ws-schemagen.jar` file.
Generate the XSD schema by running the following command in the same directory where `wlp` directory exists:

`java -jar ./wlp/bin/tools/ws-schemagen.jar ./src/main/liberty/config/server.xsd`

Set the location of the generated XSD schema to the same directory the `server.xml` file exists.
The default location for the `server.xml` file for Open Liberty is `src/main/liberty/config`.

The command generates XSD schema `server.xsd` file in the current directory.

== Generating XSD schema for Open Liberty

Download the Open Liberty files and extract the archive, which can be found in the `wlp` directory.
Generate the XSD schema by running the following command in the same directory where `wlp` directory exists:

`java -jar ./wlp/bin/tools/ws-schemagen.jar server.xsd`

The command generates XSD schema `server.xsd` file in the current directory.

You can now can then validate your `server.xml` file in any IDE of your choice.

== Adding schema location to the server tag in the `server.xml` file

After you generate the XSD schema, add the schema location to the server tag in the `server.xml` file as shown in the following snippet:

[source,xml]
----
<server
 description="my_server"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="server.xsd">
----


This article was inspired by a link:https://yeti-it.hr/blog[blog post] by Open Liberty user on the YETI IT blog.
