// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty includes tools for creating an XSD schema for the `server.xml` file.
:page-layout: general-reference
:seo-title: XSD schema for the server.xml file
:seo-description: Open Liberty includes tools for creating an XSD schema for the `server.xml` file.
:page-type: general
= XML schema for the server.xml file

The XML Schema Definition (XSD) language is a markup language that defines the structure and data types of XML documents.
Open Liberty includes tools to create an XSD schema file that you can use to validate your `server.xml` file.

== Generate an XML schema for your Open Liberty server.xml file

Create the XML schema by running the following `java -jar` command from the `_path_to_liberty_/wlp` directory:

[subs=+quotes]
[source,sh]
----
java -jar ./bin/tools/ws-schemagen.jar ./usr/servers/_serverName_/server.xsd
----

In this example, the command creates the XML schema `server.xsd` file for the _serverName_ server in the same directory as the `server.xml` file.

== Create XML schema for Open Liberty

Download the Open Liberty files and extract the archive, which can be found in the `wlp` directory.
Create the XML schema by running the following command in the same directory where the `wlp` directory exists:

[source,xml]
----
java -jar ./wlp/bin/tools/ws-schemagen.jar server.xsd
----

The command creates the XML schema `server.xsd` file in the location that is set in the command.
You can now validate the structure of your `server.xml` file in any IDE of your choice.


== Add schema location to the server.xml file

After you create the XSD schema, add the schema location to the `xsi : noNamespaceSchemaLocation` attribute in the server element of the `server.xml` file as shown in the following snippet:

[source,xml]
----
<server
 description="my_server"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="server.xsd">
----

The schema location is set to `server.xsd` because the example command saved it in the same directory as the `server.xml` file.
If you specify a different path for the output file, set the `noNamespaceSchemaLocation` attribute to include the path to the `server.xsd` file.
You can now validate the structure of your `server.xml` file in any IDE of your choice.

This article was inspired by a link:https://yeti-it.hr/blog?id=1[blog post] by an Open Liberty user on the YETI IT blog.
