// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-description: Open Liberty includes tools for creating an XSD schema for the `server.xml` file.
:page-layout: general-reference
:seo-title: XSD schema for the server.xml file
:seo-description: Open Liberty includes tools for creating an XSD schema for the `server.xml` file.
:page-type: general
= XSD schema for the server.xml file

Open Liberty includes tools for creating an XSD schema for the `server.xml` file.
The Open Liberty binary distribution comes with a tool that can generate an XSD schema.
You can also generate an XSD schema for embedded Open Liberty with the Liberty Maven plug-in.

== Generating XSD schema for Open Liberty

Download the Open Liberty binary files and extract the archive, which can be found in the `wlp` directory.
Generate the XSD schema by running the following command in the same directory where `wlp` directory exists:

`java -jar ./wlp/bin/tools/ws-schemagen.jar server.xsd`

The command generates XSD schema `server.xsd` file in the current directory.

== Generating XSD schema for embedded Open Liberty with the Maven plug-in

For Maven based projects that use embedded Open Liberty, the `ws-schemagen.jar` file can be found in `./target/liberty/wlp/bin/tools` directory after you run the Maven package command.
Set the location of the generated XSD schema to the same directory the `server.xml` file exists.
The default location for the `server.xml` file for embedded Open Liberty is `src/main/liberty/config`.

Generate the XSD schema by running the following command in the same directory where `wlp` directory exists:

`java -jar ./wlp/bin/tools/ws-schemagen.jar ./src/main/liberty/config/server.xsd`

== Adding schema location to the server tag in the `server.xml` file

After you generate the XSD schema, add the schema location to the server tag in the `server.xml` file as shown in the following snippet:

[source,xml]
----
<server
 description="my_server"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="server.xsd">
----
