== Examples

=== Configure Liberty servers to persist session data with `JCache`

Following is an example to configure session persistence by using Hazelcast as the JCache provider:


[source,java]
----

  <library id="jCacheVendorLib">
    <fileset dir="${shared.resource.dir}/hazelcast" includes="hazelcast.jar"/>
  </library>

  <httpSessionCache libraryRef="jCacheVendorLib"
                    uri="file:${shared.resource.dir}/hazelcast/hazelcast.xml"/>

  <httpSession cloneId="${cloneId}"/>
----

If you configure multiple servers to persist session data to the same database, ensure the servers share the session management configuration.
Any other configuration is not supported.

The HTTP server plug-in uses the clone ID that is inserted into the response or request header to maintain session affinity between requests.
While the clone ID usually doesn't change, in Open Liberty the clone ID is generated when you start a server for the first time, and it is regenerated if you start the server with the `--clean option`.
For production use, manually assign a clone ID to ensure that the ID is stable and that request affinity is maintained. The clone ID must be unique for each server and consists of alphanumeric characters The clone ID is specified in step 2.

Any needed Hazelcast configuration, such as for security, can be provided in the `${shared.resource.dir}/hazelcast/hazelcast.xml` file.
